### PR TITLE
MultiBackend: Handle methods with no source specific params properly.

### PR DESCRIPTION
**Pull request by EreMaijala**
Continued from #2173.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @EreMaijala. Two questions:

1.) Is it worth adding anything to the test suite related to this functionality?

2.) Does this supersede #2173 or simply complement it? Wondering what should happen to that PR after this one is merged.

**Review by xmorave2 — APPROVED** [review]

**Comment by xmorave2** [comment]
> 2.) Does this supersede #2173 or simply complement it? Wondering what should happen to that PR after this one is merged.

For our use case it's enough to push one of these PRs, but I am not sure if it will work for everybody...

I do like @EreMaijala solution - it is clean from the code what is going on

**Comment by EreMaijala** [comment]
@demiankatz 

1.) Good point, I've now added a simple test to verify that supportsMethod works properly with loginIsHidden.

2.) I'd prefer this to supercede #2173. The problem with 2173 is that it has the potential to mask problems. The exception is there for a reason, just like in this case where it uncovered an issue when default driver is not set.

**Comment by demiankatz** [comment]
Thanks, @EreMaijala and @xmorave2 -- merging now!

**Pull request merged**
