### PR TITLE
Solr 8 upgrade

### PR DESCRIPTION
**Pull request by demiankatz**
This is a work in progress PR for upgrading to Solr 8.

TODO
- [x] Update all solrconfig.xml files
- [x] Fix SolrMarc compatibility issues (see https://github.com/solrmarc/solrmarc/pull/86 ; requires update to 3.4)
- [x] Update, test and merge browse handler (see https://github.com/vufind-org/vufind-browse-handler/pull/33)
- [x] Run full test suite
- [x] Close [VUFIND-1339](https://vufind.org/jira/browse/VUFIND-1339) when merging
- [x] Update changelog (note new Solr + SolrMarc versions) when merging

### CODE REVIEW

**Comment by demiankatz** [comment]
I'm just starting to set up the Solr 8 upgrade in preparation for VuFind 7.0. This is very much a work in progress. The first major problem appears to be an incompatibility between the current SolrMarc release and Solr 8.2. I have posted to the solrmarc-tech mailing list and will see what I can do to help resolve that problem before proceeding further here.

**Comment by demiankatz** [comment]
Also problematic -- the browse handlers will not build against Solr 8 as-is:

<pre>
Buildfile: /opt/vufind-browse-handler/build.xml

clean:
   [delete] Deleting directory /opt/vufind-browse-handler/build

setup:
    [mkdir] Created dir: /opt/vufind-browse-handler/build
    [mkdir] Created dir: /opt/vufind-browse-handler/build/deps
    [mkdir] Created dir: /opt/vufind-browse-handler/build/bundled-deps

setup-solr-deps:

unpack-solr-war:

build-common:
    [mkdir] Created dir: /opt/vufind-browse-handler/build/common
    [javac] Compiling 8 source files to /opt/vufind-browse-handler/build/common
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 8
    [javac] 1 warning

build-handler:
    [mkdir] Created dir: /opt/vufind-browse-handler/build/browse-handler
    [javac] Compiling 13 source files to /opt/vufind-browse-handler/build/browse-handler
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 8
    [javac] /opt/vufind-browse-handler/browse-handler/java/org/vufind/solr/handler/AuthDB.java:63: error: bad operand types for binary operator '>'
    [javac]         if (results.totalHits > 0) {
    [javac]                               ^
    [javac]   first type:  TotalHits
    [javac]   second type: int
    [javac] /opt/vufind-browse-handler/browse-handler/java/org/vufind/solr/handler/AuthDB.java:80: error: bad operand types for binary operator '<'
    [javac]         for (int i = 0; i < results.totalHits; i++) {
    [javac]                           ^
    [javac]   first type:  int
    [javac]   second type: TotalHits
    [javac] /opt/vufind-browse-handler/browse-handler/java/org/vufind/solr/handler/BibDB.java:96: error: <anonymous org.vufind.solr.handler.BibDB$1> is not abstract and does not override abstract method scoreMode() in Collector
    [javac]         db.search(q, new SimpleCollector() {
    [javac]                                            ^
    [javac] /opt/vufind-browse-handler/browse-handler/java/org/vufind/solr/handler/BibDB.java:186: error: <anonymous org.vufind.solr.handler.BibDB$2> is not abstract and does not override abstract method scoreMode() in Collector
    [javac]         db.search(q, new SimpleCollector() {
    [javac]                                            ^
    [javac] /opt/vufind-browse-handler/browse-handler/java/org/vufind/solr/handler/BibDB.java:279: error: <anonymous org.vufind.solr.handler.BibDB$3> is not abstract and does not override abstract method scoreMode() in Collector
    [javac]         db.search(q, new SimpleCollector() {
    [javac]                                            ^
    [javac] /opt/vufind-browse-handler/browse-handler/java/org/vufind/solr/handler/BrowseItem.java:157: warning: [deprecation] Integer(int) in Integer has been deprecated
    [javac]         this.setCount(new Integer(count));
    [javac]                       ^
    [javac] /opt/vufind-browse-handler/browse-handler/java/org/vufind/solr/handler/BrowseRequestHandler.java:60: warning: [deprecation] toSolrParams(NamedList) in SolrParams has been deprecated
    [javac]         solrParams = SolrParams.toSolrParams(args);
    [javac]                                ^
    [javac] /opt/vufind-browse-handler/browse-handler/java/org/vufind/solr/handler/BrowseRequestHandler.java:94: warning: [deprecation] Integer(String) in Integer has been deprecated
    [javac]             return new Integer(s).intValue();
    [javac]                    ^
    [javac] 5 errors
    [javac] 4 warnings

BUILD FAILED
/opt/vufind-browse-handler/build.xml:84: Compile failed; see the compiler error output for details.
</pre>

**Comment by demiankatz** [comment]
And good news: the SolrMarc problem appears to be reasonably simple to fix: https://github.com/solrmarc/solrmarc/pull/86

**Comment by demiankatz** [comment]
I have updated both SolrMarc and the browse handlers in this pull request, which allows the full test suite to run. I would prefer to have an official SolrMarc release before merging this, but if none is issued, we at least have the git commit we built from incorporated into the jar's filename, so it's very clear which version of the code we are using. The browse handlers are built from https://github.com/vufind-org/vufind-browse-handler/pull/33, so we can merge those as-is (and merge that PR at the same time) unless changes occur in the browse handler's dev branch that require a rebuild.

**Comment by demiankatz** [comment]
As of today, the full test suite is passing here with the upgraded .jar files in place.

**Comment by demiankatz** [comment]
SolrMarc 3.4 has been officially released, so I have updated us to an official version instead of a custom build! Many thanks to @haschart for his support.

**Comment by demiankatz** [comment]
@EreMaijala, I think this is ready to merge now (I haven't merged https://github.com/vufind-org/vufind-browse-handler/pull/33 yet, but that's just because the tests there won't pass until VuFind's dev branch has Solr 8 in it, so I think it's probably best to merge this first). Any objections?

**Comment by EreMaijala** [comment]
@demiankatz No objections. Good to see that things are progressing. :)

**Pull request merged**
