### PR TITLE
Daia2

### PR DESCRIPTION
**Pull request by jochen-lienhard**
I implemented a new DAIA driver for a json result. It has an own config file (DAIA2.ini) and an own driver (DAIA2.php), so the xml version is still working as DAIA. 
Only the base fields for a ILS answer are implemented. Everyone can now create an own driver by extending DAIA2.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks for sharing this. A couple of comments:

1.) Is DAIA2 the best name for this? Is this for a different version of DAIA than the original DAIA driver? If so, I think DAIA2 would be fine... but if it's communicating with the same server and the only difference is the response format, maybe DAIAJSON would be a better name.

2.) There are some style issues in the file. Do you have access to phpcs? If so, it might be worth running through the output of phpcs --standard=PEAR DAIA2.php. If you don't have easy access to the tool or don't have time for this, let me know and I'll be happy to take care of it.

Thanks for sharing!

**Comment by jochen-lienhard** [comment]
2) fixed, thanks for the hint.

1) Hmmm ... it can communicate with the same DAIA server, but the answer for vufind is not the same. So I'm not sure, what will be the best name.

**Comment by demiankatz** [comment]
Thanks for the style fixes!

Do you think DAIAJSON would be an appropriate name for the driver, or is the JSON communication not really the primary feature of this alternate driver?

**Comment by jochen-lienhard** [comment]
Done. I don't like numbering the different versions so DAIAJSON would be the best name.

**Comment by demiankatz** [comment]
Thanks -- looking very good. A couple of things you might want to do before we merge this:

1.) Add some comments to DAIAJSON.ini and change the real-life URL to a fake myuniversity.edu one.

2.) Adjust the driver comments in config.ini to add the DAIAJSON option and briefly explain how the two drivers differ.

3.) Build some test coverage; this looks like it should be fairly straightforward to unit test if you capture some sample HTTP responses and push in mock objects. If you don't have experience with this, I can work with you on it. If you don't have time/interest, we can live without it -- but it's always nice to have test coverage when adding new code!

Once we take care of 1 and 2, I think we're ready to merge. 3 is just a bonus!

thanks,
Demian

**Comment by jochen-lienhard** [comment]
1) done.
2) done. I hope this is enough comment. Do we need an entry: 'daiajson' => 'VuFind\ILS\Driver\DAIAJSON' in the module.config.php (for the installer?)
3) That is a good idea. How to do this? Is it possible to test only the DAIAJSON driver, or do I need to test all? Where to put the mock objects? I think I must create a DAIAJSONTest.php like the other driver-test. Is there a mock object for the default DAIA driver? If not, I can add this too.

**Comment by demiankatz** [comment]
1) Thanks!

2) The comments look good. You are correct that it's probably a good idea to add the entry to module.config.php as well. It's not absolutely necessary because the default factory figures out how to build the object dynamically, but I try to keep everything explicitly configured.

3) It should be possible to test the DAIAJSON driver on its own. Since it has the HTTP service injected, you can set up your test to inject an HTTP service that uses a mock test adapter (see https://github.com/vufind-org/vufind/blob/d6a71c48b582c0c3c406f27f462bc509c3c2f1a4/vendor/vufind-org/vufindhttp/tests/unit-tests/src/VuFindTest/HttpServiceTest.php for an example), and you can set up expectations and fake return values on the mock test adapter to simulate the necessary interactions. You can look at the createConnector() method in https://github.com/vufind-org/vufind/blob/5e5cc40eab303dd99d641bdc538c93efe5638027/module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/Primo/ConnectorTest.php for an example of how to load an HTTP response from a text file and stuff it into a test adapter. To create the text fixtures in the first place, you can temporarily add file_put_contents('/tmp/file', $response->toString()) in your code following an HTTP call.

I'm happy to help with some of this if you run into any trouble; not sure if you've done this before. If you're new to it, it sometimes takes a while to get all the details right!

Regarding the base DAIA driver, I think it would need to be rewritten a bit to make it more testable. Right now it's not using a standard HTTP client to retrieve responses and is instead using PHP's built in URL retrieval functionality. We would have to change that to a better abstraction in order to be able to mock things out for testing. That might be a good task for a separate pull request if you really want to do it, but you certainly don't have to!

**Comment by jochen-lienhard** [comment]
2) done
3) It is my first test, so I must think about, what to test and how to test.

**Comment by demiankatz** [comment]
It looks like your test is off to a good start. Probably the best starting point for your test is to call one of the methods on the driver and do an assertEquals between the real response and the one you expect to come back for your fixture. If you do that sort of test for each of the public methods, that's going to cover most of the code reasonably. After we merge this to master, continuous integration will generate a code coverage report that will reveal whether there are any edge cases, etc., that need to have additional tests added for coverage.

Thanks again for working on this, and I hope it's a useful learning experience. As always, let me know if I can do anything to help.

**Comment by jochen-lienhard** [comment]
Do you think it is better to split DAIAJSON.php in two classes, one that contains the HTTP-Connector and the other that contains the analyse. I think to build tests is than much easier.

**Comment by demiankatz** [comment]
Splitting the class is one possibility. Another is to rely more heavily on VuFind's existing HTTP service. I think if you were to add a $headers parameter to VuFindHttp\HttpService::get() (see https://github.com/vufind-org/vufindhttp/blob/master/src/VuFindHttp/HttpService.php) you might be able to simplify your own doHTTPRequest() method significantly, and you would have an easy mock integration point for testing.

If you wanted to go this route, it's a little bit complicated simply because VuFindHttp is included as a vendor dependency in the VuFind project... so we would have to open a PR on the vufind-org/vufindhttp project, merge that, then update the dependency in the main VuFind project. But I'm willing to help with that if you think it's the way to go.

Another small issue to think about: right now, you seem to be hard-coding a CurlAdapter into your HTTP client... but one of the purposes of the central VuFind HTTP service is to allow all HTTP clients used by VuFind to share the same adapter (which is particularly important for institutions running behind a proxy server). Is there a reason that DAIAJSON has to hard-code the CurlAdapter, or could you just let the central service make the adapter decision (and perhaps recommend configuring it to CURL for users who need DAIAJSON)?

**Comment by lahmann** [comment]
Hi Jochen,
I am currently working on the DAIA-driver as well and like your new DAIAJSON driver very much.
Do you think it would be a good idea to integrate the DAIAJSON driver into the existing DAIA-driver for legacy reasons? Using a DAIA-driver .ini value to configure the response value resulting in either parsing JSON or XML would be very easy to implement - availability logic etc. would be the same for both and the DAIA-driver would be more compliant to the DAIA-specification (although it is planned to redesign DAIA JSON-only, until now XML is still a part of the specification). Setting XML to default, the DAIA-driver would keep the same behaviour as the current one in master - altering the .ini settings would enable DAIA-JSON (which would be necessary for a separate DAIAJSON-driver too).
Besides legacy support and keeping the ILS-drivers as straightforward as possible, we wouldn't have to decide which DAIA driver to use for a VuFind2 PAIA-driver implementation.

I just did a quick test and both driver (DAIA and DAIAJSON) do run combined in one ILS-driver pretty well, so there's almost no additional work to do.

Let me know, what you think.

Best,
André

**Comment by demiankatz** [comment]
André,

This sounds like a great idea to me. If Jochen has no objections, please feel free to submit a pull request.

One possible objection I can anticipate is that I believe Jochen was aiming to design the DAIAJSON class as a very simple base class that could be easily extended with local customizations. If merging the drivers would somehow provide an obstacle to this approach, perhaps it would still be possible to make DAIA a subclass of DAIAJSON or otherwise tighten up the relationship of the two drivers.

**Comment by jochen-lienhard** [comment]
Hmmm ... I did not want to touch the 'old' DAIA driver. There is some work to do, to merge both drivers, because the DAIA driver does not implement HttpService and there is a lot of code,
that must be checked and fixed. I want to keep the DAIAJSON very simple, so that everyone
can create own classes. As you can see in earlier commits, I first had a daiatype field. Jakob Voss said that json will be the default in the next daia-server release. So I'm not sure, if the xml-driver will be necessary in future. I you like to merge both, feel free to submit a pull request.

**Comment by demiankatz** [comment]
You should now be able to merge master into this branch to obtain the new VuFindHttp functionality that you added.

**Comment by demiankatz** [comment]
Regarding combining the functionality of the two drivers, we should decide on that issue one way or another before merging this PR so we don't cause confusion by introducing a new driver and then immediately eliminating it. I'll wait and see what else André has to say before weighing in further.

**Comment by jochen-lienhard** [comment]
I'm just thinking about the test cases. I think, I need the client as variable of DAIAJSON, so that I can set the client in the test with the content for the testfiles. That will be the next step.

**Comment by demiankatz** [comment]
I think you have two options:

1.) In your test, create an HttpService and use setDefaultAdapter to push in the test adapter... then push this service into the driver you are testing.

2.) Refactor the driver so that, instead of using the HttpService, it accepts an HTTP client as a constructor parameter. You'll then need to define a factory to build the driver in module.config.php instead of loading it as an invokable. Inside the factory, you can make the call to the HttpService to create the HTTP client.

I think that 2 is a slightly better solution, in the sense that your driver only really needs the HTTP client, and pushing in the service adds a more complex dependency than is strictly necessary. But setting up 2 will be more work than setting up 1.

I can help with the setup on option 2 if you like -- just let me know.

**Comment by lahmann** [comment]
I just submitted a pullrequest for the merge: https://github.com/jochen-lienhard/vufind/pull/2
It will add two additional methods for parsing the xml and extends some methods with the logic for choosing the right format-methods.

**Comment by jochen-lienhard** [comment]
Next week I will merge the pull request and start with the refactor for 2) and tests.

**Comment by jochen-lienhard** [comment]
If I understand correct, I must remove the server and add a httpClient, which is the parameter in the construct method. Must it be a \Zend\Http\Client or a \vufindhttp\Client?

**Comment by demiankatz** [comment]
The get method is a convenience method implemented by the VuFindHttp\HttpService here:

https://github.com/vufind-org/vufindhttp/blob/master/src/VuFindHttp/HttpService.php#L122

This wraps around the standard Zend\Http\Client. So if you change your class to depend on the raw client instead of the full service, you can't call get directly but will instead have to make client calls similar to the ones used by the service. For a simple use case, this shouldn't be dramatically more complicated than calling get directly, so it's probably worth it to have a more generic dependency...

**Comment by jochen-lienhard** [comment]
Hmmm ... what can be our next steps.

I hope Andre can update his PR soon, so that I can merge it.
Than I will remove the daiajson stuff.

Can you than merge it to the master and for the test case we will create a new pull request?
What is your opinion?

**Comment by demiankatz** [comment]
We'll need to make sure the existing tests pass before we merge to master, but as long as that is the case, I think that sounds like a reasonable plan. As I've probably mentioned already, I'll be on vacation next week, but perhaps you and André can make some progress while I'm away and I can finish up the merging upon my return.

**Comment by jochen-lienhard** [comment]
merged the changes from Andre, removed daiajson (is now integrated in daia).
can now be merge to master, for test cases (json and xml) there will be come a new PR 
after the merging.

**Comment by lahmann** [comment]
Hi Jochen and Demian, sorry for the delay - my son was born two weeks ago (the day after my last push) and I was on instant vacation getting things sorted. Now we've adjusted to this little fellow and I'm back at work :)

Thanks a lot for the work you were doing meanwhile - let me know if you need any help with the tests.

**Comment by demiankatz** [comment]
Congratulations, André! I'm just back from (more predictably planned) vacation and will dig into this deeper as soon as I'm caught back up again with everything.

**Comment by lahmann** [comment]
Thanks! Sure, take your time and let me know if I can be of any help.

**Comment by jochen-lienhard** [comment]
Congratulations Andre, I hope both, son and mother are well. 
I will wait, until Demian has time for digging deeper.

**Comment by demiankatz** [comment]
Okay, I've manually merged this to master (to simplify the very long commit history and to correct a very minor style issue). Please go ahead and work on tests when time permits. In the meantime, I'll share this change with Oliver in case he has any additional input.

**Comment by jochen-lienhard** [comment]
Thanks.
I create a new PR https://github.com/vufind-org/vufind/pull/310 for the test case.

**Pull request closed without merging**
