### PR TITLE
Fix account menu dropdown and sandal's account notification icon.

### PR DESCRIPTION
**Pull request by EreMaijala**
I'm not sure what the original intention was with the hidden menu elements in the myresearch menu when the dropdown is enabled, but it didn't work, and the dropdown menu was practically empty. Also sandal didn't apply correct background to notification icons with the current DOM structure, so I added a notification level class to the outer element.
Added bonus: A little bit less jQuery, but only for the touched part.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @EreMaijala. I'm requesting reviews from @crhallberg (who originally designed this and might have better historical perspective than me) and @sturkel89 (who I'm hoping can give this some thorough testing and make sure we haven't missed anything).

@sturkel89, for testing purposes:

This affects the enableDropdown setting in config.ini. When that setting is turned on and the user is logged in, the account link in the header will turn into a drop-down that shows a summary of the user's account status (basically the same content as the side menu in the account area). This should be testable by turning on the Demo ILS driver, creating an account, and "logging in" to the fake ILS account. As always with the Demo driver, the data will get randomly regenerated every time you log in and out, so it may be worth a few tries to see how things look with different data. Please compare this branch against dev (sounds like dev is going to be pretty broken -- this is apparently a rarely used or tested feature -- and hopefully this is not) and check out how things look in all of the themes. Testing mobile behavior is probably a good idea too, in case there are any responsiveness problems.

Thanks!

**Review by sturkel89 — CHANGES_REQUESTED** [review]
**TEST BRANCH**
I attempted to review the test branch in all three themes in order to compare with dev and those themes. I had a weird experience, in that **test does not allow me to switch themes**; it seems to be stuck in the default theme. Nothing is highlighted in the theme drop down, and I'm unable to select any specific theme.

| Test |
| --- |
|  | 

| Dev|
| --- |
 | 

However, in the default (sandal), this feature looks great!

image


**DEV BRANCH**
In dev, theme selection is possible, and I can switch between themes easily. However, the **Your Account** dropdown tool looks terrible in every theme.

| Sandal |
| --- |
|  |

| Bootstrap3 |
| --- |
|  |

| Bootprint3 |
| --- |
|  |

**Comment by sturkel89** [comment]
Here's a view of how this view of the **Your Account** feature appears in mobile. I don't really like that it takes on the blue background of that upper bar across the top of the screen.




<p>

The "regular" view of the **Your Account** menu looks much nicer on mobile:



<p>

NB: In my mobile emulator, it seems that I get an error saying "This content is blocked. Contact the site owner to fix the issue." whenever I click any link anywhere on the site. So, I can't really test **behavior** using this mobile emulator.

**Comment by EreMaijala** [comment]
@sturkel89 The theme switching is broken in latest dev branch as well, so not caused by the changes here. I'll fix the background color.

**Comment by EreMaijala** [comment]
@sturkel89 I ended up hiding the dropdown menu in mobile view. It's not easy to fix consistently and changing the background would make it less uniform with other dropdowns.

**Comment by demiankatz** [comment]
Thanks, @EreMaijala, I agree that hiding the dropdown in mobile mode makes sense, since the same information is accessible by clicking through to the account anyway.

@sturkel89, the theme switching bug has been identified and fixed (as @EreMaijala says, it was not just here but also in dev -- maybe you haven't pulled the latest dev recently in your VM?). I've merged the fix into this branch, so this should be all set for you to do another round of testing.

**Review by sturkel89 — APPROVED** [review]
There have been lots of code updates since I last tried this! (Indeed, I had not updated my dev before yesterday's testing.)

I can confirm that:
- Theme switcher is now working in both test and dev. 
- The **Your Account** dropdown looks great in test in all three themes! See screenshots.
- All of the items on the dropdown menu function properly: they are live links that bring the user to the appropriate place in their profile.
- The dropdown arrow does **not** appear on mobile in test.
- Nothing has changed in dev re: the **Your Account** dropdown. The arrow still appears, but the outcome still looks like the screenshots above (as expected).

Is there anything else anyone would like me to look at? I think this feature looks good and is ready to merge, as far as I'm concerned.

| Sandal |
| --- |
|   |

| Bootstrap3 |
| --- |
|   |


| Bootprint3 |
| --- |
|   |

**Review by demiankatz — APPROVED** [review]
Looks good to me too -- thanks, @sturkel89!

**Pull request merged**
