### PR TITLE
introduces showMore parameter to control, how many facet values should be displayed in list

### PR DESCRIPTION
**Pull request by olli-gold**
This PR introduces a new parameter for facet configuration, that allows the administrator to easily modify the number of facet values, that should be displayed after someone collapsed a facet. For values beyond that number the user needs to click the "show more" button.

This value had been hardcoded before. However, this could be a nice simplification for frontend modifications, that does not hurt.

### CODE REVIEW

**Comment by demiankatz** [comment]
This is great (and long overdue) -- thanks! Just two suggestions before we merge:

1.) I think we should offer a mechanism to override the default value as well as the field-specific values. It seems likely that if somebody wants to change this, they would want to change it for all facets, not necessarily just a few selected ones. Adding support for showMore[*] would probably do the trick.

2.) It would probably make sense to do the bulk of the calculation to determine the $facets_before_more value inside the recommendation module, rather than in the template. This makes the template more readable and allows easier reuse of the logic. It will probably be even more helpful if you add wildcard support as suggested above, since that check will make the logic significantly more complicated.

Let me know if I can be of any further assistance! I think we should be able to get this one wrapped up very quickly.

**Comment by olli-gold** [comment]
Thank you for the feedback - I have implemented your suggestions now and hope, its already mergeable.

**Comment by demiankatz** [comment]
Thanks again! I've made a few minor adjustments (added configuration to EDS/Primo/Summon, adjusted some code to be slightly shorter). It's now merged to master and is working perfectly for me.

**Comment by olli-gold** [comment]
Great, thank you!

**Pull request closed without merging**
