### PR TITLE
Upgrade to laminas-form version 3.

### PR DESCRIPTION
**Pull request by demiankatz**
TODO:
- [x] Run full test suite
- [x] Manually test functionality
- [x] Review [release notes](https://github.com/laminas/laminas-form/releases/tag/3.0.0) for possible issues

### CODE REVIEW

**Comment by demiankatz** [comment]
@samuli, I am working on upgrading VuFind's dependencies to the latest versions, and there is now a new major release of laminas-form, which includes some backward compatibility breaks. Since you are much more familiar with the feedback code that utilizes the Form classes, I'm hoping that you can help take a look at this.

So far, I have just run the unit tests and corrected some incompatible method signatures in our local Form subclass. I haven't tried any hands-on testing yet. I am currently running the full test suite, and will check the box in the TODO list above once everything passes.

If you have time to help with the manual testing and/or reviewing the changelog to identify any potential concerns, I would be really grateful for your help. If you do not have time, please let me know and I'll see if I can fit it into my own schedule.

**Comment by aleksip** [comment]
@demiankatz I will try to find time to test/review this change next week.

**Comment by demiankatz** [comment]
Thanks, @aleksip, I appreciate it! Happy to help if you need it, but since I never use this feature, it would be good to have your involvement as a more invested stakeholder!

**Comment by demiankatz** [comment]
@aleksip, just to make sure this is ready for you, I took care of resolving merge conflicts, and I also ran the full test suite. Tests are currently passing, but that's just as likely a sign that we're not testing the right things as it is that everything works -- I'm not sure how thorough form-related coverage is.

**Comment by aleksip** [comment]
@demiankatz Thanks! I have read the release and migration notes and tested with several of our forms, and everything seems to work fine.

**Comment by demiankatz** [comment]
Thanks, @aleksip, I've just merged this!

**Pull request merged**
