### PR TITLE
Improved inheritance for generic controller factory (using static namespace)

### PR DESCRIPTION
**Pull request by mtrojan-ub**
Hi Demian,

i wondered what you think about using static namespaces inside generic factories, instead of __NAMESPACE__. This way if you inherit the factory, you also get a generic function for free which searches in the namespace of the child class, instead of it's parent's namespace. This avoids re-implementing the function in child classes over and over again. If you explicitly want to use the parent's namespace, you can explicitly use the parent factory in the module config file.

(It might be a compatibility break, so maybe not for version 4...)
This might also be a good design pattern for other generic factory functions, not only the controller factory.
What do you think?

Best regards,
Mario

### CODE REVIEW

**Comment by demiankatz** [comment]
I think this is a good idea, and the compatibility break is likely to be minimal (though I'd still wait for release 5, as you suggest). However, I wonder if using reflection here might be unnecessarily expensive. Could we just parse the namespace out of `static::class` with a simple string operation rather than instantiating a `ReflectionClass` object? (I'm concerned that setting up reflection may be performing a number of operations that we really don't need just to look up a namespace -- though it's possible I'm being overly cautious here).

**Comment by demiankatz** [comment]
...and some discussion [here](https://coderwall.com/p/cpxxxw/php-get-class-name-without-namespace) suggests that I may be totally off-base, and reflection may actually be faster than string manipulation.

I'll see if I can find a little time to profile this when I'm closer to being caught up on merging pull requests. I have a bit of a backlog right now but hope to catch up over the next week or two!

**Comment by demiankatz** [comment]
@mtrojan-ub, please take a look at my two most recent commits. I've done a couple of things:

1.) I've refactored the new generic logic to a GenericFactory, and used this as the basis for all four controller factories in VuFind. This eliminates significant redundancy.

2.) Testing suggested that string manipulation is about twice as fast as reflection for the purposes of this logic; it's also a bit more concise. Thus, I switched the code to go that route.

If you have no objections to either of these changes (and have no further suggestions for additional improvements), I think we can merge this. Please let me know what you think, and thanks for this excellent suggestion.

**Comment by mtrojan-ub** [comment]
Hi Demian,

that looks really good! And thank you very much for taking care of it in this short time!

Best regards,
Mario

**Comment by demiankatz** [comment]
Thanks for taking a look -- I've merged it now and will note this in the changelog as a very minor potential BC break.

**Pull request merged**
