### PR TITLE
Close lightbox on status code 204 (no content).

### PR DESCRIPTION
**Pull request by samuli**

### CODE REVIEW

**Comment by demiankatz** [comment]
@samuli / @EreMaijala, what is the use case for this? @crhallberg, any thoughts?

**Comment by EreMaijala** [comment]
We intend to change the "Add to favorites" workflow slightly so that the lightbox is closed automatically. The easiest way, as far as I can see, is to modify the saving code slightly to return 204 with no content. This also compares nicely to the 205 handling.

**Comment by demiankatz** [comment]
Okay, makes sense... but I'll wait for feedback from @crhallberg before taking further action.

**Comment by crhallberg** [comment]
This looks good to me! We don't have a mechanism for this yet and I like this method.

**Comment by demiankatz** [comment]
Thanks for the review, @crhallberg -- merging now.

**Pull request merged**
