### PR TITLE
Sandal: Move tabs back up, tweak paddings and margins of searchbox.

### PR DESCRIPTION
**Pull request by EreMaijala**
Having tabs below searchbox was a neat idea, but it didn't work properly and was a bit confusing because the search field or other links were tied to the active tab. Also tab order wasn't right and filters didn't display properly.

This is in preparation for #3222.

### CODE REVIEW

**Comment by demiankatz** [comment]
@crhallberg, I'd be interested in your thoughts on these style changes, since this is a significant change to Sandal. I don't oppose to simplifying things to make the themes more consistent and thus allow for a more straightforward bootstrap5 upgrade... but if you're strongly attached to the custom tab behavior in sandal, please speak now! :-)

@sturkel, can you check this out as well and offer any feedback you might have? You can use the `[SearchTabs]` and `[SearchTabsFilters]` sections of config.ini to experiment with tabs. Something like this might be a place to start:

```
[SearchTabs]
Solr = Primary
Solr:filtered = "Primary Filtered (only books)"
SolrAuth = Authority
Search2 = Secondary
Search2:filtered = "Secondary Filtered (no books)"

[SearchTabsFilters]
Solr:filtered[] = "format:Book"
Search2:filtered[] = "-format:Book"
```

Might also be interesting to play with the `[SearchTabsSettings]` section to be sure that the setting there continues to behave as expected after the change in tab behavior.

**Review by sturkel89 — CHANGES_REQUESTED** [review]
I reviewed the test branch and compared sandal with bootstrap3. See below for my comments, and see the very end for my recommendation for revising the look and feel of the top tabs.

### Responsiveness = NEEDS TO BE FIXED
The tabs across the top of the screen are not responsive in Sandal; with a narrowed browser or on mobile, they stay in a long line and therefore roll off the screen.

image

The tabs in Bootstrap3 are responsive.
image

In both themes, the tabs at the bottom of the item record ARE responsive.

**Please make the top tabs responsive so they scroll to a second line.**

### Tabs above the search box = GOOD
In my opinion, the tabs look better above than below the search box in Sandal. There are two specific justifications for this preference:

First, I appreciate having the layout here match the layout in the other themes. 

Second, on Sandal on dev, where the top tabs are below the search box, it looks strange to have the **Reset Filters** button and any set filters appear between the search box and the tabs. It's seems to me that the elements are logically out of order:

image

I find that there's a more logical progression in the test branch:

image

This progression is like a funnel: 
- "Which catalog am I in?" 
- "Which terms did I search?"
- "Which specific limits have I placed?" 
- [Results set]

### Design and usability = COULD BE IMPROVED
In Bootstrap3, the active tab is outlined, and the font color is different due to it being plain text rather than a hyperlink. Moused-over tabs are very clearly indicated by an outline and an extreme color change. 

image

In Sandal on test, the active tab has no tab shape or outline; it's indicated by the tab's underlining being bold. Font color and boldness are uniform across all tabs. 

image

Moused-over tabs are outlined, but the tab label text turns gray (hyperlink color, I guess?) - seemingly de-emphasized, rather than emphasized. 

image

I think the Sandal tabs look elegant, but their existence as selectable catalog options is a bit less clear and noticeable than if they had distinct tab outlines and background shading. 

### Top tabs are not consistent with item record tabs
The tabs at the bottom of the item record in both themes have visible outlines for the active tab and the moused-over tabs. The moused-over tab is very clearly highlighted in negative colors with a negative outline.

**Bootstrap3 item record tabs**
image

**Sandal item record tabs**
image

**Villanova item record tabs**
image

NB: The style for visible hyperlinks in all test versions is that the regular clickable links are underlined, but links displayed in tab labels are not. At Villanova, we underline tab labels the same as other links; I prefer this, but it's not a big deal since the tab styling in the non-customized version suggests that the tabs are links.

### Top tabs are not consistent with Login, Theme, and Language options in Sandal
In Bootstrap3, top tabs and item-record tabs behave identically, AND they match the behavior of the **Login, Theme, and Language** options/dropdowns in the upper left corner of the screen.

image

In Sandal, top tabs behave differently from item-record tabs AND behave differently from the **Login, Theme, and Language** options/dropdowns. 

image

I think we have too many different things going on with tabs in Sandal...

### Recommendations
I think the best compromise for designing the top tabs would be:
- implement the always-visible outline for the active tab, as in the item-level tabs
- use the color scheme for moused-over tabs from the Login/Theme/Language area. 

For a more extreme version, which I'd actually prefer, I'd have outlines visible for ALL tabs always, and a shading and text boldness indication for the active tab, and then a different kind of visible indication for moused-over tabs. But maybe that is too much.

**Comment by EreMaijala** [comment]
@sturkel89 You raise valid points. I fixed the wrapping for responsiveness (though wrapping tabs are pretty terrible in any case), but I think that any tweak to the style would be better left for another pull request and debate. I believe the current style was a conscious choice that works with the background image etc.

**Review by sturkel89 — APPROVED** [review]
I checked the updated branch. Responsiveness is fixed! Thanks, @EreMaijala! 

If that's all we want to do with this PR at this point, then we're ready to merge.

**Review by demiankatz — CHANGES_REQUESTED** [review]
The biggest problem I have with this design is that I feel like the thick underline indicating the active tab conflicts with the permanent thin underline across the entire "tab bar." If we're going to use this different style of tab, I think it's important to remove the bottom border, since it makes the selected tab harder to identify. How would you feel about this simple change?

```
diff --git a/themes/sandal/less/search.less b/themes/sandal/less/search.less
index b6f81526c4..be0ece3175 100644
--- a/themes/sandal/less/search.less
+++ b/themes/sandal/less/search.less
@@ -237,6 +237,7 @@
   .nav-tabs {
     white-space: nowrap;
     margin-bottom: 1rem;
+    border-bottom: none;
   }
   .nav-tabs a,
   .nav-tabs a:hover {
```

Here are screen shots showing the state when the second tab is active and I'm hovering over the third tab.

Before:

image

After:

image

To my eye, at least, that's a dramatic improvement... but if others feel differently, I'm open to discussion.

I also wouldn't mind some further adjustments along the lines of @sturkel89's suggestions, but I agree that those could be addressed as a separate PR, and the work here is at least a step in the right direction in the meantime.

**Comment by EreMaijala** [comment]
@demiankatz Bottom border now removed. While the result is still not perfect, it's much better and improves the wrapped look. And I think this now looks more like "[pills](https://getbootstrap.com/docs/3.4/components/#nav-pills)", which may (?) alleviate some of Susan's concerns about the discrepancy between these and other tabs. And contradicting myself I ended up fixing the de-emphasized color of hover text.

**Comment by sturkel89** [comment]
I agree that this is the best version yet! Here's a screenshot with show_result_counts turned on. 

image

I still think the black font upon mouseover looks better against the light background that appears when you mouse over the Login and Language buttons... and a different color font might be better if you aren't going to shade the tabs... but we can hash out those details in a future PR!

image

**Review by demiankatz — APPROVED** [review]
Thank you both! I think this is now safe to merge, so here we go...

**Pull request merged**
