### PR TITLE
Fixes double-checkbox-filter display introduced by #1482.

### PR DESCRIPTION
**Pull request by demiankatz**
TODO:
- [x] Run full test suite.

### CODE REVIEW

**Comment by demiankatz** [comment]
@EreMaijala, while testing #1499, I noticed that checkbox filters were double-displaying in search results (once with the correct label, and again as an "Other" filter). I think this is because we should have been excluding them from the results of getFilterList when the changes from #1482 were introduced. This PR fixes that -- but do you mind double-checking this before I merge it? Thanks!

**Review by EreMaijala — APPROVED** [review]
Makes sense, even though I'm not quite sure how the change caused this. getFilters (a.k.a getRawFilters didn't exclude checkbox filters either. Is there maybe somewhere a check to see if a filter is indeed a checkbox filter somewhere that doesn't work with getFilterList() but worked with the raw filters?

**Comment by demiankatz** [comment]
@EreMaijala, I took a closer look at this. The issue is that, before #1482, the filters.phtml file internally called `getFilterList(true)` and relied on that value. After #1482, the filter list was passed in from searchbox.phtml, and in most cases, that did not have the "exclude checkboxes" parameter set, resulting in duplicated displays. Does that make sense, or am I still missing something?

**Comment by EreMaijala** [comment]
@demiankatz Ah, yes, that makes sense. Thanks for the clarification! I think the original issue stems from some inclarity of who owns a variable and passes what. I'm all good with now.

**Pull request merged**
