### PR TITLE
Convert all text to B&W in print view.

### PR DESCRIPTION
**Pull request by demiankatz**
This adjusts the print styles to force ALL text to B&W for consistency. This addresses a strange problem identified in #3142.

Before:

image

After:

image

### CODE REVIEW

**Comment by EreMaijala** [comment]
@demiankatz What's the role of the added menu-item template here?

**Comment by demiankatz** [comment]
@EreMaijala, that must have been accidentally committed. It's not related to the change here and has been removed.

**Comment by crhallberg** [comment]
Do we want to try to minimize this further? I'm not sure we need the link::after clearing any more and we could probably add the hidden-print classes to the action toolbars to remove that specific case at the bottom.

I don't think they're doing any harm, just looking for ways to minimize customization problems.

**Comment by demiankatz** [comment]
@crhallberg, if you think it's worth investing time in simplifying print.css further, I definitely don't object. But maybe we should approve and merge this first (since this PR is specifically about fixing the text coloration problem) and then follow with a second PR to simplify.

**Review by xmorave2 — APPROVED** [review]
I think this is step in the right direction and I agree with @demiankatz that this should be merged as it is, because it is fixing one concrete issue. We could always open another PR for more changes of printing styles.

**Pull request merged**
