### PR TITLE
Fix 2 undefined variables in search/filters.phtml

### PR DESCRIPTION
**Pull request by mtrojan-ub**
This problem exists since version 6.1

### CODE REVIEW

**Comment by EreMaijala** [comment]
@mtrojan-ub Both variables should have been relayed by the caller (they could (should?) have been written `$this->checkboxFilters` and `$this->filterList`). See e.g. https://github.com/vufind-org/vufind/blob/dev/themes/bootstrap3/templates/search/searchbox.phtml#L144

**Comment by EreMaijala** [comment]
@mtrojan-ub To add to that it's done so that the caller has control over whether the filters are displayed.

**Comment by mtrojan-ub** [comment]
Thanks for the hint! I changed it to $this->... to keep it more consistent regarding to the others (like $this->params).

**Comment by demiankatz** [comment]
Thanks! In most situations, the framework should automatically extract all variables from $this so they can be referred to with or without the prefix... but when including sub-templates, it can get more complicated, and it seems like this may be just such a case. Explicitly using $this is always the more reliable (if less enjoyable to read) approach.

**Pull request merged**
