### PR TITLE
Don't prefill the password when editing a library card for improved s…

### PR DESCRIPTION
**Pull request by EreMaijala**
…ecurity. 

This means the user needs to remember the password to change the card details but makes sure the current password is not revealed in the returned HTML.

### CODE REVIEW

**Comment by demiankatz** [comment]
If we want to minimize the password-typing, couldn't we add some logic to only display the password box if a login attempt to the existing account fails or if the user changes their barcode, and to have the backend code load the existing credentials from the database if the submitted password field is blank? (Or we could just add a note to the interface saying "leave blank unless changed").

**Comment by EreMaijala** [comment]
Makes sense. Maybe use four spaces as the default value and validate the password only if it or the card number changes?

**Comment by demiankatz** [comment]
@EreMaijala, that makes sense to me... though I assume you're proposing the "four spaces" approach to get around browser-side validation of the password field. If we can just allow the form to submit an empty password field, that might be slightly less potentially confusing. Or, alternatively, we could submit a number of blank spaces equal to the password length, which would to the end user look exactly the same as if we pre-populated the field, making a more seamless change... but of course would also be conveying a piece of information about the password that we probably don't want to share.

**Comment by EreMaijala** [comment]
Updated patch with what I was thinking. It uses spaces to denote that a password has been stored and checks the credentials only if card is new, username has beed changed or the password has been modified. This makes it easy to change the card name without having to enter the credentials. What do you think?

**Comment by EreMaijala** [comment]
Just to clarify: I'm using the spaces because that implies that a password already exists so that the user doesn't think it needs to be filled or that there's an issue with it.

**Comment by demiankatz** [comment]
@EreMaijala, this is shaping up pretty nicely. Two issues I ran into when testing, though, one of which may be a separate problem that needs its own PR:

1.) I found it distracting that, when I mistyped a password, or if my underlying password changed, the password field was always prefilled with four characters. I think it might be better to make the password field empty when there is an authentication error, to underline the fact that the user needs to retype the password. Unfortunately, based on the way the code is currently structured, this appears to be non-trivial to implement. Let me know if you'd like me to look closely enough to make suggestions on how to address this, if you think it's worth the effort!

2.) There seems to be a problem with synchronization between the user table and the library cards table. I used the [Users] section of Demo.ini to test this with the Demo ILS driver, so I could see how things would behave when passwords changed in the underlying system. So, for example, try this series of events:

- Set up a user `testuser = testpass` in Demo.ini
- Go to the profile page and select testuser, confirming that the user shows up correctly.
- Now edit Demo.ini and change the password to something else.
- Refresh the profile page. Problem 1: the library card selection list is not visible, so bad credentials on one card can prevent all the other cards from being accessible.
- Go back to the library cards page, and edit the testuser card to change the password to the correct value.
- Now go to the profile page again -- even though the card has been updated, the authentication still fails. This is Problem 2. Do we need logic somewhere to check when a library card row is updated, and if the barcode matches the active user row, update that too? Or does that logic already exist but is somehow not working quite right in this scenario?

Anyway, let me know if you need more details to be able to reproduce this, or if I can do anything else to help move this along!

**Comment by EreMaijala** [comment]
@demiankatz How about this approach? Now the password field is always empty with just a placeholder.

**Comment by demiankatz** [comment]
@EreMaijala, I think this approach makes a lot of sense, though perhaps it justifies a new text string to make the behavior more explicit. Of course, now that I try to draft something that makes sense and still fits in the box, I find it rather challenging. "Enter new password if changed" or "Leave blank if unchanged" might work... but there's also the issue that the same form is used for "add" and for "edit," and none of this makes any sense in the add context.

On a different subject, do you have any thoughts on the (probably unrelated) synchronization issue I mentioned above?

**Comment by EreMaijala** [comment]
I still need to check the sync issue. It should work, of course. We can have different translations for new and existing card, or just use a placeholder only when editing an existing one. Which one would you prefer? I'd like to avoid adding new ones when possible.

**Comment by demiankatz** [comment]
@EreMaijala, I think we only need a placeholder when editing an existing user, since creating a new one should be pretty self-explanatory. If you're happy with the existing "New Password" placeholder, I can live with it for now since it's easy enough to customize... though maybe a compromise between devising a new string and reusing a sub-optimal string would be to copy the existing "New Password" string in all of the language files to a new key (like "librarycard_edit_password_placeholder") and use that. There's a command line tool that can take care of editing all of the language files... and then the customization can be taken care of through the language files without touching templates.

**Comment by EreMaijala** [comment]
@demiankatz Now everything should be fixed, including the problems you found with the profile page.

**Comment by demiankatz** [comment]
Thanks, @EreMaijala, this is looking much better. However, the profile page is still not behaving perfectly in the situation where a library card's password changes. Try this scenario:

1.) Set up two cards -- card A and card B.
2.) Go to the profile page.
3.) Change the password on card B so that the stored value in VuFind is invalid, then try to select it in the drop-down list.
4.) You now get a flash message about an invalid login at the top of the screen, the drop-down card list shows "card A" selected (but not card A data shown), and there is no login form shown to correct the problem.

Ideally, I think it would be better if the login form was shown pre-filled with the appropriate username, and the correct card was shown as active in the card drop-down list. Logging in again would update the card table. This way, the user could either fix the bad card credentials or toggle over to a different account.

Realistically, not being familiar with all of this code, I'm not sure how hard that would be to fix... it may be more trouble than it's worth. Let me know what you think!

**Comment by EreMaijala** [comment]
It should be doable. I'll check that once more.

**Comment by EreMaijala** [comment]
This is a bit complicated.. But how about now? I added the library card selection to the catalog login template so that a card can always be chosen. Unfortunately the previously selected card cannot be displayed as storedCatalogLogin() clears the credentials on unsuccessful login.

**Comment by demiankatz** [comment]
@EreMaijala, this is much better -- thanks! I'll merge now.

**Pull request merged**
