### PR TITLE
Fix: Bootstrap 5 theme carets

### PR DESCRIPTION
**Pull request by crhallberg**
Resolves [VUFIND-1703](https://openlibraryfoundation.atlassian.net/browse/VUFIND-1703).

Fixes dropdown carets in bootstrap5, bootprint5, and sandal5.

image

### CODE REVIEW

**Review by EreMaijala — CHANGES_REQUESTED** [review]
Thanks for working on this! Unfortunately I'm still seeing the problems with this branch, for example this with sandal5:
kuva

**Review by sturkel89 — CHANGES_REQUESTED** [review]
I'm having the same experience as Ere. I tried displaying the **4+ filters** dropdown in all the themes and in a couple of different browsers, and found that in the new themes the arrows are back in the right spot but there's a little ghost square still visible on the button. 

I documented every variation. All of the next set are in Chrome on Windows.

Bootstrap3:
image

Bootstrap5:
image

Bootprint3:
image

Sandal:
image

Sandal5:
image

The extra ghost box looks a little different on Firefox for Windows (Sandal5):
image

This issue is also present on mobile (Chrome using mobile emulator set for iPhone 13):
image

**Comment by crhallberg** [comment]
@demiankatz @sturkel89 Thanks! Looks like this is a release-10 but not a dev issue? I took care of it.

**Comment by demiankatz** [comment]
@crhallberg, I believe this was a dev + release-10.0 issue last Susan checked... I haven't had a chance to re-test myself, though. Let me know if you need me to!

**Comment by demiankatz** [comment]
This looks correct to me in sandal5 and bootstrap5. @sturkel89 and @EreMaijala, do you mind double-checking?

**Review by EreMaijala — APPROVED** [review]
I think that the vertical alignment of dropdown icons is now slightly worse, but it's also pretty much identical to bootstrap3's, so I suppose that's ok.

**Review by demiankatz — CHANGES_REQUESTED** [review]
I see that the build is now failing because search.scss is out of sync between the themes. In this instance, I believe that is intentional. Do we need to add a new exception to build.xml, or is there another way we could address this? Any suggestions, @EreMaijala?

**Comment by EreMaijala** [comment]
@demiankatz Right, of course. I'd try to keep the files in sync and counter the rules in bs3-compat.scss instead. If that doesn't work at all, then a new exception would be needed, but I'd try to cope without having to do that.

**Comment by demiankatz** [comment]
Makes sense! @crhallberg, what do you think?

**Review by sturkel89 — COMMENTED** [review]
I don't know about the build failing, but in my visual inspection I see that the little extra boxes are now gone. Looks good enough for my purposes, in both sandal5 and bootstrap5.

Sandal5:
image

Bootstrap5:
image

**Comment by demiankatz** [comment]
@sturkel89, do you mind taking one more look at this now that @crhallberg has adjusted things to make the build pass?

**Review by sturkel89 — CHANGES_REQUESTED** [review]
I pulled down the updates and tested this branch with OR and Exclude facets turned on. 

In both Firefox and Chrome, I'm seeing the little extra boxes in both Sandal5 and Bootstrap5; the legacy themes look fine. 

For reference, everything looks as it did in one of my [past reviews](https://github.com/vufind-org/vufind/pull/3853#pullrequestreview-2228638543).

**Comment by demiankatz** [comment]
Since @crhallberg is out of office for a few days, I put a few minutes into this and I think I've solved the problem, though I'm not sure if my solution is the most elegant possibility.

@sturkel89, can you re-test?

@EreMaijala, do you have any opinions on my latest commit?

**Review by sturkel89 — APPROVED** [review]
I checked the latest version of the test branch in Chrome, Firefox, and even Edge on Windows. **Looks perfect in all themes on all three!!** 

For good measure, I checked Sandal5 using my mobile emulator. Even that looks good:

image

I think we're ready to merge, once Ere approves the code. :)

**Review by EreMaijala — APPROVED** [review]
Thanks, this looks good to me now!

**Review by demiankatz — APPROVED** [review]

**Pull request merged**
