### PR TITLE
Always set $VUFIND_HOME to an absolute path.

### PR DESCRIPTION
**Pull request by Witiko**
When `index-alphabetic-browse.sh` is invoked as `./index-alphabetic-browse.sh` from the `/usr/local/vufind/` working directory, and the `VUFIND_HOME` environmental variable is unset, `VUFIND_HOME` is set to the relative path `.`. Since `index-alphabetic-browse.sh` changes the working directory to `import`, `$CLASSPATH` points to non-existent files, and the script fails with a `java.lang.NoClassDefFoundError: org/apache/lucene/search/Query` exception.

This PR proposes using `readlink(1)` from GNU coreutils to always resolve `$VUFIND_HOME` to an absolute path, thereby solving the above issue.

### CODE REVIEW

**Comment by demiankatz** [comment]
@Witiko, the import-marc.sh script was recently changed to determine VUFIND_HOME in a different way:

https://github.com/vufind-org/vufind/blob/master/import-marc.sh#L70

(`export VUFIND_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"`).

I believe that should also yield an absolute path. Is there a reason that the `readlink` approach is preferable? If not, I think it would probably be best to define VUFIND_HOME consistently across scripts to make the code and behavior more predictable. What do you think?

In any case, thanks for catching this problem -- one way or another, we should definitely take care of it!

**Comment by Witiko** [comment]
> Is there a reason that the readlink approach is preferable?

@Demiankatz, they should be virtually equivalent. One subtle difference would be that `pwd(1)` does not resolve symlinks along the pathname, whereas `readlink(1)` returns a canonical pathname. Other than that, I can't think of any other differences off the top of my head, and by looking at the manpages. Both `pwd(1)`, and `readlink(1)` are also a part of GNU coreutils, so neither introduces additional requisites. If it were up to me, I would choose the more readable of the two, and apply it consistently across the shell scripts for ease of maintenance.

Note that there are also other inconsistencies between `import-marc.sh`, and `index-alphabetic-browse.sh`:

1. The former (`import-marc.sh`) exports `VUFIND_HOME`, making it an environmental variable, although none of the processes the script executes (solrmarc, and some unix utilities) will make use of this environmental variable. The latter (`index-alphabetic-browse.sh`) does not export `VUFIND_HOME`, keeping it just a shell variable.
2. The former cautiously parenthesizes the pathname, whereas the latter will break with a pathname that contains spaces (or whatever the shell variable `IFS` contains).

These should be probably also reconciled.

**Comment by demiankatz** [comment]
@Witiko, regarding the inconsistencies -- the "export" of VUFIND_HOME was recently added to import-marc.sh based on the concern that Java would be unable to read the environment variables otherwise (since SolrMarc does make use of VUFIND_HOME in several places). I did not take the time to confirm whether or not this is strictly necessary, but it seemed a harmless enough adjustment.

Regarding cautiously parenthesizing names, it seems worth doing.

I'm going to have a very busy week due to some other projects I'm involved in. If you have time and desire to make further adjustments to this PR, please feel free to do so. If you are also busy, I can see about finding time to move this forward on my end next week.

**Comment by Witiko** [comment]
> SolrMarc does make use of VUFIND_HOME in several places

I was not aware of that. Oddly, I don't see any mention of this in the source code of solrmarc:

```
$ git clone https://github.com/solrmarc/solrmarc
$ cd solrmarc
$ find -type f -exec grep -i VUFIND {} +
Binary file ./.git/objects/pack/pack-bbe31e2af02aa11e9b00a96512a06717d834dcc3.pack matches
./.git/packed-refs:733b43f14dbac92210ca3c5fb5b46b17544030c9 refs/remotes/origin/vufind/improved-author-indexing
Binary file ./.git/index matches
./src/org/solrmarc/index/SolrIndexer.java:     * searching. Shameless stolen from Vufind Indexer Custom Code
./src/org/solrmarc/index/SolrIndexer.java:     * searching. Shameless stolen from Vufind Indexer Custom Code
./src/org/solrmarc/index/SolrIndexerShim.java:     * searching. Shameless stolen from Vufind Indexer Custom Code
./src/org/solrmarc/index/SolrIndexerShim.java:     * searching. Shameless stolen from Vufind Indexer Custom Code
./src/org/solrmarc/index/extractor/impl/date/DateOfPublicationValueExtractor.java:        // TODO: Use VuFindIndexer#getPublicationDate(Record)
./test/data/getdatetest.properties:default.customClass = org.solrmarc.mixin.VuFindGetDate
./test/data/getdatetestoverride.properties:#date_display += custom(org.solrmarc.override.VuFindGetDateOverride), getDates
./test/data/getdatetestoverride.properties:date_display = custom(edu.solrmarc.override.VuFindGetDateOverride), getDates
./test/data/index_java/src/org/solrmarc/mixin/VuFindGetDate.java:public class VuFindGetDate
./test/data/local/index_java/src/edu/solrmarc/override/VuFindGetDateOverride.java:public class VuFindGetDateOverride extends SolrIndexerMixin
```

> If you have time and desire to make further adjustments to this PR, please feel free to do so. If you are also busy, I can see about finding time to move this forward on my end next week.

I will set aside time to polish the code some more by the next week.

**Comment by demiankatz** [comment]
@Witiko, you are correct that SolrMarc itself does not include any references to VUFIND_HOME, but the VuFind project includes its own SolrMarc extensions that do reference the variable. You can find them here:

https://github.com/vufind-org/vufind/tree/master/import/index_java

SolrMarc dynamically compiles this code at runtime.

I hope that helps clarify what is going on; let me know if you have any questions or concerns, or if you'd like any assistance with future revisions. Thanks again for taking the time to help improve this!

**Comment by Witiko** [comment]
Thank you for the explanation, @demiankatz. I added the definition of `$VUFIND_HOME` to all shell scripts in the repository.

Note that although the `$VUFIND_DEFINITIONS` definitions are parenthesized, most scripts will break with whitespaces in the path anyway (see `$BASEPATH` in `harvest/batch-*.sh`, the use of `exec` built-in in `import/bin/import.sh`, and `import/marc.sh`, and overall lack of parenthesization when dealing with variables).

**Comment by demiankatz** [comment]
@Witiko, thanks for this! One note: some of these scripts are in subdirectories of $VUFIND_HOME, so I think the code may have to be adjusted to $0/.. to get to the right place. Did you test any of these?

Regarding lack of parenthesization, it would definitely be good to clean that up when time permits, but it's probably a less urgent problem. If you want to deal with it, I'd certainly welcome a PR, but no pressure. You could also just open a JIRA ticket as a reminder to deal with this later.

**Comment by Witiko** [comment]
With `cd $(dirname $0)/..`, we might accidentally go back through a symlink on some operating systems including Linux:

```
$ ln -s /usr/local/vufind/harvest /tmp/harvest
$ VUFIND_HOME=$(cd /tmp/harvest/.. && pwd -P)
$ echo $VUFIND_HOME
/tmp                          # incorrect
$ VUFIND_HOME=$(cd /tmp/harvest && pwd -P)/..
$ echo $VUFIND_HOME
/usr/local/vufind/harvest/..  # correct
```

I tested that the scripts correctly set `$VUFIND_HOME` by moving the `$VUFIND_HOME` definition to the top, adding `echo $VUFIND_HOME; exit`, and running the scripts from a shell with no environmental variable `VUFIND_HOME`. Of course, larger incursions into the code would benefit from a set of automatic tests.

**Comment by Witiko** [comment]
@demiankatz, with `cd $(dirname $0)/..`, we might accidentally go back through a symlink on some UN*X operating systems including Linux:

```
$ ln -s /usr/local/vufind/harvest /tmp/harvest
$ VUFIND_HOME=$(cd /tmp/harvest/.. && pwd -P)
$ echo $VUFIND_HOME
/tmp                          # incorrect
$ VUFIND_HOME=$(cd /tmp/harvest && pwd -P)/..
$ echo $VUFIND_HOME
/usr/local/vufind/harvest/..  # correct
```

I tested that the scripts correctly set `$VUFIND_HOME` by moving the `$VUFIND_HOME` definition to the top, adding `echo $VUFIND_HOME; exit`, running the scripts from a shell with no environmental variable named `VUFIND_HOME`, and reading the output. Of course, larger incursions into the code would benefit from a set of automated tests.

**Comment by demiankatz** [comment]
Thanks, @Witiko, this looks good -- I'll do a few double-checks out of an abundance of caution and then will likely merge later this week.

**Pull request merged**
