### PR TITLE
Handle question marks consistently in basic and advanced queries.

### PR DESCRIPTION
**Pull request by demiankatz**
- Resolves [VUFIND-1217](https://vufind.org/jira/browse/VUFIND-1217)

### CODE REVIEW

**Comment by demiankatz** [comment]
I've run the full integration test suite on this, and everything is passing.

**Comment by demiankatz** [comment]
I significantly revised the logic in an effort to cover more cases and reduce redundancy; tests are still passing, but a bit more review would be helpful.

**Comment by demiankatz** [comment]
@EreMaijala, that is definitely not intentional. I believe that this is simply magnifying an existing problem that has been present since the major search refactoring of VuFind 2 -- there were already a few edge cases where query processing would leak through to the public view, this just happens to be a much more obvious instance of the problem.

In any case, I agree that this is undesirable. I'll devote some time to finding a solution when I'm back in the office next week.

**Comment by demiankatz** [comment]
At a glance, it looks like the problem is that the build() method is calling $query->setString, which is modifying the object that gets passed in. I think if we simply clone the object as the first action of the method, that should sort everything out. Feel free to try it if you have time before next week... but don't worry if you don't.

**Comment by EreMaijala** [comment]
Are there still situations where the modified search string should be displayed to the user? If so, I think we should have two stages when creating the query: First the user-visible changes and then the cloning and invisible changes.

**Comment by demiankatz** [comment]
I can't think of any situation where we would want the user to see the modified query -- I think it has always been an inadvertent side effect of passing the query object by reference. In my opinion, the query builder should not have side effects, and the user should always be presented with exactly the text that they entered to avoid confusion.

**Comment by EreMaijala** [comment]
I agree with that. I'll test cloning.

**Comment by EreMaijala** [comment]
Cloning seems to work and I really like it that now the modifications that used to show uå are hidden too. I pushed the change.

**Comment by demiankatz** [comment]
Thanks!

**Pull request merged**
