### PR TITLE
Adding remote service to DAIA driver

### PR DESCRIPTION
**Pull request by olli-gold**
This PR adds the new 'remote' service to the DAIA driver. The new service remote is used for electronic items, which are available online. The service is described in the DAIA specification: http://gbv.github.io/daia/daia.html#services

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks for sharing. A few questions:

Do we need some template/translation file changes to accompany this? Is anything currently making use of that new 'weblink' value. If not, should we add something?

**Comment by olli-gold** [comment]
I can tell a little bit more about the background, why I added this.

The DAIA specification has an availability attribute named **remote**, which is used for non-ILS-links for the resource (that's why I added it as a new value in VuFind as well, and did not map it to the existing ilslink value). An example is this item in tub.find: https://katalog.tub.tuhh.de/Record/669342122; it does not have a physical copy, but only a weblink, which is delivered via DAIA in the remote attribute (cf https://paia.gbv.de/DE-830/daia?id=opac-de-830:ppn:669342122&format=json). 

Normally this should be covered by the link resolver, but as you see in this example, we have some cases, where this does not work (for whatever reason). So the link supplied by DAIA can be very helpful for us.

I guess this could be interesting not only for our library, if the driver and the availability information have a similar option as we have in DAIA. As its an addition, I think we could expand the templates and could add the new weblink field.

**Comment by olli-gold** [comment]
I have added the new field to the full record view holdingstab template.

**Comment by olli-gold** [comment]
Thank you for your comments! I have changed the position of the weblink display and have removed the placeHold classes.
Of course we could design a weblink_label field for VuFind, but DAIA will not be able to support it right now. Unfortunately DAIA does not provide a label for link names.
Also I have not tested the impact on the detailed availability status messages (I guess you mean the messages used in the result list?). We have heavily customized the result list, as I have presented on this year's summit, so my first intention for this PR was to propose a new field for the links. Admittedly, I have no certain idea how to integrate it into the default detailed availability status.

Feedback from other DAIA users would be very welcome! If @lahmann has any input on that, this would be great. But perhaps also @jochen-lienhard, @Hirnfiedler or @Cloud8 have an idea about that.

**Comment by demiankatz** [comment]
I guess the next step is to add parallel functionality to the Demo ILS driver so thus of us without a DAIA-compatible ILS can see how this works in VuFind. I'll wait for others to comment before proceeding, but I can try to work on that in the near future if you don't have time.

**Comment by demiankatz** [comment]
@olli-gold, I haven't heard anything about this PR in a few months. I'm re-flagging @jochen-lienhard, @Hirnfiedler and @Cloud8 in this sentence just in case they have input but missed this conversation due to its proximity to the holidays. Please let me know if you think it would be worthwhile for me to do some work on the Demo driver to make it easier to test this behavior without access to DAIA.

**Comment by jochen-lienhard** [comment]
The DAIA Service - we are using - does not support the remote service, so we are not affected by this modification.

**Comment by Hirnfiedler** [comment]
The situation at HeBIS is quite the same as in Freiburg. We don't use 'remote'.

**Comment by Cloud8** [comment]
I have just indexed a record with restricted online access. I have found no serious problems with this PR until now, so only a few remarks on this: 

  * The weblink in holdingsils.phtml renders to a lightbox, such that it doesn't display properly. 
  * The holding status is translated to "Verfügbar als remote", which sounds a bit strange
  * I would prefer a weblink_label field as mentioned above. 
     Maybe, this can be suggested to http://gbv.github.io/daia/daia.html ?

**Comment by demiankatz** [comment]
@olli-gold, this is now one of our oldest open pull requests, and there hasn't been activity here in quite some time. Is there still a need for this? Is there anything I can do to help move the code and/or conversation forward? I'm happy to merge master into this branch and get things up to date if that would be useful. It sounds like @Cloud8 found some issues that need to be addressed before this can be merged....

**Comment by olli-gold** [comment]
Unfortunately my focus has changed this year, so that I'll not be able to finish this PR. I would say, it's not critical and the changes proposed by @Cloud8 sound pretty easy, but I will not be able to test it now and this makes it a bit hard to introduce this new feature.
So I would propose to close this PR without any action as it seems that nobody really needs it (even we do not use this modification in production today)...

**Comment by demiankatz** [comment]
Thanks, @olli-gold, I will close it for now. If @Cloud8 or anyone else feels there is a need for this, please feel free to reopen. I am willing to contribute assistance as needed, but I am also in the position of being unable to test, so obviously there is no point in moving forward without somebody actively desiring the functionality!

**Pull request closed without merging**
