### PR TITLE
Turn off no-JS hierarchy support by default.

### PR DESCRIPTION
**Pull request by demiankatz**
TODO
- [x] Discuss
- [x] Update changelog when merging

### CODE REVIEW

**Comment by demiankatz** [comment]
@EreMaijala, it occurred to me that we could improve hierarchy performance without totally ripping out the non-Javascript support simply by making the option configurable. This PR adds that option, and defaults it to false. I'm certainly open to more aggressive removal in the future, but this is the most conservative way to begin deprecating the feature. Any objections?

Also, are there any other non-JS features you'd like to see removed? A quick survey of the templates for `<noscript>` tags suggests that there aren't too many major offenders. Hierarchical facets are probably the next-most-complicated feature, but I'm not sure if that's introducing enough overhead to cause any problems.

**Comment by EreMaijala** [comment]
No objections. I think hierarchical facets should be done too. Depending on the index the overhead may actually be significant.

**Comment by demiankatz** [comment]
Thanks, @EreMaijala. I've made the configuration more general so we can use a single setting to turn all of the expensive non-JS stuff on and off, and I've extended its use to control both hierarchy trees and hierarchical facets. Along the way, I did some significant refactoring of the templates displaying hierarchical facets in an effort to improve clarity. I think this is ready to merge, but I'd appreciate if you could give it one more look!

**Comment by EreMaijala** [comment]
@demiankatz Thanks, looks good to me!

**Comment by demiankatz** [comment]
Thanks for the confirmation -- merging now!

**Pull request merged**
