### PR TITLE
Translate subject email with translate function

### PR DESCRIPTION
**Pull request by LuomaJuha**
If @EreMaijala  wants to say something about this.

### CODE REVIEW

**Review by EreMaijala — CHANGES_REQUESTED** [review]
This breaks all placeholders.

**Comment by demiankatz** [comment]
Doesn't passing the tokens to the translate function address that? Or am I missing something?

Sounds like test coverage would help clarify matters, if we don't already have it. (But if we do have it and the tests are passing, that would seem to me like a good sign).

**Review by EreMaijala — APPROVED** [review]
Err.. yes. I don't know how I misread this. Sorry!

**Review by demiankatz — APPROVED** [review]

**Comment by demiankatz** [comment]
I'm going to go ahead and merge this now -- it actually seems like a bug fix since the comments in the .yaml file indicate that email subjects are translated, but the actual behavior was not doing that previously.

It does seem like it might be valuable to add a test case that covers the placeholder functionality of email subjects, since that doesn't seem to be addressed in the current test suite... but I won't hold this up on that point alone. Merging now!

**Pull request merged**
