### PR TITLE
Added raw explanation button

### PR DESCRIPTION
**Pull request by ThoWagen**
Sometimes it is useful to see the raw explanation instead of the graphical representation. This PR adds a button to show that.

### CODE REVIEW

**Review by demiankatz — CHANGES_REQUESTED** [review]
Thanks, @ThoWagen, this is great! I just noticed one style issue -- in the sandal5 theme (and ONLY the sandal5 theme, not the raw bootstrap5 theme), the new button becomes nearly invisible when it is focused but does not have the mouse hovering over it:

image

I suspect this may be revealing an existing problem with the new theme that we simply haven't noticed before, so it might be best to address it in a separate PR. I'm just going to leave this one open until we figure it out.

If you can't easily identify the cause, perhaps @EreMaijala will have an idea since he's more familiar with the bootstrap5 themes than anyone else at this point.

**Review by demiankatz — APPROVED** [review]
I spoke with @EreMaijala, and he confirmed that the button style issue is pre-existing, so I'm going to go ahead and approve/merge this PR. The styles can be fixed separately in a PR targeting the release-10.0 branch.

**Comment by ThoWagen** [comment]
@demiankatz @EreMaijala The problem seems to come from these lines https://github.com/vufind-org/vufind/blob/b97e2b278018050a7e2419ec5eea687c85dfef8f/themes/sandal5/scss/common.scss#L24-L29 and the fact that in bootstrap5 clicked buttons stay focused until you clicks somewhere else. But since there is a comment about that anyway should I just create a PR and remove that part?

**Comment by demiankatz** [comment]
Thanks, @ThoWagen -- if you don't mind opening a PR targeting the release-10.0 branch and removing those lines, I think that would be a good start! Note that because sandal5 is auto-generated from sandal, we'll need to remove the lines from sandal as well. We should see if that has any negative side effects on this button. (I believe @EreMaijala mentioned that this also impacts buttons on the advanced search page, so we could look for impacts there as well).

**Pull request merged**
