### PR TITLE
Fix overlapping media-left box on EDS records

### PR DESCRIPTION
**Pull request by maccabeelevine**
The `.media-left` links are set to `white-space: nowrap;` which causes overlap problems with links on EDS.  The problem exists on both mobile and full-width viewports although there is a window around 550px to 776px where it looks ok.

Desktop:

image

Mobile:

image

### CODE REVIEW

**Comment by maccabeelevine** [comment]
With this PR.  Mobile does not look great but it's an improvement over clipping half the text.

image

image

**Review by crhallberg — APPROVED** [review]
Thanks! I've been thinking about removing as many <br> as possible.

**Comment by maccabeelevine** [comment]
> Remove accidentally committed file

🤦

**Comment by sturkel89** [comment]
Demian asked me to look at this PR. We think that having the PDF and HTML links in the sidebar are Lehigh customizations. I don't have things set up that way in my test environment, so I had to emulate having content in the sidebar by modifying the "View in EDS" label in the en.ini language file.

In my experiments, that sidebar text **does not scroll around** to fit in the sidebar with a buffer between it and the rest of the record. 

In both test and dev, the extra text in the sidebar continues straight across behind whatever elements are present on the right-hand side of the screen. See below for results of my tests.

**Condition 1: Long words in sidebar text**

**Test branch: full screen**
image

**Test branch: mobile**
image

**Dev branch: full screen**
image

**Dev branch: mobile**
image

### Condition 2: Short words in sidebar text

**Test branch: full screen**
image

**Test branch: mobile**
image

**Dev branch: full screen**
image

**Dev branch: mobile**
image

**Comment by maccabeelevine** [comment]
> Demian asked me to look at this PR. We think that having the PDF and HTML links in the sidebar are Lehigh customizations.

Hi @sturkel89, thanks for reviewing this!  So it's the PDF link is [here in EDS/core.phtml](https://github.com/vufind-org/vufind/blob/366f72d843d2ff372a1d93e0e912bb5b66d321ba/themes/bootstrap3/templates/RecordDriver/EDS/core.phtml#L34) and the the HTML link is about 15 lines below.  So those aren't Lehigh-specific, although it's certainly possible that they are only activated based on some settings in EBSCOadmin or whatever other admin UI. 

>  I don't have things set up that way in my test environment, so I had to emulate having content in the sidebar by modifying the "View in EDS" label in the en.ini language file.  In my experiments, that sidebar text **does not scroll around** to fit in the sidebar with a buffer between it and the rest of the record.

This test would not work unfortunately because the key CSS line does a `white-space: normal;` (as opposed to the inherited `nowrap`) on `.media-left .external-links > span a.icon--eds`, but the "View in EDS" [link element](https://github.com/vufind-org/vufind/blob/dev/themes/bootstrap3/templates/RecordDriver/EDS/core.phtml#L21) has no icon and so no `icon--eds` class.

You could test it by adding a new `span` below the View in EDS one that has a link with the necessary classes, i.e. 

        <span>
          <a href="foo.html" class="icon--eds pdf fulltext">
            PDF Full Text
          </a>
        </span>

**Comment by demiankatz** [comment]
I figured out why @sturkel89 was failing to see the full text links -- it's because they only load when you tell the API that there is a logged in user, and that only happens if you set up an appropriate permission setting.

Try this -- customize permissions.ini with these settings:

```
[default.EDSModule]
role[] = loggedin
permission = access.EDSExtendedResults
```

(You can just add those lines at the bottom if that's easiest).

Now create an account and log in, and the full text links should appear.

Sorry for not realizing this sooner!

**Comment by maccabeelevine** [comment]
> Ah I didn't realize this either!  Sorry for the confusion, I was looking only at EDS.ini but I do have something similar to that in place in permissions.ini.  Actually I can get the HTML Full Text link to appear even the entire [default.EDSModule] section commented out, but the PDF link requires that `permission` line and some role; (`guest`) seems to work as well for me.

Yes, you can set both guest and loggedin roles to make the links appear universally -- but the advantage to only setting the loggedin role is that it lets you test both behaviors if you need to. :-)

**Comment by sturkel89** [comment]
Thanks for the advice! I was able to get everything loaded once I added in and customized permissions.ini.

I tested the branch in all three themes, and in mobile in addition to fullscreen. In test, the link text associated with downloadable full text fits nicely in the left column with some padding between that column and the right-hand column. 

In dev, the link text continues across the screen and appears behind the content on the left.

See examples:

### **Test - full screen**
**Sandal**
image

**Bootstrap3**
image

### **Dev - full screen**
image

### **Test - mobile**
image

### **Dev - mobile**
image

-------
### Possible problem:

There are two kinds of full text available for the selected item, but only the ePub link appears. The PDF icon and link text is not showing for this item in record view, although it's clearly there in search results view:

image

I checked this with every combination of full text availability:
- Only a PDF? The PDF link appears in the sidebar
- Only ePub full text? The ePub link appears in the sidebar
-  Both kinds of downloadables? The ePub link appears but the PDF is nowhere to be found in record view.

**This is found in both test and dev.**

I'm sure there's an explanation, but I don't know what it is.

**Comment by maccabeelevine** [comment]
> There are two kinds of full text available for the selected item, but only the ePub link appears. The PDF icon and link text is not showing for this item in record view, although it's clearly there in search results view:

@sturkel89 I can reproduce this when `role[] = guest`, although if I then click the PDF icon on the search results, I get a permissions error.

I believe it's a bug and I'll open a separate PR for it.  The results list (full-text-links.phtml) is asking `hasPdfAvailable` but that function is not checking as vigorously as the `getPdfLink` called by the item page (it's not checking that a URL is actually present).

**Comment by maccabeelevine** [comment]
> I believe it's a bug and I'll open a separate PR for it. The results list (full-text-links.phtml) is asking `hasPdfAvailable` but that function is not checking as vigorously as the `getPdfLink` called by the item page (it's not checking that a URL is actually present).

Actually I'm not sure anymore of that solution; I'll open a Jira instead for discussion first.

**Comment by demiankatz** [comment]
Thanks, @sturkel89 and @maccabeelevine! Since the problem Susan reports seems unrelated to the work here, I'll go ahead and merge this and await @maccabeelevine's follow-up.

**Comment by maccabeelevine** [comment]
FYI https://openlibraryfoundation.atlassian.net/browse/VUFIND-1689

**Pull request merged**
