### PR TITLE
Fix bug: lightbox covers interfered with preview links

### PR DESCRIPTION
**Pull request by demiankatz**
The support of lightbox images broke the feature where book previews would update the thumbnail to link directly to the preview. This PR fixes the problem by making some additional adjustments to the image link.

To test:

In the `[Content]` section of config.ini, set `previews=Google`

Do a search for `title:html` to bring up one of the records that should have a working Google preview.

You'll see that cover thumbnails are clickable in this PR but do not work in the plain release-10.1 branch.

### CODE REVIEW

**Review by sturkel89 — APPROVED** [review]
I've tested this branch using the default theme only. Following the instructions above, I found that for random items on the results list, I could click the cover image placeholder and get a lightbox displaying the same placeholder image:

image

For the `<HTML> The Basics` item, I clicked the cover image and was brought to a full Google Books preview in a new tab. (The preview was of a novel called "The Test.")So, if that's the intended outcome, it works! 

NB: I think I would prefer the action of clicking a cover image to produce a lightbox showing the cover, just for consistency with all the other records. There's a Google Preview button in the record for books having that feature, and I could click that if I wanted to see the full preview.

-----------

I ran the same tests in the release-10.1 branch. 
- For the books without Google Previews, I clicked the cover and got a lightbox for the cover image. 
- For the `<HTML> The Basics` item, the cursor turns into a finger but nothing happens when I click.

**Comment by demiankatz** [comment]
Thanks, @sturkel89, the behavior you describe sounds correct.

The preview thumbnail override is done because in many cases, the preview will provide a better cover image than the normal cover providers. However, it could make sense to make that behavior configurable. Changing behavior is beyond the scope of this PR, which is just intended to restore the existing intended functionality... but if you think it's worth the effort to add a setting for this, please feel free to open a JIRA ticket and we can address it as a next step!

Would you mind repeating your test one more time in the bootstrap3 theme, just to be sure this is properly backward-compatible there?

**Comment by demiankatz** [comment]
@sturkel89, there's no need to create a JIRA ticket for cover link behavior configurability; it's already configurable!

https://github.com/vufind-org/vufind/blob/dev/config/vufind/config.ini#L1208-L1212

It defaults to "on" but can be easily turned off.

**Comment by sturkel89** [comment]
@demiankatz, I just loaded my theme switcher config.ini file and tested the behavior in all five themes. All works well! 

In every theme, when I click the cover thumbnail placeholder, the Google Preview pops up in a new tab.

Thanks for confirming that each installation has the option to just pop up a lightbox if they prefer. :)

**Review by crhallberg — APPROVED** [review]

**Pull request merged**
