### PR TITLE
Removing duplicate URLs generated in getLinkDetails()

### PR DESCRIPTION
**Pull request by kristofkessler**
Unserialization of mult-dimensional array to remove duplicates to then serialize the array again. Drawback here is that in cases in which the url is the same, but the desc value is different, these duplicates will remain, example:
array(5) { 
[0]=> array(2) { ["url"]=> string(59) "http://elib.tiho-hannover.de/dissertations/leidelf_ws14.pdf" ["desc"]=> string(59) "http://elib.tiho-hannover.de/dissertations/leidelf_ws14.pdf" }
[1]… 
[2]… 
[3]=> array(2) { ["url"]=> string(59) "http://elib.tiho-hannover.de/dissertations/leidelf_ws14.pdf" ["desc"]=> string(9) "full text" } 
[4]… 
} }

### CODE REVIEW

**Comment by demiankatz** [comment]
Do you think you are likely to encounter cases where you have the same URL with multiple descriptions? If not, this is at least a good first pass that probably meets your needs. If so, we might as well try to solve the full problem now. I have a few ideas for how to approach it, though the main challenge is picking out which description to use (one obvious approach would be to favor a description which differs from the URL over a description that simply IS the URL... but I don't know what we do if we have two different descriptions).

**Comment by qlumbus** [comment]
Indeed, I had not thought about what to do if the same URL appears multiple time with different descriptions. So far I only encountered cases in our dataset with one URL having a description and the other URL having no desription, i.e. desc being equal to url. I wonder if merging the descriptions might be a good option, i.e. something like url[1]['desc']."/".url[2]['desc']. I suppose that could lead to some odd outcomes as well. I will look into a solution.

(Btw, what does it mean if the Travis CI build failed?)

**Comment by demiankatz** [comment]
I also considered the possibility of merging the descriptions and agree that, depending on circumstances, it might or might not be a good solution. Perhaps the answer is, whatever you do, to create a protected support method that does the deduplication so it can be made configurable or overridden as needed.

Travis is a continuous integration system -- it checks to make sure that all tests pass when changes are made to the code. If you click the "Details" link in the fail notification on this PR, you'll see that the failure is caused by minor style issues -- two lines of code exceed the limit of 85 characters. Usually these things are easy to fix. The other likely failure you'll see is an error code from php-cs-fixer-dryrun, which simply means that there are some style adjustments that can be automatically fixed by running "phing php-cs-fixer" on the code (assuming that you have Phing and php-cs-fixer installed, of course). Let me know if you have questions about any of this! It's a nice way to ensure uniformity of code and catch bugs with minimal effort.

**Comment by qlumbus** [comment]
I edited my changes and created a protected class. Well, it is not configurable and I suppose it could be more efficient. What do you think?

**Comment by demiankatz** [comment]
I think you might be able to simplify this with the help of an array used as a hash table to references in your deduplicated array... something like:

<pre>
    $deduped = [];
    $urlLookup = [];
    foreach ($urls as $url) {
        if (!isset($urlLookup[$url['url']])) {
            $i = count($deduped);
            $deduped[] = $url;
            $urlLookup[$url['url']] = & $deduped[$i];
        } else {
            if ($urlLookup[$url['url']]['desc'] === $url['url']) {
                // previous description was just a URL; replace it!
                $urlLookup[$url['url']]['desc'] = $url['desc'];
            } else if ($url['url'] !== $url['desc']) {
                // current description is not a URL; append it!
                $urlLookup[$url['url']]['desc'] .= ' / ' . $url['desc'];
            }
        }
    }
    return $deduped;
</pre>

That's untested code and might not work quite as expected... but hopefully you see the general idea!

**Comment by qlumbus** [comment]
Works. Indeed this is simpler, saves a loop and some conditions.

**Comment by demiankatz** [comment]
Some more thoughts:

1.) This needs some style fixes to make Travis happy -- I think mostly having to do with using spaces instead of tabs for indenting. Also, I'd recommend renaming dedupe_urls to dedupeUrls since we prefer camelCase for method names. I'm happy to help with style issues if it saves you time, but if you want to get practice on this stuff, this is a good opportunity.

2.) One detail that I neglected in my refactoring was to deal with duplicate non-URL descriptions. If you have three entries with the same description, you'll likely end up with 'desc / desc / desc' instead of just 'desc'. I can think of two approaches: a.) check if the new description is a substring of the old description prior to merging -- simple, but the final result may vary depending on the order of inputs or b.) collect an array of descriptions during the first loop, then run a second pass to array_unique and implode the array -- the results will be more consistent regardless of input order, but the code is a bit more complicated.

What do you think?

**Comment by qlumbus** [comment]
Re 1: I will certainly do the reformating!
Re 2: We could simply add this line before the foreach loop: $urls = array_map('unserialize', array_unique(array_map('serialize', $urls))); (The line I used before to remove all items that have the same url and desc values.

**Comment by demiankatz** [comment]
There's another problem here: the URLs are currently being deduplicated before they are processed. While the most common type of link just has url/desc keys, some also use VuFind routes to generate URLs dynamically. We can't deduplicate the URLs before they have been generated, and in cases where they have been generated, there are going to be additional values in the array beyond 'url' and 'desc'. Thus, you could theoretically end up with duplicate url/desc combinations that would not be removed by the serialize/unserialize trick due to the presence of other keys.

One part of the solution is simply to move the deduplication line lower in the method -- that's a must.

Another part of the solution may be to rewrite the URL array to eliminate all keys other than url and desc. I suspect this is safe, but it will require a bit of code review to be totally sure we're not relying on any other key outside of the link processing method. Let me know if you'd like help with that -- I probably don't have time today but I can dig around a bit next week.

**Comment by qlumbus** [comment]
I had not thought about this. I will look into it next week as well.

**Comment by achanga** [comment]
Hello demian,

Kindly help me.  I am set up vufind that intergrates with dspace, it's able to fetch records from dspace but i would like it to display thumbnails which it is missing at the moment.

Would like to know how i can configure ILS driver to work. Looking forward for yor response.
Thank you


Robert Achang'a
University of Nairobi Kenya

**Comment by demiankatz** [comment]
Robert,

I have sent you an email in reply to your questions so we don't have a long off-topic conversation in this pull request thread. If you do not receive it, it probably means I picked the wrong address for you -- in that case, please send me an email at demian.katz@villanova.edu and I'll resend the message!

thanks,
Demian

**Comment by demiankatz** [comment]
@qlumbus, it's been a few months -- just checking if this is still on your to-do list, or if you need me to take any action! Thanks!

**Comment by demiankatz** [comment]
I'm closing this PR since it has been inactive for more than two years, and the implementation needs significant revisions. I've opened a JIRA ticket at https://vufind.org/jira/browse/VUFIND-1277 to track the functionality request, so we can easily revisit it in future if there is sufficient interest.

**Pull request closed without merging**
