### PR TITLE
use id field in getBibId function

### PR DESCRIPTION
**Pull request by ihardy**
Return instance id here instead of first identifier. Consider adding a configuration to use hrid if desired.

### CODE REVIEW

**Comment by ihardy** [comment]
Hi @demiankatz 
>I propose that we call native FOLIO IDs instance IDs, holding IDs and item IDs as appropriate, and we use the "bib ID" terminology to refer to whatever identifier VuFind is configured to use as its primary index ID.

This seems clear, and overall that sounds like a good plan to me, I'm able to put some time into it particularly with review and testing

**Comment by demiankatz** [comment]
Thanks, @ihardy, much appreciated! I'm probably not going to have more time for this today, but I'll see if I can carve out some time next week to draft some revisions (if nobody else gets there first).

**Comment by demiankatz** [comment]
@ihardy, I've just taken a stab at completing steps 1, 3 and 4 of my proposed actions, but I haven't tested it. This separates fetching an instance object from extracting an instance ID from an instance object into separate functions, cleans up some terminology, and ensures that all bib ID determination goes through the getBibId function. In the process, I also found a bug where an instance ID was being inserted into an item ID field, so I fixed that.

Still to do: adding the configuration setting to determine which value is used as a bib ID, and making sure appropriate queries are generated when looking up instances with bib IDs.

I thought it best to pause here for your testing/review before adding another layer of complexity to the changes. Once this looks good and is working for you, I'll go ahead and do the rest.

**Comment by ihardy** [comment]
Thanks @demiankatz this looks good to me, I've sent you a link for your review in slack if you'd like. One thing I've noticed is holdings information coming back pretty slowly, I think this is because of the operator used in the CQL queries ("=" vs "==") where double equals means exact match, and single equals is fuzzier. See: https://github.com/folio-org/raml-module-builder#cql-relations. In particular adjusting the query for `holdingsRecordId` in the `getHolding` function improves things. I haven't noticed any performance problems in particular with the others.

If I understand whats going on correctly, these can all be exact queries, but let me know if that's not your intention.

**Comment by ihardy** [comment]
actually, this is a more useful link on the double equals thing than the one in the previous comment: https://github.com/folio-org/raml-module-builder#important-information

>  For queries that only look up specific ids, etc... the preferred approach would be to query with two equals == and hence, declare a regular btree (index).

**Comment by demiankatz** [comment]
Thanks, @ihardy, I think using `==` makes a lot more sense than `=`, and I can't imagine any problems with more precise matching. I'll go ahead and implement the remaining proposed changes as soon as time permits!

**Comment by demiankatz** [comment]
@ihardy, can you take a look at commit edea769? This should take care of steps 2 and 5. I haven't actually tested the code, so I can't swear that it works, but it should at least be getting us in the right neighborhood for configurable bibliographic identifiers.

I opted for now to only support instance IDs vs. hrids; adding other types of identifiers seems like it will make things more complicated, and I didn't want to do that without a use case to justify it. It could certainly be added in future if needed.

**Comment by demiankatz** [comment]
Also, @ihardy (and anyone else with an opinion), one other question/thought: should the hrid method fail back to instanceid if no hrid is found? Is it reasonable to assume that a FOLIO instance relying on hrids will always have hrids, or do we need to assume that there may be a mix? Do we need a third setting that's mixed, or maybe support for a prioritized, comma-separated list? (I'm all for keeping this as simple as possible, but I want to be sure I'm not missing common and important use cases).

**Comment by ihardy** [comment]
Hi @demiankatz, I deployed https://github.com/vufind-org/vufind/commit/edea769303c7909bb87d4c5ed9d7f194444e5926 on our sandbox and its looking good to me, thanks!
>should the hrid method fail back to instanceid if no hrid is found?

I don't think that's necessary, hrid will be an alias of uuid and both must always exist.

**Comment by demiankatz** [comment]
Excellent, thanks, @ihardy for the testing and the clarification about hrids. I think this is probably ready to merge, but I'll wait until next week in case @crhallberg or @mis306lu have anything to add. Once this is merged, I think that #1503 can be merged as well, and then I'll merge all of those changes back into #1542 so we can continue to make progress on the issues being addressed over there.

**Comment by mis306lu** [comment]
I tested it in my development environment pointing it to our FOLIO test server and it works.  I did configure: type = hrid

**Pull request merged**
