### PR TITLE
Tag removal for users

### PR DESCRIPTION
**Pull request by crhallberg**
Whole new interface for tags and their addition/removal from records.

- [x] Update tags on login
- [x] Test non-JS
- [x] deletetagAction displays the info success message even if you don't do anything
- [x] Check for tag orphan cleanup
- [x] Convert SQL to all Zend for compatibility outside of MySQL
- [x] remove the $i = 0 initialization from core.phtml
- [x] Testing
- [x] Blueprint support
- [x] jquery mobile support

### CODE REVIEW

**Comment by demiankatz** [comment]
Chris,

A couple of comments from a first quick code review:

1.) You've got a var_dump in AjaxController.

2.) Do you need to expose user id values to achieve this? It's generally best practice to keep internal user ID numbers private. Would it be possible to just pass a flag indicating whether the current logged-in user created each tag and keep limit all the user ID analysis to the server side?

thanks,
Demian

**Comment by crhallberg** [comment]
This could be done.

**Comment by crhallberg** [comment]
This worked through every test I could throw at it, can you run it through your gauntlet?

**Comment by demiankatz** [comment]
Some comments from the latest code review -- hopefully testing can follow:

1.) If I'm not mistaken, this code:

<pre>
$tags = $this->params()->fromPost(
    'tag',
    $this->params()->fromQuery('tag')
);
</pre>

can be simplified to:

<pre>
$tags = $this->params('tag');
</pre>

Please try that out. If it works, we should simplify other similar checks when time permits!

2.) Is there a particular reason that deletetagAction is using GET rather than POST to specify the tags to delete? Usually delete actions controlled by GET are bad practice.

3.) Also in deletetagAction, why do you display the info success message even if you don't do anything?

4.) Why are you adding quotes around the tag string in AjaxController::tagRecordAjax? Won't that mess things up if the user already provided quotes?

5.) Do we have code somewhere to clean up orphaned tags if the last instance of the tag has been deleted? Are we already doing that for favorites, or are tags currently not being cleaned up at all? (I can dig into the code and answer this question if you want me to -- just don't know off the top of my head).

6.) I have a feeling that the "GROUP_CONCAT(DISTINCT user_id SEPARATOR ',')" solution for retrieving user IDs is MySQL-specific; this is likely going to break things for users with a PostgreSQL or Oracle backend. Is there a more "plain vanilla SQL" approach to this problem?

7.) Is the double-! in `loggedin = !!loggedin || userIsLoggedIn;` a JS feature I'm unfamiliar with, or a typo?

8.) Looks like you can remove the $i = 0 initialization from core.phtml, as that variable is no longer used after your redesign.

9.) We should add blueprint support once this is all working. Obviously not time to do that yet, but you might want to add a checkbox to the description. It might also be good to have jquerymobile support, but if that's impractical/complicated I can live without it!

**Comment by crhallberg** [comment]
Deleting a tag will remove any orphaned resource_tags, but the resource remains if no tags or resource_tags remain. Are there benefits to keeping the resource or should I check for and delete orphaned resources?

**Comment by demiankatz** [comment]
It's probably better to live with orphaned resource rows rather than try to delete orphans on the fly -- that might be an expensive operation, and also a potential source of bugs in the future if we add more tables with foreign keys to resource. (We never want to accidentally delete important data!). The cost of having a few useless rows in the database is probably lower than the risk of data corruption. If we want to clean up orphans, it may be better to build some utilities into the admin area that can do these types of cleanups on demand -- then we centralize the orphan detection logic and offer administrators the ability to make backups, etc., prior to cleaning out useless data.

**Comment by demiankatz** [comment]
A few comments from another quick code review:

1.) In AbstractRecord, what's the deal with `$driver->deleteTags($user, $tagParser->parse('"'.$tag.'"'));`? This seems like it's probably doing something more complicated than it needs to. Why add double quotes and then parse the string? Either you should parse without double quoting, or if you just need to deal with a single value, you could probably make it into an array without parsing anything.

2.) Best practice: use `null === $val` rather than `is_null($val)` for better performance. (It's a trivial difference, but why not use the quickest option? This is something we ought to standardize throughout the codebase one of these days).

3.) The AjaxController is reintroducing some deleted $ccself code that doesn't need to be there (probably a merge error). This has been superseded by the addition of an actual $cc parameter to the initial call.

4.) Do you need the commented-out SQL query in getForResource()? It's fine to leave it if you still want it for reference, but if you're done with it, we should clean it out.

5.) Any reason for the uppercase ID in `rt.tag_ID` in Table/Tags.php? That might cause a problem for case-sensitive databases.

6.) If my quick reading is correct, it looks like you're doing tag list rendering in two places: initially in the template and later through Javascript. Would it be easier to create a single template for rendering tag lists, then use $this->render() to fit that inline into another template for the initial display and also offer an AjaxController method to render on the fly so that the Javascript could retrieve a fully-rendered template instead of raw data?

**Comment by crhallberg** [comment]
1.) This is to handle multi-word tags. There is likely a simpler way, but this was the most straight-forward.
2.) Done.
3.) Un-merge-errored.
4.) It was for a reference, but I just removed it.
5.) Lowercased.
6.) Perhaps, we'll talk tomorrow.

**Comment by demiankatz** [comment]
In templates/RecordDriver/SolrDefault/list-entry.phtml, you've changed $list_id from null to true when in "all favorites" mode. However, there is some code elsewhere in the template that checks if $list_id is null to create appropriate edit and delete links. I have a feeling that this may no longer be working correctly. I'm also not sure what the implications of this might be when passed to getTags and getListNotes on the record driver. I can investigate this more deeply if you need me to, but I thought I'd check with you first to make sure the change was even intentional. (It seems to be related to avoiding null-list tags in the merged favorites list, but this may not be the best way to accomplish that).

**Comment by demiankatz** [comment]
Some more comments:

1.) In Db\Table\ResourceTags, I believe you can change `$select->where('list_id IS NOT NULL');` to `$select->where->isNotNull('list_id');` for slightly greater abstraction.

2.) In your subquery in Db\Table\Tags, you're filtering by record ID but not by source, which might cause problems if two sources share the same ID value. I think after `->where(['r.record_id' => $id])` you should add `->where(['r.source' => $source])`.

3.) While you're in Db\Table\Tags, you might want to review your comments... some are useful, but some can probably be removed (like `WHERE resource_id = 142`).

We're getting close here... though since this is a pretty dramatic change, I think we should wait until after 2.4 to merge to master, just in case there are any subtle problems we're missing. Also probably worth asking for some feedback on vufind-tech regarding UI look and feel (I like it, but I know how it's supposed to work... might be good to get some opinions from less experienced users).

**Comment by demiankatz** [comment]
Chris,

I did a little bit of code simplification and also found and fixed a JS bug (typo of vufindStrin was preventing tab loading). Now a couple new issues:

1.) We need to merge with master, but your LESS reformatting is causing a conflict. I didn't want to mess anything up by trying to resolve that myself. Could you take care of it when time permits? Maybe it's worth removing the tag-specific stuff from the formatted version and pushing it back to master so we don't keep hitting conflicts for every LESS change in future.

2.) Why are you urlencoding the tag strings in record/taglist.phtml? Shouldn't you be applying HTML or Javascript escaping rather than URL encoding? As it is, any tag containing a special character won't work right... Try tags like contains'apostrophe or has%percent. You can't delete them if you own them, and if you log into a different account and try to increment the count on an existing tag, a new tag gets created with double-encoded content.

**Comment by crhallberg** [comment]
capture

inaction

**Comment by demiankatz** [comment]
I'm guessing blueprint is work in progress at this point. A couple of observations from a first quick test:

1.) Tags on the MyResearch/Favorites page are not filtered correctly in blueprint, but they are in bootstrap.

2.) When you add tags in blueprint, the display does not refresh correctly (presumably some JS work is yet to be done).

Sorry if I'm testing this before you're ready!

**Comment by demiankatz** [comment]
Regarding the better tag AJAX error messages, I think you should check the APPLICATION_ENV constant and only output the exception message if it's set to 'development' -- in production mode, we don't want to expose internals like exception messages to the end user, since it could prove to be a security hole.

Are you still working on the "MyResearch/Favorites" tag filtering issue? I don't see anything that appears to address it in the latest commits, so I'll hold off on further testing until I hear more. (In case you need clarification on this, the issue is that if I add tags directly to a record so that they are not associated with a list, they show up on my favorites list in blueprint, but they do not in bootstrap3; I believe that the bootstrap3 behavior is the correct one).

**Comment by demiankatz** [comment]
Getting closer still! A couple of new questions:

1.) You've modified \VuFind\Db\Table\UserResource::destroyLinks() to behave the same when $user_id is null or $user_id is true (previously it only used 'null' for the "destroy regardless of list" special case). Why was this change made? If it's unnecessary, we should revert it to avoid confusion. If it does serve a purpose, I'm wondering if perhaps we actually want two slightly different behaviors: null to destroy ALL links whether or not they're in a list, and true to destroy only links that are in a list (retaining non-list-based links). Regardless, we should put some comments here to explain what's going on! If you can't remember this change, I can dig through the code to figure out exactly what's going on, but I thought I'd test your memory first.

2.) How do you think we should address jquerymobile? It is possible to add tags there, so perhaps we ought to add parallel delete functionality. However, if you think this is too complicated to add to the mobile experience, I can live without it. (A related existing problem: you can currently add tags to favorites in the mobile UI, but there is no way to view or edit these tags... probably not worth the effort of fixing unless it's very easy; I point this out mainly to indicate that inconsistency already has a precedent in this theme).

Thanks again!

**Comment by demiankatz** [comment]
Chris,

Looks like there's a LESS conflict between master and this branch. Do you mind resolving it before I do (hopefully) one last round of testing?

Thanks!

**Comment by demiankatz** [comment]
Manually merged to master.

**Pull request closed without merging**
