### PR TITLE
FOLIO driver - only show open loans for my transactions

### PR DESCRIPTION
**Pull request by mis306lu**

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @mis306lu. A couple of questions:

1.) Are status names hard-coded in FOLIO, or might we need to add a configuration setting to account for different FOLIO setups? Is it possible there might be more than one status that would count as active?

2.) While we're working in this area, should we consider implementing [getMyTransactionHistory](https://vufind.org/wiki/development:plugins:ils_drivers#getmytransactionhistory), which is the mirror image of [getMyTransactions](https://vufind.org/wiki/development:plugins:ils_drivers#getmytransactions)? The return value is formatted a little bit differently, but the actual data retrieval would be identical to this one, just with a different filter parameter, so it might make sense to do a little refactoring to support that.

As always, let me know if I can help. I'm also interested in hearing from @ihardy and/or @nkuitse if they have anything to add.

**Comment by kellyflo** [comment]
In response to @demiankatz question #1 above (if it's not too late).  
Item Statuses are hard coded - if the goal is to only show open loans in my transactions - that status would be "Checked out".

**Comment by demiankatz** [comment]
Thanks, @kellyflo, it is definitely not too late. So are you saying the CQL in this PR needs to be revised to use "checked out" instead of "open"?

**Comment by mis306lu** [comment]
@kellyflo, @demiankatz 
In regards to #1)  Loans have a status (like Open) and items have a status too (like Available, Checked Out).  The VuFind code calls the loan (circulation) API.

In regards to #2) I hesitate on this one because of the "Anonymize all loans" functionality built into FOLIO?

**Comment by demiankatz** [comment]
Regarding point 1, that makes sense -- @kellyflo, any objections to merging?

Regarding point 2, the "transaction history" feature in VuFind is disabled by default, so if retaining history is an option in FOLIO, it would be possible to turn it on in both places and have things work... and if FOLIO anonymizes by default, that would work just fine with VuFind's default behavior of hiding historical transactions. In any case, there's no urgency to adding this unless somebody actually needs it... but if it might be useful in the future and if FOLIO could support it under some circumstances, it looks like it would be pretty easy to implement and might be worth doing just to scratch another method off the list.

**Comment by ihardy** [comment]
concur with Kelly and Michelle on point number 1, fwiw the rtac modules are using the same query (status.name==Open).

**Comment by demiankatz** [comment]
Thanks, everyone -- I'll go ahead and merge this as-is for now; we can easily revisit the historic transactions question in the future as needed.

**Pull request merged**
