### PR TITLE
JSON Hierarchy Cache, Part 2

### PR DESCRIPTION
**Pull request by crhallberg**
Back from an accidental merge of #247

### CODE REVIEW

**Comment by crhallberg** [comment]
Context implemented as stated above, with one exception: collection links from the Collection context go to #tabnav instead of #tree-{id}.

**Comment by demiankatz** [comment]
Good progress! A few more comments....

1.) Now that you're doing routing inside the tree renderer, are you able to eliminate the %%%%VUFIND-BASE-URL%%%% and related route lookup from the gettreejsonAction?

2.) Also related to gettreejsonAction: should you be passing context in there? Seems like something's not going to work right without it, but maybe I'm confused. Is it possible that your context work so far is only accounting for HTML trees but not dynamically rendered trees?

3.) In TreeDataSource/Solr.php, I think something is wrong with the sortNodes() method. You rewrote it previously to fix a bug in the JSON code, but your rewrite broke the XML code. I then rewrote it differently so that both XML and JSON would work correctly (and so that it was a bit more readable). Now it appears that my code has been reverted to some prior version. I'm guessing this might be some kind of merge error, unless you reverted it intentionally for some reason.

Let me know your thoughts on these things; I'll give it another real-life test once they're resolved. Thanks!

**Comment by crhallberg** [comment]
Have we fixed all the sortNodes problems?

**Comment by demiankatz** [comment]
Chris,

The blueprint styling used to have different classes for the currently-selected items (the currentHierarchy and currentRecord classes) than for everything else. You can see how these were applied by looking at the deleted .xsl files in the diffs. Are these conveying important visual information that we're losing in the new implementation? I don't see either of these classes being added anywhere in your "Reimplemented blueprint styling" diff. And if we did lose something from blueprint, is it a feature worth adding back in to bootstrap as well? Let me know if you need me to help set up a scenario where you can see this in action.

Apart from this last detail, I think we're pretty much ready to merge!

Thanks!

**Comment by crhallberg** [comment]
I figured it out and it works. Take a look and then I think we're ready!

**Comment by demiankatz** [comment]
Manually merged to master. Thanks!

**Pull request closed without merging**
