### PR TITLE
Lightbox Keyboard Support

### PR DESCRIPTION
**Pull request by crhallberg**
- Constrain keyboard focus to lightbox. 
- Add ESC to close lightbox.

### CODE REVIEW

**Comment by ckaz** [comment]
You are amazing! Will look at this tomorrow. Good night!

**Comment by ckaz** [comment]
Just tested this -- works like a charm! Thanks!

**Comment by demiankatz** [comment]
@crhallberg / @ckaz: this PR has some conflicts that need to be resolved. I'm curious if it's still worth the effort of backporting this to release-5.1 and then merging it all the way forward, or if we can just move development to the bleeding edge. If having it in release-5.1 would help @ckaz, I'm certainly willing to continue that approach, but since 6.1.2 has now been released, I'm not expecting any further 6.x releases unless a major bug is discovered, so it may be better to refocus on new development. Thoughts/opinions?

**Comment by crhallberg** [comment]
I'd be happy to resolve as far back as would be useful for @ckaz.

**Comment by ckaz** [comment]
Sorry for taking so long. I was on vacation. Please don't put too much effort into backporting this. I could easily create a working version in our standard theme and take it from there!

**Comment by demiankatz** [comment]
@crhallberg, thanks for the progress on this. I noticed that it was still based against the release-5.1 branch; I've changed it to use dev as the base branch, which required me to recompile the LESS to resolve conflicts. Do you mind giving this one more review to be sure I haven't messed anything up?

**Comment by demiankatz** [comment]
@crhallberg, I notice that there seem to be some Javascript style issues that are preventing the build from passing here... Can you fix?

**Comment by demiankatz** [comment]
All tests are passing; merging now! Thanks, everyone.

**Pull request merged**
