### PR TITLE
Support multiple building filter values when determining source recor…

### PR DESCRIPTION
**Pull request by EreMaijala**
…d priority with deduplicated records so that priority determination works also with orFacets.

### CODE REVIEW

**Comment by EreMaijala** [comment]
The failing checks are not code this PR touches.

**Comment by demiankatz** [comment]
I've manually merged this to release-2.5 since it's a relatively isolated fix -- might as well get it out in the next maintenance release.

Because this is fairly complicated code, I wonder if it might be beneficial at some point to add some unit tests for it... but I realize that's probably a lot of effort and not a high priority. Something to think about, though!

**Comment by EreMaijala** [comment]
You're right, unit tests would make sense here..

**Comment by demiankatz** [comment]
If you find time, just open a new PR (since this one's already merged in). If not, I understand. :)

**Pull request closed without merging**
