### PR TITLE
Take a screenshot on integrated test failure.

### PR DESCRIPTION
**Pull request by crhallberg**
- [x] ? Configurable destination folder
- [ ] ? Add txt files with stack dumps

### CODE REVIEW

**Comment by demiankatz** [comment]
I vote yes on both of the TODOs. :-)

**Comment by crhallberg** [comment]
One side-effect that I don't know how to suppress: blank images. Every browser has a root blank page that is also saved. I don't think this can be helped unless there's an easy way to filter out blank PNGs based on their base64 content.

**Comment by demiankatz** [comment]
> 
> 
> One side-effect that I don't know how to suppress: blank images. Every browser has a root blank page that is also saved. I don't think this can be helped unless there's an easy way to filter out blank PNGs based on their base64 content.

It's possible you can figure it out based on the string length of the image data... I imagine the blank images are under a fairly low threshold.

**Comment by demiankatz** [comment]
@crhallberg, I'm reviewing older pull requests, and this one caught my eye. Is it still on your radar? If not, I can probably carve out some time to add configurability through Phing, etc., so we can wrap this up.

**Comment by crhallberg** [comment]
I seem to not be having the blank image problem inside of the biblio project. Maybe I can reconcile the two.

**Comment by demiankatz** [comment]
Interesting, @crhallberg; let me know if I can help with testing/collecting data points.

**Comment by crhallberg** [comment]
[Screenshot on Failure](https://trello.com/c/GC8orrlR/12-screenshot-on-failure)

**Comment by demiankatz** [comment]
@crhallberg, I solved the mystery of the duplicate screen shots. It has nothing to do with browser tabs; it was a weird side effect of the AutoRetryTrait, which was calling tearDown() an extra time between retries (and an extra time after the last retry). This revealed a flaw in the trait's logic, which I have fixed here. I've adjusted this so that screen shots will only be taken on the final attempt when retries are in play. There might be an argument toward taking screen shots of all attempts to figure out intermittent problems, but for the moment, I'm going to start here as the simplest approach. Happy to revisit later as needed.

I've also added a new Phing variable to control the screen shot directory. If this is not set, no screen shots will be taken. I think this effectively makes the feature configurable.

I'm not going to worry about the stack dump file at this stage; if we need that, we can address it as a separate PR.

**Pull request merged**
