### PR TITLE
WIP: Heroku support

### PR DESCRIPTION
**Pull request by bemosior**
This is a work-in-process PR for Heroku PaaS support ([more info](https://vufind.org/jira/browse/VUFIND-1220)). 

Significant aspects so far:

* Addition of platform dependencies within `composer.json`.
* Committing `composer.lock` to the repository.
* Addition of a Heroku-specific httpd config.
* Addition of one-click "Deploy to Heroku" button in README (no db/solr yet)

More to come, I imagine.

TODO:
- [ ] Consider switching to PHP long tags in templates (see #954 for discussion)

### CODE REVIEW

**Comment by bemosior** [comment]
My `master` branch was about 2 weeks behind, and I encountered some new and interesting errors when I pulled in the latest changes:

```
2017-02-10T22:36:45.225563+00:00 app[web.1]: Stack trace:
2017-02-10T22:36:45.225663+00:00 app[web.1]: #0 [internal function]: Zend\Mvc\Service\AbstractPluginManagerFactory->createService(Object(Zend\ServiceManager\ServiceManager), 'serializeradapt...', 'SerializerAdapt...')
2017-02-10T22:36:45.225782+00:00 app[web.1]: #1 /app/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(936): call_user_func(Array, Object(Zend\ServiceManager\ServiceManager), 'serializeradapt...', 'SerializerAdapt...')
2017-02-10T22:36:45.225949+00:00 app[web.1]: #2 /app/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(1094): Zend\ServiceManager\ServiceManager->createServiceViaCallback(Array, 'serializeradapt...', 'SerializerAdapt...')
2017-02-10T22:36:45.227458+00:00 app[web.1]: #3 /app/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(636): Zend\ServiceManager\ServiceManager->createFromFactory('serializeradapt...', 'SerializerAdapt...')
2017-02-10T22:36:45.227650+00:00 app[web.1]: #4 /app/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(599): Zend\ServiceManager\ServiceManager->doCreate('Se in /app/vendor/zendframework/zend-mvc/src/Service/AbstractPluginManagerFactory.php on line 32```

**Comment by demiankatz** [comment]
@bemosior, your serializer problems seem to be related to this JIRA ticket: https://vufind.org/jira/browse/VUFIND-1221 -- sounds like the solution is simple, but I remain puzzled about why I am not seeing the same problem on my own systems. I will be investigating further later today.

A couple of other comments/questions:

- You seem to be relying on a new vendor/bin script for part of this, but I don't see where that is coming from. Does something else need to be added to composer.json?

- Is there a way to auto-generate the Apache configuration by manipulating a copy of the current template configuration? That might be more maintainable over the long term if the differences between the two versions are minimal....

**Comment by bemosior** [comment]
Ok, I'll hang on for progress on [VUFIND-1221](https://vufind.org/jira/browse/VUFIND-1221). On a related note, have you ever worked with [Vagrant](https://www.vagrantup.com/)? It makes local virtual machine provisioning quick and easy, especially when it's important to have a clean environment in cases like this. I could contribute a Vagrantfile in another PR and give everyone a rundown on how to use it, if that would be useful.

### vendor/bin

Ah yes, the Procfile `vendor/bin` call has a bit of PaaS magic behind it. Basically, [Heroku promises to provide heroku-specific apache or nginx binaries](https://devcenter.heroku.com/articles/php-support#web-servers) in `vendor/bin`. We can trust that they'll be there without doing anything else.

### Apache configuration

A few possibilities:

1. We could generate one configuration based on manipulation of the other, but that might be just as fragile since the anchorpoints used for the manipulation could change (as they say, trying to solve one problem with regex means there are now two problems).

2. Generating both Apache configurations from templates (committing the templates, not the configurations) could be better, perhaps as part of a composer `post-install-cmd` script.

3. On the other hand, looking at [how frequently](https://github.com/vufind-org/vufind/commits/master/config/vufind/httpd-vufind.conf) the apache configuration gets touched (2016:3, 2015:4, 2014:0, 2013:2, 2012:4), maybe we could consider an experimental approach. If we want to take the shortest path to discovering whether the feature (Heroku support) is valuable to the user base, maybe we could tolerate the duplication in the short-term. If Heroku support does turn out to be valuable, then we can address the config duplication for long-term maintainability. If it turns out to _not_ be valuable, then we probably should remove the related configs in the codebase anyway (and we'll be glad we didn't spend time solving the config duplication issue). I'm happy to pledge my attention for either outcome. Maybe we should set a date at which point we can decide whether Heroku support is providing value (how about May 1st)?

**Comment by demiankatz** [comment]
Regarding Vagrant, I have not personally had a chance to experiment with it, though there is some (now rather old) documentation in the wiki at https://vufind.org/wiki/installation:vagrant -- please feel free to update that if you have something to share and it's not a lot of work.

Thanks for the clarification on vendor/bin -- I was confusing this with the vendor/bin created by Composer.

Regarding Apache configuration, I didn't do a close analysis to see how different your configuration was from the default version. However, since the install.php installation tool is largely designed as a script to auto-generate an appropriate Apache configuration from the template in config/vufind/httpd-vufind.conf, I basically wondered whether we could use that installation process, perhaps with minor alterations, to automate the config generation as part of the Heroku setup. I definitely hear what you're saying about a new regex-based solution not really being a solution -- but if we can leverage what we already have, perhaps with minor alteration, that might be a stable enough solution to be worthwhile. On the other hand, if there are a lot of subtle new differences, I agree that living with two files for a while is probably the lesser of two evils. We can discuss this (and the possibility of a target date) on the call tomorrow.

Thanks again!

**Comment by bemosior** [comment]
As I mentioned on the call, here's a video quickly demonstrating the button-based deployment of VuFind to Heroku:

[VuFind Button Deployment to Heroku](http://www.youtube.com/watch?v=_TMBMOrj42o "VuFind Button Deployment to Heroku")

**Comment by bemosior** [comment]
Awesome, the serializer issue is resolved, which means the "Deploy to Heroku" button in this branch's README works now for real.

I have a note to revisit the Vagrant question. The two documented examples are interesting. I'll open another issue for discussion at a later time.

**Comment by bemosior** [comment]
The below is about trying to avoid committing a separate Apache config for Heroku.

It looks like the install.php supports everything needed but the following two items:

1. The Heroku config needs a `DirectoryIndex index.php` in the `<Directory /app/public/>` stanza, otherwise it returns a 403 error when hitting the root of the app.
2. Heroku cannot parse `php_value` directives in the Apache config. I believe they want those statements pushed to specific php ini overrides.

Now, I was becoming hopeful about augmenting install.php with options for both of the above and just running that under an `app.json` [postdeploy script](https://devcenter.heroku.com/articles/app-json-schema#scripts), which only affects the button deployment. Hoewever,  I discovered that running `install.php` from there appears to have no effect on the local filesystem, despite exiting with status 0:

```2017-02-17T04:56:14.262582+00:00 app[api]: Starting process with command `(php install.php --basepath=/ --non-interactive); echo "4c3827b16eec96d55cf3519eb41b1ee3 $?"` by user ben@unicalabs.com
2017-02-17T04:56:26.703064+00:00 heroku[run.4067]: Awaiting client
2017-02-17T04:56:26.736379+00:00 heroku[run.4067]: Starting process with command `(php install.php --basepath=/ --non-interactive); echo "4c3827b16eec96d55cf3519eb41b1ee3 $?"`
2017-02-17T04:56:26.920259+00:00 heroku[run.4067]: State changed from starting to up
2017-02-17T04:56:31.420829+00:00 heroku[run.4067]: Process exited with status 0
2017-02-17T04:56:31.433018+00:00 heroku[run.4067]: State changed from up to complete```

```
drwx------  5 u32427 dyno 4.0K Feb 17 04:54 .
drwx------ 19 u32427 dyno 4.0K Feb 17 04:58 ..
-rw-------  1 u32427 dyno  245 Feb 17 04:54 README.txt
drwx------  2 u32427 dyno 4.0K Feb 17 04:54 cache
drwx------  3 u32427 dyno 4.0K Feb 17 04:54 config
drwx------  2 u32427 dyno 4.0K Feb 17 04:54 harvest```

Testing further, the same command appears to run just fine in a postinstall script in `composer.json`. But, I don't have a reliable way of detecting whether we're in a Heroku environment in order to prevent it from running in a non-Heroku circumstance.

I'll continue digging into it. I have an idea or two yet.

**Comment by demiankatz** [comment]
@bemosior, I don't see any harm in setting up the DirectoryIndex directive by default in the existing config template. It might be valuable to make sure it matches the default Apache DirectoryIndex (i.e. including .htm/.html) in case anyone is hosting HTML files somewhere under their public directory... but that's probably not too likely, and certainly not a recommended practice.

The short_open_tag directive is there to allow the .phtml templates to include code without `<?php` being repeated all over the place. I'm not completely averse to reconsidering that decision, but the implications of changing it would be large -- probably hundreds of files would need updating.

Good luck with the continuing troubleshooting. Let me know if I can be of further assistance!

**Comment by bemosior** [comment]
It's a little weird, but it works. I can specify environment variables in the `app.json`, and execute the `install.php` script conditionally in the post-install section of `composer.json`.

This is the interesting bit:

```
    "scripts": {
        "post-install-cmd": [
            "phing installsolr installswaggerui",
            "if [ \"$VUFIND_CONFIGURE_HEROKU_DEFAULTS\" = \"true\" ]; then composer configure-heroku-defaults; fi"
        ],
        "post-update-cmd": "phing installsolr installswaggerui",
        "configure-heroku-defaults": "php install.php --basepath=/ --non-interactive"
    }
```

While this works, do you still prefer it to a second httpd conf? If so, I'll update `install.php` with an option to drop the `short_open_tag` statement (and dive into ensuring the `.phtml` files still render).

I've also set the DirectoryIndex to the default statement as you described.

**Comment by demiankatz** [comment]
This sounds like a reasonable approach at least for the moment -- the extra noise in composer.json is mildly unfortunate, but I think I can live with it. Regarding the php_value things, do those cause Heroku to fail entirely, or does it just ignore them? (I'm guessing it's a failure situation or else you wouldn't be talking about it -- but just making sure we don't do more work than we need to). Anyway, I think a simple preg_replace for `^php_value` to `#phpvalue` ought to do the trick if it is needed.

**Comment by bemosior** [comment]
Here's a fun bit. Heroku uses a directory in `/tmp` to build the project and then moves it to `/app` on completion. Simultaneously, `install.php` uses a variable (`$baseDir`) in a way that does not distinguish between "current directory of `install.php`" and "VuFind base directory," because up until this point they were absolutely the same. In a platform Heroku, though, it now means that `install.php` will specify a `/tmp` directory in any generated config files while in fact needing to specify `/app`.

I intend to rename the `$baseDir` variable within the `install.php` script to `$currentDir`. That way, each use of that variable can offer a clear decision point as to whether the current directory is the truly intended use or if there should be some other value. This is more of a quality of life change for a developer working within `install.php` when platforms are supported, especially as platform support expands outside just the Apache config.

The obvious hacky "fix" is to just override `$baseDir`, but that increases the complexity of what that variable means in a procedural script and makes understanding what's going on harder.  I think it's more clear to the developer if I make the changes above and turn it into a decision between `$currentDir` and `$someOtherDir`.

I'll have a commit forthcoming that we can use to discuss the above.

**Comment by bemosior** [comment]
As I was working through this again, I realized that `$overrideDir` has the same kind of problem, but it is more complex because the value is _additionally_ collected from the user or specified in a flag (not the case with `$baseDir`). I think I am going to use the more hacky fix for `$overrideDir` by just overriding it in the platform-specific conditional. To do something "better" would require a little more re-engineering of `install.php` than I think I want to take on right now.

**Comment by bemosior** [comment]
...ok and with that we're back to a "working" state. Up next: Database provisioning and managing basic configuration (like the database connection string).

**Comment by demiankatz** [comment]
@bemosior, thanks for the progress -- this all makes sense to me so far. Let me know if there are still any outstanding issues that need to be discussed, but it sounds like you've figured out a reasonable approach.

**Comment by bemosior** [comment]
Hey-o, so I mentioned a few dev calls ago that I'd be testing out an alternative approach using Docker. Turns out it's much more practical, so I think I'd like to close this PR and open another.

Heroku is still a viable option, but it has plenty of constraints. The implementation is relatively invasive for this codebase, with lots of changes (extra files, rewriting scripts, etc.), and support for certain VuFind features may be a long way off. It's not bad, but it's not great either.

Also, the Heroku Solr add-on partner handles a pretty particular set of use cases, provides no API for managing configuration, and can be a bit pricey with multiple cores. It's not impossible, but it's also not particularly accommodating for what we have in mind.

By contrast, my initial foray into a Docker implementation is a matter of adding `Dockerfile` and `docker-compose.yml` at the root of the repository. That's it. I had a lot of success setting up automatic database provisioning and solr setup, too.

Heroku does offer a kind of potential for democratization of VuFind setup and operation, as it wouldn't necessarily need a lot of significant IT resources to leverage. On the other hand, Docker does require some expertise, but it's a generic kind of expertise, useful across software contexts. In my mind, it's a tradeoff of a little accessibility with a lot of practicality, which you'll soon see.

I'll plan to leave this branch alive on our fork, just in case it interests anyone else.

**Comment by demiankatz** [comment]
Closing in favor for #962. This work in progress has been moved to https://github.com/vufind-org/vufind/tree/feature/heroku and documented on https://vufind.org/wiki/development:git-branches for future reference.

**Comment by bemosior** [comment]
Awesome, thank you!

**Comment by demiankatz** [comment]
For anyone following this (now-abandoned) development, it has been suggested that Zeit might also be a viable platform for one-click deployment of VuFind. See https://zeit.co/ -- and feel free to open a PR if anyone is interested in pursuing this.

**Pull request closed without merging**
