### PR TITLE
Refactor export settings

### PR DESCRIPTION
**Pull request by mbeh-ub**
As suggested in pull request #436 (email exported favorites as file attachement) I open a new one for refactoring the
export settings. This code should be compatible with existing Export settings.
If we agree about the implementation I will also do the code styling and commenting.

### CODE REVIEW

**Comment by demiankatz** [comment]
Looks like a good start! A few suggestions:

1.) Something's a little strange in the config.ini changes -- you add a second [Export] section header but don't remove the [BulkExport] section.

2.) I'd rename the bulkExport setting to bulk -- since this is known to be an export setting, we can safely make it shorter without losing any meaning.

3.) The new default config.ini settings should be changed to be consistent with the old default settings -- all true settings should change to "record,bulk" and all false settings should remain false. (Of course, we can discuss the possibility of changing the defaults... but for the purposes of this PR, let's try to keep things functionally the same).

4.) For consistency with the above, I think the default settings used in getActiveFormats() when no config.ini setting is found should also be "record,bulk" rather than just "record." (Since export defaults to "on" in the old config.ini).

5.) For backward compatibility, I'd keep the public getBulkOptions() function, but change it to a wrapper around getActiveFormats('bulk'). I'll leave it to your discretion whether or not you still want to change the templates -- I have no strong preference.

Thanks for the work on this!

**Comment by mbeh-ub** [comment]
to 1.) This is a mistake. I removed the duplicated [Export] section.
The [BulkExport] section we need if someone would change the defaultType (form link to download) for bulk exports.

to 2.) In the future we may add another value for control which formats could be used when mailing a record. Then a possible definition look like: RIS=record,bulk,email. I think in this case it would be clearer to have RIS=record,bulkExport,bulkEmail. 
Or would you prefer the always have the same set of formats for bulkEmail and bulkExport - maybe this is the better (because simpler) case. 

to 3.) Of course we should preserve the current default behavior. I changed this only to show the new
options.

to 4.) ok

to 5.)  ok, I didn't keep in mind that some user defined themes may use this method.
I restored the function getBulkOptions() as a wrapper of getActiveFormats('bulk') and
marked it as deprecated.
I kept the changes in the templates. So if someone takes the code as an example he doesn't get
the wrong idea.

**Comment by demiankatz** [comment]
to 2.) I can't think of a situation where you would want to allow some formats to be bulk-downloaded and a different set to be bulk-emailed. It does seem like it would make more sense (and require less configuration) to have "allow bulk exports to be emailed" as a setting. However, it's always possible that there's a use case I'm not thinking of, and there are advantages to offering maximum flexibility. I'll leave this to your discretion.

Also, one new comment: I see that the bulkOptions property of the Export class is still being used by the restored getBulkOptions function. I think it would probably be better to have getBulkOptions directly return getActiveFormats('bulk') -- there doesn't seem to be an advantage to adding a caching layer to a legacy-compatibility wrapper function. However, perhaps there is some value to adding an equivalent caching mechanism to getActiveFormats to reduce processing on multiple calls.

Please let me know what you'd like me to do next. I see you have some Travis warnings at the moment; if you'd like help resolving them, just let me know.

**Comment by mbeh-ub** [comment]
to 2.) ok, let's keep it simple and use bulk. I will add a option allowEmailing to the BulkExport section

I added a analog caching mechanism to getActiveFormats like in getBulkOptions.
I also fixed the phpcs issues and some problems while running  ExportTest's. Could you please have a look at the persisting errors (concerning uprade test ?).

**Comment by demiankatz** [comment]
Sounds good. I'll try to find some time for this tomorrow, if not sooner.

**Comment by demiankatz** [comment]
Okay, I have fixed the broken tests, done a little work on getActiveFormats, updated the config.ini comments and added an extra test case to the Export tests. I think we're in pretty good shape now. Is there anything else you wanted to do here before merging?

(Even if this is ready to go, I'll probably wait until after I create the branch for release 2.5 -- I'm freezing changes on that release after today, so unless you feel there is an urgent need to get this change into the next release, it's probably best to wait for the following one).

**Comment by mbeh-ub** [comment]
Thanks, form my side I think we are ready to merge.

**Comment by demiankatz** [comment]
Great. I'm still in the midst of 2.5-related work, but when that's all sorted out, I'll get this merged and then we can proceed on the related features. Thanks!

**Comment by demiankatz** [comment]
Okay, I've done a little bit more cleanup on this (to expand test coverage and to address the improved defaults in getActiveFormats() that we discussed above but hadn't changed yet). It's all committed here: https://github.com/vufind-org/vufind/commit/3db71a173b9adceca17bc8c07ace2fea1945776b

I think we are now ready to proceed with #441, #436 and/or #430. Please let me know if I can be of any assistance moving any of these forward.

**Pull request closed without merging**
