### PR TITLE
Similar item carousel

### PR DESCRIPTION
**Pull request by demiankatz**

### CODE REVIEW

**Comment by crhallberg** [comment]
What needs to be done for this?

**Comment by demiankatz** [comment]
If memory serves, the last time I saw this, the sizing of the images was somewhat problematic (some were too big and some were too small, perhaps?). I think if we get that sorted out, it's just a matter of general code review and cross-theme support. Let me know if you need me to actually take another look at the running code; I haven't spent much time with this yet since I've been focusing on higher priority PR's.... but we should wrap this up eventually!

**Comment by demiankatz** [comment]
The other thing to figure out here is how to make it configurable. I don't think we want this on by default, but do we just omit it from the module.config.php tab array and let people add it to their local modules, or do we have it as an active tab but add some config setting elsewhere that controls whether the tab actually displays? The first solution puts a greater burden on users who want to activate it, while the other is going to waste overhead loading a useless class the majority of the time.

**Comment by crhallberg** [comment]
We could have it commented out in module.config to ease the use a little, I thought activating via module.config was the regular way tabs are configured. Am I wrong?

What other configurations were you thinking for this?

**Comment by demiankatz** [comment]
Activating via module.config is the regular way tabs are loaded, but each tab also has its own method to control whether or not it actually displays (since most tabs don't apply to every record). Thus, we could have it on by default and then make some configuration that controls its visibility...  but that's a lot of nasty overhead, so I think you're right that the best bet is to put it in commented out.

**Comment by crhallberg** [comment]
Is it really implemented that differently from other tabs?

**Comment by demiankatz** [comment]
No, it's not implemented significantly differently. It's just that most of the other tabs are things that I would expect people to want a good percentage of the time, while this is kind of a fancy extra toy that I wouldn't expect everyone to want by default.

**Comment by demiankatz** [comment]
It's the first thing of that sort we've built out as a record tab... and the module.config.php files don't lend themselves to "offer tons of disabled-by-default options" as conveniently as the regular .ini files do.

**Comment by demiankatz** [comment]
But I think this is the right way to do it. It's just a little annoying that there isn't a less cumbersome way to give people the option.

**Comment by crhallberg** [comment]
Is this ready to go?

**Comment by crhallberg** [comment]
Added Blueprint support via the awesome [slick caoursel plugin](http://kenwheeler.github.io/slick/).

**Comment by demiankatz** [comment]
Just to keep track of where we are on this PR: next step is jquerymobile implementation (or "unsupported" template if necessary).

**Comment by crhallberg** [comment]
The outdated version of jQuery in jquerymobile may prevent us from putting in a mobile friendly carousel at all. Still looking for a solution.

**Comment by demiankatz** [comment]
I had a feeling that might be an issue.

**Comment by demiankatz** [comment]
Looks good. Manually merged.

**Pull request closed without merging**
