### PR TITLE
Support-check for Hierarchy-Tree in Solr-TreeDataSource

### PR DESCRIPTION
**Pull request by lahmann**
Refers to discussion on mailinglist: http://sourceforge.net/p/vufind/mailman/message/33275875/
* added check for availability of hierarchical parent to Solr-TreeDataSource
* added configuration option for availability check to HierarchyTree inis

### CODE REVIEW

**Comment by demiankatz** [comment]
A few comments:

1.) I'm a bit confused about how this works; based on our conversation, I thought you were saying that we needed to add a $this->supports() check somewhere inside the data retrieval recursion... but I'm not seeing that. If adding this check is only necessary to make the checks in VuFind\Hierarchy\TreeRenderer\JSTree more strict, then I'm much less concerned about performance implications, as that should only ever require a small number of Solr retrievals (if I'm understanding everything correctly).

2.) Your config file says the default for the new setting is "true" but it's actually "false" (If you omit the setting from the .ini file, the isset() check will fail and the check will get skipped). Once we decide what our default behavior should be, we should make sure the documentation and behavior match up.

3.) You don't need to do a full search with a constructed query to retrieve a record by ID. You can simplify the code by instead calling:

<pre>
$results = $this->searchService->retrieve(
    'Solr', $id, new ParamBag(array('fq' => $this->filters))
);
</pre>

I'll hold off on testing this until I hear more from you. I was thinking the key test would be whether performance changed during the hierarchy generation CLI utility, but based on the way this works, these changes should have no impact there at all!

Anyway, thanks again for sharing this!

**Comment by lahmann** [comment]
1.) Sorry for the confusion - I meant as the VuFind\Hierarchy\TreeDataSource->supports() method already exists and also gets called in VuFind\Hierarchy\TreeRenderer\VuFind\Hierarchy\TreeRenderer\JSTree->getTreeList() one could use a Solr-Retrieval for the referenced hierarchy_parent/top_id to make sure that it's actually available in the index. So, you are right, that this check would make the checks in JSTree more strict - that's pretty much all.
In regards to performance this check would add an extra Solr-retrieval for each hierarchy_top/parent_id given in every record.

2.) You are right, the way it's implemented right now the isset() check would fail and therefore the default-behaviour would be to skip the check if the settings in the .ini file would be omitted. My assumption was as the .ini files have the checkAvailability setting set to true by default the user would have to willingly edit the HierarchyDriver .ini file in order to disable the availabilityCheck and therefore change the default-behaviour. But I agree that the default-behaviour should be reflected in the code as well, so VuFind\Hierarchy\TreeDataSource\Solr->supports() should look like:

    public function supports($id)
    {
        $settings = $this->hierarchyDriver->getTreeSettings();

        if (isset($settings['checkAvailability']) && $settings['checkAvailability']==0) {
            // checkAvailability is explicitly turned off.
            return true;
        } else {
            $results = $this->searchService->retrieve(
                'Solr', $id, new ParamBag(array('fq' => $this->filters))
            );
            if ($results->getTotal() < 1) {
                return false;
            }
        }
        // If we got this far the support-check was positive in any case.
        return true;
    }

3.) Thanks for the simplification - I'm still learning how to use the VuFind Plugins best :)

4.) CLI utility: I just tested the VuFind2.3.1 and 2.4 (commit 7656919 from vufind-org) createHierarchyTrees.php CLI-util. It does load the searches.ini settings and use the HiddenFilters-section (VuFindConsole\Controller\UtilController): getFullFieldsFacets() will retrieve any hierarchy_top_id in the index, but $recordLoader->load() will load the record in question with HiddenFilters applied and therefore will fail (the CLI util exits with a VuFind\Exception\RecordMissing). Moving the code after the "Building tree.." console-output in a try-catch block works fine.
Do you think we can use the try-catch block as an appropriate workaround? There shouldn't be any impact on the CLI-util performance.

**Comment by demiankatz** [comment]
2.) Makes sense. The thing I always try to think about when adding settings with defaults is the possibility that someone will upgrade from an earlier version that predates the new setting but forget to adjust their .ini file -- in my opinion, that's the most important reason to be careful about default behaviors. You could slightly simplify your proposed change by reversing the conditional logic to `if (!isset$settings['checkAvailability']) || $settings['checkAvailability']==1) {` to eliminate the need for the else clause.

4.) Adding a try..catch makes sense to me. We should probably Console::writeLine a warning inside the catch so people can see that things are missing.

**Comment by lahmann** [comment]
Ok, I updated the code accordingly.

**Comment by demiankatz** [comment]
Thanks! I'll try to test and merge this later in the week (I'm out of the office today).

**Comment by demiankatz** [comment]
Looks good. I've manually merged this to master with some minor adjustments (expanded comments, resolved merge conflicts). Thanks again for sharing your solution!

**Pull request closed without merging**
