### PR TITLE
fix: missed icon link in advanced search

### PR DESCRIPTION
**Pull request by crhallberg**
Found a link with an icon that escaped fixing before.

### CODE REVIEW

**Review by demiankatz — APPROVED** [review]
Thanks, @crhallberg!

**Comment by demiankatz** [comment]
Before I merge this, just to be on the safe side: @sturkel89, could you run the full test suite on this, and also double-check that it looks right in all three themes. (I'd be very surprised if it looks wrong anywhere, but I want to be absolutely sure it doesn't break any tests through the reorganized HTML). The way to see it is to go to the advanced search screen and add a search group. The issue affects the "remove search group" link, which has ugly underlining prior to the fix added here.

**Comment by sturkel89** [comment]
I ran the full test suite on this branch. No errors or failed tests!

Then I loaded the branch and tried a complex advanced search. "Remove Search Group" looks great in all three themes!

I switched back to dev and could see the extended underlining in the Remove Search Group link in all three themes. Subtle difference -- but we've made an improvement! :)

**Review by demiankatz — APPROVED** [review]
Thanks, @sturkel89 and @crhallberg!

**Pull request merged**
