### PR TITLE
Remove chdir from application initialization.

### PR DESCRIPTION
**Pull request by demiankatz**
This also removes a constant and some code designed to work around the `chdir`.

TODO
- [x] Run full test suite
- [x] Manually test console tools to ensure relative and absolute paths work as expected
- [x] Update changelog when merging

### CODE REVIEW

**Comment by demiankatz** [comment]
@EreMaijala, following up on our conversation on #2301, this PR eliminates the `chdir` from application initialization. It also removes some code designed to work around that behavior, and it reorganizes the `require` statements so that the dependencies between files are more appropriately represented. At a glance, things seem to be working, but of course this requires some careful exercise to be sure. I'm running tests now and will check the box if they pass without issues. I'll do more hands-on work when I have time. In the meantime, I'm interested in hearing your thoughts.

**Review by EreMaijala — APPROVED** [review]
Passes test suite, the command line tools I tried work great, looks good to me!

**Comment by demiankatz** [comment]
Thanks, @EreMaijala -- I'm going to put out a call to vufind-tech just in case anyone can think of any other reasons for concern about this (just in case there's something subtle we're both overlooking). If nobody objects in another week or two, I'll go ahead and merge.

**Comment by demiankatz** [comment]
There has been no further feedback on this change, so I am merging it now!

**Pull request merged**
