### PR TITLE
Added a getServerStatus ajax call that allows a load-balancer to veri…

### PR DESCRIPTION
**Pull request by EreMaijala**
…fy that VuFind is available and functional.

This is second of a couple of features that allow VuFind to play nice in a load-balanced/fault-tolerant environment.

### CODE REVIEW

**Comment by demiankatz** [comment]
I've merged this to master here: https://github.com/vufind-org/vufind/commit/d4d54ba242aedfb880d9a411770bc1b22d443d45 -- just one significant change: I converted your systemStatusAjax into systemStatusAction, so the url is AJAX/SystemStatus instead of AJAX/JSON?method=systemStatus. Having "JSON" in the URL for something that returns plain text didn't seem to make sense to me!

Thanks for sharing this.

**Comment by demiankatz** [comment]
One other observation: when I put invalid database credentials into my config.ini, I didn't get a status message about a database error in the AJAX routine; instead, I got a 500 error. Clearly DB problems cause a failure at a higher level in the code. I'm not sure if there are some scenarios where your check will work and others where it won't... but I left it alone for now. We may want to revisit this at some point (and possibly also check whether we can defer establishment of database connections longer).

**Comment by EreMaijala** [comment]
Thanks, that url is of course much better.

Do you by any chance have the session handler set to database? I believe that would cause 500 but I didn't see it when using file handler for sessions.

**Comment by demiankatz** [comment]
Yes, sure enough, that was the mode my test server was set to... So the real issue is that we need to get smarter about starting up sessions. It would be great if we could avoid all that work in contexts where the session is not actually needed. Perhaps something to look into for 3.0, if not sooner.

**Pull request closed without merging**
