### PR TITLE
Improve table layout and text wrapping on narrow screens.

### PR DESCRIPTION
**Pull request by EreMaijala**
Triggered by observations made in #3530, this is an attempt to improve table layout on narrow screens. The idea is to get rid of fixed table layout and instead make headings wrap at word-break and content wrap anywhere as needed, with some exceptions in specific cases. This affects most tables in VuFind, like:

- Record screen
- Holdings
- Staff view
- Full status (holdings) in search results
- Fines
- Search history
- Profile page
- Library cards
- Admin screens

### CODE REVIEW

**Review by sturkel89 — DISMISSED** [review]
I reviewed the test branch in all three themes and compared it with dev. There are lots of great improvements in the work that's been done! This review will focus on the places where I think a bit of tweaking would improve the interface.

### SEARCH RESULTS PAGE
If pagination is turned on, the Results per page element could be improved. (I’m not sure if this is table-related.) This is all the same in all three themes, in test and dev.

At wide widths, “Results per page” appears on one line and the dropdown is sized to fit the longest option. Sort is set up in the same way. 

image

image

At narrow widths, these elements are set to take up the width of the screen, but Results per page scrolls to two widely spaced lines. Can this be forced to one line?

image

image


### YOUR ACCOUNT SCREEN - Sandal only

The Your Account screen has a gap at the top in Sandal, and the gap after Saved Items is a bit large as well. Can this be modified? (Spacing in the other two themes is fine.)

This problem exists in both test and dev, and affects the following parts of the Account area when logged in:
- Basic “Your Account” page, with Saved Items as the first item
- Checked Out Items page
- Holds and Recalls
- Storage Retrieval Requests
- Interlibrary Loan Requests
- Fines
- Profile

There’s no extra gap in the following account screens:
- Search History
- Create a List

image

**Comment by sturkel89** [comment]
Additional comments:

I wanted to note all the places that I checked that look good!

### FRONT PAGE
This looks good in all three themes; no difference between test and dev.

### YOUR ACCOUNT screen - Bootstrap3 and Bootprint3
The Your Account screen looks identical and good in test and dev in bootstrap3 and bootprint3.

### FINES
The Fines screen looks identical to me in test and dev. The columns are already optimized for width, I think, since the table is laid out differently in full screen.

### RECORD SCREEN
The record screen is much nicer on test than dev!

Dev:
image

Test:
image

**Comment by sturkel89** [comment]
**Final note (also a change request):**

### HOLDINGS
Item **holdings** look identical in test vs. dev, in each of the three three themes. It looks like the column width has been adjusted in test for the upper table containing Author, Format, Language, Subjects, Tags, etc., but not in the table containing holdings information.

It might look better if the call number and availability information values lined up with the second column in the Tags etc column above.

Test branch, default driver:
image

The variation in alignment of the bottom table is much more clear (and probably harder to standardize) when you use the Demo driver.

Test branch, Demo driver:
image

**Comment by EreMaijala** [comment]
@sturkel89 I reduced the gap a bit. It's not straightforward to do more about it due to the layout differences between screens, and the gap is still a bit more than I'd like in some cases, but I can't do more about it in this context, so please file a Jira ticket if you feel more adjustment would be needed.

**Comment by EreMaijala** [comment]
@sturkel89 Regarding the differences in the tables in holdings, it's another case of two distinct tables, just like in the profile page. I don't think there's a great solution for that. That said, I think that the holdings array needs some care, it's just out of scope here.

**Comment by sturkel89** [comment]
I am happy with the improvement in the gap at the top of My Account in Sandal. It's no longer noticeably out of whack. I think we can approve the test branch and move on.

### Improved test:
image

### Dev:
image

--------------

I've made a Jira ticket ([VUFIND-1679](https://openlibraryfoundation.atlassian.net/browse/VUFIND-1679)) about the issues with Results per page at narrow widths/on mobile.

**Review by demiankatz — APPROVED** [review]
Thanks, @EreMaijala and @sturkel89 -- looks reasonable to me!

**Pull request merged**
