### PR TITLE
Don’t consider a request a search if it’s in lightbox or a facet list…

### PR DESCRIPTION
**Pull request by EreMaijala**
… request.

In addition to fixing statistics this avoids calling getResultTotal() for the facet list results object which would cause the search object to fetch full (well, maybe not full but like 100 each) facets for all facet fields (might be useful to somehow fix that too, but it would be a separate issue).

### CODE REVIEW

**Comment by demiankatz** [comment]
This makes sense to me, though if we keep adding special rules and exceptions like this, we may reach a point where we want to think about a more generic way to achieve the same effect without having to embed so much logic into the Piwik helper itself.

**Comment by EreMaijala** [comment]
I agree. It would be great if, for instance, we had categories for each action.

**Comment by demiankatz** [comment]
If you have any thoughts on how to implement such a thing, I'd be happy to discuss it! Perhaps a future dev call brainstorming topic.

**Comment by EreMaijala** [comment]
Not of the top of my head, but brainstorming might be useful..

**Comment by demiankatz** [comment]
Let me know if you'd like me to put it on the agenda. I won't be on the next call due to a conference (Chris will be leading), but I'll be on the one after that.

**Pull request merged**
