### PR TITLE
Add support for using Results_Settings facet configuration options in…

### PR DESCRIPTION
**Pull request by EreMaijala**
… the collection view too.

Actually, most of the settings already worked, but the full facet list didn't handle the case where the target action needs to contain the record id. Additionally, since the main searchClassId for the Collection action is Solr, the Options object needs to be taken from the results objects instead of instantiating one with the searchClassId.

### CODE REVIEW

**Comment by demiankatz** [comment]
@EreMaijala, did you give any thought to whether the recordId stuff here could be done more generically? It feels like this is very Collection-specific logic being pushed through the code... I'm wondering if there might be some sort of "extras" mechanism that we might be able to get away with to make this more flexible. I'm happy to take a closer look and give some more thought to whether this is feasible -- but first I wanted to ask if you had already gone down that route and found it unworkable for some reason.

**Comment by EreMaijala** [comment]
@demiankatz I didn't really. This was more like a minimal set of changes to make things work. Extras or such would probably make this cleaner. I think the ugliest part is the currentRecordId check in cluster-list.phtml.

**Comment by EreMaijala** [comment]
And I appreciate it if you can take a look on that!

**Comment by demiankatz** [comment]
@EreMaijala, it seems to make the most sense to create a parameter for appending to the base URI of the search results. That provides a generic solution without making assumptions about record IDs outside of the collection-specific code.

While testing this, I also discovered a bug: when paging through facets or switching sort options, the collection ID was being dropped, and the links stopped working. I believe that this is now corrected.

I'd still like to do a little more testing before I merge this, though I suspect it is now ready to go. Could you please take a look and see if it looks good from your end? Once you're satisfied, I'll do a little more testing and then merge it.

Thanks again!

**Comment by EreMaijala** [comment]
@demiankatz Thanks, that's a much nicer solution! Tested and works great for me.

**Comment by demiankatz** [comment]
@EreMaijala, found one more issue: the facet_limit and lightboxLimit settings in Collection.ini were being ignored due to a missing line in the SolrCollection Options class; fixed in d6d48c5. I'm going to merge now! Thanks again for adding this significant missing functionality!

**Pull request merged**
