### PR TITLE
Add ID to MARC subject heading data

### PR DESCRIPTION
**Pull request by aleksip**
Would be useful and performant to do it here.

### CODE REVIEW

**Comment by demiankatz** [comment]
@aleksip, this seems reasonable to me, but it is causing a test failure due to the addition of the new value. Do you think it is reasonable for `'id` to be set to `''` when no value exists, or would it be better to omit the key entirely? (I don't really have a preference; just asking whether you had considered both options).

**Comment by aleksip** [comment]
@demiankatz Ah, I already updated the test before noticing your comment! I don't have a preference either, but to be honest I did not consider both options.

**Comment by demiankatz** [comment]
Thanks, @aleksip. Since other fields here are defaulting to the blank string when unset, it makes sense to be consistent, so I'm happy to merge this as-is. Thanks!

**Comment by aleksip** [comment]
@demiankatz Wow, that was fast, thank you!

**Comment by demiankatz** [comment]
Well, it's the least I can do after how long #1886 is taking. (And speaking of that one, please let me know if you need me to do any more on it -- I've been waiting to see your response to Ere's comments).

**Pull request merged**
