### PR TITLE
Add some fields to authority index

### PR DESCRIPTION
**Pull request by xmorave2**
Could be useful for faceting

### CODE REVIEW

**Comment by demiankatz** [comment]
This looks like a good start. One comment: both 046 and 370 are repeatable fields. While it certainly does not make sense for a person to have multiple birth/death dates/locations, it appears that the MARC specs would allow this to occur. It would probably be a good idea to either make the fields multi-valued in Solr or else add the ", first" modifier in the properties file to ignore multiple values just in case they come up. Doing one or the other of these might help prevent fatal indexing errors. What do you think?

**Comment by xmorave2** [comment]
You are right, as it doesn't make sense, it is technically possible to have more dates/places in indexed record. I added the "first" modifier. Thanks for catching this issue.

**Comment by demiankatz** [comment]
Thanks! One more question before I merge: any objection to adding underscores to some of these field names? I think, for example, field_of_activity is a bit more readable (and more consistent with existing fields in the schema) than fieldofactivity. I'm happy to make the edits if you don't have time -- but I didn't want to go ahead and change them if it would inconvenience you in some way.

**Comment by demiankatz** [comment]
Once we settle on final field names and get this merged, we should also remember to update this wiki page:

https://vufind.org/wiki/development:architecture:authority_control

I'm also happy to take care of that. Just leaving this comment as a reminder to myself.

**Comment by xmorave2** [comment]
I added underscores to field names. You were right, it is more readable ;) If you can edit the wiki page after merging, I really appreciate it. Thank you.

**Comment by demiankatz** [comment]
Thanks, looks great! I'll update the wiki now.

**Pull request merged**
