### PR TITLE
Fix lightbox close button on narrow screens.

### PR DESCRIPTION
**Pull request by EreMaijala**
- Fixes black-on-black hover in all themes.
- Fixes non-rounded lightbox border in Bootstrap 5 themes.
- Improve size and position in Bootstrap 5 themes.
- Ensures that lightbox title doesn't overlap the close button.

### CODE REVIEW

**Comment by EreMaijala** [comment]
@sturkel89 I think all widths should be tested to ensure I didn't break anything.

**Review by sturkel89 — CHANGES_REQUESTED** [review]
I checked this branch in all themes and all widths, including using a mobile emulator. Everything is mostly fixed! Just one issue remains.

What's fixed:

- The shape of the upper right corner in the lightboxes in the new themes now matches the shape of the other three corners.
- The shading is gone, so the background of the X matches the rest of the lightbox.
- The X is bold, as it is in the other themes.
- Everything works (things look as they should at all widths, and the X closes the box) -- it all worked before as well.

**The only tweak I'd ask for is for the outline to appear when you mouse over the X in the new themes at narrow widths**.  Currently, in the new themes at narrow widths, mouseover does not cause any change in the appearance of the X:



At narrow widths in the rest of the themes, an outline appears (in addition to the mouse pointer turning into a hand) to tell you that you've approached the X. The "Close" button also changes color when you mouse over it. 



At full screen width, the lightbox has a separately floating X which changes color when you mouse over it in every theme including the new ones. So, no change is needed at full screen width.



Thanks, @EreMaijala !

**Comment by EreMaijala** [comment]
@sturkel89 I've added the hover outline. I'm not really a fan of it because it's inconsistent with all other buttons, but when I tried the inverse colors as elsewhere, it felt a bit too jarring in this context. Thought for further consideration at some point, perhaps.

**Review by sturkel89 — APPROVED** [review]
I've reviewed the latest version of the branch in all five themes. 

At wide screen widths, ALL the lightbox closing Xes do the color inversion when moused over. This looks great!

At narrow screen widths, all the legacy themes show the outlined lightbox closing X when moused over, in this format:

image

At narrow screen widths, the two new themes show the outlined lightbox closing X when moused over, in this format:

image

The design is slightly different, but the functionality is the same. It is clear to the user that the lightbox knows that it is about to be closed. (Pardon my anthropomorphizing!) 

Any given installation is going to use just one theme, so it's not necessary that the outline look identical between themes. I think this is ready to merge.

**Comment by demiankatz** [comment]
Thanks, @EreMaijala and @sturkel89!

**Pull request merged**
