### PR TITLE
Add Sorting (by index) for single facets.

### PR DESCRIPTION
**Pull request by ndege**
As proposed at VuFind mailing list here's the snippet to integrate a sorting by index (alphabetically) for single selected facets.  It's based on the native Solr functionality to use the *f.field.facet.sort* parameter. Therefore functionality is limitated to sort only *untranslated* facets. 

Use case e.g. at our institution are library branches to give the user a faster read orientation to look at inventory of his personal most visited library branch.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks for this. A few comments/questions:

1.) Looks like there's one long line that needs to get wrapped to make Travis happy.

2.) I adjusted the comments slightly in facets.ini; please feel free to make further changes if you desire.

3.) I believe there was a bug involving the default 'sort' parameter setting else clause being associated with the wrong if statement. I've fixed it here, but please let me know if I've made a bad assumption: https://github.com/finc/vufind/commit/872a4dc9682d88bf29ffdbebbcf5389eacec16e5

4.) Is there any reason for the `is_array($config->Results_Settings->sorted_by_index->toArray())
` check? This seems redundant, but maybe it's there for some reason I don't understand.

5.) I'm not crazy about the "facetSortedByIndex" language in the code; I wonder if there's a more straightforward phrase to make this easier to understand. I suppose you named this for some consistency with the existing facetSort parameter, but I think it might be more clear if the name indicated that it's a list of fields. Perhaps just changing it to a plural would be enough: facetsSortedByIndex. Or else we could call it indexSortedFacets to make it a little shorter. What do you think?

6.) I'm also not crazy about the special case looking for the 'sortedByIndex' key in the getBackendParameters() method, but we may just have to live with that -- I can't really think of a better way to do it, short of setting this parameter separately from the other getFacetSettings() values, which has its own major disadvantage of introducing inconsistent mechanisms for retrieving facet settings.

In any case, thanks for the work on this. It should be possible to merge with just a little bit more work!

**Comment by ndege** [comment]
Hi Demain,

thanks for your enlightening comments on the issue. I'm accord with your remarks to the first three points. 

Regarding 4, it's a check which I had in the habit of programming with VF1 to avoid PHP notices at the strict variant. There's no really need for it to run the program similarly. 

Regarding 5, me too a friend of short phrases. If you like we can change the phrase to indexSortedFacets. 

Concerning 6 I understand your remarks and it has been my first idea to put the functionality in a separate method, but as you I haven't seen any good solution without great circumstances. At the getBackendParameters() the code snippet is very tiny and from formality view it fits in my eyes. Except the faint case that the backend parameter isn't relevant for the whole Solr request but for a single field.

**Comment by demiankatz** [comment]
Great, glad we're on the same page. Further responses --

4.) It's definitely good to add checks to avoid notices; I just thought in this case, if asArray() always returns an array, we don't need to do an is_array() check here. I didn't confirm that we can rely on that, though -- perhaps it sometimes returns null, in which case your check would be justified.

5.) If you don't mind changing to indexSortedFacets, that would be fine with me.

6.) One alternative that might be worth considering would be to check for the special key prior to the foreach loop and then unset it... so, in pseudocode:

<pre>
if (isset($array['key'])) {
    process $array['key'];
    unset($array['key']);
}
foreach ($array as $current) { ...
</pre>

This way we're not checking a special case for every iteration of the loop, and our special case logic isn't nested quite as deeply. But if you prefer it as-is, that's okay with me too -- just providing a possible alternative. In practice, this almost certainly doesn't matter much one way or the other, but I like to get things as clean and understandable as I can when I have the opportunity!

**Comment by ndege** [comment]
Hi Demain,

I changed the code at Param.php now and try to adjust it for your specifications. As you proposed I remove the snippet from the loop.

I adopt your modification from the facets.ini without any additions. But it seems there is happen a little confusion with cherry-picking your changes at our local instance. Sorry for that.

**Comment by demiankatz** [comment]
Thanks; this looks good. I've made a couple of small adjustments and manually merged it to master.

**Pull request closed without merging**
