### PR TITLE
Updated all eligible dependencies

### PR DESCRIPTION
**Pull request by sturkel89**
Updated these dependencies, ran automated test suite (with exception noted below). All tests passed!

- composer/semver
- endroid/qr-code (tested manually)
- jaybizzle/crawler-detect
- laminas/laminas-diactoros
- laminas/laminas-feed
- laminas/laminas-filter (removed from list)
- laminas/laminas-form
- laminas/laminas-http
- laminas/laminas-i18n
- laminas/laminas-loader
- laminas/laminas-mvc-i18n
- laminas/laminas-paginator
- laminas/laminas-validator
- laminas/laminas-view
- slm/locale
- symfony/console
- symfony/yaml
- vstelmakh/url-highlight

### CODE REVIEW

**Review by demiankatz — CHANGES_REQUESTED** [review]
@sturkel89, I see what happened here: you must have opened this PR before I merged #4019, and so the two parallel changes to composer.lock created a conflict. Fortunately, there's an easy fix when this happens -- just delete the conflicted lock file and let Composer make a new one:

```
git fetch origin
git merge origin/dev
rm composer.lock
composer i
git add composer.lock
git commit
```

Then accept the default commit message and push up the changes.

(Note that this example assumes you have the main community repo set as your "origin" remote, which I think should be the case in your setup).

Wouldn't hurt to run tests one more time, but I would expect them to pass.

Please let me know if you still have questions or problems!

**Review by demiankatz — CHANGES_REQUESTED** [review]
Looks like laminas-validator and laminas-view need to be rolled back due to compatibility issues detected by phpstan. I think the laminas-view issue was already known, but laminas-validator appears to be a new problem.

**Comment by sturkel89** [comment]
@demiankatz - Thanks for your help! I made the changes you suggested, and all tests passed on my VM. I think this is safe to merge. :)

**Review by demiankatz — APPROVED** [review]
Thanks, @sturkel89!

**Pull request merged**
