### PR TITLE
Added OpenSearch elements to RSS view

### PR DESCRIPTION
**Pull request by scuy**
We needed some more metadata in the RSS view in order to able to use it as a lightweight search API.

I added the elements `totalResults`, `startIndex`, `itemsPerPage` and `Query` as defined in the [OpenSearch Spec](http://www.opensearch.org/Specifications/OpenSearch/1.1#OpenSearch_response_elements). I also added `atom:link` elements for paging the result.

Maybe this could be a useful general addition?

### CODE REVIEW

**Comment by demiankatz** [comment]
This makes a lot of sense to me -- thanks for sharing it. When I have a bit more time I'll give it a closer review to see if there are any issues we need to address before merging.

**Comment by demiankatz** [comment]
I just tried this out, and it works very well. A few minor suggestions:

1.) It seems to be a convention in the feed plug-ins to prefix getter/setter names with the extension name to avoid name collisions. It might make sense to rename setStartIndex to setOpensearchStartIndex, etc., etc.

2.) I think it might be slightly more readable to replace `$feed->setStartIndex(($params->getPage()-1) * $params->getLimit());` with `$feed->setStartIndex($results->getStartRecord() - 1);`.

3.) There are some minor style violations; if you have easy access to PHP_CodeSniffer, just run it with the PEAR styles on your code to get a report. If this is not convenient for you, let me know and I can take care of the cleanup.

It's too bad that the Zend Feed code requires some messy setup to make the plug-ins work, but I guess we'll have to live with that for now.

In any case, thanks for sharing this. I will be on vacation next week, but perhaps we can get it merged shortly after my return.

**Comment by scuy** [comment]
Thanks for your suggestions. I have tried to implement them all.

**Comment by demiankatz** [comment]
Thanks for taking care of this so quickly!

I ran into one small problem: when you fixed the style, you broke the code, because the Zend Framework base class has a protected method with a leading underscore. I put back that underscore and marked it as "codingStandardsIgnore" for now; I've also posted to the ZF2 developers list to see if there are any plans to update/improve the Feed components.

Also, because of the change in the description string, the integration test broke. I have updated this to match the new behavior.

The slightly revised code is now merged to master. Thanks again for sharing this -- it's very nice to have a more robust API for accessing VuFind programmatically.

**Pull request closed without merging**
