### PR TITLE
Fix broken combined AJAX DOI functionality.

### PR DESCRIPTION
**Pull request by demiankatz**
I've discovered a bug that was apparently introduced in the dev branch somewhere, since release-9.1 works correctly. DOI handler data is no longer injected correctly into Combined results loaded via AJAX. This PR includes a test that demonstrates the problem.

TODO
- [x] Fix underlying bug.

### CODE REVIEW

**Comment by crhallberg** [comment]
I think I figured out what the issue is. I am having a hard time testing it, but here's the scoop. There's a function called initResultScripts. On main-dev, it's in combined-search.js but on dev it's in common.js. The one on dev is way more robust. So this issue existed before the [loadHtml migration from jQuery](https://github.com/vufind-org/vufind/pull/3294).
 
This script goes through all of the modules that should run on the loaded search results and DOI is not among them. So we need to add something like:

```js
if (typeof VuFind.doi !== "undefined") {
  VuFind.doi.init(container);
}
```
 
- [Here's a link to the function on dev](https://github.com/vufind-org/vufind/blob/dev/themes/bootstrap3/js/common.js#L421)
- [Here's the function in 9.1](https://github.com/vufind-org/vufind/blob/release-9.1/themes/bootstrap3/js/combined-search.js#L3)

---

I'm actually not happy with the way this works. I actually thought this was event-based and I do think that's a better and more flexible way to do this. combined-search.js should call something like `VuFind.emit("combined-results-loaded", container)` that all modules can listen for in their inits so that we don't have to maintain (or customize) a central list.

**Comment by demiankatz** [comment]
Thanks, @crhallberg -- clearly my git bisect efforts led me astray, because I see you are correct that #3294 is not to blame here and the problem has existed for a much longer time in the dev branch. (I had thought that perhaps #2878 was to blame, but the problem also exists prior to that -- it must have been broken early in the dev-10.0 development process; I haven't taken the time to investigate more deeply).

I agree that an event-based solution seems like the best long-term solution, but it also seems reasonable to use your short-term fix to solve the problem until we have time for that more significant refactoring. If you agree, do you mind approving this so I can merge it? I'm also interested in @EreMaijala's thoughts, though I realize he will be on vacation soon and may not have time right now.

**Review by EreMaijala — CHANGES_REQUESTED** [review]
I think we also need to include doi.js unconditionally in theme config, otherwise it won't be active unless included in the first results page.

**Comment by demiankatz** [comment]
> I think we also need to include doi.js unconditionally in theme config, otherwise it won't be active unless included in the first results page.

Good point! I will add another test case for this scenario in the near future.

**Comment by demiankatz** [comment]
As promised, I have just pushed up improvements to the test suite to check all possible combinations of AJAX/non-AJAX settings in the two-column combined search scenario. As expected, the test presently fails when in 100% AJAX mode.

**Comment by demiankatz** [comment]
I did a bit more digging and figured out the root cause -- the loadHtml inline script handling did not account for src elements correctly. This is fixed in [c1a25c9](https://github.com/vufind-org/vufind/pull/3534/commits/c1a25c981b51c3697491f0f08b953985e6c5f429). The question, though, is whether we _want_ to do this. Are there potential security risks? Do we need to analyze the src in some fashion (e.g. to limit to same-site URLs)?

I'd like to hear thoughts from @crhallberg and/or @EreMaijala before moving forward with this change... but it does make all the tests pass. :-)

**Comment by demiankatz** [comment]
Based on the work I've just done in #3561, I feel more confident that the fix here is what we need to fully solve this... but I'll await @EreMaijala's return and review before moving it forward further. Until then, we should avoid merging the release-9.1 branch into the dev branch, since doing so will result in test failures until this PR is also resolved.

**Review by EreMaijala — APPROVED** [review]
Looks good to me. This is trusted code, so should not have any security implications either.

**Pull request merged**
