### PR TITLE
Upgrade to Openlayers version 4.2.0

### PR DESCRIPTION
**Pull request by lmgonzales**
Upgrading from Openlayers 3.x to 4.2.0 to allow for forthcoming upgrades to search box functionality and map display features. Replaces ol.css, ol.js, and ol-debug.js with latest 4.2.0 versions.

### CODE REVIEW

**Comment by demiankatz** [comment]
Looks like this is a completely backward-compatible change based on the fact that only vendor files are changing here. Is that the case? Do you need any assistance testing anything here before I merge this?

**Comment by lmgonzales** [comment]
Thanks @demiankatz . Yes, it's a completely backward-compatible change, and I've tested it out on my test server with no issues. I'm doing a couple of upgrades, and figured it would be best to do the upgrades in steps with the vendor file upgrades first, and then the other two upgrades to the geo-search & display functionality after that.

**Comment by demiankatz** [comment]
Yes, that makes sense to me. I'll try to find a few minutes to test this out before merging, just to give it another set of eyes; hopefully I'll get that taken care of before I leave for vacation in a couple of days!

**Comment by lmgonzales** [comment]
Thanks! I'll get the other upgrades submitted shortly.

**Comment by demiankatz** [comment]
Great, looks good!

**Pull request merged**
