### PR TITLE
Changed MultiBackend supportsMethod() logic a bit so that if a source ca...

### PR DESCRIPTION
**Pull request by EreMaijala**
...nnot be determined it is assumed that the method is supported.

### CODE REVIEW

**Comment by demiankatz** [comment]
Before I merge this, a couple of questions:

1.) Have you checked to see if this breaks any tests? If you haven't already checked, I can take a look myself if you don't have time.

2.) Would a more cautious approach be to check the method on all supported drivers if no single one can be determined? This way, if a function is impossible regardless of the user's origins, we never present the option. Perhaps this is too expensive an operation to be worthwhile... but if it's relatively cheap it might be worth implementing.

**Comment by EreMaijala** [comment]
1.) No, and it does. Fixing..

2.) I'm afraid that might be expensive. We have like a couple dozen drivers currently, and they're not all cheap to instantiate.

**Comment by demiankatz** [comment]
1.) Thanks

2.) Okay... I suppose if this were to become a problem for somebody, we could recommend setting a default driver, since that would bypass the "default to true" check.

As long as you have no concerns about false positives outside of the context of the myresearch menu, I'll go ahead and merge this as soon as you've finished updating the test.

**Comment by EreMaijala** [comment]
Test updated. This should not be a problem in other contexts where we usually have something to identify the backend (e.g. a record id).

**Comment by demiankatz** [comment]
Great, thanks!

**Pull request merged**
