### PR TITLE
Foundation5-based theme for VuFind2.4

### PR DESCRIPTION
**Pull request by lahmann**
As already mentioned on the mailing list (http://sourceforge.net/p/vufind/mailman/message/33739794/) we are developing a Foundation5 (http://foundation.zurb.com/) based theme for VuFind 2.x

Today, I am very happy to create the initial pull request with all the amazing work Claas Kazzer has done on creating the Foundation5-based theme. We tested it locally with our VuFind 2.4 codebase and it works fine, though there might be some bugs left - please don't hesitate to report those.

We would like to share this theme with the VuFind community as an alternative to the Bootstrap centered themes. Its design is basic, but functional and can be adjusted to personal needs easily by using some styles.
Claas has also prepared a detailed documentation what he needed to adjust and how the theme differs from the bootstrap-theme. This should get everyone going with the Foundation5-theme. We would be happy to share this documentation e.g. via the VuFind-wiki, too.

Please let us know what you think!

Best,
André

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks for sharing this, André! Looks like a great start though (unsurprisingly) not everything is working correctly.

What would you like from the VuFind community at this point? I don't want to bombard you with bug reports if you don't want them at this point -- and supporting every possible configurable VuFind feature is probably out of scope for your immediate needs.

On the developers call, we've recently been talking about the possibility of maintaining feature branches in the main VuFind repo for things that may not quite fit in the official distribution but which are likely to be of widespread interest. Alternate themes like this one may be good candidates for that treatment. I'm not eager to add official support for more themes since it adds a significant maintenance burden, but at the same time, I'd love to be able to offer this as another option and help facilitate its maintenance. (And, of course, that's not to say this could never be part of the official distribution -- just that I'm not looking to add themes at this time).

Anyway, please let me know how we can help -- by providing bug reports, by strategizing over maintenance plans to keep templates in sync, or in any other way!

**Comment by lahmann** [comment]
Demian, I have just pushed the latest updates of the foundation5-theme to reflect the changes in bootstrap3-theme on the release-2.4 branch.
Offering the foundation5-theme as feature branch is certainly the best way for sharing the theme with the community and not increasing the amount of maintenance at the moment. So, we should go this route.
As we will be using this theme in production we will maintain it and keep it in sync with the latest release-branch (using the bootstrap3-theme as reference). Please feel free to suggest any other strategy!

Meanwhile, any feedback is highly appreciated! So please bombard us with bug reports we'll try to fix those as fast as possible. ;)

**Comment by demiankatz** [comment]
This sounds good to me!

You may run into some inconsistencies if you target your theme against release-2.4 but open this pull request against master. There have been a handful of significant changes to master (such as refactoring of advanced search) which are not reflected in release-2.4. It definitely makes sense to focus on a release branch rather than master, but if that's the case, you might want to close this PR and rebuild it as a fork of release-2.4 rather than a fork of master. That will make testing more accurate since the view code and controller code will be more reliably in sync. The only disadvantage is that you'll have to rebuild the branch each time we mint a new release -- but in practice that's actually pretty easy and probably consists mainly of merging the new release branch into this one and resolving all the template diffs.

I'll talk about making this into a feature branch on next week's dev call.

Chris has been looking at this and has some feedback -- I'll let him know that you're ready to hear it!

**Comment by crhallberg** [comment]
I do have feedback, but I'd like to submit most of it by way of pull request. Brace yourselves. ;)

One of the more general feedback I have is to watch and make sure Bootstrap classes are removed as you replace it with Foundation syntax.

**Comment by ckaz** [comment]
Hello all, sorry to be so late to chime in -- our Kindergartens are on strike so I work odd hours. 

Many thanks for offering comments and bugs. You might be glad to hear that we're already working on several fixes such as the "similar items carousel". This, I'm sure, we'll have under control early next week. 

My main problem however is/was: Do you have (a) testing routine(s) which you employ to test all features? I mean, there are some things I never had visual access to since we don't use the respective modules, I guess such as vudl.

@Chris: We decided to keep some classes from the Bootstrap3 (BS) theme for practical reasons though I'm sure some others may have slipped our attention. We decided to use FontAwesome, for example, along with the BS date range slider and other bits an pieces since several of these will only be fully implemented in Foundation 6, which is slated for later this year.
So, I'm rather excited to see where I blundered. Please keep them comments/fixes comming. We'll duck for cover :-)

I hope we can make it for the call on Tuesday. Enjoy the holiday! 

Cheers,
Claas

**Comment by lahmann** [comment]
As this pull request was mistakenly opened against vufind-org/master I have opened a new pull request: https://github.com/vufind-org/vufind/pull/388

Please continue the discussion in the new pull request - this one is closed.

**Comment by ckaz** [comment]
Hi Chris, just saw you've moved ahead into integrating scss into the Foundation theme. That's very neat. Sorry we are so slow. I've chiselled at your previous commits and fixed the similar items carousel -- should all be ready tomorrow.
How do you switch on the "tabbed search" thing for testing?

**Comment by crhallberg** [comment]
There is a [SearchTabs] section in config.ini. If you need a second backend, you can always enable Combined Search. https://vufind.org/wiki/vufind2:combining_search_types

**Comment by ckaz** [comment]
André suggested we move to https://github.com/vufind-org/vufind/pull/388 so we are all on the same thing -- I'll hop over there.

**Pull request closed without merging**
