### PR TITLE
[VUFIND-1157] Include request in the call to getSessionInitiator in a…

### PR DESCRIPTION
**Pull request by EreMaijala**
…uth manager so that ChoiceAuth can proxy the request to the correct method.

This is my attempt at fixing https://vufind.org/jira/browse/VUFIND-1157. If there's a better way, please disregard this.

### CODE REVIEW

**Comment by demiankatz** [comment]
Ugh. I see why we need this, but I can't think of a non-ugly way to do it. There only seem to be two obvious options:

1.) Go with this solution, but then I'd feel obliged to adjust the signature of getSessionInitiator across all of the plugins for consistency, and that's a lot of mostly-pointless changes.

2.) Devise a mechanism to expose setStrategyFromRequest() as public so that it can be called directly from the Manager ... but of course this is letting implementation details of ChoiceAuth leak out into the main code. Perhaps that's not completely unreasonable, though, if we make an assumption that other drivers might also want to take advantage of a hook that presents the request during login processing.

Any further thoughts on your end?

**Comment by EreMaijala** [comment]
I thought about 2.) but then the same argument can be used for 1.) that an auth method might need the request params to decide if session initiator is needed. I don't have a strong opinion on it, so if you deside to go with 2.) I'm ok with that.

**Comment by demiankatz** [comment]
You make a good point. However, I think I lean toward option 2 for one key reason: getSessionInitiator gets called in a lot of places, but it is only easily possible to pass in the request object in a small subset of these cases. If we add a request parameter to getSessionInitiator, we create the expectation that we can rely on that being present, and the fact that it will be there in some cases but not others seems likely to create confusion. (Or, alternatively, we could ensure that it's always there, which probably requires a lot of "plumbing" work).

At least with option 2, we can clearly define when and why the request object is getting passed in (i.e. this is an opportunity to inspect the request prior to processing a login) which keeps the scope more appropriately narrow.

Ultimately, I still don't really like either option, and this may all be a sign that we'd be better off with something more event-driven here... but for now, I think option 2 may be the most pragmatic and least intrusive solution.

In any case, I'm going to try to get some other PRs merged before I circle back to this one, but hopefully I'll have time to give this a bit more thought, and perhaps propose a counter-pull-request before merging anything to master.

**Comment by EreMaijala** [comment]
That's a good point. No hurry, we'll manage in the meantime.

**Comment by demiankatz** [comment]
Please take a look at #644 and let me know if it solves the problem. (I can't test it on this end). If all is well, feel free to close this PR and hit the merge button on the other one (or ask @crhallberg to do it, if you don't have rights) while I'm away.

**Comment by EreMaijala** [comment]
Superseded by #644.

**Pull request closed without merging**
