### PR TITLE
Add Northern Sámi language

### PR DESCRIPTION
**Pull request by LuomaJuha**

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @LuomaJuha! Do you plan to add translations for any of the text domains as well? I realize that some may not be useful/relevant (e.g. CallNumberFirst, DDC23) but others are probably worth considering for translation (e.g. Exception, HoldingStatus, ILSMessages). If this is all you have available right now, I'm happy to merge this now, and we can talk about expanding it later... but if you'd like to fill more gaps before the merge, I'm also willing to wait for you to be done. :-)

**Comment by LuomaJuha** [comment]
@demiankatz at the moment, this is all we have, but there is a high chance that more translations will come later. So this is good to merge as it is like this :)

**Comment by demiankatz** [comment]
Thanks, @LuomaJuha. I did a closer review and found a few things that needed adjustments to be up to date with the current dev branch. I opened https://github.com/LuomaJuha/NDL-VuFind2/pull/2 to apply the changes. Once you merge that PR into this one, I'll merge this into the project.

**Review by demiankatz — APPROVED** [review]
Looks good to me. Thanks again, @LuomaJuha! When it comes time to request updates for the next release, should I send them to you, or should I bundle them along with the Finnish/Swedish requests I normally send to @EreMaijala?

**Comment by LuomaJuha** [comment]
@demiankatz Well, I think that sounds like a great option! Send the at the same to Ere

**Pull request merged**
