### PR TITLE
Voyager: add option to only display time part of due date for short loans.

### PR DESCRIPTION
**Pull request by EreMaijala**
Motivation: users may get confused thinking that the due time is related to library open hours while that's often not the case.

### CODE REVIEW

**Comment by demiankatz** [comment]
@EreMaijala, here at Villanova, we have term loans, so the policy matrix interval is 'T' rather than 'D'. That causes this change to fail to behave as expected.

I'm not sure, without doing research, what other values are possible in the matrix. However, I think this feature may need to be made a little more flexible. The question is, do we want to hard-code a more robust solution, or do we want to make the configuration specify which intervals have times displayed?

Any thoughts/preferences?

**Comment by EreMaijala** [comment]
Maybe the right way is to display the time only for 'H'. I'll check what the possible values are and update the code accordingly.

**Comment by demiankatz** [comment]
Thanks. That may well be the easiest solution, though checking the possible values first is a good idea. Let me know if I can be of any assistance!

**Comment by EreMaijala** [comment]
Okay, after consulting a Voyager admin I think the best way to do this is to allow to configure the loan interval types for which the time is displayed. The latest commit should achieve this.

**Pull request merged**
