### PR TITLE
Add "!default" flag to SASS variables for easier configuration

### PR DESCRIPTION
**Pull request by GrothTobias**
Some SASS-variables like the ones used in autocomplete.scss are not flagged as !default and cannot be easily overridden. To override them one has to copy the whole file into the cusom theme and change the variables.

### CODE REVIEW

**Comment by GrothTobias** [comment]
I added the "!default" to all SASS variables missing it, Excluding those that use other variables like `$pagination-active-bg: $brand-primary;` 

I am not familiar with LESS but as far as I know there is nothing similar in LESS - you just add your custom variables at the end to override the previous usages.

**Comment by demiankatz** [comment]
@GrothTobias, our SASS files are currently auto-generated from our LESS files; that's why this PR is failing, because the CI process is detecting inconsistencies between the LESS and SASS files. There is special markup you can include in the LESS files to create alternate versions of lines for SASS. If this is the best path forward, we can use that technique to make things work. However, before taking further action, I'd like to hear @EreMaijala's opinion, since I know he has been working more closely with SASS as we prepare to transition from Bootstrap3 to Bootstrap5 (see #3222).

**Comment by GrothTobias** [comment]
Okay, then i will look up how the markup works

**Comment by demiankatz** [comment]
@GrothTobias, you can see an example of the markup here:

https://github.com/vufind-org/vufind/blob/dev/themes/sandal/less/sandal.less#L1-L8

The LESS to SASS conversion process looks for the `#LESS>` and `#SCSS>` markers and adjusts the comments so that in the SASS version, the LESS code is commented out and the SASS code is uncommented. So whenever variations are needed, this technique can be applied.

**Comment by GrothTobias** [comment]
Seems like i did something wrong with the markup. I will check this next week.

**Comment by demiankatz** [comment]
@GrothTobias, if you run `npm run build:css` that might reveal what is going wrong -- that should generate the SCSS, and if it doesn't match what you've committed, that may give you a clue.

**Comment by EreMaijala** [comment]
I'm working on improving the LESS to SASS translation. That could bring a bit of relief, though the ultimate solution will probably require Bootstrap 5 (#3222).

**Comment by EreMaijala** [comment]
That said, the conditionals work fine at the moment. It's just quite easy for them to get out of sync if there are a lot of them.

**Comment by GrothTobias** [comment]
I edited the .less and .scss files manually. Didn't realize that variables in the LESS-section have their @ replaced with $ while generating.

We can also push back this PR and look at it again after BS5 is merged.

**Comment by demiankatz** [comment]
This seems harmless to me; I'm happy to merge it, but I'll wait and make sure @EreMaijala has no concerns about the final version first.

**Review by EreMaijala — APPROVED** [review]
I think this is safe to merge, and a good thing!

**Comment by demiankatz** [comment]
Thanks, @GrothTobias and @EreMaijala!

**Pull request merged**
