### PR TITLE
Make "Page not found", theme init and cookie manager with limit_by_pa…

### PR DESCRIPTION
**Pull request by EreMaijala**
…th setting work in console.

The theme init change stems from the fact that we use the theme code also in console utilities, but I hope that can be accepted in the core anyway.

### CODE REVIEW

**Comment by EreMaijala** [comment]
The cookie stuff is also something we've had a local override for console utils.

**Comment by demiankatz** [comment]
This looks reasonable to me, and I believe it may even resolve the long-open JIRA ticket https://vufind.org/jira/browse/VUFIND-999. Before I merge, though, do you have any recommendations on how to test this? Are there any utilities that rely on this that might be worth generalizing and sharing? (If the answers to those questions are no, that's fine, and I'll go ahead with some ideas of my own... but figured I might as well ask first).

**Comment by EreMaijala** [comment]
I do, but I need to get them to work properly now before making PRs. There's at least automatic account expiration and its reminders that may be quite important for GDPR compliance.

**Comment by demiankatz** [comment]
Makes sense. I'll do a little testing of the existing console utilities, and if all is well, I'll go ahead and merge this today so you can move forward on those other things.

**Pull request merged**
