### PR TITLE
Direct export

### PR DESCRIPTION
**Pull request by mbeh-ub**
Hi,

as you suggested I split the pull request #421 (Master extended export #421) into direct-export and
html-export. 
This pull request adds an option to bypass the "Download File"-Dialog and directly offers to save
the exported file.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks for splitting this part off from #421. As I mentioned on that pull request, I'm curious whether it makes sense to have "download" as a global [BulkExport] setting or if it might be better to make this configurable on a format-by-format basis. Perhaps it makes sense to have a default behavior at the [BulkExport] level with the ability to have case-by-case overrides.

**Comment by mbeh-ub** [comment]
I also couldn't decide which variant is better (global or local). So I check if the exportType is set for the given $format and use the global option in config.ini -> [BulkExport] -> exportType as a fallback.

**Comment by demiankatz** [comment]
I've done a little bit of work on this, adding some documentation and changing some names in an effort to make it more clear. (Though please feel free to suggest further changes if you don't like anything I have done).

For the limited case of "bootstrap3 theme with Javascript enabled" I think this is working well. However, we need to also add support for a few more cases:

  - Bootstrap3 theme with Javascript disabled
  - Blueprint theme with and without Javascript enabled

I don't think this will be difficult, but I have to refresh my memory on how this stuff works. I'll try to find time before too long.

**Comment by mbeh-ub** [comment]
1) I added the feature to the Blueprint theme.
2) Concerning the Javascript free case, I would suggest to keep the current behavior.
I tried to initiate the download and redirect the user to the recent page after clicking "Export"-Button.
But this doesn't seems possible.

**Comment by demiankatz** [comment]
Thanks for this. I've merged this to master with a couple of small adjustments to comments in the .ini files (to reduce redundancy and to address the fact that Javascript and non-Javascript behavior differ). I agree that, while we can make 'download' cause an immediate download in no-JS mode, the impossibility of redirecting the user to a better page following the download renders that option user-unfriendly in that context.

Thanks again for your work on this feature!

**Pull request closed without merging**
