### PR TITLE
Alma tweaks

### PR DESCRIPTION
**Pull request by EreMaijala**
This pull request contains a set of fixes and improvements to the Alma driver. I've bundled them here since a few of them depend on the previous commit.

I believe these should be all back-compatible, but I'd appreciate if @betullam could also check that everything still works properly.

### CODE REVIEW

**Review by betullam — APPROVED** [review]
I tested everything and all seems to be working well.

The only thing that I want to mention is the logging. In general it is very good to get log messages. But I saw that the API key and user data are getting logged. I am particularly thinking about the GDPR here. As the logging is not activated by default I think it is not a big problem ... and introducing exceptions seems to complicated. But anyway: I wanted it to be mentioned just if you want to think about it.

**Comment by demiankatz** [comment]
@betullam, this is a good point -- always better to avoid the possibility of inadvertently logging something we don't want to log. Are the key and user data being exposed in a predictable enough fashion that we can apply regular expressions to the log messages to censor them out (maybe with an Alma.ini setting to disable the censorship) or would this be more complex to solve?

**Comment by demiankatz** [comment]
(Also, as a possible example, see how the FOLIO driver handles logging - https://github.com/vufind-org/vufind/blob/master/module/VuFind/src/VuFind/ILS/Driver/Folio.php#L120 -- not that this is necessarily perfect, but it's at least attempting to avoid logging certain sensitive details).

**Comment by betullam** [comment]
@demiankatz and @EreMaijala - I haven't thought it through in much detail but I think at least masking user data from the response body should be possible without adding too much complexity as they all start with a `<user(s) ...` tag. So with some regex these tags could be removed. Also, removing the API key should be possible as it can be taken from `Alma.ini` and then remove that string from the log message.

**Comment by EreMaijala** [comment]
@betullam, @demiankatz, the idea here was that when debug logging is enabled you actually get everything. Otherwise you'd only get logs for errors, and even those shouldn't include sensitive data unless there's such stuff on the error page. And debug logging shouldn't be enabled in production. If it is, there must be a strong reason for that, and I'm hesitant to omit actual data that might be crucial for debugging. Additionally, it shouldn't be possible to access the logs unless authorized.

This said, I'm happy to change the logging or remove the debug logging possibility if you feel that's better.

**Comment by demiankatz** [comment]
@EreMaijala, I think I'm persuaded that debug logging in production is not going to be a normal part of operations, and we have to trust users to manage their debugging appropriately. We could put in some effort to mask things, but it might not be perfect, and imperfect masking might be worse than none since it could inspire false confidence. I'm going to merge this as-is for now; if we need to revisit it in future, I'd suggest a new pull request that adds a new Alma.ini setting to manage debug levels, perhaps with a conservative default setting.

**Comment by demiankatz** [comment]
One last question, @EreMaijala: are any of these fixes critical enough that you think we should cherry-pick them back to the release-6.0 branch for inclusion in 6.0.1?

**Comment by EreMaijala** [comment]
@demiankatz For us it's not crucial to get any of them into 6.0.1, but I'd say that the following would be good candidates: 
657791f
a02a6b2
705cc50
6a933d0

**Comment by demiankatz** [comment]
Thanks, @EreMaijala -- I merged the first three since those fix some problems with the existing code, but I left the fourth off because it seems more like a new feature (it's an improvement, but it wasn't broken before). One question about that pagination, as well: should the page size be configurable through Alma.ini?

**Comment by EreMaijala** [comment]
@demiankatz Well, yes, but the existing code will only display up to 100 loans, so in that sense it fixes a potential problem.

**Comment by demiankatz** [comment]
@EreMaijala, I see! That does seem to justify the merge. I'll take care of it. Thanks! :-)

**Pull request closed without merging**
