### PR TITLE
fix: don't override toggleAttrs in menu-button.

### PR DESCRIPTION
**Pull request by crhallberg**
Thanks for the spot on this, @demiankatz

### CODE REVIEW

**Review by demiankatz — CHANGES_REQUESTED** [review]
Thanks, @crhallberg. Unfortunately, it looks like adding the `btn` class to the control has some side effects.

In every theme, it changes the mouseover highlight box from being fully rectangular to having rounded corners. Since the control is currently used in the header, this causes some inconsistency, since the highlight on the "login" control looks different from the highlight on the language/theme controls immediately next to it. Maybe this is justifiable, but it's a little weird. Perhaps the solution is to add the btn class to the login control for consistency.

More serious is the effect in the bootprint3 theme. Here's what it looks like in dev:

image

And here's what it looks like in this branch:

image

Any thoughts/suggestions/preferences?

**Comment by crhallberg** [comment]
I'm not opposed to removing `btn`. It's not essential for function and can be easily overwritten where we need it. I can't remember why we added `btn` though. Which buttons did it benefit?

**Comment by demiankatz** [comment]
> I'm not opposed to removing `btn`. It's not essential for function and can be easily overwritten where we need it. I can't remember why we added `btn` though. Which buttons did it benefit?

If I'm remembering correctly, we needed the btn class to eliminate an unwanted outline in findingaugustine.org's language drop-down control. But if there's no benefit to the btn class in the core project, we can easily add it back in that instance as a customization instead of making the change globally.

**Comment by crhallberg** [comment]
> we can easily add it back in that instance as a customization instead of making the change globally.

I think that's the most widely compatible option. `.btn` removed in 1ccd21f.

**Review by demiankatz — APPROVED** [review]
Thanks, @crhallberg!

**Pull request merged**
