### PR TITLE
VUFIND-1675: Fix mobile top menu colors on sandal

### PR DESCRIPTION
**Pull request by maccabeelevine**
For https://openlibraryfoundation.atlassian.net/browse/VUFIND-1675

### CODE REVIEW

**Comment by maccabeelevine** [comment]
I think this is an improvement.  I don't love the blue color for the active item, but I'm not sure what is the expected .active color in sandal.

image

**Review by sturkel89 — CHANGES_REQUESTED** [review]
Thanks for this, Maccabee! Your update is a big improvement over dev. 

I have an idea for you! At Demian's suggestion, I checked this branch in bootstrap5 and sandal5 as well as in sandal. Sandal5 uses a very similar approach to mobile as it does to desktop for these dropdowns: all of the options are in a dropdown with a white background, and the selected item is the background blue with white font while the moused-over items are highlighted in the gray color. Could we do that in the sandal theme?

### Examples from Sandal5 on mobile:

image
image

**Review by demiankatz — CHANGES_REQUESTED** [review]
@maccabeelevine, I don't think @sturkel89's suggestion sounds too hard to implement. If you're out of time, let me know and I can try to do it later this week.

Also, either way, we're going to need to reconcile the minor conflicts caused by merging your other recent PR. I can also help with that if it saves you any trouble (though it's just a matter of rebuilding the CSS, so not a big deal).

Thank you both!

**Comment by maccabeelevine** [comment]
I've done some further changes to mimic sandal5 colors as @sturkel89 suggested.  It's really a hack though, as the sandal5 styling (which is very nice) includes elements like the rounded corners and margin that actually come from bootstrap5, not sandal5.  So I'm not sure the design really works without the full bootstrap5 behind it, which is a lot of built-in (vendor) styling that I don't want to try to mimic here.  That said, I think this is maybe another incremental improvement, but I'm not sure.

**Comment by demiankatz** [comment]
Thanks, @maccabeelevine! I'll be happy if it's better than the mess it was before, even if it's not perfect. :-) We'll be moving to bootstrap5/sandal5 in another release, so this can be a stopgap measure in the meantime. In any case, I'll wait and see if @sturkel89 has anything to add before merging anything.

**Review by sturkel89 — APPROVED** [review]
This is a big improvement over the first iteration of this branch, and a huge improvement over what we had before!

True, bootstrap5 and sandal5 have nicer rounded corners and the dropdowns are narrowed in mobile to show the blue color in the background. But all the legacy themes have these dropdowns as full-width in mobile, so it's fine.

image

image


### Definitely good enough to merge! Thanks!!

**Comment by maccabeelevine** [comment]
@sturkel89 I should mention, please check desktop as well -- some of the new CSS would in theory affect desktop widths as well (no media query), although I'm not sure they have any effect in practice.

**Comment by sturkel89** [comment]
@maccabeelevine I looked at the dropdowns in all five themes on desktop (at a fixed width) before trying my mobile emulator. Everything looked good! (I could see the lack of rounded corners...) I have shut down my VM, but is it worth me trying again and varying the width of the screen?

**Comment by maccabeelevine** [comment]
> @maccabeelevine I looked at the dropdowns in all five themes on desktop (at a fixed width) before trying my mobile emulator. Everything looked good! (I could see the lack of rounded corners...) I have shut down my VM, but is it worth me trying again and varying the width of the screen?

Ok that sounds plenty robust already, thanks!

**Review by demiankatz — APPROVED** [review]
Thank you both!

**Pull request merged**
