### PR TITLE
Archives space integration

### PR DESCRIPTION
**Pull request by mis306lu**
This integration connects with the ArchivesSpace API to display finding aid details on a tab in the record details page.
It relies on the ArchivesSpace URL's being in the 555 field.
I added more details about the integration in the [ArchivesSpace.ini](https://github.com/vufind-org/vufind/blob/archivesSpace-integration/config/vufind/ArchivesSpace.ini)  file

TODO
- [x] Laminas migration

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @mis306lu -- we're currently working on setting up the public piece of our own ArchivesSpace instance. It may take a couple of weeks to get that all sorted out, but once I have something to test with, I will give this a try and provide some feedback!

**Comment by demiankatz** [comment]
@mis306lu, in the meantime, there are some style issues that PHP_CodeSniffer is complaining about -- if you click the details of the Travis build you can see exactly what is going on. Some of them can be cleaned up automatically with phpcbf -- I'll take care of that in just a minute -- but the rest might require a little attention. Let me know if you'd like me help sorting any of them out.

**Comment by demiankatz** [comment]
@mis306lu, I finally have my ArchivesSpace instance configured correctly, so I've begun experimenting with this branch. I've just committed a significant amount of work to support harvesting Dublin Core from ArchivesSpace over OAI-PMH and then indexing that directly into VuFind, as an alternative workflow to the MARC 555 approach (though both can be supported without conflicting). It's not quite working yet, but I think I'm pretty close. I'll keep you posted as I make further progress!

**Comment by demiankatz** [comment]
@mis306lu, I've done a bit more work on this, and I'm now successfully communicating with the ArchivesSpace API from VuFind. However, in the example records I'm working with, many of the fields your template expects to see do not appear to be populated. Perhaps there are differences between the way we're using ArchivesSpace at our respective institutions, or maybe I'm just doing something wrong. In any case, I've made all the code more tolerant of missing data, so hopefully it will still work for you while not displaying empty labels/sections on my end. I need to take a closer look at the API responses and perhaps add some more outputs to the template... but for now, I'm going to take a break so you can review what I have done so far. I'd like to be sure this still works for you before I go any further!

**Comment by demiankatz** [comment]
@mis306lu, now that we've migrated from Zend Framework to Laminas in master, I should update this branch to match. However, if that will make your own testing/review more difficult, please let me know and I will hold off until you have had time to comment on the work so far. Thanks!

**Comment by demiankatz** [comment]
@mis306lu, I've gone ahead and migrated to Laminas in the interest of moving things forward... but if that's a problem, reverting it is just a matter of string-replacing Laminas back to Zend in a couple of files. :-)

**Comment by demiankatz** [comment]
@mis306lu, another update: I've extracted the work I did here for XSLT import of ArchivesSpace records harvested over OAI-PMH into a separate PR (#1623) so I could merge that to master. We're going to go live with OAI-PMH-based ArchivesSpace indexing soon, and for our purposes, linking directly to the record in the ArchivesSpace front-end makes more sense than embedding details in a tab, so I don't think we're going to need the deeper integration that's under development here.

I am, of course, still happy to work with you to finish polishing this up so we can merge it... but before we spend more time, you might want to take a look at the OAI-PMH approach, since I'm pretty sure that was not an option when you first implemented this, and it might make your workflows easier.

I'm happy to discuss this further as needed!

**Comment by demiankatz** [comment]
@mis306lu, I'm reviewing pull requests that haven't moved in a while, and so I just wanted to touch base and see where we are with this one. As always, if you don't have time for this right now but think it's worth leaving open for the future, that's fine! I'm just curious if the simpler OAI-PMH approach might work for you as well, in which case we might not need to finish this work.

**Comment by mis306lu** [comment]
@demiankatz  - I do think this will be a better approach.  I'm going to close this PR and leave notes for my predecessor about the new integration.  thank you!

**Comment by demiankatz** [comment]
Thanks, @mis306lu! As I'm sure you know, I'm happy to answer questions for the new person whenever they arrive. :-)

**Pull request closed without merging**
