### PR TITLE
Don't try to add ID prefixes if source is empty in MultiBackend driver.

### PR DESCRIPTION
**Pull request by EreMaijala**
From [VuFind-Tech] MultiBackend in result-list.

### CODE REVIEW

**Comment by jochen-lienhard** [comment]
No I understand my problem. We are using the MutliBackend in a little different way. Our ID is for example 123456 and we add the prefix for the check later, because we have one title with one ID with the same ID in different Backends, and one main Backend for the result-list - that becomes default. Your fix does not work, because $source exists, but is empty. So a check ($source === "") or empty($source) would fix the problem.

**Comment by jochen-lienhard** [comment]
Sorry ... has wrong check copied .... fix works!

**Comment by EreMaijala** [comment]
Thanks for testing!

**Comment by demiankatz** [comment]
Thanks to both of you!

**Pull request merged**
