### PR TITLE
Improve mobile search result view.

### PR DESCRIPTION
**Pull request by crhallberg**
Only controversial thing here is the removal of the result numbers and checkboxes from each result and the bulk actions menu up top. It was hidden to decrease distance from top to first result. Also, there are many sharing options available on mobile built into the OS.

More advanced mobile features, like collapsed menus, that might restore this functionality will be put into a separate PR at a later time.

Before | After
---|---
img_6196 | img_6195

### CODE REVIEW

**Comment by ckaz** [comment]
Hi Chris, I think it is perfectly fine to remove the numbers and checkboxes. We discussed this in much detail in our "Usability Group" and decided to add "Add to BookBag" icons for each record so users don't lose that functionality. We also kept the "Add to Favorites" icon but moved the entire action icons section to the right margin. 
I'll attach a screenshot. (The hand icon currently takes you to the access tab, this feature is under discussion and might get changed soon.)
We also removed sort options, result count to have a less cluttered result-focussed view and we haven't had a single complaint about it.
mobile-view-less-clutter

My best and a belated Happy New Year to you guys!

**Comment by crhallberg** [comment]
@ckaz I really like the style of your mobile view. Does the second button copy a link to the record?

**Comment by crhallberg** [comment]
I posted this in the wrong PR:

The pub date timeline (powered by flot) doesn't work with touch and the touch add-on isn't the fix we're looking for. Since it's between the top of the page and the first result, would anyone object to hiding it on mobile?

**Comment by ckaz** [comment]
@crhallberg: We get the ID of the record so it can get added to the bookbag. 

We have this at the top of our RecordDriver/SolrDefault/result-list.phtml

`<?`
`$id = $this->driver->getUniqueId();`
`$cart = $this->cart();`
`$cartId = $this->driver->getResourceSource() . '|' . $id;`
`?>`

and later in the same file we use

`<? /* Add to bookbag */ ?>`
`            <? if ($cart->isActive()): ?>`
`              <div class="bookbag-resultlist text-center left">`

`                <a id="cart-add-resultlist_<?=$id?>" name="<?=$this->escapeHtmlAttr($cartId)?>" class="cart-add-resultlist has-tip" data-options="disable_for_touch:true;touch_close_text: '<?= $this->transEsc('Tap to close')?>'" aria-haspopup="true" data-tooltip title="<?=$this->transEsc('Record to Book Bag')?>">
                  <i class="fa fa-clipboard passive "></i>
                </a>`

`                <a id="cart-remove-resultlist_<?=$id?>" name="<?=$this->escapeHtmlAttr($cartId)?>" class="cart-remove-resultlist has-tip hide" data-options="disable_for_touch:true;touch_close_text: '<?= $this->transEsc('Tap to close')?>'" aria-haspopup="true" data-tooltip title="<?=$this->transEsc('Remove from Book Bag')?>">
                  <i class="fa fa-clipboard"></i>
                </a>`

`              </div>`
`            <? endif; ?>`


Out site specific js-file then has the following section for the bookbag:

`function bookbagResultList($form) {`

`    $('.cart-add-resultlist').click(function() {`
`        var cartId = $(this).attr('name');`
`        if (cartId.length > 0) {`
`            cartId = cartId.split('|');`
`            var currId = cartId[1];`
`            var currSource = cartId[0];`
`            VuFind.cart.addItem(currId, currSource);`
`            $(getAddBtn(currId)+','+getRemoveBtn(currId)).toggleClass('hide');`
`        } else {`
`            // Search results`
`            VuFind.cart._registerUpdate($form);`
`        }`
`    });`

`    $('.cart-remove-resultlist').click(function() {`
`        var cartId = $(this).attr('name');`
`        if (cartId.length > 0) {`
`            cartId = cartId.split('|');`
`            var currId = cartId[1];`
`            var currSource = cartId[0];`
`            VuFind.cart.removeItem(currId, currSource);`
`            $(getAddBtn(currId)+','+getRemoveBtn(currId)).toggleClass('hide');`
`        } else {`
`            // Search results`
`            VuFind.cart._registerUpdate($form);`
`        }`
`    });`
`}`

`function getAddBtn(currId) {`
`    return '#cart-add-resultlist_'+currId;`
`}`

`function getRemoveBtn(currId) {`
`    return '#cart-remove-resultlist_'+currId;`
`}
`
Hope I've caught all the bits and pieces.

We got rid of the checkboxes in all views from mobile to desktop in favor of the "add to"/"remove from" Bookbag buttons. However, we kept an "Add all to Bookbag" function in an action button bar for tablet and desktop. The functionality of this is still unsatisfactory as users will have to select a extra checkbox here to add all items on the page _after_ clicking on the "All to Clipboard" button. We just hadn't had the time yet to develop/think of a smoother workflow for this, resolving the original workflow based on checkboxes.

Here's a link to the English version of the search mentioned above: https://katalog.ub.uni-leipzig.de/Search/Results?lookfor=robert+fripp&type=AllFields

Cheers!

**Comment by crhallberg** [comment]
I really liked this idea so I started working on adding the Bookbag toggle buttons in more places: https://github.com/vufind-org/vufind/pull/884

**Comment by demiankatz** [comment]
@crhallberg, one observation: while the top controls disappear from search results in mobile view, they do NOT disappear from the favorites screen. This is particularly disconcerting because the checkboxes DO disappear in both places. I suspect you may just need to make some minor adjustments so that bulk search actions and bulk favorite actions behave consistently.

**Comment by crhallberg** [comment]
Fixed. Thank you.

**Pull request merged**
