### PR TITLE
Fix handling of link tags in EDS records.

### PR DESCRIPTION
**Pull request by EreMaijala**
EDS seems to return link elements in records. They were not processed correctly and resulted in invalid HTML.

### CODE REVIEW

**Review by demiankatz — CHANGES_REQUESTED** [review]
Thanks, @EreMaijala -- this seems like a change worth covering with a unit test. There's already a test class for this, so adding it should be easy. Let me know if you'd like me to take care of that.

**Comment by EreMaijala** [comment]
@demiankatz Sure thing, test now added.

**Review by demiankatz — APPROVED** [review]

**Comment by demiankatz** [comment]
Thanks, @EreMaijala!

**Comment by demiankatz** [comment]
I also backported this to release-8.1, since it may be useful to make available sooner to avoid bad data problems.

**Pull request merged**
