### PR TITLE
daia test

### PR DESCRIPTION
**Pull request by jochen-lienhard**
The goal is to build a test case for a json and a xml result for the daia ils driver.

### CODE REVIEW

**Comment by jochen-lienhard** [comment]
follows up to PR https://github.com/vufind-org/vufind/pull/281

**Comment by jochen-lienhard** [comment]
I'm not sure about the place for the xml and json result file. 
Andre can you please create a xml dummy file and perhaps modify the json version?
I give you the permission to push on this branch.

I hope, I will find time to modify the DAIA.php next week.

**Comment by demiankatz** [comment]
I notice that the class in DAIATest.php is named DAIAJSONTest; this will prevent the test from running successfully since PHPUnit expects class names and file names to correspond.

**Comment by jochen-lienhard** [comment]
What kind of test do we need? 
- config (which DAIA.ini should be tested, the local one?)
- getStatus

Which functions do we need?

**Comment by demiankatz** [comment]
Regarding which configuration to use, I'd recommend that you simply call the setConfig method with an array to pass in whichever configurations are appropriate for your test case. I don't think we need to do any loading of .ini files from disk in order to test the functionality of the class -- that's all addressed by higher level code.

Regarding what you actually need to test, I think the main things to check are:

a) Input is converted to an appropriate DAIA request
b) DAIA responses are converted to appropriate data formats expected by VuFind

So the test strategy I would follow would be to create a DAIA object with a mock HTTP service that expects a particular input and returns a particular output. Then your tests pass values to the DAIA object, which hopefully generate the expected input... then the output comes back from simulated HTTP and your test verifies that the processed result is correct.

If you need help with the details, let me know.

Also, you might want to look at this code coverage report:

https://vufind.org/hudson/job/VuFind2/clover/VuFind/src/VuFind/ILS/Driver/DAIA.php.html

Obviously right now very little is covered... but it might be worthwhile for us to merge a first pass of the test, then look at the updated coverage report, and then add some more test cases to cover special cases that we missed the first time around.

Does that help?

**Comment by jochen-lienhard** [comment]
I'm a little bit confused. I tried to change the response call from httpService to httpClient. The response code is 200, but the body is empty. Do you have any idea, what may be wrong.
I will continue tomorrow.

**Comment by lahmann** [comment]
Jochen, sorry for answering this late - I pushed a daia.xml and a daia.json testfile which I composed from reallife DAIA queries at http://daia.gbv.de. Both DAIA responses validate in the DAIA-Validator (http://daia.gbv.de/validator). I deleted the other daiajson-file - hope that's ok with you.

I also adjusted the setConfig calls for the testfiles and included the output of the current DAIA->getJSONStatus and DAIA->getXMLStatus for these testfiles.

Let me know if you need any further help.

**Comment by demiankatz** [comment]
André, thanks for sharing the fixtures!

Jochen, I think the problem may be that the test adapter expects the response to be a full HTTP response, including headers. Since these fixtures are only the body portion, that may be causing unusual behavior. Two possible solutions: either update the fixtures to contain complete headers, or else construct a Zend\Http\Response object (which should allow you to set the body and other values independently of one another) and then pass that to setResponse instead of the raw string. Let me know if you need more help with this!

**Comment by jochen-lienhard** [comment]
I'm not sure, if the changes in DAIA have any effects to the PICA driver.

**Comment by jochen-lienhard** [comment]
I'm not sure, where to put the response. The response of the client is empty, when I call getStatus in the test case. Usually the response is put to the adapter, but then the implementation of DAIA.php may be wrong. I will look at it next week. If you have any idea, how to solve this problem, feel free to fix, comment or something else.

**Comment by demiankatz** [comment]
It's possible that the DAIA changes affect the PICA driver, but as far as I know, nobody is using it (and it has never been tested). I'm told that there will eventually be a PAIA driver that will render it completely obsolete, and I plan to delete it whenever that comes along. For now, it's just retained for reference.

Regarding your response problem, I will try to find time to look more closely at that tomorrow.

**Comment by demiankatz** [comment]
I've just pushed up a fix to the fixture loading; I think you should have better luck now. Let me know if you need more help!

**Comment by jochen-lienhard** [comment]
It looks good, thanks. Now I compare the result array for both. Do you think we need more checks?

**Comment by demiankatz** [comment]
Hello,

I have manually merged this to master with a few adjustments:

1.) I adjusted the test class so that it works with the existing DAIA driver. While we certainly could change the constructor signature to factor out use of the HttpService, if the only reason we did that was to make the test work, it's not strictly necessary. This way, we can test the code without interfering with backward compatibility.

2.) I deleted the empty testgetPurchaseHistory() method; I assume this is a placeholder for something that hasn't been implemented yet.

You can see the code coverage report for this new version of the test class here:

https://vufind.org/hudson/job/VuFind2/clover/VuFind/src/VuFind/ILS/Driver/DAIA.php.html

There's definitely some more work to be done, but this is a good step in the right direction.

I'm closing this pull request for now, but if you have time/inclination to add more tests, feel free to start another PR.

**Pull request closed without merging**
