### PR TITLE
Place hold success link expansion

### PR DESCRIPTION
**Pull request by crhallberg**
Expanding success messages with links to Storage and ILL requests

### CODE REVIEW

**Comment by demiankatz** [comment]
Manually merged to master to simplify history.

**Comment by EreMaijala** [comment]
Shouldn't the translation token have a _html suffix now?

**Comment by demiankatz** [comment]
You are absolutely correct. I'll fix that shortly.

**Comment by demiankatz** [comment]
Okay, renamed strings to have _html suffixes; also restored non-HTML version of storage retrieval request string since the VoyagerRestful driver uses it.

**Comment by EreMaijala** [comment]
Looks like that didn't quite work out. At least the Finnish translation for storage_retrieval_request_place_success is now wrong and the _html versions seem to be missing (and they wouldn't be used anyway without a code change, no?).

**Comment by demiankatz** [comment]
Spoke too soon -- did the work on my desktop and forgot to push it up. Should be fixed now. Sorry!

**Comment by EreMaijala** [comment]
Thanks! Could you restore 'ill_request_place_success' too? I think the Voyager driver is supposed to use it but there's a mistake ('ill_request_success' probably my bad)?

**Comment by demiankatz** [comment]
Sure, I'll fix all of that. Thanks for catching it!

**Pull request closed without merging**
