### PR TITLE
Added --no-background switch to vufind.sh to be compatible with systemd

### PR DESCRIPTION
**Pull request by jriedl**
Adjustments for using vufind.sh within a service script to integrate with systemd (needed on CentOS 7).
To integrated systemd copy the following script to /usr/local/lib/systemd/system and name it vufind.service. vufind can then be enabled on start, started, stopped and healthchecked by calling

systemctl [enable, start, stop, status] vufind

------
[Unit]
Description=VuFind Starter
After=network.target httpd.service mariadb.service

[Service]
Type=fork 
ExecStart=/bin/sh --login -c "/usr/local/vufind2/vufind.sh --no-background start"
User=root
ExecStop=/bin/sh --login -c "/usr/local/vufind2/vufind.sh stop"
ExecReload=/bin/sh --login -c "/usr/local/vufind2/vufind.sh --no-background restart"

[Install]
WantedBy=multi-user.target

-----

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks for sharing this. Unfortunately, though, I think there's a problem here: if you start vufind.sh in --no-background mode, it doesn't write a PID file (since Jetty waits forever when it isn't backgrounded). Thus, when you try to stop vufind.sh, it can't find which process to kill, and it doesn't work.

This suggests to me that systemd isn't going to be able to stop VuFind either. Are you actually seeing working results?

**Comment by jriedl** [comment]
Thanks a lot for your feedback. In my tests one could see that vufind.sh finished and created the pid file when using systemctl start and removed it when stopping. Stop seemed to have the the intended behaviour. Currently I can only assume that providing an explicit ExecStop is in fact superfluous since systemd takes charge of killing the processes itself (however needed anyway to remove the pid-file). I will double check that, unfortunately it will probably only be on next Monday.

**Comment by demiankatz** [comment]
No rush! This can wait until you're ready.

Perhaps the best solution is to skip writing the PID file entirely when in --no-background mode. This way, if you start VuFind in --no-background mode, "stop" and "restart" are meaningless (you have to do these things manually) and there's no necessary cleanup for systemd to do (assuming it really does manage its own processes).

**Comment by jriedl** [comment]
Spent quite a lot of time today to try to find a decent solution. From my point of view adding too many special cases to vufind.sh  might confuse things. Analysed the service file, and plannend to use the check-parameter of vufind.sh to export the settings to a temporary file and then trigger RUN_CMD as ExecStart. Ran into trouble with on the fly generation of the environment file.

An adapted vufind.service seems to allow to use vufind.sh in an unmodified way, so no need for --no-background any more 

---
Description=VuFind Starter
After=network.target httpd.service mariadb.service

[Service]
Type=forking
ExecStart=/bin/sh --login -c '/usr/local/vufind2/vufind.sh start'
PIDFile=/var/run/vufind.pid
User=root
ExecStop=/bin/sh --login -c "/usr/local/vufind2/vufind.sh stop"

\# Java responds to a SIGTERM by returning with exit code 143 which leads to "failed" exit in the systemd-Logs
SuccessExitStatus=143



[Install]
WantedBy=multi-user.target


---

**Comment by demiankatz** [comment]
Thanks! Sounds like I can close this without any action.

I've pasted your systemd configuration into the wiki here:

https://vufind.org/wiki/starting_and_stopping_vufind#linux_systemd_method

If you get a chance, please take a look and feel free to make any necessary corrections/adjustments.

**Comment by jriedl** [comment]
Thanks a lot for adding this to the documentation. I would have been glad to find a proper way to overcome the nuisance of absolute paths in the service file but systemd seems to be reluctant to paths derived from an external environment. Hope it might help someone anyway.

**Pull request closed without merging**
