### PR TITLE
KohaILS Driver for VuFind

### PR DESCRIPTION
**Pull request by misilot**
This PR will provide driver using ILS-DI with Koha >= 3.18.6 
Requires ILS-DI Enabled in Koha " Get there: More > Administration > Global System Preferences > Web Services "

This is based on work from @a-sassmannshausen and @xmorave2

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks for sharing this. Looks like there are some style fixes that need to be made before this can pass Travis and get merged. If you need help taking care of that, please give me write access to this branch and I can do some of the work. If you want to work on it yourself, you might find this wiki page helpful: https://vufind.org/wiki/vufind2:recommended_tools#style

**Comment by misilot** [comment]
I can probably fix the style fixes.

**Comment by misilot** [comment]
@demiankatz are characters per line a hard requirment?

**Comment by demiankatz** [comment]
So far we've managed to keep all of our line lengths 85 characters or less. Anything longer will flag a problem. If there's no sensible way to keep something below that length, it is possible to use annotations to tell the style checker to ignore a block of code. Let me know if there are any problem areas that you'd like me to take a look at!

**Comment by misilot** [comment]
Thanks @demiankatz I think I got most of them. Letting Travis CI run.

**Comment by misilot** [comment]
@demiankatz got them :-)

**Comment by demiankatz** [comment]
Excellent, thank you! I've taken a closer look and have a few comments:

1. Some of the properties are camelCase and others are underscored; it might be nice to be more consistent and change debug_enabled/default_location to debugEnabled/defaultLocation.

2. You can eliminate some redundant code by using the LoggerAwareTrait and HttpServiceAwareTrait instead of implementing your own versions of the related interfaces. See, for example, https://github.com/vufind-org/vufind/blob/master/module/VuFind/src/VuFind/ILS/Driver/VoyagerRestful.php#L51 and https://github.com/vufind-org/vufind/blob/master/module/VuFind/src/VuFind/ILS/Driver/Symphony.php#L48

3. Is debug_enabled really necessary if you're using the shared logger? Would it be better to just get rid of that and rely on the global debug setting?

4. Should initDB() be protected rather than public?

5. Rather than building its own VuFind\Date\Converter, should this use the shared service like some of the other drivers? See, for example, https://github.com/vufind-org/vufind/blob/master/module/VuFind/src/VuFind/ILS/Driver/Factory.php#L97

6. Semi-related to the above: it makes sense to add a module.config.php setting for this driver, whether or not you end up requiring a custom factory to build it. See https://github.com/vufind-org/vufind/blob/master/module/VuFind/config/module.config.php#L375

7. There seem to be a lot of old-style array() declarations (instead of the preferred [] form). I'm not sure why php-cs-fixer is not picking up on these. Maybe it has to do with all the codingStandardsIgnore blocks. I can help reduce the number of those if you like!

8. Assuming we get all these minor nitpicks sorted out, are you ready for this to be merged, or do you want to leave it as a PR for a little while to collect comments?

**Comment by misilot** [comment]
@demiankatz I will take a look at your comments above. This was more of a continuation of the work already done by @a-sassmannshausen and @xmorave2. So it may take a few days to get eerything sorted out.

If you want to try and help reduce the number of th codingStandardsIgnore blocks that would be great. Just submit a PR against this branch https://github.com/misilot/vufind/tree/fit-koharest and I will merge them

**Comment by demiankatz** [comment]
Okay, here you go: https://github.com/misilot/vufind/pull/1

Let me know if i can help with any of the other issues.

Also, one more observation: there's a getHoldingOld() method in there. Is that actually needed, or is it some legacy thing kept for reference that we can now safely remove?

**Comment by misilot** [comment]
@demiankatz not sure. If it isn't being called I will delete it.

**Comment by demiankatz** [comment]
Sounds good. Also, I noticed that this branch is significantly behind master, and this was causing Travis builds to fail on my pull request... thus, I've updated my PR to merge the latest master and get everything up to date again.

**Comment by misilot** [comment]
I'm not really touching files that exist yet, so that's why this PR seems to build correctly. I noticed when I rebased (and when you did) that it adds so many changes. I merged your patch by hand and applied it and pushed it.

**Comment by demiankatz** [comment]
It should be safe to do the merge -- it will affect hundreds of files within this branch, but nothing should change as far as the relative difference between this branch and origin/master. In any case, it's no problem if you prefer to keep this where it is for now... but if you follow up on my suggestions about updating module.config.php, using traits, etc., you may need to update before doing that work to be sure you're using the latest correct versions of everything.

**Comment by misilot** [comment]
Yup. I actually made another branch on my repo for the module.config.php
https://github.com/misilot/vufind/commit/ced4c03d54486a8f006ab51d38dfa5bca0a35ebc
which I forgot about when I made the PR. I had already added it to get it
working in production.

**Comment by misilot** [comment]
@demiankatz Can you take a look at this https://github.com/misilot/vufind/pull/2 to see if it looks right for module.config.php?

**Comment by demiankatz** [comment]
@misilot, your module.config.php setup looks good, but it will require corresponding changes to KohaRest.php to add a __construct() function that receives the date converter and stores it in a property (in place of building a new one in the init() method).

Also, I see that you've made initDb private, but I'd recommend making it protected instead -- we try to avoid private methods in VuFind since protected methods make it easier to extend/override things. (Sorry to bring this up *after* you've gone to the trouble of renaming initDb to _initDb!)

**Comment by misilot** [comment]
Thanks, I changed it from private to protected as recommended.

**Comment by misilot** [comment]
@demiankatz I'm trying to implement https://github.com/vufind-org/vufind/blob/master/module/VuFind/src/VuFind/ILS/Driver/Symphony.php#L48 however I keep getting ```PHP Fatal error:  Trait 'VuFind\\Log\\LoggerAwareTrait' not found```

**Comment by demiankatz** [comment]
Yes, that's the problem. The traits weren't introduced until VuFind 2.4. If you aren't in a position to upgrade, we can certainly live without the traits for the moment... but we should factor them in before merging this to master.

**Comment by misilot** [comment]
I can work at upgrading VuFind on my test system next week.

**Comment by demiankatz** [comment]
@misilot, just checking in to see if you've had any time to continue work on this. Please let me know if I can be of any assistance!

**Comment by misilot** [comment]
Hi @demiankatz currently working on this, Currently trying to merge the changes from this branch with other changes I have made locally to expand functionality.

Needed to get at least our test site up with 2.5.2 so I could make sure it works with everything.

**Comment by demiankatz** [comment]
Excellent, thanks for the update. As always, let me know if I can do anything to help!

**Comment by misilot** [comment]
Lets see if Travis likes this. 

Mhmm guess it didn't like the merge of the upstream folder :-/

**Comment by demiankatz** [comment]
Looks like the Travis failure is just phpcs stuff -- indentation and line length issues. If you'd like help cleaning them up, I can open a PR against your branch.

**Comment by misilot** [comment]
Thanks @demiankatz I think I got it fixed. Now waiting again

**Comment by misilot** [comment]
@demiankatz Finally the green :)

**Comment by misilot** [comment]
This has been tested with 2.5.2

**Comment by demiankatz** [comment]
This is great, thank you! Two small things we should do before merging (but I'm happy to take care of these if they're a nuisance for you):

1.) In module.config.php, the driver is registered both as a factory and as an invokable. The invokable declaration appears to be in error and should be removed.

2.) It would be a good idea to extend the comments above the [Catalog] section of config.ini to account for this new driver and to briefly explain how it differs from the regular Koha driver.

I'm also going to send a message to the mailing list to encourage other Koha users to review this. Hopefully we can merge it soon! (Right now we're in a "no new features" code freeze until release 3.0 comes out, but I'm sure we can get this into 3.1 ... and with enough positive feedback in the next few days, I might be tempted to break the freeze for this case and let it into 3.0, since adding a whole new driver class won't break any existing functionality).

**Comment by EreMaijala** [comment]
One comment: the naming of the driver might become a problem because of the new REST API (see https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=13799) under development at the moment. I'd suggest KohaILSDI or something to differentiate.

**Comment by demiankatz** [comment]
Ahh, I didn't realize there were multiple APIs in play. That's a very good point!

Also, a quick browse through the code reveals that a couple of methods mention Polaris in the comments; presumably a copy-and-paste error. Can this be cleaned up?

(Definitely sounds like waiting for 3.1 is going to be the wisest course of action here, just to be sure we get all of the detailed ironed out properly).

Thanks!

**Comment by misilot** [comment]
@EreMaijala I will take a look at it. I was just working on code that existed before the Rest API was created. 

@demiankatz I will look for the polaris comments, and change those. Again this was a continuation of an existing driver for Koha using ILSDI

**Comment by EreMaijala** [comment]
I understand. I just wanted to mention that because we're going to work on a driver for the new REST APIs so that SQL connection wouldn't be needed, and introducing KohaREST2 or NewKohaREST would probably be a bit confusing. :)

**Comment by misilot** [comment]
@EreMaijala understandable :) I wish the ILSDI had more functionality so I wouldn't need as much MySQL but alas.

**Comment by demiankatz** [comment]
Also note that I recently spoke with @xmorave2, and he is also planning work with the new API. You might want to touch base to avoid duplicating effort.

**Comment by EreMaijala** [comment]
Thanks for the hint!

**Comment by misilot** [comment]
@demiankatz Did how renewals work change between 2.3.2 and 2.5.2? I just noticed that I don't get the option to renew on my test site running 2.5.2 but I do on our 2.3.2 site, which uses almost the same driver. Except for using a factory instead of being an invokable. Thanks!

**Comment by demiankatz** [comment]
I can't think of any intentional backward-breaking changes in the renewal behavior. Is there any chance there's a difference in config.ini settings between your two sites that's causing the feature to be disabled in one place? I believe it's off by default, so if you didn't turn it on in 2.5.2 that might explain the problem (though I realize I'm probably not so lucky as to have such an easy explanation). Let me know if you need me to come up with a better theory!

**Comment by misilot** [comment]
I have ```renewals_enabled = true``` on both. The test site was a test of the upgrade path as well so I had copied everything and merged it into git for tracking.

Is getMyTransactions() the only function that determines if an item is renewable?

**Comment by demiankatz** [comment]
Yes, I believe you are correct that getMyTransactions is responsible for making that decision.

It might be interesting to switch to the Demo driver temporarily to see if renewals work with the fake transactions generated by that driver. This will help narrow whether the problem is specific to the Koha driver or general to your VuFind system. If you find that it's not working with Demo or Koha, let me know and I'll do some testing against this branch over here (though I'd be pretty surprised if this was globally broken; I'm sure it hasn't been long since I've tried it).

**Comment by misilot** [comment]
I'm pretty sure it is [this](https://github.com/misilot/vufind/blob/fit-koharest/module/VuFind/src/VuFind/ILS/Driver/KohaRest.php#L1242)

Not sure  if the difference is between php5.6 and php 7.0 and not being able to access objects with ->{0} ?

As I am getting data back from the $service variable. 

Example response
```xml
<GetServices>
  <AvailableFor>loan renewal</AvailableFor>
</GetServices>
```

**Comment by misilot** [comment]
@EreMaijala @demiankatz I went and changed to be KohaILSDI to not conflict with the new API being created for Koha.

I think I got all the recommended changes.

**Comment by demiankatz** [comment]
Thanks for the work. This looks good to me. I'll leave this open for a couple of weeks to collect feedback, then merge to master sometime after the 3.0 release (barring unexpected problems). Hopefully we can add a true KohaRestful to the mix at some point in the future.

**Comment by misilot** [comment]
Thanks, Do you plan on have any more releases beyond 2.5.3?

**Comment by demiankatz** [comment]
I don't expect to issue any more significant 2.x releases, though bug fix / security releases are possible if there is a major need. 3.0 isn't actually that big of a step beyond 2.x, so I don't expect that upgrading from 2.5 to 3.0 is actually much different than going from 2.4 to 2.5. I just opted to increment the major version number because the upgrade to Solr 5 changes some aspects of the command line interface (along with some other backward-breaking changes roughly equivalent to things we have done in the past). I expect that in future the version number will increase more rapidly, not because we're actually changing more, but simply because I want to do a better job of semantic versioning.

**Comment by a-sassmannshausen** [comment]
Hi,

It's really nice to see the ILSDI connector having been picked up by you @misilot — I still feel sorry my priorities took me away from getting this properly finished!

The driver looks great, but I noticed I was still the single copyright holder for the driver file.  I would have thought you should definitely add yourself to the copyright lines considering all the effort your putting in!

All the best,

Alex

**Comment by demiankatz** [comment]
@misilot, Now that 3.0 has been released and there has been no negative feedback here, I think we can merge this to master. Would you like to add yourself to the "author" tags in the comments as Alex suggested before I proceed with the merge? Thanks!

**Comment by misilot** [comment]
It is listed [here](https://github.com/misilot/vufind/blob/fit-koharest/module/VuFind/src/VuFind/ILS/Driver/KohaILSDI.php#L44) which is enough for me.

**Comment by demiankatz** [comment]
Great, thanks! I usually try to keep the file-level and class-level author comments in sync (since generally the class is the only thing in the file anyway), but that's no big deal -- I'll take care of copy and paste and get this merged now.

**Comment by demiankatz** [comment]
Manually merged to master. I usually flatten commits, but in this case, it seemed worth keeping the history. I just added one more commit to adjust the header comments to be more in line with project standards (I also removed your revision date and version number, since it's probably best to rely on Git for tracking those types of details -- it's so easy to forget to update a comment). In any case, thanks again for all of the work on this!

**Pull request closed without merging**
