### PR TITLE
New New Lightbox

### PR DESCRIPTION
**Pull request by crhallberg**
This needs to be tested, but it's the simplest lightbox yet.

This lightbox simulates an iframe of sorts, allowing the Lightbox to use the backend logic as much as possible. Progression through the lightbox should be mostly identical to that of non-JS navigation.

Known Problems:

None!

### CODE REVIEW

**Comment by demiankatz** [comment]
Haven't tested this at all yet, but a few questions based on a quick code review:

1.) Why did you remove the ILS target selection from VuFind\Controller\AbstractBase? That looks accidental to me (at least, it shouldn't be lightbox related... unless the refactoring has somehow introduced a conflicting "target" post parameter somewhere, in which case that needs to be fixed).

2.) I saw a couple of console.log calls in there that you might want to get rid of (unless you still need them for ongoing development).

3.) I notice that you have some fairly large blocks of JS commented out but not deleted. Is this stuff that you still need to finish refactoring? If you're done with it, it's probably better to delete it so we don't get confused later. We can always look at the PR diffs to see what used to be there if we need to roll something back.

4.) What is the purpose of the template-dir/template-name hidden elements in lightbox.phtml? I don't see any other references to them in the diffs here (though perhaps they're needed by something outside the scope of your changes).

5.) I see a bunch of `<p class="lead">` template reformatting. Is that specific to this branch, or is that general cleanup that could be done in master to reduce the diff count here?

Thanks!

**Comment by crhallberg** [comment]
1.) I wonder if this was a merge error. It doesn't look like code I'm familiar with.

3.) This is the old code that I'm referencing but will delete once all the Lightbox cases have been covered.

4.) I'll clean that out

5.) I have another branch where I turn all the h2s into p.leads if you want to do that in master first. I was going for more consistency among the templates. Unless the reverse makes more sense?

**Comment by demiankatz** [comment]
Thanks for the cleanup.

Regarding template consistency, I agree that it likely makes sense to better standardize things, but I don't have a strong preference for one approach vs. the other. I think <h2> is a bit simpler and more semantically meaningful, but perhaps p.lead has advantages of its own. Are there established best practices in this area?

As far as testing goes, what should I be looking at when I test this? Is there anything known not to work yet that I should avoid? I don't want to report any problems you're already aware of....

**Comment by crhallberg** [comment]
I agree that `<h2>` is more semantic. I'll adjust the themes to use all headers where appropriate and prepare a merge into master (after vacation of course). I thing p.lead is good for a bold first paragraph (like an article) or to divide paragraphs into sections (a role normally taken by `<h3>`).

**Comment by crhallberg** [comment]
Diffs should go down once lead-to-h2 is merged.

Diffs will look more like this: https://github.com/crhallberg/vufind/compare/lead-to-h2...crhallberg:lightbox-iframe#diff-5ccd41aca0785d14e659875de3a63b4a

**Comment by demiankatz** [comment]
Thanks. I've merged lead-to-h2, so I'll give this another look after you merge that here.

**Comment by crhallberg** [comment]
Demian, if you could help test some of these things, I don't have a setup that allows me to test some of these.

**Comment by demiankatz** [comment]
Sure, I'll see what I can do!

**Comment by demiankatz** [comment]
Something weird seems to be going on in record/sms.phtml -- there seem to be two open <form> tags.

**Comment by demiankatz** [comment]
Summon issue: there used to be a special case that would refresh the page if you logged in on a Summon result screen. This is because Summon will sometimes display additional results for logged in users. I see that you have removed it, and indeed, the refresh no longer happens.

I don't think it's really a good idea to have this kind of special case in the Javascript, though -- it's a big maintenance headache. I'm actually thinking that it may be better to always do a full page refresh after login. There are a lot of different cases where logging in changes things dramatically and requires changes, and trying to keep up with all of these situations in the JS seems insane. The price of a page reload is probably worth the benefit of consistent, predictable behavior. What do you think?

**Comment by demiankatz** [comment]
Cosmetic question: is the lightbox close button supposed to be floating off to the right of the lightbox? I'm not sure whether or not I like this, but it's a definite look-and-feel change that I found a bit surprising.

**Comment by crhallberg** [comment]
That is intentional. I like it better, it also conveys that clicking anywhere outside the lightbox closes it.

**Comment by demiankatz** [comment]
I can see that. Probably worth getting more feedback on, though.

**Comment by crhallberg** [comment]
Doing a full refresh on login would be a very easy solution, is there any reason not to do this? The user would lose and changed inputs (checkboxes, radios, sliders) that do not trigger a search. That's all I can think of for now though.

I'm for a full refresh on login.

**Comment by demiankatz** [comment]
Strange behavior (with demo driver on and database authentication selected):

- search for an item
- click on the item
- click on "login for hold and recall information" in the top of the holdings tab
- you are now on the login screen (not in a lightbox) -- click on "create new account"
- the "create account" dialog now pops up unexpectedly in a lightbox
- fill in the form and submit it
- the lightbox closes, and the header suggests that you are logged in, but you are still on the login form
- click on any link leading to a different page
- you are no longer logged in

Very odd! It's normal that the login link on the hold message leads to a non-lightboxed page (we didn't go to the effort of making that edge case lead to a lightbox) but much of what happens after that is just weird.

Anyway, I think I've given you enough food for thought right now, so I'll call it quits on testing for today!

**Comment by demiankatz** [comment]
Regarding full refresh on login, I think the only other downside is that it's slower than not having to refresh the page... but I'm totally willing to live with that for the sake of predictable/consistent/correct behavior.

**Comment by crhallberg** [comment]
The new Javascript has broken a lot of this. Much repair to come.

**Comment by crhallberg** [comment]
BIG UPDATE:

1. We are passing all the tests. There are a few things I spotted while watching the tests run that I'm trying to replicate, but that is awesome. We have not yet passed the dreaded Demian Test.
2. The official new name of the new new lightbox is the **DelightBox**, in honor of the obsolete functions we enjoyed and will miss so much.

**Comment by crhallberg** [comment]
I was able to get Captcha working after discovering my sslcapath config went missing.

**Comment by demiankatz** [comment]
My problem is more subtle: CAPTCHA works if you pass the first time. However, once you fail, you can no longer succeed.

**Comment by crhallberg** [comment]
Just fixed the issue on my end, can you test CAPTCHA again?

**Comment by demiankatz** [comment]
Looking good now -- thanks!

**Comment by crhallberg** [comment]
Ready for more problems!

**Comment by crhallberg** [comment]
Included the 205 refresh logic.

**Comment by demiankatz** [comment]
Manually merged to master.

**Pull request closed without merging**
