### PR TITLE
Fix warning on the holdings pages in apache when debug is enabled or disabled

### PR DESCRIPTION
**Pull request by misilot**
Wrapped a Debug statement around a if(debug_enabled) statement

### CODE REVIEW

**Comment by demiankatz** [comment]
I think all of this debug code can be simplified. A little background information: the debug setting near the top of config.ini is a special convenience setting that adds a console logger to the settings in the [Logging] section of config.ini. Right now, this driver is looking at that setting, and completely disabling debug logging when it is switched off. This means that if somebody turned on any other type of debug logger (like a file-based one), the debug information would not be captured unless the console-based convenience setting was also turned on. That's obviously not desirable. I think it would be best to eliminate the debug_enabled setting/checks entirely, and just trust the configured logger to do the right thing.

Regarding the warning you are trying to avoid here, I think the solution is not to suppress the debugging but instead to do some type casting. I think the problem is that you are calling implode() on a potentially null value. You might be able to simply change `implode(",", $patron)` to `implode(",", (array)$patron)` to cast the variable to an appropriate format.

**Comment by misilot** [comment]
Ok Thanks. I will change the implode and work on trying to figure out the rest of the debugging features. As not sure what I would need to remove from the driver and the driver ini file.

**Comment by demiankatz** [comment]
I think you could simply remove the debug_enabled setting from the .ini file, and then remove the constructor code that reads the setting, and all of the "if ($this->debug_enabled)" checks wrapped around existing $this->debug() calls. If it's still unclear, or if you try that and find that things aren't working properly, please let me know.

Also, please let me know if you'd like to make those changes in this existing PR, or if you'd like me to get this one merged now and address that one separately. I'm fine either way.

**Comment by misilot** [comment]
I think a separate PR would make sense, since it is addressing a different issue. Thanks!

**Comment by demiankatz** [comment]
Agreed -- done. Thanks!

**Pull request merged**
