### PR TITLE
Improving sticky elements behavior

### PR DESCRIPTION
**Pull request by ThoWagen**
This PR allows to add other classes besides "hidden" to child elements in the sticky state. This can for example be used to change the size of logos.

It also removes a lot of unnecessary calculations when checking if the sticky state should be applied and fixes some smaller problems.

### CODE REVIEW

**Review by demiankatz — CHANGES_REQUESTED** [review]
Thanks, @ThoWagen. I haven't given this a deep review yet, but I see that this PR replaces the hiddenStickyElements configuration with stickyChildrenClasses. I don't imagine this is likely to impact many people (if any), but it would probably be a good idea to either add some backward-compatible logic that converts the old config to the new config (if we want to include this in release 10.1) or else target this to 11.0 and note a breaking change. Do you have a preference?

**Comment by ThoWagen** [comment]
Adding backward-compatibility was pretty straight forward. So I added it.

**Comment by demiankatz** [comment]
Thanks, @ThoWagen. I've asked @sturkel89 to do some hands-on testing of this, so we should hear from her later this week with results. I'll also review the code a little more closely as soon as I have a free moment.

**Comment by demiankatz** [comment]
@ThoWagen, when you have a chance, do you mind resolving the conflicts now that #3924 has been merged? Looks like it's just a matter of recompiling the CSS, so hopefully it won't be a big issue. :-) (I'd do it myself, but my VM is shut down for the day...)

**Comment by ThoWagen** [comment]
@demiankatz The conflicts are resolved :)

**Review by sturkel89 — COMMENTED** [review]
I tried the test branch by uncommenting the appropriate stickiness-related lines in theme.config.php for both bootstrap3 and bootstrap5. I found that the appropriate pieces were both sticky and/or hidden as expected.

I found that the same was true when I uncommented the parallel lines of code on dev. Demian reassured me that this was expected.

To confirm that the application of the test branch's new code to children classes beyond stickiness, at Demian's suggestion I changed the "class" in themes/bootstrap5/theme.config.php for search tabs to "alert-info" instead of "hidden." This did not change the color of the tabs in mobile in bootstrap5, but it did change their color in sandal5:

image

If we are comfortable that there's a reason why bootstrap5 itself didn't display the alert-info style in the tabs, even with the code change in /themes/bootstrap5/theme.config.php, then I think we have proven that the new code is working properly.

**Comment by ThoWagen** [comment]
@sturkel89 `alert-info` does not work in bootstrap 5. @demiankatz Is that an issue for the compatibility between bs 3 and bs 5? 

In any case I checked the behavior and the class is also added in bootstrap 5 even if if does not change any styles. You can test it with `alert-default` instead.

But I also found the problem that I deleted the "left" attribute in the `.sticky` style. This is fixed now.

**Comment by demiankatz** [comment]
@ThoWagen, it looks like the alert-info styles are set in the sandal5 theme, but not in the bootstrap5 theme. I think @EreMaijala might be the best person to ask about whether this is intentional and/or a problem. I should also put this in context by saying that I suggested that @sturkel89 should test with `alert-info` simply because it was the first class with visual side effects that popped into my head... so there are multiple reasons why that might not be a realistic example of a thing a person would really want to do.

**Review by demiankatz — APPROVED** [review]
Thanks, @ThoWagen!

**Pull request merged**
