### PR TITLE
Use Lists instead of Sets

### PR DESCRIPTION
**Pull request by lahmann**
Demian, I finally found some time to continue work on the improved author indexing: I have refactored the `author-modification.bsh` to use Lists instead of Sets for the author names and relators.
Local tests where positive.
I am currently working on a testset - should I add the .mrc files to the root of this pull request when I'm done?

Best,
André

### CODE REVIEW

**Comment by lahmann** [comment]
Oh, sorry - just recognized, that I merged the latest master to my pull request branch - the relevant changes are in f194cd2. Let me know if you prefer a pull request without the merged master.

**Comment by demiankatz** [comment]
No problem -- I've manually merged this over (along with the latest master merge). Looks fine. Regarding addition of the test MARC file, you can put it into the tests/data directory, and then it will be automatically loaded as part of the Phing startup task, which makes testing that much easier.

**Comment by lahmann** [comment]
Thanks Demian! By the way the SolrMarc documentation should probably be updated as it says (https://code.google.com/p/solrmarc/wiki/WritingCustomScripts)
>  that all scripted custom indexing methods must return either a String or a Set

SolrMarc obviously rather expects a **Linked**Set/List or a String as the return value of any custom script.

**Comment by demiankatz** [comment]
Good point -- I've updated the docs.

**Pull request closed without merging**
