### PR TITLE
Added support for multiple library cards.

### PR DESCRIPTION
**Pull request by EreMaijala**
Currently only bootstrap3, but I'll add templates to other themes when everything else is good.

@demiankatz: Do you think this would have a chance to fly?

### CODE REVIEW

**Comment by demiankatz** [comment]
I'll try to find some time to play with this in the near future... I imagine this will take a bit of work to get totally polished (not because I see any obvious problems, but just because experience suggests that everything non-trivial requires a few revisions), but I don't see why we can't move forward with it.

**Comment by EreMaijala** [comment]
Sounds good to me, and yeah, there'll probably be something I've overlooked. Perhaps a bit of description is in order:
The idea is that upon login with a library card, or in any case when the user has cat_username and cat_password/cat_pass_enc on login, it is verified that the user has at least those as a library card. Then the user can add other cards and change the name of the default card. Whenever there are more than one card, each screen where the catalog account is used gets a dropdown where the user can choose the active card. I've tried to make sure the system works with ILS and MultiILS, but I'm not sure if the method is the best ever. 

While working on this I noticed one thing that doesn't affect the functionality but is somewhat unexpected is that the user is always saved into the database also when validateCredentials() is called. While it's not causing a problem here, I think it might be worth it to see if it could be avoided.

**Comment by demiankatz** [comment]
Thanks for the clarification. Hopefully I can test this out with the Demo driver to get a feel for it (when time permits).

Regarding the unexpected behavior you describe, right now, authentication and saving the user account to the database are fairly closely bound together. I agree that this is not an ideal situation, but I don't think fixing it will be trivial. I think there are two obvious possibilities:

1.) Add a "do not save" parameter to the authenticate method. However, this will change the interface of the authentication plugins, requiring adjustments to all of the existing classes and possibly breaking locally-built extensions.

2.) Re-imagine the whole login workflow so that the auth plugins are truly only concerned with authentication, and move the database-specific logic into the manager. I think this might be a more appropriate abstraction, but it would be an even more disruptive change than option 1 and would require deeper analysis before implementation.

For the moment, it might be worth opening a JIRA ticket to keep track of this; it's definitely something that feels like it ought to be addressed, but since it's not causing any serious problems at the moment, it's not a top priority and might easily be forgotten.

**Comment by EreMaijala** [comment]
I added VUFIND-1093 about the validateCredentials() issue.

**Comment by demiankatz** [comment]
Thanks for opening the ticket. A quick thought based on another perusal of the code: do you think it might make sense to introduce a LibraryCardController rather than shoving all of this into the already-very-long MyResearchController? That might allow some more elegant paths, as well....

I'll try to actually run a test later in the week to offer more in-depth feedback, though we're watching another snow storm and might not be open tomorrow.

**Comment by EreMaijala** [comment]
I modeled the paths and functionality after the user's lists, but of course it could be moved to its own controller and paths. Not sure about changing the paths though, since it's pretty much tied to "MyResearch" functionality anyway.

**Comment by demiankatz** [comment]
I think it might make sense at some point in the future to split up the MyResearch controller into chunks and re-path a number of actions (keeping MyResearch with forward calls for backward compatibility, of course). Not a high priority, of course, but "MyResearch" doesn't really mean anything, and it sort of bugs me. I just thought that separating the library card stuff now will prevent us from having to move it around at some point in the future!

**Comment by demiankatz** [comment]
I just tried to test this and ran into a problem: if you don't have ILS authentication turned on (either as your primary authentication method or as part of a ChoiceAuth configuration), when you go to the library cards screen, you end up with:

Illegal authentication method: ILS 

because VuFind is configured to disallow non-configured authentication methods as a security precaution.

I haven't dug into the code yet to see exactly what you're trying to do or why... but if you need me to take a closer look and provide some suggestions, I'll be happy to do so; just let me know.

**Comment by EreMaijala** [comment]
Okay, I'll refactor the library card stuff to a separate controller. "MyResearch" has bugged me too.

Regarding the illegal authentication method, I need to rethink this. The presupposition was that you'd have ILS authentication enabled, and I failed to think of the case where it isn't. I suppose I have to bypass auth and use the ILS driver directly when working with library cards. I'll work on that too.

**Comment by demiankatz** [comment]
Thanks! Let me know when you're ready for me to do another round of testing and I'll give this another look.

**Comment by EreMaijala** [comment]
Okay, ready for the next round. I've now moved library card -related stuff into LibraryCardsController. There's one thing I'm not completely sure of: if saving edits for a library card fails, I want to keep the edited values (apart from password) in the fields. Now the logic is in the controller to keep the template clean, but if you'd prefer having it in the template, that can be changed.

**Comment by demiankatz** [comment]
Thanks!

Keeping edited values in the form using the controller seems perfectly reasonable to me (unless I'm misunderstanding what you mean).

One thing to think about: I see that you've added a addLibraryCardRoute() method to the route generator modeled on addListRoute(). I'm actually fairly unhappy with addListRoute(), feeling that it is of rather limited utility. I think adding a clone of it makes matters even worse. Perhaps what we really need to do is further generalize this -- what if we parameterized the controller, so you could define all of the routes like this?

<pre>
$routes = [
    'MyResearch' => ['userList' => 'MyList', 'editList' => 'EditList'],
    'LibraryCards' => [ 'editLibraryCard' => 'editCard'],
];
</pre>

I think that's a lot more useful and flexible; it even opens the door to adding another code generator function to add a named, ID-driven route to a controller.

The challenge is that I'm not sure what you'd actually call this thing... addIdDrivenRoute()? addLookupRoute?

Any thoughts on that? Might be nice to finalize the shape of the route generator before we release it later this month, even though this PR won't be completed before that.

(I'll comment further later on if I manage to find time to actually run the code before I hear back from you on this narrow issue).

**Comment by demiankatz** [comment]
I did a quick test and ran into another problem:

1.) Clean install using database authentication and Demo ILS driver.
2.) Create new user account
3.) Go to "Library Cards" in my account area

VuFind throws an exception....

Message: Not a valid column in this row: card_name 

Any idea what's wrong here?

**Comment by EreMaijala** [comment]
Sorry about that, I had wrong column name in new card init and failed to test the code from the beginning. Does it work properly now?

**Comment by demiankatz** [comment]
It's working better now. A few observations from playing with the code:

1.) If I establish a card by logging into an ILS function and using the normal catalog login form, it has no name. Would it make sense to apply some sort of default name to auto-generated cards? Either a flat string like "Default Library Card" or perhaps a copy of the username?

2.) If I go to edit a card, the password field is not populated. This is annoying if I want to change a name, since I have to retype the password. I think we should either populate the password field in the form or else allow the user to submit a blank password field that causes the existing database value to be retained. (Though this could get tricky -- in some ILSes, a blank password may actually be appropriate, and being unable to change a value from something to nothing could be problematic).

3.) If I delete all of my cards but still have credentials in the cat_* field of the user table, would it make sense for my first new library card to be pre-populated with these values? Or should we null out those fields when the card is deleted for consistency?

**Comment by EreMaijala** [comment]
1.) That's a good idea, I like the idea of just copying the username. Otherwise an empty name could be changed to default in the UI (I don't like storing default names in the database since that makes a multilingual UI a nightmare, see My Favorites...), but then you could have a case with multiple default cards.

2.) I ended up with requiring the password mainly because it might feel safer that the system doesn't offer your password for display and changing the name of the card won't happen so often that it would really get annoying. But I can change it if you feel another approach would be more appropriate. 

3.) Perhaps nulling out the values in user table would be the proper way to do it.

Regarding the routing I just modeled it after the prevalent style but could use this opportunity to improve it. Perhaps there could be a simple addDynamicRoute(s) (as a counterpart to addStaticRoutes) that would handle properly the [:id] parameter too, like:

    $routes = [
        'MyResearch' => ['userList' => 'MyList/[:id]', 'editList' => 'EditList/[:id]'],
        'LibraryCards' => ['editLibraryCard' => 'editCard/[:id]'],
    ];

I'll try to implement that for you to evaluate. What I especially like about this approach is that it would reveal the real route in module.config.php.

**Comment by demiankatz** [comment]
1.) Works for me.

2.) You could put the password in the form without revealing it if you used a password input box... then the user could rename the card without having to re-enter the password, but there would be no plain-text-visible password there. Since (if memory serves) you validate the password against the ILS, there's no need for a confirmation box even though the text is invisible.

3.) I like this idea too.

Thanks! Let me know when you've had a chance to do more work and I'll give this another look. If you'd like to submit the addDynamicRoute piece as a separate PR, feel free.

**Comment by EreMaijala** [comment]
Sorry, I didn't have time to make the dynamic route piece separate, so here goes. The latest changes should address all the remaining issues.

**Comment by demiankatz** [comment]
Thanks; I'll try to look at this later today.

Do I have push access to this branch? If so, and assuming the dynamic route piece is ready to go, I can manually refactor that to master and merge it back into here.

**Comment by EreMaijala** [comment]
Yes, you should have push access.

**Comment by demiankatz** [comment]
Thanks. Routing stuff looks great and has been merged to master. I'll look into the rest either later today or tomorrow.

**Comment by demiankatz** [comment]
Okay, I've played with this a bit more, and the UI now makes a lot more sense to me. (I've also added some fake user management capabilities to the Demo driver so that this sort of thing is easier to test).

I think we should be good to go on a merge shortly after the 2.4 release. Just one question in the meantime: I notice that in some places you are using `$catalog->checkCapability('getLoginDrivers')` and in at least one place (one of the templates) you are explicitly checking if the MultiILS driver is active. Are these checks trying to determine the same thing? Can you get away with using the checkCapability call everywhere for greater consistency?

On a semi-related note, I haven't attempted to test with the MultiILS driver since I'm not sure how complex that is to configure. Do you think it would be feasible for me to set this up as a wrapper around the demo and sample drivers for a realistic test, or should I not waste my time trying?

**Comment by EreMaijala** [comment]
The MultiILS check was supposed to have been replaced with the getLoginDrivers check, but I somehow missed it. Now fixed. I also fixed saving the library card for a new user.

It should be quite straightforward to set up MultiILS with two Demo drivers. Here's what you need, unless I forgot something:

config.ini:

    [Authentication]
    method = MultiILS
    
    [Catalog]
    driver = MultiBackend

MultiBackend.ini:

    [Drivers]
    test1 = Demo
    test2 = Demo

    [Login]
    default_driver = test1
    drivers[] = test1
    drivers[] = test2

Then copy Demo.ini to test1.ini and test2.ini.

Actually, now you don't need to have MultiILS as the authentication method as it should be enough to have MultiBackend as the catalog driver. This allows you to e.g. force Shibboleth for VuFind login and still support multiple library cards.

The only thing I'm not really a fan of now is that the library card default name of course contains the driver prefix when using MultiBackend, but I don't want to add more logic to the User object either. Well, at least it's explicit, and how it's displayed can of course be customized locally.

**Comment by demiankatz** [comment]
Thanks for the suggested configuration -- works beautifully, and allowed me to finally try out MultiILS.

Thanks also for the fixes. This looks great to me.

The only outstanding item is updating the blueprint and jquerymobile themes to match. If you want to work on that, it will allow me to merge this shortly after the 2.4 release is done. If you don't have time, we can wait a while and see if we end up deprecating either or both. (I think it's possible that blueprint will go away relatively soon, but jquerymobile will probably be around for a while, since we are still using it here at Villanova).

**Comment by EreMaijala** [comment]
Now that everything else is good, I can add the templates for blueprint and jquerymobile.

**Comment by demiankatz** [comment]
Fantastic, thanks! No rush, but whenever you're done, let me know and I'll give them a test run.

**Comment by EreMaijala** [comment]
Okay, done! I kinda suck with jQuery mobile, so please take extra care with it..

**Comment by demiankatz** [comment]
That was fast! I'll let you know what I find when I next have a chance to play with this.

**Comment by demiankatz** [comment]
I found and fixed one small problem in jquerymobile -- the form needed "data-ajax=false" on it to submit properly (otherwise jquerymobile does that weird AJAX submission thing that tends to yield bad results). I'm also going to look into making the myresearch bottom buttons less crowded in jquerymobile, since having 5 across doesn't work well on small screens.

I did find one problematic edge case in the MultiILS authentication environment:

1.) Log in.
2.) Delete your library card.
3.) Go to Profile

You now get prompted to provide a catalog login, but the myresearch/cataloglogin.phtml template is not designed to be multi-ILS aware since prior to this feature, there was no easy way to get to it, since the cat_* fields were always populated at login time. Actually, there's an existing (very narrow) edge case where this could happen in an existing VuFind instance: if  a user's password changes or is invalidated in the ILS while they are already logged into VuFind, they would get prompted to enter a new one. Obviously adding library cards makes this problem a lot easier to reproduce.

Anyway, the form works if you manually prepend the appropriate ILS prefix... but it would certainly be better if that weren't necessary! Do you have time to look into that one?

Thanks!

**Comment by demiankatz** [comment]
Okay, just pushed up a fix for the crowded jquerymobile buttons, so that just leaves the cataloglogin.phtml issue to be resolved before I think we're ready to merge this.

**Comment by EreMaijala** [comment]
Thanks for the jqm fix. And thanks for pointing out the flaw in catalog login. That was something I forgot to port from VuFind 1. Should be fixed now.

**Comment by demiankatz** [comment]
Thanks, Ere!

One other tangentially related issue... while testing this yesterday, I noticed that the default MultiBackend.ini sets the login delimiter to a tab rather than a dot. This does not seem to play well with the MultiILS functionality. Does MultiILS need to be more flexible, or is this a bad default that should be commented out rather than active?

**Comment by EreMaijala** [comment]
In my opinion that's a bad default in MultiBackend.ini, and I'm not quite sure it should exist at all... I believe it might ave been implemented to handle a case where there actual barcode has a prefix that allows the system to decide correct backend, but that doesn't play well with anything else in MultiBackend driver..

**Comment by EreMaijala** [comment]
I opened PR #325 for MultiBackend driver cleanup.

**Comment by demiankatz** [comment]
Okay, now that 2.4 is released, I've merged this to master (manually, to simplify the revision history).

**Pull request closed without merging**
