### PR TITLE
fix: search controls no longer wrap for an improved mobile experience.

### PR DESCRIPTION
**Pull request by crhallberg**
Fixes [VUFIND-1679](https://openlibraryfoundation.atlassian.net/browse/VUFIND-1679).

image

### CODE REVIEW

**Review by demiankatz — COMMENTED** [review]
Thanks, @crhallberg! This looks reasonable to me from a code review perspective, but I'll wait for @sturkel89's approval before merging.

**Review by sturkel89 — APPROVED** [review]
I see that "Results per page" no longer wraps at narrow widths and in my mobile emulator! 

This is true in all five themes and in every language I tested. 

Here's one example:

image

I think this PR is ready to merge. 

---------------
There's one remaining issue in the JIRA ticket, though: the "Results per page" and "Sort" labels and boxes look great in relation to one another in full screen in English, but when the interface language is changed they are resized independently and sometimes look pretty wonky:

image

image

image

image

When time allows, can we create a new PR that addresses this issue?

**Comment by demiankatz** [comment]
Thanks, @sturkel89, I'll merge this as incremental progress but leave the JIRA ticket open until we have time to discuss the second piece of the puzzle.

**Comment by sturkel89** [comment]
The other issue has been fixed too! https://github.com/vufind-org/vufind/pull/4041

**Pull request merged**
