### PR TITLE
Dismax munge

### PR DESCRIPTION
**Pull request by hajoseng**
A small extension in order to use CustomMunge as well for Dismax queries. Different to Lucene queries Dismax custom munging applies to all query fields (due to the specific Dismax query syntax).

### CODE REVIEW

**Comment by hajoseng** [comment]
Travis CI tells me that only variables should be passed by reference and points to line 149 of \VuFindSearch\Backend\Solr\QueryBuilder. For me it doesn't make sense; can anybody help?

**Comment by hajoseng** [comment]
Thank you very much, Damian. In fact my first attempt followed your remarks 2 and 4 but, I decided to make it somehow "minimum invasive". I will follow your ideas and come up with further work on monday since I've some other work to do until then.

**Comment by demiankatz** [comment]
Sounds good, thanks!

**Comment by hajoseng** [comment]
I've done some further work but I'm stuck with git; our repository is out of sync and needs repair. I'll come back with this request later.

**Comment by hajoseng** [comment]
Unfortunately I was not able to continue this pull request; it went out of sync with our "home"-repository. It's continued as pull request # 1419.

**Pull request closed without merging**
