### PR TITLE
Enable text-domains for translations

### PR DESCRIPTION
**Pull request by nicokarrer**
Enables translation / label definition over text-domains. 

*Benefits:*

* Could help to tidy-up the current language files by using contexts.
* Allows multiple use of label-keys depending on the context:
 * names.ini;  libraryA = "Name of library A"
 * links.ini; libraryA = "Link to library A"

*How to:*

* A Subfolder in the languages folder defines  a text-domain.

 ```
  languages/date/en.ini
 ```
* Definition of text-domains in config.ini:

 ```
 [TextDomains]
 textDomains[] = date
 ```
* Use with transEsc view-helper:

 ```php
 $this->transExc('date::day_placeholder')
 ```

*Comments*
* Current label handling stays the same.
* Alternatives to the '::'-notation would have been:
 * Fourth paramter in transEsc view-helper. But that would be a bit unhandy.
 * Separate view-helper or direct use of the zendTranslator view-helper (would exclude escaping).

### CODE REVIEW

**Comment by demiankatz** [comment]
Hello. I have now finished translation-related refactoring of the master branch. Can you merge master into this PR and resolve the conflicts so that I can take another look at it? Thanks!

**Comment by demiankatz** [comment]
Note that some of the logic you currently have in \VuFInd\View\Helper\Root\Translate will have to move to \VuFind\I18n\Translator\TranslatorAwareTrait. This will allow consistent behavior throughout VuFind -- it will affect not just translation in views but also controller-side translation.

**Comment by guenterh** [comment]
Hi Demian,
thanks for info.
I'm going to take care on it as soon as possible. At first I have to merge and deploy our development branch with your latest master (and see what happens)
Günter

**Comment by guenterh** [comment]
Hi Demian,
I merged the latest VF2 master code into this pull request. In general it is now compatible with your current implementation.
Two files stopped the automatic merging process:
Auto-merging module/VuFind/src/VuFind/View/Helper/Root/Translate.php
CONFLICT (content): Merge conflict in module/VuFind/src/VuFind/View/Helper/Root/Translate.php

Auto-merging module/VuFind/src/VuFind/I18n/Translator/Loader/ExtendedIni.php
CONFLICT (content): Merge conflict in module/VuFind/src/VuFind/I18n/Translator/Loader/ExtendedIni.php
Haven't looked up why.
I have just used the latest implementation I could take from vufind-org/master to fix the conflict

I will take a look into what I have done to finish this task for our purposes. Did this last December - and I already have forgotten the details.... But today at first I have to read a paper for a workshop which takes place tomorrow the whole day. So I guess no answer until Wednesday  (perhaps in the evening hours) - sorry for it. But in the evening hours I'm already playing around with the ZF2 apigility framework for our linked-data project. Perhaps of interest for VuFind too.

I'll let you know.  

Günter

**Comment by demiankatz** [comment]
It looks like you'll need to add back in the logic to actually parse the text domains from the translation strings, which used to be in Translate.php but which will now have to move into TranslatorAwareTrait. I'm not sure what the conflict in ExtendedIni might have been, but that's definitely worth investigating.

I haven't had a chance to explore apigility yet, but if you have thoughts on how it might be of benefit to VuFind, I'm definitely interested in hearing them, and that might help motivate me to make time to take a closer look at it.

In any case, enjoy your workshop, and we can continue this discussion later in the week!

**Comment by guenterh** [comment]
Hi Demian,

I took a look into the case this morning.
Before I like to finish this PullRequest I suggest you finished the current refactoring caused by the new trait mechanisms related to Translation and other things. I have in mind you spoke about logging etc.

Why:
I realized things changed (not only related to traits) which influence significantly our components.  E.g. since January you instantiate another Translator type 
https://github.com/vufind-org/vufind/blob/master/module/VuFind/src/VuFind/Service/Factory.php#L730
whereas our module is still using a former type
https://github.com/swissbib/vufind/blob/master/module/Swissbib/src/Swissbib/Services/Factory.php#L112
And because of Type-Hints in some further signatures the code crashes. Don't ask me why there are types and no interfaces as hints. Unfortunately I have overseen this change last month.

Therefor my main goal is to make our current implementation stable before we start the next task.
And this multi-domain pull request has further extensions how to use it e.g. in the Result type and some view-scripts (if I remember correctly). 

Do you have at the moment an idea about the delivery date of the next version 2.4? For us it would be really helpful to have a more stable version because we want to deploy a first Responsive Design Beta version at the end of this month. Depending on your answer I could imagine to postpone the termination of this pull-request to a time behind the next version to make it ready for the VF2-core implementation.  

Günter

**Comment by demiankatz** [comment]
All Trait-related refactoring should be completed at this point. I don't expect further major changes in this area.

Regarding the Translator change, this relates to Zend Framework 2 -- in version 2.2.x, there was no interface for translators, so class name had to be hard-coded in type hints. Version 2.3.x has added an interface and changed some requirements. This is probably the most disruptive side effect of the 2.2 to 2.3 upgrade.

We are going to begin discussing goals and possible target dates for the 2.4 release on our next developers call next Tuesday (http://vufind.org/wiki/developers_call). I personally feel that we are nearing a point where a new release would make sense, now that the major Zend Framework upgrade has been completed and PHP 5.4 support is in place. I'll know more after that conversation, however. If you are able to attend the call, your input would be welcome!

**Comment by demiankatz** [comment]
For future reference, you might want to take a look at this commit: https://github.com/vufind-org/vufind/commit/8976d3537ffb5a9fe0826f54248e84dd355a2caa. Following the ZF2.3 upgrade, it's possible that the translator factory will return a dummy object that's missing a bunch of methods. It may be necessary to account for this in your work. (Or maybe not... but it seemed worth mentioning).

**Comment by demiankatz** [comment]
Günter,

Just checking in again since 2.4 went out this week. Hopefully that gives you a more stable platform to work from. As always, please let me know if I can be of any assistance!

**Comment by demiankatz** [comment]
Günter,

I see that you've deleted the branch on which this PR was based, and looking at the current set of diffs, it appears that some of the original implementation is gone. What are your plans regarding this feature? I'd love to get this PR wrapped up, but it seems that we may need to do some work to reimplement some of it. I'm happy to do that work if you haven't already, but I thought I should check in to see your status before I try anything on my own.

thanks,
Demian

**Comment by guenterh** [comment]
Hi Demian

oops - this wasn't the intended idea...
In German there is the saying: "Zuviele Köche verderben den Brei"
trying to translate it in English "Too many cooks spoil the mash" - I don't know if this possible to say. But perhaps I was the cook and I have lost the overview, which might be really a possibility... I don't know...

The idea is - we would be happy seeing multi-domain-translations as part of the core.

My thoughts at the moment:
The code implementation (beside some configurations) of the pull request was focused on a few initializations in the Bootstrapper and enhancements in the ExtendedIni loader
of the l18n package
https://github.com/swissbib/vufind/blob/master/module/Swissbib/src/Swissbib/VuFind/l18n/Translator/Loader/ExtendedIni.php#L120
But this is only part of the game. Just out of my memory e.g. code in the Result/Param objetcs had to be adapted to use the enhancements which wasn't (at least completely) part of the Pull Request so far.
And there has to be a (hopefully general) mechanism to decide which domain should be used mainly in the templates because language keys could be the same in different domains (for us 'one' reason to use multi domains, because we import automatically every night translations from remote systems)

Perhaps you can recognize: I was just able to bring this together for our own service but haven't had the time to make it convenient for a broader community focus.
 
My suggestion at the moment:
We should start from the scratch. I (the swissbib team) could collect most the pieces and ideas we have used so far for our own service and together make it appropriate for the core.

What's your point of view?

Günter

**Comment by guenterh** [comment]
Writing this text I have just seen I myself deleted the branch at the beginning of May.... (perhaps I was so happy we went live with our service...)

I just restored it (this makes it easier to collect the pieces) and my point of view is still the same

Günter

**Comment by demiankatz** [comment]
Ahh, yes, your German expression definitely has an English equivalent (usually using "pot" rather than "mash" but otherwise identical).

I seem to recall that originally, this pull request included not just the initialization/ini parsing logic but also some code to derive a textdomain from the translation string by looking for a :: separator. That seems to have vanished somehow (probably related to the introduction of the TranslatorAwareTrait which centralizes most of VuFind's translation logic, and hopefully makes uniform implementation of this new feature significantly easier).

My point of view is fairly flexible, because I don't have a personal investment in this functionality (beyond recognizing its value to others). From a functional/maintainability perspective, these are the things I'd like to see which probably aren't here yet:

1.) Auto-loading of textdomain .ini files in subdirectories, without the need for a configuration setting (to simplify the process) -- this was discussed in some of the earlier comments.

2.) The ability to fail over to the default textdomain if no value is found in a different specific textdomain (perhaps this desire is misguided, but I just have a feeling that this capability might be helpful while we transition toward using textdomains more heavily).

3.) Some mechanism for specifying textdomains for use in facet translation, since I think this is one of the most obvious use cases for this feature that the average VuFind user might be interested in. This could, for example, allow us to move all of the current format terms out of the main language file and into a format textdomain. I think we probably want to avoid a 1:1 relationship between facet field names and textdomain names, since in some cases a textdomain may be shared across multiple search backends that use different fields to present the same or similar sets of values (i.e. Solr vs. Summon). See also #238.

4.) Updates to various development tools (such as the devtools module's language report, some of the command line tools for normalizing/modifying language files, and the unit test that checks language file integrity) to account for textdomains.

Obviously I'm not saying that you need to do all of these things -- but that's what I see as a to-do list for being ready to be merged into master.

In any case, if you're able to collect together the parts of your own implementation that can be shared, that sounds like a good first step. Then I can extend it from there to fill in whatever capabilities are missing. It might be a good idea at this point to close this PR and open a fresh one, but I'll leave it to your discretion whether it's easier to do that or simply update the existing branch here.

Either way, thanks for getting back to me on this. I'll be away until July 13th but look forward to continuing this conversation when I return.

**Comment by lahmann** [comment]
Günter, we (at Leipzig University Library) are very interested in more extended language support for VuFind2 as well and would be happy to contribute to this issue. So, if you could collect the code pieces and concepts from your current swissbib implementation and post it as a pull request, this would be a great starting point.
From there we could start working together on this issue, splitting the todo-list Demian posted, etc. (e.g. as briefly discussed in #330 I could do some work on the dev-tools).
What do you think?

**Comment by demiankatz** [comment]
Sounds great to me -- thanks for your willingness to help!

**Comment by guenterh** [comment]
Hi Andre, Demian - Thanks for your support. Until the end of this week I'm going to collect the ideas and pieces already used for our current implementation and put them together as an additional part for our starting point. I will take a look into https://github.com/vufind-org/vufind/pull/330 which I haven't seen by now. 

Günter

**Comment by guenterh** [comment]
For me this pull request is a little bit like a nightmare or like a constantly moving target ...
Started one year ago, various persons (inside and outside of our project) were involved, code in VuFind core was re-factored (especially traits), our code tried to follow these changes but had to consider our specific requirements in time pressure. But I think it's important, not only for us, and perhaps we can finish it with joined forces! I would be happy if our implementation would be more in sync with the VF2 core.
	  
I started to read the comments on this pull requests again (reasons for Ere to agree on it and for Andre to make his CLI tool for language file synchronization as well as the comments Demian made on  the first implementation of Nicolas a year ago) Because I think our use case might be a little bit special (e.g. automatic creation of language files) I try to compile our reasons to use multi domain translations in more deepness.
  
# Reasons to use multi domain translations for the swissbib project

## automatic import of translation files from several external systems

For swissbib we import some of our resource files (provided in several languages) automatically from external systems (by now Aleph)
For example the tab40 aleph-files are fetched and distributed on several VuFind production hosts. These files have to be differentiated for every single network by prefix
-rw-rw-r-- 1 swissbib swissbib 38878 May  6 10:34 idsbb-de.ini
-rw-rw-r-- 1 swissbib swissbib 38846 Mar 26 17:26 idsbb-en.ini
-rw-rw-r-- 1 swissbib swissbib 38846 Mar 26 17:26 idsbb-fr.ini
-rw-rw-r-- 1 swissbib swissbib 38846 Mar 26 17:26 idsbb-it.ini
swissbib@ub-sbhp01:/usr/local/vufind/httpvfrd/local/languages/location$ 

Otherwise we can't fetch more than one network

Content of these files e.g.
a100_ls = "Lesesaal"
a100_mag = "Magazin"
a100_100fg = "Freihandmagazin, vor 1976 Magazin"

##  automatic import of translation files using the same key with different translation values
All our institutions (more than 900) from several networks are administrated in our so called libadmin system
(for test purposes look at https://admin.swissbib.ch/libadmintest/institution ) which provides APIs to fetch the content via web.

A key A100 (University Library Basle) is used for the label and at the same time for the URL to fetch library information on the web

A100 = "Uni Basel - UB Hauptbibliothek"
A100 = "http://www.ub.unibas.ch/bibliotheksnetz/verbund-basel/bibliotheken-im-verbund/liste-der-bibliotheken/a100/?S=1"
The key is part of different domains


##  Because Switzerland is a country with 4 official languages people appreciate correct and accurate translations. I assume it might be easier to edit files even it is done manually if the content is divided in categories (Ere made this point)


Organization of multi domain translations in swissbib
Because of the different contexts translations are used for we decided to organize them within a hierarchical file system
compare: https://github.com/swissbib/vufind/tree/development/local/languages
This requires to initialize the ZF2 translators with different paths.


As I said just at the beginning – the pull request is quite old which is the reason why the code base differs from our current implementation heavily. My suggestion: We should start just from the scratch and I'm going to describe the ideas, code snippets and configurations we are using. Perhaps we can take part of it.


# Initialization of translation types: 

Most parts of our initialization is done in the Bootstrapper. 
https://github.com/swissbib/vufind/blob/development/module/Swissbib/src/Swissbib/Bootstrapper.php#L223 and other initMethods

# Configuration of text domains

- https://github.com/swissbib/vufind/blob/development/local/config/vufind/config_base.ini#L260
This section depicts the local language directory I tried to explain above.
ZF2 translators need to know where to find the files related to their specific domain. This is solved by mapping the domain name to the sub directory name of local/languages. Related to the performance discussion above (Demian / Nicolas): each domain uses it's own cache namespace so I don't expect any performance issues.

- https://github.com/swissbib/vufind/blob/development/local/config/vufind/facets.ini#L56 
advanced settings for translated facets related to specific domains. We need to indicate if facets use a specific domain which is done by using the colon notation.

I can't exclude there are additional relevant configurations I have forgotten by now. I will mention it later in case I come across 


# Implementation

- I'm going to restrict myself to the main corner-pieces I'm able to recognize by now. Maybe it makes more sense to provide more information and thoughts in a later phase. 


## Reading the files:

We had to implement our own ExtendedIni Reader (as extension of the VF2 core type) 
https://github.com/swissbib/vufind/blob/development/module/Swissbib/src/Swissbib/VuFind/l18n/Translator/Loader/ExtendedIni.php#L80
The logic by now is a little bit complex – but I think it's a consequence of our design I tried to explain before  which differs from the current VuFind layout which is more straight forward and flat (no hierarchy)

## treatment of facets to be translated with multi domains
It turned out that this was difficult to be done because VuFind doesn't use this by now at all and changed the concepts (generally used traits not supporting this feature).

- A collection of relevant code pieces:
https://github.com/swissbib/vufind/blob/development/module/Swissbib/src/Swissbib/VuFind/Search/Solr/Results.php#L160
(extended method to collect the facets. It has to search for multi domain related facets and to provide this additional info to the translate implemenation.

https://github.com/swissbib/vufind/blob/development/module/Swissbib/src/Swissbib/VuFind/Search/Solr/Options.php#L44
I'm aware this is a hack because we have overwritten the general trait implementation. But the current trait doesn't support the necessary multi domain information so – this is how it is by now


I think just as a starting point this is already more than enough ...

Günter

**Comment by demiankatz** [comment]
Thanks for all of this detailed information. I think we should be able to end the nightmare soon and get this under control!

I think we're on the same page about these things:

1.) VuFind should be able to load files from subdirectories of the languages directory, and assign text domains to the files corresponding with the subdirectory names.

2.) We need a mechanism for optionally specifying a text domain when translating a string.

3.) We should be able to specify a text domain when translating facets.

For issue 1, I think it would be nice if we could simply grab all of the subdirectories of languages and load them automatically, without the need for an extra configuration setting. I think this should be fairly simple with a readdir() loop.

For issue 2, I believe that your original implementation used a delimited "domain::text" string, but it appears that somewhere along the line, you changed to a ["text", "domain"] array. Any idea why this changed? I can live with either approach (or the third alternative, adding a fourth parameter to translate()) but I'm curious if you know specifically why the change was made.

For issue 3, I like your solution of the colon separation in the config file, though I suspect we might be able to simplify the code for dealing with that configuration (though maybe it's already simple enough -- I didn't spend a lot of time looking at the code).

If we want to do this iteratively, then obviously we need to get parts 1 and 2 working first for the basic functionality, and part 3 is a great starting point for actually using the new functionality (and ties in with resolving #413 and related issues).

Let's talk out the loading/specifying issues described above, and once we're happy, one of us can start building a new PR (or overwrite the branch in this one) to get the ball rolling again.

**Comment by guenterh** [comment]
Hi Demian,

thanks for reply - as you said, I think we are on the same track.
If you don't mind, I would try to collect the pieces I described literally and create a new pull request as a starter with a fresh code base. Actually I don't have the overview which parts of the current code of the pull request might be already outdated and it's too time extensive to look through it.  I like the idea you described to collect all the subdirectories to simplify things.
I can do this hopefully on Monday or Tuesday. As said already often in the past: Unfortunately VuFind is only a part time job for me, other things are waiting.

Günter

**Comment by demiankatz** [comment]
Sounds good to me. I understand the time constraints -- I'm sure we can all wait a few days if we have to. Thanks for your help, and please let me know if I can do anything more to smooth the process along.

**Comment by demiankatz** [comment]
Superseded by #419.

**Pull request closed without merging**
