### PR TITLE
Account AJAX Improvement (v5.1)

### PR DESCRIPTION
**Pull request by crhallberg**
### Todo
- [x] Appearance
  - [x] Sandal icon contrast
  - [x] Menu hovers fixed
  - [x] Center icons and spinners in Bootstrap
- [x] Cache Updates
  - [x] on renew
  - [x] on hold place
  - [x] on hold cancel
  - [x] on library card switching
- [x] Compress LESS
- [x] Convert LESS to SASS

### For later (not yet completed, but out of scope for 5.1)
- Tooltip capitalization (language strings or JS capitalization)
- ILS function caching (v6.0)
- Server force refresh

Rebased off of v5.1 into a new branch. Didn't want to force push but I don't want to lose the conversations on PR #1343 either.

### CODE REVIEW

**Comment by demiankatz** [comment]
@EreMaijala, curious to hear your thoughts on this -- it seems to me that this covers the most critical issues you've found (though I haven't taken the time to exhaustively test it yet). I think something like this probably adequately meets our needs for a 5.1.1 release that fixes bugs.

Discussion points:

1.) Chris proposed a Javascript-based tooltip capitalization approach in #1343, but I wasn't crazy about that because I wasn't sure how well it would play with non-English languages. Do we need to create new language strings to meet this need, or should we just live with some cosmetically imperfect messages?

2.) ILS capability caching is probably a separate issue that impacts this but should be dealt with independently. Is it worth creating a JIRA ticket for now to track the need, or does somebody want to take a first stab at an implementation in the short term?

**Comment by EreMaijala** [comment]
2.) I'll volunteer to take a stab soon.

**Comment by demiankatz** [comment]
A few points (I won't number them since I'm splitting your 1 into a couple of different topics):

- I agree that the Javascript-only approach is quite fragile, though a server-side approach may end up being quite complex. I'll discuss with @crhallberg and dig through the code to see where the most sensible place for handling this might be. I suspect that a solution would require either a) the injection of a new service into a lot of different places or b) the introduction of a new account-related event system. I think option a would be easier to implement as a quick and dirty approach, but would make the code significantly uglier... and option b would be a cleaner solution, but also increase complexity in a different way, because these event systems are not the easiest things to comprehend.

- Regarding the language strings, maybe the best solution is to use the command line language copy string tool to duplicate the existing strings into a new set of ajax_tooltip_x strings... this way we can maintain the existing functionality without having to re-request new strings from all the translators, but we can also tweak the strings slightly in languages where we know it would be appropriate to do so.

- Thanks for the willingness to help with the caching behavior; I'll look forward to a separate PR when time permits!

**Comment by demiankatz** [comment]
@crhallberg, thanks for the progress on this. I hope to merge it soon. Two questions:

1.) Does the "compress LESS" task still need to be done? I can take care of the lessToSass as the final step before merging.
2.) Did you check whether there's a cancel ILL request action that needs to be accounted for, equivalent to cancel storage retrieval request?

Thanks!

**Comment by crhallberg** [comment]
I added ILL request cancelling (don't know how I missed it) and I took care of the LESS and SASS steps.

**Comment by demiankatz** [comment]
Thanks, @crhallberg, I'm merging this now. I have opened a couple of JIRA tickets so we don't lose track of the unresolved issues discussed here:

  - https://vufind.org/jira/browse/VUFIND-1333
  - https://vufind.org/jira/browse/VUFIND-1334

**Pull request merged**
