### PR TITLE
 	geändert:               module/VuFind/src/VuFind/ILS/LBS4.php

### PR DESCRIPTION
**Pull request by Cloud8**
This PR alters the LBS4 driver to make use of the improved DAIA driver to retrieve holding information,
and to only use database query to get patron information.

 	geändert:               module/VuFind/src/VuFind/ILS/Driver/LBS4.php

### CODE REVIEW

**Comment by demiankatz** [comment]
Does this require the addition of a [DAIA] section (and/or other details) to LBS.ini for the relevant settings? Is DAIA an automatic part of LBS4, or is there a possibility that some users will not be able to take advantage of the driver if we switch to making it a DAIA subclass?

(I'm not sure how large the LBS4 installed base is, so I'm not sure how critical these things are -- but I want to make sure we don't break VuFind for anyone, and that new users have clear instructions on how to configure things).

Thanks!

**Comment by Cloud8** [comment]
Yes, this requires a [DAIA] section for LBS4.ini - I attach one (as txt, since git does not allow to upload ini files).
[LBS4.txt](https://github.com/vufind-org/vufind/files/241842/LBS4.txt)

DAIA is not an automatic part of LBS4, but has good support from several consortia. 

The drawback of the old LBS4 driver was, that the settings from the database tables do vary among
installations and the usage of the copy_cache table was not the most ingenious idea.
As far as I know, there is no active usage of the LBS4 driver apart of some experimenting.

**Comment by demiankatz** [comment]
Thanks for sharing the .ini file. Is there any reason you preferred to attach it as text instead of simply committing the changes to the branch used for the pull request? If you're able to do that, I think it would make it easier to see (and it makes sense to commit these things to the default .ini file for future reference).

Thanks also for the update on usage of the LBS4 driver. I'll send out a note to vufind-tech asking people to review this, just in case anyone currently has LBS4 in use and we're not aware of it. If I don't get any negative feedback from that, I'll go ahead and merge this.

**Comment by Cloud8** [comment]
Just commited LBS4.ini as you suggested, hope it has reached the PR.
Thanks for review !

**Comment by demiankatz** [comment]
Thanks; looks good. I'll give this a few more days in case of response to the vufind-tech email, then I'll go ahead and merge if no one objects.

**Comment by olli-gold** [comment]
We are LBS4 users, but we do not use the LBS4 driver (instead we are looking forward to use PAIA, which is also available as an extension for LBS4; right now we are just setting links to our LBS4 OPAC for user account actions). The LBS4 driver is somehow related to the old PICA driver, which has been removed from VuFind some time ago - and the PICA and DAIA driver were also related to each other.
As LBS4 and DAIA are not conflictive, I guess its a good idea to use DAIA instead of native LBS4 methods.
Though, no objections from me on this PR. But this is only my opinion, since, as I mentioned, we are not affected directly by it.

**Comment by demiankatz** [comment]
It sounds like we may be able to phase this driver out entirely once the PAIA driver is completed. In the meantime, unless somebody else objects soon, I'll go ahead and merge this. People can always go back and retrieve the pre-DAIA version of the driver if there is a need in the future. Thanks for the input!

**Comment by olli-gold** [comment]
I guess it will take some more time to phase this driver out, because I don't think that all LBS4 users will use PAIA. PAIA is just an interface and its not bundled with LBS4, although there is an implementation of a PAIA server for LBS4 (which costs some extra money). So some users might still need the LBS4 driver in the future.

**Comment by demiankatz** [comment]
Is the DAIA component free?

**Comment by olli-gold** [comment]
DAIA is also a seperate component not bundled with LBS(4) - LBS4 has its own availability interface. We have our own DAIA server on top of the LBS4 availability interface, the Library Service Center of our Library network is maintaining a DAIA service for a couple of other libraries. Other Library Service Centers in Germany are maintaining other DAIA servers for their members - its pretty heterogeneous, though.

The DAIA service from the Library Service Center of the Common Library Network _was_ free for members of the Common Library Network, but I guess now they bundle it with PAIA (this would mean that it's not free anymore) - I'm not sure if one could get the DAIA service separately without PAIA and if _this_ would be still free for members.

**Comment by demiankatz** [comment]
Thanks for the information. It sounds like requiring DAIA may introduce some of the same challenges as a PAIA dependency. However, there is no point in maintaining code that no one is going to use, so for now I will go ahead and move forward with this change (unless an LBS4 user with no DAIA support raises their hand soon). We can always resurrect the stand-alone driver if we need to.

**Comment by Cloud8** [comment]
I dont't think there are LBS4 users out there without DAIA support, but if so, there are some free implementations available (e.g. Plack-App-DAIA).

**Comment by Hirnfiedler** [comment]
@olli-gold wrote: 
> but I guess now they bundle it with PAIA 

 **DAIA** is a open vendor independent API to determine the availability of items to an given local callno. This has no individual dependencies to a single user.   
**PAIA** is a open vendor independent API to the patron functions of ILS. This has no general dependencies to the availability information.

Probably, Olli's 'Library Service Center' will offer both as a license bundle. But  I doubt, that they are going to merge both in to a new proprietary interface.

In our confederation we are offering a own DAIA Service to our LBS3/4 members for free. (The source of the wrapper is not (jet) explicit free, but can be seen on http://trac.hebis.de/svn/daia/DAIA/) A service for PAIA is planed.

Most of the PICA local systems in Germany are member of one of both federations. So i agree with @Cloud8, that nearly all German LBS3/LBS4 libraries may use for free or at least for cheap both APIs.

Not now but In the long plan, I’d like to suggest the evolution from the PICA-Driver to an pure vendor independent DAIA/PAIA-Driver.

**Comment by olli-gold** [comment]
> Probably, Olli's 'Library Service Center' will offer both as a license bundle. But I doubt, that they are going to merge both in to a new proprietary interface.

Sorry for being unclear, I really not wanted to say that they are creating a new interface, but they are offering both interface implementations as a kind of license bundle.

> Not now but In the long plan, I’d like to suggest the evolution from the PICA-Driver to an pure vendor independent DAIA/PAIA-Driver.

That's already in progress. As you probably know, the DAIA driver is actually part of VuFind for a while now. The PAIA driver is currently under development here: https://github.com/lahmann/vufind/tree/paia-driver2. The PICA driver has been removed some time ago; as far as I know it has never been used in VuFind2. I guess some libraries are are using the LBS4 driver, although I don't know, which libraries that are.

**Comment by demiankatz** [comment]
I've gone ahead and merged this to master, creating a legacy branch for easy access to the old pre-DAIA LBS4 driver here:

https://github.com/vufind-org/vufind/tree/legacy/lbs4

I also noticed that this PR was missing the necessary change in module.config.php to make use of the new factory for the driver. I've added that change to master as well. Can somebody with a working LBS4 setup please try out the latest master code and let me know if it is behaving correctly?

Thanks to everyone for their help with this!

**Comment by Cloud8** [comment]
I have checked out current master and tested against our LBS4 system, and I can confirm that DAIA / LBS4 driver are behaving correctly.

Thanks for the corrections !

**Comment by demiankatz** [comment]
Wonderful, thanks for the confirmation!

**Pull request merged**
