### PR TITLE
Config key array merge

### PR DESCRIPTION
**Pull request by lahmann**
Until now when config files use inheritance by section `[Parent_Config]` settings using arrays (`setting[] = "xyz"`) are being overwritten by the last child of the inheritance-chain. This behaviour would be expected if `override_full_sections` would be enabled for the array's section but the values are overwritten every time.
This pull request merges settings using arrays unless overwriting the values is enabled via `override_full_sections`.

E.g. until now

config1.ini
```
[Section]
setting[] = "abc"
```
config2.ini
```
[Parent_Config]
relative_path = config1.ini

[Section]
setting[] = "xyz"
```

will result in
```
[Section]
setting[] = "xyz"
```

This pull request introduces merging of the two arrays, resulting in
```
[Section]
setting[] = "abc"
setting[] = "xyz"
```

### CODE REVIEW

**Comment by demiankatz** [comment]
I wonder if we should add a merge_array_settings option, defaulting to false, rather than expanding the meaning of the override_full_sections option. There may be some situations where merging arrays is preferable, and others where it is not. That might be independent of section handling. I'm concerned that changing the default behavior now could cause undesirable side effects for some users, though I agree that adding the ability to do this could be useful. What do you think?

**Comment by lahmann** [comment]
Hmm, you mean adding a "merge_array_settings" to the `[Parent_Config]` section? Well, I wouldn't mind as it would enable to have the best of both modes - and I agree that changing the current behaviour for how arrays are handled in sections being merged could cause some interruption with current configurations.
Though having the 4.0 release in sight it might be ok for breaking changes - so I think it is more the question if the possibility of having the ability to overwrite arrays while merging key-value pairs without having `override_full_sections` enabled justifies another configuration option.

**Comment by demiankatz** [comment]
Yes, that's what I had in mind. And as you say, I think having both of these options is useful regardless of backward compatibility issues... I just thought trying to maintain compatibility here would be a good idea, because this is the sort of change that could cause subtle behaviors that users might not expect... however if we wanted to change the default behavior with 4.0, we certainly could. Not sure how many people are using parent configurations or how big the impact might be.

**Comment by lahmann** [comment]
Well I just had a somewhat similar case the other day: removing an entry from the related setting in the Record section in config.ini becomes quite difficult as one would have to override the whole section (which means all settings need to be replicated) vs. simply adding a `related[] = ` in the child-config (to override the parent's config value). On the other hand this is more like a hack than anything else and could be easily worked around when having a proper basic setup which only gets extended rather than being partially reduced...

What about me adding the additional config setting and we discuss this on the next devcall (especially if someone else has any strong feelings about this issue)?

**Comment by demiankatz** [comment]
Sounds good to me!

**Comment by lahmann** [comment]
Ok, I added the setting - let's wait for the devcall.

**Comment by demiankatz** [comment]
@lahmann, there were no objections on the devcall. I've made a minor code simplification (to make the reading of the config setting less complex) and added test coverage for the new feature. I think this is ready to merge. Any objections before I hit the button?

**Comment by lahmann** [comment]
Demian, I have to apologize for not attending the devcall - unfortunately other duties called my attention and I forgot about it. Thanks for bringing up the issue during the devcalls though and thanks a lot for adding the tests and getting this ready for merge to master.
From my point of view there's nothing left to do, so thumbs up for merging this into master.

**Comment by demiankatz** [comment]
Thanks, @lahmann, I'll merge it now!

**Comment by lahmann** [comment]
Thanks!

**Pull request merged**
