### PR TITLE
Enable fluid layout between 768px and 991px, tweak sidebar

### PR DESCRIPTION
**Pull request by EreMaijala**
While working on facets I realized that with screen widths between 768px and 991px the sidebar is really narrow cramped. So here's an idea: make the width fluid on those width and make sidebar padding in sandal/sandal5 narrower unless the screen is really wide. What do you think? 

This is now based on release-10.1 branch, but can be rebased on dev if deemed too risky.

### CODE REVIEW

**Review by crhallberg — APPROVED** [review]
This looks good! In the near future, perhaps we can simplify things with a fluid/max-width container by default instead of BS5's fixed breakpoint widths. Thanks again!

**Review by sturkel89 — CHANGES_REQUESTED** [review]
I checked this branch in all five themes and in both English and Arabic/Hebrew. Nice work! Almost everything looks good.

I have identified a bunch of minor issues (mostly with Arabic/Hebrew layout) that pre-existed this PR, so I won't list them here. The following is the only formatting issue I noticed that is new to the test branch.

**Bottom padding on sidebar element** 
There is a minor formatting issue with the sidebar elements in both Sandal themes. The sidebar elements are comprised of black text on a white area surrounded by a gray shaded background that sits in the foreground of the entire page's white background. At full screen width, this gray shaded background has nice padding all the way around:

image

At narrow screen widths, the gray padding along the bottom of the element is missing:

image

That's it!

**Comment by EreMaijala** [comment]
@sturkel89 It seems to be an old issue. And it's awkwardly complicated to fix. The margin is there, but it gets collapsed, and trying to make it display would break the sticky "Select multiple filters" box. If you can confirm that you see it also in release-10.1 branch, I'd propose we handle this one separately.

**Comment by sturkel89** [comment]
There are tiny differences between your branch and release-10.1, but in both cases the bottom gray padding is missing at narrow screen widths. Sure - we can move this to its own PR if we deem it worth solving. (Sounds like a pain, though, and it's just aesthetic and doesn't hurt functionality.)

### Test branch:

image

### Release-10.1:

image

**Review by sturkel89 — APPROVED** [review]
This is good to merge for now. We can deal with the bottom padding separately. Thanks!

**Pull request merged**
