### PR TITLE
Bugfixing for sharded Solr-Setup

### PR DESCRIPTION
**Pull request by lahmann**
On testing a sharded setup with Vufind2.3.1 I came upon some errors in the recommendation sidebar in record-view. After further investigation I found some bugs in the code (it's identical in Vufind2.3.1 and latest github-commit):

1.) replaced not_null check of initialized array in VuFind\Search\Solr\Params
2.) removed redundant call of explode(implode) in VuFind\Search\Solr\MultiIndexListener
3.) added params->set(shards) for other contexts than retrieval in VuFind\Search\Solr\MultiIndexListener (I'm not entirely sure if this fix is correct - identical params->set(shards...) calls in the if- and the else-block should be moved out of the if-else-block but I wanted to make the fix as inobstrusive as possible in case I'm getting something wrong how the different event-contexts work)

Similiar items/recommendation-sidebar do work fine after this fix with a sharded index.

### CODE REVIEW

**Comment by demiankatz** [comment]
Replacing the not_null check definitely looks like the right thing to do here.

However, I believe the other check is not correct. This will force all shards to be active at all times, overriding the user's ability to uncheck shards.

At the time the event fires, the 'shards' parameter should already be filled in with the user's selections. The reason for the explode(implode()) call is simply that $params->get('shards') will return an array with a comma-delimited string in the first position... using implode allows the data to be retrieved in a single line. i.e. it converts `["a,b,c"]` to `["a","b","c"]`.

I'm not ruling out the possibility that there is some sort of bug here, but if there is, I don't think this is quite the right solution... I note that your code not only turns on all of the shards but also changes the format of $shards from `["a","b","c"]` to `["a,b,c"]`; either that's another problem, or else that might be the important part of the fix.

Let me know if you need clarification on any of this or if I can help with testing, etc. I don't have shards set up on my test server at the moment, but I can put something together if you need me to.

**Comment by lahmann** [comment]
Hi Demian,
thanks for the explanations - I do understand the event-handling better now and you are right - my fix breaks the shard-selection.
So, rewinding the changes I suggested (apart from the not_null-check) the call implode(',' $params->get('shards')) produces a PHP-Warning in Record-View as the shard-params are not submitted for the Record-View and params->get(shards) returns null.
Therefore I suggest to check the params->get(shards) result:

                // Check if $params->get('shards') returns an array to prevent
                // invalid argument warnings.
                $shards = explode(',', implode(',',
                    (is_array($params->get('shards')) ? $params->get('shards') : array())));

Admittingly it is just a cosmetic fix. :)

Let me know what you think.

Best,
André

**Comment by demiankatz** [comment]
Thanks! I've revised this a little more to avoid redundant calls to $params->get('shards'), and I've expanded the comments slightly. I've also expanded the unit test coverage of the listener class to ensure that expected behavior remains unchanged. Thanks for the fixes; I'm now able to close this PR.

**Comment by demiankatz** [comment]
Please try the latest master and let me know if you run into any further problems!

**Comment by lahmann** [comment]
I just tried the latest master - it works fine with my sharded setup! Thanks! :)

**Pull request closed without merging**
