### PR TITLE
Better differentiation between title and infotext

### PR DESCRIPTION
**Pull request by oschihin**
* very minor change, proposed by a reference librarian
* simply emphasize the title by means of double quote
* at the moment, I see no other usages
* I'm sure there is more important work, though ;-)

### CODE REVIEW

**Comment by demiankatz** [comment]
My only possible objection to this is that it might look strange for titles that already contain quotes (not a common case, but they do exist). Would it be better to use some sort of markup, like <i> or <em> or <u> to differentiate the title?

**Comment by oschihin** [comment]
I would have no objections, but my tests with <em> and <i> changed the font size, which looks even worse. <u> seems to be deprecated as a tag.

**Comment by demiankatz** [comment]
I'll see what @crhallberg thinks, as he's the resident expert on this theme.

**Comment by crhallberg** [comment]
I just went through a couple options and I have to agree with Demian on the quotes. The <u> tag may have been deprecated in the specification, but it's accepted in every browser, although it looks misleading (looks like a link).

I wasn't seeing the font size problems with <em> and <i> though, which theme are you using? I didn't see the problem with bootstrap3, bootprint3, or blueprint.

**Comment by oschihin** [comment]
We are using our own theme (sbvfrdsingle, based on bootstrap3) with no overwritte on this particular template. At the moment, I have no clean standard installation to test. So if you insert `<em>` or `<i>`, we will have to follow up with CSS-adjustments, I guess. That'd be fine with me.

**Comment by EreMaijala** [comment]
I believe styling hard-coded in the templates should be avoided, so I'd suggest using a style for the title allowing one to define whatever style and use ::before and ::after selectors to add double quotes if desired.

**Comment by crhallberg** [comment]
Unfortunately, ::before and ::after CSS selectors do not work with
elemental tags, it'll insert them as text. I'm not saying someone won't
want to see Add <em>Moby Dick</em> to List, but most wont. Maybe we could
do something similar to the highlighting system?

**Comment by demiankatz** [comment]
I think Ere's point is if we did something like &lt;span class="titleInHeading">...&lt;/span> then we could apply the appropriate text formatting to that class and/or use ::before/::after to attach quotes.

**Comment by EreMaijala** [comment]
Yes, that's what I meant.

**Comment by oschihin** [comment]
I tried to implement something based on my understand of @EreMaijala idea. I am not safe with less/css, and this could be put in some other place, and styled differently. Also, the `font-size : inherit` is due to my change of font-size. Just have a look at it.

**Comment by crhallberg** [comment]
This implementation looks good, however we should keep all customizations in this file: `themes/bootstrap3/less/bootstrap.less`. The file you edited is vendor Bootstrap.

**Comment by EreMaijala** [comment]
I'd still name the class differently. The class name doesn't need to say that it's for emphasis, but should just describe what it is e.g. along the lines of Demian's suggestion "titleInHeading". Or just "record-title" as it's in a h2 that can be used in the css selector (as long as "record-title" doesn't clash with any existing class).

**Comment by demiankatz** [comment]
Thanks, everyone. I've manually merged this to master.

**Pull request closed without merging**
