### PR TITLE
minor-bootstrap-corrections

### PR DESCRIPTION
**Pull request by ckaz**
* adds missing space in bootstrap3/search/advanced/limit line 14
* corrects bootstrap3/scss/components/offcanvas.scss line 68, calc in scss like so: calc(#{$offcanvas-padding} - 5px);

### CODE REVIEW

**Comment by ckaz** [comment]
Hi Chris,
just two minor thing I caught during our VF 4.1 upgrade. The same error occured in the Sandal theme but I couldn't find the files in master:
in sandal/scss/offcanvas.scss

instead of:
- .banner .navbar-right { margin-top: calc(($banner-height-sm - 50px) / 2); } // Put right nav in the middle
write:
- width: .banner .navbar-right { margin-top: calc((#{$banner-height-sm} - 50px) / 2); } // Put right nav in the middle
instead of:
- .banner .navbar-right { margin-top: calc(($banner-height - 50px) / 2); }
write
- banner .navbar-right { margin-top: calc((#{$banner-height} - 50px) / 2); }

Cheers, Claas

**Comment by demiankatz** [comment]
@ckaz, I see that you closed this one as well. Was that intentional?

**Comment by ckaz** [comment]
No it wasn't -- sorry. I missclicked!

**Comment by crhallberg** [comment]
Hello @ckaz. Sorry for the delay. Your changes here seem good but since they're in the scss I want to make sure our less to sass conversion tool won't make these mistakes in the future.

**Comment by demiankatz** [comment]
@ckaz, it looks like all of the changes from here are now in master by one route or another -- @crhallberg and I cherry-picked different pieces to different places. You might want to take another look at the current master to be sure we didn't mess anything up in the process, but I think we're in good shape now. Thanks again!

**Comment by ckaz** [comment]
Oh, I didn't notice it was in the convertes ... Sorry for the confusion.

**Pull request closed without merging**
