### PR TITLE
Add indication for user's public lists.

### PR DESCRIPTION
**Pull request by EreMaijala**
This allows the user to immediately see which lists are marked public when working on them or adding records to them.

TODO
- [x] Add appropriate Mink test case(s)

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @EreMaijala, makes sense to me. Just requesting a review from Chris in case he has any markup/display suggestions. I should also add a case for this to the Mink test. I'll add a TODO checkbox and will take care of it after this has been reviewed.

**Comment by EreMaijala** [comment]
Indeed this was the first way I thought, so other means of conveying the information would be fine for me as long as it's all clear.

**Comment by crhallberg** [comment]
There's not a lot of room in these sidebar items but here are a few options I mocked up.

image

image

image

**Comment by EreMaijala** [comment]
@crhallberg I like the icons more than the text for the sidebar since the text could be even longer when translated. I like the globe, but I think I'd leave private lists without an icon.

**Comment by crhallberg** [comment]
@EreMaijala Like this?
image(1)

**Comment by EreMaijala** [comment]
@crhallberg Yes. Want me to add it to the patch? I'd still keep the textual presentations in the select when adding a favorite, and also when a list is displayed, but for the menu the icon fits nicely.

**Comment by crhallberg** [comment]
@EreMaijala Yes! That sounds good. Let me know if you'd rather me do the patch.

**Review by crhallberg — COMMENTED** [review]
Just waiting on the icons patch. @EreMaijala, do you want me to jump in and take care of that?

**Comment by EreMaijala** [comment]
@crhallberg Oops, thanks for reminding. Icons added!

**Comment by crhallberg** [comment]
Looks like the CSS needs to be merged and compiled.

**Comment by demiankatz** [comment]
@crhallberg, I just went ahead and merged the latest dev branch into this PR, and recompiled everything in the process. I haven't actually tried it yet, though -- let me know if I should at this point!

**Comment by crhallberg** [comment]
Just merged and fixed the conflicts and it looks good!

**Comment by demiankatz** [comment]
Thanks, @crhallberg. There were some broken tests caused by whitespace changes in the templates, so I have fixed those. I'll add some more specific test cases during the next Community Call -- I'm planning on doing a video on Mink testing, so this makes a perfect example to work on during the recording.

**Pull request merged**
