### PR TITLE
Convert Cart to a name-spaced object.

### PR DESCRIPTION
**Pull request by crhallberg**

### CODE REVIEW

**Comment by crhallberg** [comment]
Interesting though, methods can be declared in a `function method() { }` syntax, as opposed to a `var method = function() { }` syntax. Might be worth looking into for the Lightbox because I think it'll make it much easier to read.

Anyone know otherwise or have strong opinions?

**Comment by EreMaijala** [comment]
That's part of the module pattern, see e.g. https://toddmotto.com/mastering-the-module-pattern/#revealing-module-pattern. So it's important for making things private. I wouldn't change it without thorough understanding of the consequences.

**Comment by demiankatz** [comment]
Some further detailed information here: http://stackoverflow.com/questions/336859/var-functionname-function-vs-function-functionname

@crhallberg, I think it's probably wise to convert this PR to use the non-named syntax for consistency, unless, as @EreMaijala says, you have a reason beyond readability. (Readability is good -- don't get me wrong -- but there are clearly other implications in play here).

**Comment by crhallberg** [comment]
I read more articles on the module pattern last night, and saw both non-named and named functions. My tests showed that it made no difference in privacy. However, we are immediately instantiating only one object and it seems like if we'd ever have multiple objects non-named is better and we'll want to be consistent.

**Comment by demiankatz** [comment]
Looks pretty good, but two remaining comments:

1.) I think addItemTo and removeItemFrom should be renamed to addItem/removeItem.

2.) Are you using leading underscores to denote privacy? If so, some things need to be adjusted here for consistency. If not, that's another conversation....

**Comment by demiankatz** [comment]
Manually merged to master. Thanks!

**Pull request closed without merging**
