### PR TITLE
Added fallback to query-1.12.1 for minimal support with IE <= 8.

### PR DESCRIPTION
**Pull request by EreMaijala**
By no means does this mean that everything will work properly on IE 8, but at least it will allow the menus and some functionality by falling back to jQuery 1.x with IE 8.

### CODE REVIEW

**Comment by crhallberg** [comment]
With IE8 and less being only [0.3% of web usage](http://www.w3schools.com/browsers/browsers_explorer.asp), I'm inclined to say that we're not going to support IE8 and less. We're a bit torn about this decision though.

**Comment by demiankatz** [comment]
Just to echo Chris to some extent, I hate to cut out more people than we have to, but in the case of a little-used and declining, no-longer-supported browser version, I'm a bit wary of putting in a special support case, especially if there's any risk at all that it might adversely affect other browsers (say, if there's a bug somewhere related to processing conditional JS loading). I'd be interested to hear your motivation for keeping IE8 support alive, though!

**Comment by EreMaijala** [comment]
I understand. It seems our customer base has an inproportionate amount of those 0.3%..

We can probably do something locally. It seems overriding the js file injection order of the inherited theme is a bit more difficult than one would hope, but we'll manage.

**Comment by EreMaijala** [comment]
Oh, just for the record, we don't want to keep IE 8 support alive, it's just again one of those things we can only give recommendations on.

**Comment by demiankatz** [comment]
If we can do anything to help with the file injection order problem, let me know. And, of course, I understand that the IE8 situation is not necessarily your decision!

**Pull request closed without merging**
