### PR TITLE
Save toggled facets with sessionStorage

### PR DESCRIPTION
**Pull request by crhallberg**
- [ ] Determine if this should be always or configurable.

[VUFIND-1197](https://vufind.org/jira/browse/VUFIND-1197)

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks! A few notes:

1.) The arrow does not appear to be toggling correctly when results are retrieved from storage.

2.) If you turn on the collapsedFacets setting in facets.ini, it does not appear to play well with this code -- it looks like it remembers when you close an open facet, but it does not remember when you open a default-collapsed facet.

3.) Should the keys used for storage also include the search backend currently in use? Otherwise, there is at least some risk of facet settings bleeding from one section of VuFind into another if two backends happen to use the same name for facet fields.

**Comment by edelm** [comment]
regarding 4):
I wasn't fast enough in the devcall today: From my point of view I don't see a usability improvement of having the facets opening after every page-reload. But maybe it could confuse users used to the old behaviour.

**Comment by demiankatz** [comment]
@edelm, I think a naive user is more likely to be confused by the current behavior (resetting the collapse states on every page load) than the proposed new behavior (remember from page to page). For example, one common scenario is paging through a result set. If you go to page one, collapse some things that are in your way, and then go to page 2, it seems preferable to keep those things collapsed rather than popping them back open again. Admittedly, the other scenario, where a user does a search, adjusts facet states, and then starts a second search, it may be more confusing to have those states remembered from search to search as opposed to from page to page... but I still don't think that's too unreasonable a behavior.

Does the paging scenario at least help clarify the usability improvement of adding this feature? Do you still feel that it should be made configurable? (I'm certainly open to a configuration setting if it's not a huge burden... but passing the setting all the way from the config up to the JS may require a lot of plumbing, and it's obviously preferable to avoid that if nobody's actually going to switch the setting in practice).

**Comment by edelm** [comment]
I also don't really see a necessity to be able to configure it. Just a storage of the last state should do it.

**Pull request merged**
