### PR TITLE
Improved author indexing

### PR DESCRIPTION
**Pull request by demiankatz**
This PR ports (and improves) the patches from https://vufind.org/jira/browse/VUFIND-542 to VuFind 2.

TODO list:
- [x] Adjust Solr schema
- [x] Implement custom BeanShell indexing
- [x] Port BeanShell into SolrMarc core
- [x] Update PHP code to correctly handle values in new schema
  - [x] Improve getDeduplicatedAuthors()
  - [x] Update record drivers to use getPrimaryAuthors() instead of getPrimaryAuthor().
  - [x] Solve issues related to getHighlightedAuthor()
  - [x] Eliminate as many getPrimaryAuthor() calls as possible
- [x] Update XSLT indexing to account for new/changed fields
- [x] Resolve implications of renaming authorStr to author_facet (URL integrity, etc.)
- [x] Allow .ini setting to be overridden by parameter in author-modification.bsh.
- [x] Deal with author initials BeanShell patch
- [x] Prevent deduplication of authors / relators due to Set vs. List issues.
- [x] Add PHP code for dealing with author relators.
- [x] Finish translation of relator text domain.
- [x] Arrange for SolrMarc release containing new custom code (now merged to SolrMarc's master and simply awaiting release).

### CODE REVIEW

**Comment by demiankatz** [comment]
@lahmann, not sure if you saw the mailing list discussion about this a while back, but have you given any thought to the problem that the current author/relator logic uses Sets rather than Lists in the BeanShell, which means that results will be deduplicated, thus preventing correlation of authors to relators when multiple authors have the same relator or a single author has multiple relators? Any thoughts on how we should address this? Should we switch to a List to include duplicates, or should we create some kind of delimited field to perform the correlation in a different way?

**Comment by lahmann** [comment]
Demian, a very good catch - no I wasn't aware of this issue. I would vote for using Lists as I don't see any advantage in using delimiters apart from adding string manipulation logic. Plus we should use Lists for relators and authors - just for already excluding the theoretical possibility of one author having two relators, respectively two persons sharing the same name and the data being of poor quality not distinguisihing between these two persons (via authority data etc.).

By the way - how should we proceed with this pull request? What's still to do is implementing PHP code for handling the new relator-fields.

**Comment by demiankatz** [comment]
I've added a checkbox for the "PHP relator handling" step in the list above.

I think that next steps you can work on, if you have the time, would be to proceed with that PHP implementation and (if you're willing/able) to experiment with switching the BeanShell script to use List instead of Set in the relevant places and test the consequences in the application. Perhaps you could create a few fake MARC records with all the necessary edge cases for testing the scenarios (one author, multiple relators; multiple authors with the same relator; etc., etc.).

Beyond those things, the biggest hold-up is on the SolrMarc / Marc4J side, since I'm hoping to get some new versions of those Java projects to simplify the work we're doing in our BeanShell. However, if we get everything else sorted out without progress on that front, we can always port this into SolrMarc as-is and optimize it later.

**Comment by lahmann** [comment]
Demian, I started to implement some PHP code to deal with relators. The idea is to show the relator in braces after the author name (`John Woo (Editor)`). Therefore I added methods similar to `getPrimaryAuthors()`: `getPrimaryAuthorsRoles()`, `getSecondaryAuthorsRoles()`. The output of both method pairs (author-authorroles) should correlate so far, but as the authors are being deduplicated one would have to add the deduplicated role to the left over author-index's role in order to show `John Woo (Editor, Translator)`. I couldn't come up with a satisfying solution as one would have to change the data structure for the authors array returned by getDeduplicatedAuthors(), so that's where I am at right now.
I think putting my code additions in a pull request does not make much sense - it's pretty much:

in SolrDefault.php
```php
/**
     * Get an array of all main authors roles (complementing
     * getSecondaryAuthorsRoles()).
     *
     * @return array
     */
    public function getPrimaryAuthorsRoles()
    {
        return isset($this->fields['author_role']) ?
            $this->fields['author_role'] : [];
    }

/**
     * Get an array of all secondary authors roles (complementing
     * getPrimaryAuthorsRoles()).
     *
     * @return array
     */
    public function getSecondaryAuthorsRoles()
    {
        return isset($this->fields['author2_role']) ?
            $this->fields['author2_role'] : [];
    }
```

I am afraid this pull request has to wait after release 2.5 unless you find time to work on it. But I'll be happy continuing work on it in October when I'm back.

**Comment by demiankatz** [comment]
I'll try to find some time to work on this before the next release, though whether or not this ends up in 2.5 will depend to some extent on whether we can arrange a SolrMarc release in time, since I don't want to add this functionality without the indexing routines being built into SolrMarc. I'm doing my best to get that process started, but it's not entirely within my control (there are other complications on the SolrMarc side, like the fact that it needs to transition from Google Code to something else soon due to the impending Google Code shutdown).

**Comment by demiankatz** [comment]
I have ported the current BeanShell functionality into SolrMarc. This currently resides in a branch: https://github.com/solrmarc/solrmarc/tree/vufind/improved-author-indexing -- obviously we'll need to merge that branch into SolrMarc master and arrange for a new release prior to merging this PR into VuFind master.

We'll have to be sure to port over any future changes to the .bsh file. Also, more testing of the compiled code is in order; I've only done some very cursory reviews so far.

**Comment by demiankatz** [comment]
I've just merged André's latest work on this project into the main PR. It's going to cause a Travis build failure due to new work-in-progress language files. Once that translation work is completed, I think we'll be able to schedule a merge to master. (The only other item still to be completed is dealing with author initials -- André and I discussed that long ago as a second phase of work; I'll have to dig up old emails to refresh my memory on exactly what we planned on doing... not sure if we want to start on that now or wait until the rest is done first).

**Comment by demiankatz** [comment]
@lahmann, it appears that we're nearly done with the translation work. However, my language file analysis tool is reporting two lines in the German file that are missing from the English one:

    CreatorRoles::Mutmaßl Verf = "mutmaßlicher Verfasser"
    CreatorRoles::Vorr = "Autor der Einleitung, Vorwort, etc."

Is this intentional? Do we need to add missing English lines and/or remove extraneous German ones?

**Comment by lahmann** [comment]
Demian, thanks for checking! No that was not intentional at all - I just created a pull request with these missing translations. Sorry again.

**Comment by demiankatz** [comment]
That's great! I believe that means we can go ahead and check off the translation box as done -- now to wait for progress on the SolrMarc release.

**Comment by demiankatz** [comment]
@lahmann, before sending the missing translation list out, I decided to do one last review of the new language strings here, and I ended up cleaning up a few things (see https://github.com/vufind-org/vufind/pull/354/commits/20553149d2a5a6333218feead1685a54fc086e8a -- please let me know if you disagree with any of my adjustments).

One remaining question: I notice that we have a handful of entries here where the only difference between them is case. In most cases, all cases yield the same translation. However, in en.ini, we have `Beiträger = "Contributor"` and `beiträger = "Literary contributor"`, which seems like a possible error (though the German version has a case-sensitive change in meaning as well). Is this case sensitive difference intentional? If not, might it be a good idea to normalize the case of the strings prior to translation to cover more cases, or do you think that maintaining case sensitivity might be critical here?

**Comment by lahmann** [comment]
Demian, thanks for checking the translations and correcting the cases of some terms, I have no objections so far.

Regarding the upper/lowercase terms, unfortunately this is somehow critical - if we go with normalizing all the relator terms/codes it implies that the terms need to be normalized when being indexed. When using the beanshell script this should not be an issue, but if relator terms are read from the Marc fields in VuFind one would have to normalize those as well in order to translate them appropriately. Maybe that's too hypothetical but I would rather leave those case-differing relator terms in the language files just to make sure every known code variation is covered (not implying any specific preprocessing). 

Regarding the differing translations for case-differing relator term "Beiträger" this is definitely wrong - I will talk to my colleague tomorrow which of the translations is the correct one (although I'm pretty sure it's "Contributor" - but better be sure that sorry :)). Thanks for spotting this one though!

**Comment by demiankatz** [comment]
Thanks, André; I will delay on requesting translations until the Beiträger situation is resolved.

Regarding normalization, my thought was that we could normalize this in the templates, after the data was retrieved from the record driver, which would shield us from index-time/MARC-extraction issues. However, I think it may be too early to make these kinds of assumptions, so it's probably safest to leave it as-is. We can always revisit the issue and simplify the language files in future if it seems justified.

**Comment by lahmann** [comment]
Demian, after talking to my colleague it turns out the "Beiträger"-relator-term issue is more complicated than expected and also shows that the case of relator terms is of importance:
* "beiträger" is a RAK relator code specific to the German library network **GBV** which differentiates between "beiträger" (Literary contributor), "beiträger k" (Artistic contributor) and "beiträger m" (Musical contributor).
* "Beiträger" is  a RAK relator code specific to the German library network **SWB** which does **not** differentiate contributors - therefore the more general meaning "Contributor" is used for this code.

So these two, only differing in case relator term codes do have different meanings. Maybe we should add some comments to those lines?

e.g.:
```
Beiträger = "Contributor" ;RAK Relator Code used by German library network SWB
beiträger = "Literary contributor" ;RAK Relator Code used by German library network GBV
beiträger k = "Artistic contributor" ;RAK Relator Code used by German library network GBV
beiträger m = "Musical contributor" ;RAK Relator Code used by German library network GBV
```

**Comment by demiankatz** [comment]
Unfortunately, I think the normalization routine we use to keep language files clean will strip out those comments (our language files aren't "pure" .ini; they're a subset designed for convenience). Might at least be worth adding notes at the top to indicate the reason for case sensitivity. I can do this if you don't have time -- just let me know!

**Comment by lahmann** [comment]
If you don't mind it would be great if you could add a short note in the header, so we are all set for handing out the lists to other translators. Thanks!

**Comment by demiankatz** [comment]
Will do!

**Comment by demiankatz** [comment]
Okay, comments added; feel free to adjust if you wish.

I plan on merging this to master tomorrow in parallel with Solr 5 (might as well get all changes requiring reindexing done at close to the same time to minimize the pain).

**Comment by lahmann** [comment]
Thanks Demian, looks good! It's great news that this branch will finally get merged into master tomorrow - I am looking forward to it!

**Comment by demiankatz** [comment]
Manually merged to master.

**Pull request closed without merging**
