### PR TITLE
Update Feedback to work with new Lightbox (VUFIND-1177)

### PR DESCRIPTION
**Pull request by crhallberg**
Branched off of release-3.0.

- [x] View feedback instead of throwing
- [x] Use of VuFind/Mailer
- [x] Captcha option
- [x] Write tests

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, Chris! A few minor comments:

1.) I don't think we have to add the "Dear ..." and signature lines to the email message. The sender and recipient name are hard-coded in config.ini, so making them part of the message isn't really meaningful. I think their intent was more for the purposes of email filtering, etc., so their place is really just in the message header.

2.) In the conditional adding of the "Name" line to the message body, I think you want a `.=` instead of just an `=`.

3.) Is writing the test on your to-do list, or should I add it to mine? If on yours, don't forget to testOnly setting in the [Mail] section of config.ini to bypass actual email-sending so the test doesn't generate pointless email traffic.

**Comment by crhallberg** [comment]
3.) I added it because it sounded like it was on your todo list. But I could do it.

**Comment by demiankatz** [comment]
I'll try to find time for it in the near future. If you're bored and want to take it over, just check with me first.

**Comment by demiankatz** [comment]
This has been manually merged with some additions and adjustments. Thanks, Chris!

**Pull request closed without merging**
