### PR TITLE
Return early from login if called from login lightbox to avoid proces…

### PR DESCRIPTION
**Pull request by EreMaijala**
…sing the target page twice.

### CODE REVIEW

**Comment by demiankatz** [comment]
@EreMaijala, I did a little bit of additional refactoring here in an effort to improve readability and reduce redundancy, adding helper functions for lightbox detection and returning the 205 status.

However, more significantly, I found a problem during testing: this change disrupts workflows where there are multiple steps taking place within the lightbox. For example, if you do a search and try to add one of the search results to your favorites, you will get prompted to log in. Normally, after you log in, the "add to favorites" dialog will immediately pop up... however, with this change, the whole page refreshes and the context is lost.

Do we only really want to use this feature when the user goes through the MyResearch/UserLogin route directly, as opposed to getting pushed to MyResearch/Login by some multi-part workflow? Perhaps the UserLogin route needs to set some kind of flag that can trigger the 205 status.... Sadly, I think this is a little more complicated than it appeared at first. As noted elsewhere, I'll be out of town for the rest of this week, but I'm happy to discuss this further upon my return (or sooner, if I have a free moment).

**Comment by EreMaijala** [comment]
Right, thanks for testing. I completely failed to take the multistep workflows into account. I'll see what needs to be done. I think MyResearch/UserLogin is sufficient since it's the one that's loaded in lightbox for the normal login request and anything else is either outside of lightbox or part of a more complex workflow.

**Comment by demiankatz** [comment]
Thanks, @EreMaijala! I'll re-run the tests when I return to the office next week.

**Comment by demiankatz** [comment]
@EreMaijala, all tests are passing and the code looks good to me. Merging now. Thanks again!

**Pull request merged**
