### PR TITLE
Persistent favorites

### PR DESCRIPTION
**Pull request by mbeh-ub**
This code implements a cache for record data. E.g. when adding a new favorite the record data will be stored in the database (therefore we added a new table record).

To use the the cache you have to add a new table to the vufind schema an enable the cache in the settings:
1) Add a new table to the vufind database. For postgres use: 
CREATE TABLE record
(
  id serial NOT NULL,
  record_id character varying,
  user_id integer,
  list_id integer,
  session_id character varying,
  source character varying,
  data text,
  updated timestamp without time zone,
  expire timestamp without time zone,
  PRIMARY KEY (id)
);

GRANT ALL ON TABLE record TO postgres;
GRANT ALL ON TABLE record TO vufind;

GRANT ALL ON TABLE record_id_seq TO postgres;
GRANT ALL ON TABLE record_id_seq TO vufind;

2) In config.ini set cache=enabled ( see Section [Social] )

### CODE REVIEW

**Comment by mbeh-ub** [comment]
I noticed that when I delete a favorite that the corresponding row in the resource table won't be deleted. 
Is this right?

**Comment by demiankatz** [comment]
It's possible that some relics will get left behind in the database. I believe that some of the removal routines have at least some limited cleanup built in, but figuring out whether it's safe to delete a resource could be an expensive lookup, and I think it's likely that VuFind isn't doing that work at the time of favorite deletion. It might actually make sense to build a new command line utility for eliminating orphaned rows, and then this could be run on a schedule, similar to the current search table cleanup.

**Comment by demiankatz** [comment]
I think there may be a logical problem with your cache clearing logic. It appears that when you check for orphaned records, you're including a user_id in your query. Doesn't that open the possibility of this scenario?

- User 1 adds item to favorites
- User 2 adds the same item to favorites
- User 1 deletes the favorite, and the cache is emptied out
- Now User 2's favorite is broken

Sorry if I'm misreading the code and this isn't actually a danger....

**Comment by mbeh-ub** [comment]
Thank you for reviewing the code. Luckily the described scenario doesn't cause problems.
If different users add the same item to their favorite list, a cache entry for each user will be created. 

In the first instance this seems to create an unnecessary overhead. But we want the favorite entry to reflect the state of the item at "save" time. For example:
* User 1 adds item A to favorites
* item A changes in the index
* User 2 adds the same item A to the favorites after item A changes in the index
* => We don't want the item in User 1's favorite list to be changed

**Comment by demiankatz** [comment]
Hmm. That makes sense, but it also seems potentially problematic -- some users are going to want the item saved exactly as they saw it at the time of saving, but others may actually want the latest version (if the record has been corrected/expanded). And what happens if the same user saves the same item to multiple lists at different points in time? Will the old version be replaced, or will the new version be ignored?

**Comment by mbeh-ub** [comment]
1. I see tree options according to the first problem:
* show the version at save time
* retrieve the record from the index as usual and use the cache only if that fails.
* add an update symbol to the UI for updating favorites
It should not be that complicated to implement this option and make it configurable via config.ini

2. In an earlier version of the cache a record would be added for each userId/listId-tupel.
* This resulted in different versions of the same item in different lists. This is probably confusing the user.
* Furthermore arose the question which item version to show in the summery list.
So we add a record based on the userId. As a result old versions will be implicitly updated.

**Comment by demiankatz** [comment]
My gut feeling is that the most common use case would be to use the record from the index as usual, reverting to the cache only if that fails. If that approach were taken, it would seem to make the most sense to keep just one copy of each record in the cache, possibly updating it whenever a new user saves the same favorite. This is more of a "safety net" approach than an attempt at maintaining exact copies of all saved records -- but it seems like a simple and reasonable approach.

However, I can certainly imagine use cases where it might be desirable to have favorites remain static and represent the exact state of saved records. If this approach were taken, I wonder if one approach might be to key the cache by an md5 hash of the record itself, and add a field to the favorites table to store that hash. This adds extra complexity, but it would reduce redundancy in the database and ensure exact matches. However, it doesn't solve the problem you note of figuring out which version to display in the merged favorite list. Personally, I think that case may be another argument for opting for the simpler "safety net" approach -- but of course, if your needs dictate a different approach, that may be inadequate.

It's a tricky thing to decide upon because it seems to me that each approach favors a different underlying implementation, so it may be tricky to figure out how to present multiple configurable options. However, if you have ideas on that front, I'm certainly open to the idea of offering the user more choices here.

**Comment by mbeh-ub** [comment]
I added the ability to control the cache behavior in two ways:
1. index first vs. cache first
  1.1 index first: the cache can act as a fallback if the index fails or
  1.2 cache first: as a store for exact copies of saved records (favorites).
2. granularity for saving records, i.e.
* store a single record (create cacheId based on recordId and source)
* store a record on per-user-basis (create cacheId based on recordId, source and userId)

The behavior is specified by setting the cachePolicy in config.ini or by using the method
$recordCache->setCachePolicy($cachePolicy).
The cachePolicy is realized as a bitmask which allows to combine the follwing aspects:

    protected $DISABLED          = 0b00000; //  0
    protected $PRIMARY           = 0b00001; //  1
    protected $FALLBACK          = 0b00010; //  2

    protected $INCLUDE_RECORD_ID = 0b00100; //  4
    protected $INCLUDE_SOURCE    = 0b01000; //  8
    protected $INCLUDE_USER_ID   = 0b10000; // 16

The default cachePolicy is 0 (disable cache), so the loader behaves as usual.

**Comment by demiankatz** [comment]
This is coming along very nicely. Thanks again for all the work. A few more comments:

1.) We should add MySQL support to this. I'd be happy to take care of that for you during my own testing if you like; if so, please give me write access to this branch so I can push up the necessary changes.

2.) At this point, have you finished refactoring to eliminate the need for the search backend? It looks that way to me, but perhaps I am missing something. If this is the case, it looks like you have a number of files in this branch that are no longer necessary and can be removed.

3.) If you are now happy with the way configuration looks, perhaps you should expand the comments in config.ini to elaborate the available options.

4.) There are some code style issues (missing function comments, etc.) that will need to be cleaned up before we merge this. You can run "phpcs --standard=PEAR" on your files for a summary. If you don't have time to fix this up yourself, I'm willing to help -- that's just another case where it would be helpful for me to be able to push changes here.

Thanks again, and let me know if there's anything else I can do to help. Once I hear back from you on these comments, I'll try to set aside some time for actually testing the code on my own server.

**Comment by mbeh-ub** [comment]
Hi Demian, 
I fixed the mentioned issues and:
1. added a create table statement to the mysql.sql script and a separate migration script for mysql on existing installations.
2. eliminated deprecated code (in particular the search backend code)
3. updated the config options and description in config.ini
4. made the code PEAR-compliant

I would say the cache code has now beta-status. 

Thank your very much for your suggestions !!!
Markus

**Comment by demiankatz** [comment]
Thanks for this. A few minor things:

1.) Is `UNIQUE KEY `record_id` (`c_id`)` a typo in the MySQL definition? Shouldn't both values be c_id here?

2.) What is the Katze / CACHED_Katze_CACHED str_replace() for? Looked like it might be a test or local thing; if it's meaningful it could probably use a comment!

3.) I notice that you define your cache service as VuFind\RecordCache and then retrieve it as VuFind\Record\Cache. This works because ZF2 ignores backslashes in service names, but it would probably be good to make this consistent one way or the other for readability.

4.) There are some small typos here and there that I would like to correct. If you can give me push access to this branch, I can fix them myself rather than making a list and taking up your time... or I can wait and fix them upon merging this.

Hopefully I'll have time to actually test this next week!

**Comment by mbeh-ub** [comment]
Hi Demian, I fixed the points 1.)-3.) and added you as a collaborator.

For testing I recommend to replace line 109 in Record.php:
  (-)  $record->data = json_encode($rawData); 
  (+) $record->data = str_replace('Katze','CACHED_Katze_CACHED',json_encode($rawData));
Otherwise it is hard to determine if a record comes from cache or the original source

Another point regards the use of the Record module. When displaying a single record in "details-view" we in general don't now if to read the record from cache (in case we came from the favorite list) or from the index (in case we came from a index search). So I added the ability to pass a parameter 
?cachePolicy=favorite to retrieve the record from cache. 
E.g.: <host>/vufind/Record/078900468?cachePolicy=favorite

**Comment by demiankatz** [comment]
I didn't get a chance to do much testing of this yet due to work on upgrading master to the latest Zend Framework and taking advantage of PHP 5.4 features; however, I at least managed to merge the current master into the branch and confirm that records are being saved to MySQL. I'll do some more extensive testing and have more detailed comments for you next week.

**Comment by demiankatz** [comment]
In the meantime, please let me know if you encounter any upgrade-related issues.

**Comment by demiankatz** [comment]
Hello,

I've done a bit more work on this and a little testing. Some comments/questions:

1.) Perhaps I am misconfiguring this, but the cache doesn't seem to be working for me. If I add an item to my favorites, I see it appear in the record table in the database, but if I then switch to a different index that does not contain the saved record, VuFind does not seem to be loading the record from the cache. Could you retest on your end? If the problem is that I broke something during my cleanup, I apologize!

2.) Why does the record table have a sequence as the primary key? Would it be better to use the c_id as the primary key?

3.) Should the bitmask be simplified? For example, do you need separate bits for PRIMARY vs. FALLBACK? Could one behavior be the default, with a bit to switch to the non-default behavior? If you do feel separate bits are necessary, should you throw an exception if both bits are set, since this seems like an undesirable option? Similarly, does it really make sense to have bits for INCLUDE_RECORD_ID and INCLUDE_SOURCE? It seems that you would always want to include these values in the key to prevent accidental lookup of unrelated records.

4.) Is there a reason that you are using class properties rather than constants to represent the bitmask values? It seems like constants might be more appropriate.

5.) Right now, your example configuration contains separate "cachableSources" values for "Solr" and "VuFind" (and I included a note about having to include both in config.ini). However, it's probably better if we make this more seamless. The best approach would probably be to have cachableSources correspond with search backend names, and include a special case inside the class to translate "VuFind" into "Solr." (That whole "VuFind" source thing is a legacy of VuFind 1.x that I'd love to get rid of... but it will take a lot of work, so we should probably keep living with it for now).

6.) I see that your class currently defines factories for reconstructing records after the cache. I don't think this is actually necessary; you should be able to simply set the raw data and set the source for all types of records. The only complication is figuring out which source to use for Solr records, but this is an easy enough special case to deal with.

7.) Is the static::getRecordCache($sm) in VuFind\Service\Factory intended to avoid a circular dependency problem? If not, you should probably just be pulling the record cache from the service manager to avoid creating a duplicate instance of the class. If so, we can use the ProxyManager to circumvent the problem in a better way -- let me know and I can work on that when I have a bit more time.

Once I hear back from you on these issues, I'll do another round of testing over here. Thanks again for all of the work so far!

**Comment by mbeh-ub** [comment]
Hello,
sorry for the long period of silence, but time flies...

regarding 7.) I call the record cache directly from the service manager. (In an early version this really should avoid a circular dependency, but this problem doesn't occur anymore )

**Comment by mbeh-ub** [comment]
regarding 1.) On my setup the cache seems to work. I used a vufind compatible index and worldcat.
My config.ini looks as follows:
  [RecordCache]
  cachableSources = "VuFind,Solr,WorldCat"
  cachePolicy['favorite'] = 29

For easier error analysis I added some logging/debug messages.
I also pulled the latest code from vufind master.

**Comment by demiankatz** [comment]
Thanks! I'll test this and provide more feedback later in the week (today the university is closed due to snow).

**Comment by demiankatz** [comment]
I have merged the latest master into the branch again and applied php-cs-fixer to bring the code up to the latest formatting standards.

Upon re-testing the code, it does now appear to be working. If I add a record to my favorites and switch indexes, the record continues to display correctly. If I turn off the cache, the record stops displaying.

However, if I click through to the record page itself, I still get a 404 error. Is it your intent to eventually allow full records to display from the cache?

Either way, I think my items 2-6 from the previous comment may still be worth discussing. Please let me know if you have thoughts on any of them.

Also note that I will be on vacation next week, so apologies in advance if I am not very responsive during that period. Hopefully we can make further progress on this in early March!

**Comment by mbeh-ub** [comment]
To display full records from cache you need to add the query string parameter cachePolicy=favorite. The following example retrieves the record data from cache if possible:  
    http://<host>/vufind/Record/078900468?cachePolicy=favorite

I'am also working on the points 2-6. Regarding point 6  updated the code according to your suggestions. Please see the new method getVuFindRecord($cachedRecords) in the last 
commit.

**Comment by mbeh-ub** [comment]
To display full records from cache you need to add the query string parameter cachePolicy=favorite. The following example retrieves the record data from cache if possible:  
    http://<host>/vufind/Record/078900468?cachePolicy=favorite

I'am also working on the points 2-6. Regarding point 6  updated the code according to your suggestions. Please see the new method getVuFindRecord($cachedRecords) in the last 
commit.

**Comment by mbeh-ub** [comment]
To display full records from cache you need to add the query string parameter cachePolicy=favorite. The following example retrieves the record data from cache if possible:  
    http://<host>/vufind/Record/078900468?cachePolicy=favorite

I'am also working on the points 2-6. Regarding point 6  updated the code according to your suggestions. Please see the new method getVuFindRecord($cachedRecords) in the last 
commit.

**Comment by mbeh-ub** [comment]
I kicked the whole bitmask configuration thing. Instead I added a new configuration RecordCache.ini with some comments. I think this is much more easier to understand and also simplifies the code in Cache.php

Regarding to 5) it is now sufficient to set Solr as a cachable source (I add "VuFind" when I parse the config and init $cachableSources in class Cache)

Regarding 2) I'am not sure, but my gut feeling is not to change the default way postgres handles primary keys.

**Comment by demiankatz** [comment]
Regarding 2), my main concern is that using a sequence as the unique identifier, in place of a field which is intended as a unique identifier anyway, might somehow lead to the possibility of duplicate c_ids, which could in turn cause unexpected behavior. However, I realize that the c_id value is fairly long and might not be well-suited as a key from a performance perspective (or due to architectural limitations which I may not be aware of). If you think it's better to leave it as-is, that's okay with me... but it seemed like something that might be worth thinking about.

In any case, thanks for the other changes. I'm back from vacation and will try to run some more tests on this once I'm caught up again.

**Comment by demiankatz** [comment]
A few new notes/comments:

a.) I just pushed up some corrections/expansions to the comments in RecordCache.ini; you might want to double-check that my statements are correct.

b.) One thing to consider is the possibility that future Solr schema changes will cause cache-related problems. That is, after a VuFind upgrade, if the Solr schema is different, records coming from the cache may not be handled correctly. While we don't tend to make huge, dramatic changes to the schema, it does evolve over time, so this may turn out to be a problem. (Similarly, we can't control when third-party APIs like Summon may decide to change their formats). Obviously this doesn't nullify the value of the cache, but it's an issue way may want to plan for. One possibility might be a command line utility that refreshes the cache after an upgrade, loading new versions of all cached records (though I realize this negates the cache benefit of allowing users to see exact versions of records "as they were"). Another possibility would be to write upgrade scripts that actually rewrite the cached data, but this seems overly complicated. In any case, no action needed on this -- just food for thought.

c.) Is it possible that we need more granular configuration options? What if we wanted to configure the cache to behave differently for different sources? I could envision a scenario where we might want to use the cache as a primary data source to accelerate a slow third-party API while also using it as a fallback to preserve "lost" Solr records. If you think this might be worthwhile without being too difficult to implement, there are a few approaches that might work... a [source.case_name] section naming convention might work ([Solr.Favorite], [WorldCat.Favorite], etc.). Or we could use arrays within the sections, like operatingMode[Solr] = .... But then comes the question of whether we force the user to spell out all of the source-specific settings, or if we also offer shortcuts to make a simple global configuration like the current .ini file offers. Again, if you think this gets too complicated, I can certainly live without it for now... but it might be worth doing before we release the feature so we don't have to redesign the configuration later, after it's been put into general use.

d.) How would you feel about renaming the record table to recordcache to be more specific about its purpose at a glance? Or do you prefer the more general "record"?

e.) As this gets more finalized, we should consider writing some unit tests. I'm willing to help with this if you do not have time.

Anyway, this is looking really good. I think we should be able to merge soon, though perhaps we should wait until after the 2.4 release if we need to devote time to any complex work resulting from my comments above.

I'm going to do some testing and make a few more minor adjustments, so I'll add further comments if I run into any trouble. Otherwise, I'll await your next reply!

Thanks!

**Comment by demiankatz** [comment]
I just tried a configuration where I put operatingMode = "fallback" in the [Default] section to see if that would allow the record view to work correctly after clicking a link from my favorites page after a record has been deleted from Solr. It did not work -- I'm just getting the usual exception error. I then tried adding ?cachePolicy=favorite to my URL, and that didn't make a difference. Before I dig deeper into this on my end, do you mind retrying this scenario on your own system to make sure it's specific to my setup and not a more general problem? Thanks!

**Comment by demiankatz** [comment]
One more observation:

f.) In the saveBulk method of VuFind\Controller\Plugin\Favorites, we're now loading every record as it is being saved. Since record loading can be an expensive operation, we probably shouldn't do this unless we really have to. Would it make sense to add an "isCachable" method to VuFind\Record\Cache that will tell us whether or not a particular id/source combination needs to be cached? Then we could circumvent the record loading for records that are not going to be cached. Having isCachable might also be useful internally within the Cache class for the sake of readability.

I've also pushed up a few minor adjustments to comments, and one small optimization to the way record drivers are initialized.

Thanks again for all the work so far -- I'll leave this alone now until I hear more from you.

**Comment by mbeh-ub** [comment]
**solr-exception when using operatingMode="fallback" in [Default]**
have you also set the values for cachableSources and cacheIdComponents? Please try:

[Default]
operatingMode = "fallback"
cachableSources = "Solr"
cacheIdComponents = "userId"

**to a.)**
 I'am glad about adjustments in RecordCache.ini. 

**to d.)**
I see the record table more like a common storage for records. I think of the caching aspect as an additions functional aspect (realised in the php-code). But I also have no objections to rename the table to recordcache.

**to e.)** 
I also think unit test are essential. I will try to setup a basic strucutre. If I face problems I will appreciate your help.

I'am also going to work on / thing about the points b.) c.) and f.).

Thank you for your fast feedback !

**Comment by demiankatz** [comment]
Regarding the solr-exception, yes, I do have all three settings in my [Default] section. However, I'll hold off on troubleshooting this further until you've made the next round of changes.

to d.)
How would you feel about calling the table recordstore or recordstorage, then? That's a bit more general than recordcache but still feels more meaningful/specific than plain "record."

to e.)
I'm happy to help if you need me to.

To everything else: thanks!

**Comment by demiankatz** [comment]
I see you've done some more work here. Would you like me to do another round of testing/feedback on this, or is it still a work in progress?

**Comment by demiankatz** [comment]
Still waiting for feedback before re-testing, but I merged the latest master into this PR so that we could take advantage of the new Travis CI setup to validate everything. As you can see from the failed build, there are some code style issues that need to be addressed. If you'd like me to help with cleaning this up, just let me know and I'll carve out some time. Thanks!

**Comment by mbeh-ub** [comment]
Hello Demian,

sorry for the long break butI was out of office for the last two weeks.
I hope to make some progress this week.
At the moment I'am working on some test.

Markus

**Comment by demiankatz** [comment]
Thanks for the update; I hope you had a pleasant break! As always, please let me know if I can do anything to help.

**Comment by mbeh-ub** [comment]
Hello Demian,

I added a version number to the record table. This version number will also become a part of the cacheId so we should be able to handle updates/changes in the format for index records.

I also added some test for the check the methods in Cache.php.

Best regards! 
Markus

**Comment by EreMaijala** [comment]
@mbeh-ub, maybe you already noticed but the Travis CI build failed in CodeSniffer. You'll probably have to fix the errors (click the Details link above to see them) for the PR to be accepted. Just commenting because your work is something we'll also need. Thanks for working on this!

**Comment by demiankatz** [comment]
Thanks for the update! Some questions/comments:

1.) I see that you are manipulating $_SESSION['Account'] directly (and using this in your unit test). It would be cleaner to use the \VuFind\Auth\Manager class, which is registered as the 'VuFind\AuthManager' service in the service manager. If you inject the Auth Manager into the Cache object, then you can access the object without worrying about the underlying session-based implementation. Additionally, you could then manipulate the user object in the tests using a mock manager instead of touching the session superglobal.

2.) I like the idea of keeping track of version number, but I'm not entirely sure how this would work in practice. If we make the version number part of the cache ID, does that mean that when we increment the version number, all previous versions of records are invalidated? What if those records are no longer retrievable in any other way? It seems like we might need some logic that says "if you can't get the record in the current version, try to retrieve an earlier version" and/or "if the retrieved record is an old version, try to refresh it to a new one." We might also need a placeholder in the code where we could implement operations to manipulate an outdated record to make it compliant with new schema values in the situation where the schema has changed but a newer version of the record cannot be retrieved. I'm also not sure how best to track versions -- I see you have used an arbitrary "1" here, but if we go that route, then we need to remember to increment that number upon future releases. It's even trickier if you consider the possibility that different search services may introduce backward incompatible changes at different times. I wonder if a better approach would be to use the VuFind version number (which can be looked up in the build.xml file) and store it simply for future reference, without incorporating it into the cache key. That gives us the ability to utilize this value for future functionality, but it doesn't tie it too integrally into the system before we actually know what real-life use cases are going to affect us.

3.) As Ere says, Travis is complaining about some style issues. I don't mind helping with the cleanup of these if you do not have time. Just let me know!

**Comment by EreMaijala** [comment]
I think I'll have to take a shot at this. I'm in favor of including the VuFind version number in the cache item. Is there a nice way to get it?

**Comment by demiankatz** [comment]
The easiest way is to parse it out of the build.xml, which is not beautiful, but should do the trick. Take a look at UpgradeController::getVersion; maybe this should be extracted to a helper class somewhere.

**Comment by EreMaijala** [comment]
Ok, thanks. I'm working on it now.

**Comment by demiankatz** [comment]
I'm closing this since it is superseded by #474. If any functionality is missing from the new PR, it's probably easier to implement it on top of that work rather than bringing this old PR up to date, so I'm closing it.

**Pull request closed without merging**
