### PR TITLE
mixin theme should override parent theme

### PR DESCRIPTION
**Pull request by hajoseng**
I changed the loadThemeInfo() method so that mixin themes override their parent themes accordingly

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks for this -- at a glance, it makes sense to me, but I'd like to do a little hands-on testing to confirm everything. Between a conference I'm attending this week and the VuFind Summit next week, it will be a few days before I find the time -- but I'll merge it as soon as possible.

**Comment by demiankatz** [comment]
@hajoseng, now that I have had time to test this, I actually think that we want to leave the existing behavior as it is. However, I can see how this might be a subject for debate.

As mix-ins currently work in master, mix-ins can be overridden by templates in the theme using the mix-ins. As you have changed things here, mix-ins override templates in a theme.

I think the preference depends on how you expect to use the mix-ins.

My assumption is that in order to use a mix-in, you create a custom sub-theme. So, suppose I wanted to mix "mixin1" into the "bootstrap3" theme. I would create a new theme with this theme.config.php:

`<?php return [ 'extends' => 'bootstrap3', 'mixins' => ['mixin1']];`

In this kind of scenario, the mixin is always being included in a local custom theme, and I'm assuming that the parent theme and the mixin are third-party components. Thus, I want to be able to override any of those "upstream" templates with custom versions inside my theme.

I think perhaps you are assuming that I would actually edit the bootstrap3 theme to add a `mixins` setting in order to load in a mixin. In that scenario, the approach presented here would make more sense, since we would want the mixin templates to override the main theme's templates... but since that would require editing core code, it does not seem to be in keeping with VuFind's practices, so that's just not the way I had envisioned mix-ins being used.

Does that help explain how our mental models differ from each other? Under those circumstances, would you agree that we should close this PR without changes, or do you still feel that changes are needed? Do you think we should adjust any documentation to make this situation more clear?

Thanks!

**Comment by hajoseng** [comment]
Demian thanks; I understand your point and I think we should leave it the way you suggested. Maybe it would be good to have a simple example for this.

**Comment by demiankatz** [comment]
Thanks! I've added a note to the wiki at https://vufind.org/wiki/development:architecture:user_interface#mix-ins_and_inheritance -- if you have thoughts on a more visible place to document this, I'm happy to put links to this in more locations.

**Comment by hajoseng** [comment]
I think the note is at the right place and - in my opinion - visible enough.

**Comment by demiankatz** [comment]
Thanks!

**Pull request closed without merging**
