### PR TITLE
Prevent adding facet count if it is undefined

### PR DESCRIPTION
**Pull request by LuomaJuha**
Sometimes this will break fetching of facets if there is some oddities in the index.

### CODE REVIEW

**Review by demiankatz — APPROVED** [review]

**Comment by demiankatz** [comment]
Thanks, @LuomaJuha. This seems like a reasonable extra safety check which I am happy to merge, but a related question: should there be matching code on the back end somewhere that prevents invalid count values from getting passed forward to the Javascript?

**Comment by LuomaJuha** [comment]
@demiankatz I actually have no idea where my error is coming from but if I find the reason, I will try and see if there is anything to be done. At the moment only thing reading in my Organization facet is: null and after that facets are normal. That was the reason my facets did not work.

**Comment by demiankatz** [comment]
I wonder if @EreMaijala might have any ideas...

**Comment by EreMaijala** [comment]
@demiankatz I'll take a look.

**Comment by EreMaijala** [comment]
It's a local indexing issue where a hierarchical facet value contains more levels than it should, so the index entries are not correct. I don't think there should be further need to guard against the Solr index being invalid.

**Comment by demiankatz** [comment]
Thanks for the investigation, @EreMaijala!

**Pull request merged**
