### PR TITLE
Make ID used for ILS health check configurable.

### PR DESCRIPTION
**Pull request by he247**
SetUp an override variable in config.ini: healthCheckId

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @he247, this is great! I'm having a busy week, but as soon as time permits, I'll test it (and possibly revise the .ini comment slightly to make it more generic -- bibliographic ID instead of mmsId, etc.). But this is a huge help, and I don't think it will take much to get it merged.

**Comment by demiankatz** [comment]
Also, @he247, for future reference, it probably is a good idea to create a separate branch for each pull request you open. I see that you made these changes directly to your dev branch, which in the long term could become confusing for you when it gets out of sync with the upstream version. It doesn't cause any problems from the project's end, though, as long as you don't commit unrelated changes to this branch before the PR gets merged.

**Review by demiankatz — APPROVED** [review]

**Comment by demiankatz** [comment]
Thanks again, @he247 -- I've revised the config.ini documentation and tested that this works as expected. I'll merge as soon as continuous integration passes.

**Comment by he247** [comment]
Thank you @demiankatz for the fast integration and your helpful feedback! 😊

**Pull request merged**
