### PR TITLE
Refactor record driver hierarchy (VUFIND-1240)

### PR DESCRIPTION
**Pull request by demiankatz**
This rearranges the record driver hierarchy to a more logical organization, as per https://vufind.org/jira/browse/VUFIND-1240.

Previously, most classes inherited from SolrDefault whether or not they used Solr. This new organization isolates Solr-specific logic to Solr-specific classes, using Traits to extract specific bits of reusable functionality to be used as mix-ins (thus avoiding some inappropriate inheritance contortions).

This diagram shows the changes:

image

TODO:
- [x] Create MARC-specific record driver traits
- [x] Finish revising class relationships
- [x] Test everything

### CODE REVIEW

**Comment by demiankatz** [comment]
@EreMaijala, here is a first stab at refactoring the record driver hierarchy. I haven't spent time thoroughly testing this yet, though I did some quick testing and nothing obvious seems to be broken. Please take a look and let me know if you agree with this direction. It's not 100% beautiful, but I think it's a step in the right direction. Feedback is welcomed!

**Comment by xmorave2** [comment]
Nice job Demian ;)

**Comment by jochen-lienhard** [comment]
I will look at it in the next days. Has you add some methods from my pull request https://github.com/vufind-org/vufind/pull/947

**Comment by demiankatz** [comment]
@jochen-lienhard, I haven't added any methods from #947 yet; I was waiting for your feedback. I prefer not to add record driver methods unless they are actually used for something somewhere, but I'm certainly open to adding new features if they are useful to others, and if any of your methods use MARC to implement existing functionality, they would be strong candidates for inclusion in the MarcBasicTrait.

I'm planning on merging this very soon if no one objects, but maybe we can work on merging master into #947 and making some adjustments after that happens.

**Comment by jochen-lienhard** [comment]
@demiankatz, I think there are some methods in my FullMarcTrait.php, that creates better results (for example for ISBN and ISSN).
So, I'm not sure about the next steps. Do you want to pick the methods, which bring better results, from my PR in your's? Or shall I wait until you have merged this PR and modify my PR after that?
The methods, that are not relevant for vufind, will be packed than in our local MarcRecordDriver.

**Comment by demiankatz** [comment]
@jochen-lienhard, I'll pick out the relevant methods next week when I return from my trip and will leave a comment on your pr when done. Thanks!

**Comment by jochen-lienhard** [comment]
@demiankatz, thanks, that looks good for me, I will put the rest in our local recorddriver.

**Comment by demiankatz** [comment]
@jochen-lienhard, sounds good! Also keep in mind that by default, the MarcBasicTrait is only used by the WorldCat record driver... so if you are extending SolrMarc, you'll want to `use \VuFind\RecordDriver\MarcBasicTrait;` inside your subclass in addition to adding your custom methods in order to get all of the functionality that you need.

**Pull request merged**
