### PR TITLE
Added First/Last navigation for Record scroller

### PR DESCRIPTION
**Pull request by lmgonzales**
Add configurable option to turn on/off "First" and "Last" buttons on record view page when first_last_navigation is enabled in config.ini AND when next_prev_navigation is enabled.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks for this. Looks like a good start. A few issues to deal with, though:

1.) I see at least two instances of the classic "assignment instead of comparison" bug. For example: `if ($this->data->firstlast = true) {` should be `if ($this->data->firstlast == true) {` (or just `if ($this->data->firstlast) {`, if you want to keep it simple). Not only should we fix this, but this may be a sign that our test suite is inadequate, since I imagine this should have caused a test failure.

2.) Right now, the base Options object is hard-coded to read the first_last_navigation setting from config.ini. We don't want to do this, since it prevents us from separating settings for different search backends. A better way to do it would be to create a new property in the base class that defaults to false, and return that property through the getFirstLastScroller() method (which I would perhaps rename to supportsFirstLastNavigation()). Then you can set the value of the property to true in appropriate subclasses -- so, for example, as a start, the Solr/Options class would read the config.ini setting and adjust the property accordingly ([probably around this line](https://github.com/vufind-org/vufind/blob/master/module/VuFind/src/VuFind/Search/Solr/Options.php#L196)). We could then look at other backends on a case by case basis to determine which ones could also include this setting (my guess is, most probably can't, since third-party APIs tend to limit the depth of the result set).

3.) Have you done any testing to check whether this code is doing more searches than it has to? Since the first and last records should remain constant as the user pages through the set, and since identifying those records requires some extra searches, we should be sure we don't recalculate the values unnecessarily. (I'm not saying that we're necessarily doing that -- but since this code is a bit convoluted, I like to check for unexpected behaviors like this when I work on it).

Anyway, thanks again for this useful addition to the code. Please let me know if you'd like my help with any of the above issues!

**Comment by lmgonzales** [comment]
Hi Demian,

Thanks for the feedback. I think I'm going to need your help on the issues you raised above if you have the time. 

1) I've fixed the instances of the classic "assignment instead of comparison" bug; however, the test suite is now failing. I updated the ResultScrollerTest.php file, but can't figure out how to get the test to run properly. Is there something in the VuFindTest/Search/TestHarness/ files? Where do the previousRecord/nextRecord get set in the results set? I've set the firstRecord/lastRecord in the expected array, but haven't figured out where to set this in the test results set. 

2) I've updated the ResultsScroller.php and Options object to make the first_last_navigation setting a configurable object that defaults to false. 

3) No, I haven't done any testing to see if it is doing more searches than it has to. If you have some time, I could use some help with setting up the test code to check for this. 

Thanks again for the feedback and help!

**Comment by demiankatz** [comment]
Leila,

If you need help running the test suite locally so you can see results without having to wait for Travis builds, see https://vufind.org/wiki/development:testing:unit_tests (short version: install [Phing](https://www.phing.info/), then run `phing phpunitfast -Dphpunit_extra_params=module/VuFind/tests/unit-tests/src/VuFindTest/Controller/Plugin/ResultScrollerTest.php` in your VuFind directory).

I suspect that the reason your tests are failing is that first-last navigation is turned off by default, and the test isn't doing anything to turn it on.

Presently, the test is creating a mock configuration manager that doesn't actually return anything. See this line:

https://github.com/lmgonzales/vufind/blob/3b253863bbce192aa5a8c9c644695072d1095936/module/VuFind/tests/unit-tests/src/VuFindTest/Controller/Plugin/ResultScrollerTest.php#L183

You might want to add a new parameter to getMockResults that allows you to inject a configuration into the mock configuration manager. This would allow you to turn on the setting for certain tests in order to confirm that it is correctly enabled or disabled based on the configuration. It would probably look something like:

`$pm->expects($this->any())->method('get')->with($this->equalTo('config'))->will($this->returnValue($config));`

Anyway, I hope that helps point you in the right direction -- and once we have the test suite passing again, we can further discuss the issue of avoiding unnecessary extra searches.

Also, I realize that dealing with PHPUnit mocking can be a bit of a headache. I'm happy to provide more help with this if you need it; just let me know and I'm happy to help (at least, I will be once I'm done with my post-vacation catch-up!)

**Comment by lmgonzales** [comment]
Thanks Demian. Yes, I think on this one I'm going to need your help with modifying the mock results (when you have time of course). Thanks!

**Comment by demiankatz** [comment]
I'm actually approaching being caught up, so maybe I'll have time for this before too long. I'll post another comment as soon as I'm able!

**Comment by demiankatz** [comment]
I finally found some time to do some work on this. Some notes:

1.) I've expanded the test suite to cover more scenarios specific to the new functionality (and made the existing scenarios work correctly).

2.) I fixed some minor problems in the templates.

3.) I did some refactoring to reduce the number of Solr searches required to generate the result scroller information; we now store first/last IDs in the session so we only have to look them up once per search result set.

I think we may be ready to merge this PR. However, since I've made a lot of changes, I thought it best to give you an opportunity to review my work first. Could you test this on your end when you get a chance and let me know if you agree that we're ready to merge?

Thanks!

**Comment by lmgonzales** [comment]
Thanks for improving the code Demian. It's a much better and cleaner implementation. I've implemented all the changes on our development server and they work fine. I think we're ready to merge this PR. Thanks again for all your help!

**Comment by demiankatz** [comment]
Excellent, thanks for the double-check. It's now merged!

**Pull request merged**
