### PR TITLE
Lazily create Voyager database connection and try to avoid using it u…

### PR DESCRIPTION
**Pull request by EreMaijala**
…nless necessary.

This is an initial attempt at trying to reduce the situations where an ILS connection is made so that the database connection is not established unless it's actually needed. This means that e.g. getConfig() could be called without the database connection. Currently the lazy connection initialization is only in Voyager driver because I can't test the others, but it could be extended if this mechanism is found viable. This PR avoids making the ILS connection at least when displaying favorites and saved searches (plus some other situations in our customized version). Previously the check for support of password change initialized the connection when logged in with a library card. Feedback appreciated!

### CODE REVIEW

**Comment by EreMaijala** [comment]
BTW. Travis CI is failing because packages.zendframework.com is down.

**Comment by demiankatz** [comment]
It looks like there are a few different things going on in here, and it might make sense to handle some of them as separate commits. Aside from the main goal of lazily initializing the database, it also looks like you've replaced some redundant code with calls to executeSQL and that you've adjusted the password change logic to use stored credentials instead of updating from the ILS. Each of these things probably merits separate consideration. At a glance, I'd say the executeSQL stuff is a no-brainer and should probably be merged right away. The other parts might require more thought:

1.) Using stored credentials for password change might at very least introduce a timing problem: log in to VuFind, change your password in a different system, then try to change your password in VuFind -- I think you'll run into trouble with this changed code, but the old code may have handled the scenario better. (I'm not in a position to test that, and it may already be a problem... and it's not a very likely situation... but I mention it in case it's a real issue).

2.) The biggest problem with lazy database initialization is that the NoILS driver failover support depends on the Voyager driver failing during initialization so that VuFind can fail over correctly. If we lazily load the database, we may lose the ability to deal with errors gracefully. Again, I haven't actually tried testing anything yet (in case this is already accounted for somehow) but it seems like it might be a concern.

Let me know what you think! And if you agree that we might as well at least get the executeSQL calls merged ASAP, I'm happy to manually merge just those parts of the PR so you don't have to bother opening another one yourself.

**Comment by EreMaijala** [comment]
The changes are all related, but I agree that the executeSQL stuff can be merged right away. A couple of quick comments:

1.) It's only used when checking whether password changing is supported, so it's a whole different thing when the user actually goes to change it.

2.) I haven't actually tried that since it doesn't work with MultiBackend, I believe. That needs to be taken into account somehow, but I'm not sure how it's supposed to work at the moment. I'll take a look.

**Comment by demiankatz** [comment]
Thanks again. I've gone ahead and merged most of the changes from this PR into master, as you have persuaded me that they are safe. I've also merged master back into this PR, so only the specific lazy-loading changes remain. (I've also fixed the problem with the bad Composer repo in composer.json). Let me know if you need more information on the NoILS failover behavior.

**Comment by EreMaijala** [comment]
Thanks! I didn't have time to dig into this, but there's one thing: the lazy instantiation of the db connection is equivalent to a driver using purely web services or such API that will only find out an inaccessible server when a request is made (same is true for Voyager if VoyagerRestful is used and the REST API is inaccessible). From that point of view it should work just as well as, like, the Polaris driver. Or has the init failure been a special property of Voyager driver and not even supposed to work with others?

**Comment by demiankatz** [comment]
That's a good point. The failover feature was originally developed for the Voyager driver, though it was certainly never intended to be a Voyager-only feature. When I have a bit more time, I can test how the system behaves with the relevant configurations both with and without this patch, and see if system-wide improvements can be extrapolated from those findings.

**Comment by demiankatz** [comment]
Just a quick note to confirm that I've tested this branch with the "load NoILS on failure" setting, and as I predicted, it does not work correctly (while master does). The question then becomes whether that is an argument against implementing this, or whether we need a "lazy load" setting in Voyager.ini to allow the choice, or whether we need to figure out a more robust system for monitoring ILS availability (which I feel like I proposed somewhere... though I can't remember where).

**Comment by EreMaijala** [comment]
I'd vote for the more robust system. Since the calls can go wrong in so many ways also after init, this would be the only way to make the "load NoILS on failure" setting work in all cases.

**Comment by demiankatz** [comment]
Should we close this PR for now and open a JIRA ticket to discuss the design? Or perhaps touch on during a future dev call?

**Comment by EreMaijala** [comment]
I'm ok with either way.

**Comment by demiankatz** [comment]
I'll give it some more thought and see if I can come up with a proposal. In the meantime, I'll leave this PR open as a reminder that we need to take some action.

**Comment by demiankatz** [comment]
Please take a look at #768 -- I decided to dive in and do some refactoring to refamiliarize myself with the code. The work in that PR currently takes the hard-coded driver initialization for failure detection out of the VuFind\ILS\Connection constructor and makes it more "on demand." This refactoring did add some significant complexity, so I'm not totally sure it's a step in the right direction, but I think it might make some of the code a little more understandable. It also points to the existing getOfflineMode() method as a possible place where we could hook up more robust ILS health checking functionality.

In any case, I've put some TODO items on #768 to provide some possible directions for future discussion. Let me know what you think when you have time to take a look!

**Comment by demiankatz** [comment]
Finally got around to merging this one -- thanks again!

**Pull request closed without merging**
