### PR TITLE
WorldCat Discovery API integration

### PR DESCRIPTION
**Pull request by demiankatz**
Waiting for OCLC.
- [ ] Migrate templates from blueprint to bootstrap
- [ ] Fix use of session containers to use proper injection of session manager (no more "on the fly" creation)
- [ ] Resolve https://vufind.org/jira/browse/VUFIND-1043 and related JIRA issues
- [ ] Merge master

### CODE REVIEW

**Comment by demiankatz** [comment]
We have some style issues to fix here (hence the failed Travis build).

**Comment by crhallberg** [comment]
I did a lot of checkstyle fixes. I don't have the setup to test it thoroughly, but I don't expect any problems. There were a few checkstyles I decided to leave you so that I don't mis-document something.

Need documentation in RecordDriver/WorldCatDiscovery.php
Need documentation in ILS/Driver/WMS.php

VuFindSearch/src/VuFindSearch/Backend/WorldCatDiscovery/Backend.php
----------------------------------------------------------------------
 88 | ERROR | Arguments with default values must be at the end of the argument list

**Comment by demiankatz** [comment]
Thanks, Chris. Hopefully Karen can help with the documentation stuff in the near future; I'll talk to her about it the next time we touch base.

**Comment by demiankatz** [comment]
This branch has not been worked on in quite some time, but I'm still leaving it open as a reference for a possible future WorldCatDiscovery/WMS implementation. The pull request was difficult to read due to the large number of vendor files being added. I have merged this with master up to the point where we stopped committing the vendor directory in order to improve readability of the pull request. I have not tested anything post-merging, so I can't guarantee that it's currently in a working state. However, as I say, I hope that it is still useful for reference. If we really need to support this platform, we should probably rebuild from the current master using the diffs here as a foundation.

**Comment by demiankatz** [comment]
This PR has grown very stale, and the involved APIs have changed significantly. I am closing this for now; work on a newer version will follow completion of [VUFIND-1588](https://openlibraryfoundation.atlassian.net/browse/VUFIND-1588).

**Pull request closed without merging**
