### PR TITLE
Update facets.js to create HTML for hierarchical facets with jQuery a…

### PR DESCRIPTION
**Pull request by EreMaijala**
…nd with the correct structure. Fix exclude links in hierarchical facets. Display "Loading..." message in hierarchical facets too.

Also fixes style settings that would make a clicked jstree entry invisible since it's not a block element with a background color.

While the HTML creation is a bit more JS code, it's way cleaner and takes care of proper escaping etc.

### CODE REVIEW

**Comment by demiankatz** [comment]
@EreMaijala, how did you compile the LESS for this PR? For some reason, it wasn't working correctly for me, but a quick `grunt less` set everything right.

**Comment by demiankatz** [comment]
@EreMaijala, even with the recompiled LESS, I'm seeing some display problems when I leave the bootstrap3 theme. Here's sandal (note odd white background):

image

Here's bootprint3 (note arrow out of alignment with text):

image

These look better in master (though the Sandal is still a little weird even there).

Is something strange going on on my end, or are there some outstanding CSS problems here? Should we get @crhallberg involved?

**Comment by EreMaijala** [comment]
I'll take a look. I used the old cssBuilder.php script. Locally we use different mechanism so I wasn't aware of grunt.

**Comment by demiankatz** [comment]
@EreMaijala, for the last couple of years, `grunt less` has been the method we use to build the CSS for master. It might not be a bad idea to eliminate the cssBuilder.php at some point, as it appears to have problems with some things. I think if we get rid of that, though, it would also make sense to lose the dynamic LESS compilation, since that's probably subject to the same problems. Not sure if anyone has ever really used it. Thoughts, @crhallberg?

**Comment by EreMaijala** [comment]
@demiankatz I can't reproduce your results with bootstrap3 or sandal. It all looks pretty good apart from a very slight vertical alignment issue with the facet arrow, which I'll take a stab to tweak. I tested with Firefox and Chrome.

**Comment by demiankatz** [comment]
@EreMaijala, I'm still seeing the same behavior (using latest Firefox on Windows). The Sandal glitch appears to only affect selected facets, which perhaps is not clear from my original screen shot. The misalignment and extra padding for bootprint3 still seems to be a problem. Maybe @crhallberg has some ideas about some of this.

Also, it appears that your latest compiled CSS wasn't minified for some reason, so it's possible something is still not quite right with your local grunt setup.

**Comment by crhallberg** [comment]
I can confirm the visual bug that Demian is describing, but it's in the Sandal theming not in anything you have done.

**Comment by EreMaijala** [comment]
Thanks @crhallberg. I pushed a fix for bootprint3 and tweaked the borders a bit to make them look nicer while the facet is loading. Does it work for you now? 

@demiankatz The lack of minification was because I was running `grunt watch` and forgot to run `grunt less` before committing, so nothing more mysterious here. :)

**Comment by demiankatz** [comment]
Thanks, @EreMaijala and @crhallberg -- this looks good to me now, so I have merged it.

Even though this includes a bug fix, I have opted not to backport it to release-4.1 due to the complexity of the changes. I have instead opened https://vufind.org/jira/browse/VUFIND-1279 to document the bug. If anyone really needs this fix in 4.x, we can backport in future, but for now it didn't seem worth the effort.

**Pull request merged**
