### PR TITLE
Pr daia update

### PR DESCRIPTION
**Pull request by olli-gold**
Thats the PR against the VuFind master, which was discussed on finc PR 7

### CODE REVIEW

**Comment by demiankatz** [comment]
Hello,

I just took a closer look at this, and added the new features to the Demo driver so I could test them out. I ran into a few issues:

1.) The locationhref was being used in the AjaxController in a way that simply didn't work. Because the standard AJAX location string is selected by analyzing an array of possible location options, the HREF data gets lost in the shuffle (if it's even there in the first place, which it probably isn't, because we use getStatuses instead of getHolding in this context). Because of all that, it seemed to me easier to simply abandon dealing with HREF in this context. If somebody wants linked locations, they can turn on show_full_status!

2.) The locationhref was not appearing on the holdings tab because there's some intermediate code that rearranges the data returned by the ILS driver. I made that code aware of locationhref, and now it's working fine.

3.) I made a few minor optimizations/formatting adjustments. I just can't help myself!

4.) I think the limitation feature may need more work. Just displaying a free-text string without context seems potentially problematic. At least, it doesn't look very good on my screen (especially when I'm logged in and have hold, ILL and storage retrieval links between the status message and the limitation message). I'm not sure how best to address this -- but maybe if you could share some realistic sample limitation messages, that would help me get a better feel for how this is really being used.

In any case, I think the locationhref stuff is fine even if limitation needs more work. If you would like me to merge that portion to master while we work through the limitation issue, I could do that pretty easily.

**Comment by olli-gold** [comment]
Thanks for all of the corrections. And sorry for all the work I am causing... Well, sometimes I feel that my suggestions are not making anything better...

For us, the display of the location in the result list via AJAX is working, but I have tested only our (customized) configuration and obviously did not focus enough on other possible configurations. Sorry about that.

Limitation messages are being used, if an item is not available right now, but has limitations to get it.

We are using limitation messages for
* items, which are on loan (to display the duedate)
* items, which are not available for loan (presence use only)

They could also be used for
* items, which are stored in our closed stack (to display, that they have to be ordered)
* items, which are on permanent loan (to indicate that they have to be requested in a special way)

Does that help to get a better understanding about the purpose of limitation? If not, I could share some screenshots or links to our TUBfind, where we are using limitation messages (but please note, that the production system of TUBfind is still a VuFind 1.x).

**Comment by demiankatz** [comment]
No need to apologize! It is always good to collect more use cases and try to add as much flexibility as possible! As for the AJAX availability, there are so many code paths it is quite difficult to test thoroughly.

Thanks for the clarification on limitation messages. I'm still not sure how best to handle this. The ILS driver already supports a duedate field for due dates, so perhaps an ideal situation would be to use duedate for due dates, and some other field for different types of messages. I still feel like a more generic field such as notes might be just as appropriate -- if our goal is to display a note next to an item in the list, it doesn't necessarily matter from the code's perspective what the meaning of that note is... unless we want to be able to style different notes different ways. However, the problem with the existing notes field is that the information is collated at the location level, and for these things we want the notes at the item level. So another possibility would be to add an item_notes field that gets displayed as part of the item line.

I also realize that it's probably not easy (maybe not even possible) to differentiate due dates from other messages when building the response... but if it could be done, it might be useful. And perhaps you still prefer having a specific limitation field. I'm just trying to think of a model that's as open-ended and flexible as possible so that other ILS drivers can perhaps utilize it in slightly different ways as needed.

What do you think? Any new ideas based on that brainstorming?

**Comment by olli-gold** [comment]
Well, I guess I need a little bit more time to think about this a little bit more. Perhaps your idea to use the generic notes field for such messages is really sufficient. I'll experiment a little bit with that and try to figure out, what could be the best solution, by trying it. I'll push a note here when I make progress.

**Comment by demiankatz** [comment]
Thanks for continuing to think about this. In the meantime, I've merged the locationhref functionality to master, since I believe we're in agreement that it is ready to go. Thus, we can focus on resolving the limitation issue here (or simply close this, if you determine that you don't need it... though I suspect we'll at very least need an item-level note field to meet your needs, since the existing notes make it impossible to tell which note goes with which item when you have multiple items at the same location).

**Comment by demiankatz** [comment]
An alternative to an item-level note field might be a configuration setting to control whether notes are aggregated at the holding level or displayed at the item level -- that might actually be better, unless we have a situation where some notes go in one place and other notes go in the other....

**Comment by olli-gold** [comment]
I have thought about that and have come to the closure, that we don't need the special limitation field. I have prepared a item-level note field instead, but perhaps this is worth a new PR. Another issue in relation with that is how to display items, which are for presence use only. We want to display that in the result list (if only presence-only items are available) and also for every item in the full record view. I have put this into the generic notes field right now, but perhaps this would be worth to get a seperate field (e.g. a method isPresenceOnly in the driver specification)?

**Comment by demiankatz** [comment]
I think it probably makes sense to start a clean pull request for the new approach, since there's a lot of unnecessary history on this one at the moment. Please feel free to close it once you've opened a replacement.

Regarding display of "presence use only" are you able to address that issue by switching to the full status mode (show_full_status = true in the [Item_Status] section of config.ini)? Are you proposing adding another mechanism to the basic mode? I'd prefer to avoid making the basic mode more complicated -- right now the idea is that you can use that for simple needs and switch to full view for more complex ones. It may be worth considering a more comprehensive redesign of the basic mode, but I'd rather view that as a larger refactoring rather than hacking new features onto the existing mechanism.

**Comment by olli-gold** [comment]
I'm closing this PR as I have opened the new one on #469.

The "presence use only" label is another issue, that we can continue discussing at the new PR. I think show_full_status is not sufficient, because our goal is to show only one item information in the short list.

**Pull request closed without merging**
