### PR TITLE
[VUFIND-1683] Label drop-downs for deleting lists/library cards

### PR DESCRIPTION
**Pull request by demiankatz**
Also includes a more button-like appearance for library card edit/delete controls, to improve alignment with drop-down.

TODO
- [x] Resolve [VUFIND-1683](https://openlibraryfoundation.atlassian.net/browse/VUFIND-1683) when merging

### CODE REVIEW

**Review by sturkel89 — APPROVED** [review]
The test branch improves on the behavior of Library Cards. 

In dev, the Edit and Delete options in Library Cards appear as text. In test, these options are clearly buttons.

**Dev example**


**Test example**


Further, the dropdowns on dev simply offer Yes or No as options. On test, there's contextualizing text: **Delete Library Card? Yes / No**



This feature looks good in all themes. I think it's ready to merge.

-----
### Side note
In testing this branch, I noticed a theme-related issue that's not specific to this PR. In the two new themes, the clickable options in dropdowns don't have underlining, while these options all have underlining in the legacy themes. I see it across the My Account areas and in record view (e.g., Export options). 

Every other clickable thing that isn't clearly a button or in the top row of the very top of the screen in the new themes **is** underlined, indicating that it's a link. Should I make a JIRA ticket?

Sandal example:


Sandal5 example:

**Comment by demiankatz** [comment]
Thanks, @sturkel89! Regarding your observation, I'm not sure if the underlining is strictly necessary in the drop-down, since it's a specialized control, and its purpose should be pretty clear from context. I don't think we necessarily need extra signaling to indicate that the answers are clickable. By that reasoning, the change is an improvement, and no further action should be needed.

Of course, I'm not an accessibility expert, so more opinions might be worth soliciting. We could start by asking @crhallberg what he thinks....

**Comment by sturkel89** [comment]
My only thought is that we have the underlines in those places in all the legacy themes, so for consistency I thought we would want them in the new themes.

**Comment by demiankatz** [comment]
> My only thought is that we have the underlines in those places in all the legacy themes, so for consistency I thought we would want them in the new themes.

The question, though, is whether the change is a conscious improvement or an accidental regression. I don't know the answer to that question. :-)

**Pull request merged**
