### PR TITLE
[VUFIND-1640] Eliminate submit inputs named "submit"

### PR DESCRIPTION
**Pull request by demiankatz**
This PR renames all submit inputs named "submit" to "submitButton." This is necessary because using the name "submit" overrides the containing form's submit() method, which can lead to unexpected behavior.

Many of these inputs probably do not need to be named at all, but I left the names in place since it may be helpful for automated testing or other reasons in future. However, I would not object to a follow-up PR to eliminate unnecessary input names if someone felt the urge to work on that.

TODO
- [x] Run complete test suite
- [x] Resolve [VUFIND-1640](https://openlibraryfoundation.atlassian.net/browse/VUFIND-1640) when merging
- [x] Update changelog when merging

### CODE REVIEW

**Comment by demiankatz** [comment]
@sturkel89, do you mind testing that CAPTCHA functionality still works correctly for compatible features? We have automated tests for feedback forms and comments, but everything else could use some manual testing.

To set it up, just uncomment the `[Captcha]` section in config.ini, and set `types[]` to `demo` and `forms` to `*`. This will turn on the demonstration Captcha mechanism for all compatible forms. The demonstration Captcha mechanism can be resolved by typing "demo" in the box; any other input will fail validation.

Here are the things to test:

  * Creating an account
  * Changing email address (requires `change_email = true` in config.ini)
  * Changing password (requires `change_password = true` in config.ini)
  * Sending an email
  * Recovering a forgotten password (requires `recover_password = true` in config.ini)
  * Sending a text message

My recommended test for each method would be to try to submit a bad Captcha value, confirm that you get an error; then submit the correct value and confirm that the process works as expected.

Note that many of these mechanisms are designed to send messages when successful. You should set the testOnly setting to true in the [Mail] section of config.ini to disable outgoing emails by default (since we don't want tests to generate real messages). Do not be alarmed about the fact that you will not receive actual messages as a result of your tests. As long as the user interface reports that it sent a message, that's good enough for the purposes of this test process.

**Review by sturkel89 — APPROVED** [review]
I tested captcha on this branch. Here are my findings:

**Creating an account**
- With a bad captcha, I get a red error banner “CAPTCHA not passed”
- With a good captcha, the account is created.

**Changing email address** 
- With a bad captcha, I get a red error banner “CAPTCHA not passed”
- With a good captcha, I get a green confirmation banner “Your email address has been changed successfully”

**Changing password**
- With a bad captcha, I get a red error banner “CAPTCHA not passed”
- With a good captcha, I get a green confirmation banner “Your password has successfully been changed”

**Sending an email**
- With a bad captcha, I get a red error banner “CAPTCHA not passed”
- With a good captcha, I get a green confirmation banner “Message sent.”

**Recovering a forgotten password** 
- With a bad captcha, I get a red error banner “CAPTCHA not passed”
- With a good captcha, I get a green confirmation banner “Password recovery instructions have been sent to the email address registered with this account.”

**Sending a text message**
- With a bad captcha, I get a red error banner “CAPTCHA not passed”
- With a good captcha, I get a green confirmation banner “Message sent.”

I think everything is working as it should be. Approved to merge!

**Comment by demiankatz** [comment]
Thanks, @sturkel89! I'm pretty confident this is safe to merge now, but I'm going to see if @EreMaijala has any technical concerns about my approach before I hit the button. :-)

**Review by EreMaijala — CHANGES_REQUESTED** [review]
Since this is a disruptive change, could we leave 'submit' as a fallback name for the submit button for now (deprecated, to be removed in version 11)? This would make it possible to upgrade without having to change everything simultaneously.

**Comment by demiankatz** [comment]
> Since this is a disruptive change, could we leave 'submit' as a fallback name for the submit button for now (deprecated, to be removed in version 11)? This would make it possible to upgrade without having to change everything simultaneously.

Is c4b977bcf2b8cfb2749e364daa426fb5623ee12a what you had in mind?

**Review by EreMaijala — APPROVED** [review]
Yes, now this looks great to me!

**Comment by demiankatz** [comment]
Thanks, @EreMaijala!

**Pull request merged**
