### PR TITLE
Solr 4.10.4 upgrade

### PR DESCRIPTION
**Pull request by demiankatz**
This PR tracks the changes necessary to upgrade to the latest Solr release.

### CODE REVIEW

**Comment by demiankatz** [comment]
... and Solr 4.10.4 has already been released since the creation of this PR!!

**Comment by lahmann** [comment]
Demian, when testing this branch I get the following error:

```
ERROR [main] (MarcImporter.java:379) - Unable to index record 0013331514 (record count 1) -- Error while trying to evaluate script: dewey.bsh
java.lang.IllegalArgumentException: Error while trying to evaluate script: dewey.bsh
	at org.solrmarc.index.SolrIndexer.handleScript(SolrIndexer.java:1170)
	at org.solrmarc.index.SolrIndexer.addFieldValueToMap(SolrIndexer.java:914)
	at org.solrmarc.index.SolrIndexer.map(SolrIndexer.java:821)
	at org.solrmarc.marc.MarcImporter.addToIndex(MarcImporter.java:398)
	at org.solrmarc.marc.MarcImporter.importRecords(MarcImporter.java:312)
	at org.solrmarc.marc.MarcImporter.handleAll(MarcImporter.java:605)
	at org.solrmarc.marc.MarcImporter.main(MarcImporter.java:865)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.simontuffs.onejar.Boot.run(Boot.java:334)
	at com.simontuffs.onejar.Boot.main(Boot.java:170)
Caused by: Typed variable declaration : Class: DeweyCallNumber not found in namespace : at Line: 37 : in file: inline evaluation of: ``/**  * Custom Dewey call number script.  *  * This can be used to override built . . . '' : DeweyCallNumber 

	at bsh.BSHAmbiguousName.toClass(Unknown Source)
	at bsh.BSHType.getType(Unknown Source)
	at bsh.BSHTypedVariableDeclaration.eval(Unknown Source)
	at bsh.BSHBlock.evalBlock(Unknown Source)
	at bsh.BSHBlock.eval(Unknown Source)
	at bsh.BSHBlock.eval(Unknown Source)
	at bsh.BSHWhileStatement.eval(Unknown Source)
	at bsh.BSHBlock.evalBlock(Unknown Source)
	at bsh.BSHBlock.eval(Unknown Source)
	at bsh.BshMethod.invokeImpl(Unknown Source)
	at bsh.BshMethod.invoke(Unknown Source)
	at bsh.BshMethod.invoke(Unknown Source)
	at org.solrmarc.index.SolrIndexer.handleScript(SolrIndexer.java:1149)
	... 12 more
```
Do you have any idea what might be the problem?

**Comment by demiankatz** [comment]
Do you get the same error if you try against the current master? I think Tod did some work on those .bsh files fairly recently, so I wonder if this is a problem totally unrelated to the Solr upgrade.

**Comment by lahmann** [comment]
Yes - the current master gives the same error: the current marc.properties does not use the dewey.bsh at all, so when using dewey.bsh as provided in marc_local.properties this error is thrown.
Sorry, to spam this pull request - this issue is probably better handled in a jira-ticket.

**Comment by demiankatz** [comment]
Okay, I've resolved your JIRA ticket and merged the fix to this branch. I was correct that Tod had done some work, but I misremembered where that happened -- he fixed some issues in the SolrMarc trunk, but those updates had not been merged into VuFind yet. I took care of that, so all should now be well.

**Comment by demiankatz** [comment]
If you have local customizations to dewey.bsh, though, you may need to do some merging... but that's a separate matter!

**Comment by lahmann** [comment]
Thanks for the quick fix! I just tested the updated `solr-upgrade` branch successfully!

**Comment by demiankatz** [comment]
Great news! Hopefully that means we'll be able to merge shortly after next week's dev call.

**Comment by demiankatz** [comment]
Manually merged to master.

**Pull request closed without merging**
