### PR TITLE
Fix first/last navigation.

### PR DESCRIPTION
**Pull request by EreMaijala**
Separates record page first/last navigation setting from backend support for first/last navigation by improved naming of the variable and method. Also adds flag about support for first/last navigation in results to the Options class so that it works properly with JS results and doesn't need to be set in a backend-specific template.

Spin-off from #3391.

TODO
- [x] Update changelog and next release deprecation cleanup JIRA ticket to account for deprecation of `supportsFirstLastNavigation()` and removal of `firstlastNavigation` property.

### CODE REVIEW

**Review by sturkel89 — CHANGES_REQUESTED** [review]
I checked out this branch and tested it in all three themes. The desired functionality is in place for the **results page paginator**: the first/last numbers in brackets are present at all the times they're supposed to be present. Looks good!

However, I'm finding that the **paginators in Checked Out Items and Loan History** now are displaying disabled links, and are showing the words "First" and "Last" inside the "Previous" and "Next" arrow/buttons instead of showing [1] and [4] outside those arrows:

image

I think we want the paginators in the My Account area to have the same appearance as the results page paginator, if possible.

**Comment by demiankatz** [comment]
Thanks, @sturkel89! I believe that the "My Account" improvements you refer to are part of #3391 but aren't included here. Once this is approved and merged over there, I think we'll have the best of all worlds.

**Review by demiankatz — APPROVED** [review]
Looks good to me; thanks, @EreMaijala!

**Review by sturkel89 — APPROVED** [review]
Changing my review to Approve! :)

**Pull request merged**
