### PR TITLE
email exported favorites as file attachement

### PR DESCRIPTION
**Pull request by mbeh-ub**
Hi, 
according to the conversation von the mailing-list ([VuFind-Tech] E-Mail Favorites as File-Attachement)
I implemented a prototype which shows how such a function could be implemented.

I think the asynchronous solution is desirable but in combination with caching it should also be
resasonably fast in the synchronous case.

Greetings 
Markus

### CODE REVIEW

**Comment by mbeh-ub** [comment]
This example should at least work for the formats RIS, BibTeX and URL

**Comment by demiankatz** [comment]
Thanks for sharing this. At a glance, this looks like an excellent start. I haven't actually tried this in action, though -- I notice you have some hard-coded email addresses in email-form-fields.phtml. Were these committed by accident? If you can clean that up, I can give it a test drive in the near future. Thanks!

**Comment by mbeh-ub** [comment]
Hi, I removed the hard-coded addresses (I used them for easier testing :-)).

**Comment by demiankatz** [comment]
Thanks! I've just updated this to resolve the conflicts with master.

Some more comments/questions:

1.) I see you've added a mechanism for specifying filename and extension, but this overlaps with the existing Content-Disposition headers. Do you think it would make sense to either remove the Content-Disposition headers and replace them with a new filename setting that is used to create Content-Disposition headers dynamically, or do you think it would make sense to modify the getFilename method to extract the name from the Content-Disposition header, if found? Is there really a need for a separate extension setting? Why not just have a filename setting and extract the extension from there in the code?

2.) I see that you've put the email configuration in the [BulkExport] section, but it seems to apply to single exports as well. Would it make more sense to put an AllowEmail setting in export.ini at the format level and not worry about separating bulk behavior? (I'm not sure if there's a context where somebody would want this feature on bulk but not single or vice versa).

3.) It doesn't make sense to enable emailing for redirect-based exports like EndNoteWeb or RefWorks. It looks like the user ends up receiving an email with the export data that's supposed to be retrieved by the third-party service through a callback. The user won't know what to do with that.

4.) Your `if (true):` in email-form-fields.phtml should perhaps be adjusted to `if (is_array($this->emailFormatOptions)):` to avoid errors caused by running foreach on an undefined value in email contexts where this value is missing.

5.) I wonder if we should deal with the URL special case differently. Do we need a configuration setting for this? Is it better to just have URL always on by default as a fallback if no other valid options are found? This just feels like it may be able to be simplified.

In any case, the general idea is sound, and it seems to be working pretty well -- we just need to polish it up a little bit so it can be merged to master. Thanks for working on this!

**Comment by mbeh-ub** [comment]
Hi, I'am have been working on another pull request, which I posted quite recently (bulk-actions-for-all-list-items). I will come back to this one soon...

**Comment by mbeh-ub** [comment]
Hi Demian, I worked on 1) and updated the code to extract the mime-type and filename form the headers. I think it is the more flexible way to specify the headers and extract the filename and mime-type (although it is a bit fuzzy, because I have use a regular expression to parse a simple string). 

On Point 3) and 4) I agree with you. EndNoteWeb and RefWorks should be disabled by setting the
appropriate config-setting. Point 4) is simply a bug.

To 2) I'm not sure about where to put the options. Export.ini also sounds good, but I have to have a second thought on this.

I hope to make progress in near future and give you more feedback.

PS: Thank you for the always fast and deep feedback. Its very motivating!

**Comment by demiankatz** [comment]
Thanks. This sounds like a good step in the right direction. I'll wait on further review until you have finished the rest of your progress, but please let me know if you'd like my input in the meantime, and I'll try to find some time. I'm glad you find my feedback useful -- thanks for taking it under consideration.

**Comment by mbeh-ub** [comment]
I mulled over 2). What do you think if we extended the possible values in the [Export] section of config.ini. Instead of true/false we could specify the context in which the export format could be used. E.g: 

[Export]
...
RIS: record, bulkExport, email
BibTeX: record, bulkExport, email
...

As a consequence the [BulkExport] section won't be needed anymore.
BUT: I'am not sure if we get a problem with backward compatibility if we change that. 
And if this is a too deep intervention for this small new option.

What do you thing?

**Comment by demiankatz** [comment]
I like this idea. I think we could implement this in a backward-compatible way. If an Export setting is true or 1, that equates to "record". Otherwise, we parse the string to check the options. If a [BulkExport] section is defined, we can still factor that in, but perhaps issue a deprecation notice. We can also make the upgrade script convert [BulkExport] settings.

Perhaps it would make sense to open a separate pull request for fixing up the export settings first, and then continue work on this after that is done... that will prevent this PR from getting overcomplicated. What do you think? Are you interested in putting something together? I'm willing to do it but probably won't have a chance for a couple of weeks.

**Pull request closed without merging**
