### PR TITLE
Added support for tracking combined searches in Piwik so that they do…

### PR DESCRIPTION
**Pull request by EreMaijala**
…n't get reported in "no results".

This is still not perfect in that only results loaded synchronously are taken into account, but if there are only AJAX-loaded results, the count is reported as false which Piwik should treat as "not known". I'm not sure if this is better than always reporting "not known" if there are AJAX results so any feedback is appreciated.

### CODE REVIEW

**Comment by demiankatz** [comment]
I guess part of the question here is whether we want to count a combined search as a single query with a single result count, or if we want to treat it as a whole set of independent searches. Either way, I guess there are a few possible approaches:

1.) Treat it as a single number, and ignore all the AJAX results (which seems to be the current approach)

2.) Treat it as a single number, but incorporate the AJAX results (which may or may not actually be technically feasible)

3.) Treat each search independently

If we go to option 2 or 3, we need to do something about the AJAX requests. Is there some possibility that we could adjust the combined search AJAX loader to trigger an event that the Piwik code could attach a hook to? If we trigger an event containing a result count, then event handler code could hook that and either add to a running total until all expected results have come in (scenario 2) or stash a separate statistic for each result (scenario 3).

Scenario 2 has the advantage of maintaining a more realistic history of user behavior (after all, the user only performed one search) but the disadvantages of non-granular data and the possibility that the data will not be recorded at all (if the AJAX load is slow and the user clicks through before everything has been collected).

Scenario 3 has more granular data which is likely to be more useful/meaningful in search analysis, and it also is less vulnerable to the "user clicks through before being tracked" scenario... but it will artificially inflate search numbers.

Thoughts?

**Comment by EreMaijala** [comment]
As far as I can see scenario 2 is not viable due to the possibility of the search not being tracked at all. I'm not sure about preference with regards to scenario 1 or 3. I think it boils down to the question of what we want to record with the statistics. If it's user actions, then 1 is more appropriate, but if it's more about what the user sees, then maybe 3. The upside with scenario 1 is that it's tracked as a combined search so you can find out how much combined search is being used, and you could also expand search counts by multiplying it with the numbers of columns. With scenario 3 that's not possible unless we use another custom variable to denote a combined search (and even then I'm not sure if Piwik UI allows you to handle that in a meaningful way).

**Comment by duspal** [comment]
From a personal standpoint, I would find option 3 more informative (I'm interested in user experience and tracking down potential issues rather than statistics and user actions) but Piwik is designed top down with tracking user actions in mind, so option 1 seems to be more in line with Piwik's raison d'etre.  If we want to keep to standard across Piwik, option 1 seems to be the logical choice.  Given that however...

...we're trying to fit a complex peg (search platform with Ajax calls and "bento box" search capacity) into a more simplistic hole.  The Piwik search statistics works great on easier examples (basic WordPress search box?  Works great!).  The problem here I see is as follows:  in option 1, I get useless information (aka a whole mess of "not found" searches) BUT the information is obviously useless so it won't trick anyone into misinterpriting it.  In option 3, if we do a search for something, and we get hits on 3 of our five Ajax calls, it looks like it was searched five times, but shows up as not found twice.  More useful information, but you have to know how to interprit it or you can make some grossly wrong assumptions.

I'm not sure the statistics on how many people use VuFind in combined search mode.  Maybe that will answer the question for us (aka why add a complicated, potentially confusing fix in for 5% of the population...)

**Comment by duspal** [comment]
Another thought:  can we add the search type in front of the result before sending it into Piwik (aka mark is as "combined search:jstor" (or via its search id ("library resources:jstor" "other libraries:jstor", etc for each bento box).  If we can, we're back to the question from above, which is which one is more useful, option 1 or option 3.  Again, I find the latter more useful since I'm interested in user experience, but the former falls more in line with Piwik's standard and gives more user story information.

Split the difference and add a configuration setting?

**Comment by demiankatz** [comment]
I like the search prefixing idea for clarity. I'd use the search backend ID (Solr, Summon, etc.) for greater clarity... though this brings up the question of whether we use a "fake" backend ID for combined search (which fits better with my "scenario 1" above) or whether we always use real backend IDs (which would only be compatible with my "scenario 3").

The only obvious disadvantage to prefixing searches is that it makes it harder to measure trends for specific keyword searches across multiple backends -- and that might be a problem for some... but given the way the data is being presented, I think differentiating leads to clearer results than consolidating. It's very strange to see the same search term on both the "hits" and "no hits" lists for no discernible reason.

(And sorry if I'm just repeating things that Dave already said -- just trying to add clarity).

**Comment by EreMaijala** [comment]
So, to sum it up, would the following be a working solution for everyone:

Use option 1 (treat combined search as a single number) and prefix search terms with the backend ID.

I'm going to update this PR for the above, but feel free to offer an opinion anyway.

**Comment by demiankatz** [comment]
If I understand correctly, this sounds reasonable to me. Is the idea that for single search, we'll use the backend ID as the prefix, and for combined we'll use "combined" as the prefix? The biggest potential problem is that combined results may still throw false positive "no results" entries because of the AJAX processing... but if they're all prefixed, that may not be such a big problem... or else maybe we should consider omitting combined from the "no results" tracking since it is a special case that behaves differently.

Regarding a delimiter, we use pipe (|) when we put a backend ID on the front of an ID, so that might be a logical option.

**Comment by EreMaijala** [comment]
You understood it correctly. We can omit result count when tracking combined search with AJAX results, so it doesn't even pretend to know the result count.

**Comment by demiankatz** [comment]
That sounds like a reasonable approach to me!

**Comment by EreMaijala** [comment]
Here goes. The ugly part is where the backend id is parsed from the Results object's class name since it seems there's no easy way to get a backend id from the Results class. Please correct me if I'm wrong!

**Comment by demiankatz** [comment]
You can get the backend ID from the options object, which you can get from the results object: `$results->getOptions()->getSearchClassId()`.

**Comment by EreMaijala** [comment]
Thanks, of course, now fixed!

**Comment by demiankatz** [comment]
Finally had a chance to test this out, and it looks great. Thanks again for all the work on this one!

**Pull request merged**
