### PR TITLE
Validate MultiILS login target.

### PR DESCRIPTION
**Pull request by EreMaijala**
This doesn't show up unless you have a buggy template or you modify the login target option before sending it, but should be guarded against in any case. 

Note: not really a vulnerabiliity since you would still need to have valid credentials for the given target.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @EreMaijala. It looks like we don't currently have a test class for this module. Is it feasible/worthwhile to establish a MultiILSTest to cover this new code? (Not expecting a full test class, but perhaps we could at least cover what has changed).

**Comment by EreMaijala** [comment]
@demiankatz Makes sense. I'll work on some initial tests.

**Comment by EreMaijala** [comment]
@demiankatz Needed quite hefty plumbing to get things working, but basic tests now implemented.

**Review by demiankatz — APPROVED** [review]
Thanks, @EreMaijala, you've gone above and beyond on the testing. :-)

**Pull request merged**
