### PR TITLE
Prevent result list from jumping to the top (due to link href "#")

### PR DESCRIPTION
**Pull request by powerriegel**
Without my fix, the result list always jumps to the top because the links href to "#" (same page). With my fix, adding/removing to/from cart still works but there is not link being followed.

### CODE REVIEW

**Comment by demiankatz** [comment]
@powerriegel, what browser/VuFind version/config settings are you using where you are seeing a problem? I can't reproduce this at the moment, but there are a lot of variables, so I'm probably just not looking in the right place. I just want to recreate the issue so that I can test the solution.

**Comment by powerriegel** [comment]
Firefox 59.0.2 on Ubuntu 18.04. I'm using VuFind 4.0. Yeah, there are lot's of variables but if there is no `preventDefault()` any browser follows the link, which causes a reload of the page.

**Comment by powerriegel** [comment]
On https://vufind.org there is no `href` attribute on these links. Links without href are no links anymore they must be styled manually. One should then switch to`<button>` elements.

**Comment by demiankatz** [comment]
@powerriegel, which template is defining the buttons that are causing the problem for you? I just set up an instance of v4.0 on an Ubuntu server and accessed it through Firefox, but I'm still not seeing the behavior you describe. The embedded cart add/remove buttons in the search results work correctly, without jumping to the top of the page. Also, looking at the markup, these buttons have no href attributes at all -- which leads me to wonder where you're seeing the # href. Is it possible I'm still looking in the wrong place?

In any case, I imagine the preventDefault behavior is still sensible -- but I want to see the problem occur, and then see this code change fix the problem, to be confident it's the right fix in the right place for all cases. Perhaps @crhallberg has some comments to add as well.

**Comment by powerriegel** [comment]
Seems we are not using the default template here. You're right `record/cart-buttons.phtml` never had a `href`. We might have that code copied from an older version of VuFind. 

You might close the PR.

**Comment by demiankatz** [comment]
Thanks for the confirmation! I'll wait to see if @crhallberg feels that this is a useful safety measure and/or is interested in converting `a` tags to `button` tags. Once that conversation is complete, we can merge or close accordingly.

**Comment by crhallberg** [comment]
I certainly don't see any harm to having this. Might help other libraries with customization and the option of having hrefs on these "link" buttons might be better for checkstyles.

**Comment by demiankatz** [comment]
I agree that this seems like a harmless enhancement that may have some benefits in the future. The only problem is that, as written, it will break IE8 and earlier. I don't know how much we care about IE8 at this stage, but we should have a discussion about browser support and decide whether to revise this in an IE8-compatible way or make a formal statement about dropping IE8 support. I'll put this on the next dev call agenda.

(I realize that this is a lot of discussion and debate over a very small pull request -- but it's a case of a simple fix bringing up larger issues that merit conversation!)

**Comment by ckaz** [comment]
We had quite some issues in the past with keeping website and catalog backward compatible but decided to drop support for IE8 and earlier about one year ago. For two years we had an "old browser -- please update" type detection and warning. We then decided IE8 was a danger to its users and everyone else and not to care about it anymore. We had no complaints. 
Anyone who has ever tried navigating the web with IE8 these days is bound to agree that it is no fun using it. Many sites appear broken and there are free alternatives. So we have no issues with dropping support for old browsers.
Cheers, Claas

**Comment by powerriegel** [comment]
We dropped support, too. We use this script, that users should update their browser: http://browserupdate.org/
IE8 was the best version on Win XP which is su much outdated that no one should use it anymore. 

Maybe there are more `a` elements without href in VuFind?

**Comment by demiankatz** [comment]
I've added a fairly open-ended browser support statement here:

https://vufind.org/wiki/installation:requirements

**Pull request merged**
