### PR TITLE
Centralized JS initialization

### PR DESCRIPTION
**Pull request by crhallberg**
A pass at having modules register with the VuFind object and initialize at the same time.

### CODE REVIEW

**Comment by demiankatz** [comment]
Looks good to me. I'll give @EreMaijala a chance to review this before merging, however.

**Comment by EreMaijala** [comment]
Looks good to me. The only other thing I'd do to clean things up is to move any code from the revealing return statements of the module into methods so that e.g. the one in cart.js would look like this:

    // Reveal
    return {
      // Methods
      addItem: addItem,
      removeItem: removeItem,
      getFullItems: getFullItems,
      updateCount: updateCount,
      setDomain: setDomain,
      init: init
    };

**Comment by crhallberg** [comment]
How does that look?

**Comment by demiankatz** [comment]
Looks cleaner to me.

**Comment by crhallberg** [comment]
Merged in by hand after tests passed.

**Comment by demiankatz** [comment]
Thanks, Chris!

**Comment by crhallberg** [comment]
`git merge --squash branch` is a good shortcut for how you normally reduce PR logs, Demian. It loads all the file changes and stages them so you just need to commit.

**Comment by demiankatz** [comment]
Very good to know!

**Comment by crhallberg** [comment]
It also has GitHub add a "Delete Branch" button apparently! That was handy!

**Comment by demiankatz** [comment]
Yep, that one's been around for a while, actually!

**Pull request closed without merging**
