### PR TITLE
Enable search with solr parameter facet.contains

### PR DESCRIPTION
**Pull request by liowalter**
Using facet.contains is useful when doing autocomplete based on facet counts. It makes it possible to restrict the suggestions to facet labels that match the query.

Does it make sense to add this to vufind ?

Thank you !

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @liowalter, this seems like it could be a useful addition. When I'm a little more caught up with pull requests, I'll give this a closer look and see if I have any suggestions for adjustments.

**Comment by demiankatz** [comment]
@liowalter, I've had a chance to review this more closely, and it seems reasonable to me. I've just made a minor style correction to hopefully get the Travis build to pass. Before I merge this, do you have a custom autocomplete module that uses this functionality and might be worth sharing, or would you like me to merge the basic capability now and wait until later to add something that makes use of it?

**Comment by liowalter** [comment]
Dear @demiankatz, I am working on a custom autocomplete right now : https://github.com/swissbib/vufind/blob/feature/better-autosuggest/module/Swissbib/src/Swissbib/VuFind/Autocomplete/SolrAuthorSuggester.php. But the work isn't finished yet. Therefore, I think you can already merge this. Thanks !

**Comment by demiankatz** [comment]
Thanks, @liowalter, I'll merge this now and will await the autocomplete tool when time permits!

**Pull request merged**
