### PR TITLE
[VUFIND-1508] Improve version number processing during upgrade.

### PR DESCRIPTION
**Pull request by demiankatz**
TODO
- [x] Resolve JIRA ticket when merging

### CODE REVIEW

**Comment by demiankatz** [comment]
When testing 8.0.1 I found that there are still problems with the naive version-to-float conversion being done in the upgrade controller. This PR is an attempt at making everything smarter and more consistent. What do you think, @EreMaijala?

**Review by EreMaijala — COMMENTED** [review]
How about switching to https://packagist.org/packages/composer/semver? I understand that we currently only have it as a dev dependency via php-cs-fixer, but it's a small library and it can handle any semantic version properly.

**Comment by demiankatz** [comment]
Good idea, @EreMaijala; I've just revised this accordingly.

**Review by EreMaijala — APPROVED** [review]
While I can't really test this, the code looks good to me.

**Comment by demiankatz** [comment]
Thanks, @EreMaijala! The Config\Upgrade code has pretty good unit test coverage (I confirmed that intentionally implementing the Comparator code incorrectly causes broken tests), and I also manually tested the web-based upgrade to make sure it blocks invalid version numbers appropriately and allows expected legal ones. I think we're ready to merge!

**Pull request merged**
