### PR TITLE
Solr 5 upgrade

### PR DESCRIPTION
**Pull request by demiankatz**
This PR upgrades VuFind to use Solr 5.3.0.

TODO:
  - [x] Fix browse handler
  - [x] Decide what to do about vufind.sh (do we still need it, given solr/bin/solr?)
  - [x] Decide which files to bundle (should we delete unused contrib/dist files, etc.?)
  - [x] Decide where to put VuFind-specific configs/cores (is solr/server/solr the best place?)
  - [x] Test Windows support
  - [x] Make logging go to the vufind directory instead of the vendor directory
    - [x] Check status of https://github.com/apache/lucene-solr/pull/13 for Windows fix to address location of log files. (Not merged in time for 5.5.0, so JIRA ticket opened: https://vufind.org/jira/browse/VUFIND-1158)
  - [x] Investigate problems with FieldValueCache that cause poor performance in Solr 5.3 (these issues are addressed as of Solr 5.5; see #588 for work in progress on DocValues, though this work no longer seems to be essential)
  - [x] Update vufind.sh references in install script (and anywhere else)
  - [x] Update wiki documentation to address change from vufind.sh to solr.sh and adjustments to solr directory structure.
  - [x] Find fix/workaround for broken MoreLikeThis in Solr 5.4.0 (see https://issues.apache.org/jira/browse/SOLR-8418)
  - [x] Close VUFIND-453 ticket after updating to Solr 5.5 or newer.
  - [x] Consider using edismax instead of dismax by default and closing VUFIND-935 now that underlying Solr bugs related to Extended DisMax are fixed. (Not going to change default for release 3.0 but will consider for 3.1; functionality should work correctly now, however -- just disabled by default until we gain more confidence).

### CODE REVIEW

**Comment by eocarragain** [comment]
Have you considered no longer bundling Solr with VuFind (or at least not with VuFind core)?

It would complicate the install, but users already have to install httpd, mysql, so why not solr? Some of the complexity could be reduced by documentation or scripts/tools which put the necessary components in place. It would also help to explicitly distinguish/document the VF-specific solr files (custom jars, schemas etc), which will actually make it easier to install in a non-standard way (e.g. via chef/puppet etc or in a Solr Cloud configuration etc).   

It would simplify the upgrade process, since you'd just have to specify a minimum supported Solr version for each VF version. It also seems to make sense where a) users have existing Solr instances/clusters (or want to use Tomcat etc.) b) don't use solr at all (Summon only interface etc.)

Anyway, just wondered. Since it would be a big change, the shift from Solr 4.x to Solr 5.x might be a good time to do it if desirable.

Cheers,
Eoghan

**Comment by demiankatz** [comment]
That is definitely something worth considering -- I'm viewing the Solr 5 upgrade as being part of "VuFind 3.0" which gives us freedom to reconsider some basic decisions like what we bundle. If Solr starts to become available as a standard package on common Linux distributions, then the value of bundling obviously goes down dramatically! Even if that doesn't happen, it may be worth considering changing the package-building process so that we can have a "light" distribution as well as a "full" with different amounts of stuff packaged in depending on user needs. (This also ties in to some extent with the ongoing conversation about how to deal with dependencies in the vendor directory).

**Comment by miku** [comment]
Hi,

I just wanted to +1 on Eoghan idea.

> If Solr starts to become available as a standard package on common Linux
distributions,

I remember the reasoning behind the bundling; maybe it would be worth
separating nonetheless. I could imagine creating a deb or rpm of a vufind
specific solr as an intermediate solution as well:

Then, anyone who can install apache2 with apt-get could download
solr-for-vufind-X.Y.deb and install with dpkg.

--martin

**Comment by yarikdot** [comment]
I agree with "lite" and "full" version.

To explain you why - we are currently about to deploy vufind on our servers and we want to have it with some sort of redundancy - either by active-active or active-backup. The point is, we already have a dedicated redudant mysql setup, which we want to use for vufind as well.

At this point, we are about to repackage the debian package to remove the mysql-server dependency, so we can use our existing setup.

**Comment by EreMaijala** [comment]
A couple of suggestions:

- Get rid of vufind.sh or at least rename it so that people don't think they need to restart VuFind to see e.g. template changes (or that restarting it would help in issues unrelated to Solr).
- Put all VuFind-specific stuff in e.g. solr/vufind. That makes upgrading to a newer Solr version easy as Solr distribution files are not mixed with VuFind's files. See https://github.com/NatLibFi/NDL-VuFind-Solr/blob/master/README.md for my quick notes on how I did it)

**Comment by demiankatz** [comment]
Thanks for the suggestion. I wonder if one possible approach to further clarify the separation of VuFind and Solr files would be to have vufind and vendor directories inside the solr directory... drop the installation into solr/vendor, and replace vufind.sh with a solr.sh that wraps the solr scripts inside solr/vendor. This would also simplify the process of building "light" and "full" releases, if we go down that route.

**Comment by demiankatz** [comment]
Another quick update: Mark Triggs is kindly doing some work to get the browse handler working with Solr 5. I'm going to hold off on any directory reorganization until that is completed, as I don't want to pull the rug out from under him while he's troubleshooting.

**Comment by demiankatz** [comment]
Mark has finished his browse handler updates, and that component appears to be working correctly once again. However, we encountered some strange inconsistencies between our respective test systems that we can't entirely explain -- thus, further testing would be useful, if anyone has time to experiment with the updated browse handler.

**Comment by demiankatz** [comment]
I've begun some work on creating a solr.sh to replace vufind.sh (though much more needs to be done to support all the options) and also on reorganizing the solr directory into a "vendor" subdirectory containing the raw Solr distribution and a "vufind" subdirectory containing VuFind-specific configurations and libraries.

This is nearly working, but I'm having some trouble with the browse handler being unable to find the ICU library. Right now, it's possible to resolve the problem by copying `solr/vendor/contrib/analysis-extras/lib/icu4j-54.1.jar` into `solr/vufind/lib` but obviously it should be possible to configure things so the .jar can be found in its proper location. I'll keep working on this as time permits (and will pick @marktriggs' brain in case he has brilliant ideas).

**Comment by EreMaijala** [comment]
The ICU problem may be related to https://issues.apache.org/jira/browse/SOLR-6188. If you get everything to work by copying to solr/vufind/lib, that's already awesome. I couldn't get all of our local libraries to work without copying them to server/solr-webapp/webapp/WEB-INF/lib/ which should only contain the stuff from solr.war...

**Comment by demiankatz** [comment]
@marktriggs seems to have found a workaround -- I'll experiment with it in the near future and post more details when fixes are committed. I don't think it's directly related to SOLR-6188, but it seems that the way Solr is using classloaders can be problematic depending on the order of operations.

**Comment by demiankatz** [comment]
Okay, I have implemented Mark's proposed fix, and sure enough, all is now well. The problem is that I was putting all of the .jar files in a "lib" subdirectory of the Solr home directory. Apparently a "lib" directory in that location gets handled by a different classloader in Solr than directories in any other location that are specified through the solrConfig.xml file. I'm not sure if this exactly qualifies as a bug, but it's highly unfortunate! Fortunately, though, the simple workaround is to rename the "lib" directory to something else (I chose "jars" in this case), and then everything works like it should.

**Comment by demiankatz** [comment]
I'm checking off the "organize files" task, since I'm pretty happy with the solr/vendor, solr/vufind approach. But I remain open to suggestions if anyone thinks we can refine this further.

Next task, when time permits: add more functionality to solr.sh and then remove vufind.sh.

**Comment by demiankatz** [comment]
I've just removed vufind.sh and made solr.sh more robust. Strictly speaking, solr.sh isn't really necessary since it just wraps around the solr/vendor/bin/solr script -- but this offers us a nice way to offer reasonable VuFind-specific default options with some easy overrides for things like port number and heap size. If users want to go to more advanced configurations like SolrCloud, then they can work with solr/vendor/bin/solr directly.

Next task: investigate equivalent changes for the Windows integration.

**Comment by demiankatz** [comment]
Windows support is now working -- and much better than before, since it works more consistently with the Linux equivalent (the process starts in the background now, instead of requiring ctrl-C to terminate).

**Comment by demiankatz** [comment]
Next step: update to 5.3.0, just released last month. Let's see if the upgrade process answers questions about which files to bundle in the "full" version. If we can just download the new release and unpack to the vendor directory, that would be ideal.

**Comment by demiankatz** [comment]
5.3.0 upgrade in progress -- seems to be working when run manually under Windows, but currently encountering some problems with the Phing tasks under Ubuntu. Will investigate further in the near future.

**Comment by demiankatz** [comment]
On the "which files to bundle" question, it looks like we should be able to make drop-in vendor directory upgrades possible, in which case we might as well bundle everything for the sake of simplicity. Obviously, for a "lite" version, we should investigate a dependency management option that allows us to load the appropriate Solr version on the fly instead of having to commit it all to Git.

**Comment by demiankatz** [comment]
I believe that 5.3.0 is now working correctly. Some complications were caused by the fact that Solr is no longer distributed as a .war file.

Next task: make logging go to the vufind directory instead of the vendor directory.

**Comment by demiankatz** [comment]
Logging now goes to the right place on Linux; some logs are still writing to vendor under Windows, but this appears to be due to a bug in the Windows solr.cmd file and not a problem on our end. If anyone really cares about this, I can probably patch it on the Solr side and submit a pull request.

**Comment by xmorave2** [comment]
Isn't there a typo in solr.bat? 
https://github.com/vufind-org/vufind/commit/42aa295e48568d55e56e3235a0af680b673d67f6#diff-ac5a92f2ae9af8cf29033943b4b54d6bR60

**Comment by demiankatz** [comment]
Thanks for catching the typo. I'm having trouble spelling Solr today for some reason. Fixed now! I don't think that's directly related to the other problem I mentioned, however.

**Comment by demiankatz** [comment]
Manually merged to master.

**Pull request closed without merging**
