### PR TITLE
normalize relator terms in author-modification.bsh

### PR DESCRIPTION
**Pull request by lahmann**
This is a first implementation for normalizing relator terms from author-classification.ini and MARC subfields 4&e (trim, toLowerCase, remove any char fitting POSIX character class `punct`).
It's not properly tested as import-marc.sh throws an exception:

    Target exception: org.solrmarc.tools.SolrMarcIndexerException: Unable to access author-classification.ini

Any clues how to fix that?

### CODE REVIEW

**Comment by demiankatz** [comment]
I'm not seeing that error, but I don't have good data to test with, so I'm not able to do much better at the moment. Perhaps you could share the MARC record that's demonstrating the problem so that I can try again to reproduce the error. Also, I'd recommend ensuring that your VUFIND_HOME and VUFIND_LOCAL_DIR variables are set correctly when running the test (though I'm guessing they are, or else this might actually fail at an earlier stage).

As far as code review goes outside of testing, this looks reasonable to me, though it might make sense to give the normalization functions more descriptive names (like "normalizeRelatorString", etc.) since these functions will eventually be ported into the base SolrMarc VuFind indexer, which has a lot of methods -- so more descriptive names will help with clarity and collision avoidance.

**Comment by lahmann** [comment]
Demian, thanks for the feedback - I got this error because of a typo in the VUFIND_HOME variable, so thanks for reminding me :)

Refactoring the function names is fine with me - done in latest commit.

The normalizer is almost doing what it's supposed to: it trims, puts everything into lowercase and removes characters of punct-class. But it fails on strings with umlauts (eg. `übers`). A simple `System.out.println()` of the strings in question show that from `author-classification.ini` `??bersetzer, ??bers` is read which does not match `u?bers` read from the MARC-record (it should be in both cases `übersetzer/übers` though).
I tried `org.marc4j.util.Normalizer` with all available modes on the strings, hoping that this will fix it but had no success. It's not an issue of `List.contains()` either as I had the same result with comparing via `String.compareTo()`.
So, I am a bit stuck - do you have any ideas? If you want to I can provide you a MARC record for testing.

**Comment by demiankatz** [comment]
I think the problem may have to do with the way Java reads .ini files -- I believe that it expects ISO-8859-1 rather than UTF-8. Is that possibly the explanation? Could you try changing the file encoding to see if that makes a difference?

**Comment by lahmann** [comment]
Changing to ISO-8859-1 results in strings `?bersetzer, ?bers` read from ini-file vs. `u?bers` from the MARC-record. So, that does not fix it :(

**Comment by demiankatz** [comment]
At least part of this is a unicode normalization problem, though there may be multiple factors involved. It looks like the MARC record is representing the umlaut as a separate character that gets composited onto the u, while the .ini file is using the single-character representation of "u-with-umlaut." Oh, how I hate character encoding issues!

My knowledge of Java libraries is not rich as I don't spend a lot of time with them on a day-to-day basis. However, it sounds like java.text.Normalizer might help here (see http://drillio.com/en/software/java/remove-accent-diacritic/) -- however, I don't know if this will be available to the BeanShell by default or if we'll have to do extra work to make it accessible. Doesn't hurt to experiment, though!

**Comment by lahmann** [comment]
Some colleagues and me finally found the solution for this encoding issue:

1) the dev-environment I was using had some locale-misconfiguration which apparently resulted in the system handing the files with the wrong encoding to Java.

2) in `import.properties`  the last line `marc.unicode_normalize = C` needs to be commented in - otherwise the string comparison would fail as the ini-file- and the marc-file-data would be in different formats.

After solving theses issues I can confirm the code is working! :)

Thanks again for your help, Demian!

**Comment by demiankatz** [comment]
Great, thanks for the confirmation!

**Pull request merged**
