### PR TITLE
Default complex filters

### PR DESCRIPTION
**Pull request by olli-gold**
This PR prepares the default_filters option to handle also complex filters as long as they are inside brackets

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks for this! A few comments:

1.) In the searches.ini comment, I'd use the word "parentheses" rather than "brackets" -- "bracket" tends to be more commonly associated with square brackets -- [ / ]

2.) There's some code in Base\Options and Solr\Options dealing with an advancedFilters property that, as far as I can tell, serves no actual purpose.

3.) As you may have seen, the Travis build failed due to some style issues. If you could clean this up, that would be much appreciated!

In any case, this is a great start, and I think you've found an elegant way of differentiating the advanced filters from regular ones. I'll definitely want to do some testing to see how this interacts with various other features, but I'll wait on that until you've had a chance to address this first round of comments. Thanks for the work so far!

**Comment by olli-gold** [comment]
Thank you for your feedback. 

1. No problem, as a non-native english-speaker this kind of correction is more than welcome ;-)
2. Right, the advancedFilters property can be removed.
3. OK, I'll investigate this a little bit more and will try to clean this up.

**Comment by olli-gold** [comment]
Yes - got it ;-)

**Comment by demiankatz** [comment]
Looks good. I've merged this to master, adding a few extra comments in the process.

One limitation: this currently only works for the Solr backend, and it would be nice if we could also add support for Summon, Primo, etc. However, each backend works a bit differently and it will require custom isAdvancedFilter() methods and changes to the construction of the backend parameters to make each case work, so I don't think it's worth investing time developing the code until there is a user who actually needs it.

**Comment by olli-gold** [comment]
Right, integration into other Search backends would be very nice and should be possible. I can perhaps have a look at an integration into the Primo backend, when I come to that topic in our migration process (if nobody else is faster than me).

**Comment by demiankatz** [comment]
Help with Primo would definitely be welcomed. I don't think anybody else is using default filters there, so you'll probably be the first person on the job. These API-based services are challenging, though, because they tend to have a more limited and less expressive syntax than raw Solr. Some compromises will likely have to be made! In any case, let me know if I can be of any further assistance.

**Pull request closed without merging**
