### PR TITLE
Make Solr\Backend::terms() more generic

### PR DESCRIPTION
**Pull request by seboettg**
This makes VuFindSearch\Backend\Solr\Backend::terms() more generic in order to use it for other scenarios. Therefore an adaption of the VuFind\Sitemap\Generator class is also necessary (getIdsFromBackendUsingTerms) to still guarantee the functionality of the Generator class. Includes also a bugfix for VuFind\Search\Factory\AbstractSolrBackendFactory in createConnector method. You may check if unit-tests has to be changed. Unfortunately, I was not able to get the unit tests run.

TODO
- [x] Confirm that Sitemap generation works with new code.
- [x] Update test suite to cover new functionality.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks for sharing this. Since the terms feature is used very little, it's probably not too much of a problem to change its signature. However, did you consider the possibility of approaching this in a more backward-compatible way? It seems to me that by simply adding default values to the existing parameter list and by checking the incoming ParamBag to set default `terms.lower.incl` and `terms.sort` values if those are unset, we could give the calling code greater control over the behavior without changing any existing calls.

I guess it's a question of whether we're willing to deal with a slightly less convenient parameter order in the interest of legacy compatibility. As I say, I think it may be safe to make a breaking change here, but at the same time, I've said that in the past and regretted it, so the more cautious approach is worth considering.

What do you think? If you like, I could try adjusting this PR to include the more backward-compatible version and you could test whether that's easy to integrate with your local requirements.

**Comment by seboettg** [comment]
Hello Demian!
Thank you for your reply. For my part, I do not see any problems when you adjust the function signature using new parameters with default values. We use Solr's terms function to generate autocomplete suggestions and currently we fetch the autocomplete terms directly from Solr. To be closer to the original code of VuFind (especially because of the complicated JavaScripts) I have built an custom Autocomplete Service. This Service needs terms method of Solr Backend. (have a look at https://github.com/HeBIS-VZ/vufind-module-hebis/commit/f6b38b13f17972a2bb6add79f12e2dc27c5f7b5b)

**Comment by demiankatz** [comment]
Great, I'll look into reordering the parameters in the near future and will report back here when I've had time (at the moment I have a couple of other projects I should complete first). Are you interested in having your terms-based autocomplete service incorporated as a core component? I'd be happy to look at how easy that would be as well.... Thanks for sharing the details!

**Comment by seboettg** [comment]
In principle, yes! But it's a lot of other stuff to do to get useful autosuggestions from Solr's terms function. Especially while building the Index. We're using a very customized index, wherefore our approach for autocomplete suggestions is not easily applicable for VuFind default usage. Probably @Hirnfiedler may explain details. He has built our index.

**Comment by Hirnfiedler** [comment]
Hi Demian,
like Sebastian already mentioned, our autocomplete is more influenced by Solr patterns than by extending VuFind. It's in our queue to present the approach, but first we need to migrate our deprecated 1.3 installations. :-)

The basic concept  is very simple:
* having a own (indexed, not stored) field for prepared suggest phrases
* using the fast terms-component instead of a search component

The magic is the preparation of the phrases: 
* use just relevant information (titles, persons, classifications)
* index the information 'rotated' `("the cambridge introduction to walt whitman", "cambridge introduction to walt whitman the", "introduction to walt whitman the cambridge" , "to walt whitman the cambridge introduction", "walt whitman the cambridge introduction to" and "whitman the cambridge introduction to walt")` 
This sounds expensive, but because of the internal compression of Lucene and not storing the values, it's reasonably cheap. [Have a look on one of our Installations.](https://hds.hebis.de/ubffm/index.php) Comments are welcome.

The rotation makes it possible to 'search' with the extremely fast and lightweight terms component.  

PS. At the time we implemented this solution, the state of the art was to suggest the content of stored fields and highlight the given term. In our environment this was to slow. Meanwhile Google copies our presentation. ;-)

**Comment by demiankatz** [comment]
@Hirnfiedler, thanks for sharing this information -- very interesting. I'd definitely be interested to hear more about this after you've finished your upgrade project.

@seboettg, I have just pushed an alternate implementation to this branch -- I believe it offers the same flexibility that you proposed, but without breaking any existing calls to the method. Some notes:
  - I used null checks instead of empty() checks to ensure that values like `0` can still be passed through appropriately.
  - I added a special check to allow a ParamBag to be passed as either the first or last parameter, which should make things rather more flexible (we can deprecate the current parameter list order and rearrange it in the future if we want to make things more consistent, but this makes the change less disruptive for now). 
  - The implementation will set defaults for terms.lower.incl and terms.sort if these parameters are not set in the ParamBag, but they can be easily overridden.

Please let me know if you think this is an improvement or if you preferred your own implementation (or if you'd like to work on a compromise between the two). Thanks again!

**Comment by demiankatz** [comment]
@seboettg, I've also added a couple of test-related TODO items to the top-level description of this PR. I'm happy to take care of these when the time comes, but we should make sure we are in agreement on the general design before investing time in these finishing touches.

**Comment by seboettg** [comment]
Demian, thank you.

I've tested your changes but found an issue. I guess there is a little bug in your code. 

In VuFindSearch\Backend\Solr::Backend I would change the terms function on line 234 as follows:
 
```php
// Support alternate syntax with ParamBag as first parameter:
if ($field instanceof ParamBag && $params === null) {
    $params = clone $field;
    $field = null; // sets $field null to avoid usage further below
}
```
Otherwise the `terms.fl` field in `$params` will be set with `$params` further below: 

```php
// Use parameters if provided:
if (null !== $field) {
    $params->set('terms.fl', $field);
}
```

My terms function looks like this:

```php
    public function terms($field = null, $start = null, $limit = null,
                          ParamBag $params = null
    ) {
        // Support alternate syntax with ParamBag as first parameter:
        if ($field instanceof ParamBag && $params === null) {
            $params = clone $field;
            $field = null;
        }
        // Create empty ParamBag if none provided:
        $params = $params ?: new ParamBag();
        $this->injectResponseWriter($params);
        // Always enable terms:
        $params->set('terms', 'true');
        // Use parameters if provided:
        if (null !== $field) {
            $params->set('terms.fl', $field);
        }
        if (null !== $start) {
            $params->set('terms.lower', $start);
        }
        if (null !== $limit) {
            $params->set('terms.limit', $limit);
        }
        // Set defaults unless overridden:
        if (!$params->hasParam('terms.lower.incl')) {
            $params->set('terms.lower.incl', 'false');
        }
        if (!$params->hasParam('terms.sort')) {
            $params->set('terms.sort', 'index');
        }
        $response = $this->connector->terms($params);
        $terms = new Terms($this->deserialize($response));
        return $terms;
    }
```

With this changeset our Autocompletion works fine.

I'm not familiar with pull request, yet. How can I change your commits or would you like to change the code?

**Comment by demiankatz** [comment]
Good catch! I've just added the `$field = null;` line as you suggested. I don't think that it's necessary to clone $field in this case -- the simple assignment should work, because setting $field to null will clear the reference but not affect the object. If your goal is to avoid side effects (the modification of the passed-in object) then it would probably be better to move the clone down into the later line, something like `$params = $params ? clone $params : new ParamBag();`

Let me know how you feel about that issue, and if it's satisfactory, I'll go ahead and merge this.

Regarding pull requests, the idea here is that any changes pushed to your search-terms branch (the branch used to establish the PR) will automatically show up here. So if you want to make further changes, you can just push them here and the PR will update. When you open a pull request, there's a setting which grants project owners write access to your branch -- that's how I was able to make my changes; I just pushed them over to your fork of the project. Let me know if any of that is unclear -- it's definitely a very useful system once you understand it!

**Comment by seboettg** [comment]
You're absolutely right, setting `$field` to null is sufficient and cloning `$field` not necessary. 
Also, I do not see any advantages in cloning `$params`. So I guess we can ignore it.  
Thanks, again. Feel free to merge the PR :-)

**Comment by demiankatz** [comment]
Great, thanks! I'll work on the testing tasks noted above in the near future, and then I'll merge once all that checks out (though I'm not expecting any problems).

**Comment by demiankatz** [comment]
@seboettg, thanks again for this -- I have just merged it to master. Note that I had to revert your change to AbstractSolrBackendFactory (see https://github.com/vufind-org/vufind/pull/888/commits/e591534b32be8e3bcba31df8f27cb1c08ba767f0) because it was breaking the terms functionality. I'm not sure what motivated this change on your side, but it definitely seems to be undesirable for master. Let me know if you have any questions/concerns about that!

**Comment by seboettg** [comment]
@demiankatz, thank you, too.

> Note that I had to revert your change to AbstractSolrBackendFactory (see e591534) because it was breaking the terms functionality. I'm not sure what motivated this change on your side, but it definitely seems to be undesirable for master.

There are a problem with the HandlerMap. The terms URL of our Solr Backend is reachable at "http://url.de:8080/solr/hebis/terms" ("term**s**" with added **s** at the end). But the function `setHandlerMap` in the HandlerMap class sets "term" (without **s** at the end) as handler. As a result of this the URL to our Solr Backend is simply wrong. Have a look [here](https://github.com/vufind-org/vufind/blob/master/module/VuFindSearch/src/VuFindSearch/Backend/Solr/Connector.php#L345).

Maybe I'm on the wrong way to implement the Autosuggestion, but I do not know an alternative way. What I'm doing wrong or what I have misunderstood?

**Comment by demiankatz** [comment]
I suspect that this is a Solr configuration inconsistency between your instance and the default "out-of-the-box" VuFind. VuFind ships with a configuration that uses "/solr/biblio/term" as the term handler URL (see: https://github.com/vufind-org/vufind/blob/master/solr/vufind/biblio/conf/solrconfig.xml#L548). Thus, 'term' is the correct configuration. However, if your Solr configuration uses "terms" instead of "term" than the configuration needs to be adjusted to match. It might be easiest to adjust your custom Solr configuration to match what VuFind does by default so you don't need to modify any core settings.

(I understand that "terms" might actually be a more appropriate URL than "term" -- but that's the way it's been for a long time, and I hesitate to change it since it's likely to cause more disruption than it prevents).

**Comment by seboettg** [comment]
I didn't realize that this concerns the Solr configuration. I will find another solution to resolve this issue. Thanks again.

**Comment by Hirnfiedler** [comment]
Hi Demian,
you are right. Our index isn't "out-of-the-box VuFind". It's more "out-of-the-box Solr".
(see [Terms Component](https://cwiki.apache.org/confluence/display/solr/The+Terms+Component))

We will fix this, by declaring the component twice (both styles):
Solr: `<searchComponent name="terms" class="solr.TermsComponent"/>`
VuFind: `<searchComponent name="term" class="solr.TermsComponent"/>`

But nevertheless it could be worth, to think about getting VuFind more "out-of-the-box Solr". The switch to Solr6, could be the right moment.

**Comment by demiankatz** [comment]
I have a feeling that when VuFind first started using the terms component, that component wasn't turned on at all in the Solr example configurations. I have no objection to looking into normalizing that; I don't think it will cause any major disruption. I'll make a note on the Solr 6 PR.

**Comment by seboettg** [comment]
I'm wondering why this PR didn't become part of release 3.1.3? Is there a reason for that?

**Comment by demiankatz** [comment]
3.1.3 was just a bug fix release. New features will show up in 4.0, which still has a few things in progress before it can be released.

**Pull request merged**
