### PR TITLE
translation of language field in record-related templates

### PR DESCRIPTION
**Pull request by lahmann**
Contents of the `language` field are usually as standardized as `format` and should be translated providing relevant information for the user whether the record is useful for her or not.
This pull request includes changes in `blueprint` and `bootstrap3` themes to translate languages in record-related templates.

See also https://vufind.org/jira/browse/VUFIND-583 and https://vufind.org/jira/browse/VUFIND-1044

### CODE REVIEW

**Comment by demiankatz** [comment]
I agree that we ought to do this, but I've been waiting for #177 to be completed so that we can separate the language names into their own .ini file to avoid pollution of the main language file. See also #238, which probably duplicates some of this work. Hopefully we can get all of this wrapped up soon -- there's been some recent activity on #177. Your input would definitely be welcomed there.

**Comment by lahmann** [comment]
Yes, this is quite a duplicate of #238 - I wasn't aware of that pull request.
Extending languages support in VuFind2 is becoming a popular topic, looking at #177, #238, #330 and #407 - I'll comment in #177 and maybe we should just close this pull request or combine it with #238...

**Comment by demiankatz** [comment]
André,

Since this is more complete than #238, I've closed #238 and left this one open.

However, I notice one problem -- you're using $this->escapeHtml($this->transEsc()) where you should simply be using $this->transEsc(). You don't need to escape twice, since transEsc is already doing the escaping. Please fix that when you get a chance, and then we can put this on hold until further progress on #177 (or whatever new PR replaces it in the near future).

Thanks!

**Comment by lahmann** [comment]
You are absolutely right - must have slipped my attention. I just pushed a fixed version.
Thanks for checking!

**Comment by demiankatz** [comment]
Now that #419 is merged, I have updated this PR with a preliminary text domain for language translation. Some details need to be polished up, and the templates need to be adjusted to actually use the text domain. I'll work on all of that soon.

**Comment by demiankatz** [comment]
Having spent a little time on this issue, it seems there are some practical concerns we need to sort out in order to figure out the best path forward.

First of all, what strings do we need in our language files? My initial thought was to simply take all of the values from the existing https://github.com/vufind-org/vufind/blob/master/import/translation_maps/language_map.properties and https://github.com/vufind-org/vufind/blob/master/import/translation_maps/language_map_iso639-1.properties translation maps. This likely covers the most common cases as well as some variant forms.

However, I don't want to force all of our translation volunteers to assemble all of these strings on their own. A bit of research suggested that most of the details could be extracted from the Unicode CLDR data set (http://cldr.unicode.org/). However, actually trying to map that gets complicated if we're just dealing with English language names instead of codes. Correlating values in our translation maps with values in CLDR is definitely not as straightforward as one might hope.

This in turn reminded me of this JIRA ticket: https://vufind.org/jira/browse/VUFIND-753 which proposes indexing language codes instead of language names, for greater consistency. But this also introduces problems if consistency in cases where different sets of incoming data represent languages in different ways.

At this point, I have more questions than answers. I think a reasonable solution can be reached, but I'm not sure which combination of changes gets us there. I also don't have a strong opinion since I don't personally need i18n for my local VuFind instance. Input from others with more invested in this would be very helpful!

**Comment by oschihin** [comment]
Hi
I want to give a thumbs-up to codes. I do see the argument that you will have to adapt your mapping-tables in VuFind, I think it would be worth it. We have always been indexing code, and translating them into en/de/fr/it, of course, our translations can be used. And I guess, if we stick to the MARC code list of languages, we would not need to map in most of the use cases on import. As far as I can see, the MARC codes are similar to ISO-639-2 (http://www.loc.gov/marc/languages/introduction.pdf). What needs to be developed is mapping from any codes (I have no overview of what is out there) and maybe language strings to the standard list.

Additional reasons, together with those already mentioned in https://vufind.org/jira/browse/VUFIND-753:
* Simpler translations in multilingual environments
* Better reuse of data used through APIs. Personally, I prefer to get codes through an API and translate them in "my" application, rather than get label-strings. If building an API, it would still be possible to get out both code and label.
* Simplified search through an API. It's easier to search for codes than for labels where you never know if they are in English, French, or Hebrew.
* As far as alphabetical sorting is concerned, in our case, languages are sorted alphabetically according to the label (https://www.swissbib.ch/Search/Advanced), with the four most common languages on top.

**Comment by demiankatz** [comment]
The biggest challenge with regard to mapping has to do with the scope of the codes. In some systems, a code may represent a whole family of languages, while in other systems, the family will be broken down into codes for each constituent language. When you mix two systems together, it's hard to deal with differing levels of specificity. In practice, I suspect that the most commonly used languages will not be subject to this problem, but in terms of coming up with a systematic solution, it poses a challenge.

**Comment by demiankatz** [comment]
I suppose one approach to the scoping problem could be to prefix the codes with the standard from which they are derived... though that could add some annoying overhead.

**Comment by demiankatz** [comment]
Take a look at this project: http://www.lexvo.org/ -- we might be able to use this linked data repository to generate language files, once we've decided on exactly what they should contain.

**Comment by demiankatz** [comment]
@lahmann, this is now one of our oldest open pull requests, mainly because we have never gotten around to finishing the discussion about how to manage/reconcile language codes. Just curious where this falls on your priority list, and whether you've had any time to give the problem any thought. I think @oschihin's comments all remain valid, but this is nonetheless a tricky problem with a lot of variables. If you have any opinions (or even ideas on how to begin working toward a consensus) that would be helpful. I'm clearly not getting too far on my own, since this is not a high local priority for my institution.

**Comment by ckaz** [comment]
Not sure whether I'm totally off with what I think this ticket is about. As a former translator of many years I would strongly suggest the following: Translate language names only into what the native speakers of that language would call their language. I.e. Never translate "Deutsch" into "German" in a language dropdown, or "English" into "Anglais" etc. There are many cases in which the translated language names are totally unfamiliar to many and bear no resemblance to what a native speaker would suggest, such as "nemecko" for "Deutsch". Many Germans won't know what they get when they read "nemecko".
My best! Claas

**Comment by demiankatz** [comment]
@ckaz, we are already doing what you suggest for the language selection drop-down. I agree that that is the best approach, and we do not intend to change it.

This PR is actually addressing a different issue: we have information in many records about the language of those records. So we want to be able to translate language names that are part of a record to a form that will be understandable to the current user... Right now, we translate the label "Language:" but we don't translate the value "English."

The challenge is that we haven't figured out the best way to approach this, given that VuFind can receive language strings in any number of formats: either free-text names or codes from a variety of different predefined vocabularies. In some cases, there is overlap where the same code can mean different things, or language families may be described at differing levels of granularity.

We have to answer a few different questions to find the optimal solution to the problem:

1.) When we index language strings into Solr, what should we use? A particular code list, or a free-text string?

2.) Regardless of the answer to question 1, if we receive language names in a different format, how can we map them to the desired format? (Since different APIs and metadata formats will provide different things).

3.) How can we generate translation files for languages? Is there an existing data set that we can use to create the necessary files without having to take up the time of our volunteer translators?

We could obviously start with a crude approach and then improve from there... but it will be harder to change later than to get it right in the first place, so I'd like to have a plan that feels robust before proceeding.

**Comment by EreMaijala** [comment]
None of the ISO 639 standards is perfect, so we ended up using ISO 639-3 with some additions from ISO 639-2/-5. If it's of any use, we have a translation map from ISO 639-1/-2 to this one:
https://github.com/NatLibFi/RecordManager/blob/master/mappings/language_codes.map.sample

Other than that, I'd say the RecordDataFormatter changes could be committed even if we don't have a common standard or complete translations for the strings. Just document that selecting what to index and translate is left to deside by the local admin. It would be nice to standardize on something, but it may add undue burden in simple use cases.

**Comment by demiankatz** [comment]
@EreMaijala, I agree that, given how long this PR has been open, a bare minimum satisfactory solution would be to merge the RecordDataFormatter changes without the actual language file additions... but the reason I haven't done that before now is that it seems like, if we invest a little bit of time in data-wrangling, it might be possible to use existing data sets to build full translation files for all of the currently supported languages, and then we could commit indexing rules and language files that fully support translation of language names. Obviously, I'd rather commit a full solution than a partial one, if we can find a reasonable baseline to work from... and that seems like a possible goal for 7.0.

Maybe the thing to do is merge the RecordDataFormatter changes to master now, and keep this PR open with a milestone of 7.0 to come up with a better default indexing and translation strategy... but that only works if somebody thinks it's worth the time to do that work, and that somebody is unlikely to be me due to priority issues.

**Comment by EreMaijala** [comment]
Well, the majority of 3 character language codes are the same between ISO 639 standards and MARC 21, so picking any of those as the basis would work for most cases. The only thing I'd be strongly against is using the 2 character codes.

**Comment by demiankatz** [comment]
Makes sense to me. So the question is whether we can easily come up with a mechanism for translating the 3-letter codes into appropriate labels for all of the supported languages.

**Comment by EreMaijala** [comment]
Maybe this would help: https://github.com/unicode-org/cldr/tree/master/common/main ?

**Comment by demiankatz** [comment]
Yes, that looks very helpful. Then the question becomes whether we are able to create a derivative work from it without licensing concerns (see http://www.unicode.org/copyright.html -- something that I haven't yet read in detail). Perhaps, assuming licensing concerns can be overcome, rather than reformatting the data and copying it into the project as a one-time action, it would make more sense to build a phing task that pulls down all the source data and dynamically generates the appropriate files, so we can easily keep up to date with changes to the source project.

**Comment by demiankatz** [comment]
...I suppose another approach that might be feasible would be to write a custom Zend translator plugin to read the files directly, and apply it only to the Languages namespace. That might allow us to use the files as-is without creating a derivative file. Then it would be a question of whether there's a way to pull these in easily with Composer.

**Comment by EreMaijala** [comment]
IANAL, obviously, but https://www.gnu.org/licenses/license-list.html#Unicode indicates that the license would be compatible with GPL.

**Comment by demiankatz** [comment]
@EreMaijala, I agree that that is encouraging (and honestly, I'm sure there is a way to make this work) -- just a matter of reading the terms carefully and being sure we use the content in the appropriate spirit.

**Comment by ThoWagen** [comment]
Could this be done by creating an extra ViewHelper? 
One could have translation files based on language codes. And in the ViewHelper there could be aliases of those standard language codes in different formats.  As an example for only English and German:
en.ini:
```
en = "English"
de = "German"
```
de.ini:
```
en = "Englisch"
de = "Deutsch"
```

ViewHelper:
```
$aliases = [
     'en' = ['english', 'English'],
     'de' =['german', 'German']
];
```

And then you could call
`$this->transLng('en')`
and
`$this->transLng('english')`
with the same result.

**Comment by ThoWagen** [comment]
Or one could generalize this and create an aliases.ini where alternative translation keys can be set. The translator then also looks for those aliases.

**Comment by demiankatz** [comment]
@ThoWagen, that's a good idea. I think I like the idea of generalizing to an aliases.ini for at least two reasons:

1.) It prevents us from having to create special cases to use different view helpers under different circumstances (in particular, I'm thinking of the potential difficulty of translating the Language facet list using a different helper -- we would have to add some extra configuration to facets.ini, and it would probably not be very intuitive).

2.) It could likely help us reduce redundancy in some other places (for example, I'm thinking of the creator role lists, as discussed in [VUFIND-1233](https://openlibraryfoundation.atlassian.net/browse/VUFIND-1233)).

Obviously, there are a few things we would need to think about:

1.) What is the desired order of operations for aliases? Do we resolve aliases before translating, or do we check for an alias if no translation is found? (I would think that resolving aliases first would be the more "expected" behavior, but this behavior might offer less flexibility if we wanted to use an alias for 80% of languages but have differentiated translations in the other 20%, just as an example).

2.) In the context of language translations, what convention do we use for the definitive list? A specific code list? The English names? Something else? There's already discussion about this above, but maybe the alias idea brings different considerations to the conversation. I think I'm still inclined to favor three-letter codes since they are more stable than human-readable forms... but maybe that gets messy.

In any case, thanks for moving this conversation forward!

**Comment by ThoWagen** [comment]
1.) When it comes to the order I'd say that if we only think about translations without inheritance then the order does not matter. Either the direct translation or the alias can be deleted because it is not used. When we have inheritance I think direct translations should be preferred. When we have the alias 'english' for 'en' in the standard configuration we still might want to have different translations for this in our local configs.

2.) It should not really matter at least for the functionality. But I also like standardized formats like the three-letter codes for the reasons you mentioned above.

**Comment by demiankatz** [comment]
See #3200 for related/continuing work.

**Comment by demiankatz** [comment]
Superseded by #3200.

**Pull request closed without merging**
