### PR TITLE
SierraRest: make status messages configurable.

### PR DESCRIPTION
**Pull request by demiankatz**

### CODE REVIEW

**Comment by demiankatz** [comment]
@EreMaijala, here's another customization we seem to need for Villanova's Sierra instance -- it has been customized to use "Check Shelf" instead of "On Shelf" as the available message, so all of the statuses were wrong with the hard-coded string. These changes seem to fix everything... but does this conflict/overlap with any of the other existing settings?

**Comment by demiankatz** [comment]
@EreMaijala, I agree that it's a bit confusing this way, and I'd definitely like to unify the configuration if we can. However, I'm not exactly sure how to do that. Maybe with your greater experience with the driver, you can make a suggestion.

The particular problem I'm running into is that ItemStatusMappings seems to serve a single specific purpose: to convert codes into human-readable text. However, at least in my instance, it does not appear to be getting used, and the human-readable text is coming directly from Sierra somehow. (My instance never displays the "On Shelf" that is hard-coded into the driver; it always shows the "Check Shelf" that is part of our Sierra configuration).

The reason I added a section is because I think we need a way to attach semantic meaning to specific human-readable strings. Since "On Shelf" is hard-coded into the driver as a possible output AND is used to have a specific semantic meaning, the easiest way to solve my immediate need was to add a configuration that lets me replace all of the "On Shelf" strings in the code with something different. That didn't seem to fit into the existing mapping table in an obvious way. Initially my thought was to create an available statuses array that could hold multiple values, and do an in_array check to see if a status was in that array to determine availability... but then I noticed that there was also a hard-coded "On Reference Desk" string that seemed likely to need overriding in some situations as well, which is what led me to the solution currently in this PR... but I don't particularly like it. It just seemed the quickest way to get what I wanted without breaking anything.

I suppose one possible way to unify this would be to fill out the ItemStatusMappings section with all of the available codes -- assuming that there are standard pre-defined codes in the Sierra manual for "On Reference Desk" and "On Shelf." Then, in cases where we need to check for a particular human-readable string, we could map the appropriate code from the configuration instead of putting the string directly into the code. But I don't know enough about the API to be sure this is feasible. If you think it is, I can pursue it further with a bit of research (any relevant manual page references you can share would save me time, if you already have them handy).

What do you think?

**Comment by EreMaijala** [comment]
What I was thinking was to add something like 
    '-' => 'On Shelf'
to $itemStatusMappings. Then in getItemStatus() use the mapped value instead of 'On Shelf'. To make it complete, we'd need to add a custom code for 'Charged', but I'm fine with putting something like this in the mappings too:
     'Charged' => 'Charged'
There already a mapping for 'On Reference Desk', so that won't need much to be changed.

I think that would work without adding another mapping, but I could still be missing something.

**Comment by demiankatz** [comment]
@EreMaijala, that makes sense; I will give it a try.

**Comment by demiankatz** [comment]
@EreMaijala, I've rewritten this as suggested; is this more what you had in mind? Thanks!

**Comment by EreMaijala** [comment]
@demiankatz Yes, looks good to me!

**Comment by demiankatz** [comment]
Thanks, @EreMaijala -- merging now!

**Pull request merged**
