### PR TITLE
update FOLIO driver getMyTransactions

### PR DESCRIPTION
**Pull request by ihardy**
This is a bugfix for the FOLIO driver's getMyTransactions function.

Changes:
* Use patron id instead of username for query to `/circulation/loans`
* Make data/dueDate variable match
* Use JSON syntax instead of array syntax to parse transaction
* Update `id` value
* add `item_id` value

Below is an example of the response from the call to `/circulation/loans?query=userId==xxxxxxx` thats getting parsed in this function:

```json
{
    "loans": [
        {
            "action": "checkedout",
            "borrower": {
                "barcode": "XXXXXXXX",
                "firstName": "Ian",
                "lastName": "Hardy",
                "middleName": null
            },
            "checkoutServicePoint": {
                "code": "LSD",
                "description": null,
                "discoveryDisplayName": "Library Service Desk",
                "name": "Library Service Desk",
                "pickupLocation": true,
                "shelvingLagTime": null
            },
            "checkoutServicePointId": "3a40852d-49fd-4df2-a1f9-6e2641a6e91f",
            "dueDate": "2019-11-12T04:59:59.000+0000",
            "id": "4312ff87-934a-4646-9eb7-9602bb0ff3ff",
            "item": {
                "barcode": "0114400719926",
                "callNumber": "PR6045.O68 E7",
                "contributors": [
                    {
                        "name": "Woolf, Leonard, 1880-1969"
                    }
                ],
                "holdingsRecordId": "30b99376-e6f3-11e9-8fe9-7d080c1d501e",
                "id": "ba8dbf09-73fc-4fbc-bd5c-ed1bb7024412",
                "instanceId": "091b35f8-60de-43d8-9a5e-66c66cf0378a",
                "location": {
                    "name": "Books - Level 2"
                },
                "materialType": {
                    "name": "Book"
                },
                "status": {
                    "name": "Checked out"
                },
                "title": "Essays on literature, history, politics, etc"
            },
            "itemId": "ba8dbf09-73fc-4fbc-bd5c-ed1bb7024412",
            "loanDate": "2019-10-11T14:27:05Z",
            "loanPolicy": {
                "name": "One Month(for testing)"
            },
            "loanPolicyId": "43198de5-f56a-4a53-a0bd-5a324418967a",
            "metadata": {
                "createdByUserId": "8b12519c-c01f-51a4-a08a-f0ee49afda0a",
                "createdDate": "2019-10-11T14:27:06.456+0000",
                "updatedByUserId": "8b12519c-c01f-51a4-a08a-f0ee49afda0a",
                "updatedDate": "2019-10-11T14:27:06.456+0000"
            },
            "patronGroupAtCheckout": {
                "id": "28566ed1-bccd-4aaa-a960-7ee9a8ffb4f3",
                "name": "Staff"
            },
            "status": {
                "name": "Open"
            },
            "userId": "b8b02314-dca2-4693-8ebb-ba451688e559"
        }
    ],
    "totalRecords": 1
}
```

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @ihardy -- I appreciate you taking the time to submit a fix!

I notice that the test suite is now failing, because apparently our test fixture does not include a patron id. This was set up by @crhallberg -- I'd be interested to hear from him whether this is fake data that needs to be corrected, or if this is real data from our test system. If it's real data, I just want to be sure that this reflects a real change in FOLIO and not some possible configuration-related incompatibility that needs to be addressed somehow.

Hopefully the solution here is simply to update a fixture file, merge this, and get on with our lives -- but I want to be sure we're all on the same page first.

**Comment by crhallberg** [comment]
This particular test is making sure that we're sending the proper headers and data so the response mock isn't the issue.

I think the only thing that we'd need to do to pass the test is to change what's being passed to getMyTransactions from username to id: https://github.com/vufind-org/vufind/blob/master/module/VuFind/tests/unit-tests/src/VuFindTest/ILS/Driver/FolioTest.php#L161

**Comment by ihardy** [comment]
Thank you @demiankatz and @crhallberg for taking the time to review. I updated the unit test according Chris's suggestion.

**Comment by demiankatz** [comment]
Thanks, @ihardy and @crhallberg -- glad this turned out to be much less complicated to fix than I had feared. :-)

**Comment by kwareict** [comment]
Thank you @demiankatz @ihardy and @crhallberg for making FOLIO driver happening. We are so pleased to see VuFind- FOLIO integration in action. We will be happy to test the driver with our FOLIO installed instance if that will help.

Massoud.

**Comment by demiankatz** [comment]
Thanks, @kwareict; we certainly welcome feedback at any point that it's convenient for you to test. Let me know if I can be of any assistance in the setup process!

**Pull request merged**
