### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by blackmolly**
The following issues were fixed:
- added IP authentication to users (needs ip declaration on EDS.ini file
- Display fulltext custom links
- Some record titles were not displayed
- Ebooks FT link was missing

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks for sharing this! A few comments/questions:

1.) To ensure proper .ini parsing, I'd recommend enclosing the organization_id value in double quotes.

2.) If "Springfield University" is meant to be a generic example, I'd recommend changing it to MyUniversity for consistency with other VuFind sample configurations.

3.) It appears that this PR reverts some style adjustments introduced through php-cs-fixer. This is easily corrected by running the php-cs-fixer Phing task (which I can do for you, if you don't have a setup that makes this convenient). Doing this will make the pull request easier to review by eliminating some meaningless changes from the list of diffs.

4.) It looks like template changes have only been made to the bootstrap3 theme, but I suspect that parallel changes are also needed in the blueprint and/or jquerymobile themes. Please let me know if you're fixing bootstrap3-specific bugs or if we still need to do this work of porting changes across the different themes.

Thanks for the work, and please let me know if I can be of any assistance in polishing up these remaining issues.

**Comment by blackmolly** [comment]
Hi Demian,

Hope everything is ok with you

1) i've added the quotes
2) i've changed the name to what you recommended
3) Yes please, if you could do that would be great
4) i've applied the changes to blueprint and jquerymobile themes

Thank you
Rui

**Comment by demiankatz** [comment]
Hello again. A few new comments:

1.) I've created a PR (https://github.com/ebsco/vufind/pull/1) against this branch to bring you up to date with the latest master and to apply standard style fixes to PHP and template files.

2.) Does the EBSCOAuthenticateIP.php file serve any purpose? It does not appear to be used.

3.) I notice that a couple of functions are missing header comments. Could you add these? The Travis CI build report will guide you to any remaining style problems after you have merged my PR.

Thanks again for your help! I'll take a closer look and do some testing once all of this is sorted out.

**Comment by blackmolly** [comment]
Hi Demian,

Thank you for the merge.

2) yes it's used at least once.

3) Sure. Do you have a list of the files/functions missing them ?

Thank you
Rui

**Comment by demiankatz** [comment]
2) Are you sure it's used? If I go to the "Files changed" tab on this PR and search for either EBSCOAuthenticateIP.php or the name of the function contained within, I don't see any include statements or function calls that suggest to me the file is being used. Could you point me to the specific code if I'm somehow missing something?

3) Please merge in my pull request. After that happens, wait a few minutes for the Travis build to complete. When that happens, at the bottom of this pull request, you should see a "Failed -- The Travis CI build failed" message. When you click the "Details" link in that box, it should give you a full report on remaining problems/issues.

Please let me know if I can be of further assistance!

**Comment by demiankatz** [comment]
Some comments/questions:

1.) Please merge this pull request: https://github.com/ebsco/vufind/pull/2 -- this resolves merge conflicts and fixes some things.

2.) After the merge, please re-test the IP authentication. I fixed some bugs there, but I can't test it myself, so it would be helpful to ensure that I didn't introduce any new problems.

3.) Speaking of the IP authentication, VuFind now has a centralized permission system. Rather than implementing EDS-specific IP matching code, it might make more sense to leverage the existing system. You can see the available options in https://github.com/vufind-org/vufind/blob/master/config/vufind/permissions.ini and you can see how it's used for, for example, Summon, at https://github.com/vufind-org/vufind/blob/5168d6c607da7cf2b9ec42e051a037da94dddf69/module/VuFind/src/VuFind/Search/Factory/SummonBackendFactory.php#L141 -- rather than figuring out authentication details inside the Summon search backend, we figure out the permission level inside the factory and simply pass along the value to the backend. I think it makes things a bit more flexible.

4.) I notice that you have disabled some of the links in the pagination for EDS. What is the reason for this? If it's really necessary, I think we should aim for a solution that does not require an EDS-specific special case inside the generic pagination control. I can help brainstorm a more flexible solution, but first I'd like to understand the reason for the change.

5.) Somehow, some changes to the EDS templates in the bootstrap3 theme got reverted at the same time that some of your new changes were added. I fixed some of this, but it's possible that further adjustments are still necessary. Once the other issues are resolved, I'll talk to @crhallberg about a template review to make sure everything is fully up to date.

6.) Are there any records I can use to test the new features covered in the templates? If there are standard useful test cases, that would help me actually try out the code in action using my test instance.

Anyway, thanks again for your help -- we're making progress!

**Comment by demiankatz** [comment]
@blackmolly, thanks for merging my previous pull request. I've just opened another one to get us back up to date, since there was one more recent change that introduced a minor conflict. If you can merge that (shouldn't require any review on your part -- just hit the merge button!) then this will be fully up to date, and I should be able to wrap it up later in the week.

**Comment by demiankatz** [comment]
Okay, I have manually merged these changes to master.

Note that I reworked the templates a bit to simplify some code and ensure proper HTML escaping.

One significant change: I reverted the logic that calls $this->driver->getTitle() in the result-list.phtml template for the bootstrap3 theme. This was causing keyword highlighting to break, and I thought it was probably preferable to retain the old method that allowed highlighting to appear in titles. If there is a specific problem that you are trying to solve here, it may be worth investigating an alternate solution. However, in my tests, it didn't seem to make a difference.

In any case, thanks for all of your work on this; I'm glad we've finally got it all merged. Please let me know if I can be of any further assistance!

**Pull request closed without merging**
