### PR TITLE
Basic Vagrant Support

### PR DESCRIPTION
**Pull request by bemosior**
This branch contains a `Vagrantfile` that provisions an Ubuntu 16.10 VM with all dependencies necessary to run VuFind. It does not yet handle database setup, solr setup, or local configuration. Those can be added later, if this provides value.

If you are new to Vagrant, have a look at the [Getting Started](https://www.vagrantup.com/docs/getting-started/) guide. In short, Vagrant allows you to repeatedly and predictably provision fresh, local virtual environments for your software project. The local workspace is automatically mounted in the VM under `/vagrant`, which means you can use a local editor all while testing changes within the VM.

To use the `Vagrantfile`:

1. Check out this branch.
2. Run `vagrant up` within the workspace.
3. Wait for the full system to provision.
4. Verify successful provisioning by visiting http://localhost:4567/vufind (you should see a VuFind page with an error message, since the DB won't be set up yet).
5. Set up the database, create local configuration files, start Solr, etc. You can always run `vagrant ssh` to SSH into the VM.

If anything goes wrong as you mess about with the VM, just run `vagrant destroy` and start again.

@demiankatz Feel free to contact me if you'd like a demo or would like to discuss how/why something like this might be useful.

TODO:
- [x] Find workaround for "cannot install Solr with Phing" problem under Vagrant environment (possible fix: unpack archive to /tmp instead of $VUFIND_HOME/solr).
- [x] Set up appropriate permissions so that web-based installer will work.
- [x] Document default database credentials (and additional setup steps) in wiki: https://vufind.org/wiki/installation:vagrant
- [x] Implement more future-proof Composer installation

### CODE REVIEW

**Comment by demiankatz** [comment]
@bemosior, I still haven't had a chance to play with this yet, but in the meantime, a different kind of question: do you know what conventions exist for including Vagrant configurations with projects? It seems to me that a lot of different options are possible, and I'm just curious if any patterns have emerged that you are aware of. Does it make sense to offer the user the choice of different platforms, for example? If so, are there good ways of implementing this? If not, how should we as a community decide what to offer by default?

It seems like including some kind of Vagrant support within the project is useful, and it doesn't hurt anything else since it's just a matter of adding a file... but if we're going to do it, we might as well do it in the best way possible. Apologies if any of my questions are driven purely by my ignorance of the technology. :-)

**Comment by bemosior** [comment]
These are good questions!

Just to run through some concepts, a Vagrant box is a VM image, like a snapshot. Boxes can be specialized (e.g., a LAMP environment) or general (e.g., a "base box" for Ubuntu, CentOS, etc. that only includes the bare minimum for Vagrant to work). You can find official base boxes and more specialized boxes in [the catalog](https://atlas.hashicorp.com/boxes/search).

Vagrantfiles define some number of Virtual Machines and their respective base boxes (e.g., Ubuntu 16.10 for this PR), VM settings (e.g., how much memory, which ports to forward, where to mount the shared folders, etc.), and provisioning/configuration processes (e.g., a bash script or puppet manifest that installs packages and sets the right configuration).

Supporting multiple platforms is certainly possible with different VMs and base boxes, [even within just the one Vagrantfile](http://www.thisprogrammingthing.com/2015/multiple-vagrant-vms-in-one-vagrantfile/).

A great way to really answer your question is to examine how the tool will be used. My thinking is that Vagrant could 1) Make _your_ life easier by automating much of the testing environment setup (meaning you don't have to worry about keeping a VM in pristine condition, since you can always blow it away and bring another up easily), and 2) Make getting started easier for new devs.

Vagrant support is entirely additive (no compromises to the overall project if Vagrant support for only one platform is added). If you generally only use an Ubuntu VM as a daily driver, then adding support for that by itself is worth doing. You can always add support for other platforms later, so it's not really necessary to wait until you support _all_ platforms to merge in. If interest picks up, and people go "I wish we could use Vagrant with CentOS," then we can make that leap. But the decision's up to you!

**Comment by demiankatz** [comment]
Thanks for the detailed response. That is very helpful. I agree that under these circumstances, it makes sense to merge this sooner rather than later and to incrementally improve it as needed. I'll wait until I've had time to actually try it out in case there are any refinements I can make based on my experience (and I certainly welcome comments from others, too)... but I imagine this is a very strong start.

**Comment by bemosior** [comment]
We could consider saying that the Docker capability (#962) supersedes Vagrant (some projects would choose one or the other), but there's really no harm in having both (besides points of maintenance). Many folks may be more comfortable with the idea of a virtual machine (moreso than with containers), so Vagrant could still be a very useful tool.

**Comment by demiankatz** [comment]
@bemosior, I think Vagrant and Docker cover different use cases, so supporting both is complementary. My main hangup is that I have been having trouble getting Vagrant working on my test server (I think I need to mess with the BIOS settings to allow virtualization, and I haven't had the time yet). Once I get that sorted out well enough to test this, it will probably be acceptable to merge as a first pass.

**Comment by demiankatz** [comment]
@bemosior, I've made some progress on Vagrant testing (turns out my problem was that I had an outdated Linux kernel -- the Ubuntu `do-release-upgrade` doesn't update the kernel by default, and that was causing problems for VirtualBox).

Unfortunately, though, I've run into a problem I can't seem to get past: the `composer install` is failing on the `phing installsolr` task. Specifically, I get an error about being unable to delete a file, which I think is actually occurring as a side effect of the `<move>` task that renames the unpacked Solr distribution to the solr/vendor directory. My guess is that something about the way Vagrant mounts the /vagrant directory as a shared file system is not playing nicely with the way Phing implements move operations. While in normal Linux, this triggers a simple rename, under Vagrant it appears to be triggering a very slow copy-and-then-delete operation which ultimately fails.

A possible workaround for now would be to run composer install PRIOR to spinning up the Vagrant box... but of course it would be nice if we could get everything to work properly in the appropriate context. Any ideas or theories?

(Another issue: the base box that was originally defined in the Vagrantfile no longer seems to exist, so I've switched to a stock 16.04 box).

**Comment by demiankatz** [comment]
I've just pushed up a workaround to unpack Solr to /tmp which seems to help with the aforementioned problem... though I'd be happier if we didn't have to work around that! :-)

**Comment by demiankatz** [comment]
I'd still be happier if I could make this work without having to change the Solr installation procedure, but I think the change is justifiable, so I've gone ahead and merged this (after making a few additional adjustments to make everything work properly). Setting this up is now documented at https://vufind.org/wiki/installation:vagrant .

**Pull request merged**
