### PR TITLE
Add support for Alma as an OpenURL resolver.

### PR DESCRIPTION
**Pull request by EreMaijala**

### CODE REVIEW

**Comment by demiankatz** [comment]
@EreMaijala, this looks good; is it worth taking a couple of minutes to add test coverage? If you don't have time but can send me a captured HTTP response for testing purposes, I can throw something together in the next few weeks.

**Comment by EreMaijala** [comment]
@demiankatz Yes, that's a good idea. I'll add some tests.

**Comment by EreMaijala** [comment]
Tests added. That provided to be useful as I also made some improvements in the driver to handle different service types better.

**Comment by demiankatz** [comment]
Thanks, Ere -- interesting to see how closely this aligns with SFX terminology, even though the XML is different. In any case, I'm pretty comfortable with this, but I'll wait until next week to merge so that @betullam has an opportunity to comment.

**Pull request merged**
