### PR TITLE
Remove unused/broken multi-breadcrumb functionality.

### PR DESCRIPTION
**Pull request by demiankatz**
I recently discussed with @EreMaijala the fact that the multi-breadcrumb functionality in VuFind is never used and has some problems (missing translations, improper escaping, etc.).

This code existed as part of the public VuDL implementation which was subsequently removed due to lack of interest/support. It is extremely unlikely that anyone is using it in production.

I have recently been working on upgrading Villanova's local instance of VuDL + VuFind, and in the new version of the code, I reimplemented our multi-breadcrumbs by creating a local template to render them, and then simply assigning the output of rendering that template to `$this->layout()->breadcrumbs`. This is much more self-contained, and less potentially confusing, than adding a whole bunch of additional layout variables, complex logic in the layout template, and the possibility of breadcrumbs being either an array or a string. If we ever need something like functionality this in core VuFind in the future, I would favor using that new strategy instead of the old one being removed here. Another argument in favor of eliminating this obsolete code.

### CODE REVIEW

**Comment by demiankatz** [comment]
@crhallberg, any objections?

**Review by EreMaijala — APPROVED** [review]
Nice!

**Comment by crhallberg** [comment]
No objections!

**Comment by demiankatz** [comment]
Thanks, both of you. Fastest turn-around on a PR review ever?

**Comment by EreMaijala** [comment]
Could be :)

**Pull request merged**
