### PR TITLE
Fix problem with request URLs caused by #2701

### PR DESCRIPTION
**Pull request by demiankatz**
TODO
- [x] Add a test somewhere to catch the underlying problem that this fixes

### CODE REVIEW

**Review by EreMaijala — APPROVED** [review]
Thanks! It would probably be cleaner if we'd pass the extra query params to getActionUrl instead of appending them manually, but this is good enough for me.

**Comment by EreMaijala** [comment]
@demiankatz I tweaked the testPlaceHold test and Demo driver here so that the request would fail without the fix. I also pushed a commit to pass query parameters and anchor to getActionUrl. What do you think?

**Comment by EreMaijala** [comment]
@demiankatz Note that oddly enough normalize_path needs to be set to false. Otherwise the router will mangle encoded slashes in a record ID, but only when the `fragment` option is passed to it, and even when it's an empty string.

**Comment by demiankatz** [comment]
Thanks, @EreMaijala!

**Pull request merged**
