### PR TITLE
Add support for displaying feedback form in lightbox.

### PR DESCRIPTION
**Pull request by samuli**
TODO
- [x] Run full test suite
- [x] Update changelog when merging

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @samuli, I'll review this (and your changes to the other open PR) when I'm back from vacation next week.

**Comment by demiankatz** [comment]
@samuli / @EreMaijala, is this actually being used anywhere at this stage, or are we just setting up a potential? Also, I wonder if we should try to encapsulate the lightbox detection logic somewhere. Right now we have the MyResearchController::inLightbox() method. Maybe we should move that to a LightboxAwareTrait and share it with the FeedbackController, rather than replicating the detection logic in a template. (There are lots of other ways to slice it -- I don't have a strong preference -- I'd just like to avoid creating slightly different versions of the same functional logic in different places).

**Comment by EreMaijala** [comment]
@demiankatz Yes, we need to put a form in the lightbox. I agree about the trait, that's a good idea (ping @samuli).

**Comment by samuli** [comment]
@demiankatz Since lightbox detection is used only in controllers and templates, would this kind of solution work: AbstractBase handles the detection and injects inLightbox-variable to the template in createViewModel ?

**Comment by demiankatz** [comment]
@samuli, this looks reasonable to me, but I'll do some testing and double-checking when I have a bit more time to be sure there are no side effects (or other instances of lightbox detection that should also be unified with this). Thanks!

**Comment by demiankatz** [comment]
Merged!

**Pull request merged**
