### PR TITLE
fixed double namespace attribute

### PR DESCRIPTION
**Pull request by tom-dea**
fixed double namespace attribute by checking if the namespace to be added is already defined anywhere in $xml

### CODE REVIEW

**Comment by demiankatz** [comment]
Was there a reason you favored this approach as opposed to changing `!strstr($attr, 'xmlns:' . $key)` to `!strstr($xml, 'xmlns:' . $key)` in the earlier if condition? This implementation is checking for the presence of all of the namespace declarations in a particular order -- I'm concerned that if multiple namespaces are involved, there could be scenarios where this check would fail to catch duplication. My proposed alternate solution seems a little safer since it will check each namespace independently... but perhaps there is a flaw with that approach that caused you to intentionally take a different approach. Please let me know your thoughts! In any case, thanks for working on this problem!

**Comment by tom-dea** [comment]
in my usecase the first occurrence of the namespace definition that gets
doubled up comes from metadata and is passed to the method as $attr.
that's why a check in the foreach loop would not have an effect.


you are right that the added condition could fail if multiple namespaces
where involved. so a more precise solution could parse the passed
$extractedNs string into its parts and check all of them. proably this
could happen by generating an array from the passed $attr and merging
this array with $ns before entering the foreach loop in fixNamespaces().


does this sound reasonable to you?

**Comment by demiankatz** [comment]
That does sound reasonable. Another possibility might be to de-duplicate the extracted namespaces at the source, around here:

https://github.com/tom-dea/vufind/blob/e6cb8413cda89455c96ebb5ab0dc71e4d8ff9055/module/VuFind/src/VuFind/Harvester/OAI.php#L639

Assuming we can avoid passing in a duplicate namespace, then perhaps the existing code is adequate to prevent creating further duplicates.

**Comment by tom-dea** [comment]
i like that solution. if i understand it right, this eventually could be
done by just adapting the regex to match only the first occurrence of
"xmlns:[^ ]" (or something similar) inside the metadata tag.

**Comment by demiankatz** [comment]
Perhaps. I'm not sure what all of the scenarios in the wild might be. For now, I'd conservatively say the algorithm could be:

1. Extract all attributes of <metadata> tag (which we are currently doing already)
2. Explode the extracted attributes in a way that allows you to check them one at a time (perhaps a quotation-mark-aware regular expression explode on whitespace is the easiest way; I think our existing Solr query parsing code has some regexes you might be able to borrow/repurpose -- I can dig up the details if you need me to).
3. For each extracted attribute, if the attribute name exists deeper in the XML document, simply drop it.

**Comment by demiankatz** [comment]
Looks like you're on the right track, though I'd feel better if we had some unit tests to cover all of this. I hope to eventually refactor the harvester into multiple discrete components which will make that sort of thing a lot easier to manage.

In any case, two comments for the moment:

1.) Does the regular expression need to be revised to account for single-quoted XML attributes? Both single and double quotes are technically legal in XML (though double seem to be much more common in practice).

2.) Now that you are pre-filtering the attributes, can you actually revert your original `if (!empty($attr) && !strpos($xml, $attr)) {`? I think it may be redundant at this point, though perhaps I am forgetting a detail.

Thanks!

**Comment by tom-dea** [comment]
unit tests: i also had the feeling that changing the method would demand for a unit test..
1.) you are right. i also thought about the possibility of single quotes, but ignored it in my first approach, becuse its probably a quite rare case. i will try to integrate that case into the regex.
2.) to be honest i thought that a had already taken the second condition off. i also think its redundant. 
i will add a commit in the next days to cover those two things.

**Comment by demiankatz** [comment]
Yeah, adding tests would be great -- but it's just not too practical given the current state of the code. I'll try to address that through refactoring in the not-too-distant future. Have you sent me a complete XML file that reproduces this bug? If you haven't already done it, that might be worth doing for future reference.

In any case, it sounds like we're about done with the fix for now. I'll await your next commit and then hopefully we'll be ready to merge this!

**Comment by demiankatz** [comment]
Thanks again! I've committed this as https://github.com/vufind-org/vufind/commit/220963e38a5ec3d9ac1253a30663232a2caf0e5e with a couple of minor changes:

- Removed commented-out debug message (we can reintroduce temporarily if needed)
- Adjusted regular expression to form (A|B) instead of (A)|(B) -- otherwise I think the extraction of matches might not have worked correctly.
- Expanded some comments.

If you can test the revised version currently in master, I would appreciate it! It seems okay for my use cases, but you have a better test sample for this particular case.

**Comment by tom-dea** [comment]
for my test sample it works as expected in the current master.

On 06/01/2016 03:32 PM, Demian Katz wrote:
> Thanks again! I've committed this as 220963e
> <https://github.com/vufind-org/vufind/commit/220963e38a5ec3d9ac1253a30663232a2caf0e5e>
> with a couple of minor changes:
> 
>   * Removed commented-out debug message (we can reintroduce temporarily
>     if needed)
>   * Adjusted regular expression to form (A|B) instead of (A)|(B) --
>     otherwise I think the extraction of matches might not have worked
>     correctly.
>   * Expanded some comments.
> 
> If you can test the revised version currently in master, I would
> appreciate it! It seems okay for my use cases, but you have a better
> test sample for this particular case.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/vufind-org/vufind/pull/703#issuecomment-222992978>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADT-d-dti6vD92D60fsijZdS4dwrtMX2ks5qHYn1gaJpZM4IgSFM>.
> 


-- 
Thomas Schwaerzler
Department of Digital Services
University Innsbruck Library
6020 Innsbruck - Innrain 52 - Austria
Phone: ++43-(0)512-507-2489
Fax: ++43-(0)512-507-94908451
Email: <Thomas.Schwaerzler@uibk.ac.at>
URL: http://www.uibk.ac.at/ulb/ds
OpenPGP key: 0x2BD592C2, Key fingerprint = A17C 26AE FB4B BED6 7907 5DFC
5840 AB43 2BD5 92C2

**Pull request closed without merging**
