### PR TITLE
EPF: Test record driver and changes to EDS Backend

### PR DESCRIPTION
**Pull request by maccabeelevine**
Relatively minimal new tests needed, because the EPF data source reuses much of the EDS code.

### CODE REVIEW

**Comment by maccabeelevine** [comment]
@demiankatz I got these new tests to pass, and hopefully they are useful.  But couldn't figure out how to get around the phpstan error.  I get (I think) that when you instantiate a class via reflection you need to give some code hints to phpstan, but not clear from the link it provides how to do that.  I could rewrite the code to avoid the reflection (passing the class name as a string or something), but there must be a better way.

**Review by demiankatz — CHANGES_REQUESTED** [review]
> @demiankatz I got these new tests to pass, and hopefully they are useful. But couldn't figure out how to get around the phpstan error. I get (I think) that when you instantiate a class via reflection you need to give some code hints to phpstan, but not clear from the link it provides how to do that. I could rewrite the code to avoid the reflection (passing the class name as a string or something), but there must be a better way.

Fortunately, I think the solution to this is much easier than you may fear -- you are already passing the class name as a string (the `::class` constant just resolves to a string containing the class name). However, your typehint on the function that phpstan is complaining about has the type set to `class` which is confusing the analysis. Just change `class` to `string` and it should pass. :-)

**Comment by maccabeelevine** [comment]
Wish they were all that easy!

**Review by demiankatz — APPROVED** [review]
Looks good -- merging now!

**Pull request merged**
