### PR TITLE
Better handling of diacritics and uppercase characters when providing spell suggestions

### PR DESCRIPTION
**Pull request by liowalter**
Currently, when a query term has an accent or an uppercase character, no suggestions are provided.

For example : 
friedrich dürenmat -> [no suggestion](https://vufind.org/demo/Search/Results?lookfor=friedrich+d%C3%BCrenmat&type=AllFields)
friedrich durenmat -> [suggestions](https://vufind.org/demo/Search/Results?lookfor=friedrich+durenmat&type=AllFields&limit=20)

Dwight Eisenhozer -> [no suggestion](https://vufind.org/demo/Search/Results?lookfor=Dwight+Eisenhozer&type=AllFields&limit=20)
dwight eisenhozer -> [suggestions](https://vufind.org/demo/Search/Results?lookfor=dwight+eisenhozer&type=AllFields&limit=20)

The reason is the following. The suggestions are analyzed. And especially they go through the ICUFoldingFilter as well : 

```JSON
{
  "spellcheck": {
    "suggestions": [
      [
        "friedrich durenmat",
        {
          "numFound": 1,
          "startOffset": 0,
          "endOffset": 18,
          "origFreq": 0,
          "suggestion": [
            {
              "word": "friedrich durrenmatt",
              "freq": 684
            }
          ]
        }
      ]
    ],
    "correctlySpelled": false
  }
}
```

This pull request is a way to solve this problem. There might be others or better ones... What do you think ?

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks for catching this. I'm wondering if a simpler but more robust solution would be to use the Transliterator class (part of the intl extension) to do the diacritic removal. Since this is built on the ICU library, it should yield more consistent results with what Solr is doing. See this thread for some details:

https://stackoverflow.com/questions/26185163/mysql-matching-latin-english-form-input-to-utf8-non-english-data/26186456#26186456

If you don't have time to dig into the changes, let me know and I can spend some time on this tomorrow. It would be great to get this fixed in the for the 6.0 release!

**Comment by demiankatz** [comment]
@liowalter, I've done a little work on this today. The proposed Transliterator simplification seems to work. I've also begun abstracting the idea of "normalization" to reduce redundant code and make this more extensible. I don't think it's necessary to have separate flags for case sensitivity and accent removal, so I've simplified some method signatures. I need to do some testing to be sure this doesn't break any non-Solr backends, and there's also a little more simplification still to be done (I want to rename and simplify the "...IgnoringAccents" method to make it more generic). Please let me know if you have any concerns with any of the changes; I'll resume work on this in the morning!

**Comment by demiankatz** [comment]
@liowalter, actually, replaceTermIgnoringAccents() seems to be unused, so I simply removed it!

**Comment by demiankatz** [comment]
@liowalter, in further testing, I'm seeing a problem where everything works if I use diacritics (with or without capital letters), but things do not work correctly if I use mixed case without any diacritics. This problem exists in your code prior to my refactoring, so I don't think I introduced it. I suspect some adjustments are needed to the SpellingProcessor. I will investigate further tomorrow morning.

**Comment by liowalter** [comment]
@demiankatz : thanks a lot for all this, it looks all good ! With 65cbad6 , I tried to fix the case problem, which was indeed already in my code. But I am not completely sure about my fix... Would be good if you have a look at it.

**Comment by demiankatz** [comment]
Thanks again, @liowalter, your fix seems to work for me. I've added some test coverage and done some minor cleanup. I'm going to merge this now so the fix can be part of release 6.0.

**Comment by liowalter** [comment]
Very nice ! Thanks a lot @demiankatz ! It has been productive on our side since yesterday : https://www.swissbib.ch/Search/Results?lookfor=Dwight+Eisenhozer&type=AllFields&limit=20

**Pull request merged**
