### PR TITLE
Make the max limit of search API results more flexible

### PR DESCRIPTION
**Pull request by xmorave2**

### CODE REVIEW

**Comment by demiankatz** [comment]
Makes sense to me. Any comments, @EreMaijala?

**Review by EreMaijala — APPROVED** [review]
Makes sense to me!

It might also be useful to make it configurable in the corresponding ini file, but that's just a thought for the future.

**Comment by xmorave2** [comment]
Thank for review @demiankatz and @EreMaijala 

Could be done configurable in the next step, just one thing we need is to have ability to configure any index (primary, secondary, web, ...) differently.

**Comment by demiankatz** [comment]
Thanks, everyone, I'm merging this as-is for now -- just getting rid of that "magic number" hard-coded in two different places is a useful step forward, and I'll welcome a new PR adding a config setting if the need arises in the future.

**Pull request merged**
