### PR TITLE
Javascript Formatting Rules

### PR DESCRIPTION
**Pull request by crhallberg**
Setting the code standard using [ESLint](http://eslint.org/).

See [ESLint's rules list](http://eslint.org/docs/rules/) for available choices and the [recommended choices](https://gist.github.com/crhallberg/ca24ee288146ab5de68f233ae90111d5 "parsed out here") (checked on the rules list), which we are currently extending. See the [config file](https://github.com/vufind-org/vufind/pull/700/files#diff-df39304d828831c44a2b9f38cd45289cR3) itself for rules we are adding.

- [x] Finalize set of rules
- [x] Jenkins checkstyle integration (steps: http://stackoverflow.com/a/32124328)
- [x] Travis checkstyle integration

Philosophical Points:

- "Every line of code should appear to be written by a single person, no matter the number of contributors." ~ [@mdo](http://codeguide.co)
- Don't eliminate the joy of coding.

### CODE REVIEW

**Comment by crhallberg** [comment]
I'm actually not a fan of the variable hoisting, as much as I understand why it's done and why it helps.

**Comment by demiankatz** [comment]
Chris,

Some notes/comments:

1.) There's an accidentally-commited change to index.php -- please revert.

2.) GitHub is reporting conflicts with master. Can you resolve?

3.) Do you know if eslint is able to export reports that can be incorporated into Jenkins? It would be nice to include these in the code style graph if possible. If we can do that, does it replace or supplement the existing jslint stuff? Also, should we add this to Travis once Grunt is in place, or are there some unavoidable failing issues that will consistently break the build?

4.) I notice that there are some changes here that aren't strictly style-related. For example, in advanced_search.js, some functions like addGroupJS() and deleteGroupJS() are completely removed. Are you sure they're no longer used anywhere, and if so, do you know how they ended up there in the first place? If they're truly useless orphans, can we just remove them from master with a "eliminated obsolete functions" commit to separate that task from the styling?

5.) Similarly, I see that the order of functions has moved around in advanced_search.js. Is this style-related, or done for some other reason?

6.) Because there is so much going on here, I wonder if we could do some diff minimization by applying some of the simpler and more obvious changes to master first and then merging them back here. Things like adding spaces around operators, for example, are straightforward and obviously harmless. Getting those out of the way in their own commits will make the more substantial code changes easier to review (and potentially revert) if we run into a problem down the road related to this rearrangement.

7.) I agree that a "no exceptions" policy on variable hoisting may not be the best practice, especially if it impacts code readability. However, perhaps one view on this is that if variable hoisting makes code hard to read/follow, that may be a sign that the code is already too complex and needs to be broken out into smaller functions. It might be worth revisiting areas you view as problematic with this idea in mind. Again, though, that's the kind of refactoring that might be worth doing in its own separate commit so the history remains granular and readable.

**Comment by crhallberg** [comment]
I implemented Travis integration and did the rule-by-rule fixes on another branch here: https://github.com/crhallberg/vufind/tree/eslint-fixes.

Testing failed and then [passed](https://travis-ci.org/crhallberg/vufind/builds/134772378) when I finished the changes.

**Comment by demiankatz** [comment]
Finally took the time to look at this a bit more closely. A few comments/questions:

1.) We should definitely make a Phing task for this -- maybe two Phing tasks, one that does console output (for Travis) and one that creates a report (for Jenkins). We can work together on this if you like.

2.) The only thing I thought might be too strict is "func-names" -- aren't there theoretically some situations (like a simple callback) where a true anonymous function is actually more appropriate than a named function?

3.) What do you think about adding no-unused-vars and no-unused-labels to complement no-unused-expressions?

4.) How about adding no-console to catch the frequent accidentally-committed debug messages? I realize that there are currently a couple of intentional instances of console output in the code. Does eslint provide an "ignore these lines" marker facility to get around that, or should we consider a different approach?

5.) Generally speaking, I imagine there are a lot more "possible errors" and "best practices" rules that we could add without actually having to change any code. It might make sense to turn on a bunch of them just as a guard against future problems, even if it's relatively unlikely that we'll ever encounter those problems.

**Comment by crhallberg** [comment]
1.) Travis is already working, but I wouldn't mind working it into phing if you thought it was best.
2.) It's actually a rule that gives anonymous functions a name in place, it makes debugging much easier. `$('thing').click(function thingClick() { return false; });`
3.) no-unused-labels and no-unused-vars are included by default, since we're extending the recommended rules (all the checkmarks on the [rule list](http://eslint.org/docs/rules/)).
4.) no-console is included by default as well, but I changed the rule in the other branch to allow `console.error` and `console.warn` for legitimate error handling.
5.) I parsed out the eslint:recommended rules here: https://gist.github.com/crhallberg/ca24ee288146ab5de68f233ae90111d5

**Comment by demiankatz** [comment]
Looking good. A couple more things:

1.) Once you have the Phing setup committed, you can modify the Travis config to just call the phing task as part of the one-line phing execution... makes the file that much simpler, and reduces redundancy.

2.) I notice that you have comments in your JSON file, which is technically illegal (and GitHub is flagging it as a problem). Can we safely remove those?

**Comment by crhallberg** [comment]
2.) Yes, this is normally illegal, but eslint [allows this](http://eslint.org/docs/user-guide/configuring#configuration-file-formats) in their config file.

**Pull request merged**
