### PR TITLE
php7 Horizon ILS driver

### PR DESCRIPTION
**Pull request by mathieugrimault**
Can't really test all queries : french db seems to be a heavily modified US db.

So far it seems ok : some queries are running on a debian 9 / php7 / php7-sybase install and a Sybase ASE 15.5.

### CODE REVIEW

**Comment by demiankatz** [comment]
Is the primary goal here to replace the mssql_ calls with PDO for PHP 7 compatibility? Since I can't test this, I want to be sure I'm understanding what I'm reviewing. I'll try to take a closer/deeper look in the near future.

Also note that the failing build seems to be related to php-cs-fixer. If you just run `vendor/bin/phing php-cs-fixer` and commit the changes, that should make things pass. If you need help, let me know!

**Comment by mathieugrimault** [comment]
Is the primary goal here to replace the mssql_ calls with PDO for PHP 7 compatibility?
 => Yes

The code is not working for now ! I am new to PDO/PHP7.

**Comment by demiankatz** [comment]
What exactly is not working? I'm happy to help resolve error messages, etc.; just share the details here as needed. Unfortunately I can't test since I do not have access to a Horizon system, but I'm willing to aid you indirectly as much as possible.

**Comment by mathieugrimault** [comment]
Nothing complicated, one step forward : PDO don’t like double quotes in SQL. 

It's just i struggle to get errors, i feel i'm lacking logs. For example, in patronLogin(), when an exception is thrown, AbstractBase.php is just silently displaying a message to the user but is not logging anywhere the exception->message.
Who should log errors (SQL errors for example) ? ILS Drivers ? Logic code like AbstractBase ?

**Comment by mathieugrimault** [comment]
Not completely satisfied, i would prefer to have ILSException to log to file vufind.log in its constructor but it seems not compatible with Zend (or VuFind architecture) as logger is set by ServiceManager/Initializer.php. 

To log arrays i use $this->debug(json_encode($var)); it would be better if this was handle by LoggerAwareTrait or VuFind/Logger but it will perhaps break support of arrays of message in VuFind/Logger.log() ?

**Comment by demiankatz** [comment]
Yes, it is not really practical to have ILSException log in its constructor, since the exception object would need to have a logger injected, and the on the fly `new ILSException(...)` calls we use to build exceptions does not allow us to do that automatically. It's also not really the purpose of an exception to perform actions like logging -- it's just meant to be a signal between one piece of code and another. However, if you wanted to hard-code some logging logic into the class temporarily for your own debugging purposes, that would not be too hard to do. (Just add some `fopen` and `fputs` calls to append to a log).

Also, as you say, right now, an array sent to a logger has a special meaning in VuFind (allowing messages to report at multiple levels of verbosity). This feature is not heavily used, and it might make sense to rethink it at some point... but right now there would be some complications to trying to add automatic json encoding of arrays sent to the logger.

**Comment by demiankatz** [comment]
@mathieugrimault, just checking on the status of this work. Do you feel it is ready to be merged? Do you need assistance with testing any particular aspects of it?

**Comment by mathieugrimault** [comment]
Yes it can merged. I can't test sql queries because my french database differs but so far the code is ok with sybase+php7.

**Comment by demiankatz** [comment]
Thanks, @mathieugrimault; I have merged the code to master. If any configuration settings can be added or refactoring can be done to make it easier for you to manage your local database differences, please feel free to open another PR.

**Comment by demiankatz** [comment]
@mathieugrimault, note also that I've updated the HorizonXMLAPI child class to match -- see commit https://github.com/vufind-org/vufind/commit/555fbe23d567bbe09b7c34ec3f582bf9896a244a. Not sure if this is useful to you or if you're able to test it. Unfortunately, I can't test, but hopefully I did it right. :-)

**Comment by mathieugrimault** [comment]
I'm using it but haven't check the code yet, thx :)

**Pull request merged**
