### PR TITLE
Fixed captcha check in password recovery to not lose track of the aut…

### PR DESCRIPTION
**Pull request by EreMaijala**
…h method and user to recover if captcha check fails.

I think all the interaction between changePasswordAction, newPasswordAction and verifyAction is a bit messy, but this is an attempt for a minimal change to handle a failed captcha check so that it doesn't lose track of the user and authentication method.

### CODE REVIEW

**Comment by demiankatz** [comment]
@EreMaijala, once again I'm struggling to reproduce the problem that this PR addresses. I have set up ChoiceAuth and ReCaptcha, but everything seems to work fine for me both with and without this change in place. Obviously I'm either running my test in the wrong way, or else some specific detail of my configuration is protecting me against the problem. Any chance you could share some more details to help me reproduce this?

In the meantime, a couple of things:

1.) I've pushed up a commit that does a little refactoring to reuse code and make the already very long newPasswordAction() a little bit shorter. Let me know if you have any objections to this.

2.) In testing, I did run into a possibly unrelated problem where turning on the "passwordRecovery" recaptcha setting in config.ini without also turning on "changePassword" causes the "new password" form to have a non-working ReCaptcha control on it. (It displays, but you can submit the form without checking it off). I'll talk to @crhallberg about this one.

Hopefully we can get this all sorted out quickly so it can be included in 3.1.1 next week!

**Comment by demiankatz** [comment]
Update on item 2 above: Chris fixed the problem with commit https://github.com/vufind-org/vufind/commit/a284efc5f7f1033e523def61c53a8ed762aad89a.

**Comment by EreMaijala** [comment]
Thanks for the refactoring. Now I'm not sure if the changes that update the hash etc. are really necessary, but it doesn't hurt and makes sure the recovery expires.

To actually see the difference, you'll need to add newpassword.phtml to templates/Auth/Database and make it different from AbstractBase's. Then you'll see that in initial click of the verify link the user is served the template from Database, but if the captcha check fails, the one from AbstractBase is displayed instead.

**Comment by demiankatz** [comment]
Thanks for the clarification. Seems to be working as expected -- merging now.

**Pull request merged**
