### PR TITLE
Display info if no pickup locations are available

### PR DESCRIPTION
**Pull request by LuomaJuha**
Small adjustment, as if the result is an empty array, it shows an empty select without any information.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @LuomaJuha -- since I have already begun the translation process for VuFind 8.0, I'm going to defer reviewing this until we begin work on VuFind 8.1, since we're currently freezing changes that impact language files. Apologies for the less than ideal timing!

**Comment by demiankatz** [comment]
I'm also requesting a review from @crhallberg in case he has thoughts/suggestions related to the Javascript changes.

**Comment by LuomaJuha** [comment]
No worries! Not a vital pr so this can wait till that! :)

**Review by crhallberg — APPROVED** [review]
Thank you for your patience! This looks good to my eye!

**Comment by LuomaJuha** [comment]
Oh, merge conflicts @demiankatz. Will fix them.

**Comment by demiankatz** [comment]
Thanks, @LuomaJuha; let me know if you need any help!

**Comment by LuomaJuha** [comment]
@demiankatz Fixed now!

**Comment by demiankatz** [comment]
Thanks, @LuomaJuha -- however, I think a little more work is needed. We're trying to move away from having explicit FontAwesome classes in our Javascript code, in order to make icons more configurable and less platform-specific. The changes in #2133 were part of this work, and your merge seems to have undone them. Can you revise the icon handling to match #2133 again?

**Comment by LuomaJuha** [comment]
Oh, must have missed that line. Will check tomorrow!

**Comment by demiankatz** [comment]
Thanks, @LuomaJuha, looking good now (and passing all tests)!

**Pull request merged**
