### PR TITLE
Update help translation for czech language

### PR DESCRIPTION
**Pull request by xmorave2**

### CODE REVIEW

**Comment by xmorave2** [comment]
This is still draft, I'd like to have my colleague to look at it first.

**Comment by demiankatz** [comment]
Thanks, @xmorave2 -- just let me know when you think it's ready to merge.

**Comment by xmorave2** [comment]
@demiankatz Now it is ready to merge

**Review by demiankatz — APPROVED** [review]

**Comment by demiankatz** [comment]
Thanks, @xmorave2 and @JanaKurfurstova!

**Pull request merged**
