### PR TITLE
Resolver driver for German resolver service ReDI (http://www-fr.redi-bw.de/)

### PR DESCRIPTION
**Pull request by lahmann**
This is a resolver driver for the German resolver service ReDI (http://www-fr.redi-bw.de/) which offers similar services as SFX or 360Link.
It's ready to use but needs configuration via the [OpenURL] section in config.ini.

### CODE REVIEW

**Comment by jochen-lienhard** [comment]
Hello Andre,
it seems it does not work? Can you add the config too? Did you add this parameter: url_ver=Z39.88-2004? Do you plan to support the embedded version?

In vufind 1.3 we used a smarty plugin to cut a part from the response, the 'service' div.

**Comment by lahmann** [comment]
Hi Jochen,

our [OpenURL] section in config.ini looks like this:

```
[OpenURL]
url             = "http://www.redi-bw.de/links/yourReDIid?rl_site=yourReDIid"
rfr_id          = www.yourreferrerid.de
resolver        = redi
window_settings = "toolbar=no,location=no,directories=no,buttons=no,status=no,menubar=no,scrollbars=yes,resizable=yes,width=550,height=600"
show_in_results = false    ; include in search results
show_in_record = false     ; include in core record metadata
show_in_holdings = true    ; include in holdings tab of record view
embed = true
replace_other_urls = true
```

Embedding works already - if you set it to `true` the ReDI-response will be parsed and embedded on clicking on the "more information" link in holdings tab. If it's set to `false` a pop-up will open upon clicking on that link, loading the ReDI-site for that record.

The `url_ver=Z39.88-2004` parameter is already set in your RecordDriver in the method `getDefaultOpenURLParams()` (e.g. in SolrDefault).

**Comment by jochen-lienhard** [comment]
It works only it I add url_ver=Z39.88-2004 to the url parameter. By the way ... 

[OpenURL]
; If a resolver base URL is enabled, it will be used to link ISSNs to your link
; resolver and to access articles in Summon if that module is enabled.  Earlier
; versions of VuFind included some parameters as part of the URL; at this point,
; any extra parameters will be ignored -- please provide only the base URL.

url should only be the baseURL. If you use it in the result-list the more options link do not work.

**Comment by lahmann** [comment]
Jochen, you are right - the `url_ver` parameter is missing. I mixed it up with the parameter `ctx_ver`, which gets set by default in SolrDefault. I have added the missing `url_ver` parameter to SolrDefault as `url_ver` is mandatory for OpenURLs if I read the NISO implementation guidelines correctly (cf. p.18 http://alcme.oclc.org/openurl/docs/implementation_guidelines/KEV_Guidelines-20041209.pdf) - I wonder why it's missing and why this hasn't been noticed earlier (maybe the ReDI implementation is very strict?).

I adjusted the handling of the baseURL accordingly, so no parameter is required in the baseURL (`rl_site` was obsolete anyway).

The new (working) config.ini settings:

```
[OpenURL]
url             = "http://www.redi-bw.de/links/yourReDIid"
rfr_id          = www.yourreferrerid.de
resolver        = redi
window_settings = "toolbar=no,location=no,directories=no,buttons=no,status=no,menubar=no,scrollbars=yes,resizable=yes,width=550,height=600"
show_in_results = false    ; include in search results
show_in_record = false     ; include in core record metadata
show_in_holdings = true    ; include in holdings tab of record view
embed = true
replace_other_urls = true
```

**Comment by demiankatz** [comment]
André,

Thanks for sharing this. A few things:

1.) Adding the url_ver parameter breaks several tests. That's part of the reason Travis is failing. Hopefully it should be very simple to fix -- just add the parameter to the expectations of the tests.

2.) There are also some style problems noted by Travis that should be fairly easy to adjust.

3.) I see you're doing some string replacement on the » character. What is the purpose of this? Is it some kind of character encoding correction? If so, could this be better done with mb_convert_encoding?

4.) These issues aside, I'll wait for confirmation from Jochen that this is working for him as well before merging.

Please let me know if I can be of any assistance with items 1-3!

**Comment by berndoberknapp** [comment]
Hi,

On 05/04/2015 04:18 PM, Demian Katz wrote:

> 3.) I see you're doing some string replacement on the » character. What is the purpose of this? Is it some kind of character encoding correction? If so, could this be better done with mb_convert_encoding?

the method checks if the text for one of the links includes a * which
indicates that there is additional information for the link in a
footnote. The "right-poiting double angle quotation mark" is used as the
text for the link and the "non-breaking space" as a place-holder for an
icon. I'm not sure why they are removed before applying the regex,
actually they shouldn't make a difference.

My recommendation - as the author of the ReDI»Links link resolver -
would be to check for <sup>*</sup> which indicates a footnote instead of
* which also might be included in the text for the link (that's not very
likely but it cannot be excluded).

I think using xpath to extract/check for the data would be a better
choice than traversing the XML structure, because that's easier to adapt
in case we have to change the structure of the page.

Best regards,
Bernd

-- 
Bernd Oberknapp
Gesamtleitung ReDI

Albert-Ludwigs-Universität Freiburg
Universitätsbibliothek
Rempartstraße 10-16 | Postfach 1629
D-79098 Freiburg    | D-79016 Freiburg

Telefon:  +49 761 203-3852
Telefax:  +49 761 203-3967
E-Mail:   bo@ub.uni-freiburg.de
Internet: www.ub.uni-freiburg.de

**Comment by demiankatz** [comment]
Thanks for the input, Bernd!

**Comment by lahmann** [comment]
Demian, thanks for looking into this!

I've addressed 1 & 2 in the second last commit.

Bernd, thanks for your input, too!

After your remarks regarding usage of XPaths I gave it a try and rewrote the whole driver to use XPaths. Although the document structure is still tricky to handle the code looks much cleaner now and should be easier to maintain/adjust in case of Redi-updates. Thanks for this suggestion!

The additional information strings - marked by `<sup>*</sup>` and somehow comparable to footnotes for some links - are added as `coverage` information for each link (if necessary). I found this solution the most appropriate for this additional information as the current AjaxController does not support a "Info" `service_type` or alike. But I am open minded for any idea handling those additional information strings better.

Replacing the "right-poiting double angle quotation mark" is still necessary as this character is part of the textual Redi-output being used for the link-titles and as this character is useful as a link-button on the Redi-website it is not needed when embedded into VuFind.

Please let me know if the new version of the driver works as expected and thanks again for all your feedback!

**Comment by lahmann** [comment]
Oh no, again style-issues... I'll try to fix those tomorrow.

**Comment by demiankatz** [comment]
Thanks for the progress, André. If you ever get frustrated with the style issues, feel free to give me write access to the branch and I can help -- I have a lot of experience with these things.

In any case, I'll wait for more feedback from Bernd and/or Jochen before taking further action myself.

**Comment by lahmann** [comment]
Demian, thanks - actually I would like to embrace your offer instantly as I have just tried to solve the code-style issues but fail with every attempt... you should be able to write to this branch now.
Let me know if you have trouble accessing the branch.

**Comment by lahmann** [comment]
Jochen and me had a short conversation via email and came up with two suggestions:

1) all resolver-links are currently opened in the same browser window (bootstrap3 theme) - wouldn't it be better to open it in a new tab/window?
2) the ReDI-service provides additional status-lights indicating the access rights to the linked ressource. This information should be available when embedded in VuFind. We would like to suggest to extend the resolver-link-model with the field `style` which could be used to pass styling information to the template resulting e.g. in displaying the appropriate status light by style.

Any ideas/comments on this?

**Comment by lahmann** [comment]
Demian, thank for the code style fixes!

**Comment by demiankatz** [comment]
Hopefully I haven't broken anything! Some of that was a bit tricky -- sometimes you just have to use a variable to make the style fixing easier. In at least one case (the xpath expression) I think that actually makes the code a little better anyway, since avoiding repetition of complicated strings never hurts!

**Comment by lahmann** [comment]
Yes, I agree - thanks for your help! And no, everything works fine - I just tested the code.

**Comment by demiankatz** [comment]
In response to the two latest comments:

1) Much of VuFind is designed on the philosophy that users should choose whether or not to open things in new windows, because some people find automatic window/tab opening annoying. However, this is always a controversial topic. It might make sense to add a configuration option to set the target of link resolver links so either preference can be supported.

2.) Rather than passing styles, perhaps it would be better to pass CSS classes so that the styling could be customized on a theme-by-theme basis. If we take this route, the class names should follow some convention to avoid conflicts.

Also, a couple other comments:

3.) You might want to change your private method to protected (just in case somebody wants to override it locally... fairly unlikely in this case, but I can imagine people might use it as a hook for other types of string manipulations).

4.) It might be worth adding a unit test -- then if the Redi interface changes in the future, you could update the fixture and see exactly what breaks. However, if this is too much work, I can live without it -- I won't hold up merging the PR unnecessarily.

**Comment by lahmann** [comment]
Demain, thanks for your comments.

1) This sounds reasonable - `open_embedded_links_in_new_window = true` is quite long but it would do the trick.

2) Yes, I actually meant classes but wrote styles... sorry - so absolutely no objections.

3) Providing this function as a hook sounds reasonable - I'll refactor it to `performStringManipulations` to reflect the more general approach.

4) Yes, tests would be nice - although the amount of xpaths is not that big so that structure changes in ReDi-responses should be fixable without big effort. Anyway, I'll see if I find the time for implementing tests.

**Comment by demiankatz** [comment]
Thanks, André. If you want to take time on the "open in new window" feature, you might as well make that a separate pull request, since it doesn't directly relate to this feature. The classes thing might also be better dealt with separately -- while that will impact the Redi driver, it will also touch other parts of the code, so it might be cleaner to get this merged first and then approach that as a second pass.

For the remaining two items, just let me know when you're finished to your satisfaction, and I think we can merge this to master.

Thanks!

**Comment by lahmann** [comment]
Demian, a quick heads-up on implementing tests for the redi resolver driver: I'm not sure if I'm on a right track as I haven't implemented whole new tests yet and there's no resolver driver test-class existing to use for guidance. Would you be so kind to take a brief look at `RediTest.php` and give me some advice on instantiating the Redi resolver driver in the test-context?
Thanks!

**Comment by berndoberknapp** [comment]
On 05/07/2015 04:52 PM, André Lahmann wrote:

> After your remarks regarding usage of XPaths I gave it a try and rewrote the whole driver to use XPaths. Although the document structure is still tricky to handle the code looks much cleaner now and should be easier to maintain/adjust in case of Redi-updates. Thanks for this suggestion!

I would suggest to use XPaths that are more independent from the
document structure like //dd[@class='doi_d'] for the DOI node and then a
relative XPath .//@href for the link. I could also add additional
classes or ids if that makes extracting the links and texts easier.

Best regards,
Bernd

-- 
Bernd Oberknapp
Gesamtleitung ReDI

Albert-Ludwigs-Universität Freiburg
Universitätsbibliothek
Rempartstraße 10-16 | Postfach 1629
D-79098 Freiburg    | D-79016 Freiburg

Telefon:  +49 761 203-3852
Telefax:  +49 761 203-3967
E-Mail:   bo@ub.uni-freiburg.de
Internet: www.ub.uni-freiburg.de

**Comment by demiankatz** [comment]
André,

Thanks for the progress on this! A few comments on the test:

1.) I think you can safely eliminate the VuFindTest\Unit\ResolverDriverTestCase abstract class (and the constructor of your test case, which seems related to it). I don't expect that there will be so much commonality between resolver driver tests that we need to build a common base... and we can always refactor later if commonalities do appear during test development.

2.) Since your driver doesn't use VuFind's HTTP service, you can simplify your createConnector() method. Continue to create the adapter as-is, but then in place of the \VuFindHttp\HttpService instantiation, you can do:

<pre>
$client = new \Zend\Http\Client();
$client->setAdapter($adapter);
</pre>

and then pass the $client object as the second parameter of your Redi object. I think that will at least get you further along!

Please let me know if you need more assistance.

**Comment by demiankatz** [comment]
(Sorry about closing the PR; hit the wrong button by accident).

**Comment by lahmann** [comment]
Demian, thanks for your help! I've finished implementation of the test and all is working fine.

Bernd, thanks for your feedback and especially for offering your help in terms of adding classes and ids to the Redi-output. I think this would definitely make some things easier.
I would suggest to work on these optimizations in another pull request - maybe in combination with passing status-classes from the Redi-driver to the frontend? What do you think? (also @demiankatz :))

**Comment by demiankatz** [comment]
André,

This looks fine to me, and I agree that it makes sense to commit the base version before we modify either the Redi service itself or the interface between the resolver driver and the VuFind front end. I'm happy to merge this if you think it's ready, but I wasn't sure if you wanted to simplify/generalize some of the XPaths as Bernd had suggested first. Either way is fine, just let me know when you're ready for the merge.

thanks,
Demian

**Comment by lahmann** [comment]
I included Bernd's suggested simplifications for the DOI-elements. Simplifying the XPaths for the other elements should be postponed to the time when modifying the Redi service as making the response document structure more explicit will be reflected in more general XPaths.
As Travis is not complaining about the latest commit, I think the Redi-driver is ready to be merged.

Demian, Bernd, Jochen - thanks a lot for all your help!

Best,
André

**Comment by demiankatz** [comment]
Done -- merged to master with a flatted commit to reduce complexity of commit history. Thanks again for all the work!

**Pull request closed without merging**
