### PR TITLE
Refactor BrowZine code to use search service.

### PR DESCRIPTION
**Pull request by demiankatz**
More code split off from #2036.

TODO
- [x] Update changelog when merging

### CODE REVIEW

**Comment by demiankatz** [comment]
@aleksip, more of the same here, and once again, I have tested that the refactored code works as expected with the real BrowZine service.

**Comment by demiankatz** [comment]
@aleksip, I've updated this one to match #2090, so I think it's ready to go as well, with your approval! I'll do some more work on #2092 and #2093 tomorrow.

**Review by aleksip — COMMENTED** [review]
Looks good to me, with the constructor returns removed.

**Comment by demiankatz** [comment]
Oops, that was silly of me -- thanks for the catch, @aleksip!

**Pull request merged**
