### PR TITLE
Fix visibility of off-canvas toggles.

### PR DESCRIPTION
**Pull request by EreMaijala**
Some recent changes caused off-canvas toggles to display also on wide screens. This change uses `!important` to override any other settings (very much alike `.visible-*` etc.).

### CODE REVIEW

**Comment by demiankatz** [comment]
@EreMaijala, do you think it's worth reviewing and merging #3565 prior to merging this PR, so we can add a test case to the ResponsivenessTest I introduce there to prevent future regressions of this functionality?

**Comment by demiankatz** [comment]
(I should be clear: I'm not asking you to do the reviewing and merging, as that work is already assigned -- just wondering if we should wait for it before proceeding here, or if this is too urgent to wait).

**Comment by EreMaijala** [comment]
@demiankatz Waiting for #3565 makes sense to me. I can add tests here after it's merged.

**Review by demiankatz — CHANGES_REQUESTED** [review]
I've just merged #3565, so this is ready for tests whenever you have time.

**Comment by EreMaijala** [comment]
Test added!

**Review by demiankatz — APPROVED** [review]
Thanks, @EreMaijala, looks good! I made one small adjustment to fix an existing test name that I had copied and pasted inappropriately in the first place. :-)

**Pull request merged**
