### PR TITLE
Improved ILSException handling so that the user gets a meaningful mes…

### PR DESCRIPTION
**Pull request by EreMaijala**
…sage instead of being asked to enter the ILS credentials.

This is the first stab at improving ILS error handling so that the user gets a meaningful error message and the UI elements such as MyResearch menu stay in place. This is easy to test: just change the ILS driver config enough to make the connection fail (e.g. change service setting in VoyagerRestful.ini).

Included is a blind stab at fixing patronLogin() of Aleph and NewGenLib. As far as I can see the other drivers work properly and return null for a login failure caused by bad credentials.

### CODE REVIEW

**Comment by demiankatz** [comment]
A few comments/questions:

- I reverted changes to MyResearchController.php as they seemed to serve no purpose (a comment was unnecessarily reformatted, and a "use" statement was added for a class that was never used).

- I've added the flashmessages call to the fines template in master and merged that back into this branch to reduce the number of diffs. That's clearly an oversight that we might as well address right away, and separately from the rest of this complexity.

- I'm not sure I understand the purpose of your changes to the NewGenLib driver. The existing code is messy and hard to read (among other problems), but I don't see how your changes have any impact on whether or not it throws an ILSException. Can we just leave it as-is for now?

- I'm pretty sure the Aleph changes will not work, and possibly for multiple reasons: I don't think the string being checked for is going to match, since it may be necessary to account for the "Xserver error:" prefix. Also, when a PHP try block has multiple catch blocks, they get evaluated in the order presented... you currently have the catch-all \Exception catch before the more specific ILSException catch, which means that PHP will never drop through to the ILSException block. Bottom line: this is complicated enough that I think we need to track down an Aleph user to help us with cleaning up the driver.

How urgent is this one for you? Given the Aleph complications, I think it may be difficult to get this PR merged before the 3.0 code freeze... but if it's really critical, we can certainly consider letting it in a little late. I'm just concerned that this is a fairly low-level change that could use a bit of time for unexpected consequences to be discovered.

**Comment by demiankatz** [comment]
Regarding Aleph: Václav Rosecký has very kindly offered to look into this in the very near future. We may have a fix in the next day or two.

**Comment by demiankatz** [comment]
Okay, I've received an official Aleph fix, have merged it to master, and have merged master back into this branch. So now the only untested ILS driver change is NewGenLib, which I'm hoping we may be able to simply revert for now, given that I can't see the problem with null returns there. I'll try to find time to look at this more closely tomorrow if you want to get this into 3.0. I think I'm nearly caught up, so I would like to freeze code very soon... but it can slide a day or two given recent exceptional circumstances.

**Comment by EreMaijala** [comment]
This is something we really need, so getting this in would be awesome. The problem with the current NewGenLib driver is that it will probably return an empty array instead of null. The checks it's making before returning null are probably never reached as the select statement doesn't return anything. It has other more pressing issues, though, which you can see from the latest commit. There are probably also other functions with user-entered input mishandled, but this is the most important one since it doesn't require you to be logged in.

**Comment by demiankatz** [comment]
I've merged some pieces of this to master to start making this PR smaller and more readable. A couple of issues I ran into today while testing the remaining code (ILS failures tested by garbling the Oracle connection settings in VoyagerRestful.ini):

1.) If I create a new account and try to establish ILS credentials for the first time (say, to access MyResearch/Profile), I get the same error whether I enter bad credentials on a good connection or good credentials on a bad connection. Is this scenario supposed to be able to identify a fatal error and display a different message?

2.) When using driver-based holds, I get a fatal "Cannot call method: VuFind\ILS\Driver\VoyagerRestful::patronLogin" error on the record holdings tab when my ILS credentials are bad. I assume that this is supposed to be failing more gracefully!

Please let me know if I can be of any further assistance in getting this stuff sorted out.

**Comment by EreMaijala** [comment]
Thanks!

1.) Should be fixed now. 

2.) I couldn't reproduce. If I e.g. modify cat_username in the user table, I just don't get any hold links (which is suboptimal as it would be nice to tell the user, but that's how it has worked also before). Perhaps this only happens with specific settings. As far as I can see, though, the only place where patronLogin is called in relation to holdings is Holds::getHoldings() and there it's already guarded by a try..catch, so I'm obviously missing something. Can you get a call stack?

**Comment by demiankatz** [comment]
Manually merged to master. Thanks!

**Pull request closed without merging**
