### PR TITLE
Fail with exception if a MARC file fails to load during merge operation.

### PR DESCRIPTION
**Pull request by demiankatz**
TODO
- [ ] Should we add a command line switch to ignore errors?

### CODE REVIEW

**Comment by demiankatz** [comment]
@EreMaijala, it seems based on discussion in vufind-tech that we can just merge this as-is, unless you have concerns!

**Review by EreMaijala — APPROVED** [review]
@demiankatz Agreed, and no concerns.

**Comment by demiankatz** [comment]
Thanks, @EreMaijala! I decided to add test coverage to this, which ultimately prompted me to make the code a little more sophisticated. Since tests are passing, I feel pretty safe merging this version, but if you take another look and have concerns, please let me know.

**Review by EreMaijala — APPROVED** [review]
Even better!

**Pull request merged**
