### PR TITLE
Removed bundled dependencies; adjusted Phing/Travis tasks.

### PR DESCRIPTION
**Pull request by demiankatz**
- [x] When merging, create and document legacy/bundled-dependencies Git branch.
- [x] When merging, add Composer wiki page with basic instructions, notes on Git issues, etc.

### CODE REVIEW

**Comment by guenterh** [comment]
@demiankatz 
Hi Demian
as I promised in the last developer call I wanted to take a look into the pull request. Sorry, but unfortunately I haven't merged a pull request from another account before. I just forked the lastest VuFind rep into my own account
https://github.com/guenterh/vufind
Do you have an idea how to merge it? Haven't seen it on GitHub and a quick Google didn't provide the wanted results
Günter

**Comment by lahmann** [comment]
Just a short notice: `php composer.phar install` fails at the moment as Validate_ISPN-0.6.1.tgz cannot be downloaded:
```
 [Composer\Downloader\TransportException]                                                              
  "http://pear.php.net/get/Validate_ISPN-0.6.1.tgz" appears broken, and returned an empty 200 response  
```
This is probably related to http://blog.pear.php.net/2015/12/07/server-outage-1/

> What’s currently missing:
> ...
> – old package files released more than 6 years ago

(Validate_ISPN-0.6.1 was released on 2007-03-27)

**Comment by demiankatz** [comment]
@guenterh, you should be able to merge the no-bundled-dependencies branch from the main VuFind repo in order to try this out. (Probably something like `git remote add upstream https://github.com/vufind-org/vufind.git` followed by `git fetch upstream` followed by `git merge upstream/no-bundled-dependencies`).

@lahmann, what a nuisance! We bundled dependencies in the first place to avoid situations exactly like this one. The Validate_ISPN dependency is not important, though -- it's an optional dependency of File_MARC which isn't actually used by any active VuFind code. You can just delete that to move forward for now. In the long term, I've been trying to work with the maintainer of File_MARC to get that moved from PEAR to Packagist (and, perhaps, to replace the ancient Validate_ISPN dependency with something newer -- perhaps even VuFind's own ISBN library). It's just slow going coordinating with third-party developers who have other priorities!

**Comment by demiankatz** [comment]
Good news! Looks like File_MARC actually has become accessible through Packagist, so I've adjusted the Composer configuration to work without hitting the PEAR network. That should help with the current problem!

**Comment by guenterh** [comment]
Hi Demian
I looked into the related branch (didn't use this pull request). Guess it's the same.
For me it looks fine. I haven't had any problems to pull all the dependencies via composer and after finishing the installation process I was able to start the application together with our merged modules without any problems. Seems packagist is quite stable as a central repository.

 As additional note:
On our deployment host (within the DMZ of our institution) in one case we had problems using composer for installing all our dependencies (not VuFind core). The problem was: Our firewall doesn't allow the Git protocol and one of the dependency used it for additional transitive dependencies. I could solve the problem by configuring the desired github-protocol used by composer  ([github-protocols] [https]) This might be a trap for other users too. I made the configuration global but guess shoud be possible to do it locally for a single repository in the same way. Haven't scanned this article https://getcomposer.org/doc/03-cli.md#config in it's entirety

Günter 

Within our team we have to discuss how to treat our additional local dependencies. By now @maechler created an additional composer repository in the local directory.

I can't remember exactly the ideas you have with this dependency - less branch. 
Do you want to provide the future master branch entirely without the dependencies in vendor or as an additional option?
My proposal in Konstanz was: deploy the master without dependencies and provide e.g. two  releases:
a) without any dependencies  
b) for easier deployment a release which include all the additional stuff
What's your idea?
Günter

@edelm fyi

**Comment by demiankatz** [comment]
Glad to hear things are working for you!

It's good to be forewarned about the possible issues with the Git protocol. Obviously, I try to favor Packagist-hosted packages whenever possible, but as you say, once in a while, loading from Git turns out to be unavoidable. We should create a Composer wiki page for notes like this once we've merged this. I'll put a to-do item in the description of the PR.

To answer your question about future plans, I expect to merge this to master and thus in future have a master branch entirely without dependencies in vendor. Users who pull their code from Git will be responsible for running Composer update after pulling. Users who don't want to deal with Git will be encouraged to download our pre-packaged releases, which will bundle all dependencies in the zip/tar.gz/deb files.

**Comment by lahmann** [comment]
We just tested our deploy-chain with this branch and ran into an issue that Github asks for an OAuth-Token in order to proceed (while exceeding the Github API rate limit) (this does happen only on our deploy-machines and not locally as my workstation user is already authorized by Github via SSH keys).

A workaround is either configuring a token for composer globally:
```
composer config --global github-oauth.github.com <TOKEN>
```
or defining the token in the project's composer.json:
```
{  
  "config": {
    "github-oauth": {
      "github.com": "<TOKEN>"
      }
    }
}
```
(see also https://github.com/composer/composer/issues/3542#issuecomment-67623002)

I am sceptical about the composer.json variant as tokens are essentially like passwords and should be treated like that - i.e. not publishing it on Github by pushing a project's composer.json.
The first variant requires some additional setup on the machines composer is supposed to be run, which adds complexity.
Unfortunately I have not found a better solution to this issue - at least not by following the Github developers-guide on how to manage deploy keys (https://developer.github.com/guides/managing-deploy-keys/).

Any other ideas, thoughts?

**Comment by guenterh** [comment]
Andre, are you using git or https protocol?
I haven't realized your problems with https so far.
Ok I have to confess by now I made my own tests (with vufind) only on my local machine, where I'm working with git and ssh-key. Have to repeat it on our deployment host where we are using https without a key and authentication.

With another repository for the administration of our 800 institutions where we don't have bundled dependencies in the same way (https://github.com/swissbib/libadmin/blob/master/composer.json) as in your current vufind branch (although less dependencies) I haven't had any problems on our deployment host.

Günter

**Comment by lahmann** [comment]
Günter,
thanks for your comment - I just did a rerun of our deploy-chain and the problematic dependency entry in composer.json is
```
https://github.com/ahand/mobileesp
```

So, yes we are requesting via https. :)

I wonder where we are using MobileESP for detecting mobile devices - isn't that solved by css media-query?

Best,
André

**Comment by guenterh** [comment]
Hi Andre, interesting - the various libraries are going to be visible if they  get noticed...
Is it possible that this library has transitive dependencies which use git as default? I had this issue with https://github.com/swissbib/libadmin/blob/master/composer.json#L15 and I could solve it by setting https as the default protocol   (https://github.com/vufind-org/vufind/pull/501#issuecomment-163528676) 
composer config --global github-protocols https
Günter

**Comment by lahmann** [comment]
Günter, good idea - I'll give it a try tomorrow. Although I'm afraid that won't help, as this package should not introduce any further dependencies according to https://github.com/ahand/mobileesp/blob/master/composer.json.
Best,
André

**Comment by demiankatz** [comment]
Regarding the reason for the inclusion of MobileESP: it's not used by default, but if you switch on the "mobile_theme" setting in config.ini, it is used to determine which theme to load -- the "standard" or "mobile" version. I've been talking to the author of the package about registering with packagist, which would eliminate the need for GitHub communication around the package -- but I'm not sure if or how quickly that will actually happen.

However, regardless of whether we can eliminate this specific problem by moving this specific package to Packagist, we still ought to make sure we have a good "best practice" for dealing with the general issue, as it's always possible that new dependencies will arise that depend on GitHub. (Indeed, the recent change in master to eliminate PEAR dependencies moved one package to a GitHub repo... so that's another thing to consider, though again that particular package is of very little importance to 99% of users).

Also, Günter's point about transitive dependencies might apply to some other package -- it's possible that something hosted on Packagist could in turn depend on something hosted elsewhere.

In any case, good luck, and let us know what happens when you try the configuration change.

**Comment by lahmann** [comment]
Thanks Demian for contacting the author of MobileESP!

We tested the suggested configuration change and unfortunately it did not help. Either way, by configuring it globally via cli command `composer config --global github-protocols https` and by defining it in composer.json
```
{
    "name": "vufind/vufind",
    ...
    "license": "GPL-2.0",
    "config": {
            "github-protocols": ["https"]
        },
    ...
}
```
in both cases we were asked for a OAuth token.

It looks like there is no way around it - as soon as you hit the rate limit of 60 requests per hour (without authentification) [1] composer will ask for an OAuth token.
A "best practise" would be great, although I have my doubts that we will get around the step "configure a github deploy token on your machine" - especially as I am still wondering how the composer install call can exceed 60 requests per hour if there's only one github-dependency (probably because of transitive dependencies and each communication-action of composer with github counting as request).

[1] https://developer.github.com/v3/#rate-limiting

**Comment by demiankatz** [comment]
It's possible that you're hitting the rate limit not because of downloading packages from GitHub but instead because of negotiating with GitHub to search for packages due to the 'vcs' section of composer.json (see https://github.com/vufind-org/vufind/blob/master/composer.json#L17). It might be an interesting test to remove all of the MobileESP stuff from composer.json -- the 'vcs' repository and the actual dependency line -- to see if that gets rid of the messages, or whether they are actually coming from somewhere else.

If the problem is solely caused by the 'vcs' settings, there are other ways we could retrieve that dependency that wouldn't have to use the GitHub API, and we might be able to work around the problem... but if it's due to transitive dependencies, then we're pretty much stuck with OAuth.

**Comment by lahmann** [comment]
I tried that already and can confirm that everything works fine by removing from composer.json the lines:

```
       {
            "type": "vcs",
            "url": "https://github.com/ahand/mobileesp"
        }
```

**Comment by demiankatz** [comment]
I see that the MobileESP package is now available on Packagist, so that setting is no longer necessary. I've removed the offending lines and merged the latest master into this branch.

I think that may actually solve the problem, though I'd recommend trying again with the latest code after running `composer clear-cache` just to be sure that even with an empty cache, you're not hitting the GitHub API.

If this truly has solved the problem, we may be ready to merge -- though of course the problem could recur if we add another 'vcs' repository in the future. Obviously, that's something we should strongly discourage (and most packages really ought to be on Packagist these days), but I imagine it's not completely impossible, especially if we have to load some vendor's integration library for a new search backend, or something along those lines.

**Comment by lahmann** [comment]
Thanks Demian, that solves the OAuth-problem. Our deploy-chain seems to be working fine with the current branch.

Regarding merging into master, although I do not have any pending issues regarding the removal of the bundled dependencies, maybe we should tag the last commit before removing the bundled dependencies in order to make testing with/without bundled dependencies a little bit more comfortable?

**Comment by demiankatz** [comment]
Yes, that's a good idea -- we can create a legacy/bundled-dependencies branch to add to the list (along with retired themes, etc.).

**Comment by lahmann** [comment]
Sounds great!

Alright, I am off for the holidays -- I wish you all a merry Christmas and a great start into 2016! See you next year! :)

**Comment by demiankatz** [comment]
Wiki page added: https://vufind.org/wiki/development:recommended_tools:composer

**Comment by demiankatz** [comment]
Manually merged.

**Pull request closed without merging**
