### PR TITLE
fix display of pickup locations until API supports it

### PR DESCRIPTION
**Pull request by bpalme**
this makes minor edits to the getPickupLocations to turn the array into a hash.  Then in the getMyHolds function, use the hash to display the display name.  If you want to include this but feel it should be done differently, feel free to change it however.

### CODE REVIEW

**Comment by demiankatz** [comment]
@bpalme, your approach is not illegal, but it would make this driver significantly different from all the others in its approach and might lead to confusion. I've created a helper method to allow you to do the same thing without adding special indexing to the pickup array. It's a little less efficient, of course, but I don't think it will matter. It will also allow more graceful handling of the scenario where the code is not in the pickup array for some reason (unlikely, but doesn't hurt to have a fallback).

Of course, I can't test this... so please let me know what you think and whether it causes problems. I'd also be interested in @EreMaijala's input if he has time to look.

**Comment by demiankatz** [comment]
@bpalme, one other thing: I see that the code is setting the pickup location into a variable, but then that variable is not being used. Is a line of code missing to include this in the return array?

**Comment by demiankatz** [comment]
@bpalme, on further examination, all of this may be unnecessary. If you set the 'location' value in the getMyHolds array to a pickup location ID, VuFind should automatically convert this into a display name for you (see https://github.com/vufind-org/vufind/blob/master/themes/bootstrap3/templates/myresearch/holds.phtml#L115) -- did you try that yet? Maybe this can all be simplified to a single-line fix.

Sorry for all the comments before realizing this. :-)

**Comment by bpalme** [comment]
Yes.  that one line change seems to be working for me.

**Comment by EreMaijala** [comment]
@bpalme Could you explain a bit more about what the original issue was? 
@demiankatz Your change makes otherwise sense, but 'location' is now being set twice in the array.

**Comment by demiankatz** [comment]
@EreMaijala, oops, how did I miss that?

@bpalme, is the issue that 'name' is not always set? Would it make sense to do something like `'location` => empty($entry['pickupLocation']['name']) ? $entry['pickupLocation']['code'] : $entry['pickupLocation']['name'],`?

**Comment by bpalme** [comment]
@EreMaijala 
The Sierra API doesn't return the name for holds pickup locations.  It returns the code and the branch name.  The pickup hold locations use the same code as the branches, but can have a different name.  In our case it returns "circulation desk" instead of "Downtown Library".  I assumed that this is related to your note in the config file about not being able to retrieve Hold pickup locations via the API.  Maybe I should add a ticket with III for that...

My approach was to use your configuration of the pickup locations, create a hash and lookup the name using the code.  Demian pointed out that if you set the code value that comes back from the API instead of the "name", the template takes care of it somehow.  I didn't really dig too deep; it seemed to work for me so I left it.

So, the short answer is no, it's not that the name is missing, it's just incorrect and I don't think your change above would work for us.  

@demiankatz 
Instead of adding it, I just changed it a few lines up where location is being set in the array.

**Comment by bpalme** [comment]
I just tried to submit a ticket to III but it errored out twice.  Sigh.  I tried.

**Comment by EreMaijala** [comment]
@bpalme Thanks for the clarification. I did not realize the location name is not always the same as the pickup location name. Pretty confusing! In that case the current change makes sense, though it would also be a good idea to add a comment about the wrong name in the 'name' element.

**Comment by demiankatz** [comment]
@bpalme, @EreMaijala, I have fixed the duplicate code and added a comment. Any objections to merging now? Let me know if you want to tweak the comment text first!

**Comment by EreMaijala** [comment]
@demiankatz Thanks, no objections from me!

**Comment by demiankatz** [comment]
Great, merging!

**Pull request merged**
