### PR TITLE
Lots of bug fixes. More consortial support.

### PR DESCRIPTION
**Pull request by cedelis**
Add consortial support to Renew and Cancel requests.

### CODE REVIEW

**Comment by demiankatz** [comment]
Looks like you're still working through some style problems. Let me know if you need any help with that. Given the limited number of users of this code, I have no problem merging this once everything is sorted out, as long as you're ready for it to go forward.

One other very minor note: the first diff you see if you look at the "files changed" tab here is a reversion of a correction to a wiki link in the comments. Can you put it back to the correct version? (I can also take care of it if that's easier... but if you're in the middle of editing the file anyway, you can probably do it faster).

Thanks!

**Comment by cedelis** [comment]
I'll take care of the link, thanks!
I'm still tackling styling issues ;-) Once they pass, I guess I'll be done
(I hope!).

**Comment by demiankatz** [comment]
Much appreciated. I'll take a closer look at this once the Travis build passes... but if you run into any tricky things that are difficult to style correctly, let me know and I'll be happy to offer advice.

**Comment by cedelis** [comment]
Now that I've finally decided to install and use phpcbf, I think it will
finally succeed in passing the styling tests. Why did I even try to do it
manually?

**Comment by cedelis** [comment]
Hmm... I've fixed the styling issues, but the build still fails. Not sure
why.

**Comment by demiankatz** [comment]
There are actually two different tools for style checking, each dealing with different issues... so you've taken care of all of the phpcs problems, but php-cs-fixer is still complaining about one issue. This is easy to fix -- php-cs-fixer, like phpcbf, automatically fixes everything. I'll take it from here, but for future reference, you might want to make sure you have php-cs-fixer and Phing installed so you can run the `phing php-cs-fixer` task to take care of these things.

**Comment by demiankatz** [comment]
Okay, php-cs-fixer'ed and manually merged to master (to simplify commit history).

**Comment by cedelis** [comment]
Thanks. I appreciate the help! Next time I hope to make your job a little
easier.

**Comment by demiankatz** [comment]
Not a problem -- it takes a while to get used to all the tools!

**Pull request closed without merging**
