### PR TITLE
Fixed the Finnish and Swedish translations for Backtrace.

### PR DESCRIPTION
**Pull request by EreMaijala**

### CODE REVIEW

**Comment by EreMaijala** [comment]
Hmm.. I don't quite agree with the ExtendedIniNormalizerTest failure. I'd rather have line feed at the end of every file (and indeed my editor makes sure of it). Or am I reading it wrong? I thought it should balk about sv.ini too if it's the trailing line feed.

**Comment by demiankatz** [comment]
The idea of the ExtendedIniNormalizerTest is that whenever you edit a language file, you should run:

<pre>
cd $VUFIND_HOME; php public/index.php language normalize languages
</pre>

to format everything consistently. If any file fails to match, the test fails... so the reason it's complaining about fi.ini and not sv.ini is that it failed on fi.ini and never got around to checking sv.ini.

I'll look into adjusting the normalizer to include an end-of-file line break and re-running the normalization in the near future; I think that's a reasonable adjustment.

**Comment by EreMaijala** [comment]
Ok, I normalized the files now, but it would be really good to include the trailing LF.

**Comment by demiankatz** [comment]
Okay, the normalizer is adjusted here: https://github.com/vufind-org/vufind/commit/7f27dd45e6a888a1976cb8f267f2c6d1e513ea80. I'll take care of merging this into master and renormalizing it. I don't want to cause any additional headaches for you!

**Comment by demiankatz** [comment]
Done!

**Pull request closed without merging**
