### PR TITLE
Record cache for persistent favorites

### PR DESCRIPTION
**Pull request by EreMaijala**
This is based on work started in pull request #246 and should address review comments and other issues. 

Even after reading the conversation in #246, I'm not quite convinced having the user id in the cache id is a good idea. I made it now default not to include it, but if someone decides to include it, there is still at least one remaining issue: making a favorite list public may lead to others seeing different results than the list owner, or even missing records.

I've removed version number from cache_id. This means that if a schema change occurs, we need to do one of the following:
1.) Update all records having the old version in the database
2.) Update records on the fly when they are retrieved
3.) Make record drivers version-aware
4.) Remove old records from the cache (but this may render records inaccessible)

I like the first option since it's something executed only once and could also include a record update from the original source if that would be considered desirable. In any case I think we should be able to handle the situation gracefully.

We will probably use the cache as the primary source at least for Primo, since loading records from Primo is too slow to be practical when there are more than a few in a favorite list.

### CODE REVIEW

**Comment by demiankatz** [comment]
Ere, thanks for the work on this. I'll try to review it soon. In the meantime, I'd love to hear from @mbeh-ub to find out if he has any thoughts on the user_id issue and whether he's now content to close #246 and focus on finishing this newer PR instead.

**Comment by demiankatz** [comment]
It might make sense to factor the Version stuff out to a separate PR since we can get that sorted out independently of the caching logic. I think you could probably simplify the caching logic if you just made your static cache an array indexed by directory instead of doing extra work to only cache the default version number. I don't think that cache would ever get unreasonably large, and that approach would reduce the number of special cases in the code. If you don't have an easy way to separate this out, let me know and I can probably do it manually in the next couple of days (though you'll then have to deal with some merge conflicts over here).

**Comment by EreMaijala** [comment]
Version stuff now in #475. I'll update this PR when #475 is done and dealt with.

**Comment by demiankatz** [comment]
Thanks. Let me know when that's done and I'll give it another review.

**Comment by EreMaijala** [comment]
Done!

**Comment by demiankatz** [comment]
Some random thoughts/comments from browsing the code:

1. Injecting the cache manager into every record driver seems kind of expensive if we don't actually have caching turned on. Do you think it would make sense to make the initializer smart enough to omit the cache injection if the feature is disabled, or is checking the configuration just as expensive as building the object?
2. The PostgreSQL and MySQL table definitions were slightly out of sync for some reason. I think I've gotten them back in line.
3. The VuFind\Record\Loader allows a null cache object to be passed to the constructor, but most of the code seems to assume that the property is always filled in with an object. We should either make that a required dependency or else make the code more tolerant of a missing helper.
4. Perhaps this is too big of a refactoring to consider at this stage, but looking at some of this code is making me wonder if we could do this better with the help of an event system for favorites. Right now, we have multiple places where we need to attach things like calls to cleanup and createOrUpdate, and this seems likely to make the code harder to maintain in the long term. Might it be nicer if we made the code emit events at various stages of the favorites process, and allow the cache to hook them? That would presumably enable us to better encapsulate all the cache-specific logic. I haven't really thought this through all the way, but possibly something worth thinking about.
5. Is there any particular reason why the Cache class is passed a DbTableManager in order to retrieve the record table object, as opposed to simply having the record table object injected directly?

Anyway, there's a lot to look at here, and those are just a few random thoughts to get the ball rolling. I'm sure there's more to discuss than just these points, but I'll stop here for now!

**Comment by EreMaijala** [comment]
1.) I guess it's cheaper to check configuration first especially since it's loaded anyway for the cache manager. Changed.
3.) Added a null check and changed isset() checks to null checks.
4.) Tempting, but a lot of work. I'd keep that separate but make it something to do in the future. I think it would make sense to make the record loading events quite generic like:
  - events: pre-load, post-load, record-missing
  - contexts Results, Record, Favorites, Export, Send etc.
5.) Fixed.

**Comment by demiankatz** [comment]
Thanks! Regarding the events, I agree that this is probably a worthwhile future enhancement -- something we can discuss during roadmapping at the Summit, perhaps. Generic events centered around records definitely make sense, though we'll also need to fit a "delete favorites" hook in there somehow.

Anyway, I'll try to give this another look (and perhaps do some actual testing) later in the week.

**Comment by demiankatz** [comment]
Started playing with this and ran into a bug: in updateRecord, there is a call to findRecords. The code seems to expect that this will be an array of objects, but it is actually an array of arrays. Thus, when the call to $record->save() is made at line 108, it causes a PHP fatal error.

I triggered this by adding the same item to two lists. The first time worked, the second time died with a 500 error.

**Comment by EreMaijala** [comment]
Okay, so I ran into more trouble with the user-specific cache entries as the cleanup method didn't quite work. In the end I decided to scrap it, which makes things quite a bit more simple. The latest commit addresses the review comment but also unifies the method parameters, updates the cleanup method, simplifies the database table etc.

**Comment by demiankatz** [comment]
Is there a reason to be so aggressive about doing cleanup inline along with other tasks? Would it make more sense to have a CLI tool that could do a comprehensive cleanup on some regular schedule? I can see some use cases where it might actually be preferable NOT to perform cleanup -- i.e. bookmarked record pages for deleted records could continue to function independently of favorites. Obviously the desirability of this would vary based on use case... but I wonder if a more simplistic approach would improve flexibility and maintainability.

I also hope we can get some input from @mbeh-ub about this feature -- I personally don't have a problem with eliminating the user ID portion of the equation, but if that's a must-have feature for his use case, we might need to give some more thought to how to reintroduce it in the future.

**Comment by EreMaijala** [comment]
I thought about it but decided to keep the old way since the records only get cached when they're added to favorites. But for future use and keeping the interactive features simple I agree that a CLI tool is better. I'll work on that next.

**Comment by demiankatz** [comment]
I just updated this branch to the latest master and made some optimizations to the Initializer logic (see 30e2d0f).

One question: in Record::cleanup(), is there a reason you're not using $this->select with a callback function? I think that would make the code more concise unless there's a reason it works better this way.

I still need to do more reviewing/testing, but hopefully this moves us forward a little bit more!

**Comment by demiankatz** [comment]
@EreMaijala, are you waiting for me on this one, or am I waiting for you? I notice that this hasn't moved in a little while. (No rush, of course -- I'd still like to hear something from @mbeh-ub if he has time).

**Comment by EreMaijala** [comment]
Oh, I missed your question about the cleanup() method. Well, because, uh, I don't know. I guess I forgot it after looking up how to use joins in the ZF2 table gateway. I'll revise.

**Comment by EreMaijala** [comment]
Ok, the callback is in place now.

**Comment by demiankatz** [comment]
Thanks for the progress! I'll try to give this another look fairly soon.

**Comment by demiankatz** [comment]
I've just merged the latest master in to get things up to date. A few questions:

- Cache::normalizeIds() seems like it might break in some edge cases -- i.e. what if $ids is an array of arrays and $source is non-null? I think that would create weird results. I wonder if we should centralize our ID processing logic somehow, since I imagine this kind of processing is happening in at least one or two other places, and it would be nice if it all behaved consistently. What do you think?

- I notice in Loader::load(), the "count($results) > 0" check has been replaced with a series of empty/!empty checks. Have these cases been tested? Sometimes empty() behaves unpredictably with countable/iterable objects, so this seems like a potential danger area. (I can test if you like).

- In Loader::loadBatchForSource(), should we add checks to avoid the unset calls when array_search returns false? I suppose `unset($array[false])` is probably harmless, but it seems somehow undesirable. Anyway, the fix is as simple as `if ($key = array_search(...)) { unset($ids[$key]; }` so it only really adds one more line of code (for the closing brace).

- In Search/Favorites/Results.php you're passing a 'userId' parameter to the record loader, but it doesn't appear to do anything -- probably a legacy thing from code that's subsequently been removed.

- In Record::cleanup(), do you actually need the $count variable, or can you return a count of $results instead?

As you can see, this is mostly minor stuff. I think we're just about done. Let me know if you want me to help investigate any of these comments -- don't have much time today but I can do more next week if you like.

**Comment by EreMaijala** [comment]
* I decided to refactor the lookup functionality into lookup() and lookupBatch() that resemble retrieve methods of search backends. This makes them simple to call in record loader and eliminates the need for the id/source array.

* $results is always a plain array, no? At least that's how RecordCollection::getRecords() is documented and lookup() is implemented. I've tested it to work too.

* Not having the cached record ID in the array would of course be unexpected, but you're right, array_search() return value needs to be checked. I added an explicit !== false check so that it doesn't fail when $key === 0.

* Yes, leftover 'userId' removed.

* Ah, $count was probably also a leftover, changed.

**Comment by EreMaijala** [comment]
Ah, tests need to be fixed, working on that now.

**Comment by EreMaijala** [comment]
The remaining failure is unrelated, as far as I can see.

**Comment by demiankatz** [comment]
Looks like a style glitch got pushed up on Friday. I'll fix it momentarily in master.

**Comment by demiankatz** [comment]
Okay, I merged the style fix to this branch, which ought to clear the Travis error.

Thanks also for the remaining cleanup. Looks good, though I'll do one more comprehensive round of review/testing in the near future in case I missed anything. Assuming we get everything sorted out, do you think we should go ahead and merge, or would you rather wait until we can discuss it on the next dev call? I'm beginning to doubt that we're going to get much more external feedback, and at this point, the footprint of the changes is reasonably small, but at the same time, I don't want to be hasty!

**Comment by EreMaijala** [comment]
I'd like to get this merged, but I'll leave the final decision to you. :)

**Comment by demiankatz** [comment]
I'll see what I can do this week -- much to do prior to leaving for vacation, but hopefully I can squeeze this in on Friday at least.

**Comment by demiankatz** [comment]
I've made a couple of small adjustments in preparation for merging this (renamed the migration directory from 2.6 to 3.0, since I don't think there's going to be a 2.6; commented out all the settings in RecordCache.ini so this is off by default as documented).

A couple of things to consider before the merge:

1.) I'm a little concerned that the cache population in VuFind\Controller\Plugin\Favorites::saveBulk won't perform well, since it's going to look up records one at a time in order to cache them. Would it be better to collect a list of IDs in the save loop, then pass that to a new createOrUpdateBatch method on the cache itself? I think moving some of the logic into the cache class makes sense organizationally, plus doing it this way would make it possible to take advantage of the record loader's batch capabilities to more efficiently retrieve data from the backends. The only issue is that this creates something of a circular dependency (cache uses loader, loader uses cache), but if you pass the record loader as a parameter to createOrUpdateBatch (as opposed to injecting it into the cache class), I think that's sufficient to break the circle.

2.) Right now, the [Favorites] section of the configuration completely overrides the [Default] section. Thus, if you have a WorldCat setting in [Defaults] and a Solr setting in [Favorites], the favorites module will NOT inherit the WorldCat setting from [Defaults]. Is that a bug or a feature? My gut feeling was that [Favorites] should *extend* [Defaults] rather than completely override it... do you agree, or do you prefer the current behavior? Either way, perhaps we should clarify the documentation on this point.

Anyway, let me know what you think! If you need help on point 1, let me know and I can try to find some time. Hopefully once that's sorted out, we can go ahead and merge.

**Comment by demiankatz** [comment]
One other thing to think about... in cases where the record cache is set to 'primary', when we try to update the cache, I think we're actually just going to pull data out of the cache and then push it back in again. This scenario is particularly concerning:

1. Configuration has "Favorites" set to "primary" and "Default" set to "fallback"
2. User 1 looks up record A and saves it.
3. Record A is modified to correct a typo.
4. User 2 looks up record A. They see the current, corrected version.
5. User 2 saves record A as part of a bulk operation. We set the record cache into "Favorites" mode, which makes it primary. When we update the favorites, we re-save the bad old version back into the database.
6. User 2 goes to Favorites and sees a typo that does not exist on the record page.

Maybe I'm misreading something -- I haven't actually done the work of trying to set up this scenario (but I can, if you want me to). I think it's a problem, though.

Do we need to force the cache into fallback mode whenever we're saving records to be sure we don't create situations like this? That might create some other strange scenarios where records don't update in the UI until somebody saves them, which could be confusing too -- but at least the record would change consistently in all contexts, which is better than the "different versions in different contexts" situation described above.

**Comment by EreMaijala** [comment]
1.) I changed Favorites to use loadBatch to retrieve the records efficiently, but I didn't move loading the records to the cache since that introduced a circular dependency (loader needs cache needs loader...).

2.) I believe it was intended that the sections be indepedent, but your expectation makes sense, so I changed it so that Default is inherited.

Good catch that default caching set to primary would have caused a problem when adding a batch of favorites. I made it set the context to empty now to disable caching. As far as I can tell there's no need for fallback mode here since it would just update the very same record it retrieved.

**Comment by demiankatz** [comment]
Agreed. Thanks for the fixes. I think we're ready to go! I'll do one more round of testing later today or tomorrow, then merge unless I run into trouble.

**Comment by demiankatz** [comment]
Okay, we're not quite there yet. I found and fixed a few bugs, and I added some debug logging to the cache to make troubleshooting easier. There's still a major problem with the bulk save, however.

What I think is happening now is that you're setting the cache context to '', which means that the cache's cachableSources property is empty, which means that createOrUpdate skips every record, and nothing gets written to the cache at all.

It seems that what we really need is a way to set the cache into "write only" mode -- we want to use the favorites settings to decide what should get cached, but we don't want to use those settings for retrieval. I'm not sure what the most elegant way of approaching this might be, but I can give it more thought if you don't have any immediate ideas.

Another (not particularly surprising) discovery: the cache doesn't work right for EBSCO Discovery records. Obviously the effectiveness of the cache is going to depend on some record driver implementation details. (In the case of EDS, the most serious problem is that the record driver contains different data depending on whether or not the user is logged in; in general, the cache may cause licensing problems for any database where record access is restricted in any way). This is certainly not a show-stopping bug, but we may want to give some thought to how to document potential limitations in a useful way.

Finally, you'll notice that one of the bugs I just fixed has to do with the fact that VuFind stores the "Solr" search backend in the database as "VuFind" due to legacy 1.x behavior. This is obnoxious and requires special case code all over the place. We really ought to do something about it sooner or later... but it's a lot of work and could introduce some bugs. An item for the to-do list... just a really unappealing one!

**Comment by EreMaijala** [comment]
Oops, again. I made the batch handling restore the context after loading the records. That should help. I also added a couple more debug messages to log information about the results.

The EDS issue with different metadata being served depending on the situation is something I can't see a good way around, so would it be enough to document the limitation in the ini file?

I agree it would be really good to get rid of the "VuFind" backend. Maybe something that could be sneaked into VuFind 3? At least we can start storing cached records with "Solr" instead of "VuFind" as that makes lookups more simple, so that's what the latest commit now does.

**Comment by demiankatz** [comment]
Thanks for the fixes. I'll test some more in a moment.

I agree that documenting the limitation in the .ini file is probably the best we can do regarding EDS. I'll take care of that shortly.

Regarding elimination of the 'VuFind' backend, I've opened a JIRA ticket: https://vufind.org/jira/browse/VUFIND-1139 -- I'll try to set up a branch for this before too long.

**Comment by demiankatz** [comment]
I've made a few minor optimizations (see the last two commits). I've just run into one last problem: the cleanup routine no longer works. This is related to the dreaded "VuFind as source" issue. We're now storing Solr records as "VuFind" in the resource table and as "Solr" in the record table, and the result is that the join for finding orphaned records no longer works. I guess we have a few options:

1. Go back to storing "Solr" as "VuFind" in the record table, which will require more cleanup work down the line.
2. Figure out some kind of SQL hack to work around the inconsistency.
3. Put this PR on hold until VUFIND-1139 is taken care of, and then the issue goes away after we merge things together. That will take a while to get through, but I don't have a problem with moving it fairly high on my priority list.

What do you think?

**Comment by EreMaijala** [comment]
Uhh... I'd really like option 3 the best if it's possible to make it fairly high priority.

**Comment by demiankatz** [comment]
Option 3 works for me -- I'll see if I can finish up a first draft of the refactoring today so we can discuss it on tomorrow's call.

**Comment by demiankatz** [comment]
The "option 3" discussed above has been a success. Now that #534 has been merged to master, I have updated this branch and made some adjustments to remove special case logic that should no longer be needed. Could you take a few minutes to put this through its paces and make sure I haven't broken anything? If it looks good to you, I'll do a bit more testing at this end to be absolutely sure and then merge to master. Thanks again for all of the work on this (and for helping to motivate the database cleanup, which was really long overdue)!

**Comment by EreMaijala** [comment]
Thanks! Looks good to me. I just tweaked the debug messages a bit to remove the unnecessary Cache: prefix from the messages as the class name should suffice.

**Comment by demiankatz** [comment]
Makes sense. I should be able to do my final review (and likely merging) either later this week or early next.

**Comment by demiankatz** [comment]
I've manually merged this to master to flatten the very long commit history. I've also put a stub wiki page in here where we can document it: https://vufind.org/wiki/configuration:record_caching -- feel free to expand as needed.

**Comment by EreMaijala** [comment]
Awesome, thanks! Phew!

**Pull request closed without merging**
