### PR TITLE
One Searchbox

### PR DESCRIPTION
**Pull request by crhallberg**
Simplify VuFind to only have one searchbox.

All checked [installations](https://vufind.org/wiki/community:installations) of VuFind using the searchbox in-line with the logo and menu had completely custom layouts. Having the searchbox on the next line is the most popular. This PR removes the top searchbox and simplifies css and js logic.
- [x] IDs or classes (discussion at VuFind)

### CODE REVIEW

**Comment by demiankatz** [comment]
I believe that, in our discussion of this, it was suggested that we should continue to use a class instead of an ID for the search box even if we remove the duplicate one. (I think there were some use cases around embedding multiple VuFind boxes on a single page, though I can't remember who mentioned this or what the details were). In any case, reverting the class-->id switch would certainly make the diffs in this PR smaller. What do you think?

**Comment by demiankatz** [comment]
@crhallberg, are there any outstanding issues here? This seems to be working fine for me. If you're not aware of any remaining issues, perhaps you should run the full test suite on this branch one more time to be sure all is well and then merge if so.

**Comment by crhallberg** [comment]
Some errors are coming up in the full test, maybe be a cascading timing issue though. Working on it now.

**Comment by crhallberg** [comment]
Finally got my test instance working consistently again. Tests have passed. Sorry for the delay.

**Comment by demiankatz** [comment]
Thanks, Chris, I've gone ahead and merged this.

**Pull request merged**
