### PR TITLE
Switch from recordtype to record_format.

### PR DESCRIPTION
**Pull request by demiankatz**
TODO:

- [x] Decide whether or not to retain recordtype as a deprecated field for back-compatibility (until 7.0)
- [x] Run full test suite
- [x] Document in changelog / schema documentation

### CODE REVIEW

**Comment by EreMaijala** [comment]
I removed the API from the TODO list since recordtype is only exposed in rawData and not searchable. I think we can treat rawData as something that can change, but if anyone disagrees we can also make it easily add recordtype in the response.

**Comment by EreMaijala** [comment]
That said, it might make sense to keep recordtype in the index for one version as a deprecated field. That would make it possible to upgrade VuFind without having to rebuild the whole index at the same time. Unless, of course, there will be other back-incompatible changes.

**Comment by demiankatz** [comment]
@EreMaijala, keeping recordtype as a deprecated field is worth considering... though I imagine we'll at least upgrade to Solr 7.5 (or possibly a newer version, depending on where things are when we get to the Solr upgrading), so that might require a reindex anyway. I'll add a checkbox to re-evaluate the possibility before merging this.

**Comment by EreMaijala** [comment]
Point updates with Solr, e.g. from 7.3 to 7.5 should not require reindexing.

**Comment by demiankatz** [comment]
The key word there is "should." :-) It's true that it's probably fine, but I'm paranoid and recommend reindexing for all upgrades. Still, that is certainly an argument in favor of keeping the backward compatible field for one more version.

**Comment by EreMaijala** [comment]
I did it, it worked! :)

**Comment by demiankatz** [comment]
@EreMaijala, you've convinced me that we should keep recordtype around for back-compatibility. I've opened a ticket at https://vufind.org/jira/browse/VUFIND-1323 to remind us to delete this when 7.0 comes around.

**Pull request merged**
