### PR TITLE
Add helpful exception message when custom XSLT class is missing.

### PR DESCRIPTION
**Pull request by demiankatz**
As discussed on Slack...

### CODE REVIEW

**Review by oharacj — CHANGES_REQUESTED** [review]
This works great for no namespace being set. 

To verify the first elseif I set a test namespace ('cartography') as the environmental variable and called a class in the marmot namespace. If I've read the code correctly this should return the message 'Did you forget to add 'marmot' to VUFIND_LOCAL_MODULES? Instead of that the message returned was `Fatal error: Class \marmot\XSLT\Import\Marmot does not exist.` Which is more helpful than the 'this class was returned as a string' error that I was getting previously. 

It appears that when the custom_class begins with a \ we are exploding on the \ character which is returning a blank 0th value. We then shift that to $namespace which means that $namespace is '' and  in_array($namespace, $localModuls) is always returning true. I'm fine approving if this issue is acceptable.

**Comment by demiankatz** [comment]
Good catch, @oharacj! I've added commit [c4dd130](https://github.com/vufind-org/vufind/pull/4157/commits/c4dd13048e3aa801795f47a5d8c9046bd7e1d2e4) to trim off leading slashes before parsing the class; I think this should help!

**Review by oharacj — APPROVED** [review]
Good to go.

**Comment by demiankatz** [comment]
Thanks again, @oharacj!

**Pull request merged**
