### PR TITLE
bulk-action-buttons: only show email ribbon if userlist is not disabled

### PR DESCRIPTION
**Pull request by mtrojan-ub**
... else you get the "login_disabled" message when trying to use it, so it should be treated like "ribbon-save".

### CODE REVIEW

**Comment by demiankatz** [comment]
@mtrojan-ub, the "email search results" functionality should not be tied to user list capability. I just ran a test where I disabled user lists, but emailing search results still worked correctly. Perhaps you are encountering a bug related to a different interaction of configuration settings, but I don't think the solution proposed here is the ideal solution to the problem.

Can you share your `showBulkOptions` and `[Social]` configuration settings from config.ini, along with the exact version of the code you are using? Hopefully if we can isolate a way to reproduce the problem we can find a better-targeted solution to it.

**Comment by mtrojan-ub** [comment]
Sure! Code version is 4.1.3

```
[Site]
showBulkOptions  = true

[Social]
comments = disabled
lists = disabled
tags = disabled
max_tag_length = 64
```

**Comment by demiankatz** [comment]
Thanks, @mtrojan-ub. I still can't reproduce the problem. Perhaps I am misunderstanding something. Here is what I did:

1.) I installed a clean copy of VuFind 4.1.3, using the default `phing startup` continuous integration test environment.

2.) I adjusted config.ini with the Site and Social settings you provided.

3.) I did a search for "test", selected all the checkboxes, and clicked the "Email" button.

4.) I was prompted to log in. I created an account and logged in. I was then presented with the expected Email dialog:

image

Am I looking in the wrong place? If you're getting different behavior when following these steps, it must be related to some local customization or other configuration. Can you try turning off custom themes/modules to see if that makes a difference?

**Comment by mtrojan-ub** [comment]
@demiankatz: Sorry, i forgot to mention that you also should use the following setting:

```
[Authentication]
hideLogin = true
```

And here is a screenshot of the error messages:
grafik

**Comment by demiankatz** [comment]
@mtrojan-ub, I think this is just a configuration problem. By default, sending an email requires a login. If you disable logins, then you can't send emails without also disabling that requirement. You can adjust this setting to fix the problem:

https://github.com/vufind-org/vufind/blob/master/config/vufind/config.ini#L490

I think the best long-term solution to this issue would be to replace the require_login setting with a new permission in permissions.ini. Then we could check the permission when rendering the email button as well as when trying to send emails, and provide a more consistent user experience. If you'd like to do that work, it would be welcomed... but I imagine it's probably not worth the time and effort. If that's the case, just let me know and I'll open a JIRA ticket to track the issue until somebody has more time to fix it.

**Comment by mtrojan-ub** [comment]
@demiankatz, we do not want our system to send any mails without login. There are just too many bots out there triggering spam.
Of course, you can open a JIRA ticket if you like. The permissions.ini solution sounds a bit complicated for us, so we will just put the change from this pull request to our local theme.

**Comment by demiankatz** [comment]
@mtrojan-ub, one other possible configuration-based solution without code changes would be to turn off the login requirement but turn on CAPTCHA for emails. In any case, I've opened a JIRA ticket for future reference, so I will close this PR: https://vufind.org/jira/browse/VUFIND-1317

**Pull request closed without merging**
