### PR TITLE
Add detailed status information to the badge for screen readers.

### PR DESCRIPTION
**Pull request by pasitiis**
Currently, the screen reader only reads the status as a number, not what the number relates to.

### CODE REVIEW

**Review by demiankatz — COMMENTED** [review]
@pasitiis, is it possible that using an `aria-label` attribute in parallel with the `title` attributes on these elements might be more appropriate than embedding hidden text inside the elements? Semantically, it seems to me potentially more clear to treat the text as a label than to effectively concatenate it with the element contents, which may lead to strange results depending on word order in different languages.

What do you think? I'm certainly open to this approach if you feel differently, but my first reaction is that labels might be cleaner.

**Comment by pasitiis** [comment]
@demiankatz It's possible to use, and it's better to use aria-label in this context. I switched to aria-label.

**Comment by demiankatz** [comment]
Thanks, @pasitiis, I think this is a step in the right direction... but I still am concerned about including the actual values in the aria-label attributes. Is this necessary? If the aria-label is a label for the content of the element, is it necessary to repeat the contents of the element as part of the label? I would think this would cause redundant text to be read out. For example, if I have 5 items due, isn't it going to say "5 Items due later: 5" when the result that would make more sense would be "Items due later: 5"?

**Comment by pasitiis** [comment]
@demiankatz At least VoiceOver prioritizes aria-label over the visible content when both are present. So, VoiceOver only announces the content in the aria-label (e.g. 5 items due) . However, I also noticed that aria-label cannot be applied to a span element (for example, the JAWS screen reader does not read the aria-label at all with that structure). I will explore other methods.

**Comment by demiankatz** [comment]
Thanks, @pasitiis -- it's never as simple as one wishes!

In any case, whatever approach you find, my main concern is that we try to treat this as a label-value pair rather than a sentence so we can avoid the need to construct new translation strings to handle order differences between languages. The existing translations are designed as labels, not sentence fragments.

**Comment by pasitiis** [comment]
I couldn't find another solution than creating a separate field for screen readers. Using aria-labels and similar methods isn't possible in this structure (aria-label only works with interactive element elements). Changing the status fields to be focusable (interactive ) would make navigating the menu slightly difficult for screen reader users.

Screen readers now read the content as follows: "Holds and Recalls Available for Pickup: 4, In Transit: 1,". Previously, it was read like this: "Holds and Recalls 4 3." I used commas at the end to improve the rhythm of the text for the screen reader.

If someone comes up with an alternative method, I’d be interested to hear it. I tested this with VoiceOver, NVDA, and JAWS.

Additionally, I had to adjust the flex because Firefox, for some reason, read the status information in reverse order in VoiceOver.

**Comment by demiankatz** [comment]
Thanks, @pasitiis! This looks like an improvement to me, but I'm going to wait and see if we can collect a few more opinions before I merge it, just in case there are any further ideas out there.

**Comment by ThoWagen** [comment]
Would it make sense to create a ViewHelper for this? Maybe this can be reused in other cases and it would be easier to change this if we find a better solution in the future.

**Comment by demiankatz** [comment]
> Would it make sense to create a ViewHelper for this? Maybe this can be reused in other cases and it would be easier to change this if we find a better solution in the future.

This code is taking place in Javascript, not PHP, so I don't think a ViewHelper is feasible... but creating a support function to build each element might be a good idea to reduce repetition and simplify future adjustments, as you say!

**Comment by ThoWagen** [comment]
Ah, I have missed that. But yes, a support function would be nice instead.

**Review by crhallberg — APPROVED** [review]

**Comment by demiankatz** [comment]
Thanks, @crhallberg. I'll wait and see if @pasitiis wants to create a support method as @ThoWagen suggested before I merge this.

**Comment by pasitiis** [comment]
@demiankatz I can try to create a support function for this. It will probably be the end of the week or next before I can continue this.

**Comment by demiankatz** [comment]
Thanks, @pasitiis, there is no rush! :-)

**Comment by pasitiis** [comment]
@demiankatz I added a function that slightly clarifies the code. I discussed the topic further with @EreMaijala , and he suggested that there could be a server-side template which JS would just insert into place. I didn't proceed with the change @EreMaijala suggested in this PR.

**Comment by EreMaijala** [comment]
@demiankatz Also, I promised to take a look at adding the template. It would make customization quite a bit easier without having to poke the JS.

**Comment by demiankatz** [comment]
@EreMaijala, do you plan to add the change to this PR, or would it be better to get this merged and then follow up? (I'm fine with either approach, but I'll wait to hear from you before reviewing this in more detail).

**Comment by EreMaijala** [comment]
@demiankatz No, let's do that separately.

**Review by demiankatz — APPROVED** [review]
Thanks, @pasitiis and @EreMaijala!

**Pull request merged**
