### PR TITLE
Javascript Re-organization

### PR DESCRIPTION
**Pull request by crhallberg**
It turns out applying highlighters to printed code causes a lot of improvements.

A JS revamp featuring
 - More class selectors and less ID selectors
 - refreshing page instead of complex updatePageForLogin
 - new VUFIND object to get namespacing started with path and translation

### CODE REVIEW

**Comment by xmorave2** [comment]
Nice work Chris!
I didn't try the code, but I've read it and just small comment: 
There are some "path" strings changed mistakenly (in comments) I think: https://github.com/vufind-org/vufind/pull/461/files#diff-fdd333fc560d54342c5fc4c400a66d8fL16

Josef

**Comment by EreMaijala** [comment]
I just quickly glanced over the changes and there's one thing that pokes me in the eye: all caps namespace VUFIND. I know there are different conventions and opinions on this, but could you reconsider?

**Comment by demiankatz** [comment]
Thanks for the feedback. I'll second the suggestion that "VuFind" is preferable to "VUFIND."

**Comment by crhallberg** [comment]
I had no strong connection to *VUFIND* so I switched it to VuFind. Thanks for finding those comments too, I missed a couple in my cleanup.

**Comment by demiankatz** [comment]
A couple more comments related to ALLCAPS stuff:

1.) There are still some references to VUFIND in the global declarations -- we should fix those before jslint yells at us.

2.) Can we come up with a better name for the VF_NAMESPACE class? Maybe VuFindScripts, VuFindSupport, VuFindNamespace, VuFindCode, VuFindLogic.... or something. But I like camel case better than ALLCAPS no matter what we end up calling it.

I think it might be a good idea to work on some new Mink tests to go along with this refactoring so we can have better confidence that the refactoring is not breaking anything. I've just added a retry loop to the most timing-sensitive part of the existing Mink cart test, and I'm hoping that will stop our frequent Mink-related failed builds. If that works, I think we might be able to add some more such tests with confidence. Probably good work to do in master in parallel with this refactoring, since we can merge the tests in here as they grow and watch if any fail. (Though of course Travis isn't currently running integration tests, and Jenkins doesn't run tests on branches, so we'll have to do the test-running manually for now).

**Comment by crhallberg** [comment]
So to my understanding: we're waiting for (working on) more robust Javascript integration testing to make sure that we can do all these big changes without losing any functionality. After that, we'll be moving to merge this into master.

**Comment by crhallberg** [comment]
After manually merging in most of the features of this branch, I'm preparing the final changes to be merged in very soon.

**Pull request merged**
