### PR TITLE
Make js validate with eslint 4.x.

### PR DESCRIPTION
**Pull request by EreMaijala**

### CODE REVIEW

**Comment by EreMaijala** [comment]
I first thought the indenting looks weird, but it makes sense to help distinguish chained calls. I haven't looked into any new rules yet as my aim was only to be able to use newer eslint.

**Comment by demiankatz** [comment]
Sounds reasonable to me.

**Comment by crhallberg** [comment]
These new rules (comments especially) do seem weird to me, but as long as there's a standard. Are we sure unescaping the slashes in the regular expressions doesn't cause any problems?

**Comment by EreMaijala** [comment]
It shouldn't cause problems when they're in [ ].

**Comment by demiankatz** [comment]
Thanks, @crhallberg and @EreMaijala -- I've merged in the latest master and everything is still passing, so I'm merging now.

**Pull request merged**
