### PR TITLE
Fixed lightbox login event handling.

### PR DESCRIPTION
**Pull request by EreMaijala**

### CODE REVIEW

**Comment by crhallberg** [comment]
Why do we need to check if the emit was successful before we refresh? Also, if we're going to refresh, do we need to emit at all?

**Comment by EreMaijala** [comment]
It's not about success. From MDN: "The return value is false if at least one of the event handlers which handled this event called Event.preventDefault(). Otherwise it returns true." (https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent)

So, it's about overriding the default behavior (refresh). I had an example in the original pull request (see https://github.com/vufind-org/vufind/pull/620#issuecomment-194204453).

**Comment by EreMaijala** [comment]
I added here a couple more fixes for Internet Explorer I first made a separate PR of but realized they would conflict. At least IE 11 fails miserably without these changes. I considered a polyfill for CustomEvent, but since it can't be included conditionally (IE 11 doesn't support that anymore), that would have added another piece of js for all browsers (and there's a chance that this will get fixed in IE 11).

Dataset is not supported on IE, so let's use jQuery to access the items.

**Comment by demiankatz** [comment]
Manually merged to master with @crhallberg's approval. Thanks, everyone!

**Pull request closed without merging**
