### PR TITLE
Amazon-Style Sidebar

### PR DESCRIPTION
**Pull request by crhallberg**
Instead of using an edge of the screen, add a sidebar button and move more options to the sidebar.

| image | image |
|--|--|

### CODE REVIEW

**Comment by demiankatz** [comment]
Questions/comments:

1.) Is this intended for inclusion in 4.0, or can this wait until later?

2.) It appears that you are creating multiple instances of the sort and limit controls for responsiveness. However, these controls currently have unique id attributes hard-coded. Should we do some work to ensure valid HTML without duplicate IDs?

3.) There appear to be some unresolved conflicts here.

**Comment by crhallberg** [comment]
This was intended for 4.0, but we should push this to 4.1.

**Comment by jochen-lienhard** [comment]
Will you make this configurable?
I think the problem of the new version is, that, if you scroll down, you must again go to the top to open the facets.

**Comment by crhallberg** [comment]
I'll make it configurable. About the scrolling: good point. Pairing this with the upcoming sticky header feature will solve that issue.

**Comment by crhallberg** [comment]
I still think this is better than the huge button on the side of the screen. There are a couple other ways to go about this, but I still think this is the simplest. I'll clean it up and we'll take a look.

**Pull request merged**
