### PR TITLE
Add permalink to search results in embedded mode; adjust thumbnail links

### PR DESCRIPTION
**Pull request by demiankatz**
During discussion of #3546, @EreMaijala suggested that we can simplify some of the complex logic in that PR if we eliminate the link from the results thumbnail to the record page and replace it with a separate, more explicit link.

The approach taken here is to add a "permanent link" link to the tools in the search results so there's an explicit way to get the record page link even when the main title is reconfigured to open the embedded view. This is hidden by default but gets unhidden when we switch into embedded mode. Additionally, the thumbnail link is changed to the large thumbnail instead of the record page, so it can be ignored by screen readers, etc., without losing any useful functionality.

There are still some details that might be worth discussing:

1.) Is there a better way to do this? This was the simplest solution I could come up with (without adding much complex code or new translation strings) but it's kind of awkward. It may be "good enough" since embedded record view is rarely used, but I'm open to suggested improvements.

2.) Should we add a target to the cover images so the thumbnails open in a new tab? They currently do not, which seems suboptimal for an image link... but that is the current behavior on the record page.

Let me know what you think!

### CODE REVIEW

**Review by EreMaijala — CHANGES_REQUESTED** [review]
This looks good enough for me, but I'd rather call it full-record-link (perhaps use "View Record" as translation). A proper permalink shouldn't contain sid, but in this case it can be useful.

How about adding a check for layout=lightbox to Cover/Show and return a html snippet with the image? That would allow a simple display in lightbox. I could do it if you'd prefer that.

**Comment by EreMaijala** [comment]
Or perhaps it should be a separate action (Cover/View)? That would be less confusing.

**Comment by demiankatz** [comment]
@EreMaijala, I've changed the class name and link text as you suggested, but I don't really like "View Record" as the text -- I don't think it's very clear why clicking the title and clicking "View Record" do different things. I chose the permalink text before because that at least seemed like a rational explanation, though I agree with your reasoning for not using that approach. I think maybe we need to add a new string here to make this more clear, but I'm not sure what it should say...

- Link to Record
- View Full Record
- Stand-alone Record
- Record Page
- Visit Record Page
- Open Record Page

I don't really like any of those... but maybe Open Record Page feels "least worst" to me.

What do you think?

I also like your lightbox idea. I'll experiment with that later in the day if time permits.

**Comment by demiankatz** [comment]
@EreMaijala, there's an existing data-lightbox-image mechanism, so I went ahead and used that instead of building new routes. See my latest commits and let me know what you think! It required some changes to the cover helper/template, which might be too big a change for a minor release... but I tried to be as back-compatible as possible.

**Comment by EreMaijala** [comment]
@demiankatz I suggested "View Record" because it already exists, but I agree it's not a great one. Perhaps it could be copied to a new translation as the default, though? It would allow the translation to be added in a minor release. Then make the English version "View Full Record"? It'd fit in with "Add to Book Bag" and "Save to List".

**Comment by demiankatz** [comment]
> @demiankatz I suggested "View Record" because it already exists, but I agree it's not a great one. Perhaps it could be copied to a new translation as the default, though? It would allow the translation to be added in a minor release. Then make the English version "View Full Record"? It'd fit in with "Add to Book Bag" and "Save to List".

It's not against the rules to add new translations in minor releases -- I just like to stop adding them a month or two before the scheduled release to allow adequate time for translation. If this one gets down to the wire, we could use your proposed strategy of "View Record" as a placeholder until we can get something better translated.

However, I don't like "View Full Record" -- because the embedded record IS the full record, so it's weird that clicking title gives you the full embedded record and clicking the side link takes you to the same content in a different format at a different URL. I think the link title needs to convey that it will take you to a new page, to contrast it with the title link behavior. What do you think? Am I being overly fussy, or can we do better? :-)

**Comment by EreMaijala** [comment]
@demiankatz You are right, and we can do better. :) Could it be something like "Show Single Record Page"? Or standalone record page? Show detached record?

**Comment by demiankatz** [comment]
@EreMaijala, I think "standalone record page" might be the winner, since it came up in both of our brainstorming lists. It's a bit long, though -- when time permits, I'll experiment a little bit and see how it looks in context.

**Comment by EreMaijala** [comment]
@demiankatz Right, I somehow missed that you already thought about it. :) Well, then. Perhaps we could consider displaying it separately from the other entries?

**Comment by demiankatz** [comment]
> @demiankatz Right, I somehow missed that you already thought about it. :) Well, then. Perhaps we could consider displaying it separately from the other entries?

As an initial "path of least resistance" I created a new translation string and set it to just "Standalone Record" (which I realize lacks a verb, but it's the only way we can avoid word-wrapping, which looks worse to me). Here's a screen shot:

image

I'm not opposed to further adjustments, but this might be good enough, given the likely very limited usage of this feature and the fact that it's now very easy to customize.

**Comment by demiankatz** [comment]
Didn't mean to close that -- my mouse slipped. :-)

**Review by EreMaijala — CHANGES_REQUESTED** [review]
This looks pretty good. Just one minor issue: I think each option should be on its own line on narrow screens too:
Narrow screen

**Comment by demiankatz** [comment]
> This looks pretty good. Just one minor issue: I think each option should be on its own line on narrow screens too: Narrow screen

Okay, I've added the missing line breaks to make this work. Looks correct to me now in both wide and narrow screens.

**Review by EreMaijala — APPROVED** [review]
Everything looks good now! :)

**Pull request merged**
