### PR TITLE
Sanitize keys during language normalization.

### PR DESCRIPTION
**Pull request by demiankatz**
This is the promised follow-up to #3461. As you can see, it reveals a few minor issues in our existing language files, which I have fixed. I have also added URLencoding-style escaping of bad characters (using a _ prefix instead of %, in case % is problematic) to eliminate some potential ambiguity. This is not perfect (we'd have to escape underscores themselves to make it totally unambiguous), but I think it's probably good enough for our purposes.

### CODE REVIEW

**Comment by demiankatz** [comment]
On further reflection, it seems silly not to do this in a smarter way, so I have added URLencoding-style escaping of bad characters (using a _ prefix instead of %, in case % is problematic). This is still not perfect (we'd have to escape underscores themselves to make it totally unambiguous), but I think it's probably good enough for our purposes.

I've force-pushed revisions to my branch but they're not showing here yet for some reason; GitHub is probably just running slow, and I expect the changes will be visible soon.

**Comment by demiankatz** [comment]
You can see the correct diffs [here](https://github.com/vufind-org/vufind/compare/dev...demiankatz:vufind:normalize-sanitize-keys?expand=1) if the PR still isn't updated by the time you're reading this. If this PR turns out to be entirely broken, I can close it and open a new one.

**Review by EreMaijala — APPROVED** [review]
It's pretty unlikely that we would have collisions with this, so I think this is quite perfect. :)

**Comment by EreMaijala** [comment]
I also think that the triple question mark is a pretty bad translation key. Any idea where it's used? Also, it seems that in de.ini there's a mistake in translation for `mis`.

**Comment by demiankatz** [comment]
@EreMaijala, the triple question mark key comes from some version of the ISO639-3 code list (or possibly a MARC language code list). I don't think it's especially likely to get used. Not sure how the German mis code got messed up, but I'm pretty sure I can fix that. I'll open a separate PR.

**Pull request merged**
