### PR TITLE
Folio driver get my profile proposed change

### PR DESCRIPTION
**Pull request by mis306lu**
This will use the FOLIO uuid for the patron lookup.  As it is it won't work as 'username' for my case is 'barcode'.

I thought about using the 'username_field' configuration here, however I don't think the /users API call will support all of those options (e.g. personal.lastName).  

thoughts?  thank you!

### CODE REVIEW

**Comment by demiankatz** [comment]
I think it should be safe to rely on doing things this way, though I'd welcome a second opinion from @ihardy and/or @nkuitse before merging it.

**Comment by demiankatz** [comment]
It also looks like we need to adjust the test suite before we can merge this; I'm happy to help with that if you don't have time. Just let me know!

**Comment by demiankatz** [comment]
Thanks, @mis306lu!

**Comment by ihardy** [comment]
This makes a lot of sense to me. We already have a uuid from patronLogin, seems like a good choice to use for the lookup.

**Comment by demiankatz** [comment]
Thanks, @ihardy; I'm going to merge this now.

**Pull request merged**
