### PR TITLE
Use url, if no pdf url found in Unpaywall DOI linker

### PR DESCRIPTION
**Pull request by xmorave2**
This changes the Unpaywall DOI linnker behaviour and takes an "url" data field instead of "url_to_pdf".

url means "The url_for_pdf if there is one; otherwise landing page URL."

According to http://unpaywall.org/data-format

As the resources in Unpaywall should be Open access, the url should always link to some form of full text.

### CODE REVIEW

**Comment by demiankatz** [comment]
@xmorave2, do you have any objection to using the existing `online_resources` translation string instead of "Full Text" so we don't need to add a new set of translations? (I can make the change if you don't have time; apart from that minor detail, I think this should be fine to merge).

**Comment by xmorave2** [comment]
@demiankatz I have no objections, I've changed it in follow-up

**Comment by demiankatz** [comment]
Thanks. One more thought before I merge: would it be useful to make this an if .. elseif that checks for PDF first and then fails over to url, just so that we can continue to label PDF links as "PDF Full Text," to help with user expectations? If you don't object, I'm happy to make that change -- I think it would give us a little more flexibility (and if somebody wanted to make all the labels uniform, that could be accomplished by tweaking the translation file).

**Comment by xmorave2** [comment]
It's done. I've added also some more tests.

**Comment by demiankatz** [comment]
Wonderful, thanks for taking the time! Looks great!

**Pull request merged**
