### PR TITLE
catalog password deletion after shibboleth log out

### PR DESCRIPTION
**Pull request by Cloud8**
when loggin in via shibboleth, library catalog credentials get removed
  after log out.
  I thinks thats because of line 125 in VuFind/Auth/Shibboleth.php
  -- at least, the credentials are preserved when I change like so:
  if (!empty($user->cat_username) && !empty($catPassword)) {

  If - for any reason - the catalog password deletion after log out is
  intended, please just kill this request -.

### CODE REVIEW

**Comment by demiankatz** [comment]
If memory serves, that check was removed intentionally because there are some scenarios where there is no password associated with a catalog username (for example, a barcode that stands alone with no additional credentials).

However, if the side effect of allowing empty passwords is that VuFind erases credentials on every logout, that's obviously a problem -- by allowing one edge case, we end up causing a problem for a larger group of users.

Do we have a way to detect a logout scenario (as opposed to a login scenario) and avoid updating the credentials in that case? Unfortunately, I don't have a real Shibboleth test environment to investigate this with, but if you need me to take a closer look at any code, let me know and I can do my best to set up some fake scenarios.

**Comment by lahmann** [comment]
As it was me who removed the password check from Shibboleth, I'll join this discussion. :)

@Cloud8 is right, the previously stored catalogue password gets overwritten with an empty password if none is provided by the Shibboleth attributes.

I think a good workaround (to serve both needs - ILS-login via Shibboleth with/out password) is to pass the already stored password to saveCredentials if there was no password submitted as a Shibboleth attribute (haven't tested it though):

```php
        // Save credentials if applicable:
        if (!empty($user->cat_username)) {
            $user->saveCredentials(
                $user->cat_username,
                (!empty($catPassword) ? $catPassword : $user->cat_password)
            );
        }
```

**Comment by demiankatz** [comment]
That sounds like a reasonable solution -- then we only have a problem in the (hopefully extremely unlikely) edge case where a password is changed from something to nothing. If @Cloud8 can test this out and revise the pull request, I'll merge once @lahmann has had a chance to test the revision. Thanks to both of you for your work on this!

**Comment by lahmann** [comment]
That is true, but this edge case was already present with the password-check (`if (!empty($user->cat_username) && !empty($catPassword))`) - still worth considering though (but hopefully very unlikely).

Thinking about it - we could check if `$catPassword == null` as it gets declared being null in the first place - so that would allow an empty string as Shibboleth attribute value...

**Comment by demiankatz** [comment]
You make a good point about the edge case already existing.

If a null check solves the problem for everybody, that might be the simplest thing... but then the question is simply: can we safely assume that a blank password set by Shibboleth is definitely going to be a non-null value, or is it possible that the null could come from the `$request->getServer()->get($shib->$attribute)` code?

**Comment by Cloud8** [comment]
A null check also prevents the password erasure, like so:

        if (empty($user->cat_username) || $catPassword==null) {
            // no need to save
        } else {
            $user->saveCredentials($user->cat_username, $catPassword);
        }

If I set  cat_password = 
/* nothing */ in the config, a null value arrives at $request->getServer()->get($shib->$attribute), this is also true if there is no cat_password at all in config. So is there a need so support empty passwords
which should be saved to the database ? If so, this is not easy to solve, I think.

**Comment by lahmann** [comment]
@Cloud8 I'm afraid the suggested null-check would not allow to save the logged in user with unset password either - hence this check would have the same effect as the initially proposed reverted check `if (!empty($user->cat_username) && !empty($catPassword))`.

But you are right that `$request->getServer()->get($shib->$attribute)` defaults to null (as it's signature in vendor/zendframework/zendframework/library/Zend/Stdlib/ParametersInterface.php indicates) in case of config setting `cat_password = ` or cat_password not being set at all.

The question is what happens if cat_password is mapped to a Shibboleth attribute in config.ini but this attribute is not set/is empty in Shibboleth response. According to the Shibboleth documentation 

> the attribute's values, if any, will be available in an environment variable or header corresponding to the rule's id and/or aliases properties.

(https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPAddAttribute#NativeSPAddAttribute-UsingtheAttribute) 

So from my understanding in Shibboleth's response the password attribute would not be set if the password is empty - therefore we would have the undecidable problem of having no Shibboleth attribute in the response and needing to know if that's because the attribute's value is empty or because the attribute is not configured in the Shibboleth IdP at all (hence deciding whether to overwrite an existing password or leaving it).
The only clue could be, that the cat_password mapping in config.ini is available - so one might assume that as the mapping exists the attribute should be included in the response, concluding if it's not it's because the attribute's value is empty therefore the password needs to be overwritten.

This seems to be a fairly complicated and implication-packed attempt to resolve this issue - so I wonder if the constructed case is likely enough to justify this password-overwrite logic (or just stick with my initial proposal leaving the cleared password case aside).

**Comment by demiankatz** [comment]
Thanks for the further discussion/investigation. I think at this point, @lahmann's original proposal (pass through the stored password if the new password is empty) is probably the most appropriate option; we can worry about making more detailed assumptions if we come across a use case where it matters. @Cloud8, do you mind testing? We should also be sure to add a detailed comment to the code explaining this behavior (and perhaps referencing this pull request) for future reference.

**Comment by Cloud8** [comment]
Yes, just tested, and @lahmann's proposal works, cat_password is not deleted anymore. I have no time to file another PR right now - and its probably not worth anyhow, since there are only some few lines to change. @Demian,  could you resolve/delete  this PR as is ?

**Comment by Cloud8** [comment]
Ouch, wrong button. My next time slot for this is tommorow afternoon, in case there is something remaining where I could help with.

**Comment by demiankatz** [comment]
Resolved here: https://github.com/vufind-org/vufind/commit/08681597a3281f75fcd7a3a3cc4c79b4f13497bb -- note that I expanded the comment and made a few tiny changes to make the code slightly shorter. Please let me know if I've introduced any problems, but based on testing here it seems fine.

**Comment by lahmann** [comment]
Oh, what a coincidence... I just opened a pull request with the fix to save you some time ;)

**Comment by demiankatz** [comment]
Your comment has some details that mine omitted, so I'll merge them together in a moment.

**Comment by lahmann** [comment]
Ok, let me know if I can be of any assistance.

**Comment by demiankatz** [comment]
Thanks. I think the only remaining question is whether the CAS handler has a similar problem, since I updated it to match Shib in response to #532. I'm not entirely clear on how logging out causes the credentials to get cleared in Shib. Shouldn't we only be going the whole way down this path in the scenario where the user is logged in? Perhaps I'm forgetting how the institutional login workflow operates....

**Comment by lahmann** [comment]
I agree to stick to the login scenario as I am pretty sure that the credentials got erased upon login in the DB - there is no Shibboleth specific database activity on logout. But just to make sure it would be interesting if @Cloud8 monitored the database while logging out or if the cleared password only showed effects on the next login-attempt (some data stored in session?).

**Comment by Cloud8** [comment]
@lahmann Yes, you are right -- the old behaviour was as you described, the cat_passwd gets erased upon login. Thanks for resolving this !

**Comment by lahmann** [comment]
@Cloud8 thanks for your immediate response and clarification!

@demiankatz if CAS works almost like Shibboleth (I have no experience with CAS) adding this fix to the CAS handler might be worth considering. But this decision is up to you or anyone else who actually uses CAS/knows how it works.

**Comment by demiankatz** [comment]
I have access to a CAS server, but it doesn't have any attribute data, so I don't think I have a means of testing this scenario. I'll put out a call to vufind-tech and see if anybody can help.

**Comment by demiankatz** [comment]
I gave this some more thought last night, and I think I have a better understanding of what is going on. I've revised the comment and made our solution universal to CAS, LDAP and Shibboleth here:

https://github.com/vufind-org/vufind/commit/15d4eda643198b0610a281e096678d06768d35ad

Also note that we should not have used direct access to $user->cat_password since that does not cover the case where password encryption is enabled in the configuration, so I replaced the direct access with an appropriate method call.

I think we're in pretty good shape now, as long as we don't have to worry about the scenario of a password intentionally changing from non-blank to blank.

**Comment by lahmann** [comment]
Thanks again Demian for fixing this properly!

**Comment by lmaylein** [comment]
I think we run into a problem caused by this part of code.
We map REDIRECT_REMOTE_USER to cat_username
```
[Shibboleth]
username         = "REDIRECT_REMOTE_USER"
login            = "..."
cat_username     = "REDIRECT_REMOTE_USER" 
```

If a **new** user authenticates via shibboleth he receives the "authentication_error_technical" error message. The exception is: 

> Exception in VuFind\Auth\Manager login: Not a valid column in this row: cat_pass_enc 

and it is thrown within the saveCredentials call within Shibboleth.php:
```
        if (!empty($user->cat_username)) {
            $user->saveCredentials(
                $user->cat_username,
                empty($catPassword) ? $user->getCatPassword() : $catPassword
            );
        }
```

$user->getCatPassword() and $catPassword are both empty.

If I replace the second parameter of saveCredentials with 'NULL' everything works fine and the password field in the database (which have been successfully migrated from version 2) contains a hash value.

**Comment by demiankatz** [comment]
Does your database currently include a cat_pass_enc field in the user table? If not, make sure you upgrade your DB schema. If so, what database/version are you running?

**Comment by lmaylein** [comment]
show create table user:
```
| user  | CREATE TABLE `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) NOT NULL DEFAULT '',
  `password` varchar(32) NOT NULL DEFAULT '',
  `pass_hash` varchar(60) DEFAULT NULL,
  `firstname` varchar(50) NOT NULL DEFAULT '',
  `lastname` varchar(50) NOT NULL DEFAULT '',
  `email` varchar(255) NOT NULL DEFAULT '',
  `cat_username` varchar(255) DEFAULT NULL,
  `cat_password` varchar(70) DEFAULT NULL,
  `cat_pass_enc` varchar(170) DEFAULT NULL,
  `college` varchar(100) NOT NULL DEFAULT '',
  `major` varchar(100) NOT NULL DEFAULT '',
  `home_library` varchar(100) NOT NULL DEFAULT '',
  `created` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `verify_hash` varchar(42) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=55 DEFAULT CHARSET=utf8 |
```
Database: Mysql 5.5.50
VuFind version: 3.0.1

**Comment by lmaylein** [comment]
By the way: cat_username is extended manually (only after the problems already occured) to receive the shibboleth persistent_id.

**Comment by demiankatz** [comment]
Does it help/make a difference if you add something like:

<pre>
if (!isset($this->cat_pass_enc)) {
    return null;
}
</pre>

to the beginning of getCatPassword in \VuFind\Db\Row\User?

If that doesn't help, then something weird must be going on at a lower level in the database abstraction code.

Let me know what happens -- I'm on vacation right now but I can do some more direct investigation when I'm back in the office next week.

**Comment by lmaylein** [comment]
Yes it does. When I add these lines at the beginning of getCatPassword, everything is okay.

**Comment by demiankatz** [comment]
Thanks for the confirmation. I've committed a slightly more nuanced version of that fix here, so hopefully the problem is now fully solved: https://github.com/vufind-org/vufind/commit/44fac7d63b14d67ed3193256f361591b48b54497 -- please let me know if you encounter any new problems.

**Pull request closed without merging**
