### PR TITLE
Use a gray badge for count of requests with other status. 

### PR DESCRIPTION
**Pull request by EreMaijala**
Red usually indicates a problem or something really needing attention, so gray is less aggressive.

**Note**: this is based on changes in #2506, do not merge before that one.

I found the red too aggressive, since for loans it means "overdue" but for requests it was "other status". After discussing with our usability expert we decided to propose making the "other status" gray so that it doesn't indicate that it needs attention. Sample screenshot:

Menu with gray

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @EreMaijala, I agree that the gray makes more sense! I'll give this a closer look after @crhallberg has reviewed #2506.

**Comment by crhallberg** [comment]
This looks good to me! One silly nitpick: The gray looks a bit dark compared to the contrast of the other icons, maybe `@gray-dark` or `@gray` instead of `@gray-darker`.

**Comment by demiankatz** [comment]
@EreMaijala, please feel free to merge #2506 after resolving the conflicts, now that @crhallberg has approved it. That will hopefully make it easier to move forward and finish up this one. Let me know if I can be of any help!

**Comment by EreMaijala** [comment]
@crhallberg Thanks, I changed the color to `@gray-dark`.

**Comment by EreMaijala** [comment]
Also merged the latest dev here to simplify the change set. :)

**Review by demiankatz — APPROVED** [review]
Thanks!

**Pull request merged**
