### PR TITLE
Virtual keyboard: Avoid !important with more specific selectors, escape attrs properly.

### PR DESCRIPTION
**Pull request by EreMaijala**
The style changes here make it easier to customize the look of the virtual keyboard.

### CODE REVIEW

**Comment by demiankatz** [comment]
@sturkel89, do you mind double-checking that the virtual keyboards (activated in searchbox.ini) still look correct in all themes after applying these changes?

**Review by sturkel89 — APPROVED** [review]
I checked the test branch in all themes. All behavior and appearance seem to be identical between the dev branch and the test branch. I couldn't find any differences.

As far as I can tell, this is ready to merge!

**Comment by demiankatz** [comment]
Thanks, @sturkel89 -- this looks fine to me as well, but I'll wait to hear from @ThoWagen before merging in case he has any concerns, being the person most familiar with this code.

**Review by ThoWagen — APPROVED** [review]
This looks good to me.

**Pull request merged**
