### PR TITLE
Added en, fi, sv translations for MARC note field 787.

### PR DESCRIPTION
**Pull request by EreMaijala**

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks. Any reason not to also add 787 to the default marc_links setting in config.ini?

**Comment by EreMaijala** [comment]
Well, it doesn't contain all the other link fields with translations either, so I thought changing the default might be overly aggressive.

**Comment by demiankatz** [comment]
Ahh, I didn't realize that. Not sure if that's intentional or an oversight. Perhaps the most conservative approach for now would be to include a list of supported fields as part of the comment.

**Comment by EreMaijala** [comment]
Then again I didn't realize marc_links is commented-out by default so I just added the fields there...

**Comment by demiankatz** [comment]
Works for me. Thanks!

**Pull request merged**
