### PR TITLE
Format List Cleanup

### PR DESCRIPTION
**Pull request by crhallberg**
- [x] Simplify format-list usage with LESS (no more str_replace with `.label-info`)
- [x] Make facets links to blank facet search
- [x] Bootprint styling

### CODE REVIEW

**Comment by demiankatz** [comment]
I fixed a few bugs and unlinked the format pills (the link assumed that the record came from Solr, but this is a shared template that needs to work with all backends).

A few unresolved issues:

1.) You've removed the call to the getFormatClass() method of the record view helper. That actually serves a purpose: the class gets formatted differently for each search backend, which allows different format strings used by different backends to be mapped to the same CSS classes. If we're no longer using format icons anywhere, this may be obsolete, but if we're going to eliminate the feature, we should do it in a more planned way. I think that's a separate issue and we should leave the view helper call as-is at least for the moment.

2.) There's a formatting problem on the checked out items screen, at least for me. See screen shot:

checkedoutbug

3.) It doesn't look like anything has been done yet about the display of core formats. I assume this is probably by design -- clean up first, then extend. Just mentioning it so we don't forget it.

**Comment by crhallberg** [comment]
1.) You're right. I meant to return it after evaluation, but missed it.
2.) That's weird, I'll look into it.
3.) I still prefer the core formats as text, but now that they're links, it's clearer [where one ends](# "example") [and](# "example") [one begins](# "example").

**Comment by demiankatz** [comment]
Regarding 3. -- they're not links any more, because I unlinked them, because linking them is not cross-backend-compatible.

**Comment by crhallberg** [comment]
3.) Commas added via LESS in record view.

**Comment by demiankatz** [comment]
Just found a new bug: when you are in tab or accordion mode within the search results (from bootstrap3-list) both forms of styling stack, and you end up with pills that are comma-separated. Probably not desirable.

**Pull request merged**
