### PR TITLE
Improve Overdrive Staff View

### PR DESCRIPTION
**Pull request by demiankatz**
This PR fixes a bug that @sturkel89 discovered while testing #3046: turning on hierarchical facets when Overdrive is set in non-MARC mode causes a fatal error. This is because the SolrMarc record driver's getData/setData methods are asymmetrical, causing illegal behavior.

This PR simply removes the Overdrive record driver's custom getRawData method; this only existed to make the staff view work, and it's actually better to move this logic directly into the staff view templates. This enables us to not only fix the bug but also to add proper support for the alwaysDisplayIndexRecordInStaffView setting.

I've also made a few minor changes to eliminate warnings and notices that were preventing me from testing the code. Some of this work may conflict with #3025, but I'm happy to help resolve conflicts as needed.

@bpalme, do you mind checking my work here and letting me know if you have any concerns about it?

### CODE REVIEW

**Review by EreMaijala — APPROVED** [review]
Looks good to me and fixes the issues, but I can't test this with Overdrive.

**Comment by demiankatz** [comment]
Thanks, @EreMaijala! I'll give @bpalme a few days to comment before I merge this.

**Comment by demiankatz** [comment]
Happy new year, @bpalme -- just checking in one more time to be sure you don't have any concerns about merging this. Please let me know if you think I should hold off; otherwise, I'll plan to merge this in two weeks, on 1/15.

**Comment by bpalme** [comment]
I feel good about it. I do hope to have some time in the next week or two to do more testing.

**Comment by demiankatz** [comment]
Thanks, @bpalme!

**Comment by demiankatz** [comment]
Since there have been no objections, I've just merged the latest dev code into this branch and will merge it as soon as CI passes. Thanks, everyone!

**Pull request merged**
