### PR TITLE
Properly fetch holds from Voyager also when HOLD_RECALL.HOLDING_DB_ID…

### PR DESCRIPTION
**Pull request by EreMaijala**
… = 0.

### CODE REVIEW

**Comment by EreMaijala** [comment]
This is a weird one. Apparently Voyager's database doesn't enforce referential integrity between HOLD_RECALL.HOLDING_DB_ID and VOYAGER_DATABASES.DB_ID, and at least when a universal borrowing request is received, HOLD_RECALL.HOLDING_DB_ID will be 0.

**Comment by demiankatz** [comment]
Have you tested this version of the code? It looks like the concatenation is going to result in:

`... (HOLD_RECALL.HOLDING_DB_ID IS NULL OR HOLD_RECALL.HOLDING_DB_ID = 0OR (HOLD_RECALL.HOLDING_DB_ID = ...`

(note lack of space between 0 and OR)

I can't imagine that's going to work correctly... but perhaps I'm misunderstanding something. Should we add a space before merging?

**Comment by EreMaijala** [comment]
Well, huh. That was obviously an error, but somehow Oracle managed to parse the query and it worked properly. I added the space now, thanks for spotting that!

**Comment by demiankatz** [comment]
Thanks! Manually merged to master.

**Pull request closed without merging**
