### PR TITLE
Always show caret when using virtual keyboard

### PR DESCRIPTION
**Pull request by ThoWagen**
This is a followup to PR #3248. Now, the text cursor is always shown in the correct position when the virtual keyboard is used.

Before testing this we should wait for #3247 and #3248.

- [x] Merge dev into this branch when #3247 and #3248 are completed.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @ThoWagen! I have merged #3247 and #3248 and brought this up to date, so it's ready for @sturkel89 to test.

**Comment by sturkel89** [comment]
The first thing I'm noticing about this branch is that when it's activated, **I am not able to highlight and copy text on the browser page into my computer's clipboard**! I can click and drag my mouse across text to highlight it, but as soon as I release the mouse button the text is unhighlighted. I have checked this in Chrome and Firefox on Windows.

When I switch back to dev, I can select text and it stays selected; at that point, I am able to right-click and bring up menus. Help! 

Screenshot from dev:
image

**Comment by ThoWagen** [comment]
@sturkel89 Sorry, I missed that the textbox will be focused if you click anywhere and the keyboard is hidden. It should be fixed now.

**Comment by sturkel89** [comment]
Another test branch issue: there's a problem with prioritization of autofill suggestions and virtual keyboard controls.

- **TEST BRANCH**

When I'm typing with the keyboard and autofill suggestions come up, and then I go to change or check on virtual keyboard settings by clicking the icon in the searchbox, the autofill suggestions persist and I can't see the virtual keyboard dropdown:
image

- **DEV BRANCH**

If I follow the same sequence in dev, as soon as I click the virtual keyboard icon in the searchbox, the autofill suggestions disappear.
image

**Comment by sturkel89** [comment]
> @sturkel89 Sorry, I missed that the textbox will be focused if you click anywhere and the keyboard is hidden. It should be fixed now.

Good to know! I am doing an extensive review right now and will need to pull down your changes and make sure my critiques still apply! :-) 

(Update -- I see that this fix corrects everything I had been complaining about! I will now continue testing.)

**Comment by ThoWagen** [comment]
I think part of your second problem still exists. Now, that we focus the textbox when the keyboard is shown the autocomplete is also always shown. So, if we have the keyboard visible and hence also the autocomplete and then try to switch the keyboard layout the selection is still overlapped. 

We could either hide the keyboard when selecting a new layout or let the layout selection overlap the autocomplete. What do you think is more user friendly?

Edit: There is a third option: We don't focus the textbox when clicking the keyboard selection button.

**Review by sturkel89 — COMMENTED** [review]
I tested this branch against dev with both the virtual keyboard set to NONE, and with it activated with a language. With it set to NONE, behavior is identical between test and dev. With it set to a specific language, there is a consistent difference between test and dev in terms of cursor behavior when typing with the physical vs. the virtual keyboard. I am not sure that the difference is all that meaningful, though (it's just whether or not the flashing cursor is visible; it always appears at the appropriate location).

**EITHER BRANCH, Virtual Keyboard set to NONE in user interface:**

- When I click the VuFind logo to go to the home page (http://localhost/vufind_test/), the cursor is activated inside the searchbox. If I click anywhere else on the home page outside the search box, the flashing cursor disappears. It reappears if I click inside the searchbox.

- In search results view when the entered text is still visible, the flashing cursor appears ONLY when I click inside the searchbox at a specific spot. 

If I click elsewhere on the page, nothing happens within the searchbox and the typing on the physical keyboard does not affect the text in the searchbox.

- In record view with empty searchbox, the flashing cursor is activated ONLY if I click inside the searchbox. Clicking elsewhere on the page has no effect. (Of course, clicking a link activates that link!)

-----------

 **DEV BRANCH, Virtual Keyboard set to English in user interface:**

- When I click the VuFind logo to go to the home page (http://localhost/vufind_test/), the cursor is activated inside the searchbox. If I click anywhere else on the home page outside the search box, the flashing cursor disappears. It reappears if I click inside the searchbox, and the virtual keyboard appears on the screen.

_At that point: if I start typing with the physical keyboard, the cursor is visible/flashing after every keystroke. But if I start typing with the virtual keyboard, the cursor is not visible at all._

- In search results view when the entered text is still visible, the flashing cursor appears ONLY when I click inside the searchbox at a specific spot. This also activates the virtual keyboard. (Clicking elsewhere on the search results page does not make the cursor appear.) 

_At that point: if I start typing with the physical keyboard, the cursor is visible/flashing after every keystroke. But if I start typing with the virtual keyboard, the cursor is not visible at all._

- In record view with empty searchbox, the flashing cursor is activated ONLY if I click inside the searchbox. Clicking elsewhere on the page has no effect. (Of course, clicking a link activates that link!)

_Again, at that point: if I start typing with the physical keyboard, the cursor is visible/flashing after every keystroke. But if I start typing with the virtual keyboard, the cursor is not visible at all._


 **TEST BRANCH, Virtual Keyboard set to English in user interface:**

- When I click the VuFind logo to go to the home page (http://localhost/vufind_test/), the cursor is activated inside the searchbox. If I click anywhere else on the home page outside the search box, the flashing cursor disappears. It reappears if I click inside the searchbox, and the virtual keyboard appears on the screen.

**At that point: if I start typing with either the physical or virtual keyboard, the cursor is visible/flashing after every keystroke.**

- In search results view when the entered text is still visible, the flashing cursor appears ONLY when I click inside the searchbox at a specific spot. This also activates the virtual keyboard. (Clicking elsewhere on the search results page does not make the cursor appear.) 

**At that point: if I start typing with either the physical or virtual keyboard, the cursor is visible/flashing after every keystroke.**

- In record view with empty searchbox, the flashing cursor is activated ONLY if I click inside the searchbox. Clicking elsewhere on the page has no effect. (Of course, clicking a link activates that link!)

**Again, at that point: if I start typing with either the physical or virtual keyboard, the cursor is visible/flashing after every keystroke.**

**Comment by sturkel89** [comment]
> I think part of your second problem still exists. Now, that we focus the textbox when the keyboard is shown the autocomplete is also always shown. So, if we have the keyboard visible and hence also the autocomplete and then try to switch the keyboard layout the selection is still overlapped.
> 
> We could either hide the keyboard when selecting a new layout or let the layout selection overlap the autocomplete. What do you think is more user friendly?
> 
> Edit: There is a third option: We don't focus the textbox when clicking the keyboard selection button.

I'm not sure of the best technical solution, but I think that the user's deliberate click on the keyboard selection button has to override the automatic display of title options. Overlapping is kind of messy looking, so I think the behavior of dev would be the better solution.

**Comment by demiankatz** [comment]
@ThoWagen, I'm inclined to agree with @sturkel89 -- if we require the user to focus the text box in order to input text, instead of auto-focusing the box whenever the keyboard is active, the behavior should be more consistent/predictable, and we can then avoid the weird autocomplete problems.

I took a look at [Google's virtual keyboard](https://www.google.com/inputtools/try/) as a point of comparison, and it does require the input box to be explicitly focused in order to add characters there.

**Comment by ThoWagen** [comment]
@demiankatz I'm not sure if I understand what you mean. In order to see the virtual keyboard the users have to focus the textbox or have to select a new layout. In both cases the textbox is focused. In any other case the keyboard should not be visible and textbox not auto-focused.

@sturkel89 Besides the overlapping autocomplete and keyboard selection box is there still a problem? The behavior for the test branch you described above is what I intended to do in this PR and I thought that the behavior in the dev branch was the problem we discussed in #3248

**Comment by sturkel89** [comment]
I like seeing the cursor flashing as I type; that is how we have it set in our live VuFind at Villanova. So, I think the consistent behavior in the test branch is preferable. (Of course, the main behavior I describe of having the cursor appear only when you click inside the search box is also desirable!) 

So, from my perspective, the overlapping autosuggest & keyboard selection menus are the only remaining problem.

I will let Demian respond to your other question!

**Comment by demiankatz** [comment]
Sorry, @ThoWagen, I misunderstood the behavior. You are correct that what I said didn't make any sense. :-)

Regarding the technical solution, can we just adjust z-order to make the keyboard selection appear in front of the autocomplete suggestions? I think that might be enough to make everything functional.

**Comment by ThoWagen** [comment]
Now, the textbox is not focused and hence the autocomplete is not shown when clicking the keyboard selection button.

**Comment by demiankatz** [comment]
An elegant solution, @ThoWagen! @sturkel89, do you mind taking one last look at this?

**Review by sturkel89 — APPROVED** [review]
I see the improvement @ThoWagen put into place; there is no more overlap between the keyboard selection dropdown and the autocomplete title option, as the title autocomplete disappears when you click the virtual keyboard control.

I checked this behavior in all three themes, and it was consistent across themes.

I think this branch is ready to be merged!

**Pull request merged**
