### PR TITLE
SierraRest driver: Make CAS field mappings configurable.

### PR DESCRIPTION
**Pull request by demiankatz**

### CODE REVIEW

**Comment by demiankatz** [comment]
@EreMaijala, I'm making progress getting Sierra set up here at Villanova. However, it appears that the way you use CAS is a bit different from the way we do. This PR makes the population of the CAS form configurable, to support our situation (where username = name and password = code, as opposed to the default username = code and password = pin).

Any concerns about this? Do you think this has implications for the "change password" functionality? Maybe we can address this by simply saying "if password_field is not set to pin, then you should not enable VuFind's change password functionality while using this driver."

**Comment by EreMaijala** [comment]
Regarding the pin code, I think that's up to the institution to decide. If the patrons are used using something else as the password, they can probably adjust, and in most cases the library could just modify the translation for the login field description accordingly.

**Comment by demiankatz** [comment]
Thanks, @EreMaijala, I'll merge this as-is and we can refine the "change password" stuff later if a need arises.

Regarding the client credentials grant for global patron data, is this a setting that needs to be turned on at the API key level? (I'm not able to directly look at this myself, since somebody else is managing the Sierra side of things).

**Comment by EreMaijala** [comment]
Yes, as far as I know. I've never seen it myself either...

**Pull request merged**
