### PR TITLE
Added a pure PHP OCI8 wrapper for Voyager Oracle connections to elimi…

### PR DESCRIPTION
**Pull request by EreMaijala**
…nate the need to install the troublesome PDO_OCI module.

While the package name in composer.json hints at laravel, it's just a generic module.

This eliminates the need for https://vufind.org/wiki/installation:php_oci#set_up_pdo_oci and avoids trouble that the PDO_OCI module causes with Apache 2.4 and PHP 7 if "apachectl graceful" is executed (see e.g. http://serverfault.com/questions/763631/php-zlib-version-change-because-of-pdo-oci-after-an-apache-graceful-reload that we've experienced too).

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, this is great news!

A couple of things:

1.) Is "US_ACII" in the connection string correct, or is that a typo for "US_ASCII"?

2.) I try to pin very specific versions in composer.json to minimize the number of unexpected breaks caused by new releases. I'd recommend changing 1.* to the actual working version you are using. (Obviously this means we're going to have to do periodic checks for new releases of dependencies so we can manually bump these versions up -- but given the number of past problems we've had, I'd rather invest in that process than have to deal with sudden unpredictable breakages).

**Comment by EreMaijala** [comment]
1.) Oops, a typo it was. Note to anyone that might wonder: Voyager's database is marked to be US_ASCII even if it includes UTF-8 in some tables.

2.) Done.

**Comment by demiankatz** [comment]
Thanks! I'll test this out in the near future.

**Comment by EreMaijala** [comment]
Thanks. Looks like we need to push this into production pretty quickly to get rid of the malfunctioning PDO_OCI module.

**Comment by demiankatz** [comment]
Seems to be working fine for me. Thanks again!

**Pull request merged**
