### PR TITLE
Disable deduplication listener when search parameters contains child filter

### PR DESCRIPTION
**Pull request by xrosecky**
Disable deduplication listener when search parameters contains child filter.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @xrosecky. I'm asking for @EreMaijala's review of this, since he's the expert on the DeduplicationListener. I also wonder if it might be useful to add a comment to the new method mentioning that merged_child_boolean comes from RecordManager, since it is not used or mentioned anywhere else in the VuFind code, which might cause confusion in the future.

**Review by EreMaijala — APPROVED** [review]
Looks good to me, though I'd like to know more of the use case for this. Perhaps a comment referring also refer to the wiki page at https://vufind.org/wiki/indexing:deduplication would be what's needed to clarify this? Perhaps even at the top of the file?

**Comment by xrosecky** [comment]
Our use case is special API for searching in child documents.

**Comment by demiankatz** [comment]
Good idea, @EreMaijala. I've added a comment to the top of the file. @xrosecky, do you want to make any further adjustments, or is this now ready to merge?

**Comment by xrosecky** [comment]
It is ready to merge.

**Comment by demiankatz** [comment]
Thanks! Merging now.

**Pull request merged**
