### PR TITLE
SierraRest: Refactor authorization grant requesting to make it more r…

### PR DESCRIPTION
**Pull request by EreMaijala**
…obust.

Now works with curl adapter and doesn't rely on the number of redirects.

### CODE REVIEW

**Comment by demiankatz** [comment]
@EreMaijala, this looks pretty reasonable to me, but I don't currently have a valid account on my local Sierra system, so I'm going to wait until I can get that restored so I can actually confirm that this works in our environment.

**Comment by EreMaijala** [comment]
@demiankatz Any progress on this one?

**Comment by demiankatz** [comment]
@EreMaijala, not forgotten about; I've just had trouble getting a valid test environment set up. I think I'm close, though -- should be able to work on this some more next week.

**Comment by demiankatz** [comment]
I was finally able to test this, and it seems to be working fine in my environment. Sorry for the long delay; merging now!

**Pull request merged**
