### PR TITLE
Fetch only requested facets from Solr

### PR DESCRIPTION
**Pull request by xrosecky**
Replaces #2271.

### CODE REVIEW

**Comment by xrosecky** [comment]
I'm not sure whether enabledFacets should apply also on checkbox facets?

**Comment by demiankatz** [comment]
@xrosecky, I think @EreMaijala said that he has some local customizations that allow checkbox facets to include result counts, so failing to exclude checkbox fields might break that. @EreMaijala is on holiday until August, so we might have to wait until then to get more clarification from him.

Where/how is this new feature used? Do you plan to include an example of setting up the enabledFacets setting? I think Ere's requirements may depend on how the rest of the solution falls into place.

**Comment by xrosecky** [comment]
It is optimalization - pass to Solr only required facets, parameter enabledFacets is already used in AJAX calls:

https://github.com/vufind-org/vufind/blob/dev/themes/bootstrap3/js/facets.js#L178

**Comment by demiankatz** [comment]
Ahh, thanks for the clarification, @xrosecky! We should probably wait for further input from @EreMaijala before merging this, but as long as his use case is met and the tests pass, this seems straightforward to me.

**Review by EreMaijala — APPROVED** [review]
This should be fine. We actually do the same but also filter checkbox facets by `enabledFacets`. I'm not sure but perhaps you could do the same here.

**Comment by demiankatz** [comment]
Thanks, @EreMaijala and @xrosecky. I'm going to merge this as-is since it's forward progress. If more work on checkbox facets would further improve performance, please feel free to open a follow-up PR focused on that issue.

**Pull request merged**
