### PR TITLE
FOLIO: use getPagedResults for items and holdings in getHolding

### PR DESCRIPTION
**Pull request by ihardy**

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @ihardy, this makes perfect sense to me, though I'm not yet in a position to actually test it from here. Is there anyone else we should try to get review/approval from before merging?

**Comment by ihardy** [comment]
Thanks @demiankatz it's working OK for Simmons. @mis306lu is the only other one I know that is running in production for sure. Look OK to you Michelle?

**Comment by mis306lu** [comment]
@ihardy, @demiankatz  - It's working at Lehigh (I tested it locally pointing to our test srvr).  thank you!

**Comment by demiankatz** [comment]
Thanks for the confirmation, @mis306lu!

**Pull request merged**
