### PR TITLE
Add Piwik tracking to lightbox template

### PR DESCRIPTION
**Pull request by samuli**
Add Piwik tracking to lightbox template using Page URLs.
Record page tabs are tracked as /Record/[id]/[tab]

### CODE REVIEW

**Comment by crhallberg** [comment]
After a little confusion for this Piwik newcomer, I can see that the tracking is working correctly! I was just wondering if you were doing anything on your end that differentiates the lightbox requests from the regular requests.

**Comment by samuli** [comment]
This embeds Piwik js-code to the template layout/lightbox.phtml, so that lightbox actions such as 'Save to List' get tracked when the lightbox is opened. Same thing that was done for Google Analytics (https://github.com/vufind-org/vufind/commit/b0c66884fb9bf5984bce673888ac150bb9c11028).

Ajax-requests to record page tabs are converted to more readable Piwik page URLs: /record/[id]/AjaxTab is tracked as /record/[id]/[tab], for example /record/[id]/toc for Table of Contents.

**Comment by crhallberg** [comment]
This pull request inspired us to update the Google Analytics code, so there is now a conflict in layout/lightbox.phtml. Fix the conflict and we'll merge this in! Thank you!

**Comment by samuli** [comment]
Fixed now.

**Comment by demiankatz** [comment]
Thanks!

**Pull request merged**
