### PR TITLE
Fix for the ajaxLoadTab method in record.js

### PR DESCRIPTION
**Pull request by guenterh**
Hi Chris
I took a look into your fix for the method you have done yesterday.
Please don't use the substring method with one parameter as it produces error messages. Not only in relation to the Tab mechanism but also using the login dialog on the Record-Controller page (which leads to a popup dialog box still open after successful login). I'm not a specialist in JavaScript programming but looking into  http://www.w3schools.com/jsref/jsref_obj_string.asp it is defined with only two parameters (which produces the error in the application)

I tried to make the method a little bit more stable as I'm not pretty sure if the   match method in 
document.URL.match always returns an array. Therefore the additional Array type operation.

The propsoed implementation in this pull request fit's for  all the cases I have seen - so far - in our use case.

Please give it a try!

Günter

### CODE REVIEW

**Comment by crhallberg** [comment]
Based on what I understand about match, it will always return an array or null: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match.

If we tweak the regular expression (I don't think we need to check for an ending slash since we're using a word boundary \b) we could use this to get the path we want.
```JS
var urlroot = document.URL.match(new RegExp('/[^/]+/'+id+'\\b'))+"/";
```
We still need something at the end though to keep `id123` from matching `id1234`

**Comment by guenterh** [comment]
@crhallberg 
Hi Chris,

thanks for your comments.
I looked into it this morning:
- you are right with your hint in the eMail that Array.isArray is part of ECMAScript 5 and IE8 at the moment is the only 'current' browser not supporting this functionality
(compare http://kangax.github.io/compat-table/es5/)

- 'From my point of view' even the word boundery part could be ommited because we are looking only for the Controller and id part of the haystack. I made some tests with both alternatives and I haven't found any thrown execptions. So you could use one of them - IMHO

- Personally I'm not really happy with implementations using implicit conversions like
document.URL.match(new RegExp('/[^/]+/'+id)) + "/";
where Array types are converted to String types but it is possible with JavaScript - so go for it from my point of view. 

- Please don't use substring (or substr) on the return value of the String.match method because (as you wrote) return type is Array or null. This definitely throws an exception. (see my attached picture) 

- I don't understand your hint
>>We still need something at the end though to keep id123 from matching id1234<<
because we are searching for an id referenced by the variable id which should always match if available.


As an additional question (not part of this thread)
Do you support IE8 with bootstrap3?

Günter

**Comment by guenterh** [comment]
js substring error

**Comment by crhallberg** [comment]
Sorry for the delay, I just ran into this error and came back to this. Sorry for the confusing comments and hints, I was thinking with my fingers. I covered everything in the new RegExp.

Your newest version looks good, watch your empty lines is all I would say. If this passes all your tests, I'll merge it in!

Yes, IE8 is supported in Bootstrap 3. The first isArray hack I thought of was `typeof X.sort === "function"` but maybe using jQuery's function would be better: http://api.jquery.com/jquery.isarray/. Do we still need this check in the latest version?

**Comment by guenterh** [comment]
@crhallberg 
Thanks Chris for your response.
I will take a look into it tomorrow. It's already quite dark in Europe...
Günter

**Comment by demiankatz** [comment]
Thanks to both of you for working on this fix. Chris, let me know if you'd like help merging this onto master with a simplified/cleaned up history.

**Comment by guenterh** [comment]
@crhallberg 

Hi Chris,

I made some tests with the current status of the Pull request and read a litte bit about the differences of null and undefined in JavaScript. (so hopefully I learned something...) 

Here my conclusion:
- from my point of view you can use both alternatives of the current RegEx in the PullRequest 
  //var urlroot = document.URL.match(new RegExp('/[^/]+/'+id+'\\b')) + "/";
  //var urlroot = document.URL.match(new RegExp('/[^/]+/'+id)) + "/";

With and without word boundery. Although I think word boundery isn't necessary for our use case it doesn't hurt. Perhaps you have a special reason for it I don't see?

- both alternatives patch the current errors thrown by the method ajaxLoadTab
a)  change of tabs 
b) https://github.com/swissbib/vufind/issues/167  (sorry only in German).
We saw the second one in our implementation.  In short: A login on the full view page is succesful but the pop up login dialog won't close because it stumbles upon a JavaScript error in our discussed method.

- I think we can use your suggestion with the implicit conversion of Array to string because the match always should fire where the one dimensional array (containing the match) is converted to string and concatenated with the trailing slash necessary for the whole URL.

-  I thought about something like
  if  (! (urlroot === null)) {
    var controllerPath = urlroot[0] +  '/AjaxTab';
  }
  $.ajax({
    url: path + controllerPath,
    type: 'POST',
    data: {tab: tabid},
    success: function(data) {
      $('#record-tabs .tab-pane.active').removeClass('active');
      $('#'+tabid+'-tab').html(data).addClass('active');
      $('#'+tabid).tab('show');
      registerTabEvents();
      if(typeof syn_get_widget === "function") {
        syn_get_widget();
      }
    }
  });

but I think it isn't more stable because what happens if the match doesn't fire?

So please choose one of the both regex and I think we can close this issue.

Best wishes from Basel!

Günter

**Comment by crhallberg** [comment]
You're right that the word boundary isn't needed.

If urlroot is null for some reason, we shouldn't do the ajax call, instead we should return true so that the link on the tab is followed.

**Comment by guenterh** [comment]
Hi Chris,
sorry for the delayed answer but I was busy with other things today.

Yes you are right something should be done in case the RegEx doesn't match. (Although I think it should always match)
I thought about it too but I haven't seen so far there is a link behind the HTML-element rendering the tab header. So I wasn't sure what should be done with the Ajax-Call if we cannot figure out the link with code dynamically. 

From my point of view: Go for it!

Günter

**Comment by crhallberg** [comment]
I'm going to go for it and merge it manually on my end. Thank you very much for this!

**Comment by guenterh** [comment]
It's fine with me! Merging is too much effort for these few lines. I think it was it worth for discussion.
Günter

**Comment by crhallberg** [comment]
Manually merged: https://github.com/vufind-org/vufind/commit/892e0ceee82e900a7da03b15903f5113b9aa368b

**Pull request closed without merging**
