### PR TITLE
Added support for limiting ILS password to numeric or alphanumeric.

### PR DESCRIPTION
**Pull request by EreMaijala**
TODO:

  - [x] jquerymobile support
  - [x] validation of passwords during account creation in addition to password changing

### CODE REVIEW

**Comment by demiankatz** [comment]
Do you think it might be more flexible to change the configuration options to include a regular expression and a hint to display when the regular expression fails to match, rather than creating specific implementations for specific named options? Obviously we could include sample regexes for those scenarios in the .ini file to achieve the same effect, but then it would also be easier to support additional cases we haven't thought of yet. What do you think?

**Comment by EreMaijala** [comment]
I thought about it and it's still possible to add it, but with a regexp it's difficult to give the user a hint up front about the allowed values. I also thought about showing what doesn't match the pattern, but that wouldn't be good as it would display parts of the password. However, I've just added support for specifying the pattern as a regexp in addition to the other two options, so now both approaches are possible. What do you think?

**Comment by demiankatz** [comment]
Thanks, looks good. A couple additional questions/comments:

1.) Do you think it's worth adding a configuration for a hint to go with the regular expression, so the user can specify the password rules through the config file? (This string would, of course, be subject to translation). Perhaps the hint should be included as part of the policy data structure in all cases?

2.) I notice you've added a CSRF to one of the templates, but I don't see any controller-side changes related to this. Is this a bug fix, or an incomplete implementation? (I'm mainly trying to determine whether or not this change needs to be fast-tracked into the 3.0.1 release).

**Comment by EreMaijala** [comment]
1.) Good idea, done.

2.) I mentioned it briefly in the commit message but forgot to comment. There's a login() call at the end of MyResearchController::newPasswordAction(), and it fails without a correct csrf causing an error message to be displayed after the password was changed even if everything went otherwise fine. That said, I'm not sure why it's there but decided agains removing it if it actually serves a purpose.

**Comment by demiankatz** [comment]
Thanks for the clarification. I've pushed the CSRF fix into the release-3.0 branch (along with a test case to prevent regressions) in time for the 3.0.1 release. The rest looks good, but I want to spend a little time playing with it before I merge, which will hopefully happen early next week (though not on Monday, as we're closed for the Memorial Day holiday). Have a good weekend -- more soon!

**Comment by demiankatz** [comment]
I've merged your template renaming into master to simplify this pull request, as that seemed like a change worth addressing independently of the new functionality. A bit more reviewing reveals two more issues to think about:

1.) This PR addresses password validation when changing passwords, but it does not address password validation when creating new accounts. We should be consistent in both of those places.

2.) This PR does not cover the jquerymobile theme.

I've added some TODO checkboxes to the PR description so we can keep track of these issues. If you have time to work on either or both, please check them off as you go. If you do not have time for either or both, let me know and I'll try to get them onto my own to-do list when time permits. Thanks!

**Comment by EreMaijala** [comment]
1.) Does it need to? I mean, the only place where you could limit that is creating a local account, and there are probably no reasons to limit the choices, no? If, on the other hand, you're using e.g. ILS authentication to create the account, you should be able to log in if the ILS accepts your credentials. What prompted development of this is the requirement to limit ILS passwords so that user's can still log in with self-service machines that only have alphanumeric keyboard or a numeric pin pad.

2.) Right, I (once again) completely forgot that. I'll try to deal with it later this week.

**Comment by demiankatz** [comment]
1.) In your use case, the purpose of the limitation is for compatibility with an ILS... but I could also envision a (probably increasingly common) use case where local security policy requires that passwords conform to certain rules, and this provides a mechanism to enforce that. In any case, the existing min/max length settings are enforced in both creation and password changing, so it would be a strange inconsistency to ignore one setting while enforcing another. But as I say, if this is not important for you, I'm willing to put in the time to implement it -- but I think it should be done before we merge.

2.) Thanks! I'm hoping we can consider eliminating jquerymobile in the not-too-distant future, but until we do, I'd like to keep it in sync. Again, I can help if necessary!

**Comment by EreMaijala** [comment]
1.) Policies are a good point. Thanks for pointing that out. I'll take care of it.

**Comment by EreMaijala** [comment]
Both issues should be done now. I didn't add JS validation to the jquerymobile theme since there wasn't any for the password length either, but the hint should be properly displayed.

**Comment by demiankatz** [comment]
Thanks -- nearly there! Just a few more points to consider:

1.) Are the changes to the Demo ILS driver necessary? It seems to me that the policy setting is coming from config.ini, so the driver doesn't need to be providing it -- I'm guessing this may be a relic from an earlier version of the code.

2.) Do you have any objection to setting the default hints in getPasswordPolicy() instead of in the templates? This would seem to eliminate a lot of redundant business logic in the templates.

3.) I notice that right now, you are taking the user-provided pattern setting and putting slashes around it. Would it be better to accept the full regular expression, including delimiters, so that users could include modifiers or use alternate delimiters? Given that this is an advanced feature, it seems worthwhile to give maximum flexibility.

I'm happy to take care of any or all of these changes as part of the merge process -- but I wanted to get your input in case you feel differently about any of them.

Thanks!

**Comment by EreMaijala** [comment]
1.) No, it was just an easy way to test it in the beginning. 

2.) I thought about it but decided it was up to the display logic to decide what to show, but admittedly that's practically duplicates, so I'm ok with moving the logic into the controller. You could still leave the original values there so that if a template needs to do something special they're still available.

3.) True, that would be more flexible.

Please feel free to make these changes. Thanks!

**Comment by demiankatz** [comment]
Great, thanks! Regarding item 2, I think it's a safe argument that in this case, the value of the hint has to be determined by the controller (because of the need to check configuration), so the display logic's job is simply to decides how to display the hint that is provided to it. You can still modify the hint or give it special handling from within a custom template if you need to, based either on the text of the hint itself or other password policy context. In any case, I'll take care of these adjustments and merging either later today or tomorrow.

**Comment by demiankatz** [comment]
Okay, here is my revised code, committed to master: https://github.com/vufind-org/vufind/commit/d27a6282bc7678b617e5238393a672a405598e17 -- please give it a test and let me know if I've messed anything up!

Note that I ended up leaving the regular expressions alone, since adding support for arbitrary delimiters and modifiers would have broken the use of the HTML5 pattern attribute.

**Pull request closed without merging**
