### PR TITLE
Sfxembargoes

### PR DESCRIPTION
**Pull request by johnjung**
Add embargo statements for SFX. Thank you!

### CODE REVIEW

**Comment by demiankatz** [comment]
Just one question about this: is there any chance that some of these elements may be absent under certain circumstances? If so, it may be wise to add some isset() checks with defaults to blank strings so we don't fill up the error log with notices about undefined properties.

**Comment by johnjung** [comment]
I should add that just to be safe. I'll upload that in a few minutes.

**Comment by johnjung** [comment]
Ok- I added a check to be sure the element exists. Does this look ok?

**Comment by demiankatz** [comment]
Looks pretty good, but the line lengths are causing the build to fail (style compliance problem). How about this version?

<pre>
            if (isset($target->coverage->coverage_text)) {
                $coverageText = & $target->coverage->coverage_text;
                $record['coverage'] = (string)$coverageText
                    ->threshold_text->coverage_statement;
                if (isset($coverageText->embargo_text->embargo_statement) {
                    $record['coverage'] .= ' ' . (string)$coverageText
                        ->embargo_text->embargo_statement;
                }
            }
</pre>

I can't test it, but do you mind giving it a try?

**Comment by johnjung** [comment]
There was a missing right paren in the snippet above, but once I added it back the logic above worked fine. Thanks for working with me on this.

**Comment by demiankatz** [comment]
Manually merged. Thanks!

**Pull request closed without merging**
