### PR TITLE
Fix minimum age check in expiration util.

### PR DESCRIPTION
**Pull request by EreMaijala**

### CODE REVIEW

**Comment by EreMaijala** [comment]
The second commit makes fractional values possible. This may be useful since there can be quite a few sessions during one day (and PHP's cleanup sometimes does less than a stellar job).

**Comment by demiankatz** [comment]
I've cherry-picked the bug fix to release-4.1 so we can include it in release 4.1.2. I'll review the float portion of the PR in the near future (though it looks safe enough at a glance).

**Comment by EreMaijala** [comment]
I'm already using the float change in production if that's of any assurance. :)

**Comment by demiankatz** [comment]
Thanks; good enough for me!

**Pull request merged**
