### PR TITLE
Added support for Solr's MoreLikeThis query handler that also support…

### PR DESCRIPTION
**Pull request by EreMaijala**
…s sharded indexes in SolrCloud.

I didn't make it default since the new MLT handler returns slightly different results. Upside is that it's easier to tweak the settings just by modifying searches.ini.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks for this. A couple of comments/questions:

1.) It appears that the biggest difference between the two methods is that the query handler is not using field-specific boosts. That's a fairly serious limitation, and possibly one that can be worked around. [This Solr JIRA Ticket](https://issues.apache.org/jira/browse/SOLR-7143) has some mentions of boosts in the comments that suggest the issue may have been fixed, though it may also have gotten accidentally dropped somewhere along the way. The documentation is not very helpful. It might be worth hitting the Solr mailing list to see if there is a solution to this problem or whether we need to open a new JIRA ticket and try to fix this for a future release. If we can solve the boost problem, I'd be inclined to make this the new default setting so sharding just works. If we can't, though, I agree with keeping the old default at least for now.

2.) In at least [one case](https://github.com/vufind-org/vufind/blob/master/module/VuFind/src/VuFind/RecordTab/SimilarItemsCarousel.php#L75) we pass a 'rows' parameter to the similar() method of the backend. The count setting in searches.ini currently overrides this when using the new method. I think we should treat the count setting as a default but allow it to be overridden. This also raises the question of whether we need to worry about other override parameters that may differ between the two methods.

If you would like me to do further research regarding the boost issue, just let me know -- I decided not to spend a lot of time on it before hearing back from you in order to avoid duplicating any effort you have already spent in this area.

**Comment by demiankatz** [comment]
Thanks for the rows fix -- that was easier than I thought, somehow.

Any thoughts regarding boosting? Please let me know if you'd like me to follow up on this with the Solr community.

**Comment by EreMaijala** [comment]
Oops, somehow I failed to submit the following comment.

1.) True. I've tested adding boosts to the fields and also checked the code (though it's been a while), and it didn't seem to support boosts. It would of course be great to have, but I haven't pursued it further. If you have further ideas apart from creating yet another JIRA issue, please feel free to pursue them. 

2.) Fixed overriding the rows parameter. The only other param that's overridden is q, and that was the case also before, so I'm not too concerned about that.

**Comment by demiankatz** [comment]
A few more comments:

1.) An architectural consideration, upon further examination of the code: I think this PR is putting too much responsibility into the connector, which should really just be about connecting to Solr. (Admittedly, it's following an existing precedent of the Connector generating the 'q' parameter). I think it might be smarter to move this logic up a level into the Backend, so that all the Connector does is pass the parameters along to Solr. In fact, it might make the most sense to have a SimilarBuilder.php similar to QueryBuilder.php that wraps the configuration settings and takes care of the MLT parameter generation, to prevent any of the existing classes from getting too complicated. Just like QueryBuilder, the Backend could construct a default SimilarBuilder if none is provided, but we can add logic in the factory to make use of your new configurations to build a custom-configured one. If you agree with this in principle but don't have time to implement, let me know and I might be able to find time to revise this PR.

2.) Right now the MoreLikeThis/count setting is only used when the handler is in place... but I see no harm in making it work for both the handler and the component. Any objections?

3.) I'm going to do a bit more testing/research today regarding the boosting issue and will post to solr-user if I don't find a definitive answer. I'll report back here if I find anything of note.

**Comment by demiankatz** [comment]
Posted this thread:

http://mail-archives.apache.org/mod_mbox/lucene-solr-user/201607.mbox/%3CFAA7DF3F09441B4DA93A34DF74596140627625A3@VUEX14MB1.vuad.villanova.edu%3E

No replies yet. @EreMaijala, if no late answers come in, perhaps it's worth bumping the thread with a "yeah, I'd like to know" when you get back from vacation, in case it just got missed this time around.

**Comment by samueloph** [comment]
Hi @EreMaijala, I think there's a typo on https://github.com/vufind-org/vufind/pull/730/files#diff-803f66e32b76925fae34191072487a85R614

s/sharded/shared/g

**Comment by EreMaijala** [comment]
@samueloph Thanks, but it's actually correct. It refers to index consisting of multiple shards.

**Comment by EreMaijala** [comment]
Doesn't look like there'll be any answers on the solr-user list. I'll work on the other issues, so that this could, perhaps, be merged even with the known downside.

**Comment by demiankatz** [comment]
Thanks, Ere. I'd also be interested to find out what happens if you merge in #769 and upgrade to the latest Solr 6 release and test the functionality there -- just in case later Solr releases add functionality. (I'm not particularly optimistic, but if our solr-user posts are getting ignored on the basis of "they're using an old version" this might be the remedy). Obviously we shouldn't push up the #769 functionality to this branch, but it would be pretty easy to create a temporary local branch that pulls both things together for the purposes of testing. In any case, let me know if I can be of further assistance with anything!

**Comment by EreMaijala** [comment]
I think I've tested it with Solr 6.1 to no avail.

**Comment by demiankatz** [comment]
Too bad, though I'm not surprised! I guess for now we can move forward with the improvements that are within our capabilities. Perhaps before merging, we can make one last attempt to get the attention of somebody on the inside who knows something about this (or take a deep dive into the Solr code to try to figure it out). I'll try to keep this in mind as a talking point if I run into any Solr developers at conferences, etc., in the near future (though I don't have any immediate conference travel plans right now).

**Comment by EreMaijala** [comment]
I've now added a SimilarBuilder class along the lines of QueryBuilder. I also added a couple of tests to verify that it works properly.

**Comment by demiankatz** [comment]
Thanks. Looking pretty good. A few minor comments, all of which I'm happy to take care of myself if you don't have time but approve of the suggestions:

1.) Should we amend the searches.ini comment "Only the MoreLikeThis query handler supports sharded indexes" with "but as of this writing, the traditional component offers more nuanced relevance ranking."

2.) The count setting comment says "If the MoreLikeThis handler is used," but if I'm reading the code correctly, it's now universal. Am I mistaken, or can we remove the conditional statement?

3.) In the similar builder, do you think it would improve readability to remove "mlt" from class properties? Since the properties are now defined in the context of an MLT-specific component, this may be unnecessarily redundant. If you prefer it as-is, though, that's okay with me.

4.) Would you agree that we can resolve https://vufind.org/jira/browse/VUFIND-652 after merging this? If so, is it worth opening a new ticket on our end and/or in the Solr JIRA about the lack of proper relative boost support in the handler?

5.) Do you think the potential BC break of the signature change on Connector::similar() is sufficient to hold this off until release 4.0, or should we slip this into 3.1? One possible compromise might be to leave in an unused $id parameter for 3.1 and then change the signature in 4.0.

**Comment by EreMaijala** [comment]
I agree with you and appreciate it if you have time to tweak them. WRT 5, I'm ok with either approach. Maybe leaving in $id would be the safe approach (and now that I think of if, maybe there could be a case where it could still be useful).

**Comment by demiankatz** [comment]
Great, thanks. I'll try to work on all of that later today.

**Comment by demiankatz** [comment]
Updated and merged -- thanks again! I'm disappointed that we couldn't get clarity on the weighting of parameters in the handler, but this is better than nothing.

**Pull request merged**
