### PR TITLE
Alma: Fix handling of empty API response with status code 204.

### PR DESCRIPTION
**Pull request by EreMaijala**
This fixed hold cancellation to not throw an error when trying to decode the answer.

Alma reports the empty response to be gzip-deflated, which might contribute to this. I'm not sure if that's appropriate, but at least we can avoid trying to get the response body when one shouldn't even be available.

### CODE REVIEW

**Comment by demiankatz** [comment]
This definitely makes sense to me, but I'll once again defer to @betullam's review.

**Comment by betullam** [comment]
@EreMaijala and @demiankatz - For your information: I saw your request for review but I have another event this week that is also quite time-consuming in preparation. I hope I can do the review by the end of week.

**Comment by demiankatz** [comment]
@betullam, no problem -- good luck with the event!

**Review by betullam — APPROVED** [review]
Sorry again for the long delay. I could finally test it. It works and also makes sense to me.

**Comment by demiankatz** [comment]
Thanks -- merging this one too!

**Pull request merged**
