### PR TITLE
Fixed OpenURL click handling when loading Combined results with ajax.

### PR DESCRIPTION
**Pull request by EreMaijala**
I tried to make this backwards-compatible so that it works with customized openurl.phtml files too, but of course if would be cleaner to get rid of the counter completely.

### CODE REVIEW

**Comment by demiankatz** [comment]
Ere,

Given that we already have some BC-breaking OpenURL refactoring in the next release, now might be the time to get rid of the counter if you feel we don't need it. I can just add a note about it to the existing list in the changelog.

Let me know if you think it's worth doing; I'll hold off on testing/examining this more closely until I hear more from you. (I might also wait until after next Tuesday, when I'm planning on officially removing the Blueprint theme... that will make it even easier to say with confidence that the change will have no dramatic impact on anything).

**Comment by EreMaijala** [comment]
Ok, good. I removed the counter.

**Comment by EreMaijala** [comment]
I also did a bit more cleanup to results-ajax.phtml to build the whole JS block in one place.

**Comment by demiankatz** [comment]
Looking good. Manually merged to master to flatten commit history.

**Pull request closed without merging**
