### PR TITLE
DAIA driver update with breaking changes

### PR DESCRIPTION
**Pull request by lahmann**
This is an update for the DAIA ILS-driver including **two breaking changes**:
* the signature of the DAIA driver changed, so that a DateConverter object needs to be provided
* the legacy support (compatibility to DAIA in VuFind2.3) got deprecated

Other changes:
* xml gets converted to json which simplifies mapping of DAIA-responses to VuFind data structures
* refactored DAIA code for more hooks for customized modules
* several bugfixes
* reports always success to Autoconfigure ILS-Test querying id "1" (not a valid DAIA id) (this is pretty much a **hack** -- maybe there is a neater way to fix the autoconfigure ILS-test reporting DAIA as broken)

### CODE REVIEW

**Comment by demiankatz** [comment]
A few initial comments:

1.) Travis failed due to php-cs-fixer issues; I've just pushed up corrections.

2.) Have you talked to @jochen-lienhard about this? Since I can't test it, he'd be an obvious collaborator to test that this works across multiple instances.

3.) Regarding the autoconfigure hack, I see a checkForILSTestId() method, but it does not appear to be getting called anywhere. Am I missing something? In any case, I think the expectation is that requesting a non-existent ID will return an empty array rather than a fatal exception. If you don't think that's reasonable behavior for an ILS driver, perhaps we should brainstorm a better test for the auto-configuration routine. I'd definitely like to avoid having a weird hack like this make it into master, if the hack is truly necessary.

**Comment by lahmann** [comment]
Demian, thanks for looking into this and fixing the php-cs-fixer issues!

2.) Yes, I emailed off-list a few days ago with @jochen-lienhard and he acknowledged this DAIA driver. However, I would welcome any external test (as you read on the tech-list Kristof tested this driver successfully).

3.) Hmm, you are right - this method obviously is a left over as getStatus() does already report back an empty array (logs exceptions). I wonder how that method managed to remain on my notes _and_ in the code... sorry for that.

**Comment by demiankatz** [comment]
Great! If you and Jochen are happy with this, I'm content to merge to master if you want me to... but if you'd like to leave this as a PR for a while so more people can comment, that's fine too. Please let me know what you prefer and I'll act accordingly. Thanks!

**Comment by olli-gold** [comment]
I have tested the new driver and unfortunately it doesn't work for me out of the box. Perhaps the problem is our old DAIA server; I have to investigate this a bit more... 

Since the driver is breaking backward compatibility it would be perhaps a good idea to rename it, so that its easier to switch between the different versions?

**Comment by lahmann** [comment]
Thanks for the feedback! I'm curious what your further investigations will reveal.

Regarding renaming the driver I understand your concern - we added legacy support in VuFind2.4 after discussing the pros and cons of another DAIA driver in #281 (at that time a pure JSON implementation of DAIA) and agreed that multiple DAIA drivers would complicate the upcoming DAIA-PAIA stack. Especially as mapping and handling of DAIA responses differed widely between the added DAIA implementation from #281 and the DAIA driver included in VuFind2.3, streamlining the JSON and XML logic in the new driver should now finally allow to produce consistent behaviour independent of DAIA configuration.

After adjusting `DAIA.ini` the driver should behave almost the same as the old one. Apart from the changed ini settings the only really breaking change is the changed signature of DAIA's constructor, which should pose no problem unless you are using the old DAIA driver in a custom module. Any other change in the code only affects mapping of DAIA responses and VuFind data structure which can now easily customized by the newly added getItem* methods.

Please let me know if you need help - I am sure we can get the new driver up and running with your old DAIA server. :)

Best,
André

**Comment by demiankatz** [comment]
I agree that it is better to keep just one DAIA driver, as long as we can ensure compatibility between that driver and all servers. I also agree that the backward compatibility breaks are relatively minor. One suggestion, though: for the configuration change, perhaps it is worthwhile to detect if the new configuration section is missing and the old configuration section is present and throw an exception in that case -- this will help people realize that they have to upgrade their configuration, just in case they didn't read the changelog carefully.

**Comment by lahmann** [comment]
Demian, that's actually a very good idea - I added such an ILSException. Thanks!

**Comment by olli-gold** [comment]
I have found the problem preventing the driver to work correctly here. It was just a configuration issue - we are not using a prefix for Daia IDs and I forgot to configure that. So the deafult "ppn:" had been used and that was not working. Now I have set daiaIdPrefix to "", and its working.

So no more concerns from my side for now ;-)

**Comment by lahmann** [comment]
Great, thanks a lot for testing the driver! :)

**Comment by demiankatz** [comment]
Hello, everyone. I've just gone ahead and manually merged this to master, flattening the commit history into two commits: André's initial work, and Kristof's bug fixes. I think this will make the history easier to review in future if there are any questions about how things developed. I've also gone ahead and deleted the PICA driver from master, since this refactoring breaks it, and I don't think anyone has ever used it anyway. Might as well eliminate obsolete code to prevent confusion. If we need it back, we can retrieve it from Git easily enough!

**Comment by olli-gold** [comment]
Thank you, Demian. Right, the PICA driver on VuFind 2.x has never been used productively (as fas as I know), and it was not working correctly. In the future it should be replaced by the PAIA driver anyway, so there is no use for the old PICA one anymore. So its absolutely okay to remove it from master.

**Pull request closed without merging**
