### PR TITLE
Avoid broken links being generated by Record View Helper

### PR DESCRIPTION
**Pull request by mtrojan-ub**

### CODE REVIEW

**Review by demiankatz — APPROVED** [review]
Thanks, @mtrojan-ub, this looks reasonable to me, and I've added a unit test to confirm the expected behavior. I'll cherry-pick this back to the release-9.0 branch tomorrow unless @EreMaijala has any concerns in the meantime.

**Review by EreMaijala — APPROVED** [review]
Looks good to me.

If we were to start from scratch, I'd avoid prepending anything in getCurrentHiddenFilterParams since its caller should know best what to prepend, and not doing it automatically would make it harder to make these mistakes. But this is good in keeping things back-compatible.

**Comment by demiankatz** [comment]
Thanks, everyone -- as planned, I've backported this to release-9.0 so we can take advantage of the fix in Monday's release.

**Comment by demiankatz** [comment]
To @EreMaijala's point, we could consider deprecating getCurrentHiddenFilterParams  in future in favor of a new method that eliminates the prepending functionality... but that's a conversation for another day. :-)

**Pull request closed without merging**
