### PR TITLE
Callnumber improvements

### PR DESCRIPTION
**Pull request by demiankatz**
Call number handling can be simplified due to improvements in SolrMarc and the AlphaBrowse handler.

### CODE REVIEW

**Comment by demiankatz** [comment]
TODO: introduce 'callnumber-sort' field and investigate the possibility of eliminating the plain 'callnumber' field.

**Comment by demiankatz** [comment]
Okay, I believe this is now complete, but I'll give it a few days for review before merging.

**Comment by todolson** [comment]
Generally, I think this looks pretty okay, but will try to test on some local data this week. There are two minor questions in my mind:

* The `callnumber` field type has a very general name, but cannot be general use as spaces are stripped at index and query time, so is that the right name? (Of course I don't have a better name to offer.)

* I foresee wanting a way to search with and without call number prefixes, like `f` for folio, and these will vary somewhat between libraries. Do you see the pattern in the  `callnumber` field type definition as a place where that could happen, and be reasonable configured by an individual site?

**Comment by demiankatz** [comment]
Thanks, Tod.

Regarding the callnumber field type, what would you think of searchable-callnumber, callnumber-search, or some variation like that? I'm happy to change it.

Regarding prefixes, I imagine the best approach would depend on the complexity of the prefixing system. It would certainly be possible to add a pattern to strip off prefixes, assuming a simple and easily identifiable scheme. Alternatively, it might also be possible to handle them through munge rules in searchspecs.yaml, if a solution were necessary that didn't involve modifying the Solr schema. I don't think there's any simple way of handling it generically, so some degree of local customization is likely to be necessary no matter what.

**Comment by todolson** [comment]
Yes, I think you're on the right track with the name of the field type. Following the camel case convention of the `text*` fields types is probably the way to go. We only have one call number, but still. Something like `callnumberSearch` or `callnumberSearchable` seems reasonable and descriptive.

**Comment by demiankatz** [comment]
Done -- I went with "callnumberSearch" for brevity. Also added a comment on the fieldtype definition for good measure.

**Comment by demiankatz** [comment]
Manually merged.

**Pull request closed without merging**
