### PR TITLE
Pull requests accessib pagers

### PR DESCRIPTION
**Pull request by ckaz**
Following up on the other hardly accessible pagers here's my suggestion on the other pagers I could find (partly revising my earlier commit hiding &raquo;/&laquo;)
The translation for go_to has been added in Englisch and German too.

### CODE REVIEW

**Comment by demiankatz** [comment]
@ckaz, this PR seems to have some overlapping changes with #1586; is that intentional? Should we finish/merge #1586 first, then merge master back into this to reveal how this differs?

**Comment by ckaz** [comment]
@demiankatz Yes. There is some slight overlap. If we sort out the page_no translation in #1586 first, I could review/revise this one accordingly.

**Comment by crhallberg** [comment]
It looks like the page_no fix is in place on #1586. It also seems like there's a lot of style changes that might be better put into a different contribution.

**Comment by crhallberg** [comment]
What is the fate of this PR considering the improvements of #1586?

**Comment by demiankatz** [comment]
@crhallberg, I think there are some changes here that are not included in #1586, but I'm not sure exactly what they are. Perhaps @ckaz can shed some light, or else it might be useful to simply diff the branch for this PR against the branch for #1586 and see what appears.

**Comment by ckaz** [comment]
Apologies for the delay -- my son was ill.
There were a lot of indentation differences which you can please ignore. We have switched to a new indentation standard ...
Apart from that: the changes here affect the pagers that are not search pagination -- search pagination is dealt with in #1586 -- does that clarify the issue?

**Comment by crhallberg** [comment]
That does! I believe I've captured everything and found a good middle ground between the various paginator changes.

**Comment by demiankatz** [comment]
Thanks, @crhallberg; can/should we start closing some of these individual PRs? What's left to do before we can merge the unified one?

**Comment by crhallberg** [comment]
I think we were just waiting to make sure everything here was captured and @ckaz's comments here and on the 5.x consolidation make me think we succeeded. Closing now!

**Comment by demiankatz** [comment]
Addressed by #1609.

**Pull request closed without merging**
