### PR TITLE
ILLRequest default pick-up location not set correctly

### PR DESCRIPTION
**Pull request by cedelis**
This is related to ILL Requesting, which I think is only available in the VoyagerRestful driver:

When pickUpLibraryLocation is enabled in extraFields (VoyagerRestful.ini), the AJAX code in ill.js makes no effort to set the default pick-up location according the the homeLibrary setting. This is my attempt to resolve this.

I also notice that when/if pickUpLocation is enabled (which, by the way, is *not* listed as a valid option in the VoyagerRestful.ini's comments; is this legacy code that should get removed?), that the template makes reference to the variable named $this->pickup, which doesn't work in my case. By changing it to $this-> pickupLocations, the feature seems to work correctly.

I do see that a variable named $this->pickup is being used in other templates (myresearch/holds.phtml, myresearch/illrequests.phtml, myresearch/profile.phtml) and controllers (MyResearchController.php, StorageRetrievalRequestsTrait.php, HoldsTrait.php), but not in this particular scenario (record/illrequests.phtml and ILLRequestsTrait.php). Perhaps, it makes more sense to change the variable name in ILLRequestsTrait.php, instead, for consistency?

### CODE REVIEW

**Comment by EreMaijala** [comment]
There's a possible pitfall here: depending on configuration Voyager may allow pickup also from another library than the user's home library. For the other library the pickup location codes obviously don't match the home library's pickup location codes. This means that the home library setting should only be used if the pickup library is set to user's library card's library.

**Comment by cedelis** [comment]
Ere,

Our Voyager configuration is, in fact, set up to allow patrons the ability to select a pickup library different from their own. And you're right: when a patron does so, their default pickup location will never match. And the javascript code presented here will completely ignore the isDefault attribute returned from the Voyager Restful API (which, I assume, is the default pickup location setting in SysAdmin?). This will result in a pickup location control having no default selection. However, I've found that the isDefault setting happens to be the first one in the list, anyway. Perhaps this is just a coincidence. I'm not an expert in Voyager configuration. 

So, I suppose the best way to avoid this potential is to follow your suggestion, i.e., modify the javascript to only use the homeLibrary setting when the pickup library belongs to the patron's home institution. I can work on adding this capability, if you think it's worthwhile.

This particular issue brings up yet another issue: currently, there isn't a way for a patron to choose a default pickup library (at all) in the MyResearch/Profile page. It only allows for selecting a default pickup location from the patron's home institution. The ability to choose a default pickup location from a different library is a feature our patrons want since some of them live closer to a member library (than their home institution's library). Adding this new feature is on my to-do list.

**Comment by cedelis** [comment]
Ere,

How would I know what the "user's library card's library" is? Is this information available anywhere? As far as I know, 'home_library' is the only field we have available to us. Or am I missing something. 

If that's indeed the case, then perhaps I should first add the feature allowing patrons to choose a default library pickup in the Profile page. Then I could store both pickup library and pickup location using the single 'home_library' field (using '|' as a delimiter). Or is this a bad idea?

Chris

**Comment by EreMaijala** [comment]
Home library is always attached to the library card, so it could be derived from cat_username's prefix, but that's of course not a direct match with the pickup library. You'd have to do something like the following in AjaxController::getLibraryPickupLocationsAjax: 

    $wsConfig = $catalog->getConfig('WebServices', $patron);
    if (!empty($wsConfig['patronHomeUbId']) && $wsConfig['patronHomeUbId'] === $pickupLib) {
        $homeLibrary = $this->getUser()->home_library;
        foreach ($results as &$result) {
            $result['isDefault'] = $result['id'] === $homeLibrary;
        }
    }

I haven't tested that at all. 

I think I didn't add support for isDefault originally because we usually want the user to make a conscious choice (so many users just use the default values without checking), but it would make sense to have that as an option.

Making it possible to select a default pickup location per library is a bit more work since it depends on the ILL request target which libraries are available, and without an ILL target there's currently no method that would list all the libraries with their UB ID's. As far as I remember Voyager's API requires a record ID when retrieving possible pickup libraries, so it's not easy to list the libraries unless you're in the process of placing a request.

**Comment by demiankatz** [comment]
@cedelis, just checking on the status of this PR as it has been inactive for a few months. Please let me know if you need any assistance to move things forward!

**Comment by cedelis** [comment]
@demiankatz Thanks for reminding me about this issue. I was on vacation when Ere replied and I must've missed it!

@EreMaijala I tested out your AjaxController::getLibraryPickupLocationsAjax code above and it works great! It eliminates the need for any of my pull request changes (ill.js and illrequest.phtml) and it's much cleaner too. I would love it if you would be willing to commit that change (and ignoring my PR).  

<pre>
$ git diff module/VuFind/src/VuFind/Controller/AjaxController.php
diff --git a/module/VuFind/src/VuFind/Controller/AjaxController.php b/module/VuFind/src/VuFind/Controller/AjaxController.php
index cae11df..ae3158b 100644
--- a/module/VuFind/src/VuFind/Controller/AjaxController.php
+++ b/module/VuFind/src/VuFind/Controller/AjaxController.php
@@ -1286,6 +1286,15 @@ class AjaxController extends AbstractBase
                         );
                     }
                 }
+
+                $wsConfig = $catalog->getConfig('WebServices', $patron);
+                if (!empty($wsConfig['patronHomeUbId']) && $wsConfig['patronHomeUbId'] === $pickupLib) {
+                    $homeLibrary = $this->getUser()->home_library;
+                    foreach ($results as &$result) {
+                        $result['isDefault'] = $result['id'] === $homeLibrary;
+                    }
+                }
+
                 return $this->output(['locations' => $results], self::STATUS_OK);
             }
         } catch (\Exception $e) {
</pre>


There is still one outstanding issue that remains for us, however. Currently, the Pickup Library that is selected initially is the library that owns the item being requested. For our consortium, it is more natural to have the patron's home Library selected initially (since we offer interlibrary delivery). I was able to change this behavior by overriding the getILLPickupLibraries method with something like this:

<pre>
    // Set the default pickup library to that of the patron's library (not the item owning's library)
    public function getILLPickupLibraries($id, $patron)
    {
        $results = parent::getILLPickupLibraries($id, $patron);
        if ($results === false) {
            return false;
        }

        // determine logged-in patron's UbId
        list($source, $patronId) = explode('.', $patron['id'], 2);
        if (isset($this->config['ILLRequestSources'][$source])) {
            $pickupLibUbId = $this->config['ILLRequestSources'][$source];

            // clear out any default settings and set only the patron's UbId setting

            for ($i = 0; $i < count($results); ++$i) {
               if ($results[$i]['id'] == $pickupLibUbId) {
                   $results[$i]['isDefault'] = true;
               } else {
                   $results[$i]['isDefault'] = false;
               }
            }
        }

        return $results;
    }
</pre>

I realize that this is not directly related to this PR, but I was wondering if you thought this was a reasonable solution (or, perhaps, you might know of a more clever approach). Would this behavior be useful for other consortia?

**Comment by EreMaijala** [comment]
@cedelis The problem with my piece of code is that it's very Voyager-specific. I'll see if I can come up with a reasonable patch that does this in a more platform-agnostic way.

**Comment by demiankatz** [comment]
Thanks, @EreMaijala and @cedelis; let me know if you need any more input from me. I'll leave this PR open as a reminder until @EreMaijala has time to open a replacement. Regarding the second question (about changing default pickup location behavior), is this something that could/should be configuration-driven?

**Comment by cedelis** [comment]
@demiankatz I'm not the expert on this driver, but to me it seems like a configurable option could work and the logic could also be put into the AjaxController::getLibraryPickupLocationsAjax method (then I could remove my overridden getILLPickupLibraries method, which would be nice!). Not sure what to call it, but it could be a binary option: defaultPickLibrary = "item" or "home" or something to that effect.

**Comment by EreMaijala** [comment]
@demiankatz Apparently I haven't come up with a more generic solution even if I intended to. We usually force patrons to make the selection anyway, so that they're actually paying attention. I'd say that we could close this one and, if necessary, add a JIRA ticket.

**Comment by demiankatz** [comment]
Thanks, @EreMaijala. I'd be interested to hear where @cedelis is on this before closing, in case there's still an open issue we can resolve... but if he's happy as things are, we can certainly put this one to rest. :-)

**Comment by demiankatz** [comment]
I'm closing this one due to inactivity; feel free to reopen if there is a need.

**Pull request closed without merging**
