### PR TITLE
Alma: Encode all url's properly.

### PR DESCRIPTION
**Pull request by EreMaijala**
At least patron id can include characters, such as a question mark, that would otherwise break url parsing.

### CODE REVIEW

**Comment by EreMaijala** [comment]
Not sure what's up with CI, the error is unrelated.

**Comment by demiankatz** [comment]
There was an accidental commit to dev which broke the build; I've reverted it and merged the fix here, so I think all is well! Merging now.

**Comment by demiankatz** [comment]
I'd be interested to hear if @betullam has any feedback on this, but it seems uncontroversial enough to merge right away. :-)

**Comment by betullam** [comment]
@demiankatz That change is totally fine for me ... it works perfectly with our patron IDs that could also contain special characters

**Pull request merged**
