### PR TITLE
Clean up JSON responses.

### PR DESCRIPTION
**Pull request by EreMaijala**
Make all JSON responses into keyed arrays so that they can be e.g. extended without breaking compatibility. Get rid of the redundant status field in the responses in favor of HTTP status codes.

@demiankatz While I have only lightly tested the changes and there methods I can't test (e.g. Relais), I'd appreciate it if you could run the UI tests to see if anything breaks.

### CODE REVIEW

**Comment by EreMaijala** [comment]
Any other feedback is of course welcome too.

**Comment by demiankatz** [comment]
Thanks, @EreMaijala -- this looks like a great start, but as you say, it will require significant testing. I'll try to find some time for that next week, and we can also discuss this on the dev call to decide whether it should go into 5.0 (which I think it probably can, if we get the testing done quickly enough).

**Comment by demiankatz** [comment]
@EreMaijala, I've just run the automated test suite here, and everything is passing (apart from some tests that are currently broken due to ongoing work on fixing facet displays). Obviously not everything here is covered by the test suite, so I'll continue to do some manual review of this... but so far, so good!

**Comment by demiankatz** [comment]
I've just done some pretty thorough testing, and I think all is well. I only found a couple of small missed details, which I fixed in https://github.com/vufind-org/vufind/pull/1189/commits/b4b69d19208934f8eff39b675eea8b3ca5468fe6. Thanks again for taking the lead on this -- it's great to see this become a little bit less complicated!

**Pull request merged**
