### PR TITLE
KohaREST alternate driver

### PR DESCRIPTION
**Pull request by a-sassmannshausen**
Hi Demian, VuFind Team,

We've been working on a revised KohaREST ILS/Driver for VuFind for some of our customers. Not all expected features work yet, as they depend on enhancements to the Koha API that we're still in the process of developing, but we have tested quite a lot of the funtionality and by and large things seem fine.

I thought I'd share this with you already for early feedback — let me know if you spot any faux-pas or grievious errors!

Best wishes,

Alex

### CODE REVIEW

**Comment by demiankatz** [comment]
Alex,

It's been a few months since this PR was opened. I'm just checking in to see if any progress has been made. When you get a chance, please let me know whether or not you'd like to keep this open, merge it, or close it.

thanks,
Demian

**Comment by fredericd** [comment]
I'd be interested and available in testing this new driver.

**Comment by a-sassmannshausen** [comment]
Hi Demian, Frederic,

I'm afraid I've not been able to put in any more work since we last spoke on this subject, so it probably makes sense to close it for now and I'll re-open when I've implemented your recommendations.

There's a Koha Hackfest coming up, so perhaps that would be a nice time to work on this :-)

Frederic, thanks for your offer for testing. I'll keep you in mind for this and will let you know as soon as I re-open this.

Demian, feel free to close for now.

Cheers,

Alex

**Comment by demiankatz** [comment]
Thanks for the update, Alex. I'll close this for now, but feel free to reopen at any time! Let me know if I can do anything else to help.

**Pull request closed without merging**
