### PR TITLE
New permission provider user

### PR DESCRIPTION
**Pull request by mbeh-ub**
add a permission provider to grant permissions based on user attributes (columns in user table)

### CODE REVIEW

**Comment by demiankatz** [comment]
This looks like a useful addition to the toolkit, but before we merge it, it would be useful to get some comments about how it works included in permissions.ini and fix the one outstanding style issue (see the Travis report for details). It would also be nice to have unit test coverage, but I'm happy to help with that if you don't have time. Please let me know if I can do anything else to assist you in getting the finishing touches done here!

**Comment by mbeh-ub** [comment]
I fixed the style issue and updated the permissions.ini file (add description and example).
Test will (hopefully) follow soon...

**Comment by demiankatz** [comment]
Thanks! A couple more questions:

1.) When you explode the $attributeValuePair, did you consider using the ", 2" parameter on the end to limit the number of exploded elements? This way, if there are spaces within the regular expression, it won't break anything, and you only have to worry about addressing the case where the user omits the regex entirely.

2.) Did you consider allowing the user to provide the full regex pattern (including the outer '/' characters) in order to support alternate delimiters and/or regex modifiers? That might add a tiny bit more flexibility, though perhaps at the expense of some readability. (I have no strong opinion here -- just brainstorming).

Please let me know if I can be of any assistance with the test development.

**Comment by mbeh-ub** [comment]
I will mull over point 1 and give you feedback soon. 
Regarding point 2) I had put the slash-characters in permissions.ini too. After a look at the Shibboleth PermissionProvider, which also uses regexpresions I implemented it in the same way. No preferences at this point at all.

**Comment by demiankatz** [comment]
This looks good. I'll await your input on point 1.

Regarding point 2, I would probably have made the same suggestion for the Shibboleth PermissionProvider if I had been paying closer attention when it was implemented, though given that it now exists in this format, there is some value in consistency. I don't have a really strong opinion about this either; I'll leave it to your discretion.

Let me know when you've made a decision about point 1, and hopefully we can get this merged shortly thereafter.

**Comment by mbeh-ub** [comment]
I refactored getPermissions(...) accroding to your usefull hints (thanks!).
* the option string will now be splitted in two parts and an error is logged if the second part is empty.
* both version of regular expressions are now supported ( with and without surrounding slashes)

**Comment by demiankatz** [comment]
Looking great! I've merged this to master with a couple of minor adjustments -- mostly minor edits to make the code more concise. The biggest change had to do with the error handling -- I added a test to address the case where the regex is missing from the configuration, and this revealed a possible PHP warning which I restructured the code to avoid.

When you get a chance, please try out the latest version of the code, now available in master. Thanks again for sharing this!

**Comment by mbeh-ub** [comment]
Thanks for working on this and helping to improve the code !

**Pull request closed without merging**
