### PR TITLE
Favorites Terminology Update

### PR DESCRIPTION
**Pull request by crhallberg**
Add to List
My Lists
icon refresh

Line ending madness, apparently.

### CODE REVIEW

**Comment by demiankatz** [comment]
I see that we still have a "Your" in:

<pre>
Your Favorites = "Items in Your Lists"
</pre>

What about changing it to "Saved Items"?

**Comment by demiankatz** [comment]
One more observation: we previously had the strings "My Favorites" and "Your Favorites." Now we have changed "My Favorites" to "Favorites" and "Your Favorites" to "Saved Items."

From a search of the code, it appears that "My Favorites" is only used as the default name of the user's first list, if they fail to enter a custom name of their own. "Your Favorites" is used as a label in the interface for navigating to the favorites list.

Does it make sense to continue to call the default list "Favorites" or should we make that "Saved Items" as well for consistency?

It's also very tempting to rename the key "My Favorites" to "default_list_name" to make the language file less confusing. However, I think we should hold off on that until we can do a more comprehensive refactoring of language keys (in order to deal with backward compatibility problems all at once, rather than breaking people's localizations one key at a time). Still, it's very, very tempting in this case!

**Comment by crhallberg** [comment]
I agree with default_list_name. I think maybe "My List" would be better for a default name over "Favorites". "Saved Items" would make the side menu redundant.

**Comment by demiankatz** [comment]
Are you sure you want to go down the road of "My List," reintroducing "My"?

**Comment by crhallberg** [comment]
No you're right, let's leave it as Favorites for now.

**Pull request merged**
