### PR TITLE
justify-content for navbar-left in bs-compat.scss

### PR DESCRIPTION
**Pull request by ThoWagen**
Analogous to `navbar-right` this PR adds `justify-content` to the `navbar-left` class in bs3-compat.scss.

### CODE REVIEW

**Review by EreMaijala — APPROVED** [review]

**Comment by demiankatz** [comment]
@ThoWagen, should we rebase this onto release-10.1 for inclusion in the 10.0.1 release, or is it okay to wait until release 11.0? Since the bootstrap3 theme will be removed in the 11.0 release, perhaps it is worth backporting... but maybe it's useful for backward compatibility in 11.0 regardless of the status of the bootstrap3 theme.

**Comment by ThoWagen** [comment]
@demiankatz That makes sense! I rebased it.

**Comment by ThoWagen** [comment]
Sorry, I misunderstood how the rebasing works. Reverted that for now.

**Comment by demiankatz** [comment]
@ThoWagen, it should just be a matter of resetting to the release-10.1 branch, reapplying your SCSS change, and then running the build script. If you want me to do that, I'm happy to help!

**Comment by ThoWagen** [comment]
@demiankatz Thanks! The rebasing is done.

**Pull request merged**
