### PR TITLE
Koha RESTful driver

### PR DESCRIPTION
**Pull request by xmorave2**
Koha is making new RESTful API and we want to use it for creating new driver for VuFind.

This code is very bad and not functional yet, but I am publishing it to show we are working on it. So we would not duplicate work with anybody else... 

- [ ] Use \VuFind\Date\Converter for working with dates

- [ ] Better work with HTTP status codes

- [ ] Change parent from KohaILSDI driver to AbstractBase

- [ ] ... many more

There are only 3 endpoints in Koha available yet: Patrons, Cities and Holds, as you can see here in paths definitions:

https://github.com/Koha-Community/Koha/tree/master/api/v1/swagger/paths

If there are any willings to change the way how the VuFind is working with ILS drivers, this could be good opportunity to prototype and test it I think...

### CODE REVIEW

**Comment by EreMaijala** [comment]
Shoot, I'm late. I've been working with the Finnish Koha developers and I have an almost complete driver, but it's partially based on work in Koha that hasn't made it upstream yet. I'm not sure how to coordinate this. I can publish my driver version, but at the moment all the functionality won't work with a basic Koha installation.

**Comment by xmorave2** [comment]
Yes that's our problem to - too many things aren't in Koha upstream yet :( Do you have list of Koha bug numbers which is your driver depending on? If you can publish your driver, it would be very nice. I'd like to cooperate if it's possible.

**Comment by EreMaijala** [comment]
It's here: https://github.com/NatLibFi/NDL-VuFind2/blob/koha-rest/module/VuFind/src/VuFind/ILS/Driver/KohaRest.php

Unfortunately I don't have bug numbers. I've just worked with the Koha devs and giving them feedback on the APIs. The Koha test installation API I'm working with is at http://koha-suomi.fi:84/api/v1/doc/. It was just updated with new hold-related functionality, so I haven't had a chance yet to incorporate the changes into the driver.

**Comment by taskula** [comment]
Hello Josef! I think we have been e-mailing with your colleagues before. Glad to see you here as well! I set up a test server for Ere at http://koha-suomi.fi:84/api/v1/doc/ which mostly has the patches linked to your omnibus Bug from Koha's Bugzilla. Additionally we have OAI-PMH provider improvements, return data type changes and a new availability endpoint using modules that I am creating for Bug 17712. They are still lacking some documentation but I am planning to attach them into BZ before end of the year. You can read some of my thoughts about integrating availability into REST API in Bug 17712.

Here are the list of bug numbers on that server:
15108, 16330, 15165, 13895, 16497, 17712, 16826, 17004, 17371, 17006, 17003, 17005, 17008, 17479 and 17565.

Additionally, after Bug 17008 I have corrected data types from other endpoints. 

And finally, there is a commit that sets patron modifications for approval if patron edits their own info via opac-like access (without borrowers-permission). This code is dependent on 16330 and has no patches in Bugzilla because 16330 seems quite unclear at the moment.

I will we unavailable for January but back on Feb & March to work with you.

**Comment by demiankatz** [comment]
There hasn't been any activity here in a few months; just checking in to see if there is any new work that needs to be pushed here, or if there is anything I can do to support further progress here.

**Comment by EreMaijala** [comment]
We have completed our version of the KohaRest driver for VuFind (https://github.com/NatLibFi/NDL-VuFind2/blob/master/module/VuFind/src/VuFind/ILS/Driver/KohaRest.php), but it requires the API improvements for Koha developed in Finland, and I believe the Koha developers are working on getting them merged upstream (@taskula can probably give more insight on this process). The merging process will lead to some changes to be required, so I've been holding off suggesting anything to be merged upstream in VuFind yet. In any case the driver I've developed is now feature-complete and it's currently being tested with Koha by some libraries.

We have also some local extensions for handling contact information change requests and online payments (see https://github.com/NatLibFi/NDL-VuFind2/blob/master/module/Finna/src/Finna/ILS/Driver/KohaRest.php). At least the contact information change request could be considered to be included upstream at some point too, since we have a pretty flexible mechanism for changing phone number, email address and other contact information even for ILS's that don't have APIs for that, but the priority for me would be to get the basic functionality merged first.

**Comment by demiankatz** [comment]
@EreMaijala, thanks for the update, sounds great. I'll look forward to future developments!

**Comment by demiankatz** [comment]
@xmorave2, is there anything here that needs to be incorporated into #1016, or can we safely close this now that the newer PR is available? Thanks!

**Comment by xmorave2** [comment]
@demiankatz We could close this one. Thanks!

**Comment by demiankatz** [comment]
As discussed on #1016, closing this in favor of that newer PR.

**Pull request closed without merging**
