### PR TITLE
[VUFIND-1583] Add account menu to catalog login screens

### PR DESCRIPTION
**Pull request by demiankatz**
TODO
- [x] Run full test suite
- [x] Resolve [VUFIND-1583](https://openlibraryfoundation.atlassian.net/browse/VUFIND-1583) when merging

### CODE REVIEW

**Comment by demiankatz** [comment]
While reviewing open JIRA tickets, this one looked like low-hanging fruit. Not sure if there's a more elegant way to account for the lightbox, but this seems to be working appropriately both in and out of the lightbox, and all tests are passing, so hopefully it's good enough as-is!

I recommend reviewing the diffs with the `?w=1` flag on the URL so you can see more clearly what has actually changed (apart from indentation).

**Review by EreMaijala — CHANGES_REQUESTED** [review]
Looks otherwise good, but there's a problem when cataloglogin is embedded into another page:
kuva

**Comment by demiankatz** [comment]
Good catch, @EreMaijala -- the way that embedded login is coded, it slipped under my radar! I've fixed that particular instance. Can you think of any other similar cases elsewhere?

**Review by EreMaijala — CHANGES_REQUESTED** [review]
Everything seems to work now, but the page when you click "For hold and recall information, please establish your [Library Catalog Profile])." from holdings feels a bit weird since it now seems to move away from the holdings to "Your Account". I think we could live with it, but if fixing it is doable without too much effort, that'd make sense.

**Comment by EreMaijala** [comment]
I wonder if catalog login from holdings could open in lightbox. That'd eliminate the issue.

**Comment by demiankatz** [comment]
@EreMaijala, there's actually only a very narrow situation where the login doesn't open in a lightbox. If you're not logged in, it opens in a lightbox and goes through all the steps there. The lightbox is only omitted if you are already logged in but haven't set up a catalog profile yet. Since that issue seems somewhat independent of the work here, I opened #3469 to address it separately.

**Comment by demiankatz** [comment]
I've merged #3469 into this, so I think it's ready for another review.

**Review by EreMaijala — APPROVED** [review]

**Pull request merged**
