### PR TITLE
foundation5 theme for feature branch

### PR DESCRIPTION
**Pull request by lahmann**
Demian, this pull request includes the latest version of the foundation5 vufind2 theme and should be ready for moving into a feature branch.
Please let me know if there's anything more to do.

### CODE REVIEW

**Comment by crhallberg** [comment]
I think your theme is missing a LayoutClass file. I think you need to include the folder located at module\VuFind\src\VuFind\View\Helper\Foundation\.

**Comment by lahmann** [comment]
Thanks Chris! You are right, some files were missing - 685f3f9 should complete the foundation5 theme.

**Comment by crhallberg** [comment]
This is looking really good! I have one point of critique: the organization of the SCSS file.

I think it would be a lot easier to edit if we reorganized it a bit. The change that would make the biggest difference is to remove parent selectors. A powerful tool, but can lead to some confusion.

For example, `.sidebar & {` on line 72 (https://github.com/vufind-org/vufind/pull/429/files#diff-d72ce1731a88a6a61e27786e91c29550R72). This CSS rule would be easier to find and understand in the context of the .sidebar nesting block below (starting on line 134 [https://github.com/vufind-org/vufind/pull/429/files#diff-d72ce1731a88a6a61e27786e91c29550R134]).

**Comment by ckaz** [comment]
Dear Chris, I don't have the code in front of me as I'm on holiday 'till September. I guess I got carried away a bit by the newness (to me) of the whole SASS thing and carried along some now redundant code as well while working on the theme.
I'm very greatful for any further suggestions along those lines but I don't want to take too much of your time. You've done so much already. 
Cheers, Claas

Am 10. August 2015 20:55:39 MESZ, schrieb Chris Hallberg <notifications@github.com>:
>This is looking really good! I have one point of critique: the
>organization of the SCSS file.
>
>I think it would be a lot easier to edit if we reorganized it a bit.
>The change that would make the biggest difference is to remove parent
>selectors. A powerful tool, but can lead to some confusion.
>
>For example, `.sidebar & {` on line 72
>(https://github.com/vufind-org/vufind/pull/429/files#diff-d72ce1731a88a6a61e27786e91c29550R72).
>This CSS rule would be easier to find and understand in the context of
>the .sidebar nesting block below (starting on line 134
>[https://github.com/vufind-org/vufind/pull/429/files#diff-d72ce1731a88a6a61e27786e91c29550R134]).
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/vufind-org/vufind/pull/429#issuecomment-129564476

-- 
Vom Mobiltelefon gesendet.

**Comment by crhallberg** [comment]
Sorry to interrupt your holiday! I'll take a look at reorganizing if I have the time.

**Comment by demiankatz** [comment]
Hello again!

I spent some time today setting up a "feature and legacy branches" wiki page:

https://vufind.org/wiki/vufind2:git-branches

This seemed like a good time to move the Foundation5 theme into the main VuFind repo as a feature/foundation5 branch -- see https://github.com/vufind-org/vufind/tree/feature/foundation5.

I've sent out invitations to @ckaz and @lahmann so you can make commits directly to this feature branch.

I'll leave this PR open for now, but if you're happy with moving development to the main repo, we can go ahead and close this. Let me know what you think! (No rush, of course -- this can wait until André is back from leave).

**Comment by ckaz** [comment]
Hi Demian, 
Just back from holidays. I'll look into this over the next few days. Many thanks! Claas

**Comment by lahmann** [comment]
I just updated the `feature/foundation5` branch with our revision of the foundation5 theme. This is based on the commit 74d455d which is the code base we are currently working with. As soon as we updated our code base we will adjust the foundation5 theme to the changes made (apparently next time this will mean a big js-overhaul) and update the `feature/foundation5` branch accordingly.

So, I think this pull request can finally be closed.

Demian, Chris - thanks again for all your help!

**Comment by demiankatz** [comment]
Thanks for the updates. I've gone ahead and closed this.

**Pull request closed without merging**
