### PR TITLE
Fix markdown factory not getting config from markdown.ini

### PR DESCRIPTION
**Pull request by xmorave2**
I realize there is a mistake in getting config for markdown service in MarkdownFactory (definitely my fault, sorry).

I fixed the factory and added a regression test for it.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks for the fix!

**Comment by demiankatz** [comment]
Is it worth backporting this to the release-7.0 branch? I can try cherry-picking it when time permits if you think it's worth the effort.

**Comment by xmorave2** [comment]
I do think it's worth to cherry-pick into 7.0, the patch should apply without big conflicts I think....

**Comment by demiankatz** [comment]
Thanks, @xmorave2, I'll take care of it after the Summit. :-)

**Comment by demiankatz** [comment]
Thanks again, @xmorave2 -- I was able to cleanly cherry-pick this back to release-7.0.

**Pull request merged**
