### PR TITLE
Aleph driver: support for administration identifier (adm_id)

### PR DESCRIPTION
**Pull request by xrosecky**
We use administration identifier (adm_id) in our modified MultiBackend driver.

### CODE REVIEW

**Comment by demiankatz** [comment]
@xrosecky, can you say a little more about how this is used? It certainly won't hurt anything to add another field to the return values, but it might be worth adding a comment to explain why the field is there (in case someone maintaining the code in the future has a question), and if this is something that might apply to other ILSes as well, we should consider whether the field needs to be added to the ILS driver spec, and whether there are other drivers putting an equivalent value in a differently-named field.

**Comment by xmorave2** [comment]
@demiankatz, as far as I know, Aleph is (in some configurations) not able to report the bibliographic identifier. In these cases we use 'adm_id' to identify a record in solr index.

**Comment by demiankatz** [comment]
@xmorave2, if you're using `adm_id` in place of `id`, would it make more sense to just populate `id` with the `adm_id` value based on a configuration, rather than creating a whole separate field for it?

**Comment by xrosecky** [comment]
We need both identifiers.

**Comment by demiankatz** [comment]
@xrosecky, in that case, how about adding a comment above the new code, like:

`// Secondary, Aleph-specific identifier that may be useful for local customizations:`

That way, if we review code when revising the ILS driver spec in future, it will be clear that this is something Aleph-specific, and it won't cause any confusion. If that works for you, then I'm happy to merge this as-is. :-)

**Comment by xrosecky** [comment]
OK, I added the comment.

**Comment by demiankatz** [comment]
Thanks, merging now!

**Pull request merged**
