### PR TITLE
Update Virtua.php

### PR DESCRIPTION
**Pull request by jobdiogenes**
Add language support

### CODE REVIEW

**Comment by demiankatz** [comment]
This has been incorporated into #476. I added a separate support method to retrieve the language setting and default to 'en' if it is missing for backward compatibility. Please test this version when time permits. I'll merge it once I have confirmation from you.

One other thought: it might be useful to add an 'auto' setting that will populate the Virtua language setting using VuFind's own language setting. This would allow the ILS to adapt to match the rest of VuFind's interface. However, I'm not sure what would happen if you had a VuFind instance that supported languages that were unsupported by Virtua. Some kind of whitelist and default might make sense. If you think this would be a valuable feature, let me know and I can help you implement it.

**Comment by jobdiogenes** [comment]
Hello Demian,

I test using vufind/Install, and its OK. I also change the language in VuFind Interface, and still ok.
Now I need to figure how to extract records from Virtua. Do you know something about?

**Comment by demiankatz** [comment]
Thanks! I'll merge to master shortly. I'll answer your record extraction question in reply to your email on the mailing list.

**Comment by jobdiogenes** [comment]
Thanks Demian,

Great news.

Job Diogenes

2015-10-01 9:36 GMT-03:00 Demian Katz <notifications@github.com>:

**Pull request closed without merging**
