### PR TITLE
Revised Swedish translation by Åbo Akademi University Library.

### PR DESCRIPTION
**Pull request by tmikkonen**

### CODE REVIEW

**Comment by tmikkonen** [comment]
The Åbo Akademi University Library had a group of terminology people to revise the Swedish translations. The result is implemented as part of the The National Library of Finland's Finna project but should hopefully also benefit VuFind in general.

**Comment by demiankatz** [comment]
Thank you for this! Would you like to be informed of new language strings in future releases?

**Comment by tmikkonen** [comment]
Glad if it helps!
I'm more of a middle man here and unfortunately not so fluent with Swedish myself, so I think it would go to waste a bit. It might be best to let ÅA (or some another party) to revise again sometime later.

**Comment by demiankatz** [comment]
Sounds good to me. If you have a contact at ÅA that you think might be interested in receiving updates, feel free to send me an email with details (demian DOT katz AT villanova DOT edu).

**Comment by tmikkonen** [comment]
Not a direct contact no, but I'll be sure to pass this on.

**Comment by EreMaijala** [comment]
For the record, I wouldn't mind if they'd be willing to take care of the translations instead of me. :)

**Pull request merged**
