### PR TITLE
 Initial implementation for filters in search tabs using hidden filters

### PR DESCRIPTION
**Pull request by EreMaijala**
This is a proposal to support filters with search tabs using the pre-existing (but extended) hiddenFilters mechanism so that there can be multiple tabs for a single front-end (yeah, in the end we need this even more that the filters for combined results). The design goal here was to make the actual URLs not dependent on the tab config but instead to identify the active tab by the backend and the hidden filters in the URL. This keeps e.g. saved searches self-sufficient.

A large part of this PR is about moving the current hidden filters support from Solr and EDS to the base classes so they could be used for other backend too. Then there is the tab selection logic and code to convey the filter information between screen. Then the additional functionality for autocomplete and home page facets so that they apply the filters too.

What I'm not a huge fan of is the way the information of the previous search is retrieved. There are currently two mechanisms that provide this information e.g. on the record pages: the Memory object that contains the previous search URL, and the remembered options in Search\Base\Options. I wonder if it would make things easier to just keep a hash of the last id per search class and be able to fetch it from the database. But that could be part of another refactoring attempt.

Looking for feedback on this idea. Thanks!

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks for this! I think the code actually worked a little bit like this back in 1.x, and then the hidden filters got pushed into the backend in an effort to make the intermediate code lighter weight. I've never been entirely comfortable with that, though, because it creates side effects when using the backend in different ways, and as you say, it makes it harder to develop generic, shared mechanisms. So I think this is probably a step in the right general direction. Now some specific comments:

1.) On the subject of things I've never been entirely comfortable with, I've never really liked the fact that in places where we use hidden filters, we manipulate the Options object. The original conception of the Options object was that it should contain immutable configuration settings, and all mutable settings belong in the Params object. Off the top of my head, I can't remember exactly why hidden filters ended up there -- maybe there's a compelling reason -- but I mention this since you've been in the code recently and might have some thoughts. But I think a cleaner design might be to have a getDefaultHiddenFields() method in the Options, and then allow Params to collect additional dynamic ones. Obviously, we don't have to do this -- but if you agree that it would feel better and think it could be done, now might be a good time to do it, while we're refactoring this area anyway. (I suppose, at very least, we can't avoid having getLastHiddenFilters in the Options... but perhaps all of the memory stuff would be better refactored to a different class entirely... another project for another day).

2.) Speaking of getLastHiddenFilters, I agree that it's not beautiful, but I think it's good enough for now. If I'm reading/remembering correctly, the idea here is that while you're on a search screen, the hidden filters are persisted through GET parameters. Once you leave the search screen, your last set of filters will be remembered in a session object specific to the relevant backend, so your tab will remain selected on record views, etc. As you say, it might be more efficient to store this in the database rather than the session, but that can be dealt with later -- and might tie in with my idea above of refactoring all of the context memory to a separate class. (Anything to make Options/Params/Results lighter weight is a step in the right direction as far as I'm concerned).

3.) I notice that several implementation details rely on pulling hidden filters from a GET parameter. I have a feeling this won't work if you try to put filters on your default tab, since the GET parameter won't be filled in until the user clicks on something. Have you tested that scenario, or am I just not looking closely enough?

4.) Related: it looks to me like, based on SearchTabs::__invoke(), you'll run into problems if you have filtered and non-filtered versions of the same backend, and you put the filtered version before the unfiltered version in order -- then the unfiltered tab will never select. Not sure why you would want to do this, so maybe it doesn't matter much -- but if it's a relatively easy edge case to close up, we might as well. Perhaps we need to save the index of a "probable selected tab" in the ($first && empty($hiddenFilters)) case, then if we don't find a better match on our way through the loop, go back and replace that index with the createSelectedTab() version. Or maybe there's a less complicated solution!

5.) Do we need to add a hiddenFilter[] option to combined.ini so that the combined search filtering can cleanly interface with the filtered tabs, or am I again just missing a detail that already takes care of that?

Anyway, just some thoughts based on a first read-through; haven't tried to actually run this yet. I definitely think this looks promising, and hopefully none of these comments are too difficult to address. I'll be interested to hear your thoughts!

Thanks for taking the time to work on this!

**Comment by EreMaijala** [comment]
Just a quick note: I was already a bit hesitant with having the hidden filters in Options, so I think I'll revisit that. But nothing worth watching here until next week, time to take a break!

**Comment by demiankatz** [comment]
Enjoy the holidays!

**Comment by EreMaijala** [comment]
Note: please delete any searches made with the previous version from the search table in MySQL since the hidden filters are serialized in a different format.

1.) I moved hidden filters to Params including the memory thing since it's so simple there was no need to have it in Options. Of course it's now in two places, but I think it makes more sense this way.

2.) Yes, let's leave that for later.

3.) True, I didn't quite think it through. It's now refactored to pull the filters from the search tabs helper which tries to do the right thing, and from the memory if otherwise not available. The only downside of this approach is that I couldn't think of a better way than to make a list of pages where memory is not used so that going back to start page doesn't use it (see https://github.com/vufind-org/vufind/pull/545/files#diff-e835c9dc3da54720e6212b113ddb7401R20). Any better ideas would be valued!

4.) This should work properly now.

5.) True. I added support for hiddenFilter setting to the combined search.

**Comment by demiankatz** [comment]
Thanks for the progress. A few new comments/responses (numbering here not related to prior numbering).

1.) I try to avoid accessing view helpers from controllers when possible -- it's often a sign that code is not in the most appropriate place. I can live with it for now, but something we might want to keep in mind for future refactoring. (If nothing else, if the view helper contains no view-specific logic at all, it might make sense to make a new top-level service and then create a view helper that's simply a proxy around that service, as we've done with, for example, the cart).

2.) Would the code be more readable if the SearchTabs class had a method like `getHiddenFilters($searchClassId, $returnDefaultsIfEmpty = true)` so that you didn't have to do the empty checking and default retrieval in multiple places?

3.) Regarding the problem of identifying when to skip the memory for search home pages, I think the solution is fairly simple: every search home page, regardless of which backend it uses, should be running through a subclass of AbstractSearch. Right now, all of the subclasses define their own homeAction() methods, but it would be possible to define one in the base class which resets the hidden filter search memory, and then call parent::homeAction() from all of the subclasses. Alternatively, if you don't want to mess with all the controllers that would need to be edited for this approach, another option might be to take advantage of the fact that most (if not all) of the search home pages are actually proxying the search/home.phtml template. You could simply modify that template to pass a variable down to searchbox.phtml (like `['ignoreHiddenFilterMemory' => true]`) when including it, and I think that would be a lot more elegant, flexible and maintainable than the current "whitelist."

Let me know what you think about these things, and I'll take another closer look after your next round of edits. Thanks!

**Comment by EreMaijala** [comment]
1.) I moved the new methods to their own helper class but decided to leave the previously existing stuff in the SearchTabs view helper there since it requires the Url helper.

2.) True, done.

3.) Thanks, done! That's so elegant and simple :) I also switched the render() calls for searchbox to renderInContext() so that searchbox.phtml still has access to full context like before.

**Comment by demiankatz** [comment]
Great, thanks! Some new comments:

1.) To reduce constructor complexity and duplicate factory logic, would it make sense to revise the SearchTabs view helper so that it pulls configuration and filters out of the helper instead of having its own local copies?

2.) It's probably worth writing a test for the new helper class, since this would be easy to do, and I'm always a fan of bumping up the test coverage when it's simple to do. If you don't have time/inclination, let me know and I'll take care of it as part of my review process.

**Comment by EreMaijala** [comment]
1.) Done. Thanks, much nicer this way. :)
2.) Done. Hopefully I managed to do it in a viable way with all the mocks etc.

**Comment by demiankatz** [comment]
Thanks! Found and fixed a bug that broke hierarchical collections, but other than that, looking pretty good. I'm going to give this another look either tomorrow or next week when my brain's a bit fresher -- been merging too many complicated PRs for one day!

**Comment by demiankatz** [comment]
Looking good. Autocomplete wasn't working for me on this branch, but that was apparently due to a bug in the autocomplete handler rather than this code. I fixed that problem in master, then merged in the rest of this. Thanks again!

**Comment by EreMaijala** [comment]
Thanks! Uh, the autocomplete fix totally breaks it for us. It's now displayed in the upper left corner of the viewport. Please be careful with the autocomplete code, I'm afraid this will be #533 all over again. I think there should be a way to keep it in the form without overflow:hidden causing trouble, but I can't reproduce the issue (custom theme?).

**Comment by demiankatz** [comment]
I ran into the problem with a completely raw checkout of master -- in order to avoid contamination of custom themes, etc., I try to spin up a fresh checkout of VuFind when reviewing pull requests for merging. So in this case, I checked out your branch, set up three tabs (all Solr, Solr filtered to exclude journals, Solr filtered to display ONLY journals), and everything worked except that autocomplete was totally non-visible.

I'll talk to @crhallberg about this further when he gets in. This is frustratingly fragile.

**Comment by EreMaijala** [comment]
Ah, it seems specific to bootprint3. I used bootstrap3 in testing. It seems the autocomplete results attach to wrong form, the hidden one. I'll see if I can make it work and post a new PR.

**Comment by EreMaijala** [comment]
I opened PR #555 for further work.

**Pull request closed without merging**
