### PR TITLE
Make it possible to disable CSP header generation.

### PR DESCRIPTION
**Pull request by EreMaijala**
Also tweak comments a bit.

### CODE REVIEW

**Comment by demiankatz** [comment]
@xmorave2, this looks reasonable to me; do you have any objections? While I definitely think we should strongly encourage use of CSP, being able to turn it off may be valuable, at least during the initial transition period after introducing the feature.

**Comment by xmorave2** [comment]
@EreMaijala, @demiankatz: I have no objections to have this ability. Just little note: I would make default for development mode report_only too. Otherwise the Whoops page will not work - there is CSS generated as inline in vendor library.

**Comment by EreMaijala** [comment]
@xmorave2 Oops, thanks. That's indeed how it should have been. Now fixed.

**Review by xmorave2 — APPROVED** [review]

**Comment by demiankatz** [comment]
Thanks; merging now!

(The latest failed Travis build appears to be a Travis-specific problem, not related to the code changes here, so I'm going ahead with the merge).

**Pull request merged**
