### PR TITLE
No CAPTCHA reCAPTCHA

### PR DESCRIPTION
**Pull request by crhallberg**
reCAPTCHA has been updated to sheer magic (demo: http://www.google.com/recaptcha/api2/demo) so I updated the CAPTCHA library.

Zend Frameworks has not updated yet, and shows no sign of it, although the new format is vastly different. Thusly, I moved all the logic to VuFind/Service/Recaptcha and removed the deprecated zendservice-recaptcha from vendor.

### CODE REVIEW

**Comment by demiankatz** [comment]
Chris,

Did you see this issue on the Zend Library?

https://github.com/zendframework/ZendService_ReCaptcha/issues/6

Might be worth putting in your two cents on that ticket if you have an opinion... and/or getting in touch with that developer to see if the new code is useful.

Thanks!

**Comment by crhallberg** [comment]
I don't have any particular feedback, I think they've replaced this code. I
could submit a PR, but this version is different from the reCAPTCHA in Zend
Framework itself:

https://github.com/zendframework/ZendService_ReCaptcha/tree/master/library/ZendService/ReCaptcha
vs.
https://github.com/zendframework/zf2/tree/8b644e8b0e8cd931bf25cf3babc3ffa047df26d5/library/Zend/Captcha

- Chris

**Comment by demiankatz** [comment]
This is definitely confusing. I'm not sure how ZendService\ReCaptcha and Zend\Captcha relate to one another (if at all). The purpose of the ZendService namespace was to create separate repos for managing special-purpose Zend Components in order to prevent the core framework from becoming too bloated or filled with pieces that could break due to changes in third-party APIs. This would lead me to think that perhaps ZendService\ReCaptcha is the more up-to-date component... but then again, maybe Zend\Captcha is still in core to provide hooks into the Zend\Form stuff that we don't use... and maybe the two are somehow linked together.

**Comment by crhallberg** [comment]
Zend\Captcha was updated in November. ZendService\ReCaptcha hasn't been
updated since Dec 5, 2012.



On Mon, Jan 12, 2015 at 3:17 PM, Demian Katz <notifications@github.com>
wrote:
>
> This is definitely confusing. I'm not sure how ZendService\ReCaptcha and
Zend\Captcha relate to one another (if at all). The purpose of the
ZendService namespace was to create separate repos for managing
special-purpose Zend Components in order to prevent the core framework from
becoming too bloated or filled with pieces that could break due to changes
in third-party APIs. This would lead me to think that perhaps
ZendService\ReCaptcha is the more up-to-date component... but then again,
maybe Zend\Captcha is still in core to provide hooks into the Zend\Form
stuff that we don't use... and maybe the two are somehow linked together.

**Comment by demiankatz** [comment]
The two components are related: if you look at Zend\Captcha\ReCaptcha, you'll see that it's a wrapper around \ZendService\ReCaptcha. I think the Zend\Captcha stuff is just the glue that binds the stand-alone service class with the Zend Form components.

**Comment by crhallberg** [comment]
Wouldn't it be part of \ZendService\ReCaptcha then if it's really modular?

**Comment by demiankatz** [comment]
It's definitely weird that the core framework has dependencies on things outside of the core framework. But I'm just calling it as I see it! The point is that the main ReCaptcha logic seems to be defined by the ZendService\ReCaptcha library, which is where the issue I mentioned lives.

**Comment by Lansoweb** [comment]
@crhallberg Hi! As @demiankatz said, the two are related, so to correctly use the new captcha from google, the change is needed on both. I have the changes ready for a PR on both (ZendService and ZF2), but needed some insights. Didn't get any thoughts in almost a month, specially from the maintainers, so i'll fill two PRs in the next days. I use one in 2 projects.

**Comment by crhallberg** [comment]
Still waiting on updates to Zend for the new captcha API. I may be bad at looking, but I've found no indication that progress has been made yet.

**Comment by demiankatz** [comment]
No, I haven't seen any changes either; I just added a comment to the issue report on the ZendService repo in case there's anything we can do to help things along.

**Comment by crhallberg** [comment]
I put a PR on the other Recaptcha branch to get non-JS support: https://github.com/Lansoweb/LosReCaptcha/pull/2.

After that I have a branch that will put the functionality from that implementation into VuFind.

**Comment by demiankatz** [comment]
Thanks for the update!

**Pull request closed without merging**
