### PR TITLE
Remove mobile top margin from media-body

### PR DESCRIPTION
**Pull request by maccabeelevine**
This just removes some margin-top above `.media-body` appears only on mobile widths.  I think it may have been a mistake, as it prevents the alignment of thumbnail and title, and there is nothing else specific about the mobile layout that seems to require the extra spacing there.

image

Given the comment [back when it was added](https://github.com/vufind-org/vufind/commit/76bdeb0b721a038190f317e281d6879c07697ef4), maybe it was meant to be margin-left instead, although I don't think that is needed either.

> // Add a gap between the thumbnail and the info

### CODE REVIEW

**Comment by maccabeelevine** [comment]
@crhallberg it's certainly possible I am misunderstanding the original intent here.  Just came across this oddity as I was making related changes (#3626).

**Comment by crhallberg** [comment]
I'm assuming this doesn't have any affect on desktop widths?

**Comment by demiankatz** [comment]
> I'm assuming this doesn't have any affect on desktop widths?

Given that the change is constrained by a media query, I wouldn't expect it to.

**Review by crhallberg — APPROVED** [review]

**Comment by demiankatz** [comment]
Now that @crhallberg has approved this (thanks, Chris!), I think @sturkel89 can take a look to confirm expected behavior in the various themes. This change should improve alignment of thumbnails with adjacent text, a pattern which can be seen in a few different places:

  * Record pages
  * Search results
  * Favorite lists
  * Account-level record lists (e.g. holds, checked out items, etc.)

It's probably worth inspecting all of these to be sure they line up right in mobile and desktop views. In at least some cases, they should look wrong in dev and correct in this branch.

**Review by sturkel89 — APPROVED** [review]
I reviewed the test branch vs. dev in all three themes, and compared both desktop and mobile views. Here are my observations:

### **Record pages**
In all three themes, in test, the thumbnail is aligned nicely with the top of the adjacent title text on widescreen and mobile. 

In dev, the thumbnail is too high on mobile.

### **Search results, Favorites Lists, Checked out items**
Alignment is good in both test and dev, in all three themes, on desktop and mobile.

---------
I think everything is working as expected, and the PR is ready to merge.

**Comment by demiankatz** [comment]
Thanks, everyone!

**Pull request merged**
