### PR TITLE
Update jstree component

### PR DESCRIPTION
**Pull request by LuomaJuha**
Accessibility improvements and littlebit more up to date.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @LuomaJuha! I'll run the full test suite and try a few things before merging this (hopefully next week, if not sooner).

**Comment by demiankatz** [comment]
@LuomaJuha, I ran automated tests today, and encountered this failure:

<pre>
There was 1 failure:

1) VuFindTest\Mink\SearchFacetsTest::testHierarchicalFacets
Selector not found: #j1_1.jstree-open .jstree-icon
Failed asserting that false is true.

/home/dkatz/vufind/module/VuFind/src/VuFindTest/Unit/MinkTestCase.php:248
/home/dkatz/vufind/module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchFacetsTest.php:322
/home/dkatz/vufind/module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchFacetsTest.php:352
/home/dkatz/vufind/module/VuFind/src/VuFindTest/Unit/AutoRetryTrait.php:98
</pre>

Specifically, this is where the test is failing:

https://github.com/vufind-org/vufind/blob/dev/module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchFacetsTest.php#L322

I'm guessing this means that the new version of JSTree has changed the way it names nodes, causing the test's selector to fail. Do you have any thoughts on how to fix this? If not, let me know and I can delve in more deeply when I have a bit more time.

**Comment by LuomaJuha** [comment]
@demiankatz Seems like so, I can take a closer look today at some point to find out the new way of naming the nodes. Would the best way to be update the tests to match that version of jstree?

**Comment by demiankatz** [comment]
@LuomaJuha, if it's just a case of naming conventions changing without any functional changes, then simply adjusting the selectors in the test should be enough... but if the changes are more significant, it might be more work. If you can easily figure out the new names, I'm happy to run the tests again on this end (or I can guide you through the process of setting up the test environment, if that would be helpful to you for the future).

**Comment by LuomaJuha** [comment]
@demiankatz After checking the difference in this pull request, seems like the selector is fine. However https://github.com/vufind-org/vufind/blob/12ad75ed0c18937ff6963ffa9ff88a4036db19d5/module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchFacetsTest.php#L321 seems to work differently, as that part reloads the page in this newer version. That seems to be the reason why it can not find the selector anymore.

**Comment by demiankatz** [comment]
Thanks, @LuomaJuha! I'm not sure why the test was written that way (perhaps it was a workaround for a problem in the earlier version), but if I rewrite it to use a more standard method of clicking on the tree, it works correctly and passes.

I have opened a pull request (https://github.com/LuomaJuha/NDL-VuFind2/pull/1) to fix the test in this branch, since I don't seem to have write access to your repository. Could you please merge my PR into this branch, and then I can merge the whole thing into dev?

Thanks again!

**Comment by LuomaJuha** [comment]
@demiankatz should be merged now!

**Comment by demiankatz** [comment]
Thanks!

**Pull request merged**
