### PR TITLE
Add their own translation keys for account notification tooltips.

### PR DESCRIPTION
**Pull request by EreMaijala**
TODO
- [x] Run full test suite

### CODE REVIEW

**Comment by EreMaijala** [comment]
An alternative for this would be to change the tooltip to indicate that the number includes only checked out items that don't require action. Currently it seems quite misleading.

**Comment by EreMaijala** [comment]
I'm going to change this a bit...

**Comment by EreMaijala** [comment]
Ok, here's the final proposal: use separate translation strings for the account notifications. The reuse of translations used in others contexts proved problematic for proper translation. This also makes it possible to use more generic translations that apply to all request types.

**Comment by crhallberg** [comment]
This looks good! I'm running the full test suite now. I'll approve when it passes!

**Review by crhallberg — APPROVED** [review]

**Pull request merged**
