### PR TITLE
RecordDriver for swapping the SolrMarc-fullrecord to external service

### PR DESCRIPTION
**Pull request by lahmann**
Referring to our discussion in http://sourceforge.net/p/vufind/mailman/message/33269958/ I am happy to open the pull request on this feature today.
As discussed on the mailinglist we have been struggling with a huge index for quite a while and mitigated it by moving the index's MARC-fullrecord field to a dedicated binary-server reducing the index by ~25%. The included RecordDriver allows to pull the MARC-fullrecord if needed (already using lazyMarcRecord) from another http-service. All that's necessary is to set up the service providing the MARC-fullrecord-files and configure this service in the RecordDriver's SolrMarcRemote.ini.

We have prepared documentation on setting up such a service and would like to add it to the vufind.org wiki - I thought about including it in https://vufind.org/wiki/performance or referencing it in https://vufind.org/wiki/performance#index_optimization would be a good idea.

### CODE REVIEW

**Comment by demiankatz** [comment]
André,

Thanks for this! A few comments that might help further reduce the footprint of this change:

1.) You should be able to safely omit the new record tab configuration in module.config.php -- tab configuration is inherited based on class hierarchy, so this class should automatically get the existing VuFind\RecordDriver\SolrMarc configuration without the need for redundant configuration entries (unless the SolrMarcRemote configuration needs to be different in some way I'm not noticing).

2.) Your class inherits the lazyMarcRecord and mainConfig properties from its parents, so those property definitions do not need to be repeated.

3.) The searchesConfig property does not appear to be needed at all. Passing the constructor parameter up to the parent should be sufficient.

4.) You could eliminate some redundant logic (and ensure totally consistent data structures) by changing some of the logic in your getMarcRecord() method to something like this:

<pre>
    public function getMarcRecord()
    {
        if (null === $this->lazyMarcRecord) {
            // handle availability of fullrecord
            if (!isset($this->fields['fullrecord'])) {
                if (!isset($this->fields['id'])) {
                    throw new \Exception(
                        'No unique id given for fullrecord retrieval'
                    );
                }

                $this->fields['fullrecord'] = $this->getRemoteFullrecord($this->fields['id']);
				return parent::getMarcRecord();
            }
        }

        return $this->lazyMarcRecord;
    }
</pre>

This way you just populate the missing 'fullrecord' field and fall back to the original logic -- probably easier to maintain in the long run. The parent method will take care of throwing an exception if the fullrecord field is bad or missing, but you could always add some more specific exception handling to this method if you felt it was important to differentiate between different types of errors.

Regarding the wiki, I think it makes sense to include a documentation link on the performance page. If you'd like me to create a blank page for this, let me know your preferred page name (perhaps http://vufind.org/wiki/remote_marc_records?), and I'll set it up so that you can edit it.

**Comment by lahmann** [comment]
Demian, thanks a lot for your comments - you were absolutely right and I've edited the code accordingly (I didn't know that the module.config.php settings are being inherited by subclasses as well... good to know).

Regarding the wiki, your proposal for the page name is fine. After creating the page I will also add the link to the SolrMarcRemote-header for reference.

Apropos, I just tried to log into the wiki, but apparently my user-account (`andre_l`) got deleted during your cleaning action some weeks ago :) - is there any chance to restore it? Or should I create a new user-account?

**Comment by demiankatz** [comment]
André,

I have created the blank wiki page and (hopefully) restored your old wiki account.

Two more thoughts before I merge this:

1.) How would you feel about moving the configuration from its own .ini file into a remote_marc_url setting in the [Record] section of config.ini? This would make the setting more visible and also reduce the amount of configuration loading needed to build the objects. If you prefer to keep things as-is, that's okay with me, but this alternative occurred to me this morning.

2.) If you want to create the wiki page/links prior to merging the PR, that's fine with me, since you could then edit config comments to include a link to the wiki. Just add a note that this feature requires VuFind 2.5 or higher.

Once I hear back from you about these points, I'll go ahead and merge. Thanks again for sharing this!

**Comment by lahmann** [comment]
Demian, my old wiki account works fine - thanks! I have added the page, I hope that it's a useful guide.

1) actually we had this setting in config.ini first, but I thought it would be more reasonable (and in your favor :) ) to keep as much stuff out of config.ini but put those special RecordDriver-inis in seperate files. I certainly don't mind adding it back to config.ini and have done so in the latest commit.

2) I hope this is fine: https://vufind.org/wiki/remote_marc_records

If you are ok with the commits and Travis is not complaining, this should be ready to be merged.

**Comment by demiankatz** [comment]
Looks great! I've merged this to master and updated the wiki page to reflect the new location of the configuration in config.ini.

Just one remaining question about the wiki: in order to disable the fullrecord field, you can't just put a commented-out version of the line in marc_local.properties, since you'll then still inherit the full version from marc.properties. I think you might be able to set the value to "" instead. Have you tried that?

**Comment by lahmann** [comment]
Demian, I've checked whether setting `fullrecord = ""` is sufficient and it does disable filling the fullrecord field - thanks for catching this one! I've also updated the introduction of the wiki-page to the new config.ini setting, so the wiki page should be final now.
Thanks again for all your help!

**Comment by demiankatz** [comment]
Wonderful! Thanks again for your help.

**Pull request closed without merging**
