### PR TITLE
Alma: use false and dueStatus instead of null to fix account ajax not…

### PR DESCRIPTION
**Pull request by EreMaijala**
…ifications.

I don't quite understand the logic in GetUserTransactions, but this will fix the display for number of normal loans.

### CODE REVIEW

**Comment by demiankatz** [comment]
I'm copying @betullam in case he has comments on this change, or getMyTransactions in general. I'm a little curious about why this is necessary, given that dueStatus is an optional field according to the [driver spec](https://vufind.org/wiki/development:plugins:ils_drivers#getmytransactions) and there is no specification of what a value of "false" would mean. I wonder if this means that the account AJAX code is making some incorrect assumptions and needs to be adjusted, rather than changing the driver. Let me know if you need me to dig deeper into that.

**Comment by EreMaijala** [comment]
I based this on the fact that other drivers return false.

**Comment by demiankatz** [comment]
@EreMaijala, it's also possible that we need to update the spec to match reality. When I have a little more time, I'll do a survey of all the drivers and see if I can make any sense of what's going on.

**Comment by EreMaijala** [comment]
I think it makes sense to keep it optional just in case a driver cannot support it. And probably the check in https://github.com/vufind-org/vufind/blob/master/module/VuFind/src/VuFind/AjaxHandler/GetUserTransactions.php#L67 too, since it's useful to avoid trying to display information for a driver that can't supply it.

**Comment by demiankatz** [comment]
@EreMaijala, I definitely wasn't suggesting we should make the field non-optional... I just think if there's a meaningful difference between leaving it unset and setting it to false, we should define what that difference is, since currently the documentation does not make that clear.... and if the false/unset scenarios should be the same (I'm not sure why they wouldn't be), we should make sure the code behaves consistently.

Personally, I think the bug is actually in the GetUserTransactions handler; rather than failing to count items with no dueStatus set, it should just default to assuming those are ok, just as if they were set to false. The purpose of the ok/warn/overdue counts is to tell the user how many books they have checked out, and to flag potential problems. If we don't have enough data to identify the problems, that doesn't mean we shouldn't count the transactions as existing at all.

**Comment by EreMaijala** [comment]
@demiankatz Right. In that case changing GetUserTransactions would make sense. That was my initial thought too, but then I thought it just tries to be smarter.

**Comment by EreMaijala** [comment]
It seems that also an empty string can be returned as dueStatus by Unicorn driver.

**Comment by demiankatz** [comment]
So should we revert this change to the Alma driver, adjust the AJAX handler, and add a note to the spec saying that false, empty string and null should be treated equivalently by VuFind?

**Comment by EreMaijala** [comment]
Works for me. I'll post a new PR.

**Pull request closed without merging**
