### PR TITLE
Sandal: Fix wonky focus highlight in the search field.

### PR DESCRIPTION
**Pull request by EreMaijala**
This fixes the focus highlight issue @sturkel89 mentioned in #3482.

### CODE REVIEW

**Review by sturkel89 — COMMENTED** [review]
Wonkiness is gone!! The outline now has equal thickness all the way around. The mission of this PR has been accomplished. :-)

Now, I have a little aesthetic opinion/observation that you are free to disregard. The search box and dropdown on front page have slightly different styling than on the results page: the elements on the front page have a thin darker outline between the orange outline and the white of the search box, and also there's a small buffer of space between the search box and the dropdown. See below -- all screenshots are from the test branch.

I prefer the front page appearance to that of the results page. If you could add those few pixels to the results page, I think that would be an aesthetic improvement (and would provide consistency). Your call!

Front page:
image

image

Results page:
image

image

**Comment by demiankatz** [comment]
Thanks, @sturkel89. I agree that having the consistent spacing between the controls would be nice. @EreMaijala, would you like to address that here, or should I merge this now and we address that separately?

**Comment by EreMaijala** [comment]
@sturkel89 @demiankatz Should be fixed now.

**Review by sturkel89 — APPROVED** [review]
I took a look - everything looks great! No need to provide screenshots as the search box and its spacing, highlighting, and the tiny dark outline inside the orange outline are all identical between front page, results pages, and user account pages.

Ready to merge!

**Pull request merged**
