### PR TITLE
Fix widget type handling in LibGuides query builder

### PR DESCRIPTION
**Pull request by EreMaijala**
Continued from #3590.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @EreMaijala -- this makes sense to me, but I'll defer to @maccabeelevine in case there's something we're both missing. :-)

**Comment by maccabeelevine** [comment]
> Thanks, @EreMaijala -- this makes sense to me, but I'll defer to @maccabeelevine in case there's something we're both missing. :-)

Yup, it looks fine to me but I'm doing some testing to be sure

**Review by maccabeelevine — APPROVED** [review]
LGTM!

**Review by demiankatz — APPROVED** [review]
Thank you both!

**Pull request merged**
