### PR TITLE
Authorization

### PR DESCRIPTION
**Pull request by demiankatz**
This PR integrates ZfcRbac into VuFind for authorization support. Note that this raises the base PHP version requirement to 5.4.

### CODE REVIEW

**Comment by jochen-lienhard** [comment]
I will refactor the Shibboleth-Auth module and sepearte authentification and authorization. Creating a new auth file is the best way. I will call it: Shibboleth2. Is this OK for you?

**Comment by demiankatz** [comment]
I'm not sure if Shibboleth2 is the best name (generally I like to avoid numbers like this in names, because it doesn't convey significant meaning), but please feel free to start building it as Shibboleth2, and we can revisit the naming once it's working.

**Comment by jochen-lienhard** [comment]
I agree, Shibboleth2 would be enough for the beginning. Our plan is to use REMOTE_USER for the username to login and to define a rule for the permission use_favorites. I hope to get a first version next week.

**Comment by demiankatz** [comment]
Very good! I'm hoping that in a few more weeks I will be able to merge the authorization functionality back to master, so it will then be more convenient for you to open a new pull request with the expanded Shibboleth... though, of course, if you have something to share before I have accomplished that, you can feel free to open a PR against this branch.

**Comment by jochen-lienhard** [comment]
I added a base Shibboleth2.php. userattributes(values) are not necessary any more, this information should be put in permissions.ini. Only users that have a REMOTE_USER (see configuration of shibboleth) will be logged in. Still not implemented is the check if the user was identified from the correct identity provider(s) (it can be more than one).

**Comment by demiankatz** [comment]
Jochen,

I have merged most of the authorization logic to master today, but I have left the Shibboleth2-specific parts behind in this PR for further discussion. It seems to me that this implementation is incomplete, since the example configurations depend on a Shibboleth PermissionProvider that does not yet appear to exist in this branch.

We should also give some thought to a better descriptive name for the new service than "Shibboleth2."

For the sake of simplicity, I think we should close this PR and open a new separate one for the Shibboleth logic until we get that sorted out... but I will leave this alone until I hear back from you in case there are any obstacles to doing that.

thanks,
Demian

**Comment by jochen-lienhard** [comment]
Our goal would be to replace the current shibboleth driver by the new one.
Shall we open a new pull request, for example shibboleth, to create the new authentication and authorization?

**Comment by demiankatz** [comment]
Yes, I think it would probably be easier to keep track of everything if you close this pull request and open a new one just for Shibboleth. Thanks!

**Comment by jochen-lienhard** [comment]
can be closed, for more about shibboleth look at PR 308

**Comment by demiankatz** [comment]
Thanks!

**Pull request closed without merging**
