### PR TITLE
Keep author fields even if no role is given

### PR DESCRIPTION
**Pull request by dersmon**
The API currently deletes author names (which are actual array keys here) if there is no role given (the only true value in the authors' array object).

### CODE REVIEW

**Comment by demiankatz** [comment]
@dersmon, thanks for this. A few thoughts:

1.) I'd be interested to hear @EreMaijala's thoughts on this problem, but unfortunately he is currently on holiday for a few weeks. If this is urgent, we can certainly try to resolve it before he returns.

2.) I have some concerns about hard-coding 'authors' in a low-level class. I would prefer to solve this problem in a more generic way, though I'm not sure what the best approach is. (For example, perhaps we should never filter a value if it's an empty string with a non-numeric key... but preliminary attempts to code that behavior didn't work for me).

3.) We should add a test case to cover this scenario, regardless of which implementation we choose. I have added a test case as an example. However, this test is currently failing; I'm not entirely sure whether this indicates a problem with the solution you propose or a problem with the way I set up the test. Either way, we should figure out a way to make this pass before we merge this.

Please let me know what you think, and thanks again for working on a solution to this issue!

**Comment by dersmon** [comment]
Probably there are other fields besides authors, where values are encoded as array keys.

**Comment by demiankatz** [comment]
@dersmon, thanks for fixing the test case. I've come up with an alternate implementation that makes the test pass without requiring the hard-coded 'authors' value: if a value is an empty array but the key is non-numeric, the empty array will now be retained. That should fix the author situation, though I'm not entirely sure whether there will be side effects elsewhere. It might be a good idea to wait for @EreMaijala to comment before merging this. However, in the meantime, if you could test if this approach solves your problem, that would be good to know!

**Comment by dersmon** [comment]
@demiankatz, your fix also works for our case. Thanks! Let's see what @EreMaijala has to say... ;)

**Comment by EreMaijala** [comment]
Now that I think of it, it would have been better to avoid this sort of associative arrays in the API. My bad, and there's not much that can be done now, but if I were to redesign it, the structure should have been something like this:

```
[
  'primary' => [
    [
      'name' => 'Ms. A',
      'role' => 'Editor'
    ],
  ],
  'secondary' => [
    [
      'name' => 'Mr. B',
      'role' => ''
    ],
    [
      'name' => 'Mr. C',
      'role' => ''
    ]
  ]
]
```

**Comment by demiankatz** [comment]
Thanks, @EreMaijala, I've merged this to master. We can consider the design issue if we ever work on a 2.0 API version.

**Pull request merged**
