### PR TITLE
Improve OAI deletes behavior.

### PR DESCRIPTION
**Pull request by demiankatz**
TODO
- [x] Add setting to limit lifetime of OAI deletes
- [x] Create command line utility for cleaning out old deletes from the change_tracker table (or open a JIRA ticket to track this work for future reference)

### CODE REVIEW

**Comment by demiankatz** [comment]
@EreMaijala, I'm interested in your thoughts on this one. My production VuFind database contains more than 400,000 deleted records... and so if somebody tries to do an OAI-PMH harvest, the results are extremely unwieldy... It takes hours just to get all the deleted records, and it appears that my database server can't survive that ordeal. It occurs to me that it really doesn't make any sense to output deleted record data on a full harvest, so I'm proposing the changes here as a workaround... but I'm not sure if there's a "gotcha" I'm not thinking of, or if this is a blatant violation of spec. Any thoughts?

**Comment by EreMaijala** [comment]
@demiankatz I think it violates the spec if you output them in one case but not in another. And a harvester might just take the earliestDatestamp from an Identify response and use it as the from parameter. We can't really determine what the harvester already has from the request.

But since we declare the support for deleted records 'transient', I believe we could get away by always limiting the records to be returned by date. Something like keeping deletions for only the last month might help. This would also allow you to purge older deletions from the database instead of limiting the results.

All this can still be an issue if you do a mass deletion, but then I suppose the harvester actually needs the data.

**Comment by demiankatz** [comment]
Thanks, @EreMaijala; do you think in that case the solution might be a new configuration setting to control the length of time that deletion data is presented through the OAI server? By default we can keep the existing behavior, but this mechanism could be used to limit the deletes. That would probably be good enough for my own use case, at least! If that makes sense to you, I'll see if I can find time to work on it next week.

**Comment by EreMaijala** [comment]
@demiankatz Sure. I'd also consider adding an util to purge old deletions. This could be useful also when not using OAI-PMH but having change tracker enabled.

**Comment by demiankatz** [comment]
Makes sense to me; I'll see what I can do!

**Comment by demiankatz** [comment]
@EreMaijala, do you mind giving this another look? I think this should solve the problem for my use case without violating the spec.

I haven't taken the time to write the command line cleanup utility at this stage; because the change_tracker table is structured differently from other tables with expiration utilities (it has a multi-part primary key instead of an id sequence), the existing expiration logic can't be quickly adapted, and it will instead require some additional effort. I might just open a JIRA ticket and defer that work to another time, unless you have a strong feeling that we need it right away.

**Review by EreMaijala — APPROVED** [review]
@demiankatz Looks good to me now. I don't think the utility is a priority, but a JIRA ticket is a good idea.

**Comment by demiankatz** [comment]
Thanks, @EreMaijala; I'm merging this now and have opened [VUFIND-1374](https://vufind.org/jira/browse/VUFIND-1374) to track the command line tool idea.

**Pull request merged**
