### PR TITLE
Completed ini.nl for version 2.5

### PR DESCRIPTION
**Pull request by bmoelans**
Translations that are missing:

Access URL = "Access URL"
Accession Number = "Accession Number"
medium = "Medium"    => is this about size, the media type or more like 'average'
Subject Geographic = "Subject Geographic"

I need some context for these once.

### CODE REVIEW

**Comment by demiankatz** [comment]
All of these come from the EBSCO Discovery Service interface -- they are record fields that can be displayed. Since I don't use EDS, I'm not 100% sure of their meanings, but my best guesses are:

Access URL = link to item
Accession Number = archival identifier
Medium = media type
Subject Geographic = subject heading for location

Let me know if that helps... and I'll merge this once you've had a chance to add the missing strings.

Thanks!

**Comment by demiankatz** [comment]
@bmoelans Just checking to see if you received my comment above. Please let me know if you need any more detail. Thanks!

**Comment by demiankatz** [comment]
One other thing: just noticed that we were missing a translation for the "Clear" button used on the advanced search screen. Might as well sneak that in too if you don't mind!

**Comment by bmoelans** [comment]
@demiankatz  good that you sent a reminder, I lost it out of sight.
I added the missing translations.

**Comment by demiankatz** [comment]
Thanks again for your help! This is now merged to master.

**Pull request closed without merging**
