### PR TITLE
Fix unwanted hiding of checkboxes on user account pages

### PR DESCRIPTION
**Pull request by dltj**
Fixes https://openlibraryfoundation.atlassian.net/browse/VUFIND-1684

Note — the original pull request (https://github.com/vufind-org/vufind/pull/881) intentionally hid these checkboxes on the renewal/holds page. With this commit, they remain hidden on the search results page.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @dltj! I've rebased this PR against release-9.1 so we can get the fix incorporated faster. I've also included the artifacts created by `npm run build:css`, since we need to commit those in addition to the LESS changes. I'll do some more review and testing soon, but I wanted to give you a heads-up about this in case you're wondering why I force-pushed your branch. ;-)

**Review by demiankatz — CHANGES_REQUESTED** [review]
@dltj, thanks for tracking down the cause here!

I wonder if it would be safer to be more specific about which checkboxes we hide, instead of creating exceptions for which ones should be visible. Otherwise, if we add new features, they'll be hidden by default, and it's worse to show something we don't want than to hide something we do want.

As it is, there are still three scenarios where checkboxes are inappropriately hidden: storage retrieval requests, ILL requests, and historical transaction purging. We could add exceptions for those too, but it feels to me like it would be better to just explicitly hide checkboxes in `#search-cart-form` instead.

What do you think? Also interested in input from @crhallberg here.

**Comment by dltj** [comment]
Oh, nuts...when you said "release 9.1" you mean the literal `release-9.1` tag. I'm sorry I missed that and will keep that in mind for the next time.

**Comment by crhallberg** [comment]
I agree with Demian that making the selector more specific is a better approach than adding exceptions. `#search-cart-form .result .checkbox` is probably the ticket.

**Comment by demiankatz** [comment]
Thanks, @crhallberg -- then the only question beyond that is if we would need a secondary selector for the combined search page, since that may have a different containing form than regular search results. I can't remember, but I'm happy to help set up a test instance to find out if there's a need.

**Comment by demiankatz** [comment]
@dltj, just let me know if you'd like to take the next step on this, or if it's better for me to do it. I don't think it's a lot of work either way. :-)

**Comment by dltj** [comment]
I used the `#search-cart-form` selector explicitly.  Demian: I haven't done a combined search page installation before, so I'd have to look up what that would entail. Is it difficult to do in order to set up a test for this CSS change?

**Comment by demiankatz** [comment]
> I used the `#search-cart-form` selector explicitly. Demian: I haven't done a combined search page installation before, so I'd have to look up what that would entail. Is it difficult to do in order to set up a test for this CSS change?

I just updated the [manual testing wiki page](https://vufind.org/wiki/development:testing:manual_testing#combined_search) with details on how to quickly set up a working combined search that should meet your needs for testing purposes. If anything about this is unclear, or if you have questions, please let me know!

**Comment by dltj** [comment]
> I just updated the [manual testing wiki page](https://vufind.org/wiki/development:testing:manual_testing#combined_search) with details on how to quickly set up a working combined search that should meet your needs for testing purposes. If anything about this is unclear, or if you have questions, please let me know!

Huh — cool. Never seen that side of VuFind before. In any case, with this commit the checkboxes appear and disappear at the same width breakpoints when using the `defaultModule   = Combined` controller while remaining always visible in the MyResearch functions.

**Review by demiankatz — APPROVED** [review]
Thanks, @dltj -- I just tried this out and noticed that compiled.css needed to be updated, so I took care of that. It's now ready to go, and I will merge it now!

Please note that it will take a little while longer before this code makes it to the dev branch. There are currently some fixes merged to the release-9.1 branch that will cause test failures if we merge them before #3534 is completed, so I'm holding off on merging the release branch until that is done. If there's an urgent need to get this to dev faster, we can cherry-pick it, but I think it's probably preferable to wait a little longer. #3534 is important to resolve, I'm just waiting for more input before merging it, to be sure it doesn't create XSS vulnerabilities. Feel free to weigh in if you have an opinion on that one, too. :-)

**Pull request merged**
