### PR TITLE
Autoloading(/resolving) for embedded openurls

### PR DESCRIPTION
**Pull request by lahmann**
As agreed upon in https://github.com/vufind-org/vufind/pull/395 a single pull request for feature autoloading for OpenURLs.

### CODE REVIEW

**Comment by demiankatz** [comment]
Okay, I think all we need to go forward with this one is the blueprint support. Let me know if you need help with that. It also wouldn't hurt to merge the latest master in just to be sure we don't have any conflicts with #395, which is now merged there.

**Comment by lahmann** [comment]
Demian, I have added autoloading to blueprint.
@berndoberknapp and me just had a discussion on using autoloading in result-view which would cause quite big load on the linkresolver.
My approach would be to leave it in the responsibility of the site-admin to adjust the VuFind-settings accordingly to not DOS the defined linkresolver. We definitely should add a notice to the config.ini and advising to cache the resolverlinks if autoloading is enabled for the result-view.
Still, the current implementation only allows to enable autoloading for any inclusion of OpenURLs in VuFind in bulk - therefore having an option that's more differentiated could be quite useful.
So, what do you think about adding another config.ini parameter `embed_auto_load_in_results` which if set to true would enable autoloading in results-view, being set to false only allowing autoloading in record- and holdings-view. Due to https://github.com/vufind-org/vufind/pull/397 we would have everything at hand in the OpenUrl-View-Helper already, so this would probably only add a handful of code lines (plus another config.ini parameter...).

**Comment by demiankatz** [comment]
I agree that it makes sense to make the autoloader as configurable as possible (and to include appropriate warning comments). To make the configuration more compact, perhaps rather than adding a bunch of embed_auto_load_in_... methods, you could instead allow embed_auto_load to accept true (embed everywhere), false (embed nowhere) or a comma-separated string (embed in specific places). You could use the same values as the show_in_... settings (which I would have designed differently if I had created them more recently!).

Then you can use logic along these lines:

<pre>
function embed($location)
{
    if ($this->setting === true) {
        return true;
    }
    if ($this->setting === false) {
        return false;
    }
    return in_array(strtolower($location), array_map('trim', array_map('strtolower', explode(',', $this->setting))));
}
</pre>

Another (possibly complementary) option would be to build some sort of queuing system for the link resolve requests and offer a configurable delay between requests... but that's a lot of complexity, so I wouldn't go that route unless there was a strong use case.

**Comment by lahmann** [comment]
Demian, this is a very good idea - I have prepared the OpenUrl view helper in the last commit for enabling autoloading based on a list of area-strings. As this depends on the refactoring in #397 we should put this pull request on hold until #397 is merged and closed. Do you agree?

**Comment by demiankatz** [comment]
Yes, that makes sense to me. Once #397 is merged, you can merge master in here and finish up.

**Comment by lahmann** [comment]
Just preparing this branch for #397

**Comment by lahmann** [comment]
Demian, I have just merge the latest master into this pullrequest including #397.
The alternative value of an area(-list) for embed_auto_load in config.ini works, although I am not too happy to store `$area` from the previous `isActive($area)` call in the OpenUrl helper. Alternatively one could refactor the signature of `OpenUrl->renderTemplate()` for passing the area along but I think this is even less satisfiying.
As it's working though I wouldn't bother too much with these code-aesthetics, but maybe you've got a better solution?

**Comment by demiankatz** [comment]
I think the answer may be to move the $area parameter from isActive() to __invoke(). That way, you set up the OpenUrl helper when you retrieve it, and just call isActive() to check if it's active in its current state... and renderTemplate will have the necessary information available. What do you think?

**Comment by lahmann** [comment]
Great idea, as we've changed the signature of __invoke() anyway this won't make a big difference and it solves the question when to assign the area. Thanks!

**Comment by demiankatz** [comment]
No problem. I'll take a closer look once you've had a chance to adjust that (maybe later today or tomorrow).

**Comment by lahmann** [comment]
Merged latest master and adjusted the code, tests and templates accordingly.

**Comment by demiankatz** [comment]
Looks good. Manually merged to master with a few minor optimizations.

**Comment by lahmann** [comment]
Thanks!

**Pull request closed without merging**
