### PR TITLE
Add support for passing backend parameters to RecordLoader.

### PR DESCRIPTION
**Pull request by samuli**

### CODE REVIEW

**Comment by demiankatz** [comment]
@samuli, it would probably be valuable to add some test cases for this functionality (in https://github.com/vufind-org/vufind/blob/master/module/VuFind/tests/unit-tests/src/VuFindTest/Record/LoaderTest.php -- I can help if you're not familiar with PHPUnit stuff).

Also, I wonder if it would make more sense for loadBatch to accept an array of ParamBag objects keyed by backend name. Since that method can load records from multiple backends, and each backend has its own distinct parameter requirements, sending a single ParamBag to every backend will lead to errors. If you used a keyed array, then loadBatch could look up the appropriate bag to pass along to loadBatchForSource.

**Comment by samuli** [comment]
> Also, I wonder if it would make more sense for loadBatch to accept an array of ParamBag objects keyed by backend name.

Yes, this makes sense. Fixed now.

I also updated LoaderTest to use backend parameters.

**Comment by demiankatz** [comment]
This looks great -- thanks for the revisions! Out of curiosity, what is your use case for this? I can see how it might be generically useful (and that's reason enough for me to merge it), but I'd be interested to hear what you need in your situation.

**Comment by samuli** [comment]
> Out of curiosity, what is your use case for this?

We have a need to use different versions of the same record, depending on the context. For example, record page and sending of a record via email might have different titles for the record, or some fields might only be allowed to be available on the record page. We pass the context to the RecordLoader, and the Loader forwards it to the search backend. The backend uses this information to populate result fields with correct data. By parametrizing record loading, our Loader can augment the load-call with context parameters, which it receives at creation time. The RecordDrivers do not need to know anything about the context and the funtion that creates the RecordLoader is responsible for handling the context.

**Comment by demiankatz** [comment]
Thanks, @samuli, that makes sense!

**Pull request merged**
