### PR TITLE
Fix jQuery deprecations

### PR DESCRIPTION
**Pull request by EreMaijala**
Adds an eslint plugin for detecting deprecated functionality and applies automatic and manual fixes.

One remaining issue is that facets use Bootstrap's collapse and `$.support.transition` required to disable transitions when restoring the state is also deprecated. The rule has been disabled for now to allow this.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @EreMaijala, this all looks reasonable to me. I'm going to run the test suite to be sure everything still passes for me, but I don't expect any trouble. I'm looping in @crhallberg in case he has any additional thoughts.

Have you done any hands-on testing of any of this? Are there any parts you'd like me to give particular attention to?

**Comment by EreMaijala** [comment]
@demiankatz I've run Mink tests and done some testing, but it won't hurt to test a bit more. I think the manually applied changes with embedded records, lightbox and comments would be the ones where something could have gone wrong.

**Comment by demiankatz** [comment]
Thanks, @EreMaijala, all tests pass for me too (unsurprisingly). I'll see if @crhallberg has anything to add, and I'll manually test the files you suggest when time permits. (It's been an overwhelmingly busy morning for PRs, so I'm still trying to get caught up).

**Review by crhallberg — APPROVED** [review]
This all looks great! Thank you so much!

**Review by demiankatz — APPROVED** [review]
All looks good to me as well. Merging now!

**Pull request merged**
