### PR TITLE
Add delimited facet capability

### PR DESCRIPTION
**Pull request by datavoyager**
This pull might be useful for facets with useful but human incomprehensible facets. We intend to use it for a unique authors facet. Wales has a lot of people with similar names so we get a lot of authors called "Gareth Jones". By setting the a delimited facet like 123456::Jones, Gareth we can make sure each Author get's their own filter but still display meaningful text.

### CODE REVIEW

**Comment by demiankatz** [comment]
Looks like Travis is complaining about a few things. Some may be related to a known bug in PHP_CodeSniffer -- if you merge the latest master, it will change the Travis config to load an earlier phpcs version. Others are probably real issues that need to be fixed -- but if you can give me write access to this branch, I don't mind taking care of them for you. I also spotted a typo in the example in the comments (missing }} in the example delimited facet) that I'd be happy to clean up if I could edit directly.

Obviously I'll give you more substantial comments in the near future -- but it's nice to get the cosmetic stuff cleaned up first so it's all ready to be merged if there are no functional problems!

In any case, thanks for sharing!

**Comment by datavoyager** [comment]
Hi Demian,
I think you should have write permissions now. Can you check?
Cheers,
Luke
Date: Fri, 4 Dec 2015 05:52:03 -0800

**Comment by demiankatz** [comment]
Looks like this PR was opened against the release-2.5 branch instead of master. I'm going to close it and open a new one.

**Comment by demiankatz** [comment]
Okay, I've opened #528 to replace this. I'll try to give it a closer look next week, but at least some of the minor issues should now be taken care of.

**Comment by demiankatz** [comment]
Also, I did a forced push to the delimted-facets branch to rewrite the history. Apologies if this causes you any confusion. You should delete your local branch and check out a new copy rather than trying to pull. (And if for some reason you need a copy of the history based against release-2.5, just push your local branch to a different remote). Let me know if you have any questions/problems -- I apologize if I was a bit overzealous here.

**Pull request closed without merging**
