### PR TITLE
SCSS PHP compiler

### PR DESCRIPTION
**Pull request by crhallberg**
TODO
- [x] Port to Symfony\Console
- [x] Make sure it works
- [x] Write test class for VuFindTheme\ScssCompiler

### CODE REVIEW

**Comment by demiankatz** [comment]
@crhallberg, if the ScssCompiler is largely copied and pasted from the LessCompiler, is it worth refactoring them with a common abstract base class?

**Comment by demiankatz** [comment]
We should probably put this on hold until #1571 is completed.

**Comment by demiankatz** [comment]
@crhallberg, I've merged the latest master into this and ported the Laminas\Console changes to Symfony\Console. It appears to be working, but I didn't do a deep dive to be 100% sure all is well. Can you double-check when time permits?

I think the remaining tasks are to write a test case for VuFindTheme\ScssCompiler (there's an existing test for the LessCompiler that can probably be used as a basis) and to figure out how to document and use this going forward.

**Comment by demiankatz** [comment]
Thanks for the progress, @crhallberg! Is this ready to merge at this point, or do you still have some manual testing to do?

**Comment by crhallberg** [comment]
I think this is ready to go!

**Pull request merged**
