### PR TITLE
ImageLink: Fix invalid URL being generated if file name contains special characters (e.g. '?')

### PR DESCRIPTION
**Pull request by mtrojan-ub**

### CODE REVIEW

**Review by demiankatz — CHANGES_REQUESTED** [review]
Thanks, @mtrojan-ub. However, I'm not sure if it's a good idea to urlencode this aggressively. As written, this will encode all of the slashes, and then the image links will only work when the Apache AllowEncodedSlashes setting is turned on (which is not a default or recommended setting, though it is required for VuFind instances where IDs may contain slashes).

Would it be better to take a less aggressive approach, such as this?

```
$parts = explode('/', $relPath);
$encodedRelPath = implode('/', array_map('urlencode', $parts));
```

What do you think?

**Comment by mtrojan-ub** [comment]
Thanks, you're absolutely right! I changed the code, could you please have another look?

**Review by demiankatz — APPROVED** [review]
Thanks, @mtrojan-ub -- this looks good (and works correctly for me).

**Comment by mtrojan-ub** [comment]
One more thought on this one, even though the PR has already been merged:
After some more testing, i noticed that it might be better to switch from `urlencode` to `rawurlencode`. The reason is => if you have spaces in your filename, `urlencode` will convert them to `+` but `rawurlencode` will convert them to `%20`. This might be problematic e.g. with the default configuration of apache web server. `urlencode` should usually be used to encode the query after the `?`, but since the filename of the image is usually part of the path, `rawurlencode` should be better here.

**Comment by demiankatz** [comment]
Thanks, @mtrojan-ub. Feel free to open a follow up to make this improvement!

**Pull request merged**
