### PR TITLE
Indicate that ContainerExceptions must also be Throwable.

### PR DESCRIPTION
**Pull request by demiankatz**
This is a minor documentation improvement intended to reduce Psalm warnings (see #1764).

### CODE REVIEW

**Comment by demiankatz** [comment]
@xmorave2, your work with PHPStan has inspired me to try to make more progress with Psalm as a complement. This PR is an attempt to fix one of the most prevalent issues reported by Psalm... but the fix doesn't work (see my recent notes on #1764). I think that's due to a bug in Psalm rather than an error in this change, but I'm interested in your opinion. Do you see anything wrong with what I am doing here? Is it worth merging this regardless of whether it resolves Psalm errors? I'm hopeful that if we do this now, it will benefit Psalm in the long run once the relevant bug gets fixed.

**Comment by xmorave2** [comment]
@demiankatz 


https://docs.phpdoc.org/3.0/guide/references/phpdoc/types.html

**Review by xmorave2 — APPROVED** [review]
@demiankatz, according to PHPdoc there not a thing like intersection type: https://docs.phpdoc.org/3.0/guide/references/phpdoc/types.html

But PHPstan and Psalm both do recognize them, so it is OK for us to use them. And as this change is done in the manner the intersection types were designed, I am for merging this.

**Comment by demiankatz** [comment]
Thanks for the review, @xmorave2; I'll go ahead and merge this now, and hopefully Psalm will fix their support in `@throws` soon (feel free to watch that issue if you want to add a little more pressure). Interestingly, I also see that an RFC just opened for native intersection type support in PHP: https://github.com/Girgias/intersection-types

**Comment by xmorave2** [comment]
@demiankatz That's really interesting, thanks for the info

**Pull request merged**
