### PR TITLE
Handle %size% token when using local file in coverimages

### PR DESCRIPTION
**Pull request by sbujam**
When using LocalFile in coverimages in the [Content] section of config.ini, you have the option to use %size% token to distinguish directories based on different sizes (small/medium/large).

Up till now, the %size% token was not handled and translated to one of the 3 allowed values ('small', 'medium', 'large'), resulting in a filename that contained the %size% string in it, thus not pointing to the proper directory in the filesystem.

This fix remedies that (relatively rare) issue.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @sbujam! I noticed that this class didn't have a test associated with it, so I spent a little time adding the missing test. Along the way, I made some general modernization to the class (added types, used more efficient string functions). I also reworked your fix slightly to avoid the need for a separate size-related method; I think it's simpler to replace all the tokens at once instead of doing multiple string replace operations in a row.

Do you mind double-checking my work and making sure this version works for you? Once I get confirmation from you, I'll approve and merge this unless you have problems or further suggestions.

**Comment by sbujam** [comment]
I double-checked and your modified code works like a charm!

As always, a big thank you for your time and effort :)

**Review by demiankatz — APPROVED** [review]
Thanks again, @sbujam! Merging now.

**Comment by demiankatz** [comment]
I've also backported this to the release-9.1 branch so it can be included in 9.1.1.

**Pull request merged**
