### PR TITLE
KohaRest driver: allow null for expirationdate in holds

### PR DESCRIPTION
**Pull request by JacobSandin**
When not forcing an expiration date for renewals, the renewals was added to Koha with the date 1970-01-01. This change allow for null instead of a date when $holdDetails['requiredByTS'] is null.

/Jacob

### CODE REVIEW

**Comment by JacobSandin** [comment]
I removed the tags files.

**Review by EreMaijala — APPROVED** [review]
Looks good to me!

**Comment by xmorave2** [comment]
@JacobSandin Please fix the warning from phpcs - you can the problem in CI tasks here. You can also run these checks locally when needed, just run command `composer qa`. Feel free to ask if you need any help.

**Comment by demiankatz** [comment]
Thanks, everyone. This looks fine to me too -- once the line length problem is fixed, please feel free to squash and merge it (or I can, if you prefer).

**Comment by JacobSandin** [comment]
Sorry have not learned rebase yet, but line length should pass now.

**Comment by xmorave2** [comment]
Thanks for you contribution @JacobSandin. Merging now

**Comment by demiankatz** [comment]
Thanks, @JacobSandin and @xmorave2! While the build is passing now, I'd suggest a 4-space indent rather than an 8-space indent for consistency with other code. But not a major issue! :-)

Regarding rebasing, since we usually use the "Squash and merge" when merging pull requests (to flatten everything to a single commit), it's not essential to have a "clean" commit history within the PR itself.

**Comment by xmorave2** [comment]
Sorry @demiankatz I was too fast and didn't notice the 8 spaces indent

**Comment by demiankatz** [comment]
Not a disaster. :-)

**Pull request merged**
