### PR TITLE
Add lessdev Grunt task

### PR DESCRIPTION
**Pull request by crhallberg**
- Creates CSS source maps
- Does not compress CSS
- Can be watched with `grunt watch:lessdev`

### CODE REVIEW

**Comment by demiankatz** [comment]
Would it make sense to have a variable containing the less configuration so that most of this can be shared between the less and lessdev tasks, with lessdev simply manipulating the necessary parts of the object to change to dev settings? That might make long-term maintenance easier, so we don't accidentally end up with the two tasks being out of sync on some of the standard settings.

**Comment by crhallberg** [comment]
I tried to consolidate the logic in a couple different ways but I couldn't get it to work properly. I'm willing to let someone with stronger Grunt skills try!

**Comment by demiankatz** [comment]
On closer examination, I see why this is hard. However, is it worth assigning:

<pre>
var lessFileSettings = [{
  expand: true,
  src: "themes/*/less/compiled.less",
  rename: function (dest, src) {
    return src.replace('/less/', '/css/').replace('.less', '.css');
  }
}];
</pre>

to at least eliminate that redundancy?

**Comment by crhallberg** [comment]
That worked. Still not sure why sharing other parts isn't working.

**Comment by demiankatz** [comment]
This looks fine to me now. Thanks!

**Pull request merged**
