### PR TITLE
Added support for a relevance sort override for empty searches.

### PR DESCRIPTION
**Pull request by EreMaijala**

### CODE REVIEW

**Comment by demiankatz** [comment]
This looks pretty straightforward, though I wonder if it would be a slight simplification to do this:

<pre>
if ($sort == 'relevance' && $this->getQuery()->getAllTerms() == ''
    && ($relevanceOverride = $this->getOptions()->getEmptySearchRelevanceOverride())
) {
    $sort = $relevanceOverride;
}
</pre>

(But that's probably just nitpickery).

It would also be nice to be able to share this functionality with some other backends like Summon... but that's probably best achieved by copy and paste right now, since I can't think of a good way to do this as a trait since some details aren't entirely generic....

**Comment by EreMaijala** [comment]
The second line doesn't fit in 85 chars and causes a situation where my CodeSniffer thinks there's always something wrong (too much / too little indentation). Feel free to modify before commit if you can make it work without throwing validation errors.

Does Summon allow an empty search? PCI doesn't, and I can't test with Summon, but if it allows an empty search, I agree similar functionality should be available there.

**Comment by marchitelli** [comment]
Yes, Summon allows empty searches. Try at https://discovery.sba.uniroma3.it/Summon

**Comment by EreMaijala** [comment]
Thanks for the info. I added support for Summon too, but I can't test it..

**Comment by demiankatz** [comment]
I'll see what I can do about the CodeSniffer issue and will test the Summon functionality shortly (some time after finishing up the release process). Thanks!

**Comment by EreMaijala** [comment]
@demiankatz, please feel free to push any improvements to this branch, thanks. :)

**Comment by demiankatz** [comment]
This looks good to me -- the Summon piece works fine. I addressed the style problem by abbreviating the variable to $relOv (not ideal, but I think perfectly understandable given the small amount of code that uses the variable). I also tweaked a couple of comments and changed the Summon.ini default sort option (since Summon doesn't support title sorting by default).

I've manually merged all of this to master. Please let me know if you run into any problems.

Thanks again for the work!

**Pull request closed without merging**
