### PR TITLE
Remove input-group and adjust paddings for searchbox controls.

### PR DESCRIPTION
**Pull request by EreMaijala**
Removes the input-group class since it shouldn't be used for inputs that are not visually grouped together. Adds adjustments to the input padding so that the reset button and keyboard button always have enough room.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @EreMaijala! I'm requesting reviews from @ThoWagen (since this is related to virtual keyboard work, so he might have opinions) and @sturkel89 (so she can compare the functionality here against the dev branch for all three themes, with and without virtual keyboard enabled -- we're interested in making sure the text in the search box interacts appropriately with the virtual keyboard and reset buttons and that everything is positioned correctly).

**Review by sturkel89 — APPROVED** [review]
I've tested this branch in all three themes, with virtual keyboard turned on and off. 

Everything functions identically in test and dev; the only difference is the improvement in appearance of the text in the search box in the test branch.  

I'll show examples with and without virtual keyboard.

-----
**VIRTUAL KEYBOARD ON:**
The improvements are the most apparent when the virtual keyboard is on. In this condition in dev, the search box input text is overlapped by the reset button and peeks out between the reset button and the virtual keyboard button. 

- **Test branch:**
image

- **Dev branch:**
image

------

**VIRTUAL KEYBOARD OFF:**
It's subtle, but there is more padding between the search text and the reset button.

- **Test branch:**
image

- **Dev branch:**
image


In terms of the intended improvements, I think this branch is ready to go.

**Review by demiankatz — APPROVED** [review]
Looks good to me, too! I'll just wait to see what @ThoWagen thinks before merging.

**Comment by sturkel89** [comment]
One more thing: while testing this PR, I noticed a behavior difference between the virtual keyboard and the physical keyboard. At Demian's suggestion, I created a JIRA ticket: https://openlibraryfoundation.atlassian.net/browse/VUFIND-1654

**Comment by ThoWagen** [comment]
I noticed a problem on screens smaller than 768px. The lookfor input does not have the same width as the type selection.

- Test branch:
Bildschirmfoto vom 2023-12-06 09-11-29

- Dev branch:
Bildschirmfoto vom 2023-12-06 09-11-44

**Review by demiankatz — CHANGES_REQUESTED** [review]
Thanks, @ThoWagen! @EreMaijala, can you take a look at this issue?

**Comment by EreMaijala** [comment]
> Thanks, @ThoWagen! @EreMaijala, can you take a look at this issue?

Yes, I'll take a look. To be honest, the full width fields look quite terrible to me with such a wide display, but that's how it's been and should have been here as well.

**Comment by EreMaijala** [comment]
Okay, should be fixed now. I also made the following changes:

- Moved all rules for hiding the keyboard on narrow screens to search.less (the component shouldn't be making the decision that causes adjustments to be made in the searchbox).
- Added hiding of the keyboard alongside its button on narrow screens.
- Fixed the padding adjustment to not affect narrow screens.
- Moved related rules near each other in search.less.

**Review by ThoWagen — APPROVED** [review]
This looks good to me now.

**Review by demiankatz — APPROVED** [review]
Thanks, everyone!

**Pull request merged**
