### PR TITLE
Updates to sh start script

### PR DESCRIPTION
**Pull request by samueloph**
Please feel free to report any concerns about the changes or eventual identation problems.

This should fix all the 16 issues that shellcheck reported on the script;

- [X] Rewrite findDirectory function so now it doesn't work with any parameter (only accepts -w or -r).
- [X] Prefer [ p ] && [ q ] as [ p -a q ] is not well defined (5 occurrences of this).
- [X] JVERSION was commented because it wasn't used.
- [X] JAVA_VERSION was commented because it wasn't used.
- [X] Cygwin case was commented because it wasn't used.
- [X] *\`cat $JETTY_PID\`* changed to *$(cat $JETTY_PID)*, so it prevents word splitting. Altought it's not a problem here, it's nice because of good practices.
- [X] Use "$@" (with quotes) to prevent whitespace problems and keep good practices, at the restart process.
- [X] Only echoes Java found when starting VuFind, it was echoing three times at the restart process and once with every possible parameter, even when no supported parameter was used (the usage function case).

### CODE REVIEW

**Comment by demiankatz** [comment]
Have you taken a look at #435? This PR upgrades to Solr 5, which forces a complete rewrite of the startup script (vufind.sh is replaced by solr.sh for clarity). Assuming that a Solr release comes out soon that doesn't break VuFind (right now, Solr 5.4 has some issues we can't easily work around) we'll probably be making that upgrade to master soon. Thus, I'm not sure if it's worth putting a lot of time into adjusting a script that will soon be thrown away anyway. I'm still willing to look more closely at this if you think it meets an important need, but either way, it might be worth running the same analysis against #435's solr.sh to see how it stacks up. Thanks!

**Comment by samueloph** [comment]
I did, actually, but since it was open since August I've decided to made this in case there will be any releases before the Solr 5.5 release (I think that you're waiting for 5.5 to fix something that i saw on the mail list, right?!).

I believe there's nothing left to do in the vufind.sh, so it only needs approval, but I understand that there's no sense in updating vufind.sh and dropping it before a release occurs, so I'm closing this PR

Thanks Demian, I'm gonna follow the transition to the new solr version.

**Comment by demiankatz** [comment]
The recently discussed fix in 5.5 will allow us to close an old ticket that's been open for years -- a very nice bonus. But actually the main reason we're waiting is that 5.4.0 has a bug in the MoreLikeThis handler that completely breaks all of VuFind's record pages (unless we work around by removing boost queries from similarity queries -- which would be a loss of functionality that I don't want to introduce unnecessarily). Perhaps we'll see a fix for this in 5.4.1, though I'm not sure if that's planned or not.

In any case, thanks for bearing with us -- and feel free to reopen this if it looks like we're going to end up minting a release without Solr 5 (which might happen if a working release takes too long to arrive).

**Comment by EreMaijala** [comment]
5.4.1 should contain this fix and RC2 is being released so it's near release now.

**Comment by demiankatz** [comment]
That's great news! Thanks for the update!

**Pull request closed without merging**
