### PR TITLE
Fix missing searchClassId in layout

### PR DESCRIPTION
**Pull request by LuomaJuha**
Hello! Here is a small fix for an issue where our authority search did not recognize the proper searchClassId and routed searches to solr.

### CODE REVIEW

**Comment by LuomaJuha** [comment]
Nvm, Ere told me another route :)

**Comment by demiankatz** [comment]
Thanks, @LuomaJuha. Since this is a bug fix, feel free to target your eventual work against the release-9.1 branch instead of dev if you'd like this to go into 9.1.1 when that is released.

**Comment by demiankatz** [comment]
Update: sounds like this was an entirely local issue, so no further changes are needed.

**Comment by EreMaijala** [comment]
Yes, a local issue, and no changes needed.

**Pull request closed without merging**
