### PR TITLE
Enclose the facet text with a span tag

### PR DESCRIPTION
**Pull request by liowalter**
To have more flexibility in design, I would suggest enclosing the facet text with a span tag.

Current status : 
```html
<div class="facet js-facet-item facetOR">
	<a class="text" href="..." data-lightbox-ignore="" data-title="English" data-count="4292351">
		<i class="fa fa-square-o" aria-hidden="true"></i>
		English
	</a>
	<span class="badge">4'292'351</span>
	<a href="..." data-lightbox-ignore="" title="Exclude matching results" class="exclude">
		<i class="fa fa-times" aria-hidden="true"></i>
	</a>
</div>
```
After this pull request : 
```html
<div class="facet js-facet-item facetOR">
	<a class="text" href="..." data-lightbox-ignore="" data-title="English" data-count="4292351">
		<i class="fa fa-square-o" aria-hidden="true"></i>
		<span class="description">English</span>
	</a>
	<span class="badge">4'292'351</span>
	<a href="..." data-lightbox-ignore="" title="Exclude matching results" class="exclude">
		<i class="fa fa-times" aria-hidden="true"></i>
	</a>
</div>
```

For example, this allows using ```display:block``` for the text together with ```text-overflow: ellipsis``` to have a good rendering of multiline facet texts which are too long : 

screenshot_332

### CODE REVIEW

**Comment by demiankatz** [comment]
@crhallberg, what do you think of this?

**Comment by crhallberg** [comment]
I'm in favor of this. The next theme will have much more of this. I'd recommend a class more like `.facet-label` or `.facet-description` to make the selector as easy to override as possible (less specific).

**Comment by demiankatz** [comment]
I agree that a more descriptive class name would be helpful. I'm fine with @crhallberg's suggestions, but I'd also say that `.facet-value` might be another possibility. @liowalter, do you have any preferences?

**Comment by liowalter** [comment]
Thanks for the feedback. I totally agree with you regarding the class name. I have no preference among your suggestions. I updated the pull request with `.facet-label`, but feel free to change it if you have any preference.

**Comment by demiankatz** [comment]
Thanks, @liowalter, we'll discuss this on today's developers call, make a decision, and get this merged.

**Comment by demiankatz** [comment]
I'm back from my travels and had time to run the full test suite, and nothing seems to be broken by this, so I'm going ahead with the merge. Thanks again!

**Pull request merged**
