### PR TITLE
Improve compatibility with older Solr index versions by checking if a…

### PR DESCRIPTION
**Pull request by EreMaijala**
…uthor field is an array.

### CODE REVIEW

**Comment by demiankatz** [comment]
Could you do this even more simply with typecasting... e.g.:

`return isset($this->fields['author'])  ? (array) $this->fields['author'] : [];`

? If you've already thought of that and it didn't work out, let me know and I'll merge this as-is... but if we can save a couple of lines of code, I'm always in favor of that.

**Comment by tillk** [comment]
For me Demian's economical and elegant solution works as well as the one from Ere. With the author field either defined as multi or single valued in Solr... Thank's.

**Comment by EreMaijala** [comment]
I've been a bit cautious with casting since it can sometimes seem a bit unambiguous, but I see the beauty in Demian's proposal, so I'm ok with that too.

**Comment by demiankatz** [comment]
Okay, committed here: https://github.com/vufind-org/vufind/commit/9cb7b777160284cf982ab8c2fb5f26d85f40953b. Thanks!

**Pull request closed without merging**
