### PR TITLE
Fix a PHP notice from MultiBackend driver and exception from Missing …

### PR DESCRIPTION
**Pull request by EreMaijala**
…record driver when trying to display holds with idsInMyResearch = false.

The latter happens any time getUniqueID() is called for a Missing record.

### CODE REVIEW

**Comment by demiankatz** [comment]
@EreMaijala, missing records should have a valid ID set that can be returned through getUniqueId() -- see, for example, how determineMissingTitle() uses the unique ID in order to look up title information in the database. I don't think the best solution to the problem is forcing the driver to return an empty ID. I wonder if something got broken during the record driver refactoring. Let me know if you need me to dig more deeply into this; it may take me a little while to find time, but I can do so within the next couple of weeks!

Also note that changing `$holdDetails['id'] ? $holdDetails['id'] : $holdDetails['item_id']` to `$holdDetails['id'] ?? $holdDetails['item_id']` changes its meaning, since if `$holdDetails['id']` is set but evaluates to false, it will now be returned, where it would not have in the past. This may or may not be an issue depending on the context, but just wanted to mention it in case it matters.

Thanks!

**Comment by EreMaijala** [comment]
Oh, then I need to find out why the record didn't have a unique ID. The change in semantics in MultiBackend doesn't matter since the id should always have a prefix if it's present.

**Comment by EreMaijala** [comment]
I debugged further. The id gets set, but it's null because of https://github.com/vufind-org/vufind/blob/master/module/VuFind/src/VuFind/Controller/MyResearchController.php#L948. isset() returns false for null. I'm not sure what the best way to fix it.

**Comment by demiankatz** [comment]
@EreMaijala, is the question then why the ILS driver is not providing an ID in the first place?

Assuming that there's a sane reason for the data getting sent in that way, perhaps a solution is to go forward with what you do here, but instead of forcing the unique ID to always be empty, only return an empty string when $this->fields['id'] is unset... or, to be even more sophisticated, you could do something like `return 'missing-' . md5(print_r($this->fields, true));` to generate something that's actually likely to uniquely identify the missing record.

**Comment by EreMaijala** [comment]
@demiankatz See the original description, I'm trying to run Demo driver with idsInMyResearch = false. :) That is to mimic behavior of real ILS's that don't always return the record ID (that sucks, but there's nothing we can do about it).

**Comment by demiankatz** [comment]
Ha, sorry, not quite awake yet. ;-) But in that case, I think my suggestions may be workable -- just a question of whether to use the blank string or the generated ID.

**Comment by EreMaijala** [comment]
I'll try the suggestions out to see how it goes.

**Comment by EreMaijala** [comment]
I ended up just setting the id to '' if it doesn't exist. I think it's a better indication that there's no actual id. Added a couple more checks to MultiBackend too.

**Comment by EreMaijala** [comment]
2.) Right, I assumed item_id would be always present, but it's optional in the docs, so I'll have to change that.

**Comment by demiankatz** [comment]
Thanks! I'll merge once you've had a chance to add a few more `?? ''` clauses to the code!

**Comment by EreMaijala** [comment]
Done, thanks!

**Pull request merged**
