### PR TITLE
Alma: Implement checkRequestIsValid to use AJAX for checking holdabil…

### PR DESCRIPTION
**Pull request by EreMaijala**
…ity.

Since fetching holdings from Alma is slow enough as it is, checking holdability along that makes it even slower. Thus I'd propose this change to make the requestability check via AJAX after the basic holdings screen has loaded.

### CODE REVIEW

**Comment by EreMaijala** [comment]
Additionally, this allows us to check that level and description are in HMACKeys and disallow title level hold otherwise.

**Comment by EreMaijala** [comment]
Note that if we implement support for Alma's general electronic services, the item part of this may be unnecessary as we'd need to fetch the request options anyway. But I think that should be configurable.

**Comment by demiankatz** [comment]
Thanks, @EreMaijala, no opinions from me since this all looks very Alma-specific, so I'll wait for feedback from @betullam before merging.

**Comment by demiankatz** [comment]
@betullam, I note that you approved #1456 earlier this week but haven't commented on this one yet. No rush, of course, but just checking to be sure it didn't slip through the cracks. :-)

**Comment by betullam** [comment]
@demiankatz You are right: That one sliped :-) ... I will test it next week.

**Review by betullam — APPROVED** [review]
@demiankatz and @EreMaijala - Tested it with our data and it worked without a problem.

**Comment by demiankatz** [comment]
Thanks, @betullam -- merging now!

**Pull request merged**
