### PR TITLE
Refactored route generation to a class.

### PR DESCRIPTION
**Pull request by demiankatz**
The hard-coded route generation in module.config.php is refactored to a class here so that it can more easily be called by code generators or reused in a local module. It will require some further thought to figure out how best to incorporate this into code generation -- if we automatically rewrite the VuFind module's module.config.php, we'll lose some helpful comments.

### CODE REVIEW

**Comment by xmorave2** [comment]
Would it be still possible to add non-tab record actions to the route an "easy" way? In our local module we use added non-tab record action for lending e-books.

**Comment by demiankatz** [comment]
The eventual goal is to have console routines that will add routes to modules through a single command -- so the module.config.php files will have more verbose routes in them, but it should actually be easier and more flexible to add new ones.

**Comment by demiankatz** [comment]
I've just written the basic route generators to address static routes, record routes, and addition of new non-tab record actions. I didn't create a generator for list routes, as I think these are of fairly limited utility.

At this point, I think we might be in a good position to merge this branch, as it adds functionality without breaking anything.

However, one remaining question is whether we should completely eliminate the calls to the route generator currently found in the VuFind module's module.config.php in favor of distributing pre-generated routes in that file. I don't have strong feelings one way or another, but if we do decide to make the file completely static, we'll have to think about the best way to generate that static file without losing a bunch of useful comments elsewhere in the configuration.

**Comment by xmorave2** [comment]
I agree, according to me, it's good enhancement. Thank you Demian.

I don't have strong opinion about eliminating the route generator calls from module config too.

**Comment by demiankatz** [comment]
For now, I've decided to merge this to master as-is and leave the route generator calls in the module config. We can always revisit that issue in the future if there is a compelling need, but for the moment, Zend Framework's native module config caching is already taking care of the efficiency aspect of that problem, so it may be worthwhile to keep this as-is for readability purposes.

**Pull request closed without merging**
