### PR TITLE
Added getRecords() to Primo connector so that multiple records can be…

### PR DESCRIPTION
**Pull request by EreMaijala**
… retrieved at once.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks! Looks good to me (though unfortunately I can't test on this end).

**Comment by olli-gold** [comment]
I can confirm its working fine here.

**Comment by demiankatz** [comment]
Thanks for the double-check!

**Comment by EreMaijala** [comment]
@olli-gold thanks for testing, makes me also more confident.

**Pull request merged**
