### PR TITLE
Update dependencies for VuFind 8.0 release.

### PR DESCRIPTION
**Pull request by demiankatz**
TODO
- [x] Finish reviewing/updating outdated dependencies
  - [x] composer/package-versions-deprecated: 1.11.99.1 => 1.11.99.2
  - [x] endroid/qr-code: 4.1.4 => 4.2.1
  - [x] friendsofphp/php-cs-fixer: v2.19.0 => v3.0.2 (see https://github.com/vufind-org/vufind/pull/2050)
  - [x] jasig/phpcas: 1.3.9 => 1.4.0
  - [x] laminas/laminas-cache: 2.11.1 => 2.13.0 (see https://github.com/vufind-org/vufind/pull/2054)
  - [x] laminas/laminas-escaper: 2.7.0 => 2.8.0
  - [x] laminas/laminas-filter: 2.11.0 => 2.11.1
  - [x] laminas/laminas-form: 2.16.3 => 3.0.1 (see https://github.com/vufind-org/vufind/pull/2051)
  - [x] laminas/laminas-mail: 2.14.0 => 2.14.1
  - [x] laminas/laminas-servicemanager: 3.6.4 => 3.7.0
  - [x] laminas/laminas-stdlib: 3.3.1 => 3.5.0
  - [x] laminas/laminas-validator: 2.14.4 => 2.14.5
  - [x] league/commonmark: 1.6.5 => 1.6.6
  - [x] lm-commons/lmc-rbac-mvc: v3.2.0 => v3.3.0
  - [x] pear/http_request2: v2.4.2 => v2.5.0
  - [x] phpmd/phpmd: 2.10.0 => 2.10.2
  - [x] phpstan/phpstan: 0.12.85 => 0.12.94 (see https://github.com/vufind-org/vufind/pull/2049)
  - [x] phpunit/phpunit: 9.5.4 => 9.5.8
  - [x] scssphp/scssphp: v1.4.1 => v1.6.0 (see https://github.com/vufind-org/vufind/pull/2056)
  - [x] swagger-api/swagger-ui: v3.40.0 => v3.52.0
  - [x] symfony/console: v5.2.8 => v5.3.6
  - [x] symfony/yaml: v5.2.7 => v5.3.6
  - [x] vufind-org/vufindharvest: v4.0.1 => v4.1.0
- [x] Run the full test suite
- [x] Investigate phpmd problem mentioned below (solved by https://github.com/vufind-org/vufind/pull/2055)
- [x] Check whether we can update Composer version due to fixes in composer/package-versions-deprecated

### CODE REVIEW

**Comment by demiankatz** [comment]
This is currently work in progress; I'll work my way through additional dependency updates as time permits.

**Comment by xmorave2** [comment]
@demiankatz I started working locally on update of league/commonmark to 2.0, but it requires minimal PHP version 7.4, so I think it is not OK for VuFind 8.0 and we could wait with this update to VuFind 9.0

**Comment by demiankatz** [comment]
@xmorave2, yes, I agree. There is a minor update of league/commonmark that is still compatible with PHP 7.3, and I plan to include that here when I have time to apply more updates. The major update can wait until 9.0. If you wish to share the work before you forget about it, you are certainly welcome to open a separate pull request with the update for 2.0, and we can mark it with the 9.0 milestone and merge it in the future when we are ready.

**Comment by xmorave2** [comment]
@demiankatz It is good idea, I have open #2048 with 9.0 milestone.

**Comment by demiankatz** [comment]
I spent a little time working on tool upgrades today. I think we're going to need separate PRs for phpstan and php-cs-fixer, since the latest phpstan is detecting lots of new issues that may need to be addressed, and php-cs-fixer has released a major version that changes some things significantly. 

I've also discovered that phpmd is not working at all (and hasn't been for a while, apparently -- it's not related to the update here). It's failing with the message `Trait method logError has not been applied, because there are collisions with other trait methods on VuFind\ILS\Driver\KohaRest.` Need to figure out why, but I don't have time at the moment.

**Comment by demiankatz** [comment]
I've made more progress today, including opening a couple more pull requests focused on dependencies that are more complex to upgrade. I've run into a problem with scssphp/scssphp -- if I switch the bootstrap3 theme to use scss instead of less and try to run the compiler, I get the error:

<pre>
Compound selectors may no longer be extended.
Consider `@extend a, :hover` instead.
See http://bit.ly/ExtendCompound for details.
</pre>

I'm not sure if this means we need to restructure our styles, or if this is just a limitation of the library. I'm also not sure how much time we want to put into this, since we're not really using this in practice yet... but if we're considering a switch from LESS to SCSS in future, it would be good to understand this issue in advance. Any thoughts, @crhallberg?

**Comment by crhallberg** [comment]
Made two small changes to eliminate problems with `@extend .selector all;` which appears to have been deprecated. #2056

**Comment by demiankatz** [comment]
@EreMaijala, as I mentioned to you on Slack, since the only outstanding work listed here has a PR of its own, and all tests are passing, I think it is safe to merge this now. Any objections?

**Review by EreMaijala — APPROVED** [review]
Agreed. All looks good to me.

**Comment by demiankatz** [comment]
Thanks!

**Pull request merged**
