### PR TITLE
Complete W3C validation of Vufind on Bootstrap3

### PR DESCRIPTION
**Pull request by samueloph**
Following this PR are a few changes in Vufind that make it validate without errors or warnings on the W3C validator (https://validator.w3.org/).

I'd like to receive some opinions on the changes I made, specially on https://github.com/vufind-org/vufind/commit/31388de47f18320101b114fe4410f629f6bf796a and https://github.com/vufind-org/vufind/commit/c35270b24680b30850428d5abb2b50c0ec21df88 cause I think somebody could come up with a best solution.

There are currently one problem on the page that logged users see (that one where it shows their favorites, etc), It looks like that page is calling the searchtab twice, as seen in this error:
Error: Duplicate ID searchForm_lookfor.

This was the same problem faced on https://github.com/vufind-org/vufind/commit/c35270b24680b30850428d5abb2b50c0ec21df88, and I fixed it by disabling the top search bar, the unavailable error does the same thing, so i thought it would be a nice fix in this case [vufind/themes/bootstrap3/templates/error/unavailable.phtml], don't know how to fix the user page, though.

Any views on how to solve the favorite issue or a better approach to any of the commits?

The homepage and advanced search are already being validated nicely:

BEFORE: (not really before, this print is with a few fixes already committed)
screenshot from 2015-08-25 17-31-20

AFTER:
screenshot from 2015-08-28 21-27-10

The fixes are basic things, they include changing some ARIA's role positions or even deleting them (when don't needed).

### CODE REVIEW

**Comment by crhallberg** [comment]
To prevent the modal header from ever being empty, you may also need to change the empty string to '&nbsp;' in lightbox.js closeActions: https://github.com/vufind-org/vufind/blob/master/themes/bootstrap3/js/lightbox.js#L138

**Comment by samueloph** [comment]
Ok, thanks guys.

I accidentaly replaced a "" in lightbox.js, had to make another commit to reverse it (I also mispelled the commit title, should be 'Fix accidental edit'), but anyway, when you guys feel its ready to merge, I can make another PR to remove this "trash commits" if its needed.

We still are left with two major problems, the ones where something generated a souble searchbox, I fixed one of them but the workaround didn't feel right.

**Comment by demiankatz** [comment]
The duplicate search box is related to the "responsive design" features of the Bootstrap theme. I'll talk to Chris tomorrow when we're in the office together and see if we can come up with a way to keep the responsiveness but make the markup valid.

**Comment by ckaz** [comment]
Just my 5ct on this one: We've been thinking about this for a while and added it to our todo list as well: I always thought, replacing the id with a class should work and validate completely. 

As fas as I'm aware, the current id="searchForm_lookfor" is referred to in 
common.js:
  $('#searchForm_type').change(function() {
    var query = $('#searchForm_lookfor').val();
    $('#searchForm_lookfor').focus().typeahead('val', '').typeahead('val', query);
  });
default.less/css,
and in the searchbox.phtml itself:
<script type="text/javascript">$("#searchForm_lookfor").focus()</script>

**Comment by demiankatz** [comment]
The biggest obstacle to replacing the id with a class is that we have Javascript to auto-focus the search box. You can't focus more than one thing at a time, and I'm not sure how to deal with that. Perhaps there is some way to focus only the visible version of the form, but I don't know how the timing would have to be set up to make that play well with Bootstrap. (I haven't looked into this at all, so maybe it's easy... or maybe not). But I think if we can solve that detail, as you say, the rest should be pretty straightforward.

**Comment by demiankatz** [comment]
Hello again. Chris has just made some changes in the master branch to solve the duplicate ID problem. There are currently some problems with focusing the search box on page load, but these are not related to the current refactoring but rather have to do with the Bootstrap typeahead library. We're investigating a solution, but that doesn't need to hold back completion of this pull request.

Would you like to rebase this PR on top of the current master so that you get the commit history to your liking, and then re-test the validation? I think we may be in good shape once that is done. Thanks again for taking the time to work on this and identify problems!

**Comment by samueloph** [comment]
Thanks @demiankatz.

I will definitely do that.

I sure hope to keep on contributing with the project (I'm still going to work on that daterange's facet config).

In the next 20 hours[max] you should have a new clean PR with the fixes.

**Comment by demiankatz** [comment]
Wonderful! I'll look forward to it!

**Comment by samueloph** [comment]
Ok, the clean PR is ready, I'm closing this one.

**Pull request closed without merging**
