### PR TITLE
More consistent support of repeating 260/264 fields.

### PR DESCRIPTION
**Pull request by demiankatz**
This is an alternate, more minimalistic approach to the problem described by #567.

Tests revealed that repeating subfields were being handled correctly (or at least, in some fashion) for certain subfields of 260, but for no subfields of 264. This PR ensures that all data in all repeating subfields is used one way or another. Specifically:

- Repeating dates are indexed separately (to allow date searches for all applicable years) but are concatenated together for display purposes.
- Repeating publishers and publication places are concatenated together both at index and at display time.

Other notes:

- This currently assumes that the MARC records include punctuation between repeating fields, so no additional punctuation is added by the code. Whether this is true will depend on local MARC practices, so some customizations may be needed to inject separators. It would probably be helpful to make this configurable. For now I took this approach because it was consistent with what the 260 field was already doing, and it is very simple.
- There was some discussion on #567 about whether 264 should trump 260 or continue to be combined with it. For now I have opted not to change this behavior, but I am open to further comment on the subject (and have inquired of some metadata specialists to collect more input).

This is not necessarily intended to fully replace #567 and I am open to an ultimate solution that uses parts of each. I just wanted to capture and document my own work in this area so we can easily make comparisons as we continue the discussion.

### CODE REVIEW

**Comment by witzigs** [comment]
Hi Demian

Thanks for your work.
This seems like a good approach to me. 260 and 264 are treated the same way, which they should be. 

For our use case it would be nice to have a separator between the repeating subfields as we don't have ISBD punctuation in our data. But as we have been doing just fine with 260 as is, this is absolutely alright for now.

**Comment by demiankatz** [comment]
@witzigs, thank you for taking a look at this. Since you seem happy with the basic approach, I have ported my BeanShell script changes into the SolrMarc Java code so they can be incorporated into the next SolrMarc release, and I have also added some configuration settings that should give you the ability to inject separators and force 264 to trump 260. Hopefully this will meet all of your needs while also being conservatively backward-compatible by default.

Please let me know if this all works for you -- I'll merge to master in the near future unless you have any objections. Thanks again for your help with this issue!

**Comment by witzigs** [comment]
This works very well for me - the configurable separator really improves the display of the publication info.
Thanks a lot!

**Comment by demiankatz** [comment]
Thanks for reviewing -- I have merged this to master.

**Pull request merged**
