### PR TITLE
Replace Linkify by Url highlight

### PR DESCRIPTION
**Pull request by vstelmakh**
Suggestion to replace Linkify by [Url highlight](https://github.com/vstelmakh/url-highlight) library. It covers more cases and properly works with html escaped input. See comparison table bellow.

### `Linkify` vs `Url highlight` comparison
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | Linkify                                                                  | Url highlight                                                |
|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------|--------------------------------------------------------------|
| Supported schemes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | ![](https://via.placeholder.com/10/d8c254/000000?text=+) http(s), ftp(s) | ![](https://via.placeholder.com/10/439e0a/000000?text=+) All |
| Simple url <br> <details>   <summary>Details</summary>   Simple url with scheme: `http://example.com`   <ul>     <li>Linkify: `<a href="http://example.com">http://example.com</a>`</li>     <li>Url highlight: `<a href="http://example.com">http://example.com</a>`</li>   </ul> </details>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | ![](https://via.placeholder.com/10/439e0a/000000?text=+) Yes             | ![](https://via.placeholder.com/10/439e0a/000000?text=+) Yes |
| No scheme <br> <details>   <summary>Details</summary>   Valid domain with no scheme: `example.com`   <ul>       <li>Linkify: `example.com`</li>     <li>Url highlight: `<a href="http://example.com">example.com</a>`</li>   </ul> </details>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | ![](https://via.placeholder.com/10/f03c15/000000?text=+) No              | ![](https://via.placeholder.com/10/439e0a/000000?text=+) Yes |
| No scheme with path <br> <details>   <summary>Details</summary>   Valid domain with no scheme with path: `example.com/path`   <ul>     <li>Linkify: `<a href="http://example.com/path">example.com/path</a>`</li>     <li>Url highlight: `<a href="http://example.com/path">example.com/path</a>`</li>   </ul> </details>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | ![](https://via.placeholder.com/10/439e0a/000000?text=+) Yes             | ![](https://via.placeholder.com/10/439e0a/000000?text=+) Yes |
| Invalid domain <br> <details>   <summary>Details</summary>   Not existing domain but string looks like url: `example.txt/path`   <ul>     <li>Linkify: `<a href="http://example.txt/path">example.txt/path</a>`</li>     <li>Url highlight: `example.txt/path`</li>   </ul> </details>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | ![](https://via.placeholder.com/10/f03c15/000000?text=+) Yes             | ![](https://via.placeholder.com/10/439e0a/000000?text=+) No  |
| Email <br> <details>   <summary>Details</summary>   Generic email: `user@example.com`   <ul>     <li>Linkify: `<a href="mailto:user@example.com">user@example.com</a>`</li>     <li>Url highlight: `<a href="mailto:user@example.com">user@example.com</a>`</li>   </ul> </details>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | ![](https://via.placeholder.com/10/439e0a/000000?text=+) Yes             | ![](https://via.placeholder.com/10/439e0a/000000?text=+) Yes |
| Complex url <br><details>   <summary>Details</summary>   Urls could contain lots of special chars and brackets nesting. Example: `http://elk.example.com/app/kibana#/discover?_g=()&_a=(columns:!(_source),index:'deve-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'*')),sort:!('@timestamp',desc))`   <ul>     <li>Linkify: `<a href="http://elk.example.com/app/kibana#/discover?_g=()&_a=">http://elk.example.com/app/kibana#/discover?_g=()&_a=</a>(columns:!(_source),index:'deve-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'*')),sort:!('@timestamp',desc))`</li>     <li>Url highlight: `<a href="http://elk.example.com/app/kibana#/discover?_g=()&_a=(columns:!(_source),index:'deve-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'*')),sort:!('@timestamp',desc))">http://elk.example.com/app/kibana#/discover?_g=()&_a=(columns:!(_source),index:'deve-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'*')),sort:!('@timestamp',desc))</a>`</li>   </ul> </details> | ![](https://via.placeholder.com/10/f03c15/000000?text=+) No              | ![](https://via.placeholder.com/10/439e0a/000000?text=+) Yes |
| Url with userinfo <br> <details>   <summary>Details</summary>   Url could contain basic auth credentials: `http://user:password@example.com`   <ul>     <li>Linkify: `<a href="http://user:<a href="mailto:password@example.com">password@example.com</a>">http://user:<a href="mailto:password@example.com">password@example.com</a></a>`</li>     <li>Url highlight: `<a href="http://user:password@example.com">http://user:password@example.com</a>`</li>   </ul> </details>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | ![](https://via.placeholder.com/10/f03c15/000000?text=+) No              | ![](https://via.placeholder.com/10/439e0a/000000?text=+) Yes |
| Html encoded input <br> <details>   <summary>Details</summary> Escaping html in string: `<b>http://example.com</b>` will result to: `&lt;b&gt;http://example.com&lt;/b&gt;`      <ul>     <li>Linkify: `&lt;b&gt;<a href="http://example.com&lt;/b&gt">http://example.com&lt;/b&gt</a>;`</li>     <li>Url highlight: `&lt;b&gt;<a href="http://example.com">http://example.com</a>&lt;/b&gt;`</li>   </ul> </details>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | ![](https://via.placeholder.com/10/f03c15/000000?text=+) No              | ![](https://via.placeholder.com/10/439e0a/000000?text=+) Yes |

#### Legend
 - ![](https://via.placeholder.com/10/439e0a/000000?text=+) - Proper match  
 - ![](https://via.placeholder.com/10/d8c254/000000?text=+) - Partial match  
 - ![](https://via.placeholder.com/10/f03c15/000000?text=+) - Invalid match

TODO
- [ ] Finish upgrading to UrlHighlight 3.0 (currently, this PR is broken)

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks for sharing this, @vstelmakh! I'm requesting a review from @EreMaijala, since I believe that he implemented the original linkify integration and might have stronger opinions about this than I do.

In addition to whatever @EreMaijala has to say, my initial thoughts are these:

1.) Rather than building lots of objects in Linkify::__invoke, it would probably be better to use a factory and inject dependencies into the helper. This would make it easier to extend/override the various components, as well as potentially reduce redundant object-building.

2.) Since LinkifyHighlighter is a support class and not a view helper, I don't think it necessarily belongs in the VuFind\View\Helper\Root namespace. Perhaps it should go in VuFind\Highlighter or VuFind\UrlHighlight\Highlighter instead.

If you agree with either or both of these but don't have time to implement, let me know and I'll be happy to help!

**Review by EreMaijala — COMMENTED** [review]
I appreciate the effort that you've put in the library, @vstelmakh. That said, our use case for linkifying is pretty limited, and the less aggressive linking by Linkify might actually be preferable. Since there's, as far as I can see, no current issue that this change fixes, I'd prefer to leave things as is.

**Comment by demiankatz** [comment]
Thanks for the input, @EreMaijala. I'm inclined to agree that less aggressive is preferable (for example, the "no scheme" linking seems like it has some potential for false positive links). Some of the edge case bug fixes would be nice to have, but are unlikely to actually come up in our existing (very limited) use cases.

In any case, since this introduces a fairly significant change to internals, I wouldn't want to consider it for merging before VuFind 8.0, which is some way off. If @vstelmakh still wants to move forward, perhaps the best approach would be to implement this as an [optional feature branch](https://vufind.org/wiki/development:git-branches#feature_branches) so that it's readily available and can be merged into the mainline code in the future if a stronger need arises or if the linkify library (which I notice hasn't been updated since 2017) is officially deprecated.

**Comment by vstelmakh** [comment]
@demiankatz I agree with both:
> ...better to use a factory and inject dependencies into the helper...

and

> LinkifyHighlighter is a support class and not a view helper...

Updated the PR:

1. Created a factory for `Linkify`.

2. For me, `VuFind\Highlighter` looks too generic, so decided to move `LinkifyHighlighter` to `VuFind\UrlHighlight` and renamed to `VuFindHighlighter`.

Regarding:
> the "no scheme" linking seems like it has some potential for false positive links

It has less potential for false positive that Linkify, as Url highlight check matches without shceme by [IANA's root zone list](https://www.iana.org/domains/root/db).

@EreMaijala If less aggressive matching is required. There is a way to configure how agressive matching should be, by creating custom [Validator](https://github.com/vstelmakh/url-highlight/blob/v2.2.0/README.md#validator) implementing [ValidatorInterface](https://github.com/vstelmakh/url-highlight/blob/v2.2.0/src/Validator/ValidatorInterface.php).

Anyway, this PR is a suggestion, you could keep it as optional feature branch or reject it. Any of your decition would be fine for me.

**Comment by demiankatz** [comment]
Thanks again for the continued work, @vstelmakh. I've given this a milestone of 8.0 so we can make a decision closer to that release. In the meantime, I welcome discussion/feedback from others here!

**Comment by demiankatz** [comment]
My apologies for the long silence, @vstelmakh -- it has been very busy, and I haven't been able to give this the attention it deserves.

With the VuFind 8.0 release around the corner, I finally took a closer look and found that there is now a new major release of UrlHighlight, and it is not compatible with the work in progress here. I've merged in the latest dev branch and updated the dependency, but I was not able to quickly determine how to fix the incompatible code... thus, this PR is currently in a broken state, and I have added a TODO at the top to indicate that.

Given that the linkify project has not moved since 2017, and UrlHighlight still appears to be active, I think there is a case for making this replacement... but given the short time remaining before the VuFind 8 release, I don't think I can do this properly in time. Thus, I have bumped the milestone to 9.0 for now.

@EreMaijala, do you have any thoughts on this?

**Comment by vstelmakh** [comment]
Hello people. It's been a while. I pushed an update for `VuFind\View\Helper\Root\Linkify` related classes to correspond UrlHighlight v3 interaface. Tests are also updated and should be green now.

So it's not blocked now. But it's up to you if you want to include this to `8.0` :blush:

**Comment by demiankatz** [comment]
Thanks for taking the time, @vstelmakh, I really appreciate it! I'll see if I can find time to give this a closer look in the coming week.

**Review by EreMaijala — APPROVED** [review]
I reviewed my stance, and came to agree that it makes sense to switch away from unmaintained code. And as it is it's unlikely to cause issues for our use cases anyway.

**Comment by demiankatz** [comment]
Thanks again, @vstelmakh and @EreMaijala -- looks like we can get this into VuFind 8.0 after all. I appreciate the efforts! I've made a few minor adjustments to fix bugs (there was an error on composer.json) and to bring this more in line with VuFind styles/conventions (eliminating explicit invoke calls, switching from private to protected for greater extensibility), and I've tested that it still behaves as expected. Merging now!

**Pull request merged**
