### PR TITLE
JS Objects and Events

### PR DESCRIPTION
**Pull request by crhallberg**
This is a project I started to see how much the code could be simplified by converting other js files into objects like the new Lightbox. I've updated Lightbox to broadcast events (to be picked up by browser-native event handlers) and I've converted cart.js into Cart, the object.

Lightbox events: initialized, ready (content loaded), close

I had to share because I have a crazy bias that performance increased. I'd like to know what you all think.

- [x] Lightbox object (already finished)
- [x] Cart object
- [x] Lightbox 3.0
- [x] Login events
- [ ] Testing

### CODE REVIEW

**Comment by crhallberg** [comment]
Waiting for a large theme update, to be timed with the release of Bootstrap 4, regardless of whether we adopt it or not.

**Comment by crhallberg** [comment]
Merged in the newest Lightbox, needs a lot more testing.

**Comment by crhallberg** [comment]
Working on a new new Lightbox.

**Comment by crhallberg** [comment]
I've decided this pull request is a unnecessary change that may affect performance more than it helps syntactically. If anyone disagrees, please comment.

**Comment by demiankatz** [comment]
No objections here; I think there may be advantages to doing some work in this direction, but (if memory serves) this has grown somewhat out of date and would probably need to be partially redone anyway. Might as well wait until the refactoring is driven by a more tangible use case.

**Pull request closed without merging**
