### PR TITLE
Fixed facet memory to not mess with the classes of the collapsible fa…

### PR DESCRIPTION
**Pull request by EreMaijala**
…cets.

Facet memory still didn't work properly for hierarchical facets. show.bs.collapse wasn't fired because the 'in' class was already added to the item. This fixes also a potential problem where any newly added classes would have been overwritten from the session storage.

All in all I can't see the point in saving the classes in the session storage when a boolean value would be enough, but I didn't want to change it now since it would have been disruptive.

### CODE REVIEW

**Comment by demiankatz** [comment]
I'm trying to reproduce the bug in order to better understand the problem, but I'm not seeing any problems. If I turn on a hierarchical facet and collapse or uncollapse the facet section and then refresh the page, it behaves as I expect it to. Perhaps my example data is not complex enough, or I'm not using the right default state or other advanced configuration settings to see the problem.... could you provide some more details so I can see your scenario in action?

Also, regarding saving the classes instead of a boolean, that was definitely a conscious decision, but I think it's worth revisiting. @crhallberg probably remembers the reasoning for this better than I do -- I think it was intended to be the simplest way to deal with all possible default collapse states in facets.ini, but the more I think about it, the more I am unable to see how storing classes and storing boolean collapse states are actually functionally different. I might be missing something important, though!

**Comment by EreMaijala** [comment]
Steps to reproduce:

1.) Set a hierarchical facet to be collapsed by default.
2.) Do a search
3.) Expand the collapsed facet
4.) Do another search
5.) Observe that the triangle icon on the facet name points up indicating the facet is open, but the content doesn't display. You'll also need to click the facet name twice to get it to load the contents.

Okay, my first point Is not critical since it's only in session storage, so not permanent, but if you store the classes and restore them from the storage, any recent changes in the classes specified by the template would be overwritten by the restore from storage. That affects at least developers (think of the confusion if a facet unexpectedly loses the classes it was given in the HTML). But more importantly, you must not directly overwrite the classes of an element that a component uses, as happened here again (#811 was the initial attempt at fixing this), because it can completely mess up its state.

**Comment by EreMaijala** [comment]
Both are fine for me, feel free to adjust to your liking :) I added you as a collaborator so you push to this branch if that's easiest for you.

**Comment by crhallberg** [comment]
The collapse animation is the only thing bothering me about this. I'm looking into skipping it.

**Comment by EreMaijala** [comment]
I've committed a fix. This is a bit kludgy, but at least it's a documented way to disable transitions in Bootstrap (see http://getbootstrap.com/javascript/#transitions). 

There is a request and a patch for proper support for animate option for Bootstrap 4 (see https://github.com/twbs/bootstrap/issues/18127), but I don't know what the changes of getting that merged are since it's been sitting there since the end of last year.

**Comment by crhallberg** [comment]
Great find!

**Comment by demiankatz** [comment]
Looks good to me. Thanks, everyone!

**Pull request merged**
