### PR TITLE
first pass at browse offset and match highlighting

### PR DESCRIPTION
**Pull request by hackmastera**
Note there are TODOs (most notably the config file piece). 

Seeking input on:
* how to deal with the method signature of alphabeticBrowse in VuFindSearch/Backend/Solr/Backend
* css styling (currently a blue box but if nothing else the color should change)
* is there a better way to figure out whether the result solr returns is an exact match? I'm actually fine with the rough comparison (uppercase, strip spaces) but if there's any easy and more precise way to tell I'd use that.

### CODE REVIEW

**Comment by hackmastera** [comment]
Hey Demian! Mark and I are done going back and forth over the highlighting support and we're ready for that branch (https://github.com/vufind-org/vufind-browse-handler/tree/highlighting-support) to be merged into master and pulled into vufind. Once that's done I will pull the changes and I can then push my current code (which uses his updated API) to this PR.

**Comment by demiankatz** [comment]
Thanks for the update. I believe I've merged everything in now -- let me know if you run into any problems.

**Comment by hackmastera** [comment]
The merge caused conflicts and I thought it would be easier to squash it all into one commit on top of current master. I've created a new branch and I'll submit a PR from there. Hope that works for you; I'm not really sure there is an ideal way to deal with this situation (when time has elapsed and a lot has happened on master).

**Comment by demiankatz** [comment]
That's totally fine -- I'll just mention #289 here in case anyone wants to follow the thread to the replacement PR.

**Pull request closed without merging**
