### PR TITLE
Make Voyager username field configurable.

### PR DESCRIPTION
**Pull request by demiankatz**
- Allows login with institution ID instead of barcode.
- Includes some variable renaming and null coalescing for improved style/clarity.

### CODE REVIEW

**Comment by demiankatz** [comment]
@EreMaijala, I have a need to connect to Voyager using institution ID instead of barcode, and this PR is designed to make that a configurable option. It seems to work for me, but I'd appreciate a double-check to be sure I'm not breaking anything on your end. Thanks!

**Review by EreMaijala — APPROVED** [review]
As far as I can see this still requires the patron to have a barcode. If that's intentional, it looks all good to me.

**Comment by demiankatz** [comment]
Thanks, @EreMaijala, that is intentional -- for our use case, we want to look up users by institution ID (so their user ID never changes, even if they lose their library card), but we still want to filter to only accept users with active barcodes. It's possible there could be a use case elsewhere that would not want barcodes at all, but my guess is that everyone is going to stop using Voyager before it comes up. :-)

**Comment by EreMaijala** [comment]
@demiankatz Note that patronLogin returns PATRON_ID in the id field and it's stored in cat_id column for the very purpose of matching an existing account even if the barcode changes. :)

**Comment by demiankatz** [comment]
@EreMaijala, good point, but in our situation, we load the barcode from LDAP and use it to auto-log-in the user to Voyager... and sometimes there are synchronization problems that prevent a proper match, if the active directory gets updated with a new barcode before the data is pushed over to Voyager.

**Comment by EreMaijala** [comment]
@demiankatz Ok, that makes sense.

**Pull request merged**
