### PR TITLE
Hide values of any facet for displaying

### PR DESCRIPTION
**Pull request by ndege**
Hi Demain,

I would like to propose you my second task to manipulate facets as discussed at VuFind mailing list a while ago. Purpose is hiding single values of facets. Thanks in advance for inspecting.

### CODE REVIEW

**Comment by demiankatz** [comment]
This looks good! A few comments before we merge, though:

1.) I made minor adjustments to the .ini comments in an effort to make this slightly more clear. Feel free to adjust further if you dislike my changes.

2.) I believe if you change `foreach ($value as $config_value) {` to `foreach ((array)$value as $config_value) {` then you will cover the case where somebody puts a value in the [HideFacetValue] section without adding array brackets to the key. Might be worthwhile for a little added flexibility.

3.) I would move the configuration retrieval logic out of the HideFacetValueListener and into the AbstractSolrBackendFactory. There is no reason for the listener to know about service locators and configurations, so it becomes more flexible if we move that knowledge up a level. What I'd recommend doing is to have getHideFacetValueListener() look up the configuration. If the HideFacetValue section is not empty, then that value gets passed to the HideFacetValueListener constructor (since that's the only thing the listener actually needs). If the value is empty, then getHideFacetValueListener() could return false, and the calling code could bypass attaching the listener. There's no point in hooking up a listener that we know in advance won't do anything.

I'm happy to help with these things if you don't have time; let me know what you think! Thanks for sharing!

**Comment by demiankatz** [comment]
I finally found some time to give this a closer look. I've fixed the issue mentioned above and manually merged it to master. Thanks again for sharing!

**Comment by ndege** [comment]
Hi Demian, thanks for fixing and pushing it to master :) Frank

**Comment by demiankatz** [comment]
For some reason, this code did not work correctly in VuFind 2.5.x; I'm honestly not sure how it ever worked, though it certainly seems like I tested it when working on this PR.

In any case, it is now working again (and perhaps a little simplified); see: https://github.com/vufind-org/vufind/commit/dc44c3e3b78396739d8a92b7330559db02228686

Apologies for any inconvenience caused by the broken code -- wish I knew how that slipped through the cracks!

**Comment by ndege** [comment]
Hi Demian, much thanks for fixing it and write a test. I'm even sure it worked before and André gives a solid glance on functionality before merging a issue in our local master.  Hope it works all users fine now.

**Comment by jochen-lienhard** [comment]
Thanks @demiankatz. Did you add it as a bug fix to the release-2.5?

**Comment by demiankatz** [comment]
Because the interface of NamedList changes in the fix, and since I'm not expecting another release in the 2.5.x series, I opted to leave this until release 3.0. However, if you need to apply the fix to your local instance of 2.5.x, you should be able to "git cherry-pick" the commit without any trouble.

**Pull request closed without merging**
