### PR TITLE
Pullrequest foundation5-theme on branch release-2.4

### PR DESCRIPTION
**Pull request by lahmann**
As suggested by Demian (https://github.com/vufind-org/vufind/pull/379#issuecomment-104278976) opening this pull request with code base branch release-2.4.

### CODE REVIEW

**Comment by crhallberg** [comment]
Do you have (a) testing routine(s) which you employ to test all features?

We do have some integration tests using Mink, but unfortunately they are far from complete. I've run into a lot of problems and technical restrictions trying to implement tests for more advanced features like Lightboxes.

**Comment by ckaz** [comment]
@Chris: Thanks. Switched on tabbed search. Thought it would require more.

**Comment by demiankatz** [comment]
Looks like the Travis build is failing due to a long line in your layout view helper; hopefully that's easy to fix!

**Comment by ckaz** [comment]
Here's a few notes on 3c264cd:
* You are absolutely right about the vendor directories
* The two top-bars concept is great. I had to change the code in searchbox-topbar.phtml so the shards are displayed correctly. (lines 58ff)
* The height issue for the top-bar was our mistake. Height should be left untouched for all sizes up to 720px wide. If we add "auto" to default, the toggle won't work. (Foundation adds "expanded" to the top-bar when toggled, which has "height=auto".) This way, our shard selectors are visible too. I'll see to the correct inclusion in SCSS over the next few days.
* I've fixed the similar items carousel to something workable.
* I was getting an error in SideFacets.phtml which we fixed by changing lines 202ff 
* I'll try and stick to your coding preference (spaces), however, some of our files were coded using tabs so I might miss the occasional tabs to spaces conversion
* We keep working on the same issues at times (typeahead, top-bar) which means complex merges. Do you have a preference, such as, we wait until you're done, or the other way round or are you comfortable with the current procedure?
* Do you have a coding preference (spaces over tabs, right?)? I'll use spaces too, then.
Here's a few notes on 3c264cd:
* You are absolutely right about the vendor directories
* The two top-bars concept is great. I had to change the code in searchbox-topbar.phtml so the shards are displayed correctly. (lines 58ff)
* The height issue for the top-bar was our mistake. Height should be left untouched for all sizes up to 720px wide. If we add "auto" to default, the toggle won't work. (Foundation adds "expanded" to the top-bar when toggled, which has "height=auto".) This way, our shard selectors are visible too. I'll see to the correct inclusion in SCSS over the next few days.
* I've fixed the similar items carousel to something workable.
* I was getting an error in SideFacets.phtml which we fixed by changing lines 202ff 
* I'll try and stick to your coding preferences (spaces), however, some of our files were coded using tabs so I might miss the occasional tabs to spaces conversion
* I'd love to use this as basis for further fixes which I noticed are necessary while doing the merge. These include the tranfer of other list-groups, date slider and more. In the course of this, I also need to make the jump to using SASS which I was just poking my nose into. This will take a couple of days I bet, so please bear with us. (Chris: Great many thanks for doing the migration for us! I had scheduled this for much later. I keep pressing the mental buy-you-a-beer-button.). 

@Damian: The overlong-line issue was fixed. My ignorance!

**Comment by crhallberg** [comment]
6. It's not a problem during development, we'll clean it all up before we merge this in.
7. I just tackled a few larger issues, it's my fault for not coordinating better. The changes were also complex, sorry about that again. I'll follow your lead, is there anything in particular you'd like me to look at or handle?
15. I have a script to compile SCSS that I run from the vufind root, if you're interested. I'm very impressed by how much SCSS has improved over the past year, looking at it last summer I found it lacking somehow. [sassc](https://github.com/sass/sassc) in particular is very cool.

**Comment by ckaz** [comment]
Great. 
Re: 2. Thanks for your kind offer. Nothing in particular that comes to mind, unless you've noticed any other major blunders. (See also 1 and 2 below). My plan is to follow your path cleaning up the code -- thanks for the notes in the CSS, btw.! And I'm sure I'll need to ask you for help soonish again.
Re: 3. I'm totally new to SASS but I'm worming my way in. It'll be a few days yet, but I'd sure love to run your compile script once I'll arrive at that stage. Thanks for offering it!

Here's my current steps: 
1. I've been replacing the "hidden" classes with "hide", which I gather is in your meaning of a more consistent Foundation-typical styling.
2. I've also begun replacing the list-group and list-group-item styles. I'll continue with this as I go along.
3. Unfortunately, we don't have any testing routines and I frequently arrive at points where I have no clue how the feature will look like (vudl, for example, or the facetOR feature triggered in common.js line 381 and SideFacets.phtml). That is, I'm testing per hand.
4. In additon to bugfixes, my next steps will be to get the hand-coded CSS changes (default and the old media queries) from the merge reflected in the SCSS files so we can get started using SASS. I think that will be a good hands-on learing experience, too.

My best!

**Comment by ckaz** [comment]
Hi Chris, 
I've finished the initial default.scss rewrite, including the former media queries, and had a default.css compiled which works very well. However, as a beginner, I am currently using the normal ruby compiler to watch and compile my files.Will this clash with your use of libsass/sassc? For this, I'll need some more times to get my head around.
My best, Claas

**Comment by crhallberg** [comment]
It shouldn't class. Where are you compiling to?

- Chris

**Comment by crhallberg** [comment]
Sorry, I updated from my phone. The compile methods shouldn't clash. Ruby and sassc cli should compile the same. Where are you compiling to?

**Comment by ckaz** [comment]
Hi Chris, 
I'm compiling from the scss directory to the css directory -- e.g. scss/default.scss to css/default.css.
It seems I can integrate libsass into our fav editor, phpstorm, and will give it a shot today.
Meanwhile, I'm working on removing all the list-group and list-group-item classes from the code and replacing them with something Foundation. Cheers!

**Comment by ckaz** [comment]
Hi Chris, just got libsass integrated using grunt-sass, which in turn uses node-sass etc. Much faster indeed and lots of fun even for entire folders. Thanks for the hint!

**Comment by crhallberg** [comment]
Sure thing!

**Comment by lahmann** [comment]
We are currently rebasing this pull request on vufind-org/master and will open a new pull request for the foundation5 feature branch when we are done.
Thanks a lot so far for your contributions, Chris!

**Pull request closed without merging**
