### PR TITLE
Fix Shibboleth Factory.

### PR DESCRIPTION
**Pull request by demiankatz**
- Fix incorrect case-sensitive config filename
- Fix outdated config service name

### CODE REVIEW

**Comment by demiankatz** [comment]
@xrosecky, I noticed some problems while reviewing code, and I think a bug slipped through during our work on #1617. Do you mind reviewing these fixes and letting me know if you have any concerns before I merge them? Thanks!

**Comment by demiankatz** [comment]
(If you think it would be better to rename Shibboleth.ini to shibboleth.ini instead of changing the constant in the factory, that's an option too!)

**Comment by xrosecky** [comment]
@demiankatz I have no objections.

**Comment by demiankatz** [comment]
Thanks, @xrosecky!

**Pull request merged**
