### PR TITLE
add autocomplete to form fields

### PR DESCRIPTION
**Pull request by elsenhans**
With this pull request the attribute autocomplete is added to input fields like password or username. 
Autocomplete improves the accessibility. It allows the browser to predict the value. When a user starts to type in a field, the browser should display options to fill in the field, based on earlier typed values.

### CODE REVIEW

**Review by crhallberg — APPROVED** [review]
Love this! Thanks so much! It looks like there are some test and merge conflicts but once those are resolved, this is good for me!

**Review by demiankatz — CHANGES_REQUESTED** [review]
Thanks for the contribution, @elsenhans! Given @crhallberg's enthusiastic approval, I tried to rebase this to the release-9.0 branch so we could include this improvement in time for the 9.0 release. Unfortunately, though, there are conflicts which need to be resolved before this can be merged. I strongly suspect this was caused by #2830 -- which removes trailing slashes from HTML void elements like input (i.e. `<input />` was changed to `<input>`).

Do you have time to resolve these conflicts? If so, we might still be able to get this merged for the new release. Otherwise, I'll be happy to help post-release, when I have a little more free time.

Either way, thanks again for the contribution, and sorry for the inconvenience!

**Comment by elsenhans** [comment]
Thanks for the positive feedback @crhallberg @demiankatz !
I did resolve the conflicts and hope the tests will pass through.

**Review by EreMaijala — APPROVED** [review]
Great stuff!

**Review by demiankatz — APPROVED** [review]
Since everyone is so enthusiastic about this, I've gone ahead and backported the changes to the release-9.0 branch so they can be included in release 9.0 next week. Thanks again, @elsenhans!

**Comment by elsenhans** [comment]
Thank you very much for your feedback and support @demiankatz !
I am glad the adjustments are desired :)

**Pull request closed without merging**
