### PR TITLE
Keyboard Shortcuts in detail view

### PR DESCRIPTION
**Pull request by powerriegel**
One can navigate using the left and right arrow keys. Press ctrl + arrow up to get back to result list.

### CODE REVIEW

**Comment by demiankatz** [comment]
I'm going to wait for @crhallberg to comment on this before taking any action -- since he's in the middle of some Javascript refactoring, his input would be helpful to see where this fits in the long-term plan.

**Comment by powerriegel** [comment]
No worries! It's just a really nice feature. Librarians love it, as its much faster than pointing the arrows. 

You're of course free to move it to another JS location during refactoring. 

My first intention was to activate this on result list, too. But there's one drawback: You can't use left/right arrow keys to move the page inside the browser. Maybe handicapped people use this? That's why I use it on record page only.

**Comment by crhallberg** [comment]
I only have a slight concern that the `e.preventDefault()`s are going to mess with accessibility. Also, please put `break`s at the end of your switch cases.

**Comment by crhallberg** [comment]
Doing some research and looking more carefully at where you places the `preventDefault()`s it shouldn't be a problem.

**Comment by powerriegel** [comment]
Ok, I fixed these issues and hope everything is in place now :-)

**Comment by crhallberg** [comment]
Looks good! Thank you very much!

**Pull request merged**
