### PR TITLE
Configure encryption algorithms

### PR DESCRIPTION
**Pull request by crhallberg**
Configure which algorithm is used to encrypt stored passwords.

PS. Sorry this took so long, I have configuration problems with my ILS.

### CODE REVIEW

**Comment by demiankatz** [comment]
I'm guessing that this doesn't work if a user changes algorithm after the database is already established, correct? Do we need to add a field to track algorithm so if the user reconfigures, we can still read (and then rewrite) old data?

**Comment by crhallberg** [comment]
Is it insecure to put the name of the algorithm in the database?

**Comment by EreMaijala** [comment]
Thanks Chris, I'm going to cherry-pick and test this today, just in time for launch tomorrow.

Small nit: typo in config.ini: symmtrical

Regarding Demian's question: Changing the algorithm is no different than setting up an encryption key (currently just adding an encryption key in the config will make the existing unencrypted passwords unreadable). I'd just add a comment regarding that. A command-line utility to update all passwords from one algorithm (or plain text) to another would be nice and would mostly alleviate the problem. I think that storing the algorithm in the database unnecessarily gives out a piece of information.

**Comment by crhallberg** [comment]
I agree that a command-line tool that takes two hashes as parameters would be a sufficient tool.

**Comment by demiankatz** [comment]
Sounds reasonable to me. A command line tool and documentation in the .ini file on how/when/why to use it would definitely make sense. Perhaps the tool should accept four parameters: old method, old salt, new method, new salt.

**Comment by crhallberg** [comment]
Any feedback on my command line tool? I tested it, but maybe we should write a unit test for it.

**Comment by demiankatz** [comment]
I'll try to find time to play with the command line tool and offer feedback when I'm a bit more caught up. I'm guessing this PR can probably wait until after release 3.0, so it won't be my top priority. Two related suggestions in the meantime, though: now that you can run all CLI tools through public/index.php, I've stopped bothering to create wrapper scripts in the util folder (and may eventually do away with the existing wrapper scripts). Thus, rather than bothering to create a new one for this tool, I'd instead suggest adding a line to the VuFindConsole's Module.php (see https://github.com/vufind-org/vufind/blob/master/module/VuFindConsole/Module.php#L77) to expand the list of available commands.

**Comment by demiankatz** [comment]
I think I found a problem with the command line tool: the usage note suggests that you can use "none" for the old hash method, like:

    php public/index.php util switch_db_hash none blowfish:mykey

However, this doesn't work, because the validation routine expects "none" to include a colon. Am I misinterpreting the usage note, or is this a bug?

**Comment by crhallberg** [comment]
It's a bug, looking into it now.

**Pull request merged**
