### PR TITLE
Advanced search templates

### PR DESCRIPTION
**Pull request by crhallberg**
Remix of the advanced search with script templates.

Also added a few new styles and cleaned up some syntax.

- [ ] Docs on how to make templates

### CODE REVIEW

**Comment by demiankatz** [comment]
We should make sure we remember to resolve VUFIND-299 (advanced search requires Javascript) when this is resolved thanks to the non-JS support here.

**Comment by demiankatz** [comment]
For the moment, though, something is not right. Try this:

1. Go to advanced search
2. Enter "foo" in the first field of the first group
3. Click "Add search group"
4. Enter "bar" in the first field of the second group
5. Click find

Fatal error: Unknown or invalid boolean operator.

I wonder if it would be a good idea to spend some time writing integration tests to put the advanced search form through its paces so that we can then run the same tests against the refactored code and see what happens....

**Comment by crhallberg** [comment]
I misplaced a name attr. Fixed.

**Comment by demiankatz** [comment]
Thanks for that!

Editing an existing search also seems to be broken. Repeat the steps from my previous comment. Now, the search succeeds, but if you click the "Edit this Advanced Search" link under the `Your search terms : "(All Fields:foo) AND (All Fields:bar)"` text, the form doesn't correctly repopulate your original form entries.

Also, a side note that we ought to fix in master before the 2.4 release: the search controls for advanced searches in bootstrap3 and bootprint3 are all run together.

In Blueprint, you get:

`Edit this Advanced Search | Start a new Advanced Search | Start a new Basic Search `

But in Bootstrap3/Bootprint3, you get:

` Edit this Advanced Search Start a new Advanced Search Start a new Basic Search `

I think the separators should be reintroduced for readability.

**Comment by demiankatz** [comment]
Another unrelated problem: I thought there was a <noscript> tag now that was supposed to make this work (at least partially) with Javascript disabled... but if so, that doesn't seem to be working for me right now. Without Javascript, there are no form fields to fill in when I try to start a new advanced search.

**Comment by demiankatz** [comment]
Chris,

Something isn't quite right with the EDS advanced search here. I tried:

<pre>
        [ dime novels ] in [ All Fields ]
[ AND ] [ western     ] in [ Abstract ]
</pre>

...this works fine in master, but in adv-search-templates, it fails with an "invalid boolean" error.

**Comment by demiankatz** [comment]
Thanks, Chris, this is definitely improving. However, I notice that the no-JS version of the EDS advanced search is missing the boolean drop-down in front of the search box, and submitting this version of the form causes boolean operators to be totally missing from the query. Is there a way to bring these back in no-JS context without causing major code disruption? I don't want to overcomplicate things, but if it's easy, we should fix it.

Similarly, I notice that editing an existing search does not work in no-JS mode. If this is a technical limitation, then perhaps we should just add a `<noscript>[please enable javascript to restore your previous search]</noscript>` message. If it's not actually hard to do, we should implement it.

**Comment by demiankatz** [comment]
A couple of issues from the latest round of testing:

1.) If I create a search with more than three groups and then try to edit it with JS disabled, only the first three groups are populated. In practice, this is probably not a very big deal (how many people use that many search groups?) but it might at least be worth putting up an error message indicating that not all data could be reloaded without Javascript (to cover our bases).

2.) There seems to be a problem with logic related to counting search groups. You can delete all search groups now (VuFind should prevent you from deleting the last one, if only one is left) and the "match: all/any groups" control ALWAYS shows up, but it should be hidden when only one group is active.

**Comment by demiankatz** [comment]
Problem number two there is a perfect candidate for an integration test, if only we could implement one successfully!

**Comment by demiankatz** [comment]
New glitch: when you click "Add Search Field" it copies the content of the top box within the search group. New field should be empty.

**Comment by demiankatz** [comment]
Another problem: in non-JS mode, if you have more than three fields in a group for a saved search, only the first three lines load.

**Comment by demiankatz** [comment]
And one last issue for today: the Mink test fails on this branch but succeeds on master:

<pre>
There was 1 failure:

1) VuFindTest\Mink\AdvancedSearchTest::testBootstrapThree
Failed asserting that null is not null.
</pre>

**Comment by crhallberg** [comment]
Tests passed!

**Comment by demiankatz** [comment]
Chris,

We're getting there... but we still have the 3-field limit for non-JS (which, of course, is not a show-stopper if it's hard to fix... just a nice bonus if it's easy).

More importantly, it looks like EDS is giving us the "Unknown or invalid boolean operator" error again, so something must have gotten re-broken.

thanks,
Demian

**Comment by demiankatz** [comment]
Manually merged to master.

**Pull request closed without merging**
