### PR TITLE
Simplify Mink tests with support methods.

### PR DESCRIPTION
**Pull request by demiankatz**
This PR adds and leverages support methods to reduce redundancy in Mink tests; it also streamlines some things, particularly related to AutocompleteTest.

### CODE REVIEW

**Review by EreMaijala — CHANGES_REQUESTED** [review]
I'd take this a bit further and make the $page parameter of `assertAutocompleteValueAndReturnItem` mandatory (and maybe the first parameter?). And get rid of `loadSearchHome` method.

**Comment by demiankatz** [comment]
@EreMaijala, is it possible that you are only looking at the first commit? The second commit renames and moves loadSearchHome and uses it to reduce redundant search home page loading throughout all the tests.

**Comment by EreMaijala** [comment]
@demiankatz It is possible, and indeed what I did.. So loadSearchHome is no longer an issue, but since all tests still need `$page`, I'd rather pass it to `assertAutocompleteValueAndReturnItem` like we do with all support methods in MinkTestCase.

**Comment by demiankatz** [comment]
@EreMaijala, I agree -- working on it now; will push up once I confirm that tests still pass.

**Review by EreMaijala — APPROVED** [review]
Looks good to me now, thanks!

**Pull request merged**
