### PR TITLE
Reduce Bootstrap class reliance

### PR DESCRIPTION
**Pull request by crhallberg**
Relying on Bootstrap classes for the layout of pages makes it more difficult to style because:
1. Changes to layout require changes to template, which creates more work as VuFind updates
1. Some of the Bootstrap classes are very strong and are tedious to override.
1. Having more semantic classes benefit the readability and customization of the style.

Places that can be improved
- [x] Overall layout, layoutClasses hard-coded to col-sm-x
- [x] Advanced search also relies on col-sm-x
- [x] ~~Forms hard-coded with col-sm- widths, [syntax could be simpler](https://github.com/vufind-org/vufind/pull/958/files?diff=split#diff-7dd13a8c84a927401e2d208a421c99b9)~~ #973 
- [x] Standardize btns
- [x] Merge support PRs (order)
    - [x] #973 
    - [x] #976 
    - [x] #978 
         - [x] #974 
    - [x] Test margins on forms
    - [x] Revisit spacing of submit / new / recover links in login dialog box.
    - [x] Global check for remaining col-xx-y classes.
    - [x] Check advanced search alignment
    - [x] Fix layout bug when turning on multiple range controls on Summon and Solr advanced search screens (see #976 for screen shots and discussion).
    - [x] Fix broken "edit favorite" screen
    - [x] Responsive check
    - [x] ~~pull-left pull-right~~ Delayed
    - [x] rtl
    - [x] Fix negative padding oddities in bootprint3 combined search
    - [x] Test AuthorFacet
- [x] Copy changes from Modern Theme (#961 )
- [x] Semantic elements
- [x] LESS comments
- [x] More LESS/SASS variables
- [x] SASS port

### CODE REVIEW

**Comment by crhallberg** [comment]
I would like feedback on whether this [new form layout](https://github.com/crhallberg/vufind/blob/497e218825284ca13661bbbfade592a25c55bb82/themes/bootstrap3/templates/Auth/AbstractBase/loginfields.phtml) is the right way to go. The syntax is much simpler and flexible to customization and having labels above inputs is a rising standard.

image

**Comment by demiankatz** [comment]
Okay, @crhallberg, #976 and #978 are both merged. I haven't ticked the checkboxes here yet, though, because I'm not sure how to resolve all of the merge conflicts; I'll leave that bit to you. Thanks!

**Comment by demiankatz** [comment]
@crhallberg, also note the duplicate warning coming from Codacy; possibly a merge problem with the Gruntfile.

**Comment by demiankatz** [comment]
Split into smaller commits and manually merged to master.

**Pull request closed without merging**
