### PR TITLE
Add some missing Northern Sami translations.

### PR DESCRIPTION
**Pull request by EreMaijala**
@nikopartanen Could you check that this set of translations makes sense in VuFind's context. I left out translations that mention Finna by name, but I couldn't judge if the others are worded in a general way suitable for VuFind. Thanks!

### CODE REVIEW

**Comment by nikopartanen** [comment]
Looks good, I didn't spot anything really Finna-specific now. The ones added now are generic and good messages. 

Looking to the entire file, there are quite many double spaces inside the strings which cannot be intentional. Also `eBook = "E- girji"` should to be `eBook = "E-girji"`.

**Comment by EreMaijala** [comment]
@nikopartanen Thanks! I'll fix the double spaces and eBook translation.

**Review by nikopartanen — APPROVED** [review]
I couldn't find anything clearly specific to only Finna, so I would approve these updates.

**Review by demiankatz — APPROVED** [review]
Thanks, @EreMaijala and @nikopartanen!

**Pull request merged**
