### PR TITLE
Update Sierra.php

### PR DESCRIPTION
**Pull request by joemontibello**
Initializing $barcode. Also checking if $results has rows before trying to fetch the rows.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks for this. For some reason, it appears that this PR has some conflicts with master. Could you resolve those? I also think there will be some style warnings from Travis (though I'm happy to fix those if it's an inconvenience for you).

Also, one functional concern: is it necessary to set the call number to "No call number" or would it be better to use null or an empty string? If we need the English string, we probably ought to hook up a translator... but since none of the other ILS drivers seem to be doing anything equivalient, I'm hoping that perhaps we can get away with a less complex solution.

Thanks again for helping to improve the driver. Let me know if I can do more to help!

**Comment by joemontibello** [comment]
Hi,
I don't see the conflicts or the Travis style stuff on my end. I'm wondering if I need to have write access to the repo in order to address the conflicts?

I'm seeing this message on my pull request:
This branch has conflicts that must be resolved
Only those with write access to this repository can merge pull requests.

If there's another way to merge without having write access, I'm happy to give that a shot. Let me know what my best way forward is.

Take care,
Joe M.

**Comment by demiankatz** [comment]
You would need write access to merge this pull request, but you shouldn't need write access to resolve the conflicts. Try this:

1. Check out the branch that you used to create this PR.
2. Merge in the master branch from the main VuFind repo (you may need to add an "upstream" remote to accomplish this, if you don't already have one -- see https://help.github.com/articles/configuring-a-remote-for-a-fork/ if you are not already familiar with this process).
3. Resolve the conflicts.
4. Push it back up to your branch -- this will automatically update the pull request.

I'm also happy to help with this if you like -- but hopefully it's good practice for future contributions to GitHub projects.

In any case, I'm also interested in your thoughts on the "missing call number" issue -- we'll still need to figure out the best way forward there before we can fully merge this.

Thanks again for your willingness to contribute!

**Comment by joemontibello** [comment]
I think this is all set now - but please let me know if there's anything else I should do on this.

**Comment by demiankatz** [comment]
Wonderful, thanks! I've manually merged this to master to simplify the commit history a bit!

**Comment by joemontibello** [comment]
Hi,

Thanks for this! I thought I had the upstream configured correctly in step 2, but re-doing that step yesterday helped me move past it a bit, and with a bit of fiddling I got through all the Travis stuff.

I agree that this was really good practice for me – thanks for letting me work through it a bit. 

I fully agree with you about the “No call number” thing – leaving it blank will be simpler, and it sounds like it’s more consistent with what the ILS drivers are doing more generally. I think the pull request as submitted initialized the call number to an empty string rather than the English text.

Take care,
Joe Montibello

**Comment by demiankatz** [comment]
No problem -- I appreciate your help with the driver, and I'm glad there were some side benefits for you!

**Pull request closed without merging**
