### PR TITLE
PHP code for dealing with author relators in frontend

### PR DESCRIPTION
**Pull request by lahmann**
Demian, this is the first draft for how I imagine the author relators are being used in the frontend. As you can see the `getDuplicatedAuthors()` got heavily extended in `getDuplicatedAuthorsRoles()` in `SolrDefault.php` but it's not significantly slower than `getDuplicatedAuthors()` (I measured execution time of the method's call in `core.phtml` and `getDuplicatedAuthorsRoles()` added in average 1/10th in time needed). The code was tested by indexing the records in `tests/data/author_relators.mrc`: the current implementation only shows relators in detail-view (core.phtml) (I left the original author-rows in place for comparison).

If you are ok with this implementation 
1.) I would move the code-blocks in `getDeduplicatedAuthorsRoles()` restructuring the result from `getPrimaryAuthors()`, `getSecondaryAuthors()`, `getCorporateAuthor()` into the aforementioned methods
2.) proceed by replacing `getDeduplicatedAuthors()` with `getDeduplicatedAuthorsRoles()` and
3.) adjust the templates accordingly - as the current implementation also works with non-existing relator-terms I would vote for not implementing a config-setting disabling/enabling relator terms.
4.) finally, I would add the relator terms in `config/vufind/author-classification.ini` to the en.ini and de.ini language files

This should finish the reflection of the author relators in PHP code.

What do you think?

### CODE REVIEW

**Comment by lahmann** [comment]
What I forgot: the `default_relator` is hardcoded right now - should we stick with it or make it more flexible?

**Comment by demiankatz** [comment]
A few thoughts/comments:

1. Regarding default_relator, do we actually need this to be a string at all? Could we just set a blank value in the index for these values? Then we don't need to strip anything out or deal with a weird hard-coded string. I imagine it's possible that we need to put something there in the indexer to hold the position in the list (maybe blank strings are dropped), and maybe we had hoped to be able to translate a specific value for default relators.... but if those issues/problems do not exist, eliminating the string seems easier. Sorry if I'm just forgetting something important -- it's been a while!

2. Do we need to introduce a getCorporateAuthorRole method? And for that matter, do we need to change getCorporateAuthor to getCorporateAuthors in case of multiple 710 fields? (Note that while corporate stuff is ignored in the SolrDefault driver, it does have an implementation in the SolrMarc driver). This might be another scenario that we should cover in our sample records if we are not already doing so.

3. It might be nice to create a support method to do the work of formatting the author and role arrays into the final data structure, since you're basically doing the same job two times (and it will be three if you add the corporate roles as suggested above). I think that will make the code a lot more readable.

4. Similarly, perhaps the deduplication functionality can be factored out to a support method (though I realize this is a bit harder since it involves modifying multiple parts of the array as opposed to simply creating a new data structure).

Anyway, let me know what you think about these comments... but it looks like a good start in any case!

**Comment by lahmann** [comment]
Thanks for the comments!

1.) I tested `author.bsh` without the `default_relator` instead passing an empty string - this works, Solr does not remove those empty strings (at least with standard VuFind solrconfig.xml). So, I think it's safe to get rid of the hard coded `default_relator`. Now, the updated `author.bsh` only needs to get included in Solrmarc.

2.) The Marc-corporateAuthor fields (`110`, `710`) are altogether indexed with `author.bsh`. But by doing so they lose their semantic meaning of corporate author (apart from the possibility to check the relator term, but that one is not always given). So in order to display _the_ main corporate author for a record (which, according to the current implementation in SolrMarc.php, isn't entirely the case as simply the first match of field 110 or alternatively 710 will be considered corporate author) `getCorporateAuthor()` reads the Marc-fullrecord. To provide the occasionally available relator term for the corporate author we should also check the Marc-fullrecord (as you suggested via `getCorporateAuthorRole()`) as we only index creative roles according to `author-classification.ini`. Our sample records actually cover such a case and show that especially if we introduce a method `getCorporateAuthors()` non-creative corporate authors would have their relator term missing even if it's avaiable in the Marc-record.
To sum it up: to keep the behaviour consistent we should introduce the methods `getCorporateAuthors()` and `getCorporateAuthorsRoles()`... how to deal with `getCorporateAuthor()` depends on the next issue:

3.) A support method got added (`getAuthorRolesArray($authors, $roles)`)  which will create the new data structure. But now we have to decide if this new data structure should be adapted by `getPrimaryAuthors()` and `getSecondaryAuthors()` - if we do so, this will break e.g. template compatibility as we have to refactor all the result processing of the above mentioned methods in the templates (and of course anywhere else). For consistency reasons and to keep complexity low (only one data structure vs. two competing structures) I think this is the way to go (as mentioned in 2. this should apply to `getCorporateAuthor()` as well, adapting the new data structure).

4.) I refactored the dedup code - it should be more readable now. Same here (as in 3.): right now we have two getDeduplicated*() methods supporting the old and the new author data structure. I think we should go with the new data structure.

Let me know what you think about my comments.

**Comment by demiankatz** [comment]
1.) Good news! I'll get that update into the compiled version of SolrMarc once this PR is merged in.

2.) Do you think it would make sense to add corporate author fields to the Solr index so that we could eliminate the MARC-specific processing? That would enable us to add corporate author information from non-MARC sources more easily (as well as disabling corporate author display from the indexing side of things if so desired). If we're going to change this, we might as well consider changing it all the way -- the fewer hard-coded MARC tags in PHP code, the better, as far as I'm concerned!

3.) We're already breaking template compatibility, so I don't have a problem with making the breaks bigger in the interest of simplifying/consolidating code. However, perhaps we should take a moment to think about the data structure. If I'm reading the code correctly, it's currently "author name => array of roles". I'm inclined to agree that this makes sense, but for the sake of playing devil's advocate, have you thought about "role => array of author names" and/or "array of [author name, role]" as alternative candidates? I think the main way in which this makes a difference is in how the default relator gets handled. Imagine a scenario where the same author appears twice, once with the default (blank) relator, and once with a specific relator. Depending on the data structure, you'll have to deal with this case differently, and your options vary depending on how important it is to capture the fact that a default relator is present. Am I making sense? ;-)

4.) I agree, let's go with the new structure.

5.) Looks like the current Travis failure is related to some style issues that were fixed a long time ago. I guess we haven't merged this branch in a while. Probably safe to ignore them for now; they should go away after we've merged everything together with the latest master.

Thanks again for working on this!

**Comment by lahmann** [comment]
1.) Great!

2.) Yes, I think that would make sense! Indexing Marc 110 and 710 in an `author_corp` field and the relator terms into `author_crop_role` should do it. Do you agree? We should probably also stick with the distinction creative/non-creative roles for corporate authors and leave it up to the indexing-step whether to index also non-creative authors and roles.

3.a) Regarding the compatibility breaks for templates - great!

3.b) Regarding the data structure: so your argument is that by removing the default relator the information that the author was mentioned twice (once without any further explication and once with a relator) will get lost when only the explicit relator will be displayed? If that's the case, I do agree with you, but I can't see how an alternative data structure might help in such a case: even if I do have the blank relator available I would have to pass this (potential) information to the user. This could only succeed in a satisfying way if additional information would be available (e.g. from which Marc field the relator-less author was read). Eventually that would mean we have to index more data or fallback to reading the fullrecord.
Besides the issue of additional information needed for the blank relator, I cannot see how the current data structure is inappropriate for such a scenario: by removing the `!empty($roles[$index])` check in `getAuthorRolesArray()` the blank relator will be stored in the current data structure.
I think the question is rather what to do with the blank relator and as the current templates show authors based on the distinction primary/secondary author a data structure grouping authors by their relators would complicate this output. Of course, if we want to change that output to relator-centered presentation of authors a different data structure would make much more sense, but as we are more likely to show the relators in _addition_ to the author names it makes more sense for me to organize the relators in the current way (`author => [array of roles]`). Or am I missing something?

Let me know what you think!

**Comment by lahmann** [comment]
In any case, I think we need to decide, if we want to somehow indicate the relator-less author appearance in the record.

**Comment by demiankatz** [comment]
2.) Yes, I agree that this approach sounds reasonable... though perhaps I'd use author_corporate/author_corporate_role rather than the abbreviated corp just to be a little more explicit.

3b.) I suppose you are right that the data structure actually doesn't make a real difference with regard to blank author relators... and your justification for the choice of data structure makes sense, and supports my gut feeling that it's the best option.

As you say, we really only have a problem if we need to display something in place of the blank relator -- for example, suppose the same person is author and illustrator of a work, but only an "illustrator" relator is found in the MARC.... it will look like that person is only the illustrator because the blank relator would not display anything, and we don't have enough information to figure out what string to use in its place. However, I think the solution to this problem is not to worry about it in the PHP but rather to address it at index time. Reasonable strings for default relators can be assigned to different MARC fields in a custom marc.properties if there's a need for this -- the mechanism is already there. So perhaps the only remaining question for us is whether blank relator is the best default configuration... and I suspect that it is (though perhaps vulnerable to a few weird edge cases).

So I think that just leave us with this to-do list:

  - [ ] Add the corporate author fields/indexing rules (I assume you'll take care of this)
  - [ ] Update the compiled SolrMarc (I'll do this when the rest is done)
  - [ ] Add translations (perhaps we should create a new CreatorRoles text domain)

Actually, one other question that might be worth considering: should we revisit some of our labels? Is "author" the best word now that we may have multiple types of creators in different contexts?

**Comment by lahmann** [comment]
2.) Sounds good to me - I have started adding the corporate author fields. Fields 110/111 and 710/711 will be indexed in `author_corporate/_role` - it should be good enough for general use to handle corporate bodies and meetings together vs. reflecting the distinction in the index as well - if further distinction is required we always can fallback to the RecordDriver-methods. Plus we should not introduce another secondary corporate field in order to reflect the distinction between main entry fields 110/111 and additional entries 710/711.

Regarding the question whether to revisit our labels I cannot think of a much better alternative to "author". The common ground for all Marc-fields being used (100, 110, 111, 700, 710, 711) are entities, which is in my opinion a too unspecific term. Another possibility would be to distinguish between persons and corporate bodies/meetings but that would also not reflect the creator-aspect if we are not willing to make the labels far more explicit, e.g. creator_person, creator_person2, creator_corporate_role, ...

3.b) I agree with you that we should leave the default_relator issue to the indexing stage - it's easy enough to process a default_relator term in the templates and adjust the display of author information to individual needs.
If the blank default relator is the best choice is hard to say - I cannot think of an edge case where this could cause problems. Still, in general it might be better to be explicit just to make sure that blank marc-relator-field content is not treated the same as no content which could be done by using an uncommon identifier like `default_relator` but than again one can easily do so by adjusting settings in marc_local.properties.

If you agree with me handling corporate bodies and meetings the same I would start updating all the methods and templates regarding the author fields and add translations.

**Comment by demiankatz** [comment]
André,

Sounds good to me -- I'm comfortable with merging 110/111 and 710/711 for the purposes of VuFind indexing. As you say, these can be easily separated by somebody who needs to make the distinction, but most users will probably not mind.

Regarding the label issue, perhaps the answer to this will become more obvious when the work is complete and we look at the interface. Probably worth discussing on the next dev call (along with the default default_relator behavior). Regardless, it seems that we are making great progress on functionality, and these cosmetic matters of labeling and setting reasonable defaults are just finishing touches!

Thanks again!

**Comment by lahmann** [comment]
Demian,
I think I'm done so far with the templates (though we have to think about whether the roles should be displayed anywhere else apart from getDeduplicatedAuthors() calls).
In order to continue with the translations I had to merge the current master into this pull request - the merge went smooth except for `module/VuFind/src/VuFind/Config/Upgrade.php`. I went ahead and resolved the conflicts but I'm not 100%ly sure if I haven't reintroduced old code (especially Collections.ini and upgradeFacetsAndCollection()) -- it would be very reassuring if you could confirm the merge.
Thanks!

**Comment by demiankatz** [comment]
André,

I just merged vufind-org/master into vufind-org/improved-author-indexing, and it looks like my merging and yours were consistent, so I don't think there are any problems there. However, this branch is now reporting conflicts. Can you try merging vufind-org/improved-author-indexing into here? Let me know if I've created a mess and I'll see if I can figure out how to help!

Thanks!

**Comment by lahmann** [comment]
Demian,

thanks for updating the vufind-org/improved-author-indexing branch! I merge the branch into this pull request and all conflicts are resolved now.
I'll continue with the language files now.

Best,
André

**Comment by lahmann** [comment]
Demian,

An initial set of language files (en and de) for the CreatorRoles text domain exists now including the LOC-Marc relator codes and terms plus the German RAK codes and terms plus some additional codes and terms (depends on the library network). What still needs to be done is to translate the German terms into English and the English terms into German - but we are working at least on the latter task.
The text domain works great - #419 was well done! :+1: 
I also added the missing comma separator when multiple roles are present for one author.

I'll update this pull request as soon as we have made progress with the translations.

This should get us close to the final review for this PR and the improved-author-indexing branch.

Best,
André

**Comment by demiankatz** [comment]
Sounds great! I'll try to do some testing/review on this between now and next week's dev call so we can discuss it there if necessary.

**Comment by demiankatz** [comment]
A few new comments:

1.) There was some unexpected indentation added to author.bsh; I've removed it. Not sure how/why that happened, but not a big deal in any case.

2.) In marc.properties, I think there may be some issues with the modified author settings -- they seem out of sync with the modified author_role settings. Why has 110 been removed from the primary author list, but not 111? Also, why is 110 still in the acceptWithoutRelator parameter even though it has been removed from the tagList parameter? It seems like this needs to be made a little more consistent. I assume that part of the intent was to move 110/111 from the author field to the author_corporate field... but is it a problem that the author field uses the firstAuthorRoles configuration while author_corporate uses secondAuthorRoles? Does this mean that a primary corporate authorship will not be handled correctly? Do we need to accept a broader range of roles for the corporate authors?

3.) Travis is complaining because your new language files aren't sorted the way it expects. It may make sense to leave them alone until you're done translating, but eventually we'll probably want to fix that. I realize that the custom order with comments helps to explain what's going on in there, but it's probably not worth making an exception to our standard language file formatting rules. This also makes me wonder if we need to worry about collisions between the English and German relator terms. Are there any cases where the same string means different things in each context?

4.) I don't think your deduplicate routine is working correctly -- it sets $array2[$author] and then immediately unsets it. Was your intention to set $array1[$author] and unset $array2[$author] (or vice versa)?

5.) Do we need to do role deduplication in getAuthorRolesArray, or is that already handled somewhere else?

6.) We need to add "Corporate Authors" (the plural form) to the language files.

Thanks again!

**Comment by lahmann** [comment]
Thanks for your comments! You raised some serious issues - I addressed some in the latest commit (I was just about to head off for the weekend):

2.) That was a mistake, I have synced the `author` field to `author_role` now. You are absolutely right that only indexing corporate authors with secondaryrelators is not sufficient - I came up with the solution to be able to chain multiple relatorConfigs in `author.bsh` delimited by `:`. So we have the same syntax as with the Marc-fields. After a quick local test it seems to work quite well but should need some refinement (although some duplicates are indexed in the author_corporate field - but they are deduplicated in VuFind).

3.) So far I am not aware of diverging translations of relator terms, but we'll know for sure when we've got the first full translation into German/English.

4.) You were right, that was a bad typo - is fixed now.

5.) Yes, I implemented a small routine being called on each author array subfield to dedup the roles.

TODO:
* add "Corporate Authors" (the plural form) to the language files.

Let me know what you think!

**Comment by demiankatz** [comment]
Thanks for the fixes. One remaining issue:

2.) I think this needs some more work. The code you implemented for loading multiple sections of the .ini file is not defined at the most appropriate place. Not sure how familiar you are with Java/Beanshell, but one of the quirks of the language (at least, it seems like a quirk if you're more accustomed to scripting languages than strongly typed, compiled ones) is that you handle default parameter values by "overloading" a function, creating different definitions of the same function with different parameter lists. You've implemented the multi-loading of .ini sections in one of the overloaded function definitions designed to default one of the parameters. This means that you'll only get that behavior when a particular parameter is omitted, which of course would not make much sense! I think a more appropriate place to implement this functionality would be in the loadRelatorConfig function. Unfortunately, this function is already looking for a colon since you can pass a colon-delimited list of values in place of an .ini section. Maybe we just need to use different delimiters -- i.e. perhaps we should use a comma instead of a colon for hard-coded relator lists (since this is more consistent with the contents of the .ini file anyway), and if we find a colon we know that we need to merge together multiple .ini sections. What do you think?

**Comment by lahmann** [comment]
Demian,

2.) You made a very good point - the overloading functions are not the right place to handle the config-setting string. So I went ahead and implemented that code in loadRelatorConfig as you suggested. As for the delimiter: it's not entirely clear to me how values are parsed in .properties files and as the comma is usually used as parameter separator for function calls, I decided to go with the `|` delimiter in order to keep the distinction parameter -- value-delimiter clear. So now we can define `secondAuthorRoles|nonCreativeRoles|adp:cmp` for the relatorConfig-parameter in our .properties files which allows us to pass ini-settings as well as relator-lists (in combination).

Let me know what you think!

Best,
André

**Comment by lahmann** [comment]
As you can see I just pushed the translations of "Corporate Authors" in en.ini and de.ini - how should we proceed with other languages?

**Comment by demiankatz** [comment]
I agree that the `|` delimiter makes sense here, especially since it has "or" connotations.

Regarding the translations, English and German are a good start -- we'll get the rest as part of the regular translation cycle for the release that includes this code.

I think this may be ready to merge into the main branch, but I'm going to do a bit more testing today just to be sure!

**Comment by demiankatz** [comment]
Just made a minor correction to marc.properties: the secondary author was configured to allow 700 fields with no relator... but those should go into the primary field. I've changed this to avoid duplicate indexing. (Probably just a typo introduced when moving things to the corporate field).

**Comment by lahmann** [comment]
Hmm, maybe we have to rethink that again: our primary key for deciding if an author gets indexed into `author/_role` is the relator (therefore we got the primary/secondary relator-setting in author-classification.ini). Only if no relator is present we have to decide if an author should go into primary or secondary author field based on the Marc-field.
Thus, any additional person in 700 without any relator should go into `author2/_role` but not into `author/_role`:
```
author                = script(author.bsh), getAuthorsFilteredByRelator(100abcd:700abcd,100,firstAuthorRoles)
author_role           = script(author.bsh), getRelatorsFilteredByRelator(100abcd:700abcd,100,firstAuthorRoles)
author2               = script(author.bsh), getAuthorsFilteredByRelator(700abcd:,700,secondAuthorRoles)
author2_role          = script(author.bsh), getRelatorsFilteredByRelator(700abcd,700,secondAuthorRoles)
```

What do you think?

**Comment by lahmann** [comment]
If we really want to push it, we could even go this far:
```
author                = script(author.bsh), getAuthorsFilteredByRelator(100abcd:700abcd,100,firstAuthorRoles)
author_role           = script(author.bsh), getRelatorsFilteredByRelator(100abcd:700abcd,100,firstAuthorRoles)
author2               = script(author.bsh), getAuthorsFilteredByRelator(100abcd:700abcd:,700,secondAuthorRoles)
author2_role          = script(author.bsh), getRelatorsFilteredByRelator(100abcd:700abcd,700,secondAuthorRoles)
```

**Comment by demiankatz** [comment]
I thought the idea here was that if a work has multiple "primary" authors, the first one goes in 100 and the rest go in 700's. So we need to treat 100 and 700 the same in terms of relators -- thus, 100's or 700's with no relator get treated as authors and go to the author field. We should never send 700's with no relator to author2.

Am I misunderstanding something?

**Comment by lahmann** [comment]
You are right that multiple primary authors go into Marc field 700, but also other persons can be catalogued in Marc field 700 (if I understand Marc correctly: http://www.loc.gov/marc/bibliographic/bd700.html) - thus there's the distinction informational/analytical (or am I misunderstanding this distinction entirely?). I have to admit that I just came across this distinction and until now I thought that there would be no property to decide if a person in 700 is in a primary or secondary (according to our relator-gorups) relationship to the record _apart_ from the relators being assigned.
So, I guess we might be both right and have to decide whether we want to take the second indicator into consideration or index all 700 entries without relator into `author`.

**Comment by demiankatz** [comment]
My understanding of "analytical entries" is that these can be used to break down the contents of an anthology or omnibus edition. So if your 245 is "The Complete Works of Charles Dickens," then there could be a 700 field indicating that Charles Dickens wrote Nicholas Nickleby within that volume. Obviously, in the case of an anthology containing the works of multiple authors, this gets complicated -- each 700 field could contain the primary author of a work within the collection, but these might be viewed as secondary in terms of the work as a whole.

In any case, I don't think adding special code to deal with "analytical entries" solves the problem as a whole -- it just addresses one tricky edge case of the overall situation. The key question is: can we reliably assume that a 700 field with no relator term means something specific? I suspect that the answer is going to depend on the cataloging rules in use at a given institution, with possible differences between AACR2, RDA, etc.

I'll try to talk to our head cataloger here and see if he has any thoughts (he's not at his desk right now, but I'll try again later). We can also discuss this further on the call tomorrow. My gut feeling is that we should try to keep this relatively simple and allow people to customize to meeting local practices as needed, because there probably isn't a single universal solution... but of course I'd like to get as close to a universal solution as we can to save everybody time, trouble and confusion!

In any case, independent of all that, I've gone ahead and updated this branch to use a new version of SolrMarc that's been compiled to reflect your latest BeanShell changes. I've switched marc.properties back to use the compiled version instead of the script and updated marc_local.properties to match the latest settings in marc.properties. Note that I discovered that having a null parameter in marc.properties breaks the compiled version of SolrMarc, so I just used the word "null" in the parameter list in place of the empty space between two commas. Should have the same functional effect. There might be a more elegant solution, but I didn't take the time to find it.

For the moment, I'll hold off on merging this until I hear more from you (and perhaps until we've had time to talk about it on the dev call tomorrow).

Thanks again for all the hard work! There's a lot to think about here.

- Demian

**Comment by lahmann** [comment]
Great, I will also talk to a colleague about this issue tomorrow.

Thanks for your work on SolrMarc!

Just a reminder: we are still working on the relator-translations.

**Comment by demiankatz** [comment]
Sounds good. Regarding the relator translations, I don't think that needs to hold up merging this into the main branch -- we can just add "finish relator translations" as another checkbox on that PR's to-do list.

**Comment by lahmann** [comment]
Demian,

I just talked to a colleague about this issue and he pointed out that according to German cataloguing guidelines a person in Marc 700 with _no_ relator does not hold any specific meaning - only in relation to Marc 100 there is a special case: if Marc 100 is empty any person in Marc 700 with no relator is no author for sure (if Marc 100 is _not_ empty persons in Marc 700 with no relator can be authors). But this special case should not be relevant for us as this would only mean that the person in Marc 700 should definitely go into `author2` - if we stick with the relators being the primary key deciding whether to index in `author` or `author2` those entries would go into `author2` anyway.

So from our point of view we should _not_ index any person in Marc 700 without a relator in `author`.

Did you find the time to discuss this issue with your colleague?

Best,
André

**Comment by demiankatz** [comment]
André,

Just discussed with my colleague and he said essentially the same thing: treat 100 with no relator as primary, treat 700 with no relator as secondary. So I think that means we can make a very minor tweak to the properties files and then we're in good shape! I can take care of that after the dev call, unless you're able to get to it first.

Thanks!

**Comment by lahmann** [comment]
Demian,

alright, I just pushed the updated marc(_local).properties files. That should get this pull request ready for merging into `improved-author-indexing`.

Best,
André

**Comment by demiankatz** [comment]
Great, I've gone ahead and merged this.

**Pull request merged**
