### PR TITLE
Release of croatian translation files

### PR DESCRIPTION
**Pull request by milotype**

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @milotype, this is a very helpful contribution! Do you plan on also adding appropriate lines to the config.ini and languages/native.ini files? If not, I'm happy to add those details for you!

**Comment by milotype** [comment]
Yes, I can do those as well.
I found `languages/native.ini`, but don't know where to find the `config.ini`.

**Comment by demiankatz** [comment]
Thanks again, @milotype!

Regarding config.ini, you can add the new language option to this list to make it available in the language drop-down:

https://github.com/vufind-org/vufind/blob/master/config/vufind/config.ini#L1399

Also note that the automated testing process is detecting some minor formatting errors in the files. If you look at the Travis build output, you will see the details -- looks like it is mostly problems with extra or missing quotation marks.

You can automatically apply the changes shown in the build output by running:

`php public/index.php language normalize languages`

from inside your $VUFIND_HOME directory... but it looks like at least a couple of the problems may require some manual intervention because they have to do with inverted quotes being used in place of regular quotes.

Please let me know if you'd like me to help with any of this final cleanup!

**Comment by milotype** [comment]
@demiankatz Thank you for the info. FYI, I'm not a programmer, just a MacOS user, not even using vufind … i just like to help translate opensource software … I don't make builds or any of that sort, sorry.

I've corrected `languages/hr.ini`.

When inserting the line
`hr          = "Croatian"`
to the `config.ini` file, would it make sense to make that whole list in alphabetic order by language codes? Currently it looks very random. And in the comment of the file I found:
> ; The order of the settings is significant -- they will be displayed on screen
> ; in the same order they are defined here.

**Comment by demiankatz** [comment]
@milotype, thank you for your help -- that is very generous! I will take care of the remaining file cleanup for you.

Regarding the order of the language list, it is currently chronological in order of when languages were added, but of course that makes no particular sense. The assumption is that most users will want to reorganize it to put their local language at the top of the list, but having a better default order would make sense. I'll bring this up with the community and see if anyone has any suggestions on a best approach. (Alphabetical is somewhat challenging because different scripts are in use -- not sure how to decide on an order for Cyrillic, Chinese, etc.).

Also, would you like to be notified when new versions are released so you can help keep the translations up to date? If so, I'll add you to my list of translators... but if you don't expect to have that free time going forward, I'm still very grateful that you took the time to get this started!

**Comment by milotype** [comment]
> … I will take care of the remaining file cleanup for you.

Ok.

> … (Alphabetical is somewhat challenging because different scripts are in use -- not sure how to decide on an order for Cyrillic, Chinese, etc.).

- In the `config.ini`, sort languages by **language code** – nobody really wins, but it's "nicer" in the code.
- For simple alphabetic sorting by **script** and **language** in vufind itself, some extra programming would probably be needed, maybe also taking the user's system locale into account. Ideally, the user's locale would help/decide the order of scripts and languages. Of course I don't know how to implement it, and it's just an idea of a non-programmer ;-)

> Also, would you like to be notified when new versions are released so you can help keep the translations up to date? If so, I'll add you to my list of translators... 

Sure, feel free to add me to the list …

**Comment by demiankatz** [comment]
Thanks again, @milotype -- I have run the cleanup utility and the build is now passing; everything looks good.

I see that you skipped the CreatorRoles translations, which is understandable because it is a long list, and many of the terms are very technical and thus challenging to translate. If you would like to do a subset of the easier ones (author, translator, editor, etc.) that might be valuable -- but no pressure, of course!

Thanks also for offering to help keep things up to date. We usually have about two releases a year, so I'll be in touch whenever one of those is in the process of being assembled. Obviously, you can feel free to say "please wait until next time" if you are too busy when that happens. If it would be more convenient to hear from me through email rather than GitHub notifications, feel free to send me a message at `demian.katz@villanova.edu`.

**Comment by milotype** [comment]
@demiankatz I have no preference on how to contact me.
> I see that you skipped the CreatorRoles translations

I was going to do it for croatian, but as you said, it's a long list … but, I will do it soon.

**Comment by demiankatz** [comment]
Great, thank you. Feel free to open another PR for that whenever you have a chance. If you have questions about any definitions, just let me know!

**Pull request merged**
