### PR TITLE
Final composer updates for release 9.0.

### PR DESCRIPTION
**Pull request by demiankatz**
TODO
- [x] Run full test suite
- [x] Manually check OAI harvest
- [x] Manually check Swagger API functionality

### CODE REVIEW

**Comment by demiankatz** [comment]
@EreMaijala, this PR gets the remaining Composer dependencies updated (including catching up with a few new releases that were issued since last week's work was merged). I don't expect major problems here, but I'm currently working through some tests. Once all of the TODO checkboxes above are checked, this will be ready for your review. I think the only thing you might want to give a little extra attention to is Swagger UI, since that has been fragile in the past and I'm not sure how thoroughly it needs to be tested (I'm just going to make sure that results load).

**Comment by demiankatz** [comment]
Okay, not seeing any obvious problems from my end!

**Review by EreMaijala — APPROVED** [review]
Everything seems to work, including Swagger UI. :)

**Comment by demiankatz** [comment]
Thanks, @EreMaijala!

**Pull request merged**
