### PR TITLE
Fixing hard coded links in HelpTranslations

### PR DESCRIPTION
**Pull request by lahmann**
Replaces all hard coded links in HelpTranslations with links build by view helper (otherwise links will fail if vufind is not installed in site root).

### CODE REVIEW

**Comment by crhallberg** [comment]
Good catch! Thank you!

This also brings to my attention that these links needs `data-lightbox-ignore` so that they escape the lightbox. I'll take care of that after merging.

**Comment by crhallberg** [comment]
Actually, the `help-home` route fails in the lightbox.

**Comment by lahmann** [comment]
Hmm, I don't know if it is working for you know, but the route `help-home` does at least work for us.

**Comment by demiankatz** [comment]
Thanks, Chris! Should some/all of this also go into the release-3.0 branch?

**Pull request merged**
