### PR TITLE
Fix hierarchical facets and make exclude link placement more consistent.

### PR DESCRIPTION
**Pull request by EreMaijala**

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @EreMaijala. All tests are now passing, and I couldn't find any major issues.

One small outstanding issue was that "OR" icons were being aligned incorrectly, but I fixed that here:

https://github.com/vufind-org/vufind/commit/dde03e5d1a65c899fb08b01ca8074b780b01c1c1

(That fix was compiled in along with the other changes in this branch, and it's all in master now).

Might not hurt for @crhallberg to take a look at all of this when he gets back, but if there are remaining problems, they're subtle ones.

**Comment by edelm** [comment]
Using jQuerys "text()" to render the decimal separator does not work with the single quote (') we use in Switzerland, since it doesn't decode html entities.

We could change it to "html()", which does encode html entities. To be on the super safe side regarding javascript injection, we could also strip the script tag (str.replace(/<script[^>]*>([\S\s]*?)<\/script>/gmi, '')).

Here is the direct link to the code:
https://github.com/vufind-org/vufind/blob/c688c1a43b7985b958bc534f61c9137653d58c2a/themes/bootstrap3/js/facets.js#L36

**Comment by demiankatz** [comment]
@edelm, thanks for the heads-up, and sorry for the slow response (I've been on vacation). I'll take a closer look at this soon as I catch up on everything that occurred while I was away!

**Comment by demiankatz** [comment]
@edelm, see https://github.com/vufind-org/vufind/pull/1225 -- I've opened this PR to allow continued discussion of this issue (and hopefully to reach a quick resolution).

**Pull request merged**
