### PR TITLE
Switch Koha ILS Driver to using VuFind's dateConverter

### PR DESCRIPTION
**Pull request by jlcooper**
This pull request moves the Koha ILS Driver from being an `Invoked` ILS driver to being one created by the ILS Driver Factory, so that it can get access to VuFind's user configured dateConverter.  It then uses that to format any dates it returns.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks for sharing this! Looks reasonable to me, but as I'm not a Koha user, I do have one question: I see that you are currently parsing for some very specific date formats. Is it safe to rely on these in all Koha installations, or is there any risk that these may vary based on locale/region settings? Before I merge this, I just want to be sure it's not going to break anyone's installation.

**Comment by jlcooper** [comment]
The dates in Koha are from a MySQL Date or DateTime field, so I'm matching against MySQL's date format just to be sure.

  I'm more than happy for you to get a second opinion from another Koha user, as I wouldn't want to break others installations either.

**Comment by jlcooper** [comment]
Alternatively, I could always modify the `displayDate` and `displayTime` functions to return their parameter if they don't match the date pattern (rather than throw a `DateException`).  That way existing functionality will be maintained if the date patterns don't match.

**Comment by demiankatz** [comment]
@jlcooper, yes, I think that's an elegant solution to the problem -- it enhances the behavior in most (maybe all) cases, but doesn't introduce a fatal error. You could put an `error_log('unexpected date format');` before returning in that case, so at least there's an indication in the Apache error log that something unexpected is going on....

**Comment by demiankatz** [comment]
Thanks, @jlcooper, this looks pretty good... but two side effects of your refactoring:

1.) Now that you don't throw exceptions, you can remove the `@throws` comments and the `use` statement for the Date exception.

2.) I see that you are no longer using the `displayTime` function, presumably to avoid the scenario where an unexpected format would cause a string to be displayed twice. Should you remove the function now that it is no longer in use?

**Comment by jlcooper** [comment]
I've dropped the `throws` comments and the `use` statement, and as we don't need the displayTime function anymore I've also dropped it (we can always pull it back from an old commit if we need it in the future).

I have noticed that there's a few other functions which have existing `@throws \VuFind\Exception\Date` comments, yet they don't seem to throw a date exception. So we might want to review those and see if they are accurate or if we need to remove them.

**Comment by demiankatz** [comment]
Looks good to me. I'll merge it as-is. Regarding the existing @throws statements, those were likely copied-and-pasted from other ILS drivers. We could choose to remove them, or we could leave them as an indication that the method is allowed to throw that exception, since the calling code will expect it. I'm honestly happy either way -- and doing nothing is of course the easiest approach. :-)

**Pull request merged**
