### PR TITLE
Don’t try to use the event parameter in checkSaveStatuses. Fixes chec…

### PR DESCRIPTION
**Pull request by EreMaijala**
…king of save statuses after adding a record to the favorites.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks for sharing. What behavior were you seeing that this is designed to help work around?

**Comment by EreMaijala** [comment]
Save statuses don't update on the results list after adding a record to favorites. Instead a JS error is logged.

**Comment by EreMaijala** [comment]
And that's because for lightbox callbacks the first parameter is the event, while checkSaveStatuses expects it to be, if specified, a container element.

**Comment by crhallberg** [comment]
Would it be less complex to do a `_container instanceof HTMLElement` check instead of introducing a new function?

**Comment by EreMaijala** [comment]
Yes, but I don't think that it's the right thing to do, because it would mean that checkSaveStatuses() is intentionally called with an invalid _container param, and I don't like that. If you feel it's better, though, feel free to do that instead of this.

**Comment by demiankatz** [comment]
I'm inclined to agree that the wrapper function is slightly more clear... or, at very least, if we went with the overloaded parameter, we should rename _container to _containerOrEvent.

**Comment by crhallberg** [comment]
Fair enough. Should we make sure this is covered in our integration tests before merging?

**Comment by demiankatz** [comment]
Okay, we've figured out why our test suite was not catching this situation, and we've addressed the situation. I have also confirmed that this problem is unique to master -- not affecting release 3.1.x. Merging now. Thanks for the catch, @EreMaijala.

**Pull request merged**
