### PR TITLE
GeoFeatures - Handling of empty and malformed text in titles for map selection results

### PR DESCRIPTION
**Pull request by lmgonzales**
This fixes a bug that is caused by empty title fields, or titles that have malformed UTF-8 characters in them. Both of these caused the map selection js file to break.

### CODE REVIEW

**Comment by demiankatz** [comment]
Do you have a test record that demonstrates the problem here? Might be worth adding it to the test data if so. I also wonder if there's a more direct way to detect the problem, or if it can be solved at the indexing stage. At very least, perhaps using the mb_detect_encoding / mb_convert_encoding functions might be more straightforward than relying on JSON error behavior.... though if you've already been through that and this is what actually works, I can probably be persuaded to live with it. :-)

**Comment by lmgonzales** [comment]
Thanks for the feedback @demiankatz. I'll create a couple of test records to demonstrate the issue. 

I agree that it would be good to detect this on indexing, but lack of titles or non-UTF8 characters in the title only seem to be an issue with the Map Selection module (it completely breaks the interface) and not any of the other VuFind code. That's why I didn't pursue the check/fix in the indexing code route. I'll take a look at the mb_detect_encoding and mb_convert_encoding functions to see if they would work better than the current proposed change. Thanks for the tip!

**Comment by lmgonzales** [comment]
@demiankatz , I checked the mb_detect_encoding function but it doesn't catch malformed UTF-8 text strings like the json_encode() and json_last_error functions do. That said, I've updated the code to convert all titles with the mb_convert_encoding() function. This will save a few lines of code and solves the issue as well. I've also added a test file with records that are missing titles and one with a title that causes the map selection code to fail unless it's converted (that's the one that returns the malformed UTF-8 string error when run thru the json_encode() function).

**Comment by demiankatz** [comment]
Thanks, @lmgonzales, looks good! Note that I made some slight adjustments to the missing title code to ensure that the string is properly translated. (I adjusted the wording slightly to match an existing string in our language files). Please let me know if you have any concerns about this, but I'm confident enough that I went ahead and merged it to master.

**Comment by lmgonzales** [comment]
Looks good to me @demiankatz. Thanks!

**Pull request merged**
