### PR TITLE
Adjust pager buttons for mobile

### PR DESCRIPTION
**Pull request by maccabeelevine**
This makes two small adjustments to the pager component, for when the viewport is too narrow to display the entire thing.  See screenshots from the iPhone SE 2022.

- The Next/Last buttons are kept together, instead of Last wrapping on its own.
- It adds a small gap between the two rows of buttons, for accessibility.

Before:

image

### CODE REVIEW

**Comment by maccabeelevine** [comment]
After: 

image

**Review by crhallberg — APPROVED** [review]

**Comment by sturkel89** [comment]
I looked at the user interface for this PR, comparing test vs. dev in all three themes. The branch looks good! I think putting those controls together is an improvement over dev.

-------
My only comment/critique, which applies to both test and dev, is that the First, Prev, Next, and Last controls look very spaced-out in Sandal because they're just text, not contained in outlines:

**Bootstrap3**
image

**Sandal**
image

I think it would be better if there were outlines around those controls. But that's not a problem that's specific to this PR.

**Comment by demiankatz** [comment]
Thanks, everyone -- I'll merge this now! Regarding the outline issue, does @crhallberg (or anyone else) have any opinions? We could likely tweak styles in Sandal to adjust this if necessary; just a question of whether we should restore outlines or reduce padding... or we could decide that the distance between the controls is beneficial for accessibility reasons.

**Comment by maccabeelevine** [comment]
> we could decide that the distance between the controls is beneficial for accessibility reasons.

When I added that padding, I think I was aiming for a total effective height of 44px, which I see now is [Level AAA compliance](https://www.w3.org/WAI/WCAG21/Understanding/target-size.html) vs. 24px for [AA Compliance](https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html).  There is also an exception for inline text, which is what Sandal effectively has.  So the spacing could certainly be reduced if needed.

**Pull request merged**
