### PR TITLE
import-marc-auth using solr.indexer.properties option from PROPERTIES_FILE

### PR DESCRIPTION
**Pull request by mtrojan-ub**
see https://sourceforge.net/p/vufind/mailman/message/36430409/

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @mtrojan-ub, this looks great; I'll make some time to test it in detail next week.

**Comment by demiankatz** [comment]
@mtrojan-ub, what Windows environment did you use to test this? Under the Windows 10 command prompt, I'm getting the error `'MAPPINGS_FILENAMES' is not recognized as an internal or external command, operable program or batch file.` when I try to run import-marc-auth.bat.

**Comment by demiankatz** [comment]
@mtrojan-ub, this also does not appear to be working as expected on my Ubuntu 16 system. I modified import-marc.sh so that it just echoes out the final Java command without executing it, and I compared output from the master branch and this branch when I run `./import-marc-auth.sh my-marc.mrc marc_auth_fast_title.properties`.

In master, solr.indexer.properties gets set to `$VUFIND_HOME/import/marc_auth.properties,$VUFIND_HOME/import/marc_auth_fast_title.properties` ; in your branch, it gets set to `$VUFIND_HOME/import/marc_authpropertiesmarc_auth_fast_title.properties` -- note how the specified properties file is getting directly concatenated to the default properties file without a delimiter or full path. Any idea what's happening here?

For all of the problems I'm reporting, I've simply approached this as a user and examined outputs. If you need help troubleshooting, I'm happy to dive in deeper -- but first I wanted to share this initial report.

Thanks!

**Comment by mtrojan-ub** [comment]
@demiankatz, i tested it under Windows 10 Enterprise (Version 1803) and Ubuntu 18.04. Thanks for testing! I will try to reproduce the errors on my systems as well.

**Comment by demiankatz** [comment]
@mtrojan-ub, I just noticed that this was targeted against the release-4.1 branch, which is no longer under active development. I have repointed it at master and have merged the latest changes in. I will do further testing in the near future as time permits; just wanted to let you know about this step -- I hope it is not an inconvenience for you.

**Comment by demiankatz** [comment]
@mtrojan-ub, please take a look at my commit ca02c01 -- I found that if I included a comma-separated list of properties files in my import_auth.properties file, the filenames all got jammed together. Translating the commas into spaces fixed the issue. Perhaps your test case used comma-space separators rather than just commas. In any case, with my change, both scenarios seem to work correctly... but please double-check that I haven't broken anything for you!

**Comment by mtrojan-ub** [comment]
Building the java command works fine now.
But after having a look at the solrmarc code, maybe we should use ";" instead of "," as delimiter?

see solrmarc:
https://github.com/solrmarc/solrmarc/blob/master/buildtools/install_template/how_to_run.txt#L48
https://github.com/solrmarc/solrmarc/blob/master/src/org/solrmarc/driver/ConfigDriver.java#L48
https://github.com/solrmarc/solrmarc/blob/master/src/org/solrmarc/driver/ConfigDriver.java#L98

**Comment by demiankatz** [comment]
@mtrojan-ub, the code you cite seems to be related to loading the top-level SolrMarc configuration rather than the MARC mapping configuration (though it's possible I am mistaken -- this can be a little confusing). I'm not sure if different delimiters are used in each of these cases, or if multiple delimiters are supported. If multiple delimiters are supported, we may need to make the scripts a little more flexible to support additional possibilities. Do you have time to test this out, or should I? I'm willing, but since I have quite a few PRs still in need of review, it will take me a little while to get to it!

**Comment by mtrojan-ub** [comment]
@demiankatz :
i suppose the next step would be to take a look here: https://github.com/solrmarc/solrmarc/blob/master/src/org/solrmarc/driver/BootableMain.java#L59
since i will be on vacation next week, it would be great if you could have a deeper look into this by yourself. Thanks a lot!

**Comment by demiankatz** [comment]
@mtrojan-ub, I also have some vacation coming up, and a lot of code reviewing to get through, so I'm not sure if I'll get to it before you return or not, but I will try, and I'll report back here when I make some progress!

**Comment by demiankatz** [comment]
@mtrojan-ub, I had a chance to dig a little deeper into the code, and found that the specification file list is split apart here:

https://github.com/solrmarc/solrmarc/blob/7a9e70ae7e1788d5bb2df45dcd6f5be5dcf409d6/src/org/solrmarc/driver/IndexDriver.java#L241

It looks to me like comma is the only supported delimiter, so I don't think any further changes are needed. Would you agree at this stage? Let me know if you have any other concerns. If you are satisfied, I'll do one final round of testing and then merge this.

**Comment by mtrojan-ub** [comment]
That's fine for me, thanks for helping!

**Comment by demiankatz** [comment]
Thanks, @mtrojan-ub -- I have merged this!

**Pull request merged**
