### PR TITLE
Improved interface for active filter removal

### PR DESCRIPTION
**Pull request by crhallberg**
- Remove icon
- Show removal with line-through
- Improve contrast
- Move sr text to more clearly identify links

image

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @crhallberg. This looks reasonable to me across all three themes, but I don't have really strong opinions about the change. Curious to hear what @EreMaijala thinks, since a lot of the original design comes from him.

**Review by EreMaijala — CHANGES_REQUESTED** [review]
While this looks (and works) fine when you know what you're looking at, I think this affects the discoverability of the function particularly on mobile devices where you can't rely on the hover effect.

**Comment by crhallberg** [comment]
To address @EreMaijala's concern, I could keep the x icon for mobile but this slashing and red styling is definitely much clearer to me.

**Comment by EreMaijala** [comment]
@crhallberg Is it possible to have the effect also on keyboard focus? A focus rectangle would be great as well. It didn't have that before either, but the x changed color on focus so you had at least some sort of input.

I'm still a bit hesitant on the underlining changing to overstrike. Without underlining the addition of overstrike would be great, but the transition feels weird to me, kind of like I'd be losing the originally implied action.

**Review by EreMaijala — CHANGES_REQUESTED** [review]
Having thought about this, I think the link shouldn't be underlined. The whole element is more of a button, so underlining doesn't convey more information. The focus indication would be important to have.

**Comment by demiankatz** [comment]
Thanks, @EreMaijala; I'm inclined to agree that this is more clear without the underlining, and that keyboard focus highlighting would help a lot.

@crhallberg, I noticed there were some conflicts here, so I resolved them in order to test; you might want to double-check my work.

I'm also bringing @ckaz into this conversation, because I think he might have helpful opinions as well.

**Comment by ckaz** [comment]
Great idea but I fully agree with @EreMaijala : For accessibility we need the focus indication and it would make more sense to me too, if there was no underline (which I wouldn't expect of a button type-looking interaction element anyway). So my preference would be 
* Strikethrough on hover/focus / x-icon on mobile
* Focus rectangle on focus
* No underline

**Review by demiankatz — APPROVED** [review]
Thanks, @crhallberg, this looks much better to me. Curious what @EreMaijala and @ckaz think at this point; I'll wait for their feedback before merging.

**Review by EreMaijala — APPROVED** [review]
Looks good to me!

I noticed the strikethrough overflowing on the right, but I tested it without, and it looked worse to me, so I've no problem with that.

**Review by ckaz — APPROVED** [review]
Looks good to me. Pls. go ahead!

**Comment by demiankatz** [comment]
Thanks, everyone -- just merged!

**Pull request merged**
