### PR TITLE
Permissions improvement

### PR DESCRIPTION
**Pull request by olli-gold**
Although this is still work in progress in a pretty early state, I'm opening a PR for the improvements of the permission system here. Perhaps its easier to discuss this feature here instead of the mailinglist.
- [x] Add tests for new components
- [x] Add translation strings to german and english translation files (at least)
- [x] fix style issues
- [x] use native logger instead of error_log() function
- [x] fix compatibility with $accessDeniedBehavior controller property.
- [x] Improve documentation of action configurations, and make sure options are consistent, correctly documented and all fully functional.
- [x] Improve documentation of display logic configurations, and make sure options are consistent, correctly documented and all fully functional.
- [x] Improve documentation of search tab configurations, and make sure options are consistent, correctly documented and all fully functional.
- [x] Confirm that [global] section of permissionBehavior.ini works as documented; adjust as needed.
- [x] Remove Primo-specific changes if unnecessary (or separate to different commit if useful but unrelated to infrastructure changes).
- [x] Add documentation for these new features to the Wiki
- [x] Improve display of list, what to do to get permission (need better persistence than flash message!)
- [x] Determine a more appropriate name for the favorites.save permission
- [x] Make sure save permission is consistently implemented (buttons on record and result views; a complementary controller check).
- [x] Revisit default behavior for undefined permissions in both action and display contexts. (Currently inconsistent: treated as denied in action, permitted in display).
- [x] Fix or remove the incomplete testExistingTemplateDisplay() test for the view helper (and review tests for other issues).

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks for getting this going. A few comments based on a quick review:

1.) In Controller\AbstractBase, rather than having a `$this->pm` property that gets populated in `attachDefaultListeners`, I think it would be cleaner to create a getPermissionManager() protected method that pulls the service out of the service manager and returns it. This way, you avoid the possibility of a "method call on non-object" error if $this->pm gets called before it's initialized. Probably a better long-term solution would be to solve this with more explicit dependency injection (since I'd like to reduce the dependency of the controllers on the service manager), but for now I think it's easiest to follow the established pattern, and then it can all get cleaned up at once at some point in the future.

2.) Since you're adding new templates, we should make a note to ensure that we update the jquerymobile theme to match before merging this. Not a high priority -- better to finalize the design first and port it later -- but it's probably worth putting a TODO checkbox in the top-level comment so we don't forget about it. (If you haven't done this before, you can just edit the text and create a list using `- [ ]` before each item, and GitHub will convert them into checkboxes and display stats about their completion). A very useful feature!

3.) Similarly, I see that you're adding some new translation strings for the new template. We don't want to forget to translate these. Perhaps it would be best to use short placeholder strings as keys in the language files so that changing the English wording won't force us to change any other language files. I'd suggest something like 'permission_denied' for the first part and 'permission_action_list_header' for the second part.

4.) For tab permissions, rather than hard-coding the permission name as `'access.'.$tab['id']` perhaps you could just use `$tab['permission']`. This would make it easier to customize the behavior by configuring permissions for tabs. We could also decide whether to populate this with a default permission string by default (i.e. the current concatenation) or if we want it to be "false" by default, which would bypass permission checking entirely and thus save some cycles in most cases.

5.) I see you've added code to output `$this->message` in home.phtml, but I'm not sure where this is getting set. Was that committed by accident? Is something missing?

6.) Continuous integration is complaining about a handful of style issues. Might not be worth spending a lot of time fixing these right now while the code is in flux anyway, but if you want to fix them and need help, let me know.

7.) I have a feeling that this is going to eventually become a fairly large and complex PR. While we develop, it's worth thinking about whether there are any parts that can be split off from it, or whether we can commit it in some kind of incremental fashion, to help make our revision history clean and understandable. Obviously the first thing we need to do is get it in the shape we want -- but just thinking ahead here.

Anyway, that's just a first round of minor comments. I need to take a closer look at the meatier classes of the code, but I'll probably put that off until next week as I have a few other things I'd like to get done prior to the next dev call, and I'm going to reserve my mental energy today for those. In any case, thanks for keeping this going, and I'm sure we'll discuss it further next week!

**Comment by olli-gold** [comment]
Thanks for your comments and hints! In my opinion this PR has absolutely no priority, its more a nice-to-have, so its no need to hurry here.

I have done your points 1-5. Regarding point 6 I agree, that we can clean the errors up when we have a more stable code base. About point 7 I also agree, that this might get a complex PR - and it's certainly possible to split things off if we find something, which is fitting also in another context.

One question I stumbled about is the PermissionManager and the LinkDisplay ViewHelper - they have nearly identical code. Perhaps we can simplify the LinkDisplay class and use the PermissionManager there as well.

**Comment by demiankatz** [comment]
Thanks for the progress! Some new comments based on another read-through of the code (again, not necessarily comprehensive, and not yet based on actually trying to run the code, but just items that caught my eye):

- In AbstractBase::preDispatch, you are instantiating the permission manager and calling getDisplayLogic() on it even if $this->accessPermission is unset; this seems potentially wasteful of resources.
- Throughout AbstractBase, you are fetching the permission manager directly from the service locator; I'd recommend using the new getPermissionManager() wrapper method instead to make future refactoring easier.
- In your preDispatch switch statement, `case 'exception'` and `default` are the same... so you can just delete the code block under `case 'exception'` and allow both cases to fall into the same code.
- I don't think that AbstractBase::attachDefaultListeners is the best place to be assigning a value to $this->accessPermission; I'd prefer to do something more targeted. Ideally, I think we should try to avoid actually introducing new permissions in this pull request and instead focus on the behavior of the new classes. If we want to add new permissions, that's probably a detail better addressed directly in master or in a separate pull request. Obviously I don't have a problem with setting up some example permissions in the code to make testing/development easier, but I think we should be careful to separate "handling of denied permissions" from "developing VuFind's permission options" in order to keep things focused and simple.
- The comments in PermissionManager::isAuthorized don't seem to match the code. (Same goes for constructor, getConfigContext and getReaction). I understand that documentation can easily get out of sync during early development, but if nothing else, it might be worth deleting the inaccurate doc blocks entirely; the style checker will remind us to put them back later, so we won't be able to merge this without proper documentation.
- PermissionManager::getReaction includes references to an undefined $tmpl variable; possibly the result of copy and paste from another class. This should either be fixed (if necessary) or deleted (if the method is unused).

Anyway, that's probably more than enough for now. I can provide more comments if you want me to keep reading, but I don't want to overwhelm you with too many picky details. If there's some aspect of the code you'd like me to focus on reviewing first, let me know and I'm happy to do that! Thanks!
-

**Comment by olli-gold** [comment]
Thank you for the new comments! I have corrected and improved the things as you suggested. About your fourth point: you are right, that it's probably better to leave the setting of new permissions out of this PR. So I have deleted the code to set new permissions based on configuration settings from AbstractBase::attachDefaultListeners and we can think about this later.

Next week, I'll start to create tests, this should help to continue implementation as it can clarify the demands for the new classes. Also, I will try to refactor the displayLink helper to use the new PermissionManager to avoid duplicate code.

Thanks again for all of your help - it is always very valuable!

**Comment by olli-gold** [comment]
I have made some improvements to the PermissionDeniedManager (I have renamed the former PermissionManager to clarify that the purpose of this manager is only to handle denied permission behavior) and I have added a unit test for the manager. I hope, tommorow I can start to refactor the LinkDisplayHelper and I'm going to develop a unit test for the helper also.

**Comment by demiankatz** [comment]
Thanks, Oliver, that sounds good. I'm going to be distracted by Code4lib this week, but hopefully can take a closer look at this either on Friday or some time next week.

**Comment by olli-gold** [comment]
All right, still no need to hurry. Have a good time at Code4Lib!

**Comment by olli-gold** [comment]
Again I have made progress on this: I have prepared a test for the LinkDisplay helper and have redesigned the helper as planned to use the PermissionDeniedManager. I guess now we can start refining and improving it - and perhaps it will be even finished for VuFind 3 (although this might be too optimistic; I guess there is still a lot of work in the details).

**Comment by demiankatz** [comment]
Thanks for the update. I think getting this into 3.0 might be a little too ambitious, since we'll be freezing code in a couple of weeks, and I'm probably going to be too preoccupied with polishing up other things to give this the attention it deserves. However, it might be a strong candidate for a 3.1 a few months after 3.0, since I don't think it's going to break any backward compatibility, but simply add some new features.

**Comment by demiankatz** [comment]
Finally had a few moments for a review. Another round of comments:

1.) Looks like this branch now has some conflicts with master. Let me know if you need any help resolving them.

2.) I think using a delimited label string to associate a permission name with a tab is potentially a bit dangerous; somebody might want to display a colon inside a tab name. Perhaps it would be better to follow the precedent of [SearchTabsFilters] and create a [SearchTabsPermissions] section.

3.) In permissionBehavior.ini, the defaultAction lives outside of a section header. This is unprecedented in VuFind and might cause some confusion, especially since the commented-out "[access.EITModule]" example header above it sort of implies that it belongs inside another section. I definitely understand why you might want to have these free-floating settings, since if you put general settings inside a section, there's a chance the section name will conflict with a permission name. However, it's at least worth considering a non-conflicting section name for clearer formatting... or if that's not deemed a good idea, we should move general settings to the very top of the file above more of the existing comments and put them under a comment clearly indicating that they must NOT be inside a section.

4.) Is it intentional that you cannot configure the code to throw a generic Exception? (At least, I think this is the case based on reading the code -- is_subclass_of('Exception', 'Exception') will return false)

5.) Right now, the PermissionDeniedManager wraps around the authorization service. Thus, the class is doing more than just managing permission denied actions, because it is also checking the permission. I wonder if this makes things a bit unclear. Perhaps we should consider some different class/method names, or else consider separating the two concerns to limit the scope of the PermissionDeniedManager. One possibility might be to create a simple PermissionManager class that wraps around the authentication service and the PermissionDeniedManager. Obviously, this is just a first thought as a result of glancing at the code -- you don't have to take any action on the suggestion. But something to think about!

Anyway, that's probably enough for the moment to keep the conversation alive. I'm interested to hear your thoughts whenever time permits.

**Comment by olli-gold** [comment]
I finally had a chance to proceed working on this PR.
So now I have incorporated your suggestions (thank you again for that) and hopefully improved things a little bit.
I still have to adopt the tests to the refactorings.

**Comment by demiankatz** [comment]
Thank you! I will take another look as time permits!

**Comment by olli-gold** [comment]
I have upgraded the tests and access validation of the controllers in order to match the refactored classes.

Doing that I have decided not to support the showTemplate option for Controllers - I think that this was too complex to implement for a use case which is not the most likely one... So I think this is ready for review now, whenever you have the time to do that.

**Comment by demiankatz** [comment]
I agree that the showTemplate option may be out of scope. Definitely no need to waste effort on it before we know there is a use case.

I've taken a few minutes to merge the latest master code into this branch. Please let me know if I've broken anything in the process (though I don't think I have -- there was only one minor conflict).

I still need to find time to give this a thorough test and review. In the meantime, a couple of questions to keep the ball rolling:

1.) I notice that you have some error_log() calls in the AbstractBase controller's exception handling logic. Was this just for debugging purposes, or was it intended as a long-term feature? If a feature, I wonder if we'd be better off using VuFind's native logger so that the messages can be sent to different places in a more controlled fashion.

2.) The build is currently failing with some "cannot redeclare class" errors -- is it possible that some of your new test classes are named incorrectly?

Thanks!

**Comment by olli-gold** [comment]
Thank you for your feedback - I don't think this PR has high priority, so take your time testing it.

1) This was intended to be a feature - and of course its a good idea to use the native logger instead of error_log. I'll change that later (I don't think its gonna be a big deal, is it?).
2) Yes, my test class had an inappropriate class name, which was due to cut and paste of things... I have corrected that, so hopefully the tests will work now.

**Comment by demiankatz** [comment]
1.) Yes, changing the logger is no big deal. I've added an item about this to the TODO list in the description so we don't lose track of it. Not high priority, of course!

2.) It looks like some tests are still failing. I think I've just fixed one of them by normalizing the language file, but the rest may merit a closer look at the Travis build details. Let me know if you'd like me to assist with this! I'm hopeful that once the tests are passing, we may also be able to clean up most of the remaining style issues automatically with tools in order to get the build into a passing state.

**Comment by olli-gold** [comment]
Sounds great. I have also cleaned up the todo list for this PR a bit, as I think it was partially outdated. I'll have a look into the failing tests again.

**Comment by olli-gold** [comment]
I have made a bit of a progress today, but I recognized, that I will have to document these new functions a little bit more. The tests are ok now and the style issues are fixed, but I guess I will have to have a look on my testsystem, if this is really doing what I expect it to do. It has been a too long break...

**Comment by demiankatz** [comment]
Thanks for the progress. Please let me know if I can do anything to help and/or when you are ready for me to give this another review.

**Comment by olli-gold** [comment]
I have started documentation of the new feature describing some use cases and how to configure them: https://vufind.org/wiki/configuration:permission_options

There are still some use cases left, which are not covered by the implementation yet and I'm still not happy with the display of the permissiondenied-template. I would like to display a selection of options, what to do to get access, but this is not working as I would like it to work.

**Comment by demiankatz** [comment]
Thank you for this excellent start on the documentation. Browsing through it, it looks very clear and thorough. I will try to find some time to test this latest iteration of the code when I have a bit more time. Unfortunately, I think it is unlikely to be completed in time for release 3.1, so I have adjusted your documentation to list this as a 4.0 feature.

One very minor enhancement suggestion based on reading the docs: it appears that right now, the "showMessage" option always uses the "error" namespace in the flash messenger. It might make sense to add another optional parameter to set the level (in case somebody wants to use 'info' or 'warning' instead under some circumstance). I don't think this would be difficult to implement, though perhaps it conflicts with the key/value pairs alluded to by the .ini file (but not the wiki).

**Comment by olli-gold** [comment]
Thank you for your comment. I guess it's really to late to get that into 3.1. Perhaps it can get it into a 3.1.x or 3.2? Its also ok to wait until 4.0, though.

Yes, the showMessage redirecting to an error page is perhaps kind of bad. I think its a good idea to setup different levels to address different templates. Perhaps that's even a good idea to improve the display of suggestions what to do to get permission (which might be different depending on the page, which was called without having permission). I'll check that.

**Comment by demiankatz** [comment]
I think 4.0 is actually not too far off -- my expectation is that there will be no 3.2, and 4.0 will be the result of the roadmapping conversations at this year's Summit (so, the release that comes about 6 months after 3.1).

**Comment by demiankatz** [comment]
@olli-gold, I've just updated this branch to merge in some changes @EreMaijala made recently to master. It is now possible to specify a default permission denied behavior on a per-controller basis, and I had to resolve some conflicts to make that work with this branch. In the process, I also did some code simplification and made some of the configuration case-insensitive for broader compatibility. Also, at Ere's suggestion, I changed the "promptlogin" setting to "promptLogin" for improved readability (though the case-insensitive evaluation should allow either version to work).

I haven't had time to test these changes yet, so you may want to look at the behavior more carefully the next time you are able to work on this. However, I wanted to be sure to get the merging done now while the reason for the changes was fresh in my mind. Please let me know if you have any questions or problems!

**Comment by olli-gold** [comment]
Thanks for pushing this PR a little bit forward! And sorry, that I had to pause this again... I hope I can continue working on this soon (if there is still demand for such a function).

**Comment by demiankatz** [comment]
@olli-gold, I noticed that this PR had a conflict with master, so I have done a merge and resolved it. Once again, I haven't taken the time to test out the functionality yet. Is this still on your to-do list, or do you need us to put some more time into it on this end? There's still no huge rush on this, but of course I'd like to move it forward eventually!

**Comment by olli-gold** [comment]
I'm very sorry, that I have lost focus on this for such a long time... I'm not sure, if this PR is still necessary after Ere has added some functions, which seem to be very near to the goals of this PR. I'll try to have a look into this again to see, what is still missing to push this PR a little bit forward or even to complete it finally.

**Comment by demiankatz** [comment]
No problem -- and please let me know if/where/how I can help!

**Comment by demiankatz** [comment]
@olli-gold, I finally have some time to work on this, so I have been bringing it up to date and making some adjustments. I hope that I may be able to get this merged in time for release 4.1. Please let me know if you would like to discuss/review any of my changes before they get merged. Right now work is still very much in progress, and some things may be broken or inconsistent. Obviously I won't merge until I've finished cleaning up my mess... but if you want me to invite you to a code review when I'm done and wait for your approval before proceeding, I'd be more than happy to do so. Thanks for all of your work on this!

**Comment by olli-gold** [comment]
Thank you very much for pushing this forward! Admittedly this ticket gnaws at my conscience as it is so old and still not finished - and I'm sorry that you are the one who has to push this forward now, although I had committed to do that.
I would also appreciate to get this finally merged into 4.1, so that this can be closed. I'm absolutely willing to review the changes and to test the whole thing on my side and I hope, this will be a bit of help for you (that's surely the least I can do). If I can do anything else, please let me know!

**Comment by demiankatz** [comment]
@olli-gold, no problem, I understand how it can be. I appreciate your willingness to test and review. I'll try to finish my work on this this week before I leave on vacation, and I'll invite you to a formal GitHub review when I'm ready for you to take a look at everything. Thanks again!

**Comment by demiankatz** [comment]
@olli-gold, it turns out that I can't add you as a reviewer of this PR, since you opened the PR in the first place!

In any case, I believe that I have completed the work to my own satisfaction; I have significantly refactored and renamed things in an effort to make this as clear and simple as possible -- though of course it is entirely possible that there is still room for improvement!

Please let me know if you have any questions, concerns or problems with this version of the code. If you are happy with it, I will consider merging to master after I return from my vacation in a couple of weeks.

Thanks again for all of your work on this -- you provided a very solid foundation for me to build from!

**Comment by olli-gold** [comment]
Great! Thank you very much for moving this forward, so that it can obviously get finished in the near future.
I will have a look at this while you are on vacation and comment here.

**Comment by olli-gold** [comment]
I have taken a quick look over the changes and tested it here (this was not a complete review, but at least I started). 
One point, which was irritating to me, was in the section of Primo. I configured the search tabs, so that I should not have been able to search in Primo. The Primo search tab was missing, as I expected. But then I tried to use the module by a URL with a query, and was surprised, that this worked. 

These are my sections in permissions.ini:
```
[access.Primo]
require = ANY
ipRange = "our IP-Range"
role[] = loggedin
permission = primoPermission.onCampus

[default.primo]
require = ANY
role[] = loggedin
permission = access.PrimoModule
```
And this is my permissionBehavior.ini
```
[access.PrimoModule]
deniedTemplateBehavior = "showMessage:"
deniedControllerBehavior = "exception::You are not authorized to use this module!"
```
With this configuration I would have been expecting to get the exception defined in deniedControllerBehavior of [access.PrimoModule]. But the search was done without problems.

I'll try to continue testing next week, but wanted to mention this before I'm leaving for some days off.

**Comment by olli-gold** [comment]
Thank you for the explanation. I tried adding `$this->accessPermission = 'access.PrimoModule';` into the controllers and that worked as expected. I guess that's enough flexibility.
We could address your alternative approach in a future version, but I think for the basic idea of having an improved use of permissions the mission is accomplished with this PR.

So I'm voting for merging this into the master to have it ready for the next release. Thank you for all of your work on this feature!

**Comment by demiankatz** [comment]
Great, thanks! I'll leave this open a couple more days in case anyone has anything to add following discussion on today's developers call... but if I don't hear anything by the end of the week, I'll go ahead and merge. I appreciate the time you spent both developing and reviewing this!

**Comment by demiankatz** [comment]
Wiki documentation at https://vufind.org/wiki/configuration:permission_options has just been updated.

**Comment by demiankatz** [comment]
@olli-gold, I have manually merged this to master in order to clarify the commit history. (I accidentally neglected to put the right committer email on the main commit, though -- I had intended to give you credit for the bulk of the work; sorry about that). In any case, thank you again for all of the work on this. It will be included in release 4.1!

**Pull request closed without merging**
