### PR TITLE
Font Awesome 4.6 and Accessibility

### PR DESCRIPTION
**Pull request by crhallberg**
Font Awesome 4.6 released and improved accessibility. They had some [good advice](http://fontawesome.io/accessibility/) on the matter, so I took it.

- [x] Escaped &
- [x] Experiment with FontAwesome LESS

### CODE REVIEW

**Comment by demiankatz** [comment]
A few comments:

1.) Reviewing the diffs on GitHub highlights the fact that there are unescaped ampersands in the href attributes of some tags in vudl/navigation.phtml and browse/home.phtml. Probably worth fixing for the sake of correctness.

2.) Can we come up with a better translation for "toggle_offcanvas"? I don't think anybody is going to know what that means.

3.) I see that you are adding some vudl_* translation strings for new alt texts. Good idea for accessibility, but given that we're planning on removing the existing VuDL code from master due to its Villanova-specific nature, it's probably not worth making the translators do all that work. Should we try to get the VuDL cleanup done sooner rather than later so we can then merge it into this branch and eliminate some no-longer-needed stuff?

4.) I see that you've added all the FontAwesome LESS, but it does not appear that it's currently being used. Would it make sense to include this into compiled.css instead of separately including the minified CSS in order to save on an HTTP call, or is it this way for a strong reason?

Thanks!

**Comment by crhallberg** [comment]
This will become easier with the removal of VuDL (PR #697).

**Comment by crhallberg** [comment]
Not to self, never rebase a branch. This now contains the Remove VuDL PR in it now... Merging manually.

**Comment by crhallberg** [comment]
Merged manually here: c501c939ebd1aee43aa69237caf492738ab421d1

**Pull request closed without merging**
