### PR TITLE
Add support for configurable Collection routes.

### PR DESCRIPTION
**Pull request by samuli**
This extends the current record > collection route mapping to support a configurable set of record > collection pairs.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @samuli, this makes sense to me. I'm at a conference today and tomorrow, but I'll give this a hands-on test later in the week when I'm back in the office and will hopefully be able to merge it quickly.

**Comment by demiankatz** [comment]
@samuli, I tried this out and it seems to be working for me. Just a couple of notes/questions:

1.) I simplified the code a little to use an array_merge instead of a foreach loop; please review and let me know if you have any concerns.

2.) I'm not sure about your use case, but of course as currently implemented, this will only affect the link mapping from the record route to the collection route; it will not affect other hard-coded collection links, like this one: https://github.com/vufind-org/vufind/blob/a595b80d64708f8b3bbb1bedf0ee58cc0a411c90/themes/bootstrap3/templates/RecordDriver/DefaultRecord/result-list.phtml#L56 -- is that a problem?

**Comment by samuli** [comment]
@demiankatz 
1.) This is OK
2.) For our use case this is is not a problem: the template determines the route when using the Url-helper.

**Comment by demiankatz** [comment]
Thanks, @samuli, in that case, I will merge this now. I believe that @EreMaijala has some ideas about further improving the collection routing behavior, but I think we can address that as a separate PR when the time comes, and any future code will still need this configuration hint, so adding the setting now seems reasonable.

**Pull request merged**
