### PR TITLE
Update single-facet.phtml (<div> instead of <li>)

### PR DESCRIPTION
**Pull request by liowalter**
Is this `<li>` tag really wanted ? It is a bit strange as there is no `<ul>`. Shouldn't it be a `<div>` or a `<span>` ? I have the feeling that it is a leftover from the facets refactoring... Thank you !

### CODE REVIEW

**Comment by demiankatz** [comment]
@liowalter, I'm asking @crhallberg to review this, as he probably knows best about the history and possible implications. Thanks for pointing this out!

**Comment by crhallberg** [comment]
I think this was accessibility motivated. Since the [container elements](https://github.com/vufind-org/vufind/blob/master/themes/bootstrap3/templates/Recommend/SideFacets/cluster-list.phtml#L30) for facets are also divs, I think it would make sense to make this change.

**Comment by demiankatz** [comment]
Thanks, @liowalter, I've gone ahead and merged this!

**Comment by liowalter** [comment]
Thank you @demiankatz @crhallberg !

**Pull request merged**
