### PR TITLE
Ezb link resolver access state improvements

### PR DESCRIPTION
**Pull request by lahmann**
This pull request adds support for proper mapping of statuses received from the EZB resolver to access classes in VuFind. Above that it also parses more response-content and adds this information to the `coverage` field of the resolver plugins response.
I also added tests for the EZB resolver using a real-life response from the EZB that covers most of possible cases.

TODO
- [x] Solve broken "more options" link
  - [x] Add `getResolverLink()` method to any other resolver
- [x] Note backward compatibility breaks in changelog (and update other docs as needed)

### CODE REVIEW

**Comment by demiankatz** [comment]
I've asked Markus Fischer if he has time to look at this since he developed the original EZB driver and might have some thoughts. In the meantime, a couple of things from me:

1.) It looks like getElectronicResults is now capable of creating records with no 'title' entry (due to the return value check on the xpath call). Have you checked whether this scenario causes problems? I have a feeling the upstream code may assume that 'title' is set (though I didn't double-check the code... so maybe it's already addressed).

2.) Do you definitely want the "additional information" to replace the standard coverage information rather than augmenting it?

3.) When you implode $additionals and $elements, should there be a space after the semi-colon? (Perhaps this is a difference of convention between English and German?)

Anyway, no strong feelings on any of this from me -- just things that a quick code review suggested might be worth thinking about.

**Comment by lahmann** [comment]
Thanks Demian for your comments and sorry for getting back to this pull request this late.

1.) As far as I can tell (after checking AjaxController and resolverLinks.phtml) records containing no title are not causing problems. But maybe inserting a default title if href is set might be a good idea - this could be done best in the template. What do you think?

2.) The coverage information only gets replaced if useful information extracted from the resolver response exists. If the additional information exists it should be more valuable than the hard coded coverage information. Above that the response always contains access states that will be passed to the view as 'access' having the same value as the hard coded coverage information regarding access status of the record. Therefore I think it is save to use the hard coded coverage information only in case no additional information was found.

3.) Good catch! Fixed it :)

**Comment by demiankatz** [comment]
1.) I agree that making the template cover the missing title case is the safest and most broadly useful thing to do, assuming it needs to be done at all.

Everything else sounds good. Let me know if you need me to review this again after making a template change, or if you think it's good to go as-is. Either way, I'll be happy to merge it when you're ready (though I'd also still welcome input from @flyingfischer if he has time).

**Comment by lahmann** [comment]
1.) Well, currently we do not insert default values for any field in `resolverLinks.phtml` therefore it might be most consistent if we leave it this way or add default values for every field (coverage, title, service_type - just adding a default for the title would break consistency imo). As so far nobody complained I would rather avoid adding default values plus their translatables etc...

I just talked the other day with @jochen-lienhard and he plans on testing the resolver driver by the end of this week. So, if @flyingfischer does not find time to take a look into this pull request we will have at least one tester that is not me :)

**Comment by jochen-lienhard** [comment]
Hmm, the 'more options' link below the EZB informations does not work.

How do you tell the EZB, what your LIBID is? I can not see any parameter for this. Or is the IP-adresse of the vufind server the identifier?

Why do you not use the ZDBID?

Do you analyse moving walls?

**Comment by lahmann** [comment]
Hi Jochen, thanks for taking a look at the EZB resolver!

1.) Yes, the "more options" link is not working and has never been afaik. The EZB resolver needs to rewrite the OpenUrl to OpenUrl 0.1 to comply with the EZB/JOP-API.

2.) The most generic approach to tell the EZB/JOP-API which library the user is coming from is to pass the IP (that's how it's implemented right now). This approach obviously has its disadvantages as the library specific availability information is incorrect if the user is in a non-campus IP-range. A better but EZB/JOP specific approach would be to pass the various custom parameters EZB/JOP allows to the API (e.g. BibID) - the same applies to journal identification (ISSN etc. currently, better would be ZDBID). We actually have extended the EZB resolver for our catalog to use all these parameters, but this would require to add custom parameters to VuFind's `[OpenUrl]` settings for this single resolver.
If you like, I can share our custom EZB resolver (this also extracts the `Readme` information). Another idea is (I'm planning to show this briefly on the VuFind Summit in Germany in October) to allow multiple resolvers and move the resolver configuration from config.ini to a separate Resolver.ini which would imo allow to add resolver specific parameters.

**Comment by jochen-lienhard** [comment]
I forgot to say, that it looks good.

Perhaps we can add the "pid" parameter to the config for the openurl. Than you can add such things like the BIBid.

We think about to use the print information to expand the holding information too.

**Comment by lahmann** [comment]
Thanks! :)

The "pid" parameter might be a pragmatic addition to solve the BIBid problem, but the ZDBID could not be covered by that as it needs to be retrieved for each journal from a custom index.

The print information should be completely covered in this version of the EZB resolver, though the data structure returned by the resolver service would need some customization to use it for holding information. If it's sufficient for you to show the plain text holding information - this should work out of the box.

**Comment by flyingfischer** [comment]
You can add

$openURL .= '&pid=client_ip%3D' . $_SERVER['REMOTE_ADDR'];

to the OpenURL-String. In this way it will transmit the requesting IP and availability will be shown upon you actual IP range.

**Comment by lahmann** [comment]
Thanks @flyingfischer for taking time to looking into this!

Isn't this already done in https://github.com/finc/vufind/blob/2d66dd0fc6f2de47ac508307420ba8547897b88e/module/VuFind/src/VuFind/Resolver/Driver/Ezb.php#L110 ?

**Comment by jochen-lienhard** [comment]
Hmmm .... but if some hosts the catalog for a library it does not work. What do you think about a mapping of the rfr_id to the bibid for the ezb resolver?

**Comment by flyingfischer** [comment]
You right, the code is already in place. I did write the driver for http://bibnet.org/vufind/ This is exactly a "hosted" situation, open to many institutions. The IP of the requesting client gets transmitted to JOP in the pid zone. This works perfectly (in embeded mode).

**Comment by flyingfischer** [comment]
...and actually they are preparing a hidden parameter rlink=1 which would cause always article level linking (if available) even when you are not a EZB member. This is already implemented in the (different) API of the EZB and should make it's way into JOP too soon.

We the could use: $openURL .= '&rlink=1&pid=client_ip%3D' . $_SERVER['REMOTE_ADDR'];

Right now the JOP crashes with an error, if you send an unknown parameter, which is a very uncomfortable behaviour in the context of OpenURL...

**Comment by lahmann** [comment]
@jochen-lienhard I have created a branch in our finc repo with the customized EZB resolver: https://github.com/finc/vufind/tree/ezb_resolver_customized

All changes are included in the last commit: https://github.com/finc/vufind/commit/fc352c71fbf6faf0500afc4ca2cd20d7c6944926

**Comment by demiankatz** [comment]
I've added a TODO list to the top of this pull request so we can figure out when the work is done and it is ready to be merged. I've just put one item there, but if there are other outstanding issues, please add them.

Regarding the item I added, the "broken more options" link that @jochen-lienhard pointed out, I think there are two possible solutions:

1.) Add a "getMoreOptionsLink" method to the resolver driver that, by default, just passes back the unmodified OpenUrl, but in the case of EZB can return the translated version

2.) Add a "supportsMoreOptionsLink" method that can be set to false in EZB to disable the broken link entirely.

I think option 1 is preferable if it is feasible, but it's been a while since I've reviewed the code, so I'm not sure if there is some technical reason that this might be difficult.

**Comment by lahmann** [comment]
Fixing the non-functioning "More options" link for the EZB resolver was a bit more complicated than expected: 

1.) The OpenUrl view helper does not have any access to the resolver and depends entirely on the OpenURL provided by the RecordDriver. Therefore fixing the "More options" link for the EZB resolver by introducing a "getMoreOptionsLink" method means to at least instantiate the resolver in the view helper in order to get the appropriate link URL.

2.) The EZB link resolver is actually not suited for displaying its raw results to the user - we get unstyled XML which won't help the user at all. Therefore disabling the "More options" link for some resolvers should be possible.

3.) Although the EZB link resolver's response is not really helpful for the user, configuring the EZB resolver to not embed and autoload the resolver links will result in a faulty "Get full text" link as the linked OpenURL does not work for the EZB resolver (see "More options"). Therefore we also need to call the "getMoreOptionsLink" for the resolver link with disabled embedding and autoload.

The committed draft adds a "getResolverLink" method to the EZB resolver (which needs to implemented in each other resolver after this code got approved - todo added), which will return in most cases the OpenURL but for some resolver (such as EZB) a modified URL. On top of that I introduced another OpenURL setting to enable/disable the "More options" link at all (see 2 for reasons).

Let me know what you think.

**Comment by demiankatz** [comment]
Thanks for the continued work on this, @lahmann. As you say, it is not as simple as it might first appear.

A couple of comments on the latest iteration:

1.) I don't think we can allow the OpenURL view helper to depend upon the resolver driver -- resolver drivers are only required when using the AJAX retrieval method. If you have a resolver that does not support AJAX, we shouldn't create a situation where the non-AJAX version is broken too. One possible approach here might be to create a factory that builds the VuFind\Resolver\Connection. This factory could throw an exception if the resolver plugin manager lacks the required resolver driver. Then in the AJAX routine, we can call the factory inside a try..catch that puts the error output return inside the catch block. Inside the view helper, we could make the same factory call inside a different try..catch block that sets a default resolverLink value (`$this->openUrlBase . '?' . $this->openUrl`) if no resolver can be found to calculate one.

2.) It may be worth considering whether the "show more link" setting makes more sense as a config.ini setting (as you have implemented) or a resolver driver setting, or both -- i.e. maybe we want the user to be able to shut this off in config.ini, but we also want a resolver driver to be able to say "sorry, can't do that" and override the user setting. I think the resolver driver approach reduces the necessary amount of user configuration and might even remove the need for the config.ini setting entirely. (Since if a user really wants to get rid of this for cosmetic rather than technical reasons, they could just as easily customize the relevant template).

Hopefully that's food for thought that can help guide the next iteration. Let me know if you disagree with any of this or need me to look at other specific areas more closely.

**Comment by lahmann** [comment]
Back again - sorry for the long time of silence.

1.) Demian, I agree with you - therefore I have hopefully chosen a less complicated way to deal with the resolver driver in the view helper. If the resolver driver does not exist the "More options" link will be generated as before (base + openurl) - this does also serve as fallback behavior for the other implementations of getResolverLink() in SFX, 360, Redi and Demo resolver driver.

2.) I have absolutely no strong opinion about the config option - if you think it's overengineered I am happy to get rid of it. Just let me know :)

Please let me know what you think and hopefully we can finish this ancient pull request as soon as possible.

**Comment by demiankatz** [comment]
André,

Thanks for the progress on this!

A couple of comments:

1.) I wonder if getResolverUrl would be a slightly better name than getResolverLink for the new driver method.

2.) If we're going to implement the new method on all of the drivers, we should add it to the interface. I also wonder if we would be better off making it return a valid URL instead of false in those cases too (since I think we could easily return $this->baseUrl . '?' . $openUrl in all of the existing drivers). On the other hand, if we DON'T want to have to implement this in every driver, what if we gave it a more specific name, like getAdjustedResolverUrl, and did an is_callable check to see if the method exists. Then we would only have to implement the method on drivers that require it, and the rest could omit the code entirely and fall through to the default "false" case.

3.) I think for now I prefer having a supportsMoreOptionsLink() method on the resolver driver, rather than having a config.ini setting. The nice thing about this is that we could always add logic to load the config.ini setting into the resolver driver to influence the supportsMoreOptionsLink method in future if we want to make this more configurable.

4.) I wonder if we should have a default AbstractDriver implementation to allow all drivers to inherit generic functionality for supportsMoreOptionsLink (and, depending on your thoughts on ideas suggested above, getResolverLink or equivalent).

I realize that your time is short these days, so please don't feel obligated to implement all of these suggestions -- I'm just brainstorming options. If you like some of these ideas but don't have time to implement, feel free to add TODO's above, and I can help as time permits. If you think I'm overthinking anything, I'm also open to feedback to that effect!

Thanks again!

**Comment by lahmann** [comment]
Demian, thanks for reviewing the code!

1.) Done - this is especially correct as the Ajax-task is called getResolverLinks which might lead to confusion.

2.) + 4.) I implemented an AbstractBase which implements the default getResolverUrl() to return the base url + open url. I had to adjust the Demo driver a bit - I hope I didn't break anything accidentally.

3.) Done - I reckon supportsMoreOptionsLink() needs to be added to the DriverInterface as well?

I wonder why the tests are failing - one assumption was that the tests invoke the OpenURL view helper which omits the OpenUrlRules thus failing to assert that OpenURLs are active without OpenUrlRules set. So I added a special case for missing OpenUrlRules (bf82247), assuming OpenURLs apply for the current record (which would reduce configuration needs for VuFind instances without very complex data pools as every record gets OpenURLs). But that does not seem to work either and I'm not sure if I'm missing the point - could you please take a look at it? Sometime four eyes see more than two :)

Thanks!

**Comment by demiankatz** [comment]
@lahmann, thanks for all of the work on this! I've made a few minor adjustments and bug fixes. Some notes:

1.) I refactored the Http Client out of AbstractBase, since I'm not sure if we should assume that every driver will always use it.

2.) The broken test was caused by the fact that you changed the signature of the OpenUrl constructor, so the configuration was being treated as the plugin manager. I just added the new parameter to the test and everything went back to normal.

I believe that everything is now ready to be merged; the only thing left to do is update some documentation. Please take one last look at my changes and let me know if you see any problems. If it looks good to you, I'll update the wiki and merge the PR as soon as I hear back from you.

Thanks again!

**Comment by lahmann** [comment]
Demian, thanks a lot for finalizing the code (stupid me that I forgot to reflect the changed OpenUrl constructor signature in OpenUrlTest...) - it looks great to me!

Let me know if I you need any help with the wiki.

Thanks again!

**Comment by demiankatz** [comment]
Okay, all merged! Here's the updated link resolver driver wiki page:

https://vufind.org/wiki/development:plugins:link_resolver_drivers

Please feel free to make further edits if you spot anything wrong or missing.

**Comment by lahmann** [comment]
Demian, thanks a lot!

**Pull request merged**
