### PR TITLE
Add support for checking selected holds for different pick up locations.

### PR DESCRIPTION
**Pull request by EreMaijala**
When editing multiple holds, they may have different pick up locations. When the situation is detected, editing of pickup locations is disabled. A message telling the user to edit an individual hold to change the pickup location is displayed instead. Since the check may be slow, a driver may indicate that only up to a configured limit of holds should be checked.

The Demo driver change makes it so that different pick up locations are returned for the second hold so that this functionality can be tested.

The possibility of using any request groups for short-circuiting the checks was considered, but it's possible that request groups have identical pickup locations, so they can't be used for this purpose.

### CODE REVIEW

**Comment by demiankatz** [comment]
The full test suite is passing for me. I'd like to add a new Mink test to verify this when time permits, though. I'll try to find time soon!

**Comment by EreMaijala** [comment]
@demiankatz I should learn to do that as well, but I'd appreciate help here!

**Comment by demiankatz** [comment]
@EreMaijala, I have started building a test, but it's not passing due to what appears to be a bug in the new code. It looks like, if I create holds with mismatched pickup locations and then submit an edit dialog box without actually changing anything, the lightbox displays a generic error message. This is what shows up in my vufind-exception.log:

<pre>
2021-06-17T16:34:36-04:00 CRIT (2): TypeError : Argument 3 passed to VuFind\Controller\HoldsController::getUpdateFieldsFromGatheredDetails() must be of the type array, null given, called in /home/dkatz/vufind3/module/VuFind/src/VuFind/Controller/HoldsController.php on line 211
Server Context:
Array
(
    [REDIRECT_VUFIND_LOCAL_DIR] => /home/dkatz/vufind3/local
    [REDIRECT_STATUS] => 200
    [VUFIND_LOCAL_DIR] => /home/dkatz/vufind3/local
    [HTTP_HOST] => localhost
    [HTTP_CONNECTION] => keep-alive
    [CONTENT_LENGTH] => 182
    [HTTP_SEC_CH_UA] => " Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"
    [HTTP_ACCEPT] => */*
    [HTTP_X_REQUESTED_WITH] => XMLHttpRequest
    [HTTP_SEC_CH_UA_MOBILE] => ?0
    [HTTP_USER_AGENT] => Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36
    [CONTENT_TYPE] => application/x-www-form-urlencoded; charset=UTF-8
    [HTTP_ORIGIN] => http://localhost
    [HTTP_SEC_FETCH_SITE] => same-origin
    [HTTP_SEC_FETCH_MODE] => cors
    [HTTP_SEC_FETCH_DEST] => empty
    [HTTP_REFERER] => http://localhost/vufind_test/Holds/List
    [HTTP_ACCEPT_ENCODING] => gzip, deflate, br
    [HTTP_ACCEPT_LANGUAGE] => en-US,en;q=0.9
    [HTTP_COOKIE] => language=en; language=en; VuFindTestSuiteRunning=1; VUFIND_SESSION=t72ffmklvdakvcst271ga7s97b; ui=standard
    [PATH] => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
    [SERVER_SIGNATURE] => <address>Apache/2.4.41 (Ubuntu) Server at localhost Port 80</address>

    [SERVER_SOFTWARE] => Apache/2.4.41 (Ubuntu)
    [SERVER_NAME] => localhost
    [SERVER_ADDR] => ::1
    [SERVER_PORT] => 80
    [REMOTE_ADDR] => ::1
    [DOCUMENT_ROOT] => /var/www/html
    [REQUEST_SCHEME] => http
    [CONTEXT_PREFIX] => /vufind_test
    [CONTEXT_DOCUMENT_ROOT] => /home/dkatz/vufind3/public
    [SERVER_ADMIN] => webmaster@localhost
    [SCRIPT_FILENAME] => /home/dkatz/vufind3/public/index.php
    [REMOTE_PORT] => 44688
    [REDIRECT_URL] => /vufind_test/Holds/Edit
    [REDIRECT_QUERY_STRING] => layout=lightbox
    [GATEWAY_INTERFACE] => CGI/1.1
    [SERVER_PROTOCOL] => HTTP/1.1
    [REQUEST_METHOD] => POST
    [QUERY_STRING] => layout=lightbox
    [REQUEST_URI] => /vufind_test/Holds/Edit?layout=lightbox
    [SCRIPT_NAME] => /vufind_test/index.php
    [PHP_SELF] => /vufind_test/index.php
    [REQUEST_TIME_FLOAT] => 1623962076.747
    [REQUEST_TIME] => 1623962076
)

Backtrace:
/home/dkatz/vufind3/module/VuFind/src/VuFind/Controller/HoldsController.php line 211 - class = VuFind\Controller\HoldsController, function = getUpdateFieldsFromGatheredDetails, args: none.
/home/dkatz/vufind3/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php line 77 - class = VuFind\Controller\HoldsController, function = editAction, args: none.
/home/dkatz/vufind3/vendor/laminas/laminas-eventmanager/src/EventManager.php line 331 - class = Laminas\Mvc\Controller\AbstractActionController, function = onDispatch, args: none.
/home/dkatz/vufind3/vendor/laminas/laminas-eventmanager/src/EventManager.php line 188 - class = Laminas\EventManager\EventManager, function = triggerListeners, args: none.
/home/dkatz/vufind3/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php line 103 - class = Laminas\EventManager\EventManager, function = triggerEventUntil, args: none.
/home/dkatz/vufind3/vendor/laminas/laminas-mvc/src/DispatchListener.php line 138 - class = Laminas\Mvc\Controller\AbstractController, function = dispatch, args: none.
/home/dkatz/vufind3/vendor/laminas/laminas-eventmanager/src/EventManager.php line 331 - class = Laminas\Mvc\DispatchListener, function = onDispatch, args: none.
/home/dkatz/vufind3/vendor/laminas/laminas-eventmanager/src/EventManager.php line 188 - class = Laminas\EventManager\EventManager, function = triggerListeners, args: none.
/home/dkatz/vufind3/vendor/laminas/laminas-mvc/src/Application.php line 331 - class = Laminas\EventManager\EventManager, function = triggerEventUntil, args: none.
/home/dkatz/vufind3/public/index.php line 71 - class = Laminas\Mvc\Application, function = run, args: none.
</pre>

I am pushing up my work-in-progress test. I'm not sure whether or not it will pass completely when this problem is fixed, but hopefully it's at least close to being correct. Please let me know if you want me to put some time into troubleshooting this problem and/or the remainder of the test... but I figured I might as well pass the ball back to you for the moment.

Regarding learning about writing Mink tests, hopefully the video I recorded on the May Community Call will be helpful, once we find time to edit and post that. I'll try to remember to let you know when that's up.

**Comment by EreMaijala** [comment]
@demiankatz I realized that the wording of the message caused some confusion; the problem wasn't that the holds had a different pick up location but that the options differ. I revised the message and the test accordingly. I also fixed the issue you reported and modified the pickup location retrieval to return any common pick up locations for the selected holds.

I did not change the functionality, but the plumbing now makes it possible to change the template so that if the options differ but have some common choices, those choices would be displayed alongside a message telling that more options would be available for individual holds.

**Comment by EreMaijala** [comment]
@demiankatz Also, thanks for working on the tests. They are now passing for me.

**Comment by demiankatz** [comment]
Great, thanks for the fixes and test improvements. Merging now!

**Pull request merged**
