### PR TITLE
Template Path Helpers

### PR DESCRIPTION
**Pull request by crhallberg**
Adds two view helpers:

`parentTemplate($file, [$theme])` searches the theme's parent stack until the file is found. A second parameter can be sent to specify a particular parent template to use.

`templatePath($file, $theme)` allows you to get the path for any template from any other theme.

```php
<?php include $this->parentTemplate('footer.phtml'); ?>
```

This is intended to be used with Slots (#1454).

### CODE REVIEW

**Comment by demiankatz** [comment]
@crhallberg, it would probably be a good idea to add some tests for these before we merge them. Let me know if you'd like any help with that!

**Comment by crhallberg** [comment]
Is this ready to go?

**Comment by demiankatz** [comment]
Might be worth cherry-picking c0f1370 onto master before merging this since the package.json changes are totally unrelated to the rest of this work, and it would make more sense as a separate commit. Other than that, I have no objection to merging this, since it's just adding new helpers that aren't being used yet, so it's not going to break anything. We should be sure we document these in an appropriate place, though.

**Comment by crhallberg** [comment]
The diffs are less than that commit so I'll do it manually.

**Pull request merged**
