### PR TITLE
Set up GitHub code scanning with CodeQL.

### PR DESCRIPTION
**Pull request by demiankatz**
This replaces LGTM, which is shutting down in December.

TODO:
- [x] Clean up alerts if practical
- [ ] After merging, examine other possible code scanning workflows to add

### CODE REVIEW

**Comment by EreMaijala** [comment]
@demiankatz I checked the cookieconsent alert, and it's a false positive. The result is added to a node's textContent property, so even if the sanitization didn't work, it wouldn't cause any issues. The tag removal is there to just make a label from HTML input for accessibility, and the input comes from configuration and translations, so I'd consider it trusted.

**Comment by EreMaijala** [comment]
@demiankatz The other issues look like false positives to me, so I'd mark them ignored as well.

**Review by EreMaijala — APPROVED** [review]
The new workflow looks good to me.

**Comment by demiankatz** [comment]
Thanks, @EreMaijala, it's possible to dismiss false positives through the GitHub UI, so I've done that on the critical alert you analyzed, and now the build is showing as passing here. Merging now!

**Pull request merged**
