### PR TITLE
Added support for multiple checkbox facets for the same field (e.g. P…

### PR DESCRIPTION
**Pull request by EreMaijala**
…rimo uses tlevel for both 'available online' and 'peer reviewed'). Added handling of checkbox facets for getFacetList() so that they can be displayed nicely in the search history.

### CODE REVIEW

**Comment by EreMaijala** [comment]
Here's an example of what this PR allows:
```
[CheckboxFacets]
tlevel:online_resources = "Online Resources"
tlevel:peer_reviewed = "Peer Reviewed"
```

**Comment by demiankatz** [comment]
A few questions/comments based on a quick read/test:

1.) Why the special case to hide the displayText when a field matches a checkbox filter? This means that if you create a checkbox filter that overlaps with a facet field, then users won't be able to see the values of related facets that they select (suppose you do a "format:Book" checkbox filter for quick access to books... then other selected facets display as blank strings in the filter list).

2.) What is the purpose of the new $value parameter to getFacetLabel? (Sorry if this is obvious, but from reading the code it's not immediately obvious to me why this is needed).

3.) Why the hard coded addition of checkbox facets in initFacetList()? It is intended that checkbox facets should be added conditionally by recommendation modules, which could be configured to point to arbitrary sections of arbitrary .ini files. Hard-coding this here could cause a variety of weird side effects depending on existing configurations.

These issues aside, though, the underlying functionality you're aiming for is definitely a worthwhile addition, and the fact that it doesn't currently work is unintuitive.

**Comment by EreMaijala** [comment]
1.) There's no actual value to display in checkbox facets (you don't want '1' there).

2.) It's used right there in getFacetLabel() to check if we have a checkbox facet with the given value so that its description can be returned. We also have other situations where the value would be useful when determining proper label to display.

3.) That was a mistake and it should work fine without it too. Now fixed.

**Comment by demiankatz** [comment]
Not sure what combined.zip is, but guessing that was committed by accident. Will exclude when merging to master.

**Comment by demiankatz** [comment]
Okay, manually merged to master with a revised commit history.

**Comment by EreMaijala** [comment]
Thanks for catching that! It was indeed an accident (luckily just some theme files regarding combined search).

**Pull request closed without merging**
