### PR TITLE
adds suggestion to disable all facets/filters for no hits results

### PR DESCRIPTION
**Pull request by olli-gold**
In our old TUBfind we had a suggestion, when the user got no results while having set facets or filters to disable them. This PR adds this feature to VuFind2.

### CODE REVIEW

**Comment by demiankatz** [comment]
Have you looked at the existing SwitchQuery helper at all? I realize that this and that are looking at different aspects of the user input, but they're really accomplishing much the same purpose. It might be valuable to have a single helper that provides both types of recommendations.

If you've already looked at that and decided it's better to keep this separate, that's fine -- I'll review this as-is.

If you haven't seen it before, I'd be interested to hear your thoughts (and would be willing to help brainstorm the best way to incorporate the two things).

Let me know what you think, and thanks for sharing this!

**Comment by olli-gold** [comment]
I thought the SwitchQuery helper would be used to only recommend using truncation or wildcards, but I didn't see the advanced configuration options in [NoResultsRecommendations]. Perhaps you are right and this kind of suggestions better fits into this helper instead of creating a new one.

I'll try to redesign it and to extend the SwitchQuery helper.

**Comment by olli-gold** [comment]
I guess I need a little more input on this. As far as I can see the SwitchQuery helper returns a list of new search terms and sets a new query based on this list. What I want is something different: I do not want to exchange the search term, but I want to delete the active facets and filters. The actual SwitchQuery helper can't do that currently.

Maybe its better to stick with a new helper for this as the functions are pretty different as a closer look reveals...

What do you think?

**Comment by demiankatz** [comment]
Oliver,

My thought was that right now, SwitchQuery is only concerned with the "lookfor" value, and suggests new values for that parameter... but we could expand it so that it could make suggestions for other parameters (such as "filter") as well. Without a few more minutes of looking at the code, I'm not sure how practical that actually is -- but that was my idea in theory.

If it's easier to keep these separate, we can certainly do that... but I figured I'd suggest this more integrated alternative, since if we're eventually going to decide to refactor these two things together, better to do it up front than have to deal with backward compatibility with a different approach further down the road.

Anyway, let me know if you'd like me to take the time to do a deeper analysis and make more detailed suggestions. I can do that later in the week when I have more time if it would be helpful.

Thanks!

**Comment by olli-gold** [comment]
I really think its easier to keep these things separate. As you wrote, all checks in SwitchQuery are concerning the lookfor parameter. For my use case, I do not need the lookfor parameter. And I don't want to suggest other values for filters, but I want to remove all filters instead. This is a special case, which has not very much in common with a suggestion of other lookfor or other parameters and that's why I would prefer to keep the PR just as it is.

Of course it would be possible to expand the SwitchQuery helper, but this would make the helper more complex than it needs to be. I know that on the other side of course its better to have as few files as possible, and it makes refactoring a bit more difficult. It's not easy to decide, which approach is better for this case, but I think I would take the one as it is now.

**Comment by demiankatz** [comment]
Works for me. I'll take a closer look at this soon. Thanks for taking the time to consider the alternative!

**Comment by demiankatz** [comment]
Okay, I've just tested this out. Looks pretty good. Just a couple of comments:

1.) If you pass false to getFilterList(), it will include active checkbox filters. I don't think you need a separate getCheckboxFacets() call and loop in your code.

2.) Do you think there's really a value to including a count of filters in the message displayed to the user? You might be able to further simplify the code if you don't include the number. (If you feel the number is valuable, I don't mean to strip off functionality -- but my personal feeling is that it doesn't really add useful information). Including the number also creates the awkward need (at least in the English text) to say filter(s) / facet(s) to account for the (probably very common) case of a single applied filter. If you skip the number, you could probably make the text say something like "You have applied one or more facet filters..." and the language seems a bit less awkward.

3.) Speaking of the text, it might be worth adding a second sentence saying something to the effect of "If you remove filters, you may retrieve more results." to help motivate the user to click the link, and to set context.

4.) I don't think getResults() is the best method name for use in your new module. If you decide to keep the count, I'd change it to getFilterCount() (and change the type hint to int). If you agree that we don't need the count, I'd change it to hasFilters() and change the type hint to bool.

5.) We need a template for this in the jquerymobile theme, since jquerymobile will attempt to load this module when it is active. We can obviously save that for last -- might as well get the wording to a state we both like before we create a second template that needs to be maintained. However, we should be sure to remember to do it before we merge this to master. If it's inconvenient for you to work with the mobile theme, I'm happy to do this for you. Mainly mentioning it here so I don't forget about it!

Thanks again!

**Comment by olli-gold** [comment]
Thank you for the feedback, Demian!

1) Right, it works fine with getFilterList(false). Thanks for this hint!

2) Right, the difference of singular and plural words also applies to german, so I guess it's really easier to drop the number of filters (I aggree that its not worth the effort).

3) Good idea, I have added this.

4) I have removed the getResults method and therefore added a new method to get the QueryUrl without filters from the controller.

5) I have prepared a template for jquerymobile (using the same code as in bootstrap) - but it would be great if you could review it.

**Comment by demiankatz** [comment]
Thanks again -- manually merged to master with a few minor adjustments. I also turned this on by default, since it seems universally useful.

**Comment by olli-gold** [comment]
Great, thank you!

**Pull request closed without merging**
