### PR TITLE
Facets.js::buildFacetNodes without jQuery

### PR DESCRIPTION
**Pull request by LuomaJuha**
Here is a version where the facetnodes are build without using jQuery.

TODO
- [x] Run full test suite.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @LuomaJuha! I'm going to run my test suite on this and see if there are any problems. After that, I'm hoping @crhallberg can take a look and offer feedback.

**Comment by demiankatz** [comment]
Existing tests are passing (though they may not be exercising every line of code). I'll defer to @crhallberg for further comments!

**Comment by LuomaJuha** [comment]
Noticed that I was appending wrong icon at the end but fixed it. There is not really much difference in this one as it is just creating lots of html elements :)

**Review by crhallberg — APPROVED** [review]
This is well done! I wouldn't change a thing but I do wonder if a basic HTML element factory and parser would come in handy as we build more advanced JS logic away from jQuery. Thank you for this!

**Comment by demiankatz** [comment]
I'm merging now; thanks everyone! If we need an HTML element builder, we can start a new PR as needed. :-)

**Comment by EreMaijala** [comment]
@LuomaJuha can you check exclude facets? E.g. set 

[Results_Settings]
exclude = "*"

Looks like clicking the x behaves the same as clicking the facet value, and there's no space between the x and the badge.

**Comment by EreMaijala** [comment]
Follow-up: #1878.

**Comment by demiankatz** [comment]
Thanks for catching that, @EreMaijala! Looks like we need to add a Mink test case for excluding hierarchical facets.

**Comment by demiankatz** [comment]
I've opened [VUFIND-1471](https://vufind.org/jira/browse/VUFIND-1471) as a reminder to add the test; when I get to Mink testing in my video series, this might be an example to consider using.

**Pull request merged**
