### PR TITLE
Split holds tests into their own class.

### PR DESCRIPTION
**Pull request by demiankatz**
This PR splits the Holds-related tests out of IlsActionsTest in order to make the test suite more granular and to reflect the separation of HoldsController from MyResearchController.

### CODE REVIEW

**Comment by EreMaijala** [comment]
@demiankatz There might be a side-effect that's causing testCancelIllRequest to fail for me with `Selector not found: a.placeILLRequest` when all tests are run, but it works when only IlsActionsTest is run.

**Comment by demiankatz** [comment]
@EreMaijala, this branch is passing all tests in my environment when I run the full suite, so something must be different on your end. Is it possible it's a timing issue of some sort? I'd be interested to know if adding `-Dsnooze_multiplier=2` to the Phing command line makes a difference to your outcome. (This will cause the tests to run more slowly).

**Comment by EreMaijala** [comment]
@demiankatz Right, this seems to be a timing problem on my end.

**Review by EreMaijala — APPROVED** [review]

**Comment by demiankatz** [comment]
Thanks, @EreMaijala!

**Pull request merged**
