### PR TITLE
Update DOAJ OAI configuration

### PR DESCRIPTION
**Pull request by xmorave2**

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks for sharing this. A few questions:

1.) Just to document the history, am I correct in recalling that the doajArticle format became unsupported after a DOAJ infrastructure upgrade a few years ago, and this new format has been more recently introduced?

2.) Should we update the wiki page at https://vufind.org/wiki/indexing:open_data_sources#doaj_-_directory_of_open_access_journalsarticles to reflect these changes? It clearly hasn't been updated in many years and still seems to reflect VuFind 1.x practice. I wonder if it is better to document the DOAJ stanza there rather than in the oai.ini (since in the past, we haven't included a lot of examples in oai.ini -- though I am certainly not completely opposed to changing that practice).

3.) Do we need a separate ISO 639-2b language map, or can we use the existing MARC code list? It appears that most of these values are the same. I haven't recently researched the differences between the MARC language codes and ISO 639-2, so I can't recall if there are significant cases where they contradict one another; I'm just wondering if there is a way we can simplify this to reduce the number of maps we need to maintain.

4.) Do you think we should add a global search-and-replace feature to the vufindharvest project so that correcting the problem described here is possible as part of the harvest process without requiring a separate sed call? That would probably not be difficult to implement if needed.

**Comment by xmorave2** [comment]
Thank for quick response Demian!

ad 1) yes, I think so... I've worked with this documentation: https://doaj.org/features

ad 2) we definitely should update the wiki page - and probably add link to oai.ini instead of example. What do you think?

ad 3) in fact, the marc list is subset of iso 639-2b, so, we can merge it, see the differences here:
https://www.diffchecker.com/ADeXLvUP
the ones with different reading are just other names for the same languages...

ad 4) it would be useful I think, could you take care of it in the vufindharvest project?

**Comment by demiankatz** [comment]
@xmorave2, thanks for the adjustments. I can take care of the vufindharvest piece, though it may be a couple of weeks before I find the time (it's unusually busy for me right now). As long as you don't mind waiting a little bit, I'm happy to do it -- I'll post an update here as soon as I can.

**Comment by xmorave2** [comment]
@demiankatz thanks! I am sure I can wait ;)

**Comment by demiankatz** [comment]
@xmorave2, as promised, I have implemented a global search-and-replace feature in the VuFindHarvest project. However, after doing that, I discovered that the problem was actually not on the DOAJ end, and the search-and-replace feature was not needed to fix it. Instead, there was a bug in the VuFindHarvest tool's namespace handling. I have fixed that bug and updated everything in master, and now this works as expected, so I have merged your PR. Thanks again for your help with this!

**Comment by xmorave2** [comment]
Nice work, thank you Demian!

**Pull request merged**
