### PR TITLE
Update API spec to OpenAPI 3.0.3, update Swagger UI

### PR DESCRIPTION
**Pull request by EreMaijala**
I propose we switch from the pretty old Swagger spec to OpenAPI 3. What do you think?

### CODE REVIEW

**Comment by EreMaijala** [comment]
Note: While OpenAPI 3.1.0 has been published, it's not yet recognized by Swagger UI, so I believe it's better to keep with the older and more supported 3.0.3.

**Comment by demiankatz** [comment]
Thanks, @EreMaijala -- I'll review this in more detail when I have a bit more time (busy day today!). One quick question in the meantime, though: does this impact the API in any way for end users, or is this just an internal rearrangement? I'm just wondering if there are any documentation or backward-compatibility implications we need to worry about.

**Comment by EreMaijala** [comment]
@demiankatz This does not affect the functionality. Only the spec loaded with /api?swagger or now /api?openapi will return a newer version. It could affect someone using a separate very old version of Swagger UI or an old code generator. However, these are typically used once when starting to use an API, not later.

**Review by demiankatz — APPROVED** [review]
Looks good to me, and works fine in my test environment.

**Pull request merged**
