### PR TITLE
Fix escaping of backslashes in ExtendedIniNormalizer.

### PR DESCRIPTION
**Pull request by EreMaijala**

### CODE REVIEW

**Comment by EreMaijala** [comment]
Perhaps a test would be useful, I'll add one.

**Comment by demiankatz** [comment]
Thanks, @EreMaijala -- I've also added comments to this whole function for future reference. I'll wait until your test is added before approving and merging, but this looks good to me.

**Comment by demiankatz** [comment]
Also, should we rebase against release-9.1?

**Comment by EreMaijala** [comment]
@demiankatz Either way works for me. But this could be considered a bug. I added a test, but I'm not entirely happy with how confusing the strings look in the test.

**Review by demiankatz — APPROVED** [review]
Looks good to me, @EreMaijala -- while the test examples are a bit painful to look at, I think some pain is unavoidable when dealing with escaping. At least it's clear that the test is round-tripping the data successfully.

**Comment by demiankatz** [comment]
Manually backported to the release-9.1 branch (and merged from there to dev).

**Pull request closed without merging**
