### PR TITLE
Adds success namespace to flash messages

### PR DESCRIPTION
**Pull request by maechler**
Dear Demian

I updated the flash messages namespaces. Turns out a lot of "info" messages are actually "success" messages.
This implementation already works for bootstrap themes since bootstrap adds styling for alert-success.
I am not very familiar with the other themes, I would like to ask for your assistance / guidance there.

Kind regards
Markus

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks! This looks like a good start. I'll try to give it a closer review (and work on the other themes) next week.

**Comment by demiankatz** [comment]
Markus,

It doesn't look like I have push access to this repo. Would you mind adding me so I don't have to create pull requests for adjustments I make to the code?

Thanks!

**Comment by maechler** [comment]
I just added you! Kind regards

**Comment by demiankatz** [comment]
Thanks!

**Comment by demiankatz** [comment]
This turned out to be very easy -- blueprint already supported .success, and jquerymobile was brought up to date with minor copy-and-paste from blueprint. I've gone ahead and manually merged this to master. Thanks again!

**Comment by maechler** [comment]
Thank you very much!

**Pull request closed without merging**
