### PR TITLE
AJAX error codes

### PR DESCRIPTION
**Pull request by crhallberg**
I made sure every error return in the AjaxController is throwing an appropriate error code. This makes it easier to use jQuery.ajax with success and error.

Wanted to PR to make sure I used the best practices and codes.

Codes used
- 400 - Bad Request
- 401 - Unauthorized
- 405 - Method not allowed
- 500 - Server Error (generic)

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, Chris. This looks like a great start -- it will be nice to actually use HTTP instead of reinventing portions of it unnecessarily.

Regarding your codes used, I think you might want to replace 405 with 403. 405 means "you used an HTTP method that is illegal" -- like you tried to "POST" to a URL that only accepts "GET." It looks like you're using this code in a scenario where a user tries to access another user's content -- which would be a textbook case of 403 Forbidden.

I didn't look too closely at the actual JS changes (the GitHub diffs are not very helpful here) but will give a more careful review next week.

What's the status of testing? Are browser tests passing? Do we need to create some new tests to address more edge cases? Are there any scenarios that remain completely uncovered? I'm happy to help write some more tests next week if necessary... I think the process is getting faster with experience.

**Comment by crhallberg** [comment]
It was a misinterpretation on my part. I though it was a case where the admin can choose whether or not users can delete their lists. Either way that would count as Forbidden.

**Comment by crhallberg** [comment]
There are some error messages that don't have translations:
- [Invalid Method](https://github.com/vufind-org/vufind/pull/587/files#diff-14d20cd3bc2025c3a4d6da9bf54ca59fR97)
- [Argument must be array.](https://github.com/vufind-org/vufind/pull/587/files#diff-14d20cd3bc2025c3a4d6da9bf54ca59fR495)
- [Could not load driver for $resolverType](https://github.com/vufind-org/vufind/pull/587/files#diff-14d20cd3bc2025c3a4d6da9bf54ca59fR1103)
- ['location_' . $result['locationDisplay']](https://github.com/vufind-org/vufind/pull/587/files#diff-14d20cd3bc2025c3a4d6da9bf54ca59fR1266)

**Comment by demiankatz** [comment]
I think all of those untranslated strings are okay. The first three are technical things that an end user should never see -- they're for the information of the administrator. (We should probably double-check that these are not displayed to the user under any normal circumstances, because they really shouldn't be). The last one is a "hook" that allows a library to create custom translations for its library's locations... but since those will be different for every user, we cannot provide them by default (and the default value passed to the translator ensures that we display something reasonable if the translation is missing).

One other note: just happened to see that one of the 403's got changed back to a 405. Was that intentional?

**Comment by demiankatz** [comment]
This is looking pretty good. A couple of questions:

1.) In common.js, in ajaxLogin(), there are two nested AJAX calls. You've eliminated both `response.status == 'OK'` checks, but you've only added in one error handler (on the innermost of the two calls). Is this intentional, or do you also need to add another error handler to the outermost call?

2.) This thread seems to suggest that the success/error callbacks are deprecated in favor of done/fail -- http://stackoverflow.com/questions/13168572/call-to-jquery-ajax-fail-vs-error -- does this affect us, or is somebody misinterpreting something?

3.) You've added this code to lightbox.js:

    if ('undefined' == typeof obj.error) {
      obj.error = function() {
        Lightbox.displayError(response.data);
      };
    }

What is its purpose? In particular, I don't understand where "response" is coming from in this context -- it's not a defined global and it's not passed in anywhere.

Aside from those things, this is looking great, and I think we should be able to merge it soon. However, I'd like to wait and hear your thoughts on these points before I devote any time to testing, because if we find ourselves having to change all of our AJAX calls to avoid deprecation, it's better to do that BEFORE tackling a comprehensive test.

**Comment by crhallberg** [comment]
1. I could not see any logically way that the salt could fail (outside of bad config), or what case to fall to if it were to fail.
2. The Lightbox handler is because almost every ajax that goes through the Lightbox has the same fail handler. I'm thinking of removing the error handlers everywhere that calls Lightbox.ajax.
3. I'm looking into success vs .done. There doesn't seem to be a big performance bonus either way. .done would reduce file size and density slightly. I'll give it a shot.

**Comment by demiankatz** [comment]
1. Previously, it looks like a lightbox error popped up. Is it worth retaining this functionality just to be on the safe side? Imagine, for example, that at the exact moment somebody tries to log in, Apache experiences a problem and starts serving 500 errors across the board. Probably better to pop up an error than to just hang with no apparent action. (Might be worth forcing a failure in that method just to see exactly what behavior you end up with -- I'm willing to give it a shot if you don't have time).

2. Thanks for the refactoring. Looks good, and also clears up my concerns about the lightbox.js modifications.

Let me know what you think about item 1. Once you're satisfied, I'll do some more extensive testing, and perhaps we'll be ready to merge this.

**Pull request merged**
