### PR TITLE
Eliminate ServiceLocatorAwareInterface from search objects.

### PR DESCRIPTION
**Pull request by demiankatz**
TODO
- [x] Finish eliminating interface
- [x] Fix broken unit tests
- [x] Test everything (including running all integration tests)

### CODE REVIEW

**Comment by demiankatz** [comment]
@crhallberg and @EreMaijala: This is a pretty dramatic refactoring to get rid of the Results/Params objects' dependency on the ServiceLocatorAwareInterface. That's going away in Zend Framework 3, and it makes things complicated and confusing. I've switched to constructor-injected dependencies, and I've also done some work to change the way we cache facets to avoid problems with complex objects in the cache.

This is probably easiest to review if you look at it one commit at a time -- I tried to create a logical series of commits here.

@EreMaijala, you might want to pay particular attention to whether this breaks hierarchical facets. As far as I can tell, it behaves the same here as in master -- but during my testing, the translation of applied filters wasn't working the way I expected it to. That's possibly totally unrelated to the refactoring, but it's worth a look.

**Comment by demiankatz** [comment]
Note that as of right now, there are some broken tests because I need to update everything to match the new constructor signatures. I'm out of time for today but will try to work on that tomorrow. Please feel free to hold off on reviewing until I have the whole test suite passing if you prefer.

**Comment by demiankatz** [comment]
Okay, all tests are now passing (including Mink integration tests). I think this is ready to merge to master, but I'd definitely love a bit of extra input before pulling the trigger.

**Comment by demiankatz** [comment]
Good point, @crhallberg -- I didn't have enough faith in the flexibility of the spread operator. Code looks much cleaner now. Thanks!

**Comment by demiankatz** [comment]
Thanks for taking a look. I definitely tried to keep the concern about not creating too many objects in mind here, and as you say, the objects being created here are not too heavy-weight, and in the vast majority of cases, they're being created because we're going to need to use them. Certainly, any time you perform a search, you're going to need the search service. The record loader is probably not needed in all cases, but that's just a lightweight wrapper around the search service, so I think we can afford to include it. Of course, it wouldn't hurt to do some profiling after all of this refactoring is done, just in case we've missed any unnecessarily inefficient behavior.

**Comment by EreMaijala** [comment]
I thought about profiling too, but that can well be done later.

**Comment by demiankatz** [comment]
Thanks for the reviews, everyone -- I've manually rebased this onto master to preserve the full incremental history.

**Pull request closed without merging**
