### PR TITLE
Disable WorldCat v1

### PR DESCRIPTION
**Pull request by demiankatz**
This PR removes all WorldCat search API v1 code and uses aliasing and redirection to ensure that saved records and searches are appropriately re-routed to the new API v2 code. I have tested saving WorldCat searches and favoriting WorldCat records, and after applying this code, favorite lists and saved searches still behave appropriately (though they look slightly different due to API changes).

I propose including this change in a 10.1.1 release to be issued shortly after 10.1; this way, users can upgrade to 10.1 during the window that WorldCat v1 is still online, and then upgrade further to 10.1.1 when they are ready to fully eliminate WorldCat.

TODO
- [x] Add config upgrader warning to eliminate [WorldCat] from config.ini
- [x] Ensure that all tests pass

### CODE REVIEW

**Comment by maccabeelevine** [comment]
> I propose including this change in a 10.1.1 release to be issued shortly after 10.1; this way, users can upgrade to 10.1 during the window that WorldCat v1 is still online, and then upgrade further to 10.1.1 when they are ready to fully eliminate WorldCat.

What if there is some other important-to-the-institution bug fix that people want in 10.1.1, but they're not ready to eliminate WorldCat v1?  Admittedly I'm not sure why anyone would not be, but there must be some reason, or we would just put this PR in 10.1.

**Comment by demiankatz** [comment]
> > I propose including this change in a 10.1.1 release to be issued shortly after 10.1; this way, users can upgrade to 10.1 during the window that WorldCat v1 is still online, and then upgrade further to 10.1.1 when they are ready to fully eliminate WorldCat.
> 
> What if there is some other important-to-the-institution bug fix that people want in 10.1.1, but they're not ready to eliminate WorldCat v1? Admittedly I'm not sure why anyone would not be, but there must be some reason, or we would just put this PR in 10.1.

My thought is that 10.1 comes out in November and the API shuts down in December. With the holidays, we're unlikely to make a 10.0.1 release before January, at which point continuing to use the old API is no longer an option anyway!

**Review by ThoWagen — COMMENTED** [review]
Should the comments here https://github.com/demiankatz/vufind/blob/62e119bfa302c3ecb3e382fb182ccf7b0522e2ef/config/vufind/combined.ini#L2 and here https://github.com/demiankatz/vufind/blob/62e119bfa302c3ecb3e382fb182ccf7b0522e2ef/config/vufind/config.ini#L2543 be changed from WorldCat to WorldCat2?

Apart from that, the changes are reasonable to me and seem to do what's intended. However, I'm not familiar with WorldCat and did not test this.

If you are confident with this PR I'd be happy to approve it. Otherwise, someone else should review this as well.

**Comment by demiankatz** [comment]
Thanks, @ThoWagen -- I've adjusted those two comments as you suggested (commit [1c0504f](https://github.com/vufind-org/vufind/pull/4038/commits/1c0504fb35e62e869a85a29ed7a52615bfc74b43)). If you want to approve this, I'm pretty confident that it's okay, and I also plan to leave it open for another week, since I shouldn't merge it until after the 10.1 release on Monday, so any other interested parties still have a few days to comment if they have any remaining concerns.

**Review by ThoWagen — APPROVED** [review]

**Comment by demiankatz** [comment]
Now that v10.1 has been released, I've gone ahead and merged this for inclusion in 10.1.1. Thanks again!

**Pull request merged**
