### PR TITLE
Fav action direct download 3.1.2

### PR DESCRIPTION
**Pull request by mbeh-ub**
Hello Demian,

since the new lighbox code has been introduced the option defaultType = download in 
the [BulkExport]-Section of config.ini seems to stop working.

I fixed this an hope you add this fix to the vufind base code.

Notice: I have created an separate theme where I keep the changes files. Therefor you cannot sadly see the changes directly but have to compare the file lightbox.js with the one in the bootstrap theme.
This branch is based on the vufind 3.1.2 code.

Greetings 
Markus

TODO
- [ ] Backport to release-3.1

### CODE REVIEW

**Comment by demiankatz** [comment]
@mbeh-ub, thanks for sharing this. I've adjusted the PR to apply your changes to the latest master, so that the diffs are more visible.

@crhallberg, can you take a look at this and offer your feedback when time permits? Thanks!

**Comment by crhallberg** [comment]
Hello! Thank you for catching this missing functionality, but I have a few suggestions about approach:

1. I see that in order to cause a direct download, you add then check a class to the alert buttons. The Lightbox already handles a 205 refresh HTTP code, so I'm wondering if it would be better to add the [303 HTTP code](https://en.wikipedia.org/wiki/HTTP_303) so that the server can just directly tell the Lightbox to open the page with a response.
1. I'm a little confused about your target addition. The difference between this and `lightbox-ignore` is using it to open in a new window, correct?

**Comment by demiankatz** [comment]
Thanks for looking into this, @crhallberg!

Note that, whatever solution we settle on, it's probably a good idea to backport the fix to release-3.1 if practical, since this definitely qualifies as a bug. I've created a TODO checkbox above so we don't forget to look into that after the general approach has been settled.

Let me know if I can be of any further assistance.

**Comment by mbeh-ub** [comment]
Hello Chris, I removed the the "target"-code in lightbox.js. 
Sorry for the confusion, that was code from another feature.

I also tried to directly tell the lightbox to open the page. But if I send a redirect (303) the browser catches the request , do the request and renders the response (i.e. the exported titles) in the lightbox.

**Comment by crhallberg** [comment]
Well that's generous of the browser. Since that's the case, I agree with your solution. Thank you for removing the other feature code.

It looks like there are still a few Javascript style issues. You can run `phing eslint-fix` to repair some of the problems and see the remaining ones.

**Comment by mbeh-ub** [comment]
I run eslint and fixed the style-issues in lightbox.js.

**Comment by crhallberg** [comment]
Everything looks good to me! Thank you, I'll merge this manually, then close.

**Comment by crhallberg** [comment]
`release-3.1`: e59f1526f03d835a493c043db772ae98036017ee
`master`: 49d686c9a64bfb6ced29d8210b7b2a089c17b1e6

**Pull request closed without merging**
