### PR TITLE
add ability to use theme-specific langauge files

### PR DESCRIPTION
**Pull request by mbeh-ub**
Hello,
I added the option to extend or override wordings from the global language files by wordings, defined in theme-specific language files ( ./themes/<theme_name>/languages/[de|en|...].ini ). This little code also respects the theme inheritance. 
Is this an extension you are interested in?

PS: On open point is the question how to deal with the mobile-theme detection an the alternate theme
functionality.

PSS: the other pull-request "persistent-favorites" is not dead but asleep at the moment. 

Regards
Markus

### CODE REVIEW

**Comment by demiankatz** [comment]
I think this may be a useful mechanism to add, but as you point out, there are some difficulties here related to the use of alternate themes.This is something of a chicken-and-egg problem; I very recently changed the order of initialization to determine the language setting prior to the theme setting, as there is a use case for loading different themes based on the language (for example, in cases of right-to-left vs. left-to-right languages). However, for your use case, it is preferable to know the theme setting prior to the language setting. It's possible that we'll need to do some work on the bootstrap process so that we actually figure out the user's settings for language and theme prior to initializing objects, so we can make smarter choices. Ideally, it would be nice if your code could simply pull a preconfigured ThemeInfo object, rather than having to set it up itself (which might have weird side effects, depending on the order of operations).

I also think it might actually be preferable to process the directories in a slightly different order:

languages/
local/languages/
theme/languages/

This way, the policy could be "if you want to override a core language string, override it in your local directory; if you want to override a theme-specific language string, override it in your local theme." I think this leads to more consistent behavior; otherwise, overriding a global string might end up overriding theme-specific strings that it shouldn't change (for example, if we introduced shorter versions of text for the mobile version).

Let me know what you think. I'm happy to give deeper thought to the bootstrap issues if you need me to.

(Also, thanks for the update on persistent-favorites; I'll be happy to continue working with you on that whenever it wakes up).

**Comment by mbeh-ub** [comment]
Hi Demian,
i moved the language file handling to the VuFindTheme/View/Initializer. Now the translator gets updated with the additional language files (if present) after the setUpThemes in the init()-Method.

Therefore I extended the ExtendedIni class by the addLanguageFile()-Method which simply
adds the additional language file directories to the $ptackPath.

I prefer to process the the files in the order: languages/ -> local/languages/ -> theme/languages/

**Comment by demiankatz** [comment]
Hello,

I just made a few adjustments to this, both to address style issues to make the Travis build pass, and also to improve the behavior slightly -- I adjusted the logic so that we only add theme language directories to the path stack if the directories actually exist. This way, we don't waste time searching non-existent locations, and we can totally bypass the translator modification if theme-based language directories do not exist.

However, there is one major problem that we have to overcome before we can merge this: because the translator uses caching, this does not work correctly when you switch between themes (standard vs. mobile, etc.). The cache gets updated with the strings from the first theme that was loaded, and then when you switch themes, those strings continue to be used -- the system doesn't know that it needs to reload different values. I don't see a simple solution to this. We could disable caching when theme-based language files are turned on, but this would likely yield a performance penalty. We might be able to use text domains in some fashion to help (since text domains are used to form part of the cache key), but I think this would be an abuse of the intended use of text domains, and might also conflict with work in #177. Any other solution would probably require us to build a custom translator object, and a quick look at the existing one suggests that extending it to change the cache behavior would be a bit messy -- that functionality doesn't have its own separate methods to override, so we'd have to copy-and-paste lots of extra stuff along with the logic we would have to change.

Any ideas?

**Comment by mbeh-ub** [comment]
Hello,
I added an additional directory level below local/cache/languages. So for each theme a separate cache directory will be placed at local/cache/languages/<themeName>/...

Works with file caches, I have not tested it with other storage backends. Do you see any problems?

**Comment by demiankatz** [comment]
Very good solution -- why didn't I think of that? ;-) I'll test this out (and most likely merge it in) when I return from vacation next week.

**Comment by demiankatz** [comment]
I just made a few minor adjustments to fix a bug and slightly improve efficiency. Please give this another try on your end and let me know if you see any problems. Once I get your approval, I think this is ready to be merged.

**Comment by mbeh-ub** [comment]
glad to hear :-). I merged the updates in my development branch and tested it with different two different themes (?ui=theme1 and ?ui=theme2). I found no errors. So I think we are ready to
merge.

**Comment by demiankatz** [comment]
Thanks for the test. I've now merged this to master.

**Pull request closed without merging**
