### PR TITLE
Aleph: paging support in my transactions

### PR DESCRIPTION
**Pull request by xrosecky**

### CODE REVIEW

**Comment by demiankatz** [comment]
@xrosecky, I didn't have a chance to review #2122 until today, and I see it has now been superseded here. You can always force-push to an existing branch rather than opening a new PR if you need to replace content. In any case, is this ready for review now, or should I wait until more work is completed?

**Comment by xrosecky** [comment]
It is now ready for review, I didn't realize that I need also modify the getConfig method in Aleph to disable sorting and make it compliant with the driver specification.

**Comment by demiankatz** [comment]
@xrosecky, I took a closer look at this; is it intentional that this seems to break/remove sorting capabilities?

**Comment by xrosecky** [comment]
@demiankatz Yes, it is intentional. Aleph API unfortunately does not support sorting so to order the items reliably you need to fetch them all.

**Comment by demiankatz** [comment]
Thanks! I'll just make a note in the changelog.

**Pull request merged**
