### PR TITLE
Dynamic cover improvements

### PR DESCRIPTION
**Pull request by samueloph**
This PR is related with https://github.com/vufind-org/vufind/pull/550.

So I removed the magical number "- 4" and I still can't detect what is causing the misaligment (centered texts are off by about 3% [4px max. in a 128px cover]), the magical number wasn't properly fixing it too (it could misalign to the other side up until 2 px =~1%).

So you should decide if it's acceptable to have such misaglinment in the covers (I didn't find too perceptible), at least until we find what is causing it (is there a chance that php is getting the wrong text size!?). I think It's best to remove the magical number and have slightly more misalignment.

I did some local tests and this changes seems to be ok, altough it's always good to have someone else looking at the code.

It's still missing the option to pass the color RGB parameters through config.ini instead of the color names (letting the user chose any desired color), but I don't think I will make this one very soon, so I will PR as it is and someone can do that if it's needed or wait till I do it.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks for this! Looks like there are quite a few style issues (see Travis build failure for details). If you'd like some help getting this cleaned up, let me know (and give me push access) and I'm happy to help. In the meantime, I'll ask @crhallberg to take a look at the actual code changes.

**Comment by crhallberg** [comment]
Would it be possible to make the color variables a little more verbose and self-documenting? Maybe something like `authorFillColor` and `authorBorderColor`. Or spell out the abbreviations? `authorMainColor`, `authorSecondColor`.

**Comment by samueloph** [comment]
I have made adjustments regarding the php-cs-fixer and changed the variable names as suggested by Chris, let me see if it will pass the CI test.

**Comment by samueloph** [comment]
Oh, I forgot to use the PEAR standard

**Comment by demiankatz** [comment]
See https://vufind.org/wiki/development:recommended_tools#meeting_project_standards if you haven't already -- might save you a little time.

**Comment by samueloph** [comment]
Thanks Demian!

While the CI is running, I'd like to ask if this[1] is really needed.

I don't have enought knowledge of VuFind to know if it can be dropped, but at least ISBN and Amazon seems to be the case, are they used?

[1]https://github.com/samueloph/vufind/blob/dynamic-cover-improvements/module/VuFind/src/VuFind/Cover/Generator.php#L29

**Comment by samueloph** [comment]
Well, phpcs is giving me 3 warnings, and looks like that was enough to stop the Travix Build, the three warnings are about some code that exceeds the 85 characters widht, altought the code looks better this way, i'm gonna break some lines here.

**Comment by samueloph** [comment]
@demiankatz I added you as a collaborator, the CI build still don't pass but phpcs gives me no errors or warnings.

**Comment by demiankatz** [comment]
First of all, I think you are correct that the use statement can be dropped -- it was probably copied and pasted from the cover loader and never removed. It's a safe bet that if you can search the whole file for the class names in the use statement and there are no matches, then you can remove the use statements... "use" is only there to create short aliases for namespaced names, so if the aliases aren't used, removing the statement can't hurt anything.

The remainder of the problems seem to be related to php-cs-fixer, but I'm getting different results on my test server than I am seeing in Travis. I've just tried merging the latest master in here to see if that makes a difference... more after the next build completes!

**Comment by demiankatz** [comment]
Okay, I think that might have done it. I'll probably be heading home before the build finishes, but we can touch base about this tomorrow!

**Comment by samueloph** [comment]
Ok, Thanks a lot Demian!

I'm gonna make a last change by removing that uneeded "use"s statments as soon as the the CI build finishes.

**Comment by demiankatz** [comment]
Looking good -- I'll merge this into the existing PR, rewrite the commit history there to simplify things a bit, and add a note there to continue investigating the slight centering inaccuracy.

**Pull request merged**
