### PR TITLE
Replace Laminas\Loader with Composer autoloading.

### PR DESCRIPTION
**Pull request by demiankatz**
The laminas-loader package has been abandoned, and this is a step toward getting rid of it (as of this writing, it is still an indirect dependency via laminas-http).

TODO
- [x] Run full test suite
- [x] Does module generator and/or documentation and/or video need updating to account for loading needs?
- [x] Update changelog when merging (document/link to best practice for converting autoloading for local custom modules)

### CODE REVIEW

**Comment by demiankatz** [comment]
I was able to figure out a way to make the Install command correctly set up autoloading for newly-built modules, and this should work without requiring changes to existing documentation. It may be somewhat fragile for users who have Composer set up in a non-standard way, so maybe we need to make that aspect of the process more robust... but I think that may be something we can address separately if/when the need arises.

**Review by EreMaijala — APPROVED** [review]

**Comment by EreMaijala** [comment]
@demiankatz This looks good enough to me. Perhaps the message about being unable to run `composer install` could suggest "Please run `composer install` manually to update the autoloader settings." so that the user can get the job completed?

**Comment by demiankatz** [comment]
Thanks, @EreMaijala -- I'm requesting another review since I've made two significant changes since your approval:

1.) As you suggested, I have made the Composer error non-fatal, instead outputting a warning (which shows up in red highlighting for visibility) asking the user to manually correct the problem.

2.) It occurred to me that we could simplify our complicated PHPUnit autoloading setup, so I created an autoload-dev section in composer.json and simplified our bootstrapper.

With these changes in place, the full test suite is still passing.

**Comment by demiankatz** [comment]
(I've updated the changelog on the assumption that this will be merged soon; please feel free to merge yourself when ready if you wish!)

**Review by EreMaijala — APPROVED** [review]
Nice!

**Pull request merged**
