### PR TITLE
Make noscript version of JSTree renderer output valid HTML.

### PR DESCRIPTION
**Pull request by EreMaijala**

### CODE REVIEW

**Comment by demiankatz** [comment]
Is there a reason that you're not escaping $node->text here? If so, might be worth a comment to prevent confusion in future. If it's just an oversight, then please add the missing escape. Either way, I should be able to merge after the next revision. Thanks!

**Comment by EreMaijala** [comment]
Oops, just an oversight. Thanks, now fixed!

**Comment by demiankatz** [comment]
I just did some testing with this, and it's a bit trickier than it appears at first. Your solution fixes the non-JS output, but there are still problems with the regular JSTree output. In order to test this, I modified one of my cached .json files to include an HTML tag in the title to see whether that tag would be rendered or not. With your fix, the non-JS version renders correctly, but the JSTree version interprets the tag as HTML and not as a simple sequence of characters.

It appears that a more universal fix would actually be to escape the strings within the formatJSON method rather than the jsonToHTML method. I don't entirely like this solution, but it may be necessary. The question is which elements are escaped at the JSTree level and which are not. It's possible that we have to split some of our escaping between formatJSON and jsonToHTML in order to ensure consistent results.

Do you have any thoughts on this, or any good test cases that can help with checking the consistency of behavior in the two modes? If you're not easily able to test this, I'm willing to put some more time into it myself -- just let me know.

Thanks!

**Comment by EreMaijala** [comment]
Well, escaping it in formatJSON would do the trick, but I think it would be wrong. The JSON consumer needs to do whatever escaping is necessary. I'll take a quick look if I can fix it.

**Comment by EreMaijala** [comment]
Okay, here's the second attempt. I decoupled the HTML rendering from the JSON rendering so that the HTML version doesn't need to rely on what getJSON() does.

I also verified that text is the only attribute that needs to be pre-encoded for JSTree.

**Comment by demiankatz** [comment]
Looks good to me -- thanks for the work on this. I've merged it to release-2.4 so that it can go out in 2.4.1.

**Pull request closed without merging**
