### PR TITLE
[VUFIND-1436] Account for previous exceptions in ILS drivers

### PR DESCRIPTION
**Pull request by demiankatz**
TODO
- [x] Test (to whatever extent possible)
- [x] Resolve [VUFIND-1436](https://vufind.org/jira/browse/VUFIND-1436) when merging

### CODE REVIEW

**Comment by demiankatz** [comment]
This is a fairly trivial change, simply designed to make debugging of exceptions a little easier by providing access to earlier exceptions in the chain. Not all of it can be easily tested, but the change is straightforward enough that I'm not too worried. I would appreciate another pair of eyes on it, just to be sure I didn't do anything dumb anywhere. I'm including @xmorave2 since some of this touches the XCNCIP2 driver, and @EreMaijala because he has worked on several of the drivers impacted here.

**Comment by demiankatz** [comment]
The full test suite is passing, but since our coverage of ILS drivers is spotty, that's not especially conclusive.

**Review by xmorave2 — APPROVED** [review]

**Review by EreMaijala — CHANGES_REQUESTED** [review]
How about adding to AbstractBase class a helper method such as `throwAsILSException($e);` to encapsulate all the `throw new ILSException($e->getMessage(), 0, $e);`?

**Comment by demiankatz** [comment]
Thanks, @EreMaijala, that's a great idea and significantly improves readability. I've just made the change; do you mind taking another look?

**Review by EreMaijala — APPROVED** [review]
Looking good now!

**Pull request merged**
