### PR TITLE
Remove ServiceLocatorAwareInterface from table gateways.

### PR DESCRIPTION
**Pull request by demiankatz**
TODO
- [x] Run full test suite with MySQL.
- [x] Run full test suite with PostgreSQL.

### CODE REVIEW

**Comment by demiankatz** [comment]
Here's some more ServiceLocatorAwareInterface refactoring to complement #909. Once again, a few more eyes on the problem would be appreciated to make sure I haven't done anything foolish. From @EreMaijala, I'm particularly interested in whether this will break any hard-to-test features like the ExternalSessions table. So far, all commonly-tested features seem to be working as normal.

**Comment by demiankatz** [comment]
No, I think that __NAMESPACE__ is constant to the file, even if you subclass it. If you need to build objects using a different namespace, we should either add a parameter to the function to allow a namespace override, or else you should duplicate the method in your own factory.

I also don't claim that the __callStatic() approach I'm using in the factory here is really the best way to do this -- it was just a simple approach to get everything working quickly. The most common practice these days seems to be one factory class per class. I still think the idea of having a single collection of static factory methods has some benefits, but I could certainly be persuaded to bring VuFInd in line with other projects in the future, especially if changes to the ZF 3.0 ServiceManager require a rewrite of all of the factories (which may be a possibility).

**Comment by EreMaijala** [comment]
Well, for now I think it would suffice for us to make __callStatic only prepend the namespace if there are no backslashes in $name. What do you think?

**Comment by demiankatz** [comment]
That sounds like a reasonable revision. I'll work on that shortly, unless you already have an implementation you can push up.

**Comment by EreMaijala** [comment]
I haven't done anything yet, so please go ahead. Thanks!

**Comment by demiankatz** [comment]
@EreMaijala, I've just revised the commit to include a better version of the factory. Now, instead of using __callStatic everywhere, I've created a getGenericTable method that supports either a relative or absolute class name. __callStatic is now a lightweight wrapper around getGenericTable (as are all of the other more explicit factories). In addition to supporting your use case, this also better isolates the messy "magic" method name munging from the cleaner process of actually building the table objects. Thanks again for the input; please let me know if you have trouble with this, or any other concerns.

**Pull request merged**
