### PR TITLE
Accessibility: Moravian Library Report

### PR DESCRIPTION
**Pull request by crhallberg**
Applying the recommendations from [Moravian Library Accessibility Report](https://docs.google.com/document/d/1qII8IRWOk0eP3er-91C5clhTfQq92yPkUbvAtq3xdNU/edit#heading=h.kvcl9sm0nhrb) (thank you, Josef!)

## Needs Clarification

- Advanced Search
  - From and To need labels _(couldn't replicate)_
  - Search Tips to (ul) _(not sure which tips, headings might be better)_

## To Research

- [x] Top Recommendations to (ul) #3107 
- [x] Refine Search to (ul) #3108 
- [ ] Advanced Search
  - [x] Identical "Remove" links (PR) #3109 
  - [ ] From and To need labels
  - [ ] Search Tips to (ul)
- [ ] Headings
  - [ ] Alternative Searches (h3)
  - [x] Search Tools (h2) -- handling in #3070 
- [ ] Autocomplete (looking into alternatives)
- [ ] aria-expanded in collapsed facets
- [x] Pick up location label -- handling in #3076
- [ ] My Account
  - [ ] Your Account and Favorites headings
  - [ ] Add alert after changing account
  - [ ] Make individual loan checkbox labels unique
    - [ ] Likely applies to search checkboxes as well

## To Research

- [ ] H5 in Footers _(h5 seems high)_

### CODE REVIEW

**Review by demiankatz — CHANGES_REQUESTED** [review]
Thanks, @crhallberg! I see that the build is failing here -- looks like you just need to run `lessToSass` to sort it out.

I'd also suggest that it might be better to open multiple small PRs for this instead of one huge one, unless some of the changes depend on one another. Mashing it all together will make review and testing harder and will also result in a less clear Git history. I'm not suggesting that you need to split this one up necessarily, but it's probably better not to pile lots more changes on top of it.

**Comment by maccabeelevine** [comment]
> I'd also suggest that it might be better to open multiple small PRs for this instead of one huge one, unless some of the changes depend on one another. Mashing it all together will make review and testing harder and will also result in a less clear Git history. I'm not suggesting that you need to split this one up necessarily, but it's probably better not to pile lots more changes on top of it.

I'd be willing to take on a few of these items as separate PRs.  Are there any I should / shouldn't look at @crhallberg ?  Also I see the linked Google Doc but do we have any indication of what tool (or human) identified these as issues so we can use the same tool to make sure the "fixes" don't create other accessibility issues as a side effect?  I have used WebAIM and SiteImprove checkers mostly.

**Comment by demiankatz** [comment]
Thanks, @maccabeelevine! The original report was provided by @xmorave2, so he might be the best person to answer whether or not there is an easy way to re-check things. (I believe the report was provided to him by a third party, so the answer may not be easy, unfortunately).

**Comment by crhallberg** [comment]
I cherry-picked the work done into separate PRs, which will also resolve the conflicts when merged into dev.

**Comment by demiankatz** [comment]
I'm moving this PR to the 10.0 milestone. All of the work that has been done so far in separate PRs has a 9.1 milestone, but I don't expect we're going to have time to finish all the remaining items in time for the 9.1 release.

**Comment by xmorave2** [comment]
@maccabeelevine: as @demiankatz wrote, the report was created by third party - it was local non-profit organization. As far as I know, the testing is done by several persons (all with disabilities) using  their usual setup for browsing web (they use different screen reader). So this is real life testing.

**Comment by crhallberg** [comment]
Moved to [JIRA Issues](https://openlibraryfoundation.atlassian.net/browse/VUFIND-1668).

**Pull request closed without merging**
