### PR TITLE
Add Print button to record toolbar

### PR DESCRIPTION
**Pull request by crhallberg**
- [x] Tests?
- [x] Translations

Closes [JIRA VuFind-282](https://vufind.org/jira/browse/VUFIND-282).

### CODE REVIEW

**Comment by demiankatz** [comment]
@crhallberg, if we label the button "Print" rather than "Print this," we can leverage existing translations. Adding a test seems like a good idea, because it should be pretty easy!

**Comment by demiankatz** [comment]
Thanks, @crhallberg! I've merged master into this in hope of eliminating the Snyk warning. Do you think it's worth the effort to write a Mink test for this? Should we bring this up on a Community Call first to see if there are any objections to adding the button? (I don't think it's likely, but it might be worth reaching out about).

**Comment by demiankatz** [comment]
@crhallberg, this is another PR that has sat idle for a long time; any thoughts on next steps at this point?

**Comment by crhallberg** [comment]
Just missing tests on this, correct?

**Comment by demiankatz** [comment]
@crhallberg, a test would be nice; I think we may also have failed to solicit feedback about whether or not this is desirable... though it's easy enough to hide with CSS if unwanted.

**Comment by crhallberg** [comment]
I think it's easy enough to remove with CSS, yes. I'll work on a test today.

**Comment by demiankatz** [comment]
Looks good! Merging now.

**Pull request merged**
