### PR TITLE
Fixed color of focused btn-default in sandal themes

### PR DESCRIPTION
**Pull request by ThoWagen**
As discussed in #3871 this PR fixes the coloring of focused btn-default buttons in the sandal themes.

### CODE REVIEW

**Review by demiankatz — COMMENTED** [review]
Thanks, @ThoWagen! This looks good to me -- as far as I can tell, it has no adverse effect on the original sandal theme, and it fixes the bug in sandal5. I'm going to wait and see if @EreMaijala has any further thoughts, but this seems pretty safe to me.

**Review by EreMaijala — CHANGES_REQUESTED** [review]
Nice! But I think we should also undo https://github.com/vufind-org/vufind/commit/1e1724ce6e3913139a361586704091ca58e9a449 while at it.

**Comment by ThoWagen** [comment]
Yes, you are right. Done

**Review by demiankatz — APPROVED** [review]
Thanks, @ThoWagen, this looks good to me. I tested both default and info buttons in both sandal and sandal5, and they look either the same or better in this PR when compared to the release-10.0 branch.

The most noticeable change other than default buttons actually becoming legible is that the info buttons no longer incorporate the blue theme color in sandal5 when focused.

Before:
image

After:
image

I don't think this is a problem because (to my eye at least) it improves legibility in the new form.

(And just for the record, I tested this by turning on feedback forms, writing feedback to the database, and going into the feedback admin panel -- info buttons aren't used in very many places and that was the easiest way for me to find one).

**Review by EreMaijala — APPROVED** [review]

**Pull request merged**
