### PR TITLE
Improvements to dynamic covers

### PR DESCRIPTION
**Pull request by demiankatz**
Derived from work by Cornelius Amzar and @samueloph.

Current features:
- Do not strtoupper text (caused problems with accents)
- Allow more configuration via config.ini
- Added additional font and color options

Known issue:
- Text centering is slightly inaccurate (see https://vufind.org/jira/browse/VUFIND-1146)

### CODE REVIEW

**Comment by samueloph** [comment]
@demiankatz By documenting do you mean comment options like "minFontSize" and explaining the difference between solid and grid options? 
I think I can help with that.

Thanks for the PR, having this upstreamed will be very handy.

**Comment by demiankatz** [comment]
@samueloph, yes, that's exactly what I was talking about. If you don't mind adding some docs, that would be a big help. I can either give you write access to this repo, or you can open a PR against this PR -- let me know what you prefer. If anything is unclear to you, we can talk to @crhallberg for clarification!

Thanks!

**Comment by samueloph** [comment]
Ok, I can open a PR.
Just came back today and am doing some cleanups to our vufind's theme, I should pick this this week.

**Comment by demiankatz** [comment]
Great, no rush!

**Comment by samueloph** [comment]
I'm making a few changes and would like to discuss them before making a PR, because I'd like to confirm that one of them would be accepted and discuss which is the best approach to the other one:

I modified [the generator defaults](https://github.com/vufind-org/vufind/blob/70aa3de3a41e98e2b1e81deab46e3bf791285083/module/VuFind/src/VuFind/Cover/Generator.php#L67-L78) to reflect [config.ini changes](https://github.com/vufind-org/vufind/pull/550/files#diff-9b17baaddf3ed772a0bbcc5b283d1627R652) and also set default mode to solid (thought it would be the main preference, since it's cleaner, visually speaking).
Is this change ok?

Now I'm thinking in ways to add font color options for main color and secondary color (border). I removed the predefined colors in [here](https://github.com/vufind-org/vufind/blob/70aa3de3a41e98e2b1e81deab46e3bf791285083/module/VuFind/src/VuFind/Cover/Generator.php#L125-L128) and [here](https://github.com/vufind-org/vufind/blob/70aa3de3a41e98e2b1e81deab46e3bf791285083/module/VuFind/src/VuFind/Cover/Generator.php#L183-L186), My suggestion is to add the 16 [4.0 html's named colors](http://www.w3.org/TR/REC-html40/types.html#h-6.5) in Generator.php and check it with a SWITCH CASE to get the hex codes for each color, this would also give the oportunity to whoever needs a different color to add a custom CASE inside the switch for this needed color.

I would like to check if anybody suggest a better approach to this, if there's a way to solve it without having to predefine colors, since imagettftext only accepts color parameter with the format AARRGGBB.

**Comment by demiankatz** [comment]
Regarding the generator defaults, my main goal is to retain the old defaults in some fashion so people who wish to keep using them can do so, but others can benefit from your improvements. My initial approach to that was to keep the old defaults in the PHP code but override them with better defaults in the config.ini file. Another option would be to switch the defaults in the PHP, but keep the old settings in config.ini (commented out) so they can be switched back on as needed. I don't have a strong preference about this one way or another -- I just want to make sure there's a convenient way to roll back should anyone want to.

Regarding colors, supporting named colors is a good idea. If you also support hex codes, then that would allow lots of customization with no need for code modification.

Thanks!

**Comment by samueloph** [comment]
Could somebody help me understand why we need to make this size adjustment https://github.com/vufind-org/vufind/blob/dynamic-cover-improvements/module/VuFind/src/VuFind/Cover/Generator.php#L448 ?

Also, I'm trying to fix a few things, already fixed a problem calculating author textwidth (it was using titlefont to get its size), and that was causing some problems when trying to center author names. 

Now I see that everytime the Generator needs to calculate the txtWidth, it subtracts 4 from the result, and when I don't do that the text get misaligned, Could anybody tell me why this is needed? 

PS.:I know that the line I highlighted should be changed to a call for the function txtWidth, but currently I just need to understand what the '- 4' does.

Should I PR my changes to the dynamic-cover-improvements branch to get them with this PR?

**Comment by samueloph** [comment]
Oh, forget about my last question. I understand now that we were talking about the dynamic-cover branch instead of master previously, I'm gonna PR my changes there when I'm done.

**Comment by demiankatz** [comment]
Okay, sounds good. If you find bugs that need fixing in master, feel free to open separate PRs for those against master so we can get them fixed right away -- then I'll merge them into here from master. (But really, do whatever makes your workflow the easiest -- I'm not trying to make extra work for you!)

**Comment by samueloph** [comment]
Thanks Demian, now I just need to understand what the "- 4" mentioned above does (why it is needed). Gonna read the code again carefully to see if I get it, but If anybody could help me I appreciate.

**Comment by demiankatz** [comment]
I think @crhallberg is the one most likely to be able to answer that!

**Comment by crhallberg** [comment]
I'm not entirely sure to be honest. It could have something to do with the border I add or it could be me trying to correct a consistent width detection error with the font I chose. Either way it was likely put in to properly align the text. My apologies for the magic number!

**Comment by samueloph** [comment]
No problem, thanks for your answer, I'm gonna see how I will deal with it.

**Pull request merged**
