### PR TITLE
Koha: Check and display a status if item will be automatically renewed

### PR DESCRIPTION
**Pull request by alexklbuckley**
If Koha returns the status 'auto_too_soon' then VuFind should say 'Item will be automatically renewed', rather than what it currently says 'Item cannot be renewed'. 

This is a helpful clarification for the borrower to inform them what will happen to their checkout.

### CODE REVIEW

**Comment by alexklbuckley** [comment]
Currently, the renewalBlockMappings in KohaRest.php maps the renewal block reason of 'too_soon', but doesn't for 'auto_too_soon'.

**Comment by demiankatz** [comment]
Thanks, @alexklbuckley -- this seems straightforward to me, but I'm requesting a review from @EreMaijala in case his deeper knowledge of Koha leads to any feedback.

**Review by EreMaijala — CHANGES_REQUESTED** [review]
Looks otherwise good, but I'd put the new message to the [ILSMessages](https://github.com/vufind-org/vufind/blob/dev/languages/ILSMessages/en.ini) text domain since we now have it. :)

**Comment by alexklbuckley** [comment]
Thanks @demiankatz and @EreMaijala . I'll make that change!

**Comment by alexklbuckley** [comment]
Hey @EreMaijala and  @demiankatz , 

I've made the below change, would you mind please taking another look?

> Looks otherwise good, but I'd put the new message to the [ILSMessages](https://github.com/vufind-org/vufind/blob/dev/languages/ILSMessages/en.ini) text domain since we now have it. :)

Thanks so much,
Alex

**Review by demiankatz — APPROVED** [review]
Thanks, @alexklbuckley, this looks good to me. I'll wait to merge until @EreMaijala also approves.

On a related note, I notice that several of the strings in the $renewalBlockMapping array are currently undefined in en.ini -- including some that are just tokens, like renew_debt. Would it make sense to do follow-up work to define the missing strings in the ILSMessages namespace as well? (This is a question more for @EreMaijala than for @alexklbuckley).

**Comment by EreMaijala** [comment]
> On a related note, I notice that several of the strings in the $renewalBlockMapping array are currently undefined in en.ini -- including some that are just tokens, like renew_debt. Would it make sense to do follow-up work to define the missing strings in the ILSMessages namespace as well? (This is a question more for @EreMaijala than for @alexklbuckley).

@demiankatz indeed, not sure how that happened, but I'll try to get them sorted.

**Review by EreMaijala — APPROVED** [review]

**Comment by alexklbuckley** [comment]
Thanks so much @EreMaijala and @demiankatz !

**Comment by demiankatz** [comment]
Of course; thanks for the contributions, @alexklbuckley!

**Pull request merged**
