### PR TITLE
Alma: Display item status according to process type.

### PR DESCRIPTION
**Pull request by EreMaijala**
Note that I added getTranslatableStatusString to use a 'status_' prefix for any translation string since they're not really library-specific. status_in_transit_requested is copied from request_in_transit.

### CODE REVIEW

**Comment by EreMaijala** [comment]
Uh, all items in transit seem to have requested=true. I'll need to revise this a bit.

**Comment by demiankatz** [comment]
@EreMaijala, is your transit problem solved, or should @betullam hold off on review until further notice?

**Comment by EreMaijala** [comment]
This should be good for review now. Thanks!

**Comment by betullam** [comment]
@EreMaijala and @demiankatz - We are hosting a conference the next 3 days and I am quite busy with it. The earliest I can test is on weekend.

**Comment by demiankatz** [comment]
Thanks, @betullam, I don't think there is a huge rush! I can merge this some time next week if you are ready by then.

**Comment by EreMaijala** [comment]
And I'll just cherry-pick this right away in anticipation of positive review. :)

**Review by betullam — APPROVED** [review]
Had the chance to test it ... works. Thank you!

**Comment by demiankatz** [comment]
Thanks to both of you -- merging now!

**Pull request merged**
