### PR TITLE
FOLIO: add title-level holds support

### PR DESCRIPTION
**Pull request by demiankatz**
Some work was begin in the FOLIO Lotus release to support title-level holds, though it may not be fully functional until Morning Glory.

TODO
- [x] Test (once FOLIO fully supports the feature)
- [ ] Update changelog (note change to FOLIO.ini) when merging

### CODE REVIEW

**Comment by demiankatz** [comment]
I have access to a Morning Glory test environment as of today, but when trying to place a title-level hold, I'm still getting `requestLevel must be one of the following: "Item"`. It appears that some additional configuration and data manipulation is required on the FOLIO side to enable the feature; I'm not sure if I'll be in a position to take care of that in the near future, so I'll see if other volunteers are available to test this.

**Comment by demiankatz** [comment]
I was able to test this in my test environment, and it is now working as expected. However, based on local circulation rules, I had to switch the default request type from "Hold" to "Page" to get the desired result. Thus, I've added a comment in Folio.ini highlighting the fact that this option also exists.

**Comment by demiankatz** [comment]
@damien-git, since you're currently doing work on FOLIO, I'm curious if this PR is of any interest to you. I'd welcome your review if you have an opinion!

**Review by bbusenius — APPROVED** [review]
Hi Demian, I don't see any problems with this and I'm glad to know about it. I'm told that we don't do much with title holds but I can imagine it coming up in the future. I'm not in a good position to test this at the moment and won't be for another week but I don't want to hold up the pull request. If you need me to test this, let me know and I'll set something up when I can, otherwise, feel free to merge.

**Comment by damien-git** [comment]
> @damien-git, since you're currently doing work on FOLIO, I'm curious if this PR is of any interest to you. I'd welcome your review if you have an opinion!

I am curious about it, but I don't really understand the feature. I will ask someone else in my team to take a look.

**Comment by demiankatz** [comment]
Thanks, @bbusenius. Since this is working for me and I have an approval, I'll go ahead and merge now; I don't expect this to hurt anything. If you or @damien-git have time to test later and encounter any issues, just let me know (or post a follow-up PR, as appropriate).

**Comment by damien-git** [comment]
@demiankatz I understand it better now. We have some interest in using it although it's not a priority. I think we will test it when 9.0 comes out. Thanks.

**Pull request merged**
