### PR TITLE
refactoring of the shibboleth authentification and authorization

### PR DESCRIPTION
**Pull request by jochen-lienhard**
follow up PR 209 ... contains only the shibboleth part

### CODE REVIEW

**Comment by jochen-lienhard** [comment]
I need a little help. I want to add the following permission / rule. If there is no config for the staffview in the permission.ini, show it, if there is some, follow the rule (at the moment IPRange based).
When I add the isGranted check in StaffViewMARC.php, I get this error:
Call to a member function isGranted() on null

What can be wrong?

**Comment by demiankatz** [comment]
The issue here is that the authorization service will only be injected if the service manager creating the object uses the ZfcRbac\Initializer\AuthorizationServiceInitializer initializer. Right now, VuFind is only configured to use this initializer when creating controllers (see module/VuFind/config/module.config.php). To get this to work, you'll have to add the initializer to the configuration of the 'recordtab' section of module.config.php.

**Comment by demiankatz** [comment]
Let me know if you need more specific guidance/clarification!

**Comment by jochen-lienhard** [comment]
Thanks for that hint. It was a problem of the cached config files ;-)

**Comment by jochen-lienhard** [comment]
It seems there is a php warning in the IpRegEx.php:
PHP Warning:  preg_match(): Delimiter must not be alphanumeric or backslash in ..../module/VuFind/src/VuFind/Role/PermissionProvider/IpRegEx.php on line 72

**Comment by jochen-lienhard** [comment]
I'm not sure if we should add a role staff and return in the legacy.StaffView a role => staff?

**Comment by demiankatz** [comment]
Regarding the warning in IpRegEx, I think this is a configuration problem rather than a bug -- if you pass in a regular expression that preg_match doesn't like, it will trigger the warning. Have you checked your configuration?

**Comment by jochen-lienhard** [comment]
I have no permission with IpRegEx active, so I'm wondering about this warning.

**Comment by demiankatz** [comment]
That's very strange. The class shouldn't even be instantiated unless something is trying to use it. Could you double-check your permissions.ini in both local/config/vufind and config/vufind just to be sure there are no uncommented lines in either referring to IpRegEx? If you don't find an obvious explanation there, you should also check for the [Auth] ip_range setting in Summon.ini and the [AdminAuth] ipRegEx setting in config.ini, since both of these are mapped to IpRegEx settings for legacy compatibility. If none of those things are set, this is a real mystery! Let me know exactly what you are doing that puts the warning into your logs, and I'll see if I can reproduce the situation on this end.

**Comment by jochen-lienhard** [comment]
I found the problem. I had a string not a regular expression in the AdminAuth. Sorry for my confusion.

**Comment by berndoberknapp** [comment]
I've implemented the permission providers as discussed in [pull request 209](https://github.com/vufind-org/vufind/pull/209#issuecomment-67533669).

Maybe we can find a better class name for Header.  Shibboleth by default uses environment variables which are also included in $_SERVER. Actually Server would be more appropriate, but that's even worse that Header in my opinion.

**Comment by demiankatz** [comment]
Thanks, this is coming along nicely!

A few comments:

1.) I agree that Header isn't a great name for the class, since it sort of implies HTTP headers, which are something different. I also agree that Server isn't very helpful. What about ServerVariable? It's more verbose, but also more accurate, since we're dealing with server variables here, and I can't think of a different name for them.

2.) In permissions.ini, we should keep all the permission type definitions in alphabetical order... but we can hold off on reorganizing those until we've settled on a final name for header/servervariable/etc.

3.) In permissions.ini, you've turned off [default.EITModule], but we should leave that on as-is. I also don't think we should restrict staff view to logged in users by default, though we can certainly leave that configuration there (but commented out) as a useful example.

4.) Maybe I'm missing something, but it looks to me like some of the things you've marked as deprecated in config.ini have actually been removed completely... in which case, there's no reason to keep the corresponding configurations around. If we want to deprecate rather than remove, I think we may need some backward-compatibility logic somewhere.

5.) The most significant of these changes seems to be the handling of user attributes, which appears to be totally removed. I don't think we can totally do without this, because user attributes are used not just for authorization but also for population of VuFind's user table. For example, it should be possible to load in email address and ILS credentials from the Shibboleth attributes as part of the login process... but your changes seem to remove this capability (though again, I might be missing something).

**Comment by berndoberknapp** [comment]
1)  Maybe ServerVar (less verbose :wink:) oder ServerParam (Zend Request.php uses the term server params or server parameters)?

3) We had commented out default.EITModule for testing and I didn't notice that change when commiting the changes. I will revert the change and add the guest role to the staff view.

4)+5) Jochen and I will look into this on Monday. I would be in favor of removing the userattribute settings because they actually were used for authorization and we now have more fine grained permissions that have to be configured anyway if Shibboleth is used. Maybe we should remove these options but still check for them and throw an Exception if they are present?

**Comment by demiankatz** [comment]
1) I think I prefer ServerParam, but if you want to be as short as possible, I wouldn't object to ServerVar.

4/5) I'm okay with eliminating authorization-related functionality and throwing exceptions if legacy settings are still found. However, I definitely don't want to lose the ability to pre-populate the user database from attributes, since this is important for a good user experience (e.g. it allows us to pre-fill cat_username/cat_password, so I user can access ILS functions without having to manually type in a barcode later).

Thanks!

**Comment by jochen-lienhard** [comment]
1) renamed Header to ServerParam
2) now in alphabetical order
3) EITModule active and StaffView for guest and loggedin
4) I removed the userattribute* stuff and the username and added a check in the validate function
5) added the cat_username and other stuff for ILS functions.

I have a question about casting or toArray of Zend/Config-objects. I'm using toArray for check if the config is correct, because casting does not work. What do you think?

Another question is about the $this->config. In the Shibboleth Auth class we only need the Shibboleth part of the config, is there a reason to use the getConfig in each function?

**Comment by demiankatz** [comment]
Thanks for the updates!

To answer your questions:

1.) It's okay to use toArray() instead of casting. I don't know the technical background on why this is the case, but toArray() and casting are definitely not meant to be functionally equivalent.

2.) It's worth continuing to use getConfig in each function, because this ensures that the configuration is properly validated regardless of the order in which functions are called. It may be overkill in this particular case, but I think it's worth doing to keep all of the authentication modules behaving consistently.

A few new comments of my own:

1.) In config.ini, you've changed the comment above [Shibboleth] to:

<pre>
; Shibboleth is optional. This section only needs to exist if the
; Authentication Method is set to Shibboleth and the rules for the attributes
; are set in the permissions.ini.
</pre>

Is this really accurate? Would it be better to leave the comment as it was, but add a separate sentence saying: "To restrict which Shibboleth users are permitted to log in, please see permissions.ini." Technically (if I understand correctly) the permissions.ini settings aren't required, though they are of course likely to be strongly recommended!

2.) Later in config.ini, is "IdPEntitId's" a typo for "IdPEntityId's"?

3.) Perhaps we should go ahead and merge the serverParam permission provider and the access.StaffView permission to master. They're not Shibboleth specific, and if those pieces are completed to your satisfaction, merging them now will make the rest of this PR easier to review. I'm happy to take care of splitting out those parts if you agree that it is a good idea.

4.) How universal are the Shib-Identity-Provider / REMOTE_USER variables? I'm not familiar with the inner workings of Shibboleth, but I want to be sure that this change will not break any existing instances. Also, on a semi-related note, I've found it very useful to be able to override the username variable, since it allowed me to simulate Shibboleth for testing purposes by setting the username field to some other server variable, like REMOTE_IP. It seems that with these fixed variables hard-coded into the module, it will be harder for me to perform tests without a real Shibboleth environment. (That's not the most important consideration, of course... but if there's an easy solution it would be nice).

5.) Is there a reason for the removal of the isExpired() functionality? Isn't it still possible for a user's Shib session to expire while they are logged in to VuFind?

6.) I don't think the logic is split up appropriately between RecordTab\AbstractBase and RecordTab\StaffViewArray; either the isVisible logic should all be implemented in the base class, or else the property should only be defined in the subclasses. Having the property defined in the base class but only functioning meaningfully in the subclasses is likely to cause confusion. (I see no harm in having this capability universally, so I'd favor the first option of moving isVisible changes up to the base class; that will also reduce redundancy in the subclasses).

7.) You should update the default behavior in DynamicRoleProviderFactory to match the new configuration for 'access.StaffView' (right now it appears to be loggedin-only).

Anyway, thanks for all the work so far!

**Comment by berndoberknapp** [comment]
3) The serverParam part should be completed and could be merged.

4) All versions of the Shibboleth SP set Shib-Identity-Provider (and some other special Shib-* values) after a successful authentication. This is the only reliable way to detect a successful Shibboleth authentication because a user might have no attributes. I'm not sure if the server param name might get normalized by the web server in some cases, for example if headers are used instead of environment variable (which is not recommended and not necessary for PHP applications).

REMOTE_USER is the best choice for the username for the Shibboleth SP because the SP can map values from different attributes to REMOTE_USER (default in shibboleth2.xml: eppn, persistent-id, targeted-id), which can be helpful if you have to deal with multiple IdPs.

You could set the server params in a script or in the web server configuration for testing. Of course
it would be possible to make the server param names configurable, but changing them might be dangerous so we probably should add a warning if we do that. Maybe it would be an option to also split the authentication module in ServerParam and Shibboleth and make them configurable for ServerParam but not for Shibboleth?

**Comment by demiankatz** [comment]
Thanks! I'll work on merging the serverParam piece now and will let you know when that's done so you can merge master back into this branch.

Regarding the rest of this, it sounds like it makes sense to leave things as you have set them up. I don't think it's worth the effort of creating a separate ServerParam authentication just for the sake of my testing, and I'm not aware of another use case. As you say, I can find other ways of faking the Shibboleth environment, so I'll just have to work out a different workflow for testing. That shouldn't be a big problem.

**Comment by demiankatz** [comment]
Okay, serverParam is in master now. It looks like I've introduced a conflict in the process (possibly because I made a small style adjustment to the test class), but hopefully it will be easily resolved when merging master back into your branch.

**Comment by demiankatz** [comment]
You might also want to take a look at the Clover test coverage report for ServerParams:

https://vufind.org/hudson/job/VuFind2/2101/clover-report/VuFind/src/VuFind/Role/PermissionProvider/ServerParam.php.html

It appears that there are some features that don't have test cases yet.

**Comment by jochen-lienhard** [comment]
1) it is not a reason about login the shibboleth user, more about the permissions he has, so I would prefer the new version
2) fixed
6) I thought that perhaps someone want add the comment or tagging only for loggedin-user, so it is easier that the some parts are in the AbstractBase, but I can also put it in the both StaffView files.
7) fixed

**Comment by jochen-lienhard** [comment]
5) I must check this.

**Comment by demiankatz** [comment]
1.) Do you mind updating config.ini so we don't forget about this? (Or, if you prefer, you can give me write access to this branch -- assuming I don't already have it -- and I can take care of it).

2/5/7.) Thanks!

6.) I agree that it's possible people might want to restrict the other tabs... that's why I think it might make sense to update the AbstractBase::isVisible with the new logic you've added to the staff view tabs, rather than only implementing it in the subclasses. That way, anyone can simply add a line to a constructor in another tab and get the behavior.

I'll await hearing more from you about the still-outstanding issues before proceeding on this end. Thanks again!

**Comment by jochen-lienhard** [comment]
1) Hmm ... strang, I think you can push. My opinion is, that the current description for Shibboleth is OK.
5) fixed, if the there is no shibboleth session any more you need to click 'institutional login' again.
6) I hope the rule works like you wish. If you have not set the accessPermission to the string of the permission, the tab is shown.

Is there any outstanding issue?

**Comment by demiankatz** [comment]
I just pushed up a slight adjustment to the config.ini comment (which I think makes it slightly more clear) as well as a couple of cosmetic adjustments that make the diff in the pull request a little more readable.

I think the accessPermission stuff needs a little bit of adjustment: I think we should actually make the tabs inactive rather than simply invisible when the user is unauthorized. I also think we should name the permissions with a "Tab" suffix to reduce the odds of conflicts with Module-related permissions.

I should have time to make these adjustments and merge this functionality to master either today or tomorrow. After that, I'll merge master back into this branch and give the remaining diffs another review to see if there are any further outstanding issues. Either way, since this is a fairly drastic change to the Shibboleth module, I don't think we should merge it to master until after the 2.4 release, so it has a bit more time to get tested before being included in an official release.

**Comment by demiankatz** [comment]
Okay, I have merged all of the tab authorization logic to master (and from there, back into this PR). Now, the pull request contains only the basic essentials specific to Shibboleth.

One more question:

Previously, with the old userattribute functionality, you could block users from logging in if they did not have the proper Shibboleth attributes.

I understand how this new functionality allows you to set specific permissions based on Shibboleth attributes, but I don't see an equivalent mechanism for actually blocking authentication for invalid users. Is there a mechanism that I am failing to notice, or is this something that needs to be addressed?

My concern is that, right now, VuFind bases a lot of access on the simple "loggedin" role. I don't see a way of preventing a Shibboleth user from receiving that role.

**Comment by berndoberknapp** [comment]
Could you please also merge the Shibboleth permission provider? That part is independent from the Shibboleth authentication module and could be used both with the old and the new version.

As far as I know the userattribute option was implemented for controlling access to licensed content because there was no authorization support available at that time. Therefore we thought that we could remove these options now that access to licensed content and other features can be protected by permissions. With RBAC access usually can be controlled by checking a role, but since we only have two fixed roles with dynamically assigned permissions, all access control should be based on permissions.

Which features are currently protected by checking whether the user is logged in? I'm only aware of the default rule for the EITModule which in my opinion should be commented out because that permission usually cannot be granted to all authenticated users.

**Comment by demiankatz** [comment]
The key areas that are protected by checking if the user is logged in are the MyResearch controller (which provides ILS functionality and favorites management) and record-level augmentation (user tags and comments). It probably makes sense to change these to use authorization, but it hasn't been done yet.

I notice that one of your Shibboleth examples in permissions.ini uses a fictional access.Favorites permission, so perhaps you were already thinking ahead.

In any case, I'll go ahead and merge the permission provider momentarily (minus the access.Favorites example, since I don't want to confuse anyone with a permission that doesn't really exist).

**Comment by demiankatz** [comment]
Okay, the permission provider is now merged.

I also realize I neglected to respond to your comment about the EITModule default rule. My goal for the initial implementation of the authorization logic in release 2.4 was to aim for backward compatibility with previous releases, so the new functionality did not confuse existing users. However, perhaps the best thing to do is to change this for the next release in order to eliminate some legacy compatibility code and revisit best default practices.

**Comment by berndoberknapp** [comment]
For Shibboleth the username might be transient. Users only should be able to save persistent searches and favorites if they have a persistent username (usually persistent-id, targeted-id or eppn), that's what access.Favorites is intended for.

Changing all access control to permissions of course would be the best solution, but in case that's not possible for release 2.4 maybe keeping the userattribute option and just deprecating it would be an option.

**Comment by demiankatz** [comment]
That makes sense to me. 2.4 is coming very soon, so we can get the rest of this sorted out after the release... then we'll have more time to test and collect feedback before including it in 2.5.

**Comment by jochen-lienhard** [comment]
Well, I think, we only need to add some comment / info to the config.ini, that user_attribute-(value) is deprecated and a hint to look at permissions.ini. Can you do this, Demian?
And after the release we can start a discussion in the vufind-test list about the authenticate features of shibboleth, and merge the Shibboleth.php (auth) later.

**Comment by demiankatz** [comment]
If I understand the situation correctly, the problem here is that VuFind assumes that if you are authorized, you have a persistent ID... but in some situations, Shibboleth will authorize a user with a temporary ID. The temporary ID is problematic because it will cause VuFind to create lots of useless user rows, and if users tag records, leave comments or save favorites, they will not be able to refer back to or edit those entries in future because their ID will change.

The solution in the past was to use user_attribute logic to block those users from accessing the logged in area of VuFind at all. But if we take that away, these users will be able to log in, but the problems described above will affect them. Some of this may be alleviated by adding some new permissions to conditionally turn off features like tags, comments and favorites. However, the problem of junk rows in the user table is a separate matter that might need a solution of its own.

I'm certainly happy to add a comment to config.ini indicating that user_attribute settings are deprecated, but before I do that, I think we need to figure out how to deal with the problems that result from changing this behavior.

Perhaps one of us could work on a separate pull request to add permissions that control all of the social features. Since we already have code in place to disable those features through config.ini, it is probably fairly easy to leverage that existing code but add some conditionals based on the permission provider. I'm happy to do this when I have a bit more time, assuming you don't get there first.

Regarding the problem of temporary rows in the user table, perhaps it would make sense to add an "expiration date" column to that table, and write a utility to wipe out expired user rows. Then we could add some logic to the shibboleth authentication code that detects non-persistent users and sets an expiration date in the database so they can be cleaned up in the future.

What do you think?

**Comment by useltmann** [comment]
Hello everyone. As Demian pointed out in the tech mailinglist this is the upcoming changeset in shibboleth authentication. since Im involved in setting up several vufind instances im concerned about the behavior of how vufind requests authentication and how vufind verifies that a user user is authenticated.

The latter first: relying on `$_SERVER` variables to be present like `$_SERVER['Shib-Identity-Provider']` and even `$_SERVER['REMOTE_USER']` restricts vufind2 to a very strict setup. As soon as you try to use php-fpm or another fast-cgi approach you do not get this variables anymore (at least not without further configuration overhead), because of changes in naming conventions.
`$_SERVER['REMOTE_USER']`  becomes `$_SERVER['REDIRECT_REMOTE_USER']` etc., with other setups they could vary more. 
To compensate that i would suggest to consider an option to name the variables.

For the first problem about where vufind requests authentication the question is whether the 'logged in area' can be associated with a certain location (meaning a path in the url) within vufind2?

**Comment by demiankatz** [comment]
Regarding the first part (configurable variable names), I think this sounds reasonable, but I'll let Jochen and/or Berndt comment.

Regarding the "logged in area" being associated with a certain location, that is harder -- every page of VuFind potentially cares to know whether the user is logged in (so it can display appropriate status/links in the header), and while most of the user functionality is under MyResearch, there are also features like tags and comments and holds that take place under individual record URLs. Assuming that you run vufind under its own path (like /vufind), is it possible to take advantage of that? (Again, my ignorance on Shibboleth implementation details may be working against me here).

**Comment by berndoberknapp** [comment]
If the server param names differ depending on the web server setup, we can of course make them configurable (as discussed a week ago). The permission provider shoudn't require a separate configuration, it could reuse the settings from the config.ini [Shibboleth] section.

The user always is redirected to /MyResearch/Login for the login, but the permssion providers indeed seem to run on every page that contains protected content. I'm wondering why that is the case, wouldn't it be sufficient (and more performant) to compute the permissions only once during the login?

**Comment by demiankatz** [comment]
It sounds to me like we have a legitimate use case for configurable variable names, so it seems worth implementing... though of course it's also worth adding a comment discouraging people from changing the settings unless they really know what they're doing!

Regarding the permission providers running on every page, it may be possible to add some sort of caching mechanism to, for example, save generated permissions in the session. However, since most of these checks are fairly inexpensive, it is probably more secure to leave them alone -- otherwise a user might be able to, for example, bypass an IP restriction through a session hijack. Also, if we did caching, we would have to figure out under which circumstances the cache must be cleared, since sometimes changes of state will require new permissions to be generated.

**Comment by berndoberknapp** [comment]
I didn't expect that, because most more complex applications I know only use the Shibboleth SP session to setup an application session. Running the permission provider everytime the permission information is needed will work fine for Shibboleth - if the SP session length is configured accordingly.

**Comment by jochen-lienhard** [comment]
Hello Demian,

Franck implemented the user_attributes to allow login for users, who may use Ebsco or Summon.
With the new permission.ini this is not longer necessary. All users that can login, may use the
persistent favorites, and only the users with the correct attribute may use Ebsco or Summon.

The problem with temporary ID does not effect the user_attributes. So you can add the deprecated comment. The 'username' is the critical point for temporary ID, but I think we will discuss this soon.

**Comment by demiankatz** [comment]
So if a user with a temporary ID clicks on the account link, what happens? Or is your point that Shibboleth can assign attributes to users without actually allowing them to log in to VuFind?

**Comment by berndoberknapp** [comment]
The Shibboleth SP usually maps transient and persistent IDs to different server params, so both cases can be distinguished. If we keep the current implementation (and just add a deprecation notice for the userattribute options and a configuration option for the Shib-Identity-Provider server param) the login with a transient ID can easily be blocked by not mapping that ID to the server param specified in username.

There are use cases where we might want to allow a login with just a transient ID, for example if the user is entitled to access licensed content (I think that's the use case Jochen had in mind). And there are use cases where a user has a persistent ID but should not have access to persistent personalization features, for example for group accounts. With the permissions we could support these use cases, but of course that would require significant changes, so we should look at/discuss this (and other possible new features) on the mailinglist after the release.

**Comment by demiankatz** [comment]
Okay, that makes sense to me. I'll hold off on doing anything more here until you have time to add the configurable server parameter feature. After that, I'll be happy to put in a deprecation warning if you prefer that I define the wording there.

I'm going to miss the next VuFind developers call due to a conference, but perhaps on the following call in mid-April I can put the topic of permissions for social features (and, more broadly, future goals for permissioning) on the agenda to get a discussion started.

**Comment by berndoberknapp** [comment]
How can I access a setting from config.ini (name of the server param with the identity provider entityID, added for the Shibboleth auth module) in the Shibboleth permission provider?

**Comment by demiankatz** [comment]
You could pass the config.ini settings to the constructor of the permission provider from within the VuFind\Role\PermissionProvider\Factory (either passing in the whole configuration object or using some of the settings, as appropriate). To access the configuration in the factory, use:

`$sm->getServiceLocator()->get('VuFind\Config')->get('config')`

(this will give you a  Zend\Config\Config object)

**Comment by berndoberknapp** [comment]
I've added the configuration option for the identity provider entityID server param with default Shib-Identity-Provider.

While testing the changes I noticed that getServer()->get(...) has to be tested for null instead of false to detect missing server params. The bugfix commit unfortunately only contains the fix for one check, the fixes for the Shibboleth permission provider and the unit tests are included in the second commit.

**Comment by berndoberknapp** [comment]
I'm wondering why the result of VuFind\Auth\Shibboleth::isExpired depends on whether the configuration contains a logout URL. The Shibboleth SP session expired after the lifetime or timeout configured in shibboleth2.xml, and when it expires the Shibboleth server params are gone. So it should be sufficient to check if the identity provider entityID server param exists, or am I missing something?

**Comment by demiankatz** [comment]
I seem to recall some conversation long ago about some Shibboleth setups offering users a mechanism to manually log out, and others failing to do so. Checks related to the logout URL setting may be an attempt to accommodate those two scenarios, but I'm not sure why/how that would affect expiration.

**Comment by berndoberknapp** [comment]
Logout is one of the Shibboleth features we probably should discuss on the mailinglist. The Shibboleth SP supports both local logout and single logout (SLO). Local logout doesn't make much sense in my opinion because the user can simply login again without entering credentials if the IdP session is still valid - we only could tell the user to close the browser to really log out. Implementing SLO is difficult, especially on the IdP side (see https://wiki.shibboleth.net/confluence/display/CONCEPT/SLOIssues ), nevertheless I think we should be prepared to support SLO. The Shibboleth SP supports front channel SLO via redirects (we have a working implementation for VuFind 1.3) and back channel SLO via SOAP requests and application notification (this should also be feasible).

**Comment by EreMaijala** [comment]
In our federation there's a local (to Finland) logout implementation where on logout the app must redirect back to the IdP using a link provided in Shibboleth attributes. Not much different from a staticly configured logout URL, but something we have to implement locally, at least.

**Comment by demiankatz** [comment]
Definitely an issue worth discussing further among actual Shibboleth users. Is there anything I can do to help facilitate this discussion? Would a wiki page or JIRA ticket be helpful for summarizing issues and collecting opinions? Would you like me to get this onto the developers call agenda for a particular date? (Due to the fact that many Shib users are not regular attendees of the dev call, it might be best to start the discussion on the mailing list and then plan on a future dev call date if people would benefit from a real-time discussion).

**Comment by jochen-lienhard** [comment]
Bernd and I discussed about the next step. We will send a mail to the vufind-tech list (after eastern) describing the changes and new features of the new Shibboleth authentication and authorization.
We think that the mailing list would be the best platform to discuss this.

**Comment by demiankatz** [comment]
Sounds like a good plan!

**Comment by berndoberknapp** [comment]
I would like to clean up the remaining changes in this pull request before adding more changes to the Shibboleth authentication module. There are different changes which unfortunately are mixed.

The result of request->getServer()->get(...) is compared against false instead of null in two places, see bea0065614c5b295364397d5761dab45deb379f6 and line 80 resp. 94 in PermissionProvider/Shibboleth.php 42c33d1a6aca5098f8fd85de324a6e6b74c8744d. These changes should be included in the next bugfix release.

The remaining changes make the name of the server param with the IdP entityID configurable as requested. I didn't want to duplicate the option in the authentication module and the permission provider, therefore I've also used the option/default from the authentication module in the permission provider. I hope that's OK?

Regarding the code coverage of the unit tests for the PermissionProvider, some of the code marked as not executed in ServerParam.php is actually tested by Shibboleth.php, but that doesn't seem to count...

What's the best way to proceed with theses changes?

**Comment by demiankatz** [comment]
Bernd,

I've manually applied the false ==> null corrections to the release-2.4 branch and merged that both to master and back into this branch.

The remainder of the code looks reasonable to me and can probably be committed to master soon in order to close out this PR (we can start a new one for the next phase).

Just one question first: I see that you've changed the providerId parameter to entityId. What is the significance of this? Are they synonyms, or do they potentially serve different purposes? If they're different, maybe we need two different config options. If they're the same, we should probably adjust some of the terminology to be more consistent (right now the config.ini comment says we're going to use the providerId parameter -- at very least, maybe that needs to change).

Thanks as always for all the work on this!

**Comment by demiankatz** [comment]
Regarding the code coverage, note that a method will not show as green until every line has been covered by tests, and it looks like there are some edge cases that are not covered in the case of ServerParam, such as the $escape === '' case in splitString(). Are there really some lines that are showing as uncovered that you're sure are executing, or does this explain what you are seeing?

**Comment by demiankatz** [comment]
It's been over a month since the last comment, so I'm just checking in to see where we are with this. There are still a couple of unanswered questions in my last two comments. As always, please let me know if I can be of any further assistance... and no rush on this; I just want to make sure nobody has missed anything.

**Comment by berndoberknapp** [comment]
I'm sorry for the delay. I was out of office for five weeks and currently I'm busy prepraring the move to a new library building next week...

providerId is an alias for entityID for backward compatibility, the setting/parameter was renamed in Shibboleth 2. I think we currently should leave the ini setting as is and change it when we improve the Shibboleth module. So you could merge the changes and close the PR.

**Comment by demiankatz** [comment]
Thanks for the clarification. I've gone ahead and manually merged this to master. Please let me know if you still need any help with the testing situation.

**Pull request closed without merging**
