### PR TITLE
Show More Facets in Lightbox

### PR DESCRIPTION
**Pull request by crhallberg**
Started with Chelsea (@ChelseaL) from Swarthmore.

- [x] Summon bug
- [x] Test with building: for stability
- [x] getPartialFacetList
- [x] Convert facetListAction to getPartialFacetList
- [x] Test compatibility with OR and NOT facet settings
- [x] Revise configuration functionality to match dev call discussion (second button)

### CODE REVIEW

**Comment by demiankatz** [comment]
Just tried this out on my test server, and my "author" facet yields a generic error message in the pop-up. I'm guessing this may be a timeout or other limit related to the large number of values in that field. We may need some form of pagination. Pagination might also be nice for cosmetic reasons; the lightbox is a bit unwieldy with large numbers of values in it.

**Comment by demiankatz** [comment]
Another problem: the Summon implementation is not fully fleshed out. The "Summon/FacetList" route definition is missing from module.config.php, and for some reason this causes a fatal error in the Summon search results even though showMoreInLightbox is not defined in Summon.ini and thus should be off by default. If I do define the route, I end up with a weird behavior where clicking on the "more" under a facet first expands the facet group and then forwards me to a full-page version of the Summon/FacetList route, which itself displays a white screen of death...  so apparently this is broken on several levels. :-)

**Comment by demiankatz** [comment]
Note: the problem of getting redirected to the FacetList action when showMoreInLightbox is turned off also affects the main Solr results, so that's a broader bug.

**Comment by demiankatz** [comment]
Two quick thoughts:

1.) Do we need separate lightboxLimit  / showMoreInLightbox settings? Could we just set the page size as the showMoreInLightbox setting, with false meaning "don't do it"? This would give us the ability to set different page sizes for different facets, and it would reduce the number of .ini settings. On the other hand, this isn't very intuitive, and I'm not sure there would ever be a scenario where we needed to set different page sizes for different facet fields. Definitely not a "must change" thing -- just brainstorming in the interest of reducing verbosity/complexity.

2.) Did you consider using the building facet to pick a specific MARC test file for your test? That might make the test more stable over time, since as new test data is added, the results for searching "test" may change.

**Comment by demiankatz** [comment]
Also:

3.) Had we talked about using the new functionality to make the "more" links in the facet sidebar work correctly even with JS disabled? I don't really see a down side to linking that up so that (in non-JS mode) we replace the current completely broken "more" button with a link that actually does something. I notice that in this case, though, the "more" button within the "FacetList" action is broken when JS is disabled. Should we simply hide that control in non-JS mode? Do we already have a class for "hide this by default, then show it if JS is active"?

**Comment by demiankatz** [comment]
And, more seriously:

4.) Clicking on a facet in the Summon lightbox appears to link back to a Solr search, which (unsurprisingly) causes things to break.

**Comment by demiankatz** [comment]
A few issues related to facet sorting:

1.) If you click the button corresponding to the currently-active sort order, all of the facet data gets unnecessarily reloaded.

2.) When you change the sort, the code attempts to reload the same number of facet values that are currently being displayed. This can result in out of memory errors in some extreme cases. (For example, set lightboxLimit to 10000, load up the author facet, hit the "more" button five times, and attempt to re-sort... You get a fatal error). Realistically, people aren't likely to run into this very often, but it would be nice to have some kind of safety in place. Two possibilities: either put a hard cap on the page size that can get loaded when switching sort options (though picking a number may be hard due to possible variations between search backends -- e.g. what if there is a hard limit on some API and it's impossible to get more than 30 at a time?) or else create some kind of loop to grab a page at a time until the whole list is populated. (Or, there's the third option of just getting the first page when switching sort and forcing the user to page down through it from there -- that might actually be the safest/cleanest).

3.) Related to item 2: switching back and forth between sorts becomes quite expensive when the list gets big. Can we just maintain both lists in separate <divs> and toggle them so we only hit the server when we need data that we haven't previously retrieved?

**Comment by crhallberg** [comment]
Separate divs for each sort has been implemented and does greatly contribute to performance.

**Comment by demiankatz** [comment]
I've made a few minor adjustments. Also, food for thought:

1.) Should we have a "loading..." icon in the lightbox while sorting? For large data sets (if you set the page size very high) it takes a few seconds for everything to come through, and it might be nice to have some visual feedback.

2.) There is currently a lot of Javascript in the facet-list template. Would it be possible/wise to move most of this to common.js (or somewhere else) and just have the template instantiate an object rather than dynamically generating code?

3.) I think we should brainstorm a better way of dealing with facet paging. Having the presence of a $page parameter in getFullFieldFacets() return page size + 1 as a side effect is kind of unintuitive/weird, and it's made worse by the fact that this feature doesn't work right in Summon. I wonder if we either need more methods to communicate capabilities, or else a different return format that can convey more information. Perhaps one solution is to have a getPartialFieldFacets() method that conveys paging information, and then rewrite getFullFieldFacets() as a thin wrapper around that.

4.) I see that you are hiding the "close" button outside of the lightbox. Should you also hide the sort parameters, since they will not work outside of the lightbox? (I suppose you could also make them work by linking, but I suspect hiding them is less work, and there's not much call for non-JS support, so this is really more a formality than anything else).

**Comment by crhallberg** [comment]
I'm not sure about the wider, multicolumn format. Especially with the sorting and paging, I think it'll cause more UI confusion than it solves.

**Comment by demiankatz** [comment]
True. I can live without it. I do still find the huge overflowing lightbox visually distracting, though. I'd be happier if the lightbox fit in the screen and had its own internal scroll bar, possibly with sort/close controls hovering in fixed positions. But if you disagree, I can stop complaining about it. Might be worth showing the current UI to Dave to see if he expresses the same concern, to see if this is just my personal pet peeve.

**Comment by demiankatz** [comment]
As discussed, I've put a couple of TODO items up above.

One other minor point to consider: in the sidebar, the more link says "more ..." but in the lightbox, it just says "more" (without the ellipses). Should we add "..." to the lightbox version for consistency? (If so, it looks like we'll need to make changes in several places, including the Mink test).

**Comment by demiankatz** [comment]
Would it make sense to roll the facet-list.js functionality into the existing facets.js, or do you think that will just increase confusion? Is there a reason you're not plugging this new object into the existing VuFind namespace?

**Comment by demiankatz** [comment]
The latest round of questions/comments:

1. Would `($showMoreInLightbox && $showMoreInLightbox !== 'more')` be a safer condition than `$showMoreInLightbox === '1'`? I'm not sure that the .ini parser is always going to give you a string of '1' for every possible variation of a "true" configuration that a user might input.

2. If we want the 'more' setting to be a default behavior, we should make sure it gets set when the setting is commented out in the .ini file (I don't think that's happening right now).

I can work on either or both of these things if you like... just let me know. Currently switching gears to look at a bug report that just came in.

**Comment by crhallberg** [comment]
1. I tested around various values and they all seemed to work but I am must more comfortable with this logic. Done.
2. Done.

**Pull request merged**
