### PR TITLE
Allow filter manipulation outside of search results.

### PR DESCRIPTION
**Pull request by demiankatz**
Resolves [VUFIND-1353](https://vufind.org/jira/browse/VUFIND-1353).

TODO:
- [x] Test OR facets
- [x] Test NOT facets
- [x] Test range facets
- [x] Test checkbox facets (simple and complex)
- [x] Resolve JIRA ticket and update changelog when merging

### CODE REVIEW

**Comment by demiankatz** [comment]
@EreMaijala, I'm also interested in your thoughts on this one: it seems to be a workable way of extending facet manipulation functionality beyond the search results screen, but again, I'd value your input when time permits!

**Review by EreMaijala — CHANGES_REQUESTED** [review]
The only thing I don't like is how long the url helper makes it. How about adding a couple of helper methods in the Url or SearchMemory helper?

**Comment by demiankatz** [comment]
Thanks, @EreMaijala; what do you think of 827c2ff? This should make things considerably more readable on the template side.

**Review by EreMaijala — APPROVED** [review]
Nice!

**Comment by demiankatz** [comment]
Turns out there were some bugs here related to default filters; I fixed them in 1be2ac19500da9c5491087e41e4d98d0895aa0ff post-merge.

**Pull request merged**
