### PR TITLE
Add function to detect multi facet selection configuration

### PR DESCRIPTION
**Pull request by LuomaJuha**
Added a default value into facets.js file.

### CODE REVIEW

**Comment by demiankatz** [comment]
The code looks good to me, but I'm going to ask @sturkel89 to do a bit of hands-on testing to confirm.

@sturkel89, this PR just adjusts the way the code turns multi-facet selection on and off. Could you please test with bootstrap5-based themes in both Firefox and Chrome (no need to worry about bootstrap3 since it will soon be removed). The key thing to check is simply whether the option appears when activated in facets.ini and does not appear when not activated. Please check the browser console for any weird messages. No need to go too deep into actually interacting with the facets, or to worry about all the different possible facet configurations; the switch we're testing here doesn't care about those details.

**Comment by LuomaJuha** [comment]
Cheers! Just noticed that without a default value, any templates which does not implement this broke so this was  one way to ensure it is always present in a way or another.

**Comment by LuomaJuha** [comment]
@demiankatz had a discussion with @EreMaijala and the assignment to variable is littlebit off, so will tune it to be in an attribute related to the facet

**Comment by demiankatz** [comment]
@LuomaJuha, will it be possible to do this in time for today's release? Do you need any help from my end?

**Comment by LuomaJuha** [comment]
@demiankatz how much till the release? Depends on that :O

**Review by EreMaijala — APPROVED** [review]
This works for me. There's still a possibility to get the "Select multiple filters" checkbox that doesn't work, but that'd require partial template updates, so I think this can be used without further modification.

**Review by demiankatz — APPROVED** [review]
Makes sense to me too -- thanks, @LuomaJuha!

**Pull request merged**
