### PR TITLE
Update PHP-CS-Fixer

### PR DESCRIPTION
**Pull request by demiankatz**
TODO:
- [x] Resolve dependency conflict with phpdocumentor2 over symfony/console.
- [x] Determine how to handle binary_operator_spaces (do we align, or not align, double-arrow/equals). (This will probably resolve itself by allowing the legacy behavior when https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2573 is completed).
- [x] Review the rule list at https://github.com/FriendsOfPHP/PHP-CS-Fixer and determine whether any new settings might be useful.
- [x] Update other vufind-org projects to match.

### CODE REVIEW

**Comment by crhallberg** [comment]
I'm willing to make a PR on PHP-CS-Fixer for this, but I will wait to see if there is a problem or not. I'd propose a separation of `binary_operator_spaces` and `align_operator_spaces`.

**Comment by demiankatz** [comment]
Status update: we are currently waiting for https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2573 to be completed and merged so that we can move forward with this. It should give us the flexible alignment functionality that we desire.

**Comment by EreMaijala** [comment]
FriendsOfPHP/PHP-CS-Fixer#2573 has been merged. Can this continue now? There's the additional motivation that version 2 supports caching of results and that can give a nice boost to the Travis build times. For reference the following files show the extra params I used to enable the caching in RecordManager:

https://github.com/NatLibFi/RecordManager/blob/master/.travis.yml
https://github.com/NatLibFi/RecordManager/blob/master/build.xml

**Comment by crhallberg** [comment]
Yes! We're just waiting for the next release, which [seems to have come out](https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v2.7.0 "Actually on v2.7.1 now.").

**Comment by EreMaijala** [comment]
@demiankatz Oh, that's disappointing. I'll take a look if I have time at some point, but I can't promise anything.

**Comment by demiankatz** [comment]
@eremaijala, Chris has started investigating. Don't spend any time on this without first checking his process. :-)

**Comment by crhallberg** [comment]
Just opened PR #1052 to resolve the dependency paradox.

**Comment by demiankatz** [comment]
@EreMaijala, an update: @crhallberg has fixed the phpDocumentor conflict by using the .phar download approach in place of composer, which seems to be working well. That has been merged to master, and from there into this PR.

That has allowed me to upgrade to php-cs-fixer 2.7.1, which incorporates https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2573.

That's the good news. The bad news is that we still don't seem to have what we want.

The binary_operator_spaces fixer now offers four different configurable behaviors: 'align', 'align_single_space', 'align_single_space_minimal', or 'single_space'. The actual meaning of these settings does not appear to be documented anywhere, so I'm not sure how the three different "align" methods differ from each other. Whatever they're supposed to mean, though, none of them offer the behavior we want, where a minimum of one space is inserted around operators, but existing alignment is not messed up. Every setting seems to make things worse, and some of the settings even seem to have bugs.

So I think this sets us back to square one: we either compromise on the alignment by picking one of the available behaviors (I think `single_space` is the only acceptable option of this current list, as the forced alignment makes things ugly in a lot of places), or we go back to trying to submit a fix that will add the behavior we want to php-cs-fixer.

Any thoughts?

**Comment by EreMaijala** [comment]
@demiankatz Well, I've always been a fan of single space, so I wouldn't have a problem with that, but I understand that in some places the code can become arguably uglier.

**Comment by demiankatz** [comment]
@EreMaijala, I may have found a starting point for a compromise: in commit https://github.com/vufind-org/vufind/pull/897/commits/46eceb027bc0eb01ed4f3cbac0d41347640f7179 I have configured the fixer to use the single_space rule for everything except the `=` and `=>` operators. Right now, no rule is enforced for those two in order to give us our current level of flexibility. This actually found and fixed some obviously erroneous spacing around other operators in a handful of files, so it only improves things without causing any harm.

I think changing `=>` to single_space would be a step in the wrong direction, since it would make a lot of things less readable... but aligning everything would also make a lot of things less readable. So it's probably best to leave that alone.

The `=` argument is less clear-cut -- single_space seems to make a lot of files cleaner; we seem to have a lot of totally unnecessary whitespace around assignments in our codebase. However, there are a handful of places where things are neatly lined up and might look a bit messier if we flatten them out. We should discuss this on the next dev call and see if there are any further opinions.

In the meantime, are there any other new rules in the rule list that you would like to add here?

**Comment by EreMaijala** [comment]
@demiankatz Sounds good to me. I haven't had a chance to really go through the list with new additions in mind.

**Comment by demiankatz** [comment]
I've reviewed the available rules and added what I believe to be some fairly uncontroversial choices, fixing a number of existing issues in the process. We can discuss this further on the next dev call.

There are several "risky" rules that look interesting and might be worth applying, but I decided not to use any of those as part of the core rule set to avoid potential problems.

**Pull request merged**
