### PR TITLE
Improve selection of a full star in rating.

### PR DESCRIPTION
**Pull request by EreMaijala**
It was difficult to select 1, 2, 3 or 4 stars because the hidden part of the half-star overlapped the full one.

### CODE REVIEW

**Comment by demiankatz** [comment]
@sturkel89, do you mind taking a look at this one? Just a matter of turning on ratings, comparing this against the release-10.1 branch, and confirming that setting ratings works better with this version than release-10.1 in all of the themes. (You just need to turn on ratings in the [Social] section of config.ini).

**Review by sturkel89 — COMMENTED** [review]
I may be doing something wrong, but in my testing I can't replicate there being a problem selecting any number of stars in **release-10.1** in Chrome or Firefox in any theme. 

I can select any whole number of stars or any half-star increment. Things worked well both in "Add first rating" view and in "Add or Update Rating."

I checked the test branch and release-10.1 thoroughly. Ratings selection works the same for me in both settings, so I can't say that I see an improvement with the test branch. (What am I doing wrong?)

**Comment by EreMaijala** [comment]
@sturkel89 For me the problem was that it was almost impossible to hit the full star because the half star was overlapping it (on the invisible part). Perhaps it's a peculiarity that only shows up on macOS, but it happened with both Firefox and Chrome.

**Review by demiankatz — APPROVED** [review]
Since the new code makes sense to me and isn't breaking anything for @sturkel89, I'll go ahead and merge this, even if it's only fixing a narrow platform-specific issue.

**Pull request merged**
