### PR TITLE
Reduce EDS API calls by caching data required for Search Options.

### PR DESCRIPTION
**Pull request by demiankatz**
TODO:
- [x] Discuss: is this safe/reliable? Should it be configurable? Do we need to factor any extra parameters into the cache key?

### CODE REVIEW

**Comment by xmorave2** [comment]
@demiankatz we have something similar, as we wanted to reduce EBSCO API calls too... this is what we are using on top of VuFind 2.x: https://github.com/moravianlibrary/CPK/commit/dac41e1575fda4356aaff0c4bba04b92e7b04dd1

**Comment by demiankatz** [comment]
Thanks, @xmorave2, that looks like a more elegant approach. When time permits (probably not for a couple of weeks, since I'm currently out of the office), I'll try to reconcile your version with mine and revise this PR.

**Comment by demiankatz** [comment]
Thanks again, @xmorave2 -- I think I've turned this into a "best of both worlds" version of the code. @mis306lu has offered to test/review as well, so I am requesting her input now. Do you have any thoughts on whether it is a waste of time to maintain separate caches for guest vs. non-guest users? If this is guaranteed to be the same under all circumstances, I can take that out... but it seemed like perhaps it might make a difference in some situations.

**Comment by xmorave2** [comment]
> Do you have any thoughts on whether it is a waste of time to maintain separate caches for guest vs. non-guest users? If this is guaranteed to be the same under all circumstances, I can take that out... but it seemed like perhaps it might make a difference in some situations.

@demiankatz: I am not an EDS guru, but I consulted it with colleague, and it looks like the data for guest and non-guest users could differ (but it depends on your EDS setting). So I think we need two separate caches

**Comment by mis306lu** [comment]
I tested this on my local environment and it works.  Tested as guest and as a logged in user.  I didn't run into any issues.  thank you!

**Comment by demiankatz** [comment]
Thanks, @xmorave2 and @mis306lu! I think this is ready, so I am merging it now.

**Pull request merged**
