### PR TITLE
Right-to-Left Language Support

### PR DESCRIPTION
**Pull request by crhallberg**
Adds a setting that allows admins to list languages to be supported with a right-to-left layout.

[LanguageSettings]
rtl_langs = ar,he

Right-to-left conversion powered by https://github.com/morteza/bootstrap-rtl.

Todo:
 - [x] Respect position of sidebar based on sidebarOnLeft
 - [x] Config documentation

### CODE REVIEW

**Comment by demiankatz** [comment]
This at least partially addresses https://vufind.org/jira/browse/VUFIND-287.

**Comment by crhallberg** [comment]
This is ready as far as I can tell, unless there's a good case to change the organization or location of the configuration.

**Comment by demiankatz** [comment]
I'll try to do some testing in the near future.

**Comment by demiankatz** [comment]
I made a few minor adjustments to simplify the code. This feels pretty elegant to me! Let's talk about it briefly on the next dev call, then merge if there are no objections.

**Comment by demiankatz** [comment]
No objections on the dev call, but I'm still waiting for some feedback from the team working on Arabic localization before proceeding -- just want to be sure they have no comments before we merge.

**Comment by demiankatz** [comment]
There have been no objections from anyone, so I have gone ahead and merged this to master (manually, to flatten commit history).

**Pull request closed without merging**
