### PR TITLE
Introducing holdings and item notes

### PR DESCRIPTION
**Pull request by lahmann**
As suggested by @demiankatz in https://github.com/vufind-org/vufind/pull/521#issuecomment-161026994 this pull request introduces the fields `holdings_notes` and `item_notes` to the returned item-array of ILS driver method `getHolding()` substituting the undifferentiated field `notes`.

To offer legacy support for the now deprecated `notes` field `holdings_notes` is mapped to `notes` (and vice versa) if a field (given by config.ini or default setting) does not exist (either because of old config.ini settings or due to deprecated usage of `notes` by the ILS driver) the alternate field is checked and if non-empty mapped to the current field.

I implemented the mapping-logic into Logic/Holds.php as this is the place where the holding-array is restructured for displaying convenience. As the textfield-logic in the template holdingsils.phtml does need a list of configured textfields to select the appropriate elements from the holding-array I would have had to setup parts of the mapping in the templates as well. Because the textfields-logic's purpose in Holds.php is only to make handling in the templates easier, I decided to group the textfields in a subelement textfields which eliminates the need to search the holding array for the configured textfields.

One thing to think about is, that the `notes` field is actually only used by the Symphony ILS-driver.

### CODE REVIEW

**Comment by lahmann** [comment]
Regarding the `item_notes` I have included those in holdingsils.phtml as ul-list - the bootstrap classes I found applied do not seem to be perfectly suited for this kind of list. If we are happy with the implementation this should be something to review before merging into master.

**Comment by demiankatz** [comment]
A couple of questions/comments:

1.) This makes sense to me, but it might be useful to add some notes to the randomly generated holdings in the Demo driver so that it's easier to test this out. (I can work on this if you don't have time -- just let me know).

2.) Once we have Demo driver support so that it's easy to look at this, I can talk to @crhallberg about the styling of the item_notes in case he has alternative ideas.

3.) Why do you say that Symphony is the only ILS driver that supports notes? I see implementations of the feature in quite a few drivers when I just do a full text search of 'notes' in the ILS folder. Am I misunderstanding something?

In any case, thanks for the progress -- looking good so far!

**Comment by lahmann** [comment]
1.) I just added holdings_notes and item_notes to the Demo driver.

2.) Sounds good!

3.) Sorry - I have to apologize as I let mislead myself from a quick fulltext search by my IDE ignoring one collapsed listing labeled "Usages in string constants"... `notes` is obviously used in several ILS drivers (which is good as this does not render the mapping unnecessary).

**Comment by demiankatz** [comment]
Thanks for the update! I'll show this to Chris shortly.

I've just pushed up a small code simplification that should fix the error in the Travis build.

One other issue I've just noticed: the field name must be using to dynamically generate labels in the holdings display, since I'm now seeing a label called "Holdings_notes:". It's probably easiest to just copy the existing notes string to the new holdings_notes string (which we can automate using the command-line language tools). However, perhaps it would be better to find a way to normalize all of this so that the same string is used regardless of the setting; that will prevent unnecessary language file bloat, though maybe it's not worth the effort.

Related: You've added an "Item Notes" string, but it's not in the language files yet. We should put it there so we don't forget about it!

**Comment by lahmann** [comment]
I fully agree that language file bloat should be avoided but I could not come up with a good way to get around this. Therefore I have gone ahead and updated the language files with the cli language tool.

**Comment by demiankatz** [comment]
Fair enough. In this case, it's probably justifiable to have some redundancy since it allows more granular display customization. I talked to Chris about the style stuff, and he'll take a look at that shortly. After that, we may be in a mergeable state.

**Comment by crhallberg** [comment]
I've considered two other options, let me know what you think:

Original (list-group)
list-group

Horizontal rule and ul (minimal)
hr-ul

Panel with info styling
panel-info

**Comment by lahmann** [comment]
Thanks @crhallberg - both are already better than my attempt with list-group :)

I think I would go with "Horizontal rule and ul (minimal)" as it's most unobtrusive and does not dominate the holdings row too much. Visually I like "Panel with info styling" more, but it would probably shift the user's attention too much towards the notes whereas these are only additional information.

Any other opinions?

**Comment by demiankatz** [comment]
What if we drop the horizontal rule and use a more tabular format, like:
<pre>
Item Notes: - Item 3 note 1
            - Item 3 note 2
            - Item 3 note 3
</pre>
? Pretty similar to "Horizontal rule and ul (minimal)" (which I also like), but using even less vertical real estate. Is there a good bootstrappy way to achieve that (so that, for example, the label can pop above the ul in narrow displays)?

Anyway, I agree that minimizing the emphasis on the notes is the best default behavior. If greater visibility is important, that should be a local customization.

**Comment by crhallberg** [comment]
I was waiting for feedback on the idea, but maybe this screenshot will help.
tablenotes

**Comment by lahmann** [comment]
Chris, thanks for the screenshot - it looks great and I have no strong objections. The only slight concern I have is if in case some notes contain lots of text the space below "Item Notes:" would not be used and shifts the text weight more to the right.
But I don't want to be too nitpicking as this looks great and any other tweaking needs to be done in customized themes anyway.

**Comment by crhallberg** [comment]
I added a but of css to prevent header wrapping for longer notes.

screenshot_1

I made a PR for the original branch: https://github.com/finc/vufind/pull/10

**Comment by demiankatz** [comment]
I actually thought header wrapping for longer notes might actually be desirable, to save vertical space. Did it look really bad?

**Comment by demiankatz** [comment]
(I mentioned it in chat because I thought we wanted to encourage it, rather than prevent it...)

**Comment by demiankatz** [comment]
I just realized that the word-wrapping is a non-issue, because the translation for "Item notes" is simply "Notes" (we're seeing "Item notes" in @crhallberg's screen shot because he very understandably must not have cleared his language cache when he checked out the branch). It might make sense to remove the wrap-specific styling since it serves little or no purpose (though I don't have strong feelings one way or the other).

@lahmann, is there anything else we need to talk about here, or are we ready to merge from your perspective?

**Comment by lahmann** [comment]
Demian, thanks for reviving this pull request! From my perspective this is ready to be merged.

Regarding the header-wrapping, my initial concern was that the current styling

with header wrapping disabled

does leave more vertical space unused than in comparison to

Horizontal rule and ul (minimal)

Plus header wrapping would not be an issue either. But as I said before, either way the styling looks great now and if someone needs to display very long notes it's easy to adjust the style accordingly.

Thanks again for your work, @demiankatz, @crhallberg !

**Comment by crhallberg** [comment]
I agree, the last picture above is probably the way to go, if I can tame or remove the horizontal rule.

**Comment by crhallberg** [comment]
I just opened a PR for you to switch to this new style!

**Comment by demiankatz** [comment]
In the interest of keeping things moving, I've gone ahead and merged Chris' PR. I've also added some missing escaping to the jquerymobile theme. In the near future, I'll give this one more test to see if I can find any remaining issues prior to merging it. Thanks, everyone!

**Comment by demiankatz** [comment]
Manually merged to master (with a little more jquerymobile theme tweaking) here: https://github.com/vufind-org/vufind/commit/0498863f3a2a28f797d524168d3ca49df0d32331

**Comment by lahmann** [comment]
Thanks @crhallberg and @demiankatz!

**Pull request closed without merging**
