### PR TITLE
Image based linking options for OpenUrl display

### PR DESCRIPTION
**Pull request by olli-gold**
I have prepared a PR to introduce image based linking for OpenUrl display. This should not affect anything in running systems unless it is configured.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks for this! One question: is there a particular reason you opted to create a new image-specific template and helper method, rather than putting this logic into the existing template for rendering OpenURLs?

As I see it, both approaches have advantages and disadvantages. As implemented here, we have a lot of redundant logic across different templates that could probably be encapsulated inside the single template for rendering OpenURLs. However, I recognize that this approach does offer more flexibility for customization since it offers the option of displaying different kinds of OpenURLs in different places.

It's also possible that I'm missing an important detail that forces you to take this approach -- I only took a cursory look at the code.

However, if my initial analysis is correct, here's a possible compromise that gives the best of both worlds: what if you move all of the display logic into the single OpenURL template, and add an optional parameter to the method for rending the template. By default, you'll get an OpenURL rendered according to the configuration parameter... but the parameter can be used to override the configuration, so that a custom template could force particular types of OpenURL renderings in particular places.

What do you think?

Also note that I'll most likely be removing the Blueprint theme next week (unless somebody objects on the mailing lists before then). If you decide to make changes, please feel free to skip updating the Blueprint templates since they may very possibly get deleted soon anyway. In the unlikely situation that we change our minds about removing Blueprint, we can always catch up on those templates later.

**Comment by olli-gold** [comment]
Thank you for your feedback, Demian!

You have got the reason why I used a new template: we needed the flexibilty to set the image based linking image anywhere in the template independently from the other OpenURL stuff. 

Your idea to use only one template and to use parameters to control, which OpenURL should be displayed is good - I will change that tomorrow.

**Comment by demiankatz** [comment]
Great, I'll look forward to the updates. Thanks!

**Comment by olli-gold** [comment]
Demian,

I have rewritten my pull request and have implemented it the way you suggested. Thanks again for the great idea and I hope, this is mergable now.

**Comment by demiankatz** [comment]
Thanks -- looks good, but one further suggested improvement that will make the template changes even more minimal: what if the $imagebased parameter to renderTemplate defaulted to null instead of false and then you started with:

<pre>
if (null === $imagebased) {
    $imagebased = $this->imageBasedLinkingIsActive();
}
</pre>

This way, you can override with true or false, but if you omit the parameter, you get the default setting. Makes the templates less verbose!

**Comment by olli-gold** [comment]
I have upgraded the code following your suggestion. Thank you!

**Comment by demiankatz** [comment]
Oliver,

I spent a little time playing with this and pushed up a few changes:

  - I added some comments to config.ini for new settings (please review/correct as needed).

  - I adjusted the helper class to isolate the image-based functionality and to simplify some code.

  - I adjusted the template to rename a variable (I thought $class_ib was more meaningful than $class_ft, though maybe I misunderstand the name) and reduce some redundancy.

I don't think I've broken anything, but if you can re-test, I'd appreciate it.

I've also come across a few issues (and I apologize if any of these are related to my refactoring, though I don't think they are):

1.) If your dyn_graphic setting does not contain a question mark, an invalid URL is generated (since the OpenURL is appended with an & character). I imagine it's possible there could be a dynamic graphic service that accepts the OpenURL directly with no other parameters, so we should probably support that.

2.) When embed is set to true, the embedded content does not load correctly when I click on the graphic (no OpenURL gets passed to the AJAX routine). Let me know if you need me to investigate this more closely on my end.

3.) I mention this just as a reminder to myself -- but when other issues are sorted out, we should add support to the jquerymobile theme for consistency.

Thanks!

**Comment by olli-gold** [comment]
Thank for the adjustments, Demian!

1.) You are absolutely right (as always) about the dyn_graphic setting. I will correct that.

2.) I have to admit, that I did not test the behaviour of the image based link in embedded context - though its absolutely possible that this does not work as expected. I will test that as soon as I can. 

3.) Did I forget jquerymobile?

**Comment by demiankatz** [comment]
1.) Thanks -- I'll test again when you've had a chance to adjust this.

2.) Let me know if I can be of any assistance in troubleshooting this.

3.) I wouldn't say you forgot it -- I didn't ask you to do it. But since the jquerymobile theme displays OpenURL links, it makes sense to add consistent support for image-based links there. I'm happy to do the work if you like (though of course I won't stop you if you're willing to do it yourself).

Thanks again!

**Comment by olli-gold** [comment]
This commit should adjust comment number 1.
https://github.com/olli-gold/vufind/commit/c7a68fe3a84c97b656ae7cef423ae3690c5b8f3a

**Comment by olli-gold** [comment]
Ahm, by the way, github is moaning about conflicts. Can I see, which conflicts that are?

**Comment by demiankatz** [comment]
This is probably related to Ere's recent fixes to OpenURL embedding. If it's not clear how to resolve the conflicts, let me know and I'll be happy to take care of it.

**Comment by demiankatz** [comment]
Never mind, I see you already fixed it!

**Comment by olli-gold** [comment]
Yes, it was my own fault. I had not the most recent version pulled, and so I had lost some lines of code in the version I pushed.

**Comment by demiankatz** [comment]
Hello again,

I made some more adjustments in an effort to further simplify the code:

  - There are now fewer variables passed to the view; I eliminated openUrlImageBasedBase and renamed openUrlImageBasedComplete to openUrlImageBasedSrc. I think this makes things slightly more clear.
  - I renamed openUrlImageBased to openUrlImageBasedOverride and changed the code so that rather than forcing the regular OpenURL into this variable in the helper, we simply use the existing openUrl variable in the view if the override value is undefined/false. This eliminates some lines of code and prevents us from having to unnecessarily run through potentially complicated OpenURL generation logic multiple times.

I also adjusted some minor problems that may have been related to the previous merge.

At the moment, embed is still broken. We'll definitely have to sort that out before we can merge this. I'll try to investigate soon if time permits. If you find anything in the meantime, please let me know... and I'll also report back here if I come up with findings of my own.

**Comment by demiankatz** [comment]
Okay, I think I've fixed the embedding problem. Please re-test and make sure all is well on your end!

**Comment by olli-gold** [comment]
Demian, you are too fast for me. Thank you for that!

I have tested your latest changes and have found a small logical mistake, that I corrected (without testing I wouldn't have found that, my intuition was the same as yours). 

I will have another quick look at the style issues github is moaning about, and than the last thing missing is just the integration into jquerymobile.

**Comment by demiankatz** [comment]
Can you repeat your tests? I think the code you changed was actually correct in the first place (at least, it still seems to be when I read it, and I'm pretty sure I tested both scenarios). Here's what it was before:

`false !== strpos('?', $base)) ? '&' : '?'`

I think it probably makes sense to improve its readability by changing it to this:

`false === strpos('?', $base)) ? '?' : '&'`

That more clearly states "if there is no ? in $base, append ?, else append &."

However, you've swapped the ? and & in a way that seems to me should have the opposite of the desired effect.

I apologize if I'm somehow still confused and looking at this backwards... but I don't think I am. In any case, it's clearly worth revisiting to be sure we don't stumble over it again in the future!

On an unrelated subject, I also received some helpful suggestions from @EreMaijala and plan to incorporate them later today or tomorrow to make the embed logic a bit cleaner. (Just need to find time to do it, and today is looking rather busy).

**Comment by olli-gold** [comment]
I have repeated my test, and I am as confused as you - as I mentioned, I would have thought the same way as you. But this definitely does not work.

I have debugged doing the following:
error_log($base);
error_log(false !== strpos('?', $base) ? 'There is a questionmark set, concatenate with &' : 'There is NO questionmark set, concatenate with ?');

This is the logic you have implemented. Using the base http://sfx.gbv.de/sfx_tuhh?__service_type=getFullTxt&__response_type=image-large we should suppose to get the first string.

But this is what I got:
[27-Aug-2015 15:24:09 Europe/Berlin] http://sfx.gbv.de/sfx_tuhh?__service_type=getFullTxt&__response_type=image-large
[27-Aug-2015 15:24:09 Europe/Berlin] There is NO questionmark set, concatenate with ?

Thats definitely wrong and thats why I reversed the logic.

Now I'll test the better readable option:
error_log(false === strpos('?', $base) ? 'There is NO questionmark set, concatenate with ?' : 'There is a questionmark set, concatenate with &');

And I still get the same result:
[27-Aug-2015 15:27:30 Europe/Berlin] http://sfx.gbv.de/sfx_tuhh?__service_type=getFullTxt&__response_type=image-large
[27-Aug-2015 15:27:30 Europe/Berlin] There is NO questionmark set, concatenate with ?

Maybe there is something strange with the questionmark as a special character, but strpos definetely does not return the expected value (or we both are wrong thinking about the logic of the function).

**Comment by demiankatz** [comment]
Mystery solved: we have our strpos parameters backwards! It's $haystack, $needle, not $needle, $haystack.

**Comment by demiankatz** [comment]
I can fix this later if you like, but I imagine you'll probably get to it first.

**Comment by olli-gold** [comment]
Hah - a classic mistake... Looking into the documentation would have saved a lot of debugging minutes on my side. Thanks for clarifiing this.

**Comment by demiankatz** [comment]
No problem. Now the mystery is how my tests work and led me to believe that everything was okay. Clear I was working too quickly! But anyway, glad we're making progress. :)

**Comment by olli-gold** [comment]
I have corrected that and tested again and now everything works fine for me. Thank you again, Demian!

**Comment by demiankatz** [comment]
Okay, I think I've cleaned this up to my satisfaction. A few more changes:

1.) More adjustments to the embedding logic (in an effort to be a little simpler).

2.) Renamed dyn_graphic setting to image_url (more consistent with the existing url setting).

3.) Added jquerymobile support.

Please give this one more look and let me know if you have any objections. If you're happy, I'll merge it tomorrow so we can get it into release 2.5. Thanks!

**Comment by olli-gold** [comment]
Perfect, I am happy with this. I have only added quotationmarks to the option for the image url in config.ini (to be sure it works when its enabled).

Renaming dyn_graphic to image_url is fine - although the static image (graphic option) could also be an url. Thats why I named it dyn_graphic, to clarify, that its also an image, but not a static one (as openUrlImage). But as already said, image_url is also ok.

**Comment by demiankatz** [comment]
When I renamed that, I had forgotten that the static image setting was just called 'graphic'. So actually I agree that 'dynamic_graphic' is probably the best way to go (I just expanded the 'dyn' since I think we can afford to use the whole word here). I've made that change, moved the configuration settings so that graphic and dynamic_graphic are closer together, and merged it all to master. Thanks again!

**Comment by olli-gold** [comment]
Great, thank you!

**Pull request closed without merging**
