### PR TITLE
Resolve OAI-PMH date discrepancies.

### PR DESCRIPTION
**Pull request by demiankatz**
TODO
- [x] Test

### CODE REVIEW

**Comment by demiankatz** [comment]
@EreMaijala, while testing #1331, I ran into a problem where the OAI-PMH server would not serve up records that I had just indexed. This appears to be time zone related. SolrMarc is indexing the records using UTC times. VuFind is setting the default 'until' date using the current local time. When local time lags behind UTC (i.e. GMT-4 where I am currently located), then records get unnecessarily missed.

I've just spent a couple of hours debugging this, and I'm still not entirely clear on how the various layers of code and storage are interacting and if/where time conversions are taking place. I'm wondering if this simple workaround of defaulting to a date in the future is good enough to protect us against problem edge cases, or if I'm just masking a deeper problem... but for now, I'm exhausted by this problem, so I'm opening this pull request for discussion.

I know you're using a somewhat different indexing stack than I am, so perhaps you are not even affected by the underlying problems I'm seeing... but I'm still interested in your input!

**Comment by demiankatz** [comment]
Thanks, @EreMaijala, that definitely helped put things in some perspective (though this still makes my head hurt). I've adjusted the code so that all dates generated in the Server.php code are converted to UTC, which makes the responses correct according to the spec (they previously were not). When generating a default 'until' value, I'm still adjusting it to be one day in the future as an extra safety net. This is probably not strictly necessary, but I don't see any harm in doing it, since the spec does not appear to specify default behavior for 'until' and this should ensure that everything is caught (unless there is a really wild problem with the indexing code).

I don't think any additional work is needed on converting dates/times for index/database lookups. At least, on my test system, all dates in MySQL and Solr are already correctly showing up as UTC. I'm testing with the SolrMarc indexer, though, so perhaps things behave differently with RecordManager and/or the XSLT indexer. Let me know if you think further discussion is needed there... but I have a feeling that we can merge this as a step in the right direction regardless of whether or not further adjustments are needed.

What do you think?

**Comment by EreMaijala** [comment]
@demiankatz I tested and you're correct about timestamps working fine with Solr since it uses UTC, but I'm not seeing the same with MySQL. I wrote a timestamp into change_tracker.deleted with time_zone set to +02:00, and when I retrieve the deleted header via OAI-PMH, it's the same timestamp. I suspect it seems to work because VuFind's indexer converts the timestamp to UTC and writes that as the local time, but if you look at the timestamps directly from MySQL using your local time_zone, they will look wrong.

**Comment by EreMaijala** [comment]
@demiankatz Oops, sorry! Please disregard.

**Comment by EreMaijala** [comment]
MySQL doesn't handle time zones for DATETIME fields, only TIMESTAMP fields. I didn't know that. Looks like it's working fine then, and the fields need to be stored in UTC.

**Comment by demiankatz** [comment]
@EreMaijala, I've confirmed that standard VuFind tools are always writing UTC dates to the database, and I've adjusted the wiki record change tracking page to mention the UTC requirement. I think that covers our bases, so I am merging this now. Thanks again for your help getting this sorted out!

**Pull request merged**
