### PR TITLE
Improved translation of hierarchical facet strings by encapsulating t…

### PR DESCRIPTION
**Pull request by EreMaijala**
…he values in TranslatableString class so that the original value can be read as a string and doesn't need to be stored in another index field.

### CODE REVIEW

**Comment by demiankatz** [comment]
Ere,

Looks like a good start, though a unit test appears to have broken. Aside from that, just one question: why put the object handling into the translate view helper rather than the TranslatorAwareTrait? I would assume that we want translation to behave the same way both in the view and in the controller, so modifying the trait instead of the helper will ensure consistent behavior across the board.

**Comment by EreMaijala** [comment]
That was an oversight, TranslatorAwareTrait is obviously a much better place. That's done, tests fixed and a couple more assertions added.

**Comment by demiankatz** [comment]
Thanks! This looks much better. However, I thought the distinction between translate() and getTranslation() was a bit confusing. I tried to rename and comment things to emphasize the fact that one method is intended for strings while the other also accepts objects. I think this makes the purpose of each a bit more clear. Do you agree? If you approve (and assuming I haven't broken anything) I'll go ahead and merge this as soon as I hear from you.

**Comment by EreMaijala** [comment]
That makes sense and makes it more clear and works, please go ahead and merge. Thanks!

**Comment by demiankatz** [comment]
Manually merged to master with a couple more minor comment tweaks. Thanks again!

**Pull request closed without merging**
