### PR TITLE
Added generic ILS exception handling in MyResearch actions.

### PR DESCRIPTION
**Pull request by EreMaijala**
This is a proposal for handling ILS exceptions on a high level in MyResearchController. While there's already exception handling in patron login, it's not sufficient for guarding against problems later on.

For testing with Voyager, you'll need #914 too. Then change the WebServices port to something invalid.

### CODE REVIEW

**Comment by demiankatz** [comment]
I'm not sure exactly what I should be looking for here -- I tried setting up a bad port as you suggested, then went through various MyResearch functions... but I didn't see an obvious difference between master and this branch. I thought the LoadNoILSOnFailure mechanism was already designed to help with some of these problems (and that's what I was seeing in my tests -- though I also had reasonable results when turning off that setting). Is it possible that you're seeing different results because MultiBackend is also part of the mix? Or am I simply looking at the wrong thing?

**Comment by EreMaijala** [comment]
MultiBackend is probably playing a part, but perhaps there are other settings too. I'll check again. We haven't used LoadNoILSOnFailure because of reasons I can't remember right now.

**Comment by demiankatz** [comment]
I think the reason you don't use LoadNoILSOnFailure may be somehow related to MultiBackend as well, but I can't remember the details either. In any case, let me know what you find and I'll be happy to give this another look (though it probably won't happen until I get back from vacation next week).

**Comment by demiankatz** [comment]
@EreMaijala, there hasn't been much conversation here in a while. It seems that #924 suggests a use case for this; just curious where you stand on its necessity. I've just done a bit of minor tweaking to make Codacy happy (it didn't like the one-character variable name -- and renaming it revealed that we were using the same variable for both the event and the exception, which was probably not ideal).

#924 brings up some issues related to end-user-readable vs. admin-readable exception messages, which I will discuss in more detail there... but curious if it's worth merging this in the meantime to get it out of the queue, or whether there's a possibility that we don't actually need this at all.

**Comment by EreMaijala** [comment]
I'm about to get back to this real soon now.. I'll try to do some testing today.

**Comment by EreMaijala** [comment]
Ok, so it's all about MultiBackend. Since NoILS gets loaded and replaces MultiBackend, we lose support for functionality that we have with MultiBackend, e.g. MultiILS authentication. Since MultiILS authentication requires MultiBackend, it would just throw an exception. There are other things too, like us expecting that supportsMethod() is available (that's fixable, but not in a way that it would return correct results).

**Comment by demiankatz** [comment]
So, if I'm understanding correctly, the bottom line is that we should go ahead and merge this, because it is helpful for MultiBackend users and will not hurt anything for everyone else. Perhaps we should add a comment to that effect, since the code is a bit unintuitive at a glance (not a criticism of your approach -- it's just a bit of a subtle thing because of the way it relies on Zend Framework infrastructure).

**Comment by demiankatz** [comment]
(If you agree that this is ready to go, I'm happy to expand the comments if you like -- not trying to make more work for you).

**Comment by EreMaijala** [comment]
Yes, I agree, and thanks if you can add/improve the comments!

**Comment by demiankatz** [comment]
@EreMaijala, I've made two changes:

1.) Added the comment as suggested.

2.) Added a feature to display the full exception message in development mode, since this may be helpful for troubleshooting (basically restoring some of the most important detail that is lost by intercepting the standard exception dump page).

Let me know if you think the comment is accurate and whether you have any objection to the development-mode tweak. If you're happy with all of this, I'll merge as soon as I hear from you. Thanks!

**Comment by EreMaijala** [comment]
That's a good tweak and the comment makes sense. Thanks!

**Pull request merged**
