### PR TITLE
Sandal theme improvements.

### PR DESCRIPTION
**Pull request by demiankatz**
Some theme improvements that didn't make it into #961 for release 4.0:

- [x] Modern checkboxes
  - [x] Fix "select all" functionality in combined search
  - [x] Consider a solution requiring fewer Javascript customizations
  - [x] Make test suite pass in sandal theme
- [x] Class improvements
  - [x] Advanced search links
  - [x] Hierarchy facets
  - [x] Eradicate .list-group, .list-group-item
- [x] CSS Grid Header ( #1026 )
- [x] Header float ( [for diff clarity, a PR onto the branch for this PR](https://github.com/crhallberg/vufind/pull/3) )
- [ ] Advanced search float buttons

### CODE REVIEW

**Comment by crhallberg** [comment]
How does this look for the scroll feature? Is it stable and functional? https://www.crhallberg.com/beta/scrolltest/

**Comment by demiankatz** [comment]
That scroll feature seems a little weird to me -- it scrolls off the screen when you scroll down, but then appears out of nowhere when you scroll up. Maybe this is a convention that I'm unfamiliar with, but it struck me as a little confusing.

**Comment by crhallberg** [comment]
I modeled it off what the [Washington Post website](https://www.washingtonpost.com/news/the-switch/wp/2017/09/15/the-practical-guide-to-choosing-a-smartphone/?utm_term=.5ba9d3e2cf89) and many mobile sites do. it's definitely a mobile-targeted design. I can keep the header from going off the top.

**Comment by ckaz** [comment]
Hmm, I personally find that behaviour a little confusion too. Thanks for the Washington Post example though. I tested it on Desktop (Firefox) and Smartphone (Chrome) but some confusion remains.

I don't fully get the usability idea behind this, but I guess it might be the following: 
When/as you read on (scroll down) you get the full screen real estate for better reading comfort? But only at a point where the designer assumes you scrolled because you wanted to read on. Therefore the topbar doesn't scroll immediately out of view. (One more reasing for making available more screen estate might be the Post's needs to show adverts!)
What doesn't make sense to me is that when you scroll back up, you don't get the topbar back immediately. This has potential for becoming a big nuissance. And it makes the entire topbar design decision smack of eye-candy over usability or, worse, not fully thought-out design. 

Or am I missing something here?

What I'd prefer _in a catalog_ would be to have the topbar visible when I need it, for example to change my search terms, log in, navigate. Not sure what the perfect solution for this might be. 

It could be a vote for "always sticky" on all sizes until a scroll down occurs that can be identified as a scroll aiming to read in the same page. I.e.: Not a scroll to get a rough overview of the results. (How many scrolls would this be?) Upon scroll up the toolbar should become visible immediately. 

However, we should evaluate inhowfar a catalog might be fundamentally different from a newspaper here. I guess people browse or scan catalogs rather than reading them. If that is the case, quick and reliable access to navigation could be paramount. To me that'd mean "always sticky".

Just my 2 cents. Cheers!

**Comment by crhallberg** [comment]
The idea was to get the header out of the way, yes. Look how much room the searchbox takes up on mobile:

**Comment by crhallberg** [comment]
The hiding of the header off the top is a space-saving member, yes. Look how much room the searchbox takes up on mobile:

image

There are a few things we can try:
- We can try having a color border always visible, so you know the header is there.
- We can try showing the breadcrumbs all the time.
- We can try disabling sticky headers on mobile.

**Comment by crhallberg** [comment]
@ckaz 

> What doesn't make sense to me is that when you scroll back up, you don't get the topbar back immediately. 

In the Post example or in my code example?

**Comment by ckaz** [comment]
Hi Chris,
> What doesn't make sense to me is that when you scroll back up, you don't get the topbar back immediately.

I meant the Post topbar. It's fine in your example.

Imo, the topbar-visible-or-not issue presents itself differently, if we strip down the XS header. For my taste, the XS-size version of Sandal contains way too much clutter. If we strip it to essentials, there will be a lot more real estate, so we can keep the topbar visible at all times. 

My preferences for the stripped-down header would be:
1. **Use icons instead of text buttons** to save space and arrange buttons and searchbox in one line. (I'd use text + icon from MD up, if necessary.) (see mockup below)
2. **Offer a link to advanced search** via an icon, and get rid of the entire "All fields ..." select box!
3. **Get rid of the breadcrumbs** on XS, and save another line. The navigation buttons on mobile devices should suffice to get back and forth. 
4. **Get rid of the suggestions** or wrap them in a dropdown-button or offcanvas.
5. **Get rid of "Showing ..." "for search ..." + "query time ..."** as this is mostly redundant or of little practical use, considering the users just performed a search and might want to see results as such.

This should **produce a view where users can comfortably see the first couple of results** even on an XS mobile. A view that focusses on the most important information and elments, clear and navigable.

If we'd go for an even more reduced look, we could try to think of an alternative for the logo which takes up lots of space. One option could be to have the searchbox there.

Cheers!

Comparison of reduced header (rough mockup) vs. current state:
sandal-xs-header-comparison

**Comment by demiankatz** [comment]
@crhallberg, I'm afraid we're in a similar situation here that we were with the last big theme update -- I'm not sure how to review and merge this, because there's too much going on here. A lot of commits, a lot of changed files, and several discrete changes being worked on at once.

It may be easiest to simply hold off on all of this until after 4.1 -- I think by the time we could refactor this to separate pull requests for review, we wouldn't have time to actually test them thoroughly enough. I'd also like to have @EreMaijala test the hierarchical facet changes for us, but he's on vacation right now.

If there are easy and/or critical changes you'd like to separate out to a different pull request, I'd be happy to do some testing and reviewing -- but I don't want to unnecessarily introduce problems to the release if we can avoid it, and there's just not much lead time at this stage.

Also note that the build is failing here due to some Javascript-related errors....

**Comment by crhallberg** [comment]
CLOSED: All of the best parts of this have already been incorporated into VuFind or copied into other pull requests. The rest of it should serve as a model of how to approach more advanced interfaces.

**Pull request closed without merging**
