### PR TITLE
Convert paths in css files using a naïve mechanism that disregards sy…

### PR DESCRIPTION
**Pull request by EreMaijala**
…mlinks etc.

This should allow the CSS minification to work with all kinds of combinations of symlinked directories since it doesn't rely on converting paths using their common parts.

TODO
- [X] Verify that this works properly in all cases. I'm going to implement this locally to make sure there are no more edge cases failing.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @EreMaijala. I'm back in the office now, so please let me know when you're ready for me to review this. If I don't hear from you sooner, I'll take a closer look once work on 6.0 begins.

**Comment by EreMaijala** [comment]
@demiankatz We now have this in production and it's finally working well for us.

**Comment by EreMaijala** [comment]
It's possible that this is somehow causing minification to intermittently output an extra path to the minified file, though I've been unable to pinpoint how exactly that happens since the error cannot be reproduced.

**Comment by demiankatz** [comment]
@EreMaijala, I'll keep an eye out for that behavior while testing. What leads you to believe the intermittent error might exist? Is there anything in particular I should be watching for?

**Comment by EreMaijala** [comment]
@demiankatz We're seeing intermittently both js and css files contain lines like this:

    [previous js file minified]

    /data/vufind2-views/finlit/skstestiuusi;
    [next js file minified]

The line is the base path to the VuFind instance. If I delete such file, it's recreated properly. That's the worst part that it seems to only happen randomly.

**Comment by demiankatz** [comment]
So something is actually dumping file paths into the file, thus presumably causing syntax errors? That's a weird one.

**Comment by demiankatz** [comment]
@EreMaijala, seems like if something is going wrong somewhere, it's unlikely to be related to the changes in this PR... more likely to be in the action of the https://github.com/vufind-org/vufind/blob/master/module/VuFindTheme/src/VuFindTheme/View/Helper/ConcatTrait.php -- though not sure what would be triggering it. Maybe adding some detailed debugging/logging there might help catch it in the act.

**Comment by EreMaijala** [comment]
Ok, huh, I found the reason. That happens at least if a non-minifiable file doesn't exist for some reason (in this case probably it just being updated). It should cause an exception, but that's obviously not happening. Anyway, probably it's completely unrelated. I'll investigate and post another PR if necessary.

**Comment by demiankatz** [comment]
Just updating this conversation to note that the above problems were resolved in #1308.

**Comment by demiankatz** [comment]
@EreMaijala, since this code does not appear to be causing problems, I have gone ahead and merged it. If you have any remaining concerns, please let me know!

**Pull request merged**
