### PR TITLE
Make search tab filters work with advanced search too and fix the "St…

### PR DESCRIPTION
**Pull request by EreMaijala**
…art a new Basic Search" in the advanced search results.

I somehow missed this from the original tab filters.

### CODE REVIEW

**Comment by EreMaijala** [comment]
Oops, I broke the basic tabs, fixing..

**Comment by EreMaijala** [comment]
Okay, now it should work properly.

**Comment by demiankatz** [comment]
I've made two changes to this:

1.) I found another edge case that needed to be sorted out: if you went to the home page and switched between tabs, hidden filters were not accounted for on the default advanced search links. I've addressed this, but in what feels like a rather brute-force way (see 4dabb3e). If you have any more elegant ideas based on your more recent close work with the code, I'm open to suggestions.

2.) I added support for hidden filters on advanced searches in jquerymobile. Not likely to matter much, but we might as well maintain the integrity of links across themes where possible. It looks like there may be some other edge cases that don't work in mobile -- I didn't attempt to fix everything, just avoided making it worse.

If these look good to you, I think we can go ahead and merge, but I wanted to give you a chance to offer feedback before rolling everything into master. Thanks!

**Comment by EreMaijala** [comment]
1.) Thanks, I missed that one too. I couldn't think of a cleaner way of doing, so it works for me.
2.) Ok, thanks.

I fixed the parameter definition of buildUrlHiddenFilters method in the SearchTabs view helper (no functional difference). I'm ready for merge.

**Comment by EreMaijala** [comment]
One more change: I removed one unused variable and added tab id to the result from getTabConfig() so that it can be used to identify the tab (not used in the base code but we'll need it).

**Comment by demiankatz** [comment]
Okay, manually merged to master to collapse commit history.

**Comment by demiankatz** [comment]
After merging, I found one more loose end: the "start a new basic/advanced search" links were not propagating hidden filters. Fixed here: https://github.com/vufind-org/vufind/commit/f541056029c427fb87192f09b0bff9e634b9efda

**Comment by EreMaijala** [comment]
Thanks!

**Pull request closed without merging**
