### PR TITLE
Add browscap cache to ignore list in admin API.

### PR DESCRIPTION
**Pull request by EreMaijala**
Since browscap cache should be a long-living one just like cover cache, it should not be cleared by cache clear command by default.

### CODE REVIEW

**Comment by EreMaijala** [comment]
After the first commit I realized that now that there are cache settings in cache manager, it would make sense to store the setting for persistence there as well. Last commit does that.

**Review by demiankatz — CHANGES_REQUESTED** [review]
@EreMaijala, there's a hard-coded reference to the browscap cache in [admin/maintenance/home.phtml](https://github.com/vufind-org/vufind/blob/dev/themes/bootstrap3/templates/admin/maintenance/home.phtml#L26). Can that be removed now that this mechanism has been added?

**Comment by EreMaijala** [comment]
@demiankatz Good point! Yes, though it also means that cover cache is now unchecked by default as well. But I think that's actually a good change.

**Review by demiankatz — APPROVED** [review]
Thanks, @EreMaijala, looks good to me and works in my test environment. I agree that it makes sense to change the default cover cache behavior too.

**Pull request merged**
