### PR TITLE
enables conditional filters for Solr

### PR DESCRIPTION
**Pull request by olli-gold**
This is my suggestion to enable conditional filters, which are interacting with the permission system. I guess the method permissionExists($name) should be better in another class, but I did not know, which class would be best for it. 

I have also done some documentation for the new option in searches.ini and have put an example for an appropriate permission set for conditional filters into permissions.ini.

It would be great, if you could review and comment, how this feature could be improved.

One limitation is, that its only applicable for Solr at the moment. But I think it shouldn't be too difficult to use it also in other contexts.

### CODE REVIEW

**Comment by olli-gold** [comment]
It was a hard fight with the style issues, but I guess now its according to the recommendations :-)

**Comment by demiankatz** [comment]
Thanks! A few initial comments:

1.) I'd add "(see [ConditionalHiddenFilters] in searches.ini for details) in the example comments in permissions.ini

2.) It's more efficient in the factory to skip attaching the event listener entirely if no conditional filters are defined -- no point in running that code if we know it won't actually do anything.

3.) I'm not sure that I understand the need for permissionExists(). If somebody defines a '-' filter on a rule that does not exist, that filter will always be applied because a non-existent permission can never be granted -- but I would expect that to be the desired behavior. I don't think we want to go out of our way to work around the results of a configuration error. But please correct me if I'm misunderstanding the purpose of this code!

4.) Rather than passing in the service locator to the listener, I think it would be better to pass in the actual dependencies (and I feel this even more strongly if you agree with me on point 3 above and no longer need direct access to the configuration). This will make it somewhat easier to write tests, which leads me into the next point....

5.) This new class would be a good candidate for a unit test. Let me know if you'd like help writing one.

6.) I notice that you have some private methods here. I'd recommend changing all private methods to protected -- as a general principle, we try to avoid private methods in the VuFind code so that people can more easily override things in subclasses if they have a need.

In any case, this is a great start, and while this is a bit of a long list, I don't think any of these are very significant issues. Thanks for working on this, and let me know if I can be of any assistance with the final polishing!

Regarding your observation about this being limited to working with Solr, that is true, but the other listeners are also Solr-specific. I think it's unavoidable that each service will need its own listener for dealing with permissions of this sort. If we need this functionality in more places, perhaps we can factor out a generic base class so that each service just gets a subclass with implementation-specific details... but fortunately this is fairly simple code, so that may not even be necessary!

**Comment by olli-gold** [comment]
Thank you for your comments, Demian!

1. No problem, thats a good addition
2. Right, I'll do that
3. I do not completely agree in that. This check helps to avoid unwanted behavior when there is a mistake in spelling (for example). The filter would be always applied (without any condition) and this could be a problem. I think it's better to ignore the filter in this case, and that's why I implemented this method. But if you feel uncomfortable with this method in this class (I have to admit that it's probably not the best place for it), then of course we could drop that extra check.
4. OK, that's true. I'll try to improve that.
5. Yes, I would like to try to write a test (that's kind of new for me, so I will need a bit time, but I am absolutely willing to learn it).
6. Right, I'll change the private methods to protected ones.

Thank you for your feedback and your absolutely helpful hints, again!

**Comment by demiankatz** [comment]
To respond to a couple of points:

3. I think if we want to do anything about an undefined permission, it would be better to throw an exception rather than simply ignore the setting. Ignoring the setting seems very likely to cause confusion -- for example, I could imagine myself doing this step by step: first, I define a conditional filter that is applied in the absence of a permission. I define the setting, and test my interface to see if the filtering is happening. Then, I add the permission definition to permissions.ini so I can refresh the page and watch the permission go away. If I got an exception after defining the setting, I would understand what was going on. If the setting were simply ignored, I could end up wasting a lot of time troubleshooting before I understood the behavior. So I suppose I could live with the exception, but I'm still not especially happy with that due to separation of concerns: ideally, the listener shouldn't have to know how the authorization service is configured in order to use the service. If somebody overrides the whole thing for some reason and ended up using a different configuration mechanism, that would unexpectedly break this listener. I'm still willing to make the assumption that people will test their configurations and confirm that they actually work in practice -- and that simple level of testing should be enough to catch typos in permission names.

5. Testing definitely takes some time to get used to. Please let me know if I can help you along in any way, either by answering questions or by putting together some boilerplate to get you started on the test writing.

**Comment by olli-gold** [comment]
OK, Demian, you persuaded me. I have removed the method and have done all the points from your list (except for the test, I will do that later).

Thank you!

**Comment by demiankatz** [comment]
Thanks! If you want any help with the test, just give me write access to this branch and let me know what you need and I'll chip in as time permits. I'll hold off on merging this until you give me the go-ahead.

**Comment by olli-gold** [comment]
OK, I have given you write access to my fork, so that you can help, if time permits. I would take David Maus' Test VuFind/tests/unit-tests/src/VuFindTest/Search/Solr/MultiIndexListenerTest.php as a skeleton for my test. I think, this is the most appropriate test for this context. Is that right or is there a better one I should use?

**Comment by demiankatz** [comment]
Yes, that's probably the most appropriate place to start, though I think your test will be considerably simpler.

**Comment by olli-gold** [comment]
I'm going mad trying to get the authorization service into my test. I see that there is a method getAuthorizationService, which can be executed on ServiceLocator Objects. But from where can I get the service loactor for my test? Do you have a hint how to do that?

**Comment by demiankatz** [comment]
I would advise against using a real authorization service in your tests. Just set up a mock object that demonstrates the behaviors you wish to test, and push that in instead. Something like:

<pre>
$mockAuth = $this->getMock('ZfcRbac\Service\AuthorizationServiceInterface');
$mockAuth->expects($this->once())->method('isGranted')->with($this->equalTo('myPermission'))->will($this->returnValue(true));
</pre>

(This creates a fake authentication service which expects a single call to isGranted('myPermission'), which it will cause to return true).

It gets a little more complicated if you want to simulate multiple calls -- you can either use $this->at(0), $this->at(1) in place of $this->once() to specify different inputs and outputs at different calls to the same method, or you can use callbacks in places to more flexibly simulate dynamic behavior.

I hope this is a useful clue, but let me know if you need more details... and apologies if my example is not 100% correct; it's from the top of my head. If you have trouble getting it working, let me know and I can help figure out where I mistyped. ;-)

**Comment by olli-gold** [comment]
Thank you for that suggestion. I also wondered about using a mock, but didn't know how. 

I'm still afraid I do not totally understand your suggestion. My class expects to have an AuthorizationService associated with it (since I am using $this->getAuthorizationService() in the key method addConditionalFilter()). How can I seriously test this method with the mock object you mentioned? I don't want to test the AuthorizationService, but my class, which is depending on that AuthorizationService.
Sure, I could use a mock object from my class and test that, but what would that say?

Do you have another suggestion how to solve that or could explain, in what way the mock object could help in this case, please?

**Comment by demiankatz** [comment]
Presumably in each of your test cases, you manually construct the InjectConditionalFilterListener object that you are going to test. You can use that object's setAuthorizationService() method to inject the mock authorization service into the object. The expectations you set up on the mock object are part of the testing project -- this enables you to test that the object is requesting the permissions that you expect it to. The values you force the mock object to return are also part of the testing project: these enable you to simulate a real authorization service and force your listener code down the paths you wish to test.

Does that help?

**Comment by olli-gold** [comment]
Thank you for your help, Demian. Unfortunately it's still not working as I want it to. I have commited my efforts, so that you can see, what I was doing. 
If I understood you correctly, you suggested to make something like that: 
        $this->listener = new InjectConditionalFilterListener(self::$searchConfig);
        $mockAuth = $this->getMock('ZfcRbac\Service\AuthorizationServiceInterface');  $mockAuth->expects($this->once())->method('isGranted')->with($this->equalTo('myPermission'))->will($this->returnValue(true));
        $this->listener->setAuthorizationService($mockAuth);

Trying that I get the following error from phpunit:
Argument 1 passed to VuFind\Search\Solr\InjectConditionalFilterListener::setAuthorizationService() must be an instance of ZfcRbac\Service\AuthorizationService, instance of Mock_AuthorizationServiceInterface_ca1e8934 given, called in /srv/www/vufind2/vufind/module/VuFind/tests/unit-tests/src/VuFindTest/Search/Solr/ConditionalFilterListenerTest.php on line 145 and defined

I guess I cannot use the mock object for my class. Do you have an idea, what's wrong in that case?

**Comment by demiankatz** [comment]
The problem in this case is simply that the type hint on the setter is more specific than I had expected. Instead of mocking the interface, you're going to have to mock the real object. Not a big deal, except that you'll have to change:

`$this->getMock('ZfcRbac\Service\AuthorizationServiceInterface')`

to

`$this->getMockBuilder('ZfcRbac\Service\AuthorizationService')->disableOriginalConstructor()->getMock()`

**Comment by olli-gold** [comment]
Great, thank you very much, this is working. So I can continue writing the tests. 

Thanks so much!

**Comment by demiankatz** [comment]
Great!

**Comment by olli-gold** [comment]
I have finished working on the tests and hope, this is fine for release now.

**Comment by demiankatz** [comment]
Great work! I've manually merged this to master in order to flatten the commit history and to make a few very minor adjustments (ran php-cs-fixer to tidy up a couple of things, and adjusted some .ini comments slightly).

**Comment by olli-gold** [comment]
OK, thank you!

**Pull request closed without merging**
