### PR TITLE
Change single authors to plurals

### PR DESCRIPTION
**Pull request by LuomaJuha**
Give credit to all the authors in citation

### CODE REVIEW

**Comment by LuomaJuha** [comment]
I just left this pull request as I think it would be better that every primary / corporate author could get their name to the needed citation.

**Comment by demiankatz** [comment]
@LuomaJuha, this makes sense to me -- but as currently coded, corporate authors will only be included if there are no primary authors. Is that intended?

**Comment by LuomaJuha** [comment]
I was thinking about that, but to me it seems that writers are usually mentioned only in these kinds of citations. One thing I also noticed is that it adds the word and to some of those so I was thinking about adding a translation for that word?

**Comment by demiankatz** [comment]
@LuomaJuha, thatat makes sense, but in that case, I don't think you need to have separate $authors and $primary arrays, nor do you need to array_merge... I think it might be simpler to just assign to $authors directly in all cases. Does that make sense?

Regarding translation, I couldn't find the word you were referring to. I suppose there could be some debate about whether or not it is appropriate to translate citation formatting, depending on how strictly you interpret the citation standards... but I'm open to adding translation if there is something missing.

**Comment by LuomaJuha** [comment]
Seems like I had to add ',' after reading online.

**Comment by demiankatz** [comment]
@LuomaJuha, thanks for the latest additions; this is looking good! Just one question: was there a particular reason to cast all of the outputs to array? I thought the code should work without the casting... and if you need the casting, then you can remove the is_array check, because it will always resolve to true.

**Comment by LuomaJuha** [comment]
@demiankatz I thought so too, but there were some failing tests without the casting.

**Comment by demiankatz** [comment]
Thanks, @LuomaJuha, this looks good to me!

**Pull request merged**
