### PR TITLE
Custom munge for dismax handler

### PR DESCRIPTION
**Pull request by hajoseng**
I just wondered why there is no Custom Munge processing for dismax-style queries. If there is no reason for this I added Custom Munge processing (and enhanced ist a little bit)

### CODE REVIEW

**Comment by hajoseng** [comment]
I just realised that I've overseen something important; I close the request and do some further work on this issue. Sorry.

**Comment by demiankatz** [comment]
No problem, @hajoseng; please let me know if I can do anything to help!

**Comment by hajoseng** [comment]
Thank you @demiankatz. You can indeed help me and give me a hint, if "custom munging" dismax-queries makes sense in your opinion. As far as I understand it's not implemented and CustomMunge sections within searchspecs.yaml has no effect on DismaxField. If it makes sense in your opinion I'd prepare a pull request on this issue.

**Comment by demiankatz** [comment]
@hajoseng, I think the ability to apply munging to Dismax queries could be useful... but you'll need to introduce some new syntax to make it work. Munging is currently used in the context of the Lucene query builder, where we build up a big OR query with different munging rules applied to searching different specific Solr fields. Since dismax queries don't use the same fielded approach, I'm assuming you would want to apply munging to the entire user query just once, instead of building up a complex Lucene-style query. That probably means you would need a new seciton in the Yaml, like `DismaxMungeRules:` where you could create a list of rules to apply to the overall Dismax query. Is that what you had in mind? If so, I don't see any harm in adding it, and I believe it could be useful. If you had something different in mind, we should probably discuss further to get on the same page!

**Comment by hajoseng** [comment]
Thank you for you're comment. I'm going to work on this and prepare a pull request.

**Comment by demiankatz** [comment]
@hajoseng, if you want, when the time comes, you're welcome to force-push your code to this existing branch and reopen this pull request so the existing conversation is associated with the new code (though you can also just open a new one if that's easier). Let me know if I can be of any further assistance!

**Pull request closed without merging**
