### PR TITLE
Allow custom labels for AuthorityRecommend.

### PR DESCRIPTION
**Pull request by demiankatz**

### CODE REVIEW

**Comment by psmukhopadhyay** [comment]
What it does?

No custom labels for AuthorityRecommend produces something like this:

-------------------
    Search: Myocardial infarction

No Results!

Your search - Myocardial infarction - did not match any resources.
See also:
Coronary heart disease, Infarction
See also:
Ventricular remodeling, Cardiogenic shock
---------------------------------------

custom labels for AuthorityRecommend produces something like this:

------------------------------
No Results!

Your search - Myocardial infarction - did not match any resources.
See also:
Coronary heart disease, Infarction
Use For:
Ventricular remodeling, Cardiogenic shock
---------------------------------

**Comment by demiankatz** [comment]
@psmukhopadhyay, that looks like what I would expect, but perhaps I am missing something. If you provide no custom label, it defaults to "See also," as demonstrated by your first example. If you customize labels, they are used, as demonstrated by your second example. Is something not working as expected for you?

**Comment by psmukhopadhyay** [comment]
@demiankatz, yes it is working as desired, for example, the following two lines produce the result given below.
Subject[]        = "AuthorityRecommend:record_type:Topical*:source:ILS-FAST:__mode__:seealso:__header__:See also (Broader heading):__resultlimit__:10"
Subject[]        = "AuthorityRecommend:record_type:Topical*:source:ILS-FAST:__mode__:usefor:__header__:Used for/See from:__resultlimit__:10"

------

No Results!

Your search - Myocardial infarction - did not match any resources.
See also (Broader heading):
Coronary heart disease, Infarction
Used for/See from:
Ventricular remodeling, Cardiogenic shock
-------------------------------------------------
And
----
 Your search - heart attack - did not match any resources.
Used for/See from:
Silent myocardial ischemia, Myocardial infarction
----------
The BT (Border Term) it can manage successfully but my slight confusion is here...... If we see the block Cardiogenic shock in FAST, it shows: 
 
Cardiogenic shock
See also:
Myocardial infarction
Shock
Use for:
Circulatory shock 

And the block 'Ventricular remodeling' shows

 Ventricular remodeling
See also:
Myocardial infarction Complications
Use for:
Cardiac remodeling, Ventricular
Myocardial remodeling, Ventricular
Remodeling, Ventricular
Ventricle remodeling
Ventricular cardiac remodeling
Ventricular myocardial remodeling
----

Obviously 'Myocardial infarction' is a BT of 'Cardiogenic shock' and 'Ventricular remodeling' but in the display the favour of BT-NT relationship is missing (coming under the generic 'Used for/See form' - the label I used). But in case of a non-preferred heading, it can successfully lead to preferred heading, for example,
----
 Your search - mechanization of library - did not match any resources.
Used for/See from:
Libraries Automation
--------------

**Comment by demiankatz** [comment]
Thanks, @psmukhopadhyay. I think it sounds like we can merge this pull request, since the functionality added here is working as expected... but we should also probably continue the conversation about the broader AuthorityRecommend functionality, because while I believe it is working as intended, there may be some other options that we need to add, and the existing naming of things may be confusing or misleading.

Right now, what the "usefor" mode is doing is running the user's search against the authority index looking for records that contain matches somewhere in the headings, but not in the main heading. This should pick up a list of main headings where the search terms are in the "see also" or "use for" fields.

The "seealso" mode is doing the opposite -- it is searching for the user's terms ONLY in the main heading field, and then retrieving any "see also" references indexed into the authority record.

To see this in action in the code, take a look at the methods here, which build the queries:

https://github.com/vufind-org/vufind/blob/master/module/VuFind/src/VuFind/Recommend/AuthorityRecommend.php#L201

...and the configuration here, which defines how the VuFind search handlers referenced in the above code actually map to Solr fields:

https://github.com/vufind-org/vufind/blob/master/config/vufind/authsearchspecs.yaml

Does that help clarify what is happening? Do you have suggestions for changes or additions?

**Comment by demiankatz** [comment]
@psmukhopadhyay, I have gone ahead and merged this. If you want to discuss functionality further, please feel free to email me or open a JIRA ticket.

**Comment by psmukhopadhyay** [comment]
Thanks Demian. It will be helpful for vufinders. In future we may try to have another mode option like **mode**:usefor so that it can handle RT issues. I am trying prepare a concept paper on the basis of my experiences with authority data. I'll share it with you as and when it will be ready. Regards....

**Comment by demiankatz** [comment]
Thanks, @psmukhopadhyay, I will look forward to hearing more!

**Pull request merged**
