### PR TITLE
Local override of xsl files

### PR DESCRIPTION
**Pull request by mathieugrimault**
Poor man's solution. 
A better approach would be to move "xsl" directory out of module in root directory and have : 
if (file_exists(LOCAL_OVERRIDE_DIR . '/xsl/' . $xslt)) {
            $style->load(LOCAL_OVERRIDE_DIR . '/xsl/' . $xslt);
        } else {
            $style->load(APPLICATION_PATH . '/xsl/' . $xslt);
        }

I have done some tests and it seems ok but I don't know every functionalities behind Processor class and if all files in 'xsl' directory are loaded by Processor.

### CODE REVIEW

**Comment by demiankatz** [comment]
Out of curiosity, what is your use case here? Are you trying to locally override the MARC rendering? It seems that this mechanism is not used very heavily, so it would probably not be very disruptive to move the files as you propose. I certainly wouldn't object, but understanding your goals might help inform my opinion.

**Comment by mathieugrimault** [comment]
We use the marc staff view in production, we find it very helpful. 
In UNIMARC, data fields 909 can contain login and/or passwords so we need to hide them to unauthenticated users.
More, we are not allowed to display data fields 011 and 530 (issn data).

**Comment by demiankatz** [comment]
That makes sense. Would you like me to merge this as-is, or would you prefer to move the xsl directory outside of the module? Perhaps it would even make sense to check three levels -- first the module, then the top level VUFIND_HOME, and finally the VUFIND_LOCAL_DIR. This would allow us to make a more gradual transition -- we could begin supporting /xsl with 5.1, and then move the files out of the local module in 6.0.

**Comment by mathieugrimault** [comment]
Yes, checking three levels could make migrations easier. I can't decide if it's better or not. 

Maybe I misunderstand but I would change your order, for 5.1 : 
1. VUFIND_LOCAL_DIR/xsl -> customization 
2. VUFIND_HOME/module/VuFind/xsl/ -> actual files
3. VUFIND_HOME/xsl -> 6.0 files

And in 6.0 swap to : 
1. VUFIND_LOCAL_DIR/xsl
2. VUFIND_HOME/xsl

**Comment by demiankatz** [comment]
@mathieugrimault, yes, I was speaking in reverse order for some reason, but you have correctly interpreted what I was trying to say. :-)

**Comment by demiankatz** [comment]
@mathieugrimault, thanks again for this. I've rewritten it slightly to make it easier to change in future and will merge to master now.

**Pull request merged**
