### PR TITLE
Add missing translations for MultiBackend messages.

### PR DESCRIPTION
**Pull request by demiankatz**
These changes were proposed in discussion on #2196. I'm interested in whether @EreMaijala feels any changes are needed, and also whether @xmorave2 still wishes to move forward with #2196, or if it can/should be closed after this is merged.

Note that no driver-side translation is needed for these messages since translation is handled in the flash message display. (I confirmed that things work as expected).

### CODE REVIEW

**Review by xmorave2 — APPROVED** [review]
I am OK with this. From my point of view it' good for now, so I am going to close #2196

**Comment by demiankatz** [comment]
Thanks, @xmorave2 -- just noticed that I broke some tests as well; hopefully I've fixed them now. I'll wait to hear from @EreMaijala before merging this.

**Comment by EreMaijala** [comment]
@demiankatz Looks good to me!

**Review by EreMaijala — APPROVED** [review]

**Comment by demiankatz** [comment]
Thanks, @EreMaijala -- merging now!

**Pull request merged**
