### PR TITLE
Switched caching in VoyagerRestful driver from session to Zend cache.

### PR DESCRIPTION
**Pull request by EreMaijala**
Eliminate the use of session for caching in VoyagerRestful driver in preparation for #584.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, looks good. Just two suggestions:

1.) Can you move the cache parameter to the end of the constructor parameter list; now that it's optional, you can get away with this, and it will improve backward-compatibility. (Alternatively, you could also omit it from the constructor and add a setter to inject it; since it is optional, this might make the signature a little cleaner).

2.) I think it might make sense to better encapsulate the cache key generation... rather than having to do the md5 hashing in the functions that use the cache, what if you keep the values passed to getCachedData/putCachedData the same but have both of those methods use a "formatCacheKey" method that does the "VoyagerRestful-" prefixing and the md5 hashing of the significant part of the key with the unique Voyager identifiers? This should make the code outside of the cache internals more readable and also make it easier to change the key generation algorithm in the future if some other factor comes into play.

I can help with this if necessary. Thanks!

**Comment by EreMaijala** [comment]
Thanks for comments! I don't mind if you'll be able to help, but otherwise I'll try to revise tomorrow.

**Comment by demiankatz** [comment]
Sounds good. I have a few other things to work on today, but if I get done with those early I'll work on this. If I don't get to it, you'll know by the lack of activity tomorrow morning.

**Comment by demiankatz** [comment]
Okay, I've made the changes I suggested. I also noticed there was still one remaining reference to $this->session, so I got rid of that as well.

**Comment by demiankatz** [comment]
@EreMaijala, can you test this tomorrow? If it looks good to you, I'll merge it as soon as I get the go-ahead.

**Comment by EreMaijala** [comment]
Thanks! Tested and works good, but then André mentioned that he could use it for DAIA and we also need caching for another driver, so I though it would make sense to put the supporting functions to the base class. The last commit does that. If you think this is a good idea, please go ahead with the merge.

**Comment by lahmann** [comment]
Thanks a lot Ere! Looks great and it will definitely be of great use in the DAIA driver to improve performance.

**Comment by demiankatz** [comment]
Thanks -- good idea to share the functionality. I've manually merged this to master.

**Pull request closed without merging**
