### PR TITLE
Display AND operator in filter list

### PR DESCRIPTION
**Pull request by liowalter**
I would suggest displaying the AND operator as well in the filter list. The NOT and OR operators are already displayed.

Here is an [example](https://www.swissbib.ch/Search/Results?filter%5B%5D=navSub_green%3A%22History%22&filter%5B%5D=navSub_green%3A%22Germany%22&filter%5B%5D=%7EnavAuthor_full%3A%22Benz%2C+Wolfgang%22&filter%5B%5D=%7EnavAuthor_full%3A%22Schubert%2C+Werner%22&type=AllFields) or you can have a look at the screenshot below.

What do you think ?

screenshot_307

### CODE REVIEW

**Comment by EreMaijala** [comment]
Lionel, see also PR #1265.

**Comment by demiankatz** [comment]
@crhallberg, interested in your thoughts on this, though as @EreMaijala points out, this work may be superseded by the work in progress on #1265.

**Comment by crhallberg** [comment]
In light of the active filter visual overhaul, I still think we should go forward with this. This information needs to make its way into the new version as well.

**Comment by demiankatz** [comment]
I've gone ahead and merged this into master while simultaneously updating #1265 to include matching behavior. Thanks again, @liowalter, and sorry for the delay in getting this fully resolved!

**Pull request merged**
