### PR TITLE
German help translations updates

### PR DESCRIPTION
**Pull request by cwolfebsco**
As discussed via Slack, these are updated translations for VuFind.

**blender.phtml** & **blender_advsearch.phtml** were aligned with search.phtml & advancedsearch.phtml to provide consistency in the way information is proviced.

**geosearch.phtml** was translated from scratch, by comparing to functionality as it is presented in https://www.coldregions.org/vufind/Search/Results?filter[]=long_lat:Intersects(ENVELOPE(-68%2C+-9%2C+-62%2C+-76)) - my recommendation would be to rewrite the English original for clarity and then re-translate. 

**tags.phtml** was aligned with English, but will be removed in VuFind 10 (https://github.com/vufind-org/vufind/pull/3174)

**visualization.phtml** was translated. In German Treemap can be used as an English term "Tree Map" or as German translation "Baumkarte"  - see https://de.wikipedia.org/wiki/Tree_Map - I've chosen to introduce both terms, but left the link to the original English article about the type of visualization intact.

I am not precious about translations, so I welcome any updates by the community. My testing was limited to copying the translations to a locally installed VuFind and viewing the updates by changing the query parameter, e.g. `http://{{localserver}}/vufind/Help/Home?topic=blender`

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @cwolfebsco! I've asked for reviews from all of our German-speaking committers. Obviously, I don't expect everyone to comment, but if anyone has time to take a look within the next 24 hours or so, I would appreciate it. If no one objects, I will merge this tomorrow when I begin building the release.

**Review by hajoseng — CHANGES_REQUESTED** [review]
I only found some minor issues: In visualization.phtml linie 1 it should be "sehe" instead of "sehen" in "Was sehen ich hier?" and in line 4 "Kategorien" instead of "Kategoriren". In tag.phtml I found a missing comma after "Informationen" in "Informationen auf die er angewendet wird".

**Comment by demiankatz** [comment]
Thanks, @hajoseng! I believe I've made the corrections you highlighted at https://github.com/vufind-org/vufind/pull/3176/commits/d61d8ab6faa2f09961ddbe796e87873477a1e6a3.

**Comment by hajoseng** [comment]
@demiankatz: Yes, thank you.

**Review by hajoseng — APPROVED** [review]

**Comment by demiankatz** [comment]
I think this is fine to merge now. If anyone else has feedback, feel free to open a follow-up PR.

**Pull request merged**
