### PR TITLE
Make Piwik helper more robust.

### PR DESCRIPTION
**Pull request by EreMaijala**
Piwik helper was trying to access the result of ViewModel->getCurrent() without null checking (apart from getCombinedSearchResults, which already did). I encountered this while calling Record helper's renderTemplate() from an AjaxHandler.

Also make the helper try current view for a record driver if there's no current template in the ViewModel.

### CODE REVIEW

**Comment by jochen-lienhard** [comment]
@EreMaijala shall we discuss the problems of tracking using accordion or tabs in this PR too?

1. When using accordion/tabs the action is not track
2. When switching to another accordion it is tracked but no customvariables.

**Comment by EreMaijala** [comment]
@jochen-lienhard I don't believe this affects the accordion, so let's keep that separate.

**Comment by jochen-lienhard** [comment]
OK, than I wait with a new PR until this is merged.

**Comment by demiankatz** [comment]
This looks reasonable to me. I'm merging it now; @jochen-lienhard, please go ahead with your new PR whenever you're ready!

**Pull request merged**
