### PR TITLE
Fix XCNCIP driver cancel request

### PR DESCRIPTION
**Pull request by xmorave2**

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @xmorave2 -- happy to merge this, but before I do: would it make sense to add any test coverage over these changes? (Same question also applies to the work I already merged from #2176).

**Comment by xmorave2** [comment]
@demiankatz I added some more test for these two patches

**Comment by demiankatz** [comment]
Thanks, @xmorave2!

**Comment by xmorave2** [comment]
Thanks @demiankatz! But I made a typo in code which makes CI fail - I have fix in this branch, but pushed after you merged this. Should I open new PR or could you fix it by cherry-picking or manually?

**Comment by demiankatz** [comment]
Oops, sorry about that! I can cherry-pick a commit if you point me in the right direction.

**Comment by xmorave2** [comment]
It's this one: https://github.com/moravianlibrary/VuFind-2.x/commit/0389abe04e7118d7978d13cc92ae1943c445613a

**Comment by demiankatz** [comment]
Thanks again, @xmorave2 -- fixed now!

**Pull request merged**
