### PR TITLE
Upgrade to Solr 6

### PR DESCRIPTION
**Pull request by demiankatz**
This PR gets VuFind up to date with Solr 6.

TODO:

- [x] Resolve deprecation warning in browse handler (see work in progress at https://github.com/vufind-org/vufind-browse-handler/pull/20)
- ~~Resolve deprecation of solr.SynonymFilterFactory~~ Ignore for now!
- [x] Recompile browse handler
- [x] Run full test suite
- [x] Wait for resolution of this major performance bug: https://issues.apache.org/jira/browse/SOLR-10130

### CODE REVIEW

**Comment by demiankatz** [comment]
As of today, all tests are passing.

**Comment by EreMaijala** [comment]
With Solr 6.4 the new MLT should finally be usable, along with a multitude of other improvements, of course. I'd suggest upgrading to it.

**Comment by demiankatz** [comment]
Great, I'll get everything up to date when time permits!

**Comment by demiankatz** [comment]
@EreMaijala, I've just updated to Solr 6.4.1. This seems to introduce a couple of new deprecations -- one in compiling the browse handler, and one related to solr.SynonymFilterFactory. Documentation seems to be sparse on the best way to address these issues. Have you investigated either of these things on your end? If not, I'll take the time to do it -- just wanted to avoid repeating work that's already been done.

**Comment by EreMaijala** [comment]
I can't say about the browse handler (we're not using it now because we couldn't make it scale well enough), but for now it's safe to ignore the SynonymFilterFactory deprecation. I inquired about it on the solr-user list (see topic "Solr 6.4.0 and deprecated SynonymFilterFactory​"). It seems to have been quite premature and the replacement has some issues.

**Comment by demiankatz** [comment]
Good to know, regarding SynonymFilterFactory. Hopefully the browse handler issue is relatively simple. I'll look into it when time permits.

**Comment by demiankatz** [comment]
All tests are passing, and I figured out that some of the weird behavior I was seeing during testing had to do with ClassicIndexSchemaFactory no longer being the default behavior in Solr 6; I think for VuFind's default setup, we're better off keeping the classic functionality, so I have adjusted the configs accordingly.

I think we may be pretty close to being able to merge this. Just a matter of deciding whether or not to risk going to the just-released 6.5.0 and seeing whether we can do anything about the browse handler deprecation (I've just sent an email to @marktriggs to see if he has advice... but if not, I think we can survive as-is and deal with the deprecation problem later).

**Comment by demiankatz** [comment]
Looks like the deprecation issues in the browse handler are sorted out. Thanks again to @marktriggs.

**Pull request merged**
