### PR TITLE
Fix for multiple relators in marc field

### PR DESCRIPTION
**Pull request by demiankatz**
MARC fields with multiple relator-codes/terms (repeatable subfields $E and $4) are currently indexed only once, i.e. only the first found relator-code/term will get indexed.

This pullrequest adds a MARC record containing the relator-codes `edt` and `trl` for a person in MARC 700$4 and implements a workaround in `author.bsh` to index each occuring relator-code/term with its corresponding entity-name. That is for the mentioned example the person will be indexed twice in author2 - once as `edt` and once as `trl`.

This PR supersedes the earlier #689.

###### TO-DO
- [x] Substitute newly added MARC record with artificial test-record covering more cases?

### CODE REVIEW

**Comment by lahmann** [comment]
Demian,

thanks for reviving this issue! Looking at the code the approach looks pretty good so far - what I did not update in #689 but was working on locally is the possibility of $e and $4 diverging, e.g. three primary relator codes and two primary relator terms are found (if I am not mistaken $e and $4 are not required to correlate in terms and codes, and in quantity). Luckily #771 should help by normalizing any known $e to a relator code allowing `relators` being deduped so that any found relator from $e and $4 matching the permitted roles will be indexed.
Therefore thumbs up for this PR.
Regarding the case sensitivity problems I wonder if my comments made in #771 might solve this issue.

**Comment by demiankatz** [comment]
I'm going to have to take a little time to digest your comments on #771, so a reply on that will be coming a little later in the day... but first, thanks for your approval of this one!

I think it would probably be helpful to get this PR merged as soon as possible so that we can resolve its conflicts with #771 and then focus on cleaning up the remaining edge cases over there. Having two open PRs with conflicting changes to the same file is probably not a good thing to keep around for too long!

To that end, two key questions:

1.) Is there any chance you might have time to work on the "artificial test record" task noted above so we can run more tests and have greater confidence in the revisions? If you're too busy, I can do it next week, but your input on what cases we should be covering would be appreciated!

2.) The new logic here is actually significantly different from the old logic in terms of which values it selects -- and I think it's a change for the better, but it may leave some problematic uncovered cases. The old logic was basically "if there is a whitelisted value in $e or $4, then index the first value found in either $4 or $e, favoring $4." So you could have something like `$e whitelisted_term $4 utter garbage` and the method would put `utter garbage` in the index because $e was whitelisted but $4 was considered a "better subfield." The new logic looks through both $e and $4 and creates a set of whitelisted terms. This achieves both deduplication and ensures that only expected terms go into the index. In most cases, that seems like a preferable behavior.

However, there is the question of what to do with unrecognized terms. Since it appears that free-text use of $e is very common, do we need to have a setting that says "if the term isn't found on any of these lists, include it here"? So, for example, if we have lists of first author, second author and corporate author terms, would we want second author to also include anything not found on any of the lists? If you think this case is already covered by your ideas on #771, we can move the discussion over there... but if this is a separate edge case that needs to be thought about, we should be sure to add another TODO somewhere so we don't lose track of it.

**Comment by lahmann** [comment]
Demian, I have added eight fake/artificial Marc records to our test set which should cover all edge cases (with one exception but more on this further down the text).
The records are all identical except the id (Marc 001), title (Marc 245 describing the cases being covered by the test record) and of course Marc 100, 110, 700 and 710. All 1x0 and 7x0 fields contain the same data but with changing constellations of the relator terms and codes:
* Fake Record 1 with multiple relators in Marc 100, 110, 700 and 710; only in subfield 4
* Fake Record 2 with multiple relators in Marc 100, 110, 700 and 710; only in subfield e
* Fake Record 3 with multiple relators in Marc 100, 110, 700 and 710; both in subfield e and 4
* Fake Record 4 with multiple German relators in Marc 100, 110, 700 and 710; only in subfield e
* Fake Record 5 with multiple German relators in Marc 100, 110, 700 and 710; both in subfield e and 4
* Fake Record 6 with multiple German, gender neutral relators in Marc 100, 110, 700 and 710; only in subfield e
* Fake Record 7 with multiple German, gender neutral relators in Marc 100, 110, 700 and 710; both in subfield e and 4
* Fake Record 8 with multiple German, gender neutral relators including relators with generic code oth in Marc 100, 110, 700 and 710; both in subfield e and 4

The result should always be the same:

    Primary Author (Author, Interviewee, Designer, Buchkünstler*)
    Primary Corporate (Organizer, Sponsoring Body, Host Institution)
    Secondary Author (Editorial Director, Producer, Researcher, Letterer*)
    Secondary Corporate (Degree Granting Institution, Honouree, Issuing Body)
    
    * applies only to "Fake Record 8"

But when actually indexing the test records Solr contains
* for Fake Record 1,3,5,7,8:

```json
       "author2_role": [
          "edt",
          "pro",
          "res"
        ],
        "author": [
          "Author, Primary 1795 - 1881"
        ],
        "author2": [
          "Author, Secondary 1875 - 1950",
          "Author, Secondary 1875 - 1950",
          "Author, Secondary 1875 - 1950"
        ],
        "author_role": [
          "aut"
        ]
```
* Fake Records 2,4,6 have empty author fields

Obviously the code now handles multiple relators well but needs to extended to also handle relator terms in $e without corresponding relator code in $4. But I think this issue will be addressed in #771.

What is not covered by these records is the theoretical possibility of one or more existing relator term(s) in $e with one or more existing relator code(s) in $4 which do not correlate - i.e. no term-code pairs. Marc does not restrict the cataloger from such constellations but such cases would pretty much question the implicit relation among all subfields in the respective main field and make things very complicated. After talking to a colleague who's more proficient in Marc and cataloging we decided that such cases should rather be logged as cataloging errors than getting covered by extra code.

Any thoughts?

**Comment by demiankatz** [comment]
@lahmann, unless I'm missing/misunderstanding something, the current code makes no assumptions about correlation between $e and $4 -- it just takes the union of the two and deduplicates them. It might be worthwhile to add an example that contains half the relators in $e and half in $4 just to cover more bases, but I suspect that this will behave in a fairly reasonable fashion. Would you be willing/able to add this one additional test case?

Obviously, as you say, none of this is going to work completely right without the further work in #771.

I'm hoping that we can soon merge #761, which will make working on indexing code much easier, since we will no longer have to schedule SolrMarc releases in order to modify VuFind-specific indexing Java. Once that happens, we can easily merge this part of the update to master and then proceed with the work in #771. However, since that may be a few days, if you're ready to proceed on #771 right now, maybe I can work on rebasing #771 so that it has all of the work from here as a first commit and all of its own work as a second commit. If that would be helpful to you, let me know and I'll make it a high priority -- since I would like to get all of this sorted out as soon as we can!

Speaking of #771, I think the other big piece we need to sort out is dealing with case-sensitivity, which has been addressed to some extent in the comments over there... but I seem to remember running into some German edge cases where the case of the relator could make a difference in meaning, and if that's really something we have to worry about, we should have a test case to cover that situation as well!

Anyway, thanks again for working on this, and let me know how you'd like to proceed!

**Comment by lahmann** [comment]
Demian, after indexing the added testcase with non correlating relators in $e and $4 I agree that the current logic does not make any assumption about correlation between $e and $4 - that's good and should cover all possible cases. I updated my previous comment with the added test record and indexing results.

Regarding your suggestions on how to proceed I think it's a good idea to continue in #771 independently of #761 to hopefully get these pull requests into master for release 3.1.

Regarding the case sensitivity issue I honestly don't see any problem right now - unless I'm misreading the code. As long as we normalize the relator terms and codes from the Marc record and the RelatorSynonym list in #771 we should be good. The whitelist is applied afterwards and should contain only normalized relator terms or codes. The indexed codes will get translated in the frontend according to the translation files.
If the relator term/code in a Marc record can be mapped with the RelatorSynonym list _and_ is found on the whitelist _and_ has a translation, we _should safely_ assume that the translation is the appropriate form for display.
The remaining cases are the relator terms/codes without a mapping in the RelatorSynonym list and no match on the whitelist. As briefly pointed out in my comments in #771 for those unknown relator terms/codes we should assume these worth indexing in dependency of the Marc mainfield - i.e. index unknown relator terms/codes in 100 as primary in `author_role`, 700 as secondary in `author2_role` etc.
In some cases this might add some redundant relator information but at least no relator information will get lost. This should also address the German cataloging specific use of `oth` so that `oth` could be omitted from the whitelist and the German specific relator terms (without appropriate mapping to Marc relator codes) being indexed as they are.

**Comment by demiankatz** [comment]
Glad to hear the new test case confirms that things are working the way we want them to.

Regarding how to proceed, there's some good progress on #761, and I'll make that my first priority to move forward... but if I reach a stopping point on that one and need something else to do, I'll switch gears to #771 in order to keep that moving along. If #761 gets fully resolved before I find time for that, that will be great and will save us some time. We'll see how it goes!

Regarding case sensitivity, the extreme edge case that I am concerned about is Beiträger vs. beiträger, which in previous conversations were said to have a semantic difference. If that is really the case, I don't see how we can properly and reliably differentiate them without adding a lot of complexity to the code. If we really want to support this level of specificity, we should add another test case containing an author with both versions of the term, so we can confirm that both versions end up in the index (I'm sure that with current code, they will not). On the other hand, maybe we need to decide that we can't and shouldn't make this fine distinction, and pick one or the other version of this translation. If it's really an important difference in real-life usage, we can try to support it, but it seems to me like a very fine and fragile distinction, and if we can eliminate the need for it, I think it will make our lives a bit easier.

Regarding unknown relator terms, do we have any tests of those in primary/secondary fields for testing purposes?

**Comment by lahmann** [comment]
Demian, regarding the case sensitivity I recalled the discussion we had in #354 but I'm having a tough time to grasp our approach in its entirety - maybe a small recap will help:
1.) we have a whitelist defining which relator code _or_ term will be assigned to primary, secondary or corporate index fields
2.) the Marc subfields $e and $4 are of the same rank - i.e. both will be matched to with the whitelist and their content indexed accordingly
3.) whitelist matching will be done with normalized terms/codes, but the subfield contents will get indexed _unnormalized_
4.) as a result of 2. we have to dedup the roles in VuFind as the index will most likely contain pairs of codes and terms
5.) deduping in VuFind most likely has to happen with the translated relator codes/terms - otherwise we have to know somehow that `aut == Author`
6.) unknown terms/codes are currently skipped but *should* get indexed based on the mainfield (e.g. Marc 100 => primary, Marc 700 => secondary)

If this recap is correct we should not have any problems so far with case sensitivity as this will get covered by translation in VuFind after the terms/codes were being indexed case sensitive (3).

Unknown terms/codes (6) needs to be addressed, although I think it might be easier to do so in #771. I have added a fake record 10 including unknown relators (e.g.`$eUnknownRelator1$4xx1`) for each relevant Marc field though and updated the other records as the mapping of German RDA relator terms to relator codes have changed in the past few weeks (see 32c8bb2).

**Comment by demiankatz** [comment]
Merged to master since this improves the situation, even though there are some outstanding questions/concerns -- remaining issues will be addressed on #771.

**Comment by demiankatz** [comment]
To address @lahmann's previous comment:

Note that 3 in the list is not currently accurate: all relators are being indexed in NORMALIZED form, not raw. This almost certainly needs to change -- but the question is whether raw indexing is desired, or some sort of mapping from the raw version to a value from the whitelist.

Also regarding number 6, I've added a checkbox to the TODO list on #771 so we can continue discussing this over there. I wonder if we need to add a parameter to the indexing routines to control how unknown codes/terms are handled. For example, I could imagine a scenario where we might want to index values just from $e or $4 but not both.

**Pull request merged**
