### PR TITLE
Sort and deduplicate facet values on EDS advanced search

### PR DESCRIPTION
**Pull request by meganschanz**
This adds logic to sort the facet values in the EDS advanced search in a method consistent with how it is done in the other advanced search templates (such as solr and summon).

### CODE REVIEW

**Review by demiankatz — COMMENTED** [review]
Thanks, @meganschanz, this looks reasonable to me and seems to work correctly. However, before I merge it, I did have a couple of observations, which I think might really be questions for EBSCO more than anything else:

1.) The language facet order doesn't really make much sense unsorted, but it does seem like more commonly-used values are closer to the top. I'm not sure if there might be a situation where somebody might want to keep that order. I don't have a huge appetite for designing a config setting for this, but I wanted to at least raise the question. (Maybe the solution is switch to sorted by default, and if anybody complains, introduce a setting later).

2.) I'm seeing some duplicate values in the list -- for example, English appears twice in my instance. Are you seeing this too? I don't have time to dive in right now, but I wonder if perhaps this is an issue with extraneous whitespace somewhere, or something like that.

**Comment by meganschanz** [comment]
1) I could reach out to EBSCO to ask what the default sort order is. But even if it does sort them by frequently used (our first result from the API is "Afrikaans", so I'm surprised if that is the most used language in EBSCO content), from a usability perspective if someone is looking for a language to select, the frequency sorting is ineffective since you'd possibly need to search the whole list to find what you wanted instead of having them alphabetized. I think the frequency sort is more suited for the search result page facets where it shows the count by the item to explain the sort order. I don't mind adding a config if we want to allow for disabling the sort if we think that would be better. I originally didn't consider it because the other advanced search page templates didn't have a config to disable the sorting either.

2) I'm not seeing duplicates in [our instance](https://catalog.lib.msu.edu/EDS/Advanced). I queried EDS directly (https://eds-api.ebscohost.com/edsapi/rest/info) to see if the API response had duplicates for English and I didn't see any their either. But it did have multiple languages that contained "English":
```
...
<LimiterValue>
    <Value>English</Value>
    <AddAction>addlimiter(LA99:English)</AddAction>
</LimiterValue>
...
<LimiterValue>
    <Value>English, Old (ca.450-1100)</Value>
    <AddAction>addlimiter(LA99:English\, Old \(ca.450-1100\))</AddAction>
</LimiterValue>
...
<LimiterValue>
    <Value>English, Middle (1100-1500)</Value>
    <AddAction>addlimiter(LA99:English\, Middle \(1100-1500\))</AddAction>
</LimiterValue>
...
<LimiterValue>
    <Value>Pidgin english</Value>
    <AddAction>addlimiter(LA99:Pidgin english)</AddAction>
</LimiterValue>
...
<LimiterValue>
    <Value>Creoles and pidgins, English based</Value>
    <AddAction>addlimiter(LA99:Creoles and pidgins\, English based)</AddAction>
</LimiterValue>
```

**Comment by demiankatz** [comment]
@meganschanz, I agree that the sort is not especially meaningful. But the thing that troubles me is that a lot of the values in Villanova's list don't actually yield any results at all if I apply them as filters. Not sure why they're in the list if nothing matches, but it's probably a combination of default settings/filters that leads to bad results. I feel like sorting the list may promote bad values to a more prominent position... but I don't think there's really any avoiding that. As you say, the list is hard to use as it is, and it's probably better in order, even with these problems.

I also tried dumping out the raw API response in VuFind, and I really am seeing the exact same value come through twice:

```
line 148:
                    {
                        "Value": "English",
                        "AddAction": "addlimiter(LA99:English)"
                    },
...
line 1288:
                    {
                        "Value": "English",
                        "AddAction": "addlimiter(LA99:English)"
                    },

```

I don't even see subtle differences of whitespace, etc. It's just a plain duplicate coming directly from the EDS API. I don't think there's much VuFind can do about that... but should we perhaps add deduplication logic somewhere? Could be something as simple as:

```
              $this->sorter()->natsort($sorted);
              $lastDisplay = $lastValue = '';
              ?>
              <?php foreach ($sorted as $i => $display): ?>
                <?php
                  $facetValue = $facet['LimiterValues'][$i];
                  // Filter out duplicate values:
                  if ($lastDisplay === $display && $lastValue === $facetValue) {
                    continue;
                  }
                  $lastDisplay = $display;
                  $lastValue = $facetValue;
                ?>
```

If you think that's worth adding, I can test if it actually works in our situation.

**Comment by meganschanz** [comment]
Removing duplicates sounds like a good idea - I just pushed a commit for that. I also create a ticket with EBSCO to see if they could explain the sort order.

**Comment by meganschanz** [comment]
I heard back from EBSCO and they informed me that the order is based on a relevancy formula and referred me to [this documentation](https://connect.ebsco.com/s/article/How-is-relevance-ranking-determined-in-EBSCO-Discovery-Service-EDS?language=en_US). They also confirmed that the facet list values would likely be different between institutions and depends upon the databases/partner databases enabled for that specific EDS account.

Knowing this, I wouldn't think the relevancy for a language on a non-search query, like on the advanced search page, to be helpful to a user as opposed to sorting alphabetically like the other advanced search templates do. But I'm open to making it configurable if we want to let everyone choose for themselves.

**Review by demiankatz — APPROVED** [review]
Thanks for the investigation on this, @meganschanz! I agree that alphabetizing makes more sense than some arbitrary and meaningless relevance ranking. We can revisit the subject if anyone complains, but I don't expect that they will.

**Pull request merged**
