### PR TITLE
Improve display of electronic items from Alma.

### PR DESCRIPTION
**Pull request by EreMaijala**
Use more fields for the location and make it possible to display status also when the 'item' is available. Also use 'Get full text' as default if there's no collection name in subfield m.

### CODE REVIEW

**Comment by EreMaijala** [comment]
If the change to status-full.phtml is too dangerous, I'm ok with leaving it out for now.

**Review by betullam — APPROVED** [review]
@EreMaijala and @demiankatz - We have no electronic records in our Alma production system but I set some up in our sandbox environment. Your code works as expected.

**Comment by demiankatz** [comment]
@EreMaijala, I think I'd be more comfortable addressing that status-full.phtml change separately; I think it would take an analysis of all the ILS drivers to figure out what the consequences of that might be... and I suspect we might need to make it configurable to be completely safe. I'm open to discussing it, but it's definitely not a change we should sneak in along with changes to one specific driver.

**Comment by EreMaijala** [comment]
Ok, I reverted the changes in status-full.phtml.

**Comment by demiankatz** [comment]
Thanks!

**Pull request merged**
