### PR TITLE
Reset focus to bookbag toggle buttons after action.

### PR DESCRIPTION
**Pull request by charbugs**
Hi VuFinders,

this PR is an small accessibility improvement. It makes the keyboard focus stay on the bookbag toggle button when hitting the enter key.

To test this feature you need to set `showBookBag = true` in config.ini.

### CODE REVIEW

**Review by demiankatz — APPROVED** [review]
This makes sense to me, but I'm also going to make sure @crhallberg agrees before merging.

**Comment by demiankatz** [comment]
(For the record: I just ran the full Mink test suite, and all tests are passing).

**Comment by demiankatz** [comment]
I also did some hands-on testing and see how this is clearly a functional improvement... but I'll wait and make sure @crhallberg has no technical suggestions.

**Review by crhallberg — APPROVED** [review]
Looks good to me!

**Pull request merged**
