### PR TITLE
extending config for covers

### PR DESCRIPTION
**Pull request by jochen-lienhard**
The goal is to implement a helper class, that allows to show/hide the covers in core and result.
It should be also possible to define the size of the covers.
Perhaps this feature can be used in the carousel too.

### CODE REVIEW

**Comment by jochen-lienhard** [comment]
This is the first idea, how to extend the config. 
Demain: Where should the helper class be placed? module/VuFind/src/VuFind/View/Helper or module/VuFindTheme/src/VuFindTheme/View/Helper.
Chris: How can we use this in the carousel?

**Comment by demiankatz** [comment]
I think you can probably simplify the configuration to a single value so it's either a size (to display that size) or false (to disable thumbnails). For optimal flexibility, you could also allow "true" which would just pick a default size appropriate for the context. I think the setting names should reflect that they are related to the coverimages setting in their naming... like coverimagesRecordDisplay and coverimagesResultDisplay, perhaps. Another thing to think about: are there any situations in which we should default the display to false? My first thought was that if coverimages is false, we need to hide the images, but that's not really true: at very least, we need to account for both the standard coverimages setting and the generated cover images setting, and it's further complicated by the Summon feature that displays images based on format.

As far as where the view helper should live, I think it would make more sense to put it in the core VuFind module -- the VuFindTheme folder is just for components specifically related to VuFind's theme-switching features, but this is a more general thing.

I'll let Chris comment on the carousel part of things.

Thanks for getting the ball rolling on this!

**Comment by crhallberg** [comment]
It may be too much to assume, but if someone wants to disable cover images, they wouldn't be interested in the carousel feature.

**Comment by jochen-lienhard** [comment]
Ok, I will try to build a helper.
Hmmm ... I'm not sure about the carousel. I think it is a nice feature, special for mobile devices even without covers.

**Comment by jochen-lienhard** [comment]
I'm not sure, what the helper class shall do. 
Shall it only have some get methods to give the result from the config?
Shall it has an CoverController? Shall it has a method that returns the numbers of rows, that are necessary for the width of the bootstrap cols?

**Comment by demiankatz** [comment]
One possible approach might be, instead of creating a separate cover helper, to add a method to the existing record helper:

https://github.com/vufind-org/vufind/blob/master/module/VuFind/src/VuFind/View/Helper/Root/Record.php

This could be structured similarly to something like getCheckbox() to read some information out of the record driver and then render a template using that information (something like, say, record/cover.phtml).

We need to figure out a way to do this in a platform-independent fashion, since the helper will be shared by all of the themes -- blueprint, bootstrap3 and jquerymobile. Adding specific methods for things like bootstrap columns is undesirable since this should be as general-purpose and reusable as possible. Probably the best solution is to have it return either an HTML string (if a cover is rendered) or false if not. That way, you can adjust other column widths in the row based on whether or not a cover was displayed, and all of the width-related behavior is found only in the template code, not in the helper itself.

**Comment by jochen-lienhard** [comment]
This seems to be a good approach. A own phtml-file will make it easier to modify the link (some provider want that the link of the cover go to their page) or add some hint (like it is necessary for google-books). I will add a method and than we can discuss about it.

**Comment by jochen-lienhard** [comment]
What kind of parameters do we need for the getCover method?
$size medium|large
$link for full result or provider 
$location which template calls the renderer (list, grid, result)

Do you think, we need more parameters?

**Comment by demiankatz** [comment]
At the minimum, you need a linkSize and a displaySize (linkSize = size to link to, displaySize = size to show. linkSize could be false to skip the link). As to whether other parameters are needed, the first step is probably to search all the existing templates for calls to getThumbnail and see how that is used in different contexts. By comparing that code, you can probably determine whether you need a cased-out template to do things significantly differently in different contexts, or if you can instead generalize to something simpler. (I'm hoping you can generalize, as that will obviously result in neater code).

**Comment by jochen-lienhard** [comment]
I don't understand, why I need two sizes.
Do you not think it would be a good solution to implement cover.phtml for each theme?
Perhaps some getThumbnail calls (with the code around) can be put in there and you only
need to put the needed variables in the helper class.

**Comment by demiankatz** [comment]
You need two sizes in some cases because we display a small size with a link around it pointing to a larger size... e.g. `<a href="large_image"></a>`

I think it does make sense to implement a separate cover.phtml for each theme -- it is likely that we'll want to apply different CSS classes, etc., depending on each context.

**Comment by jochen-lienhard** [comment]
OK, that looks good for me.
I think the helper function (getCover) only needs the size of the thumbnail, and default will be small. I'm not sure about the link of the cover. In the result-list or grid-list, the link is the full record. 
In the full record it can be the large image, or it can be that the link must connect to the provider for a 'fast-buy'. So we can perhaps use a fixed code for the link like (none, large, record, external) or the link must put explicit in the call. I don't know, how to do this when using the link of the provider from the config. What do you think about?
In the following files it will be easy to replace the getThumbnail call:
RandomRecommend.phtml (use small or medium)
list-entry.phtml (no size defined)
result-grid.phtml (large or no size defined)
result-list.phtml (no size defined)
collection-info.phtml (like in core.phtml)

Do these files use the SolrDefault too? So that we can use the cover.phtml in SolrDefault?
storageretrievalrequests.phtml (no size defined)
checkedout.phtml (no size defined)
holds.phtml (no size defined)
illrequests.phtml (no size defined)

I don't know what to do in the following cases:
similaritemcarousel.phtml (just call thumbnail large, so I think we do not touch it)
core.phtml and result-list.phtml of EDS (if no thumbnail available, use mediaicon.

**Comment by demiankatz** [comment]
Good point about non-image links being used on covers in some contexts. I think given that, the most flexible option is to simply pass a full URL (or false) to the getCover method to specify the link or the lack of a link.

Regarding which templates use SolrDefault, at the moment, all of VuFind's built-in record drivers inherit from SolrDefault (even if they don't use Solr) in order to allow sharing of templates. At some point in the future (VuFind 3?), I may add a generic "BibliographicRecord" driver as the shared base to make this more semantically appropriate, but for the moment, I'm leaving it alone to avoid breaking backward compatibility.

I think you're right that we can just leave similaritemcarousel.phtml alone -- the purpose of getCover is to deliver a fully formatted cover image, and the carousel does things differently.

For the EDS special cases, can you just add a custom cover.phtml to the EDS driver that overrides the SolrDefault version and adds the mediaicon functionality?

**Comment by jochen-lienhard** [comment]
I think, I will keep the EDS parts as is. EDS only has covers for ebooks at the moment, so in the most cases the mediaicon is used.

**Comment by jochen-lienhard** [comment]
I'm not sure about the size definition of the covers. It is not consistent if we use a config defined version for list/grid and full result and not for the other use cases. My opinion is, to use only a cover true/false in the config and use the parameter for the size in the themes in the getCover call.

Do we need the 3 different sizes in the cover.phtml or would it fits, if we only use the size that is used by the call?

**Comment by demiankatz** [comment]
What if we used two parameters to deal with size: context and defaultSize? Context would look up a size in the configuration, and if no configuration is found, it would use defaultSize? Then we could label every distinct usage of a cover with a different context (and users could define their own) to allow maximum configurability, but the configuration would be totally optional and simple to deal with.

**Comment by EreMaijala** [comment]
While you're at it, consider a somewhat different approach: we found that having two or three predefined sizes didn't work well for all use cases (e.g. image records from a museum could use a larger image than books) and didn't allow easy customization of their display, so we ended up with passing the desired width and height as params to the cover/other image loader. This also allows the loader to do something useful when the image dimensions don't fit the requested size like padding or cropping the image.

**Comment by jochen-lienhard** [comment]
So do you think we have following implementation:
in config.ini: 
context={small|medium|large|false}
in Record.php in get Cover: 
public function getCover($size, $link = false)
if (!$size) than (check if $context is set else use $defaultSize)

I'm not sure, where the $defaultSize may be defined.

@Ere: Do I understand right, that you wish that the $size in getCover may be:
{small,medium,large,(24x50)}

**Comment by demiankatz** [comment]
I had envisioned something like this...

In config.ini:

<pre>
coversize[result-list] = small
coversize[core] = medium
</pre>

In a template:

`<?=$this->coverHelper()->show('core', 'medium')?>`

And then in the cover helper's show method:

<pre>
function show($context, $default)
{
    $size = isset($this->config[$context]) ? $this->config[$context] : $default;
   // ...
}
</pre>

Obviously none of these example method or configuration names are set in stone -- I'm just trying to demonstrate the functionality I intended.

I think Ere's suggestion about specifying dimensions is an interesting one. The convention of {maxwidth}x{maxheight} seems like a solid one for passing dimensions around in place of the more arbitrary small/medium/large sizes. However, if we did add support for specific sizes, we'd also need to add logic for all of the cover retrieval code to figure out how to map specific sizes to an appropriate API parameter. Perhaps that should be the subject of a separate pull request -- I think if we implement this on the assumption that small/medium/large might eventually be replaced by or augmented with a dimensional string, we can keep the two issues separated.

**Comment by jochen-lienhard** [comment]
Do you think we can implement it this way to hide covers? If no cover, qr or preview is available than use more space for the main content.

**Comment by demiankatz** [comment]
This looks like a reasonable start to me. Where do we stand with regard to the issue of associating a link with the cover image? Do we just need to add an optional parameter to getCover() that accepts the href of an <a> tag that surrounds the cover image? I think that is preferable to the current situation where it is hard-coded to a large thumbnail within the cover template.

**Comment by jochen-lienhard** [comment]
That is my plan. I want to check in the cover.phtml if this->link is set and create a link to that target, for example: large cover or full result or provider of the covers to bye that book.

**Comment by jochen-lienhard** [comment]
I added the link in the result-list and in the core of bootstrap3. If you agree, I will continue with the other files.

Another question: How can I solve the travic error?

**Comment by demiankatz** [comment]
If I'm reading this correctly, in core, you've hard-coded the link to a string instead of the expected `$this->record($this->driver)->getThumbnail('large')`, but other than that, this looks like a good approach.

Regarding the Travis error, right now there seems to be a problem on their end. I will investigate and see if I can do anything about it, but we may simply have to wait for the service to fix itself.

**Comment by jochen-lienhard** [comment]
I'm not sure about the names for the configuration. In the most cases I'm using the name of the phtml file. This makes it very flexible. If you like this version, I will modify the blueprint and mobile theme too.

**Comment by demiankatz** [comment]
A quick look at RandomRecommend suggests that this refactoring has some logic missing. In that instance, we check for a small thumb, revert to a medium if the small is unavailable, and then display the "unavailable" graphic if neither of those exists. Perhaps we need to extend this to allow a list of options to try... for example, you could represent this as "small:medium:unavailable" -- then the cover template could loop through these options and try each one in turn ("unavailable" could be a special case to display the unavailable graphic -- an option that will sometimes still be desirable in contexts where a consistent layout is desired).

Also, a minor style nitpick: please try to include spaces after commas for readability.

I like the convention of matching the image context to the template name. I think that should be good enough for now.

Also note that Ere fixed the Travis build problems, so the next time you merge with master, you should get a better result.

**Comment by jochen-lienhard** [comment]
I don't like to put to many logical syntax in the template, so I add some code to the helper, that checks is more than one size is defined and test, which one exist and takes the last one, that exist. 

Oh ... I usually make spaces after commas, it was a copy & paste mistake. Fixed.

I have a little bit a problem modifying the blueprint theme. There are a lot of different classes for the thumbnails: summcover, recordcover, gridImage so it is difficult to put these all together.

I would prefer if we don't touch the EDS getThumbnail part and keep it as is.

**Comment by demiankatz** [comment]
Thanks for the progress! I'll be traveling for the next couple of days but will give this a closer look when I return.

**Comment by demiankatz** [comment]
Okay, I'm back, and have found some time to take another look here.

1.) I'm fine with doing most of the work in the helper rather than the template; however, I still think we need to somehow address the 'cover-unavailable' case.

2.) If the EDS code totally fails to follow the same pattern as everything else, I'm okay with leaving it alone.

3.) For the blueprint theme, what if you pass the context from the helper through to the cover template? Then in the cover template, you could use a switch to map the context to an appropriate class. I realize that this is not at all ideal, but it might be a worthwhile compromise to move forward with the work in light of the fact that the blueprint theme is deprecated and will eventually be eliminated anyway. Alternatively, it may also be worth investigating how the different blueprint cover classes are used and whether they actually serve any meaningful purpose. If we can standardize to a single class without changing anything, then that's obviously a desirable possibility.

**Comment by jochen-lienhard** [comment]
1) I don't understand, why we need a 'cover-unavaiilable' case. If no fitting cover is available, it is the fall back in the cover.phtml or do I understand something wrong?

3) I will look, if I find the different between the classes for the covers in blueprint. I think the best way would be to put it all together. We will see.

**Comment by demiankatz** [comment]
1) I think I may have been accidentally looking at the jquerymobile version of cover.phtml when I wrote that previous comment. I see that this is now covered. New question: is there any reason to pass the $size value through to the template now that we're looking up thumbnail URLs inside the helper? Would it be better to pass the thumbnail URL directly to avoid redundant lookups?

3) Let me know if Chris or I can be of any assistance here!

**Comment by jochen-lienhard** [comment]
3) There are 3 different classes: summcover, recordcover and gridImage. Can you please look at blueprint/css/styles.css. I'm not sure, if we can merge this classes.

1) good idea, than we have all logic in the helper.

**Comment by demiankatz** [comment]
3) I haven't looked into this yet myself (though hopefully @crhallberg can in the near future), but it occurs to me that even if there are important differences between the classes, perhaps we can adjust the HTML and CSS so that the differences are applied based on a container element -- e.g. rather than putting a .gridImage class for grid images, make sure the image is inside a .grid div, and then set up the css to be .grid .image. (Obviously those class names are hypothetical -- but hopefully you see what I'm getting at).

**Comment by crhallberg** [comment]
I'll look into the different classes tomorrow. As far as I remember off-hand, the bootstrap theme made this more consistent by using .recordcover instead of multiple classes.

**Comment by crhallberg** [comment]
Blueprint:
 - .summcover - Search result thumbnails
 - .recordcover - Record view
 - .gridImage - Grid search results

Bootstrap:
 - .recordcover - Record view, search results
 - Grid search results missing class

Bootstrap can easily have the same class on all the views, but I'm concerned about breaking custom themes by making it standard in blueprint.

**Comment by demiankatz** [comment]
In that case, perhaps the best solution for blueprint is what I proposed earlier: pass the context to the template, and use a switch in the template to map the context to an appropriate class. This is obviously not ideal -- it is better to minimize logic inside templates -- but since we're currently viewing blueprint as a legacy, deprecated theme, I don't mind taking this measure to minimize disruption to the installed base, on the assumption that the whole theme will go away in a release or two, so this non-optimal workaround won't create a long-term maintenance burden.

**Comment by crhallberg** [comment]
Shall I put the recordcover class on the thumbnails in the grid view?

**Comment by demiankatz** [comment]
I'll leave that to your judgment. I seem to recall that grid view had some special resizing of images in blueprint to make the grid uniform and attractive. If the recordcover class interferes with that, perhaps it's omitted for a reason... but you can try it out and see what happens!

**Comment by jochen-lienhard** [comment]
Is it a problem that the grid now has the recordcover class in bootstrap?

OK, depending on the context I will set the classes for blueprint.

**Comment by demiankatz** [comment]
I don't think adding .recordcover in bootstrap3 is going to hurt anything (it appears to simply impose a max-height), but Chris might know more about this than I do.

It does seem that, independent of this PR, the bootstrap3 grid view could use some work. The blueprint grid is very uniform, but the bootstrap3 grid is quite irregular as it appears to be less explicitly controlling image height.

**Comment by jochen-lienhard** [comment]
I added the changes for blueprint. I'm not sure, if we must make changes in the jquerymobile theme.

**Comment by demiankatz** [comment]
A couple of small comments:

1.) When you have code like `$newcontext = ['size' => $size, 'link' => $link, 'context' => $context];` this is an ideal time to use the compact() function -- `compact('size', 'link', 'context');` is functionally equivalent but a bit easier to type!

2.) We don't normally capitalize template variables. Would you mind changing $Cover to $cover? If this would be a lot of work for you, let me know -- I think I could do it pretty quickly by generating a patch, running a search-and-replace, and then reapplying a patch, and I'm willing to do that if it's inconvenient for you.

Regarding jquerymobile, the use cases there are much more limited. If the existing work there still functions, we probably don't need to extend it further.

I'd like to do a more detailed review of all this before merging it, but I think we're getting close. Please remind me about this when you return from your vacation if I haven't posted more in the meantime!

**Comment by jochen-lienhard** [comment]
1) fixed
2) That would be nice, if you can create a patch.

**Comment by demiankatz** [comment]
Looks like your compact change introduced an extra semi-colon that is causing some tests to fail. I'd fix it myself but I don't seem to have write access to this branch. Would it be possible to give me access so I can push up the $Cover changes directly? If not, let me know and I can create a PR against your PR to introduce the change. Thanks!

**Comment by jochen-lienhard** [comment]
very strange, usually you have push access to my repository.

**Comment by demiankatz** [comment]
Seems like the problem fixed itself overnight. Weird.

**Comment by demiankatz** [comment]
Okay, $Cover changed to $cover. I'll try to do a more thorough review/test later this week.

**Comment by demiankatz** [comment]
Sorry, things got busy and I didn't manage to review this as quickly as I had hoped. I've just merged in the latest master and will try again to review more thoroughly soon.

**Comment by jochen-lienhard** [comment]
No problem, at the moment I have a lot of other projects too. Tell me, if I shall make anything.

**Comment by demiankatz** [comment]
Jochen,

I think we're just about done. I found and fixed some issues, and also ended up changing the way parameters are passed to cover.phtml to eliminate some redundant work (we can figure out the thumbnail in the helper, so we don't need to pass the size down). I also added a mechanism for globally disabling thumbnails.

Do you mind taking one last look at this to make sure you're happy with it? After that, I'm hoping Chris can do a final review for template style, and then I think we're ready to merge!

Thanks again for working on this!

**Comment by jochen-lienhard** [comment]
It looks great, good idea with the global configuration. I have no further comments for this PR.

**Comment by jochen-lienhard** [comment]
I detected, that the global configuration does not deactivate the covers in core. Is this a bug or a feature?

**Comment by demiankatz** [comment]
Which theme are you using? Exactly what does your configuration look like? Which URL are you accessing? On my test server, the global configuration does appear to disable covers in core, so either I'm misunderstanding which page you refer to, or else there's some inconsistency between our systems.

Thanks for testing!

**Comment by jochen-lienhard** [comment]
Now it works, very strange, perhaps it was a cache problem.

**Comment by demiankatz** [comment]
Thanks for confirming that it seems to be okay now. I think we're very close to being ready to merge -- I'm just waiting for feedback from @crhallberg, who has been out of the office for a few days.

**Comment by crhallberg** [comment]
Sorry for the delay! I am back to work. It's been a while, Demian is now out of the office, and I am having a hard time remembering what feedback was required for this. Can you remind me?

**Comment by jochen-lienhard** [comment]
I think, that Demian asked you to make a final review for the template style.

**Comment by demiankatz** [comment]
That's right -- I think it should be fine, but if you had any feelings about placement of classes or general formatting, feel free to do some final cleanup.

**Comment by crhallberg** [comment]
I looked through the templates and that was the only fix I'd recommend.

**Comment by demiankatz** [comment]
Thanks for all the work, everyone! I've manually merged this to master.

**Pull request closed without merging**
