### PR TITLE
Tweak and reorganize styles for improved compatibility with Bootstrap 5.

### PR DESCRIPTION
**Pull request by EreMaijala**
- Imports Bootstrap 3 vendor accessibility files from the main style file instead of components/accessibility.
- Adds missing blank lines at EOL.
- Uses flex for vertical positioning of searchbox controls to avoid pixel-based positioning.
- Moves variables not used in components from components/variables to variables.
- Other minor fixes.

### CODE REVIEW

**Comment by EreMaijala** [comment]
These changes were identified while I was working on automated tool for checking if themes are in sync for #3222.

**Review by demiankatz — CHANGES_REQUESTED** [review]
This all looks pretty good to me. Just one question: when the reset button and virtual keyboard button are both active, should we have some margin between them? While this branch fixes the vertical alignment problems with the keyboard button and generally looks better, I think the loss of the small gap between the buttons is a step in the wrong direction.

dev branch: 
image

this branch: 
image

**Comment by EreMaijala** [comment]
@demiankatz Yes, gap added, and I also tweaked the right padding of the input field to avoid overlap.

**Review by demiankatz — APPROVED** [review]
Thanks, @EreMaijala, looks good to me now!

**Pull request merged**
