### PR TITLE
Phone Number Validation

### PR DESCRIPTION
**Pull request by crhallberg**
Using Google's libphonenumber library to check for number validity. Compiled with Closure before use.

https://github.com/googlei18n/libphonenumber

### CODE REVIEW

**Comment by demiankatz** [comment]
Looks pretty straightforward. A few questions:

1.) Why load the library in record/view.phtml? You could keep the whole thing contained to record/sms.phtml, couldn't you? Then you don't load it in contexts where you don't need it.

2.) Is this easily adaptable to the other themes for consistency?

3.) Is there a master list of legal region codes so we can update the documentation? If we implement this, we can go beyond just supporting US.

Thanks for putting this together!

**Comment by crhallberg** [comment]
1.) This is so it works in the Lightbox, which does not load external
scripts.
2.) Very easily, just testing thoroughly in BS3 before porting (as is the
modern style).
3.) There is, it uses standardized country codes:
http://www.iso.org/iso/country_names_and_code_elements

- Chris

**Comment by demiankatz** [comment]
Thanks for the update, Chris. Do you want to add a link to the country code list (and adjust comments as needed) in sms.ini? If you can do that and add cross-theme support, I think this is ready to be merged.

**Comment by crhallberg** [comment]
Done.

**Comment by demiankatz** [comment]
Chris,

I just rewrote your branch to adjust some wording in the .ini file and to eliminate some unnecessary file changes (some of the juggling left some files in the PR that were unchanged except for whitespace). You might want to kill and re-check-out your own local branch for this PR.

In any case, I just tested this out and discovered that the Google library seems to be generating a variety of detailed error messages. The problem is that these are all in English. Does the library support i18n so that we can display appropriate messages to users regardless of current language setting?

Thanks!

**Comment by crhallberg** [comment]
The error codes seem to be hard-coded into the Javascript. We could make language strings, but we'd have to import them all into the JS language array. Found the following:

Invalid country calling code
Invalid region code: 
Phone number too short after IDD
The string supplied did not seem to be a phone number
The string supplied is too long to be a phone number
The string supplied is too short to be a phone number

**Comment by demiankatz** [comment]
That's too bad. I seem to recall you mentioning that the JS had to be compiled. Is there something in the source for that which defines the active language, or is it always English? I thought Google was usually good about making things multi-lingual....

**Comment by crhallberg** [comment]
Now that it's on GitHub, this may change soon.

**Comment by demiankatz** [comment]
So would the interim solution be to override the i18n.phonenumbers.Error object in the template?

**Comment by crhallberg** [comment]
It either returns a boolean or a string, so we could just translate the strings if they're returned.

**Comment by demiankatz** [comment]
Six of one, half a dozen of another, I suppose. Either way we have to embed all of the translations in the HTML somewhere so the JS has access to them....

**Comment by crhallberg** [comment]
Waiting for official language features to harvest Google's excellent translation strings: https://github.com/googlei18n/libphonenumber/issues/583

**Comment by crhallberg** [comment]
Surprising news: "Sorry, we have no plan to provide translations for these. If you look at the Java version, they are enums. Clients are free to choose the best way they want to phrase them in different languages, including English."

Well, I'll take a look at the Java tomorrow.

**Comment by demiankatz** [comment]
The problem with this argument is that I seem to recall that at least one string here is assembled on the fly, combining a variable with surrounding text. That's not very i18n-friendly!

**Comment by crhallberg** [comment]
So by enums, they mean that it only returns error codes, so it's not vastly different. My apologies to our loyal VuFind translators!

**Comment by demiankatz** [comment]
So the Java version returns codes but the Javascript version returns strings? Or does the JS code return strings AND codes?

**Comment by crhallberg** [comment]
The former: Java returns codes, JS returns strings.

**Comment by demiankatz** [comment]
That's very annoying!

**Comment by crhallberg** [comment]
What else does this need? Or are we waiting for 2.4?

**Comment by demiankatz** [comment]
I thought there were still some outstanding translation problems related to strings contructed from multiple parts that are hard to translate properly... but maybe I'm misremembering or overestimating the importance of this.

**Comment by crhallberg** [comment]
That's right. Probably lost that one on the flight home.

I removed the multi from the multipart translation, for both completion and user load.

**Comment by demiankatz** [comment]
Hmm. Still not in love with having to hack the third-party library to make it work -- this could become an ongoing maintenance headache. Is there a way to implement these changes from the outside? (I realize we're probably stuck... just wishful thinking).

**Comment by crhallberg** [comment]
Let me see if I can match it with regular expressions. If you like I can also move phoneNumberFormHandler() from the bottom of the libphonenumber.js to common.js.

**Comment by demiankatz** [comment]
Thanks, Chris. I'll review this further after the 2.4 release (right now, with the freeze on translation files, we can't merge this until that's done).

**Comment by crhallberg** [comment]
Additional language strings push this one back to v2.5

**Comment by demiankatz** [comment]
Chris, we're getting close on this, but a few issues:

1.) The translation doesn't seem to be working for me. I'm seeing the raw strings from the JS, not the translated versions from the language file.

2.) In bootstrap3, if I enter an invalid phone number, the AJAX spinner keeps spinning even after the error message is displayed.

3.) I get a different message in bootstrap3 vs. blueprint if I submit the form without entering anything. Perhaps just a side effect of slightly different implementations, but I mention it in case it's a clue to an actual problem.

**Comment by demiankatz** [comment]
One potentially important detail: during testing, I had my country code set to "bad" to see what would happen. Not sure if this influenced any of the problems I just mentioned, but if you're unable to reproduce them in a normal context, you can try modifying your sms.ini to match mine.

**Comment by demiankatz** [comment]
Manually merged to master.

**Pull request closed without merging**
