### PR TITLE
Rename offcanvas to vufind-offcanvas to avoid clash with Bootstrap 5.

### PR DESCRIPTION
**Pull request by EreMaijala**
Unfortunately the offcanvas class(es) clash with those of Bootstrap 5 (see #3222). Renaming them seems the safest approach to avoid any future incompatibility issues, although it causes a back-compatibility break.

This also prompted some cleanup of obsolete RTL styles shoehorned into themes/bootstrap3/css/vendor/bootstrap-rtl.min.css. It seems that many of them were not necessary, but the useful ones were incorporated into their appropriate locations in .less and .scss files.

TODO:
- [x] Change log entry

### CODE REVIEW

**Comment by demiankatz** [comment]
@crhallberg, can you please weigh in on this one? I'm especially interested in your thoughts on the rtl refactoring, in case you see anything removed that you think might still be needed for some reason.

If there's anything that @crhallberg or @EreMaijala would like @sturkel89 to test across themes, etc., I'm sure she'd be willing to help!

**Comment by EreMaijala** [comment]
@demiankatz @sturkel89 It wouldn't hurt to double-check that offcanvas still works properly. :)

**Comment by demiankatz** [comment]
Sounds good! @sturkel89, can you take a look at this? When you set offcanvas = true in config.ini, it changes things so that the sidebar slides in from the side when you click the "Refine Results" button on a narrow display. (The default behavior is just an anchor-jump to lower on the page). It would be a good idea to check this in all three themes, and in both English and a right-to-left language like Arabic, to be sure the orientation of everything is appropriate in all the combinations.

**Review by sturkel89 — APPROVED** [review]
I reviewed the test branch vs. dev in all three themes and in English, Arabic, and Hebrew.

As far as I can see, appearance and behavior are the same between test and dev under all conditions. 

I like the sliding-in sidebar in narrow screens! I don’t think I’d seen it before. The little arrow pointing to the direction that the sidebar will come from is a nice touch. However, it’s a little annoying to have to reopen the filters multiple times if you want to set multiple filters. In wide screen, this isn’t an issue. I’m not sure that we would want to change this, though.

I noticed a few oddities in terms of translations and also a formatting thing with the Themes and Language options when in narrow screen in Sandal. However, this is all the same in dev, so it isn’t an issue for this PR. I will consider creating a JIRA ticket; I’ll discuss this with Demian.

Since the test branch is behaving as expected, I think this is ready to merge. If you’d like me to provide any screenshots, please let me know.

**Review by crhallberg — APPROVED** [review]
Thank you for correctly placing my misguidedly placed RTL customization! That is a lot of work and improvement that I appreciate.

**Review by demiankatz — APPROVED** [review]
Thanks, everybody! I suspect those misplaced customizations were misplaced nearly a decade ago, before we had nearly as good of an idea about what were doing as we do today. :-)

**Comment by demiankatz** [comment]
Here's what I added to the changelog:

The .offcanvas CSS class in the bootstrap3 theme has been renamed to .vufind-offcanvas to prevent conflicts with an .offcanvas class introduced in newer versions of Bootstrap. If you rely on or customize this class in custom code, please adjust accordingly.

**Pull request merged**
