### PR TITLE
Query with multiple IDs support for DAIA driver

### PR DESCRIPTION
**Pull request by lahmann**
The DAIA query API supports queries with multiple ids (see http://gbv.github.io/daiaspec/daia.html#query-api). Especially for showing availability in the result list this becomes very useful as one query with multiple IDs is significantly faster than one query for each record in the result list (in our development setup we had a speed increase of more than **factor 5** using multiQuery compared with single requests - measuring the time for completion of the AJAX request for getItemStatuses).
This DAIA driver supports queries with multiple IDs but does not break legacy support/compatibility with older versions of the DAIA driver. I refactored the code in order to make it easier to distinguish between DAIA-helper methods and VuFind ILS-Driver methods. I also extended the documentation/comments and marked sections necessary for legacy support as deprecated.
In order to make further development easier the legacy XML-centered DAIA methods remained functionally untouched and the relevant code from these methods got duplicated into other methods. Therefore dropping legacy support in the future means we only have to remove any code that's marked as deprecated (plus the legacySupport-switches) and we are pretty much done. Plus we do not have to worry about legacy support if we extend the functionality of the DAIA driver.
The DAIA.ini got extended by the multiQuery setting - it is set to false by default and only applies if not in legacy mode.

We tested this driver with VuFind2.3.1 (modified version calling httpservice and logger explicitly) and VuFind2.4 - both work fine. The ID delimiter is hardcoded to "|" according to the DAIA query API (see above).

I have not implemented any tests, the tests from https://github.com/vufind-org/vufind/pull/310 *should* work (I haven't tested though), but if this PR gets accepted I would extend the DAIA test accordingly.

### CODE REVIEW

**Comment by demiankatz** [comment]
Now that #310 has been merged to master, you can easily merge master back into this branch and run tests to make sure nothing is broken.

I'd be interested to hear if @jochen-lienhard has any specific comments on this. I'll be happy to take a closer look at this personally at some point, but it seems best for me to first wait and see what Jochen thinks, since (as an actual DAIA user) he's much more invested in this functionality than I am!

**Comment by lahmann** [comment]
So, I merged the latest master into this PR and ran the test. I had to adjust DAIATest.php a little bit as I realized that the testResult-arrays where faulty: getStatus(id) was calling a id that was not part of the response files daia.json and daia.xml (obviously my mistake while creating these output arrays). As the DAIA driver did not check on the ids this didn't matter, but the multiQuery feature requires to compare the document-id of the response with the queried id. After fixing this the test was ok.
In addition to that I had to add the ilslink-key-value-pair to the testResult array for the json-Response as this was missing in the original getJSONStatus() function of the DAIA driver.

One problem remains: as the DAIA driver does now parse the DAIA response according to its type I have included a check on the http result header ContentType (see https://github.com/finc/vufind/blob/bc27d776b9dbee27670a65779c472dc449977b64/module/VuFind/src/VuFind/ILS/Driver/DAIA.php#L350). This check is far from being bulletproof (cf. todo note) but I think it's necessary just to make sure we get a http response we can handle.
Unfortunately a check on the http-headers will break during testing - has anyone an idea how to solve this problem?

**Comment by demiankatz** [comment]
André,

Thanks for all the work!

Regarding the header problem, the issue is that the current fixtures you provided contain only the body of the HTTP response rather than the full response. Thus, we use this code to load the fixtures:

<pre>
 $response = file_get_contents($file);
$responseObj = new HttpResponse();
$responseObj->setContent($response);
$adapter->setResponse($responseObj);
</pre>

This creates a new response but populates only the body field of the object.

If you can revise the fixtures to include the full HTTP response, including headers (which I think can be fairly easily captured and written to file using CURL -- I can look up the details if you need me to), then you could revise the fixture loading to:

<pre>
 $response = file_get_contents($file);
$responseObj = new HttpResponse($response);
$adapter->setResponse($responseObj);
</pre>

and the headers would be correct within the test environment.

**Comment by lahmann** [comment]
I just tried this with `curl -D - "URL" > fixturefile` but I still get the error - is there any way how to call this single test from command line, so that I can debug it? Until now I'm using `phing phpunitfast`.

**Comment by demiankatz** [comment]
I've just pushed up a change to build.xml which will allow you to specify a single test to run through a property... you can then run:

`phing phpunitfast -Dphpunit_extra_params="path/to/test/script.php"`

A bit verbose, but Phing doesn't seem to support a simpler command line parameter interface.

If you're still having trouble with this, feel free to push your changes up to this PR and I can take a look over here when time permits.

**Comment by lahmann** [comment]
That's perfect! Thanks a lot! :)

**Comment by demiankatz** [comment]
No problem. I've often thought "it would be useful to run just one test," but I never took the time to investigate whether it was easy to do. Turns out, it's easy to do! Thanks for providing the motivation to finally do it.

**Comment by lahmann** [comment]
:) And with the help of running this single test (including verbose output for var_dumps) I finally managed to get DAIATest.php running including HTTP-header checks.

So, from my point of view this should provide the exact same behaviour as the DAIA driver currently in master, plus the ability to query multiple ids.

**Comment by demiankatz** [comment]
Thanks! I've just sent Jochen an email to see if he can take a look at this and offer his perspective as another actual DAIA user. There's a lot going on in some of that code, and I'm not in a position to fully understand its significance.

Beyond that, the only other feedback I have is that some of this will need to be adjusted slightly to meet coding standards; I see some braces out of the usual positions, plus protected methods should not have a leading underscore in the name. You can do `phpcs --standard=PEAR [filename]` to get a full report if you're interested in addressing this, or else I can do it later as part of the "merge to master" process.

**Comment by lahmann** [comment]
Thanks Demian for contacting Jochen! I've fixed the code style issues - there's only one warning left (exceeding 80 characters).
I also made the http-header comparison a little bit more robust and it should comply now to Media-Types definition in [RFC2616](http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.7).

**Comment by jochen-lienhard** [comment]
The json version seems not to work correct. If I use the xml version, everything looks good.
Andre, do you look at this problem, or shall I search for the bug?

**Comment by lahmann** [comment]
Hi Jochen, thanks for testing it. What exactly does not work? I just tested this version with xml/json (not in legacy mode), multiQuery on/off and it works fine.

Besides I am rethinking the changes I introduced yesterday by removing the underscored method-names: maybe it's a good idea to reintroduce those and declare those methods as private methods. 
As Jochens initial thought was to build a DAIA driver that could be the base for more customized DAIA drivers it might be a good idea to keep some methods private and only expose methods that cover the mapping of DAIA attributes to VuFind holdings info.
What do you think?

**Comment by jochen-lienhard** [comment]
json, not legacy mulitQuery off ... I get no callnumbers etc ...  even in both, list and result

**Comment by lahmann** [comment]
Ok, I tried this setting and it works for me. Could you please check the response of the DAIA server (e.g. `curl -D - "url"`): I added a check on the Content-Type, so if your DAIA webservice sends JSON with a different Content-Type than application/json the response gets ignored.

**Comment by jochen-lienhard** [comment]
The content type looks good. I try to find, what maybe wrong.

curl -D - "https://daia.ibs-bw.de/isil/DE-25?id=ppn:340216956&format=json" 
HTTP/1.1 200 OK
Date: Fri, 27 Mar 2015 10:02:15 GMT
Server: Apache/2.2.12 (Linux/SUSE)
Content-Length: 1850
Content-Type: application/json; charset=UTF-8

{
    "version": "0.5",
    "schema": "http://ws.gbv.de/daia/",
    "timestamp": "2015-03-27T11:02:15.772316",
    "institution": {
        "content": "Universit\u00e4tsbibliothek Freiburg",
        "href": "http://www.ub.uni-freiburg.de/",
        "id": "http://lobid.org/organisation/DE-25"
    },

**Comment by jochen-lienhard** [comment]
The Problem is, that the $doc["id"] == $this->generateURI($id) is not equal (line 485)
$doc["id"] = string(13) "ppn:04217466X" 
$this->generateURI($id) = string(18) "adis:pr_isn:559459"

**Comment by lahmann** [comment]
I see. Shouldn't the document id in the response correspond with the queried URI?

**Comment by jochen-lienhard** [comment]
I don't know. We have no access to the configuration of the DAIA-server, so we must accept, what we get. In our case the id's do not correspond.

**Comment by demiankatz** [comment]
Regarding protected vs. private, as a general rule, I've avoided private methods in VuFind on the theory that you can never fully anticipate what somebody is going to need to override in a subclass. However, if you feel that adding private methods would improve the clarity of the code, it's certainly not "against the rules."

**Comment by lahmann** [comment]
Hmm, the DAIA specs are not very explicit on that topic:

> id (attribute) - each document needs an unique id to query it (e.g. ISBN, ppn, etc.). Please consider that ids have to be URIs. Type xsd:anyURI.

(see http://gbv.github.io/daiaspec/daia.html#document-element)

It seems logical to assume, that an unique id used to query a document will also identify the document in the response - above that this is absolutely necessary for DAIA queries with multiple ids as one needs to identify the documents in the response with the queried ids.

Anyway, that doesn't help you if you don't have access to configuration of the DAIA server...

A quick and dirty fix would be to compare response-document-id and query-document-id only if multiQuery is enabled as with mulitQuery disabled only one document will be queried anyway and the document(s) in the response _should_ belong to the queried id.

As this seems to be a conceptual problem I've filed an issue in the DAIA specifications concerning the not required match of document-id and query-id (see https://github.com/gbv/daiaspec/issues/13).

**Comment by jochen-lienhard** [comment]
Have you this check only in the json part? I can not find it in the xml part.

**Comment by lahmann** [comment]
If you mean the check of document id and query id: no, it's done for both, xml and json.
I have added now a check if multiQuery is enabled, so that the document id and the query id will not be compared in case we don't have multiQuery on.
Could you please test the driver again?

**Comment by jochen-lienhard** [comment]
I'm a little bit confused, do you not use getJSONStatus any more?

**Comment by lahmann** [comment]
Sorry for being not very specific: getXML(Short)Status are only used in legacy mode, getJSONStatus is not used anymore, but I kept it in case you refer to it from another class. All three methods, getXML(Short)Status and getJSONStatus are untouched (except for the initial query of the document), but I copied the logic into the more general methods parseDaiaArray (json) and parseDaiaDom (xml) which are called both by parseDaiaDoc. The reason I had to rearrange the code was that due to the multiple documents that can occur in the DAIA response with multiQuery I needed to be able to loop only the parsing logic. In the end parseDaiaArray and parseDaiaDom are pretty much identical with getJSONStatus and getXMLStatus.
Another advantage is that because the parseXStatus methods include only the parsing logic they could be easily adapted for a customized DAIA driver, leaving the whole logic for querying the DAIA document and handling it untouched.

**Comment by jochen-lienhard** [comment]
What will you do, if you have an institution tag? How do you react is you have some base errors? (for example DAIA can not find the database or something else)? I understand your motivation, of changing the behavior. You can remove dead code, I have no sub class at the moment.
It seems all works now.

**Comment by lahmann** [comment]
1.) As in the original getXStatus methods the institution tag is not considered - and I think it's not really necessary right now: referring to the DAIA specs the institution-element holds "information about the institution that grants or knows about services and their availability". As the DAIA driver is very likely being used in institutional catalogues the availability information regards availability for the specific institution anyway.
Even having a catalogue that spans several institutions would not break that assumption (if I read the DAIA specs correctly) as this meta-catalogue would provide the availability information and would credit herself in the institution-element. The actual availability of the documents/items would be specified by the elements department and storage.
On the other hand I am not opposed to parsing the institution element, but I don't see any necessity at the moment. Of course this could change if one would like to query multiple DAIA APIs for availability information and therefore would need the institution element to group the responses accordingly - but then the DAIA driver would need further implementation work anyway as multiple APIs are not supported at all.

2.) As for the error handling: in my understanding the DAIA API is a RESTful interface that serves documents. If there is an error with my query (i.e. wrong id) I'll get a 404, if the service is offline, I'll receive a 5xx - all these cases are covered in doHTTPRequest.
Anything else concerns the availability of the record I queried and therefore goes into the DAIA response. That needs to be handled by our driver and is not very well covered at the moment - probably the next point of our todo-list :)

I'll remove the getJSONStatus method with my next update of this PR.

**Comment by demiankatz** [comment]
Thanks for the collaboration on this! Is any further review/work required before we merge this?

**Comment by lahmann** [comment]
Demian, from my point of view the driver can be merged, but I would leave it to @jochen-lienhard to give the final go.

Regarding protected vs. private, thanks for sharing your thought - I see your point and think it's a good practise to declare private methods only if it's absolutely clear that no subclass will use those.

**Comment by demiankatz** [comment]
Thanks, André! I'll wait for Jochen's final word and then merge with his approval. It may not happen until next week, though, since I'll be away at a conference for the rest of this week. We'll see how good my Internet access is while I'm away!

**Comment by lahmann** [comment]
Sure, no problem. Enjoy the conference! :)

**Comment by jochen-lienhard** [comment]
It looks good for me, so you can merge after the conference.

**Comment by lahmann** [comment]
Just a very small bugfix, that caught my attention a few minutes ago. Still ready to be merged into master.

**Comment by lahmann** [comment]
Another small bugfix that prevents PHP-Warnings in calculateStatus() if some array-keys are not set (which can happen as only attribute expected is mandatory for unavailable element).
Unittest report is ok.

**Comment by demiankatz** [comment]
Thanks again for all the work on this! I've manually merged it to master (collapsing the commit history for simplicity and making a couple of small php-cs-fixer whitespace changes).

**Comment by lahmann** [comment]
Perfect! Thanks!

**Pull request closed without merging**
