### PR TITLE
Fix HTML validation and JS deprecation issues.

### PR DESCRIPTION
**Pull request by EreMaijala**
Notes:
- role=menuitem has been removed from hierarchical facet entries. It was invalid and likely to be ignored anyway since it wasn't contained in a menu or menubar.
- The cookie consent module creates duplicate id's for table headers. This has been reported as https://github.com/orestbida/cookieconsent/issues/483.
- embedded_record.js is currently using collapse to manage switching between short and long view. I don't think collapse can manager aria attributes properly in this case since the heading toggles two elements, but I'm not sure what would be the best remedy either.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @EreMaijala! Let me know when you're ready for a review (I'm assuming not yet, since this is still in draft).

**Comment by EreMaijala** [comment]
@demiankatz Now ready for review. This doesn't fix everything, but with #2774 gets us down to a much more reasonable number of issues.

Sorry for the messy PR. There are some changes that could be easily picked separately, at least:

- record.js
- embedded_record.js
- facets.js
- visual_facets.js
- ContentBlock/FacetList.phtml
- Recommend/FavoriteFacets.phtml
- Recommend/SideFacets/range-slider.phtml
- RecordTab/holdingsils.phtml
- channels/channelList.phtml
- collection/view.phtml
- collections/home.phtml
- holds/list.phtml
- record/view.phtml
- search/advanced/ranges.phtml
- search/controls/results-tools.phtml
- search/pagination.phtml
- Helpers/icons/collapse.phtml
- Helpers/icons/images.phtml


Then the link-*.phtml templates are similar in that they aim to eliminate line feeds from link URL's.

**Comment by demiankatz** [comment]
Thanks, @EreMaijala! I've reviewed and merged all the link-*.phtml templates as a separate commit to dev and merged that back into this PR to greatly reduce the number of files. I'll work on some of the other individual files you highlighted above as time permits (though I may not get back to this before tomorrow).

**Comment by demiankatz** [comment]
@EreMaijala, I've finished cherry-picking your other recommended files to dev -- all of those changes make sense to me. I'll review the remainder of this PR as soon as time permits!

**Review by demiankatz — APPROVED** [review]
I've cherry-picked more pieces off of this, and I'm now comfortable merging what remains. Thanks for all the work on it, @EreMaijala!

**Pull request merged**
