### PR TITLE
Fix save statuses and save action links in combined results

### PR DESCRIPTION
**Pull request by EreMaijala**
I would have wanted to make the new combined.js have a class that would be part of the VuFind namespace, but it's currently initialized so late in the process, only after .js files are loaded, that I decided to do it the "traditional" way for now.

### CODE REVIEW

**Comment by crhallberg** [comment]
This fixes the problem of checking statuses in AJAX columns, right?

**Comment by EreMaijala** [comment]
Yes, that's correct.

**Comment by crhallberg** [comment]
I understand you wanted to incorporate this into the VuFind object. I just opened a PR to reduce the complexity of the namespace and have it load much sooner. https://github.com/vufind-org/vufind/pull/607

Also, the CSS for the combined search is called `combined-search.css` to distinguish it from `compiled.css`. Do you think we should name your file `combined-search.js`? It's not as important because there is no `compiled.js`.

**Comment by EreMaijala** [comment]
Awesome, I'll refactor this and open a new PR when PR 607 hits master. Also combined-search.js is more explicit so I'll use that.

**Comment by demiankatz** [comment]
Okay, #607 is merged, so you're free to revise at your convenience.

**Pull request closed without merging**
