### PR TITLE
Add delimited facet capability

### PR DESCRIPTION
**Pull request by demiankatz**
Replaces #525.

### CODE REVIEW

**Comment by demiankatz** [comment]
Finally had a chance to review this more closely. A few comments/questions/ideas:

1.) There's some inconsistent spelling here -- getDelim*e*ter vs. setDelim*i*ter. We should make sure that "delimiter" is spelled correctly throughout.

2.) I'm not sure if get/setDelimiter is specific enough, though -- might be best to rename those methods to be get/setFacetDelimiter for greater specificity.

3.) Do you think there might be a situation where the user would need different delimiters for different facet fields? Might it be better, rather than having a separate delimiter setting in facets.ini, to instead make the delimiter part of the delimited_facets setting? That is, we could define some kind of default delimiter, and allow the user to override it by adding some delimited value onto the name of the facet field... like `delimited_facets[] = "my_facet_field|my_delimiter"` or something similar. Maybe I'm overthinking here -- but even if we don't implement this right away, I think we should make sure our design doesn't make it hard to do in the future, just in case the need arises.

Apart from that, it all makes sense to me! I'm not in love with the fact that we're adding even more methods to Options and Params, which already have too much code in them, but that's not a problem with your solution so much as with general architecture. I'd still love to find a more elegant model there, but that's well beyond the scope of this PR!

**Comment by datavoyager** [comment]
Hi Demian,

Thanks for reviewing this.

I agree with all your comments (I had nightmares about spelling delimeter / delimiter!).

I see that the pull request is closed. Does that mean I should refactor and then open a new pull request?

Thanks,

Luke

**Comment by demiankatz** [comment]
#525 is closed, but #528 is open. You should be able to push more commits to this branch (delimted-facets on datavoyager/vufind) to continue work on the feature.

**Comment by demiankatz** [comment]
(I had to open a new PR because the first one was targeted against the release-2.5 branch instead of master, and GitHub doesn't let you change the target of a pull request).

**Comment by datavoyager** [comment]
Hi Demian,

I've added the custom delimiter functionality and hopefully sorted out the spelling of "delimiter".

Cheers,

Luke

**Comment by demiankatz** [comment]
Thanks for the progress. I think this can be made a little more efficient, however -- as written, we're doing a lot of redundant work for every single value of every single facet. I think it might be better to do more of this up front so we just use the same lookup array over and over during display.

Thus I'd propose adding this property:

<pre>
    /**
     * Convenient field => delimiter lookup array derived from $delimitedFacets.
     *
     * @var array
     */
    protected $processedDelimitedFacets = null;
</pre>

Then, when we set either a default delimiter or list of delimited fields, the processed cache gets cleared out (so we don't return inappropriate values). We then modify the getter for delimited fields to accept a parameter which controls whether it returns the raw values from the configuration, or processed values from the cache... and the processed values are a convenient field => delimiter associative array. Here's the code:

<pre>
    /**
     * Set the defaultFacetDelimiter value.
     *
     * @param string $defaultFacetDelimiter A default delimiter to be used with
     * delimited facets
     *
     * @return void
     */
    public function setDefaultFacetDelimiter($defaultFacetDelimiter)
    {
        $this->defaultFacetDelimiter = $defaultFacetDelimiter;
        $this->processedDelimitedFacets = null; // clear processed value cache
    }

    /**
     * Get a list of delimited facets
     *
     * @param bool $processed False = return raw values; true = process values into
     * field => delimiter associative array.
     *
     * @return array
     */
    public function getDelimitedFacets($processed = false)
    {
        if (!$processed) {
            return $this->delimitedFacets;
        }
        if (null === $this->processedDelimitedFacets) {
            $this->processedDelimitedFacets = [];
            $defaultDelimiter = $this->getDefaultFacetDelimiter;
            foreach ($this->delimitedFacets as $current) {
                $parts = explode('|', $current, 2);
                if (count($parts) == 2) {
                    $this->processedDelimitedFacets[$parts[0]] = $parts[1];
                } else {
                    $this->processedDelimitedFacets[$defaultDelimiter] = $parts[0];
               }
            }
        }
        return $this->processedDelimitedFacets;
    }

    /**
     * Set the delimitedFacets value.
     *
     * @param array $delimitedFacets An array of delimited facet names
     *
     * @return void
     */
    public function setDelimitedFacets($delimitedFacets)
    {
        $this->delimitedFacets = $delimitedFacets;
        $this->processedDelimitedFacets = null; // clear processed value cache
   }
</pre>

With that in place, it becomes much simpler to actually process the facets. The getDisplayTextFromDelimitedFacet() method becomes unnecessary and goes away, and checkForDelimitedFacetDisplayText() reduces down to this:

<pre>
    /**
     * Check for delimited facets
     *
     * @param string $field       The facet
     * @param string $displayText The facet value
     *
     * @return string
     */
    public function checkForDelimitedFacetDisplayText($field, $displayText)
    {
        $delimitedFacetFields = $this->getOptions()->getDelimitedFacets(true);
        return isset($delimitedFacetFields[$field])
            ? current(explode($delimitedFacetFields[$field], $facet, 2))
            : $displayText;
    }
</pre>

(I haven't tested any of this code, so there may be a bug or two... but hopefully it at least conveys the idea. What do you think? If you like the idea but don't have time to test, let me know and I can try this out on my test server -- but I'm guessing you may be able to test this faster than I can since you have real data to play with).

**Comment by datavoyager** [comment]
Hi Demian,

I've made your recommended changes (with a few minor fixes).

Cheers,

Luke

**Comment by demiankatz** [comment]
Looking good to me! I'll probably ask for input on this on the next dev call just to make sure there are no further suggestions/objections, then I'll go ahead and merge.

One small thing: Travis is complaining about a couple of style issues (click "details" under the "all checks have failed" message for the specifics). If you have a chance to fix them, that would be great. If not, I'll take care of it at merge time.

Thanks again!

**Comment by datavoyager** [comment]
When I click on the details tabs I get a "There was an error while loading data, please try again" message.

**Comment by demiankatz** [comment]
Strange -- it takes me to https://travis-ci.org/vufind-org/vufind/builds/96765971 which loads correctly on this end. In any case, here's the important bit:

<pre>
----------------------------------------------------------------------

FOUND 2 ERRORS AFFECTING 1 LINE

----------------------------------------------------------------------

 533 | ERROR | [x] Line indented incorrectly; expected 16 spaces,

     |       |     found 15

 533 | ERROR | [x] Closing brace indented incorrectly; expected 16

     |       |     spaces, found 15

----------------------------------------------------------------------

PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY

----------------------------------------------------------------------</pre>

**Comment by EreMaijala** [comment]
A couple of comments (I didn't read the code, sorry):

1.) The description in #525 is understandable but the comments in facets.ini should be improved. At least I couldn't understand the idea from the comments. Also the first example should use the default delimiter (it's missing a couple of }, no?). 

2.) I'd also verify whether the comment in facets.ini has the order of display text and value right, since the first comment in #525 has it the other way around (123456::Jones, Gareth) and that would seem more appropriate. 

3.) Can the display text still be translated? I was thinking that this could be used with index-sorted facets and translation to display a facet in a predefined order, like:
1::lib_main
2::lib_branch

**Comment by demiankatz** [comment]
I thought I had already fixed some of those issues with the .ini comments, but you're right -- they're still there. Before I work on that, though, we should probably discuss the order issue a little further.

Luke originally implemented this with value::displayText; I proposed switching it to displayText::value so that index sorting would be more likely to yield appropriate values. But your "fixed order" example shows a use case where Luke's original order is definitely preferable. Perhaps we need to allow further configuration to specify the order -- though I'm not sure if that amounts to overproliferation of options. One crazy (probably bad) idea: what if the delimiter determines the order... like "1<DisplayText" or "DisplayText>1"? (I don't like it, but it popped into my head, so I said it anyway). Thoughts?

Also, regarding translation of display text, yes, that is possible -- the code translates the display text according to the normal translation configuration just like non-delimited text.

**Comment by EreMaijala** [comment]
Feel free to disregard my thoughts on the order if it becomes too cumbersome. :)

**Comment by demiankatz** [comment]
Well, I think your thoughts may actually provide a more justifiable use case than the default case. I'm a little bit uncomfortable with the idea of having the same display text have two different meanings in the facet list (which is Luke's need: disambiguating authors with the same name when they have different known identifiers), but being able to control the order of the facet list in a language-independent way seems more broadly applicable.

Perhaps a more elegant solution: don't assume that there are a fixed number of delimited parts -- just assume that the last part is the display portion. Then, for Luke's case, where he wants to sort by display text, he could use two delimiters:

`[sort_text][delimiter][identifier][delimiter][display_text]`

For your case, where the prefix is just for sort order, you could use:

`[sort_text][delimiter][display_text]`

That would seem to argue for reverting to Luke's original order. What do you think?

**Comment by EreMaijala** [comment]
That'd work for me.

**Comment by demiankatz** [comment]
I'll see what Luke has to say, then one or the other of us can make the final adjustments. Thanks for the input -- very helpful!

**Comment by datavoyager** [comment]
Hi Demina and Ere,

Thanks for your comments.

Just to be sure, Demian, are you suggesting the following:

1) Return the default delimiter to [sort_text][delimiter][display_text]
2) Create code which checks the number of delimiters and assign values accordingly? E.g. If there is one delimiter it's  [sort_text][delimiter][display_text], if there are two delimiters it's [sort_text][delimiter][identifier][delimiter][display_text]

Thanks,

Luke

**Comment by demiankatz** [comment]
Luke, that's correct. Thanks for checking (and for coming back to this!). Let me know if I can be of any further assistance.

**Comment by datavoyager** [comment]
Hi Folks,

I've updated the branch. 

I didn't go for the simple replacement of current() with end() as that can lead to "return value in write context" errors depending on the version of PHP being used.

I've tried to make the description in facets.ini a little more understandable via example. 

Cheers,

Luke

**Comment by demiankatz** [comment]
Okay, I've manually merged this to master to flatten the commit history; I've also made a couple more tweaks to comments in an effort to further improve clarity.

**Comment by demiankatz** [comment]
Thanks again for all the work on this!

**Comment by datavoyager** [comment]
No problem - Thanks for accepting it. Will keep Helen Davies and Helen Davies here happy ;)

**Pull request closed without merging**
