### PR TITLE
Remove faulty support for login delimiter configuration from MultiBacken...

### PR DESCRIPTION
**Pull request by EreMaijala**
...d driver.

### CODE REVIEW

**Comment by demiankatz** [comment]
Looks like these changes break a couple of unit tests. Might be worth investigating those to see if they provide any insight to why this code was here in the first place. I can't remember if this was related to an actual need at Keystone Library Network, or if it just got put in because I said "it's probably better practice to make the separator configurable for future flexibility." I certainly have no big objection to removing it at this point as long as it's not going to break any live installs.

**Comment by EreMaijala** [comment]
Oops, I'll check the tests, which of course test that the login delimiter works. From what I gathered from the discussion when I worked on the MultiBackend driver, they ended up not using the patron functionality in MultiBackend. I don't know if there's any way to verify that, but I strongly believe that supporting configurability here is wrong. If you feel it's too risky to remove the support, I suggest at least making period the default and adding a warning that changing it would break at least multiple library card support.

**Comment by demiankatz** [comment]
I think your recollection is correct. I have no objection to ripping this out for now; if we need it back, it probably won't be much more work to reimplement than to fix what's already there but broken.

**Comment by demiankatz** [comment]
Okay, manually merged to master. Note that I did some further work to remove the (now meaningless) second parameter from calls to getSource(). Pretty sure I didn't break anything, and all tests still pass, but you might want to give the latest version a quick check to be sure it's still okay.

**Pull request closed without merging**
