### PR TITLE
Update jQuery to 3.5.0 (security)

### PR DESCRIPTION
**Pull request by xmorave2**
See https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @xmorave2! Doesn't look like this should cause any problems, since I'm pretty sure we're not using the impacted `htmlPrefilter` method anywhere (a quick search of the code seems to back this up). As soon as time permits, I'll run the full test suite on this to be totally sure nothing breaks, and then I'll merge it.

**Comment by demiankatz** [comment]
I just ran the test suite, and it appears that two tests are consistently failing with jQuery 3.5.0 but passing with the earlier version. There must be some subtle problem. I'm short on time today, but I will investigate further when time permits.

**Comment by demiankatz** [comment]
I've had a chance to look into this further; it appears that jQuery 3.5.0 breaks the accordion functionality in Bootstrap 3.4.0. It might be worth upgrading to the latest version of Bootstrap3 (3.4.1) to see if that resolves the issue. If that doesn't help, we could investigate whether introducing the jquery-migrate plugin helps (though that would be a last resort).

**Comment by demiankatz** [comment]
(Clearly I should never say "Doesn't look like this should cause any problems" -- I should know better by now ;-) )

**Comment by demiankatz** [comment]
I've opened a PR to upgrade Bootstrap (#1618) but when I combine that upgrade with this upgrade, the accordions still don't work... and then @crhallberg found this, which seems to explain everything: https://github.com/twbs/bootstrap/issues/30553

Short version: it's a bug in jQuery 3.5.0, and they just released 3.5.1 to fix it.

@xmorave2, can you update this PR to use jQuery 3.5.1 instead? Once you have a chance to do that, I'll re-run the test suite, and then hopefully we'll be able to move forward.

**Comment by xmorave2** [comment]
thank for investigation @demiankatz and @crhallberg, I update to 3.5.1

**Comment by demiankatz** [comment]
Thanks, @xmorave2; all tests are passing now, so I'm going to merge this!

**Pull request merged**
