### PR TITLE
[VUFIND-1149] Don't mess up the login lightbox if the user has alread…

### PR DESCRIPTION
**Pull request by EreMaijala**
…y logged in in another browser tab or window.

### CODE REVIEW

**Comment by crhallberg** [comment]
Sorry for the slow reply on this. Demian and I were concerned about the non-JS compatibility of this so we've been working on it. Our solution is similar to yours, but uses 307 and a custom header to make the browser refresh the page, even without JS. We're still cleaning it up for review.

**Comment by crhallberg** [comment]
Soon after this we discovered that trying to support non-JS puts us in a catch-22. By sending redirect headers, we fix non-JS but break JS. By not sending them, we break non-JS redirects.

The majority wins. Update this with master and we'll merge it in.

**Comment by crhallberg** [comment]
Closed by accident (clicked the wrong button)

**Comment by demiankatz** [comment]
Manually merged to master to resolve the conflict.

**Comment by EreMaijala** [comment]
Thanks!

**Pull request closed without merging**
