### PR TITLE
KohaRest: Show recalled message if a recall is blocking renewal

### PR DESCRIPTION
**Pull request by aleishaa**

### CODE REVIEW

**Review by EreMaijala — APPROVED** [review]
Looks good to me!

**Review by EreMaijala — CHANGES_REQUESTED** [review]
Oops, I didn't notice the test failures. Please check the CI test results. There's still a problem with the language file that should be in alphabetical order.

**Comment by demiankatz** [comment]
And in case you haven't done this before, note that you can run `php $VUFIND_HOME/public/index language normalize languages` to automatically fix it. :-)

**Comment by demiankatz** [comment]
Since this is adding a new language string, and translation work is already underway for release 10.0, we won't be able to merge this until we begin work on release 10.1, since that is when the next translation cycle will occur.

**Review by EreMaijala — APPROVED** [review]

**Pull request merged**
