### PR TITLE
Loading Performance Improvements

### PR DESCRIPTION
**Pull request by crhallberg**
Based on the metrics of [Google's Lighthouse](https://github.com/googlechrome/lighthouse)
 - Scripts files are deferred by default. You can add a `:critical` condition to the end of the file name to load it before the body or other scripts (jQuery, common.js, record.js).
 - ~~External links (Google Books in particular) given [`rel="noopener"`](https://jakearchibald.com/2016/performance-benefits-of-rel-noopener/)~~ [Merged](https://github.com/vufind-org/vufind/commit/dc85e357a78547e460173af96e988a93bba5356b)
- ~~Update bootstrap-slider, which [now](https://github.com/seiyria/bootstrap-slider/pull/680) uses [passive touch event listeners](https://developers.google.com/web/updates/2016/06/passive-event-listeners).~~ [Merged](https://github.com/vufind-org/vufind/commit/bb9b7d731f4edb1be5ab6db98f32b691e224bdda)

- [ ] Pipeline tests vs deferred
- [ ] Split on colons for attrs: `record.js:IE 10:critical`

### CODE REVIEW

**Comment by crhallberg** [comment]
The pub date timeline (powered by flot) doesn't work with touch and the touch add-on isn't the fix we're looking for. Since it's between the top of the page and the first result, would anyone object to hiding it on mobile?

**Comment by demiankatz** [comment]
I've merged your two simple, straightforward commits to master. That leaves the ":critical" condition support, which I think may require a bit more thought. I think that the conditional portion of the JS files is processed by some other code at a higher level (though I need to review the details). I want to be sure that this functionality doesn't conflict with anything else. I'll give it a closer look, and more thought, when I have a bit more free time.

**Comment by demiankatz** [comment]
@crhallberg, to follow up on my earlier comment, here is the existing code that parses the colon-delimited JS settings:

https://github.com/vufind-org/vufind/blob/82e077002a5e1b4905bb0582f6cd6b607b0c2846/module/VuFindTheme/src/VuFindTheme/View/Helper/HeadThemeResources.php#L155

As you can see, this happens outside of the actual script view helper. I think it would probably be cleaner to handle the priority processing here rather than deeper in the code, since that avoids adding extra complexity to subclasses of core ZF components. Additionally, I wonder if it might be worth considering adding a second colon-delimited value rather than overloading the conditional position, since these are really two different things -- what if we need to support a conditionally-loaded high-priority script?

**Comment by crhallberg** [comment]
I initially put the code here, but appended scripts that are added through the templates aren't handled here. For example:
image
image

**Comment by demiankatz** [comment]
Ahh, good point. Are those even being handled properly as it is?

**Comment by crhallberg** [comment]
After the comments in the dev call today, I ran performance tests comparing deferred to the pipeline. I ran each test 3 times (this branch vs master with pipeline on) and you can see some of the metrics below.

image

It is clear that this method gives no clear advantage over the asset pipeline. Since two of the improvements have already been merged into master, leaving only the script deferring, this PR will be closed.

It is more likely that the code here will be more useful for conditionally loading scripts from templates than for improving performance.

**Pull request closed without merging**
