### PR TITLE
Buchhandel.de Cover service

### PR DESCRIPTION
**Pull request by powerriegel**
Cover Class for Buchhandel.de'e new API (mandatory in 2016)

### CODE REVIEW

**Comment by demiankatz** [comment]
Have you looked at #507? It seems to implement the same API as this, though it is a bit more configurable and has more test coverage. Is there something in this version that is missing from #507, or should we close this version and use that one?

**Comment by demiankatz** [comment]
In any case, thanks for sharing this -- apologies if you've ended up wasting any duplicate effort building it.

**Comment by powerriegel** [comment]
Ok, no worries.

**Comment by jochen-lienhard** [comment]
I think it would be better to work on PR 507. @powerriegel if you need write access to PR 507 please tell me, and I will set it.

**Comment by demiankatz** [comment]
Okay, I'm going to close this one. Feel free to reopen if there's a need.

**Pull request closed without merging**
