### PR TITLE
Make UrlQueryHelper more extensible.

### PR DESCRIPTION
**Pull request by demiankatz**
TODO:
- [x] Finish implementation: use factory service in Results objects
- [x] Test functionality

### CODE REVIEW

**Comment by demiankatz** [comment]
@EreMaijala, it was brought to my attention that there's not currently a good way to extend the UrlQueryHelper in VuFind; this PR aims to address that limitation. I think it's pretty straightforward, but do you mind giving this a quick review in case I've overlooked anything? Thanks!

**Review by EreMaijala — APPROVED** [review]
Looks fine to me (apart from the Travis issues). But this got me thinking that I don't really like that the factory is unlike any other factory. I understand this is probably the best that can be done without breaking compatibility.

**Comment by demiankatz** [comment]
Thanks for the review, @EreMaijala. I agree that it is not ideal that the UrlQueryHelperFactory does not follow the same pattern as 99% of other factories in VuFind, but I think it's somewhat unavoidable. It's a factory in the sense of the "factory pattern" broadly, but it's not a Zend Framework factory -- and that's because it needs to build an object from specific pieces of data rather than by pullling services from the service manager. I think trying to force it into that mold might actually make matters worse... though I'm open to suggestions if you have any! For now, I think this is at least a step in the right direction (in that it offers us extensibility where there was none before).

**Comment by EreMaijala** [comment]
@demiankatz Maybe we could have a normal factory and then a separate builder, but that feels then like an extra layer of obscurity. I can very well live with the current one. :)

**Pull request merged**
