### PR TITLE
Mailer is now able to send name in "from" header

### PR DESCRIPTION
**Pull request by MartinKravec**

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks for sharing this; however, I think there may be a simpler solution to this problem. All of the \Zend\Mail\Message methods that accept an email address string are also capable of receiving a \Zend\Mail\Address object, which itself can include both an email address and a name. Rather than adding a whole new parameter, it may be possible to simply adjust the relevant typehints in the comments to be string|\Zend\Mail\Address instead of just string, and then pass in an object with a name property from the higher level code. What do you think?

**Comment by MartinKravec** [comment]
Thanks, your solution is much simpler! I will refactor it like you say.

**Comment by demiankatz** [comment]
Thanks! Please leave a message here when you've had a chance to do that and I'll take another look.

**Comment by MartinKravec** [comment]
Hey Demian. I got it. Do I have to create a new pull request or can i edit this one somehow?

**Comment by demiankatz** [comment]
You can push the code to this branch to update the pull request -- if you have a different branch derived from master, just do a "forced push" to overwrite what's already here and it should be fine... but if you have any trouble with that, feel free to just close this one and open a new one if that's easier.

**Pull request closed without merging**
