### PR TITLE
PAIA notifications in ILS\Driver\PAIA

### PR DESCRIPTION
**Pull request by domerz**
Incorporates PHP functionality for new PAIA functions concerning notifications (i.e. system messages).
See http://gbv.github.io/paia/paia.html#notifications

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @domerz; am I correct in understanding that this functionality is not currently being used in this version of the driver but is simply being provided for use in local customizations or future work? If so, that's fine, and I don't mind merging -- just want to be sure I'm not missing something!

I'm also interested in whether @hajoseng or @ndege have any feedback on this, since they have both been involved in recent PAIA driver discussions.

**Comment by domerz** [comment]
Hi @demiankatz, thank you for the quick answer. Actually, we at the finc-Team (which @ndege is a member of) use the new notifcations functionality. We were even involved in including those functions to the PAIA standard. At the moment our implementation resides in an inherited version of the PAIA class on the finc-module-level. So, this PR can be seen as an attempt to keep the VuFind-core PAIA class up-to-date with the standard.

**Comment by ndege** [comment]
@demiankatz As @domerz has already mentioned humbly I have no objection for this pull request. We  initiated it to integrate it at the PAIA standard, so I suppose there aren't any integrated use cases at other institutions so far. It's an extensions everyone can reuse at VuFind in future if he like. 

Minor point: There's a typo needs to be fixed by naming of constant at line 1915.

**Comment by demiankatz** [comment]
Thanks for the catch and fix, @ndege and @domerz; this seems safe to merge, so I'll go ahead with it! If there is a common way to make use of this and you want to incorporate it more directly into the master code in future, please feel free to open another PR.

**Pull request merged**
