### PR TITLE
Fix for cache keys not matching Zend's default cache key naming pattern in ILS driver

### PR DESCRIPTION
**Pull request by lahmann**
When implementing cache functionality to ILS driver based on methods provided in `VuFind\ILS\Driver\AbstractBase` doing so will fail with error `The key 'VuFind\\ILS\\Driver\\DRIVERNAME-5cfbd89e7fb28cdb3f791fe3b78ca5fa' doesn't match against pattern '\/^[a-z0-9_\\+\\-]*$\/Di'`.
This pullrequest simply replaces backslashes with `_` to match the pattern. This is obviously a very simple fix.
One, maybe more appropriate, alternative fix would be to change the default Zend cache key pattern (see http://framework.zend.com/manual/current/en/modules/zend.cache.storage.adapter.html#the-filesystem-adapter) - although backslashes in filenames will cause trouble in most filesystems.
Another solution would be to introduce a VuFind-wide naming scheme for cached data (or does this already exist?).
Maybe something worth to discuss - in any case the current fix works.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks for catching this. It seems like it might make sense to add a page to the wiki listing the various ways in which VuFind uses caching and recommending some conventions to avoid collisions. I'd be willing to work on a draft of this when time permits.

We can discuss this on tomorrow's dev call to see if there are any strong opinions. Your approach seems reasonable, though I suppose another option would be to move the prefix inside the md5() call (which ensures uniqueness at the possible expense of readability).

Also note that right now, Travis is complaining about this PR due to a line length issue.

**Comment by lahmann** [comment]
Sound like a good idea documenting where VuFind uses caching already. Let's discuss this on tomorrows dev call.

Good old Travis - the latest commit should fix the code formatting issue :)

**Comment by demiankatz** [comment]
Thanks for the formatting fix. Here's a first draft of a wiki page -- not too rich in information yet, but it gives us a place to expand from:

https://vufind.org/wiki/development:architecture:caching

**Comment by demiankatz** [comment]
I've just updated the wiki page with an inventory of uses of the object cache. There actually aren't very many at all. It might be possible to decide on a convention like "class of object using cache with backslashes switched to underscores, plus whatever additional details are needed" or else "md5 of class name plus additional details" if we want to have more fixed-length keys. Either way, if we pick a convention, we can standardize all of the existing code relatively easily. Any thoughts/preferences?

**Comment by lahmann** [comment]
Demian, sorry for getting back to this pull request this late. Regarding the wiki page this looks great and provides in my opinion sufficient information for the current state of cache implementation. Thanks again!

Regarding the naming conventions, I actually like your suggestion "class of object using cache with backslashes switched to underscores, plus whatever additional details are needed". This is very straightforward and provides enough room for customization in case one wants to handle cached data differently based on the cacheKey-suffix; plus it makes debugging easier as you can actually identify the cached data from the filenames. For production though I think using md5 on top of class-convention would be better as the filename length is more predictable - we could make this configurable. What do you think?

**Comment by demiankatz** [comment]
I like the idea of configurable key generation -- it could either be configured based on a cache setting in config.ini, or else we could consider basing the behavior on the environment setting ('development' vs. 'production').

The challenge with moving forward with that strategy is that we need to have a place to put the key generation logic, and preferably a place that has easy access to configurations (if we go down the config.ini route). The challenge there is that the easiest place to put the key generator would be in VuFind\Cache\Manager, but the code that actually needs access to the method is not currently being injected with the cache manager, just with the storage adapter... and we're using a vanilla Zend storage object for the object cache. Subclassing the file adapter just to add this functionality seems excessive (not to mention creating some strong coupling). Perhaps another option would be to create a VuFind\Cache\KeyGeneratorTrait that could be "mixed in" to any class that needs to use the functionality...  The mix-in approach has the advantage of allowing the getCacheKey() method to use get_class($this) rather than requiring the calling object to pass itself to an external function... but this approach would also favor NOT depending on a config.ini setting, since doing so would make things more complicated. Any thoughts?

**Comment by lahmann** [comment]
You are very much right and I could not think of a better way than the already mentioned options of having the caching made configurable via config.ini. So I went ahead and implemented your suggestion to add a KeyGeneratorTrait providing the getCacheKey() method and changed the ILS\Driver\AbstractBase accordingly to use this trait. I bound the usage of md5 to the environment setting as this will probably be the usual use case and because of the necessary additional complexity that needs to be added when making this configurable in config.ini (I think documenting it well will be sufficient).

What do you think? Does this do the trick?

**Comment by demiankatz** [comment]
This looks like a reasonable solution, but with one problem: the VoyagerRestful driver overrides formatCacheKey, but you have just renamed the method to getCacheKey in defining the Trait. I think we have a few possible solutions:

1.) Change the name of the method in VoyagerRestful to properly override it (creating a minor BC break)

2.) Change the name of the method in the Trait (maintaining backward compatibility, but using a less desirable method name -- I agree that "get" is probably better than "format" here).

3.) Use the feature of the 'use' method that allows renaming of methods to import 'get' as 'format' for the purposes of ILS drivers.

Option 1 is probably fine in this case given the relatively low likelihood of somebody locally customizing this method, but I present all the alternatives for your consideration. Let me know what you think!

**Comment by lahmann** [comment]
I opted for option 1 and committed the change - as formatCacheKey was introduced in March this year this minor back compatibility break hopefully won't cause too much trouble.

Out of curiosity: how would option 3 actually look like? I never thought of using `use` for renaming methods.

**Comment by demiankatz** [comment]
See this section of the PHP manual for using the "as" feature to rename trait methods and/or change their access levels:

http://php.net/manual/en/language.oop5.traits.php#language.oop5.traits.visibility

Regarding the relatively recent vintage of formatCacheKey, you're right that it probably won't have much impact if we change it. It's too bad it's in the 3.0.x series, though, since that makes it a bit more mainstream than if it had only hit master. In any case, @EreMaijala is the person most likely to be affected, if anyone -- Ere, do you have any objections to renaming the method in release 3.1?

**Comment by EreMaijala** [comment]
No objections, we can handle that. :) And the change makes sense.

**Comment by demiankatz** [comment]
Thanks, everyone. I've merged this -- and, after merging, caught and fixed one instance of "formatCacheKey" that slipped through the cracks.

**Pull request merged**
