### PR TITLE
Make autocomplete use a separate results list for each autocomplete f…

### PR DESCRIPTION
**Pull request by EreMaijala**
…ield so that it's aligned properly.

### CODE REVIEW

**Comment by EreMaijala** [comment]
This is continued from an issue noticed in #545. So the problem was that the autocomplete module created the results window only for the first field with the autocomplete flag and reused it in all autocomplete fields. In bootprint3 there is a hidden form in the results and the autocomplete window was bound to it. Now, this seems to fix it for me, but I started wondering whether it's appropriate to have any of the other settings global either. It probably doesn't hurt if all the autocomplete fields are for identical purpose, but if there happened to be two different fields on a page it would use same settings for both, as far as I can see.

**Comment by crhallberg** [comment]
Before we go in this direction, can you try my latest fix? It seems that [`.position()`](https://api.jquery.com/position/) is relative to a parent in some inconsistent ways, so I replaced it with [`.offset()`](http://api.jquery.com/offset/) in align. It goes relative to the document.

**Comment by EreMaijala** [comment]
Thanks, a quick test looks promising.

I see you added hiding of the results on window resize. In that case I suppose this is superfluous in setup(), right?

        $(window).resize(function() {
          align(input, element);
        });

**Comment by crhallberg** [comment]
Definitely superfluous, not sure how both versions got in there.

**Comment by demiankatz** [comment]
Looks like we can close this -- but please let us know if you run into any new problems!

**Pull request closed without merging**
