### PR TITLE
Offcanvas Menus

### PR DESCRIPTION
**Pull request by crhallberg**
First example of offcanvas menus, only in search results, with easy extension to other sidemenu'd pages in place.

Bootstrap Demo: http://getbootstrap.com/examples/offcanvas/ (shrink window to mobile size to see)

There are several issue to contend with, that need some design consideration.
1. The button isn't very prominent and remains at the top of the screen regardless of scrolling
2. Sidebar also remains at the top, regardless of scrolling
3. A `position:fixed` sidebar can still be longer than the height of the screen
4. Affix from Bootstrap is stuttery and not smooth on mobile
5. Swipe to expose menu
5. Non-JS phones?
6. Configuration

### CODE REVIEW

**Comment by crhallberg** [comment]
I really like that arrow, a really good solution.

**Comment by crhallberg** [comment]
Should I remove this PR since we have the feature branch?

**Comment by crhallberg** [comment]
Added configuration. If it passed the dreaded Demian Test, I'd be satisfied with this implementation.

**Comment by demiankatz** [comment]
Manually merged to master.

**Pull request closed without merging**
