### PR TITLE
deduplicates code in PAIA driver

### PR DESCRIPTION
**Pull request by olli-gold**
This PR cleans up the PAIA driver to deduplicate some code used in two methods

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks for this! At a glance this looks great, but I'll wait for @lahmann's blessing before merging (though I realize he's pretty busy right now -- if there's any urgency to merge this, I can give it a closer look myself and go ahead).

**Comment by olli-gold** [comment]
No urgency on this from my side, so I'm absolutely ok to wait for Andre's blessing :-)

**Comment by demiankatz** [comment]
Having taken a closer look at this, it seems pretty uncontroversial, unless we can come up with a more accurate name and/or comment for `getBasicDetailsMapping()`. I wonder if something like:

Map a PAIA document to an array for use in generating a VuFind request (holds, storage retrieval, etc).

might be slightly more accurate. (But it could also be completely wrong -- I don't really know this code very well). In any case, feel free to use or ignore that as you see fit.

**Comment by lahmann** [comment]
@olli-gold thanks for taking care of removing redundant code in the PAIA driver. No objections from my side.

Regarding Demians naming/comment suggestion, I think the suggested comment would make it a bit clearer what the method is about.

**Comment by olli-gold** [comment]
Thanks to both of you for your feedback. I have adjusted the comment as suggested by Demian and changed the method name to getBasicDetails(), which hopefully makes sense to you.

**Comment by demiankatz** [comment]
Thanks, everyone -- merged!

**Pull request merged**
