### PR TITLE
Fetch holds in VoyagerRestful driver from both the database (more inf…

### PR DESCRIPTION
**Pull request by EreMaijala**
…ormation) and API (includes Universal Borrowing request based holds).

So we found out that when a user has an arrived Universal Borrowing request, it shows up in the API as a local hold, but is nowhere to be found in the HOLD_RECALL table. To be able to show them in the holds list, fetch from both and combine the results.

### CODE REVIEW

**Comment by demiankatz** [comment]
Do you think it's worth including a VoyagerRestful.ini setting to indicate whether or not universal borrowing is being used, so we can avoid the extra API call if we know that it's not going to be necessary? Or alternatively, is there any advantage to merging the database results with API results, or would we be just as well getting everything from the API and skipping the database entirely? Or does the DB have data missing from the API?

Also, I wonder if it's worth including a deprecated getRemoteHolds() wrapper method to maintain API compatibility... I think odds are slim that anyone is relying on that method anywhere, but every time I think that I seem to get burned by an unexpected local customization somewhere. Even if we don't put in a backward-compatibility wrapper we should at least document the change in the changelog (which I'm happy to take care of if you think that's the best approach... which it probably is).

**Comment by EreMaijala** [comment]
Unfortunately the API doesn't provide some very useful fields such as bib id. Go figure. That's why the hybrid approach.

After thinking about it a bit I changed the mechanism so that now all holds including the remote ones are fetched from the Voyager database. Then if the hold array contains remote holds the API call is made and the results are augmented with information from the API. This way no configuration is needed and we get more information about the remote holds. The best way would of course be to connect to the remote databases but we don't have the credentials and that might become even more complicated.

I think documenting the change in the changelog is enough. It affects how the holds are fetched anyway, so it's something that's useful to be notified about if the functionality has been modified locally.

**Comment by demiankatz** [comment]
I thought it might be better to make the SQL setup for the new functionality more incremental, rather than completely copying and overriding the getMyHoldsSQL() method. This eliminates a lot of lines of code and also potentially makes it easier to disable this functionality based on a configuration setting, should there ever prove to be such a need.

I've just pushed up a commit (https://github.com/vufind-org/vufind/pull/657/commits/4efe141a208793af8fa46f19b37e88dd98f2270b) containing the simplification. Could you review/test and let me know what you think? We should be able to merge this if you're happy with that (and if you're not, we can certainly discuss other options).

**Comment by demiankatz** [comment]
Also took care of missing jquerymobile changes (though jquerymobile still has no ILL support... not worth spending time on until somebody needs it, of course).

**Comment by EreMaijala** [comment]
Thanks, Demian. Your version is much cleaner and seems to work great.

**Comment by demiankatz** [comment]
Thanks for checking!

**Pull request merged**
