### PR TITLE
Refactor pagination controls.

### PR DESCRIPTION
**Pull request by EreMaijala**
- Splits pagination templates so that each list entry is easier to customize.
- Adds classes and switches layout from table to flex for Bootstrap 5 compatibility.
- Fixes page_num translation.
- Fixes styling to use bootstrap's variables.
- Removes invalid role attributes.

### CODE REVIEW

**Comment by demiankatz** [comment]
@sturkel89, can you take a look at this one? It adjusts the way pagination controls are built, so we should do a visual and functional comparison of paginators between dev and this branch, across all of the themes.

The most obvious paginator is the one in search results, so I'd recommend looking there first as the easiest option. If no problems are found there, we should look at some of the more obscure ones:

- Try turning on the Demo driver and reducing the checked_out_page_size setting in config.ini so you can see multiple pages of checked out items.
- Similarly, historic_loan_page_size controls historic loans, but you'll also have to set enabled to true inside the [TransactionHistory] section of Demo.ini to see that option.

Let me know if you have trouble getting to anything... and @EreMaijala, please let me know if I'm forgetting any other important paginators! :-)

**Comment by sturkel89** [comment]
I am working on my review, and I've sidetracked myself with something I observe in all themes and in both test and dev. It might be something that is an option I could change in an .ini file; I don't know. All I know is that it works differently in Falvey Library's main VuFind instance, and I am not sure if what I see is by design or not.

In all themes, in both test and dev, **the start and end numbers appear at the ends of the paginator under only two circumstances**: _when I get my initial search results_, and _when I refresh the page_. Otherwise, as I scroll through results pages, the start and end numbers disappear. (In Villanova’s main VuFind instance, the start and end numbers are always visible.)

I like having the functionality of being able to jump quickly to the beginning and end of the search set and I think I’d prefer that they always be present. I don’t particularly like the design of having those numbers in square brackets. Can we do something different?  (I don’t have a good suggestion for what.)

### Upon page refresh:
image

### After clicking Next, Previous, or selecting a different page by clicking a number:
image

**Comment by demiankatz** [comment]
@sturkel89, if you set `load_results_with_js` to `false` in searches.ini, does that fix the behavior you describe? If so, it may be an issue introduced by the AJAX search functionality that hasn't gotten caught before.

**Comment by sturkel89** [comment]
> @sturkel89, if you set `load_results_with_js` to `false` in searches.ini, does that fix the behavior you describe? If so, it may be an issue introduced by the AJAX search functionality that hasn't gotten caught before.

**YES - when I changed that setting to 'false,' that fixed this issue!**

**Comment by demiankatz** [comment]
@EreMaijala, we've obviously gone off topic for this particular PR, but it sounds like there may be some issues to address with the AJAX search results. Can you investigate?

**Comment by sturkel89** [comment]
I found another bug that's related to **load_results_with_js** being set as 'true':

In all themes and in both test and dev, I've found that when a user sets **10** as the number of **Results per Page** they want to see, the dropdown display of **the number 10 disappears** as soon as you click 'Next' or select another page to display from the paginator. 

This happens immediately and consistently in every environment, as long as you're loading results with JS. As soon as you change that ini setting to 'false,' the 10 continues to appear.

I tried setting Results per Page to 1, 5, 10, 20, 40, 60, 100 -- and the only one I had trouble with was 10.

image

image

**Comment by EreMaijala** [comment]
It seems that the first/last navigation is my mistake. But I'm so far unable to reproduce the result limit problem. I'll keep trying.

**Comment by sturkel89** [comment]
> It seems that the first/last navigation is my mistake. But I'm so far unable to reproduce the result limit problem. I'll keep trying.

We figured out that the result limit problem emerged from my inadvertently including a space in my list of page length value options in searches.ini:

default_limit        = 5 
limit_options        = 1, 5, 10,20,40,60,80,100 

When I removed the space, the problem disappeared. 

Demian said "I think it is a bug, because those values should be getting trimmed or normalized to numbers, and this proves that they are not." 

I hope all these observations are helpful! (And I'll be more careful with my modifications to .ini files in the future!)

**Review by sturkel89 — COMMENTED** [review]
I reviewed the test branch vs. dev in all three themes. I have screenshots of EVERY permutation but will only include a subset here. This review will document each theme’s appearance on test, and will point out any critiques that I have. Everything functions properly and as expected.

### Results page paginator 

**SANDAL**
I like the new blue color of the Prev and Next labels/arrows. The paginator is otherwise sized, centered, and designed the same in test as in dev.

**First page**
image

**Non-first page**
image


**BOOTSTRAP3**
The paginator in this theme has been changed in test to look more like the sandal paginator. It is now centered on the page and no longer has outlines around each number and element. 

> **POSSIBLE FIX**: Without outlines, it isn't necessary to have the two **rounded corners** for the first and last element in the paginator. Every button could be a full square. I'm not sure that it's bad this way, but the rounded corners make more sense when you can see the overall shape of the outline of the element.

**Test - First page**
image

**Non-first page**
image

**Dev - First page**
image


**BOOTPRINT3**
Test and dev look pretty much identical, and function identically. The paginator is centered on the page. 

**First page**
image

**Non-first page**
image

### My Account area
**Checked Out Items** and **Loan History** seem to share paginator code. My screenshots are from the Checked Out Items area.

> **QUIRK**: I note the following quirk in all themes and in test and dev in the paginators in My Account. The paginator displays **unclickable options**, e.g., when you are on the first of multiple pages, the unclickable options **Prev** and **[1]** are displayed. These elements are subtly grayed out, but they are so small on the page that it’s difficult to see the color difference. When you mouse over the unclickable items, your mouse pointer becomes a universal NO symbol.
> 
> **SUGGESTED FIX**: These unclickable options are not displayed at all in the main paginator, and I don’t think they should be displayed here in the Checked Out Items area. Furthermore, I don’t think we need the [1] and [3] when there are only three pages to available on the list. Can those be suppressed when redundant, as in this case? (This might be a JIRA ticket item, not an item for this PR.)

**SANDAL**
**First page**
image

**Not first page**
image

**BOOTSTRAP3**
The paginator has been updated from dev in the same ways as it is in the results page paginator: it is centered and no longer has outlines. Good change!

**First page**
image

**Not first page**
image


**BOOTPRINT3**
**First page**
image

**Not first page**
image

**Comment by EreMaijala** [comment]
@sturkel89 The space issue in limit_options should be fixed now. Normally I'd say that we should minimize fixing of settings on the fly, but I added trimming since it used to work without JS results.

Also the missing borders and left alignment in bootstrap3 should now be back, and I implemented your suggestions of not displaying the disabled links and displaying first/last only when there are more than 3 pages.

**Review by sturkel89 — CHANGES_REQUESTED** [review]
Several comments:

1. Thanks for fixing the space issue in limit_options. I tested it, and the problem is gone!

2. Re: bootstrap3, the design and borders look good, but actually **I actually like it better with the paginator centered**. It’s the only theme without it centered and it looks weird to me left-justified. Not sure that we can make that decision in the context of this PR, but that’s my opinion. 🙂

3. I’m seeing your improvement of not displaying disabled links in every context. Thanks for that fix!

4. HOWEVER: I don’t know if it’s me, but I am still having the issue I reported above:

> In all themes, in both test and dev, on Firefox and Chrome, the **first and last numbers appear in the results page paginator under only two circumstances: when I get my initial search results, and when I refresh the page.** Otherwise, as I scroll through results pages, the start and end numbers disappear.

I see that first and last work properly, consistently, in the paginators in Checked Out Items and Loan History. But I think we need to make them work consistently in the main results page paginator. (Or is it me?)

**Comment by demiankatz** [comment]
@sturkel89, your last problem should be addressed by #3404, which @EreMaijala opened to fix that bug independently of the rest of the work here. Once we get that merged into this, everything should be solved.

(I hope to review #3404 later today but haven't gotten there yet. If you want to take a look in the meantime, please feel free!)

**Comment by EreMaijala** [comment]
@sturkel89 You're not alone in that I think the centered paginator looks better, but that's a change I didn't mean to do, so that's why I reverted it. I could be persuaded to still change it back..

**Comment by demiankatz** [comment]
@EreMaijala, I don't have strong feelings about centering (or not centering) the paginator. I think the intent of the bootstrap3 theme was to apply as little non-default styling as possible... so one argument could be to choose whichever approach leads to simpler CSS. But if both are equal, I'd probably go with centering for consistency with other themes.

**Review by demiankatz — CHANGES_REQUESTED** [review]
Now that #3404 is merged, there are some conflicts here. Can you resolve when time permits, @EreMaijala? After that, I think @sturkel89 can do another (hopefully final) test.

**Comment by EreMaijala** [comment]
Merged. And I decided to center the pagination in bootstrap3 as well so it doesn't need to be handled in the other themes (resulting in a few less lines of style code).

**Review by sturkel89 — APPROVED** [review]
I've looked at the test branch in all three themes, and checked out the results list paginator and the paginators in the My Accounts area. 

Everything looks good and functions well! I think we are ready to merge.

**Review by demiankatz — APPROVED** [review]
Thanks, @EreMaijala and @sturkel89!

**Pull request merged**
