### PR TITLE
Adds missing sr-only text to exclude facets

### PR DESCRIPTION
**Pull request by ckaz**
The exclude switches in the side facets are not accessible since the icon is hidden, they appear as empty links to screen readers. I've added sr-only text.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @ckaz. I see that we still have the same text in the title attribute, which I imagine is still valuable for the purpose of providing hover text for sighted users... but will this cause any problems with double-reading for screen reader users?

**Comment by ckaz** [comment]
@demiankatz you are right of course, my oversight. will submit correction asap

**Comment by crhallberg** [comment]
My understanding is that title is not read by screen-readers: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title

**Comment by ckaz** [comment]
@crhallberg Erm, yes and no. While some screen readers ignore the title completely, others read it, in some cases in addition to the anchor text. Therefore I'd suggest we remove the title and rely on the anchor text as best practice. 
There is a report at deque (https://www.deque.com/blog/text-links-practices-screen-readers/) saying.
> **Results with JAWS 2020 / JAWS 2019**
> **JAWS** behaves identically across Chrome, Firefox and Internet Explorer with the **identical title** in Case B being **ignored**.
> The only failure noted is with Microsoft Edge: JAWS simply fails to read the title attribute for all the four links.
> 
> **Results with NVDA**
> With Internet Explorer, NVDA does not expose the title attribute for any of the links.
> **NVDA reads** the **identical title text** (Case B) **when using Chrome or Edge**. The user experience with Firefox is better as previously updated in 2015
> 
> **Results on Mobile Devices**
> No change in VoiceOver behavior.
> **TalkBack repeats the identical title text with Chrome** on the Pixel with Android 10

A similarly erratic situation was reported by our accessibility testers several years back.

**Comment by demiankatz** [comment]
Addressed by #1609. Closing now.

**Pull request closed without merging**
