### PR TITLE
Add ability to send referrer with feedback form

### PR DESCRIPTION
**Pull request by xmorave2**
This little enhancement adds ability to send referrer in feedback form (turned off by default)

### CODE REVIEW

**Comment by demiankatz** [comment]
This makes sense to me; since @samuli has developed most of the feedback form functionality, I am requesting his review in case he has any suggestions or concerns.

**Comment by samuli** [comment]
@xmorave2 @demiankatz This looks good to me.
This could also be a good time to add support for hidden fields so that the 'referrer' field wouldn't need a special case in the template? We would also need a way to pass request (and possibly other) parameters from `FeedbackController` to `Form`. Something like this: 
https://github.com/vufind-org/vufind/compare/master..samuli:feedbackFormReferrer

**Comment by demiankatz** [comment]
Thanks, @samuli, that seems like a good way to make the code even more flexible. What do you think, @xmorave2?

Also note that this comparison link might be useful:

https://github.com/xmorave2/vufind/compare/feedbackFormReferrer...samuli:feedbackFormReferrer

(This shows what @samuli changed from @xmorave2's original version, and could be used for @xmorave2 to create a secondary pull request and then merge the changes into this existing PR if desired).

**Comment by xmorave2** [comment]
@demiankatz @samuli I do like it, so I merged these changes here
Thanks

**Comment by demiankatz** [comment]
Great! Merging to master now.

**Pull request merged**
