### PR TITLE
Searchbox Placeholders

### PR DESCRIPTION
**Pull request by crhallberg**
Configuration section added: [SearchPlaceholders] in config.ini.

### CODE REVIEW

**Comment by demiankatz** [comment]
I haven't tested this out yet, but it looks like a great start. A few thoughts/comments:

1.) Do we need a mechanism for a default placeholder, in case users don't want to define these in a backend-specific way? -- e.g. "Enter search terms here" would work for anything.

2.) What do we want VuFind's default configuration to be? The examples currently turned on in this PR are fine for testing, but I don't think we would want those to be out-of-the-box settings.

3.) If we implement a setPlaceholderText() method to the searchbox helper, that would theoretically allow the search tabs template to modify the placeholder text based on the active tab in a very simple way. I'm not in love with that approach, as it's a bit "magical" and side-effect-driven. However, in a pinch, I think it would work if we couldn't come up with anything better.

**Comment by ckaz** [comment]
re: 2.) I'd be in favour of an empty default, i.e. no placeholder. We had placeholders but our "Usability Group" decided against them mainly because it was felt that they added more clutter to an already full interface.

**Comment by crhallberg** [comment]
I'm not sure if the use of [getActiveTab](https://github.com/vufind-org/vufind/blob/master/themes/bootstrap3/templates/Recommend/SwitchTab.phtml#L7) ([defined here](https://github.com/vufind-org/vufind/blob/master/module/VuFind/src/VuFind/Recommend/SwitchTab.php#L118)) would be more appropriate than passing 'selected' as a top level index in the tab config array.

**Comment by demiankatz** [comment]
I think it might be a good idea to adjust the structure of the tab data so that at the top level there are simply 'selected' and 'tabs' keys, rather than mixing the special-case 'selected' key in with the array of tab information.

I still think it may be worth adding a configuration setting for a default placeholder that does not require backend-specific configurations (in case somebody wants a single placeholder across all backends).

It looks like this code should be able to support configuring placeholders for filtered tabs. Have you tested this scenario? If it works, we may want to update the config comments.

**Comment by EreMaijala** [comment]
How about translation support?

**Comment by demiankatz** [comment]
Sorry, should have caught that -- escaping is important too. Fixed here: https://github.com/vufind-org/vufind/commit/4418a209ab9e016ac579c907670536ff0d3533b4

**Pull request merged**
