### PR TITLE
Added support for getRequestBlocks() and getAccountBlocks() to the Mu…

### PR DESCRIPTION
**Pull request by EreMaijala**
…ltiBackend driver.

### CODE REVIEW

**Comment by demiankatz** [comment]
A couple of questions:

1.) Since these two new methods are essentially the same except for the method name, would it make sense to abstract to a shared support function? Are there other existing calls that follow the same pattern that might allow the whole class to be reduced/simplified?

2.) Since this is an optional method, does it make sense to throw an exception when it is unsupported? Would it be better to default to false? Or is that exception just a safety check in case of unexpected behavior, and the normal support checking should prevent this from being called at inappropriate times? (Sorry, can't remember all the implementation details at a glance).

**Comment by EreMaijala** [comment]
1.) They are similar, but I can't see anything else quite like them. I decided to keep them separate, but I can change that tomorrow. There's at least one thing that could be done for almost all: create a getSourceAndDriver() method that would return both, since that's done in the beginning of most methods. 

2.) Now fixed so that if driver is not found, an exception is still thrown (this obviously shouldn't happen), but if the driver doesn't support the method, it will return false.

**Comment by demiankatz** [comment]
Thanks for the work. I think this is fine to merge as-is. If you feel like taking time to refactor/reduce code, feel free to open another PR... but I imagine you have other priorities at the moment!

**Comment by EreMaijala** [comment]
Thanks. I'll put that on my TODO list.

**Pull request merged**
