### PR TITLE
Create hy.ini

### PR DESCRIPTION
**Pull request by tigran54**

### CODE REVIEW

**Comment by demiankatz** [comment]
@tigran54, can you merge the changes from this PR and #2167 into the patch-1 branch created for #2166? I think it would be easiest if all the work related to this localization was included in a single pull request, so it could all be merged at once. Please let me know if I can be of any help in setting this up for you.

**Comment by tigran54** [comment]
> @tigran54, can you merge the changes from this PR and #2167 into the patch-1 branch created for #2166? I think it would be easiest if all the work related to this localization was included in a single pull request, so it could all be merged at once. Please let me know if I can be of any help in setting this up for you.

How should I proceed with merge?

**Comment by demiankatz** [comment]
@tigran54, if you use Git on the command line, I would suggest doing something like this:

<pre>
mkdir vufind
cd vufind
git clone https://github.com/tigran54/vufind .
git checkout patch-1
git merge origin/patch-2
git merge origin/patch-3
git push
</pre>

This should create a new clone of your Git repo in a directory called vufind, then take all of the code changes from your patch-2 and patch-3 branches and add them to the patch-1 branch. This will update your first pull request so that all the changes are in one place, and then we can close the other two. As you do further work on the translation, you can commit them to patch-1 and push them up there, and the pull request will be automatically updated. When the work is done, we can merge it from there all at once.

If you have not worked with Git before or have questions about any of this, please let me know and I'll be happy to help as best I can!

**Comment by demiankatz** [comment]
@tigran54, just wanted to follow up and see how things are going with this project. If you need help combining the pull requests together and don't mind giving me write permission to your VuFind repository fork, I'm happy to help!

**Comment by demiankatz** [comment]
Thanks, @tigran54 -- I was able to merge this PR and #2167 into #2166. Please edit the files in #2166 if you want to make changes and additions, and let me know if you need any more assistance along the way!

**Pull request closed without merging**
