### PR TITLE
Primo config and connector tweaks

### PR DESCRIPTION
**Pull request by EreMaijala**
This pull request contains the following changes to the Primo connector:

1.) Replace apiId and port in Primo.ini with a url.
2.) Upgrade action to accomplish the above.
3.) Fixes for the connector so that it doesn't hide important exceptions like connection errors but still returns an empty set for an empty search.

### CODE REVIEW

**Comment by demiankatz** [comment]
This looks good to me. I just added a test case for the config upgrade. I'll pass this along to a couple of other known Primo users for comment, then merge if everyone is happy.

**Comment by demiankatz** [comment]
I've gotten thumbs up from everyone, so I'll merge this after the dev call today.

**Comment by EreMaijala** [comment]
Thanks! Oh, by the way, I can't attend today, sorry!

--Ere

5.1.2016, 15.51, Demian Katz kirjoitti:

**Comment by demiankatz** [comment]
Merged!

**Pull request closed without merging**
