### PR TITLE
Add configurable alphabrowse row highlighting.

### PR DESCRIPTION
**Pull request by hackmastera**
Use new additions to browse-handler API. Replaces #255.

### CODE REVIEW

**Comment by hackmastera** [comment]
I'd still appreciate any opinions on the changed signature of getAlphabeticBrowse in VuFindSearch/Backend/Solr/Backend.php.

Meantime, I'm going to look at validating the config values.

**Comment by demiankatz** [comment]
Anna,

A few comments:

1.) Could you run: `cd $VUFIND_HOME; php public/index.php language normalize languages` to sort the language file into the correct order?

2.) Regarding the changed signature, it would be more backward-compatible to put the new parameter at the end of the list, though I realize that logically it feels better earlier. Perhaps $offset should be renamed $offsetDelta, which might also improve readability slightly. And maybe $offsetDelta doesn't feel so out of place at the end of the parameter list compared to $offset (which feels like it has to be next to $limit). What do you think?

thanks,
Demian

**Comment by hackmastera** [comment]
That sounds great, Demian. I've added some new commits. I think this amount of config validation is sufficient. I also made the other changes you requested.

**Comment by demiankatz** [comment]
Thanks, Anna. I should be able to give this a close review early next week. The other thing we're going to need to do is port template support into blueprint and jquerymobile themes for consistency. If you don't have time for that, Chris and I can do it on this end -- but it might be helpful for us to have write access to this branch in that case.

**Comment by hackmastera** [comment]
I will look at it. I thought blueprint had been deprecated?

**Comment by demiankatz** [comment]
We're probably going to deprecate blueprint with the next release and make bootstrap3 the default theme at that time... but for now we're still fully supporting it since so many people are still using it in the wild. It was easier to get rid of the older bootstrap theme since that never came out of "experimental" mode.

**Comment by hackmastera** [comment]
Hey Demian, I added the theming for blueprint but I don't know whether I'll have time to look at jquerymobile. Can you do a pull request against this branch? If not I will look at adding permissions for y'all. Thanks!

**Comment by demiankatz** [comment]
Sure, one of us can do a PR if that's easier. Thanks!

**Comment by hackmastera** [comment]
Awesome. I am excited for nested PRs!

**Comment by hackmastera** [comment]
Oh also, I wanted to ask if Chris could check the color I chose for the highlight box in the blueprint theme. It was somewhat arbitrary and my gut says it looks weird. Thanks!

**Comment by demiankatz** [comment]
Sure, I'll check with him next time we talk. Given impending weather, it might not be as soon as it otherwise would be!

**Comment by demiankatz** [comment]
Anna,

I haven't had a chance to talk to Chris yet, but I thought the highlighting looked okay. I've fixed a handful of minor bugs, merged in the latest master diffs, and added jquerymobile support. You should have a new pull request on your branch that you can merge in to update this one! Review of my diffs would be appreciated in case I've broken/missed anything.

thanks,
Demian

**Comment by demiankatz** [comment]
Thanks! I've manually merged this to master (to flatten the long history).

**Comment by hackmastera** [comment]
Awesome. Thanks, Demian!!

**Pull request closed without merging**
