### PR TITLE
Missing translation for previous

### PR DESCRIPTION
**Pull request by lahmann**
Translations for "Previous" as it is used in the template Helpers/paginator.phtml were missing for German language. I added those.
Is this translation missing in other languages as well?

### CODE REVIEW

**Comment by crhallberg** [comment]
Thank you for this. If you're in development mode for VuFind, you can checking missing for missing or extra translations via the `/devtools/language` web address.

**Comment by demiankatz** [comment]
Before we merge this, let's have a quick conversation....

**Comment by demiankatz** [comment]
I think it's possible that "Previous" was added to a template by accident at some point in the past, because originally all of the pagination said "Prev."

**Comment by demiankatz** [comment]
We should look into whether there is any reason to have translations for both "Prev" and "Previous" or if we should just pick one and use it consistently.

**Comment by demiankatz** [comment]
If we need both, we can use the language copy tool to duplicate the existing "Prev" translations to "Previous" in existing language files so that none is incomplete. If we don't need both, we should make sure that templates and language files all consistently use the same single term.

**Comment by lahmann** [comment]
I'm good with either solution - I didn't want to alter the template strings just because of missing translations. But if "Previous" was intented to be a "Prev" I am completely fine with it. :)

**Comment by crhallberg** [comment]
It may be clearer for our translators to convert all instances of Prev to Previous.

**Comment by demiankatz** [comment]
Since 'Previous' was used in a narrow edge case and 'Prev' was used in a lot of places, I changed 'Previous' to 'Prev' here for consistency: https://github.com/vufind-org/vufind/commit/31776fe519d8f432478c1c89e9ea6871d2eeb2a4 -- we can always update the translation in en.ini if we prefer using the full form of the word. In any case, that renders this PR unnecessary, so I'm closing it now. Thanks, @lahmann, for bringing this issue to our attention!

**Pull request closed without merging**
