### PR TITLE
adds suggestion module to change the search tab for nohits

### PR DESCRIPTION
**Pull request by olli-gold**
In addition to PR #562 I have another PR concerning the same topic: if a query returns no hits and VuFind is having search tabs configured, it makes sense to suggest using another search tab. This is implemented in this PR.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks for this -- definitely makes sense. However, a couple of issues:

1. Travis is complaining because you're missing a doc comment on one of your functions; presumably that's easy to fix.

2. More serious: we recently refactored the search tab helper. See https://github.com/vufind-org/vufind/commit/d3a59fbdd276aa816e2d95b7509e2d80290615f7 for the most important details. Unfortunately, it looks like your code is written for the old version of the helper, when everything went through __invoke(). It will need to be changed to use getTabConfig() instead. I also wonder if it might be even cleaner to add a getTabConfigForParams() convenience method that wraps getTabConfig() so that your templates can be simplified.

Let me know if I can be of any further assistance!

**Comment by olli-gold** [comment]
Thank you for your feedback and the hint about the refactored search tab helper - sorry, I did not see that. I'll have a look at this tomorrow and will see how it affects my PR. Simplification of the templates is a very good plan; they are really bad...

**Comment by demiankatz** [comment]
Thanks! Hopefully it won't be too dramatic a change, but let me know if you have any questions!

**Comment by olli-gold** [comment]
I have improved my implementation and hope its now ready to get merged.

**Comment by demiankatz** [comment]
I made a few more minor adjustments and merged this to master. Thanks again!

**Comment by olli-gold** [comment]
Great, thank you!

**Pull request closed without merging**
