### PR TITLE
Few clean ups in language files

### PR DESCRIPTION
**Pull request by samueloph**
I know this is a rather useless commit, but I had a few minutes free-time and thought you could find this usefull.

Please note that if you think there's no need to make this changes, you can close this PR.

I've removed some double whitespaces and one case of triple whitespace of each translation files.
Also removed one unecessary whitespace in the form of "\<tag\>text\[whitespace\]\</tag\>".
And made consistent "email" spelling for all the languages.

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks for this. It definitely never hurts to clean up/normalize whitespace. Regarding the spelling of email/e-mail, are you familiar enough with these languages to know whether the normalization is valid? Is it possible that in some cases the inclusion of the hyphen is preferred or semantically significant?

**Comment by samueloph** [comment]
Thanks Demian!

I'm not 100% sure that changing from "e-mail" to "email" won't change the semantic, I searched it on the web and found nothing regarding this type of thing, I think this is very unlikelly to happen though. Anyway, if there's doubt, maybe you want to keep it that way or wait for the translators to confirm.

Maybe someone with experience on linguistics can give a help, but I don't know any case where a foreign word can or has to be modified in such a way.

Or I can only change the ones which I'm 100% sure that have no problem in using "email", that would be the Latin ones:
pt
fr
it

And the germanic languages that we know it uses "email":
en
en_gb

Which gives us the ones we don't know if its ok (though being very unlikelly):
tr (has "e-mail" only in 3 strings)
ru (has "e-mail" in some strings, "email" in others)
pl (has "e-mail" in some strings, "email" in others)
nl (has "e-mail" in some strings, "email" in others)
cs (has "e-mail" in some strings, "email" in others)

**Comment by demiankatz** [comment]
Do any of the languages consistently use "e-mail" in all contexts? If so, I'd leave those alone, and I can make a note to ask the translators. If the others all have a mix of "email" and "e-mail" then I would be pretty comfortable with normalizing to "email" for consistency.

**Comment by samueloph** [comment]
All the 6 languages that I'm not familiar with (tr, ru, pl, nl, cs) have a mix of "email" and "e-mail". The other ones I'm sure the change is ok.

So is it ok to change?

**Comment by demiankatz** [comment]
Yes, I think that makes it pretty safe. Thanks for double-checking!

**Pull request merged**
