### PR TITLE
Replace "retain filters" checkbox with "reset all filters" button.

### PR DESCRIPTION
**Pull request by demiankatz**
This PR intends to replace a confusing and hard-to-maintain UI control with something simpler that the user can better understand and that will introduce fewer regressions in future.

TODO
- [x] Implement basic control
- [x] Style button (be sure to address both responsive contexts in which it appears)
- [x] Eliminate basic_search_keep_filters language string if no longer needed
- [x] Make sure new control works correctly in collection view as well as regular search results
- [x] Test edge case behavior: when all default filters are removed, reset button should appear and restore defaults
- [x] Fix bug: NOT filters displayed on record page do not re-apply correctly (they convert to AND filters).
- [x] Write appropriate tests
- [x] Make sure full test suite passes
- [x] Update changelog when merging

### CODE REVIEW

**Comment by ckaz** [comment]
Dear all,
just tested this locally and it works very well. Only the button is still lacking in buttonness, for my taste, across the Sandal and BS3 themes on all devices widths. Thanks for the good work!

**Comment by demiankatz** [comment]
Thanks, @ckaz, glad that this is working for you. @crhallberg is trying to make the button styling "lighter" (see also #1379), but I tend to agree that it may be slightly too subtle now. Do you have any suggestions for improvement? Maybe we can find a compromise that all three of us are happy with.

**Comment by ckaz** [comment]
I agree that the header looks a little too heavy or buttony. So I guess the other way round would make more sense.

Maybe the following: If we removed the button styles from the "Remove filters" and from the dropdown (4 filters or more) and kept the font-weight of the selected other filters at "normal". Then the "Remove filters" would stand out enough without vying for attention with the search button, like so
vf-remove-filters

**Comment by EreMaijala** [comment]
We once toyed with the idea of providing a "Apply previous filters" button when current filters are not retained. In the new design it could be provided as a counterpart to "Reset filters". We never actually did any usability testing with it, so it could also be a complete disaster, but I just wanted to throw the idea in the air.

**Comment by demiankatz** [comment]
@EreMaijala, sounds like something that would not be terribly difficult to implement technically, if the usability research suggests it's worth doing. Feel free to open a PR if you ever think it's worth the effort!

**Pull request merged**
