### PR TITLE
Refactored search table handling so that existing searches are update…

### PR DESCRIPTION
**Pull request by EreMaijala**
…d instead of deleting and creating new ones.

Fixed duplicate search elimination to not consider extra url parameters such as page.
Added a simple checksum to search table rows so that duplicate elimination does not have to go through potentially all searches in current sessions history.
Added a database upgrade that adds checksums to saved search rows.

### CODE REVIEW

**Comment by demiankatz** [comment]
In testing this, I noticed one odd little quirk that we might want to address: the search history page displays a date and time for each search. This comes from the stored search object. In the old code, this time updates when you repeat a search because the object is rewritten. In the new code, it gets locked at the time of the first instance of the search. This can result in an apparently out-of-order history. Do you think we should revise the templates to pull the date/time from the created field, now that it is all available there?

Also, have you confirmed that the upgrade script correctly modifies the `created` field in MySQL? I can set up a test for that if you haven't already done so -- this is not a common sort of database modification, so I just want to be sure the upgrade will go smoothly before I run it on my main test instance.

**Comment by EreMaijala** [comment]
I thought about this and realized that also the result count should be updated so I added updating of search_object to saveSearch(). Now it works like it did before, I believe, so there's no need to change the templates or controller code. I'm still not quite sure if it makes sense to treat saved searches differently, though, but that's a case for another place.

**Comment by EreMaijala** [comment]
The modification of created in MySQL has been tested was works great, but I haven''t tested the PostgreSQL scripts.

**Comment by EreMaijala** [comment]
I added one more commit that fixes fetching of searches by session id. This is not really related to the table change but fitted here. The issue was that PHP doesn't necessarily recreate a session id when the session is ended but reuses the existing one, and without the check any searches saved during the previous session were still visible after logout.

**Comment by demiankatz** [comment]
This is looking pretty good. Just two questions:

1.) Did you consider adding a database index on the checksum field to boost performance, or does the write penalty outweigh the read benefit?

2.) Is there a particular reason that you separated the `get_class($dupSearch) == get_class($newSearch)` and `$oldUrl == $newUrl` conditions? It seems that your code (which introduces a 'continue' statement) is functionally equivalent to the old code, but slightly longer. I'm tempted to revert this, but wanted to see if there's a reason for it that I'm overlooking.

I'm going to keep testing a little longer, but barring any unexpected problems (which I'll comment about if I find them) I expect I'll merge this tomorrow.

**Comment by demiankatz** [comment]
Okay, clearly I spoke too soon, because I found an unexpected problem immediately after posting my last comment. :-)

It appears that when a search is rewritten, the search ID is lost. Try this:

1.) Perform a search for "test"
2.) Go to search history and hover over the save link -- there's an ID in the save parameter
3.) Perform a search for "test" again
4.) Return to search history and hover over the save link again -- the parameter is empty now, and clicking on it will result in a fatal error.

Note that this problem appears to be somehow unique to search history, as the save links embedded within the search results work just fine regardless of whether this is a new or reused search object.

Let me know if you need help investigating this -- I'm short on time right now but might manage to squeeze it in tomorrow or Saturday if necessary.

**Comment by EreMaijala** [comment]
Oops. Now that the search_object of the existing search is updated, its id must be retained. Fixed now. Regarding your questions:

1.) I did, but checksum may not be that unique without session_id or user_id which means we'd need two composed indexes, which is probably not worth it (I haven't benchmarked it though). MySQL is't good at using two or more indexes at the same time, so creating an index just for checksum wouldn't be very useful. This can of course be revisited if necessary.

2.) Yes, this avoids creating $oldUrl at all if the classes don't match. Building the query string is a relatively heavy task, so avoiding it when possible is useful. That said, I'm not sure how often the checksums will clash between classes, but since it's guaranteed non-unique it might happen. If, however, you feel the previous more simple code is better, I'm ok with that.

**Comment by demiankatz** [comment]
Thanks for the fix and the clarification. Your choices make sense in both cases (and I really should have noticed the moved initialization of $oldUrl!). I'll give this a few more tests later today just to be on the safe side, and will merge as-is assuming I encounter no further problems.

**Comment by demiankatz** [comment]
Manually merged to master. Thanks!

**Pull request closed without merging**
