### PR TITLE
New Captcha with Lansoweb's Zend Captcha

### PR DESCRIPTION
**Pull request by crhallberg**
Upgrade to the latest Captcha version using a Zend library collaborated on here: https://github.com/Lansoweb/LosReCaptcha.

This PR replaces #276.

### CODE REVIEW

**Comment by demiankatz** [comment]
First round of comments:

1.) I see that privateKey/publicKey have been replaced with secretKey/siteKey. I understand this probably brings us more in line with Google's terminology, which is fine, but we need to either retain backward compatibility with the old configurations or else we need to make the UpgradeController do the work of migrating the data. If the old values are incompatible with the new values, at very least we need the UpgradeController to issue a warning if it encounters the old settings.

2.) Similarly, we might want the upgrade script to deal with obsolete themes in some fashion.

3.) The old code seemed to have pretty good internationalization support. The new code seems to lose this. Is there any way we can get it back? Do we need to remove some obsolete strings from the language files?

4.) The ReCaptcha view helper seems to be ignoring the $useRecaptcha parameter. Is this truly no longer needed, or does that support need to be restored? We should either make it work or make it go away completely.

5.) Looks like the change to index.php was committed by accident.

6.) There are a lot of changes in here that have to do with a composer update rather than this particular branch. We should probably update dependencies on master soon and merge it to simplify the file count on this PR! I'll try to remember to take care of that in the near future.

**Comment by demiankatz** [comment]
Chris,

I've taken care of item 6 by updating master dependencies and re-merging. The remaining issues still stand, as far as I can tell.

Thanks!

**Comment by crhallberg** [comment]
Took care of those comments. As far as 2. goes, blueprint is all set as I didn't make changes to the template interface, although I did add the proper alignment in bootstrap3.

**Comment by demiankatz** [comment]
Looking good. Two remaining things:

1.) I think there's still a Service/recaptcha.phtml file in the root theme. Can we get rid of that too?

2.) Perhaps we should ask for a new losrecaptcha release to be minted so we don't have to have a dev-master dependency in the composer.json. But best to save that for very last, so we don't have to ask multiple times if we find any last-minute bugs that require further pull requests. (I don't expect that to happen, but I'm going to do one last round of testing right now).

**Comment by demiankatz** [comment]
Okay, testing done. Looks good. Let me know your thoughts on the points above, and we can merge as soon as those last things are settled.

**Comment by demiankatz** [comment]
Manually merged to master (with new losrecaptcha release incorporated).

**Pull request closed without merging**
