### PR TITLE
Make it possible to style differently OR and AND facets

### PR DESCRIPTION
**Pull request by liowalter**
Feel free to use other class names if you prefer for consistency ;-)
Thanks !

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks, @liowalter; this makes sense to me but I'd like to hear @crhallberg's thoughts too.

**Comment by demiankatz** [comment]
@crhallberg, it looks like `.facetOR` was used in the past but got lost in refactoring. There's this line of LESS that currently has no effect, but might introduce a side effect with these class name changes:

https://github.com/vufind-org/vufind/blob/c61a1b5d5019ec681b25a7ed6c402ca11d07205b/themes/bootprint3/less/bootprint.less#L149

Should we remove that LESS as part of this PR? Or am I missing something, and it serves a current purpose?

**Comment by crhallberg** [comment]
That code should be legacy for sure. I checked to make sure `.facetOR` isn't used in the JS anymore and it looks like that part was removed.

**Comment by demiankatz** [comment]
Thanks @liowalter for the idea and @crhallberg for the confirmation about the legacy LESS. I've removed the obsolete line from the bootprint3 theme and recompiled the CSS. I'll merge this now!

**Comment by liowalter** [comment]
Thanks !

**Pull request merged**
