### PR TITLE
Add missing doublequote to attribute

### PR DESCRIPTION
**Pull request by dltj**

### CODE REVIEW

**Review by EreMaijala — APPROVED** [review]
Thanks for catching that one!

**Comment by demiankatz** [comment]
Thanks, @dltj and @EreMaijala! I thought we were going to have to backport this to release-9.1, but I see that I was fortunately mistaken! :-)

**Comment by dltj** [comment]
I think the backport is needed...I found this in [9.1](https://github.com/vufind-org/vufind/blob/v9.1/themes/bootstrap3/templates/Auth/ILS/loginfields.phtml#L5) and [9.0.3](https://github.com/vufind-org/vufind/blob/v9.0.3/themes/bootstrap3/templates/Auth/ILS/loginfields.phtml#L5).

**Comment by demiankatz** [comment]
Thanks for double-checking, @dltj! When I looked at the commit that introduced the bug, the tags in GitHub indicated that it was only in the dev branch and not in any release tags... but that appears to be incorrect! I've now backported this to release-9.1 as 2de49b5ab754569f3a5fc3936131796c4cabb615. There won't be any more 9.0.x releases, so I didn't backport further than that.

**Comment by demiankatz** [comment]
...and now GitHub _is_ showing the tags, so either I missed them the other day, or there was a momentary technical fault. :-)

**Pull request merged**
