### PR TITLE
Smarter CSRF handling.

### PR DESCRIPTION
**Pull request by demiankatz**
- Do not create multiple tokens per request.
- Clear tokens after successful verification to save session space.
- Limit the number of tokens that can be generated before successful verification.

(This is designed to address the problem that repeatedly accessing the login page can cause unreasonable session growth due to endless generation of new CSRF tokens).

### CODE REVIEW

**Comment by EreMaijala** [comment]
Is there a reason not to keep the last $maxTokens tokens? I.e. array_slice them from the overflown array to be safe?

**Comment by EreMaijala** [comment]
I'm also a bit worried that if session->tokenList is used in several places and the underlying implementation is changed, this won't work anymore. How about inheriting a VuFind CSRF class from the Zend one and putting the functionality there? At least it would be in one place..

**Comment by demiankatz** [comment]
Thanks, @EreMaijala, I've incorporated all of your feedback. I was reluctant to subclass Zend\Validator\Csrf simply because I was trying to keep things simple, but you're right that it is better this way -- it enables me to write a test class to catch future regressions if the Zend code changes. Let me know if you see any remaining issues; once you're satisfied with this, I'll merge it.

**Comment by EreMaijala** [comment]
@demiankatz Looks good to me. Thanks!

**Comment by demiankatz** [comment]
Thanks, @EreMaijala -- merged now.

**Pull request merged**
