### PR TITLE
autocomplete.js

### PR DESCRIPTION
**Pull request by crhallberg**
A custom, lighter autocomplete solution that removes the woes that typeahead.js caused.

### CODE REVIEW

**Comment by demiankatz** [comment]
It looks like you add an autocomplete.css file in your theme configuration, but no such file exists. Is that an error or am I missing something?

**Comment by crhallberg** [comment]
I did forget a few files, sorry.

**Comment by EreMaijala** [comment]
While at it, can I request that a delay be added to the input handling? The current autocomplete mechanism hammers the server with a request after every character when a user is typing or backspacing, and adding a small delay would alleviate this.

**Comment by crhallberg** [comment]
Sorry it's so late in the day, I almost missed the email. I added a default but configurable ajaxDelay of 200 ms.

**Comment by demiankatz** [comment]
I just tried this out on my test server, and it's not working for me at all. It appears that the autocomplete requests sent to the server lack the "searcher" and "type" parameters, so no suggestions come back. Perhaps this is caused by some interaction of other settings on my system, but something is definitely wrong somewhere. Let's take a look at this next time we're both in the office at the same time. Thanks!

**Comment by crhallberg** [comment]
I found the error, after a recent change, `this` in the setup code was referring to the autocomplete plugin instead of the input, so the class parameters weren't being parsed.

**Comment by demiankatz** [comment]
This seems to be working for me now. Two questions:

1.) Is autocomplete.css necessary? Would it be better to put this in the LESS with the rest of the styles?

2.) Would it make sense to cache results so we don't hit the server again for the same thing if the user switches back and forth between search handlers or backspaces? (Not sure how best to limit the size of the cache, so maybe this is a bad idea -- but it seems like it might reduce HTTP traffic).

**Comment by crhallberg** [comment]
We could constrain the cache to the current word, so if the search bar is cleared or drops below the minimum length we clear it. I don't think we could maintain the cache between search types unless make it really VuFind specific...

... which is the reason for the separate autocomplete.css. I was considering putting this out as a library, but it need not be the case in our implementation.

**Comment by demiankatz** [comment]
Regarding the caching issue, perhaps this should be addressed from a different angle: I notice that right now, the AjaxController::output() method always forces no-cache HTTP headers. If we added a parameter to output() to allow different cache settings (even a 10-minute cache would solve most problems related to autocomplete) we might be able to address this at the HTTP level without changing your code at all. Worth experimenting with, anyway!

Regarding the CSS, is it possible to keep autocomplete.css as a separate file but simply include it into compiled.less so that we maintain the logical separation but don't have to introduce a separate HTTP request to retrieve a separate file on the client end?

**Comment by crhallberg** [comment]
I saved the .css for my potential release. I can play around with caching within the plugin, which would be faster and least hammer-y.

**Comment by demiankatz** [comment]
Should we roll back the AjaxController changes here since they don't seem to be doing anything? (If you think it's worth keeping them, then we need to add a doc comment to prevent a style issue).

Are there any other outstanding issues here?

**Comment by crhallberg** [comment]
I reverted them. Disappointed this didn't work, we could use the boost for cover images.

**Comment by demiankatz** [comment]
It might be worth trying something similar for cover images -- that's a whole separate file. Let me know (outside of this PR, so we don't go wildly off topic) if you need/want the gory details.

**Pull request merged**
