### PR TITLE
Migrate from Zend to Laminas

### PR DESCRIPTION
**Pull request by demiankatz**
TODO
- [x] Deal with deprecated code (zendrest, zendservice-amazon) -- not a blocker for merging this PR; tracked by [VUFIND-1284](https://vufind.org/jira/browse/VUFIND-1284).
- [x] Investigate implications of using ZfcRbac (see https://github.com/ZF-Commons/zfc-rbac/issues/391) -- not a blocker for merging this PR; tracked by [VUFIND-1380](https://vufind.org/jira/browse/VUFIND-1380).
- [x] Replace zf2-whoops with a Laminas-based whoops library
- [x] Check for stray Zend / ZF2 references
  - [x] Fix non-backward-breaking references
  - [x] Fix EDS module (Zend2 class)
  - [x] Fix Summon module (Zend2 class)
  - [x] Fix TabManager ($zendConfig property)
- [x] Update VuFind libraries to Laminas, where appropriate.
  - [x] VuFindHttp
  - [x] VuFindHarvest
- [x] grep vendor directory for "Zend" after replacing all known Zend dependencies in case of other references or secondary dependencies -- note: there are still some known issues here, but all addressable concerns have been addressed.
- [x] Fix or eliminate bootstrap.php files found in module-specific test folders.
- [x] Run full test suite
- [x] Document base requirement update to PHP 7.2 when merging
- [x] Update wiki when merging

### CODE REVIEW

**Comment by demiankatz** [comment]
Another detail of some note: the [ProxyManager](https://github.com/Ocramius/ProxyManager) library that we depend on has been upgraded for Laminas compatibility, but that version requires PHP 7.4+. It's going to be a while before VuFind raises its requirements that high, so we're going to have to live with the compatibility layer for some time (or else find a different solution to this need).

**Comment by xmorave2** [comment]
Just a note: ghislainf/zf2-whoops looks a bit old, do you think to use it does make sense to use something else, for example Ppito/laminas-whoops? 

https://github.com/Ppito/laminas-whoops

**Comment by demiankatz** [comment]
Good point, @xmorave2, that is definitely one of our older, less well maintained dependencies. I'll add it to the TODO list now, and I'll check out your recommendation next week when I'm back from WOLFcon.

I'm also going to add a TODO to grep the vendor directory for "Zend" so I can catch any outstanding Zend-specific dependencies after all the known ones are taken care of.

**Comment by EreMaijala** [comment]
Tested this with our VuFind. A quick check indicates that migration will be pretty smooth.

**Pull request merged**
