### PR TITLE
Page enhancements: Comparing Languages Against English

### PR DESCRIPTION
**Pull request by demiankatz**
Contributed by Karel Pavelka via [VUFIND-1453](https://vufind.org/jira/browse/VUFIND-1453).

Optional, undeveloped style recommendations from Chris:
- [x] Left align all text and cells
- [x] Move action buttons to end of text
- [x] Copy to clipboard button in pop-up.
- [x] Wait for #1795 copy button helper

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks again for sharing this, @dotek. I have made a few adjustments:
- Conforming to project style
- Adding more escaping (just to be safe)
- Moving more logic out of the view template and into the language helper (to keep business logic out of the view)
- Fixing some minor bugs

Please let me know what you think, and whether you have any further suggestions. I will merge with your approval, and following a review from @crhallberg.

**Comment by crhallberg** [comment]
I have a few style suggestions which might help the style and clarity of the interface:
- [x] Progress bar readability
- [x] Table cell alignment
- [x] Readonly textarea in pop-up
- [ ] Left align all text and cells
- [ ] Button order
- [ ] Copy to clipboard button in pop-up.

I've done the ones I think we really need (first three) here: https://github.com/crhallberg/vufind/tree/ch-vufind-1453

Here's what I propose the progress bars should look like:
image

**Comment by demiankatz** [comment]
Thanks for the progress, @crhallberg. I've merged your improvements here, since they seem reasonable to me. I've also updated this to match the current dev branch.

@dotek, sorry that it is has taken so long for us to get to this. Do you have any further thoughts/suggestions?

**Comment by crhallberg** [comment]
I still recommend these three changes which I didn't include in my PR:

- [ ]  Left align all text and cells
- [ ]  Button order
- [ ]  Copy to clipboard button in pop-up.

**Comment by demiankatz** [comment]
I'll take a look and weigh in with my opinions when time permits, but I suspect that I will agree with you, @crhallberg. Feel free to create a TODO list in the top-level comment if that would make this easier to keep track of.

**Comment by demiankatz** [comment]
@crhallberg, while we have not heard more from @dotek, I think at this point it's safe to move forward with your suggestions when time permits. (Or, if you feel those are optional and that you won't have time for them in the foreseeable future, we can merge this as-is as an incremental improvement). Please let me know how you would like to proceed!

**Comment by demiankatz** [comment]
@crhallberg, #1795 has been merged, so you're free to integrate the copy to clipboard control at your convenience!

**Comment by crhallberg** [comment]
Code has been updated to use the new copy to clipboard helper. I have a few reservations about the clipboard button template being wrapped in a paragraph tag but that's for another time.

image

**Comment by demiankatz** [comment]
Thanks for the finishing touches, @crhallberg; this looks great!

**Pull request merged**
